2016-04-12 08:50:40.848 [info] <0.7.0> Application lager started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:50:40.848 [info] <0.7.0> Application poolgirl started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:50:40.884 [info] <0.430.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.430.0>
2016-04-12 08:50:40.909 [info] <0.498.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.498.0>
2016-04-12 08:50:41.324 [error] <0.489.0> CRASH REPORT Process <0.489.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:50:41.324 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:50:41.468 [info] <0.608.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.608.0>
2016-04-12 08:50:41.471 [info] <0.7.0> Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:50:41.819 [info] <0.7.0> Application lager started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:50:41.819 [info] <0.7.0> Application poolgirl started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:50:41.908 [info] <0.99.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.99.0>
2016-04-12 08:50:42.115 [error] <0.155.0> gen_server <0.155.0> terminated with reason: killed
2016-04-12 08:50:42.118 [error] <0.665.0> gen_server <0.665.0> terminated with reason: killed
2016-04-12 08:50:42.115 [error] <0.155.0> CRASH REPORT Process <0.155.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:50:42.118 [error] <0.665.0> CRASH REPORT Process <0.665.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:50:42.117 [error] <0.90.0> CRASH REPORT Process <0.90.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:50:42.119 [error] <0.599.0> CRASH REPORT Process <0.599.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:50:42.119 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:50:42.184 [info] <0.735.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.735.0>
2016-04-12 08:50:42.491 [info] <0.7.0> Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:50:42.793 [error] <0.729.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): ** ERROR ** (ignoring core) ** FATAL ** A fallback is installed and Mnesia2 must be restarted. Forcing shutdown after mnesia2_down from 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'...

2016-04-12 08:50:42.794 [error] <0.730.0> Supervisor mnesia2_kernel_sup had child mnesia2_locker started with mnesia2_locker:start() at <0.733.0> exit with reason killed in context child_terminated
2016-04-12 08:50:42.794 [error] <0.730.0> Supervisor mnesia2_kernel_sup had child mnesia2_locker started with mnesia2_locker:start() at <0.733.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:50:42.797 [error] <0.728.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.730.0> exit with reason shutdown in context child_terminated
2016-04-12 08:50:42.797 [error] <0.728.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.730.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:50:42.117 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:50:42.187 [info] <0.215.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.215.0>
2016-04-12 08:50:42.203 [info] <0.7.0> Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:50:42.793 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:50:42.848 [info] <0.864.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.864.0>
2016-04-12 08:50:42.958 [info] <0.964.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.964.0>
2016-04-12 08:50:43.696 [error] <0.959.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.979.0> exit with reason killed in context child_terminated
2016-04-12 08:50:42.876 [info] <0.369.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.369.0>
2016-04-12 08:50:42.967 [info] <0.460.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.460.0>
2016-04-12 08:50:43.697 [warning] <0.6.0> lager_error_logger_h dropped 32 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:50:43.697 [error] <0.518.0> gen_server <0.518.0> terminated with reason: killed
2016-04-12 08:50:43.696 [error] <0.959.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.979.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:50:43.698 [error] <0.518.0> CRASH REPORT Process <0.518.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:50:43.698 [error] <0.955.0> CRASH REPORT Process <0.955.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:50:43.698 [error] <0.451.0> CRASH REPORT Process <0.451.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:50:43.698 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:50:43.768 [info] <0.549.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.549.0>
2016-04-12 08:50:43.778 [info] <0.7.0> Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:50:43.698 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:50:43.764 [info] <0.1087.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.1087.0>
2016-04-12 08:50:44.070 [info] <0.7.0> Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:50:44.207 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:50:44.220 [info] <0.1200.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.1200.0>
2016-04-12 08:50:44.227 [info] <0.7.0> Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:50:44.745 [error] <0.1237.0> gen_server <0.1237.0> terminated with reason: killed
2016-04-12 08:50:44.746 [error] <0.542.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.544.0> exit with reason killed in context child_terminated
2016-04-12 08:50:44.745 [error] <0.1237.0> CRASH REPORT Process <0.1237.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:50:44.746 [error] <0.1191.0> CRASH REPORT Process <0.1191.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:50:44.747 [error] <0.542.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.544.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:50:44.747 [error] <0.564.0> gen_server mnesia2_snmp_sup terminated with reason: killed
2016-04-12 08:50:44.747 [error] <0.564.0> CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:50:44.747 [error] <0.548.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-12 08:50:44.747 [error] <0.548.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:50:44.747 [error] <0.546.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-12 08:50:44.747 [error] <0.546.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:50:44.747 [error] <0.545.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-12 08:50:44.747 [error] <0.545.0> CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:50:44.746 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:50:44.813 [info] <0.1432.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.1432.0>
2016-04-12 08:50:45.027 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:50:45.053 [info] <0.1546.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.1546.0>
2016-04-12 08:50:45.057 [info] <0.7.0> Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:50:45.211 [error] <0.1537.0> CRASH REPORT Process <0.1537.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:50:44.749 [info] <0.7.0> Application mnesia2 exited with reason: shutdown
2016-04-12 08:50:44.840 [info] <0.764.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.764.0>
2016-04-12 08:50:45.026 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:50:45.060 [info] <0.863.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.863.0>
2016-04-12 08:50:45.069 [info] <0.7.0> Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:50:45.212 [error] <0.854.0> CRASH REPORT Process <0.854.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:50:45.212 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:50:45.275 [info] <0.1662.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.1662.0>
2016-04-12 08:50:45.212 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:50:45.293 [info] <0.964.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.964.0>
2016-04-12 08:50:45.915 [info] <0.1071.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.1071.0>
2016-04-12 08:50:46.115 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:50:46.115 [error] <0.1125.0> gen_server <0.1125.0> terminated with reason: killed
2016-04-12 08:50:45.909 [info] <0.1789.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.1789.0>
2016-04-12 08:50:46.119 [warning] <0.6.0> lager_error_logger_h dropped 10 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:50:46.119 [error] <0.1780.0> CRASH REPORT Process <0.1780.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:50:46.115 [error] <0.1125.0> CRASH REPORT Process <0.1125.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:50:46.116 [error] <0.1062.0> CRASH REPORT Process <0.1062.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:50:46.116 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:50:46.204 [info] <0.1170.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.1170.0>
2016-04-12 08:50:46.216 [info] <0.7.0> Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:50:46.373 [error] <0.1161.0> CRASH REPORT Process <0.1161.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:50:46.120 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:50:46.183 [info] <0.1920.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.1920.0>
2016-04-12 08:50:46.188 [info] <0.7.0> Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:50:46.375 [error] <0.1911.0> CRASH REPORT Process <0.1911.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:50:46.375 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:50:46.458 [info] <0.2053.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.2053.0>
2016-04-12 08:50:46.373 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:50:46.462 [info] <0.1271.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.1271.0>
2016-04-12 08:50:47.023 [error] <0.2044.0> CRASH REPORT Process <0.2044.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:50:47.024 [error] <0.1326.0> gen_server <0.1326.0> terminated with reason: killed
2016-04-12 08:50:47.024 [error] <0.1326.0> CRASH REPORT Process <0.1326.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:50:47.025 [error] <0.1262.0> CRASH REPORT Process <0.1262.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:50:47.025 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:50:47.101 [info] <0.1378.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.1378.0>
2016-04-12 08:50:47.104 [info] <0.7.0> Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:50:47.318 [error] <0.1432.0> gen_server <0.1432.0> terminated with reason: killed
2016-04-12 08:50:47.023 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:50:47.092 [info] <0.2194.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.2194.0>
2016-04-12 08:50:47.095 [info] <0.7.0> Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:50:47.319 [error] <0.2250.0> gen_server <0.2250.0> terminated with reason: killed
2016-04-12 08:50:47.318 [error] <0.1432.0> CRASH REPORT Process <0.1432.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:50:47.319 [error] <0.2250.0> CRASH REPORT Process <0.2250.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:50:47.320 [error] <0.2185.0> CRASH REPORT Process <0.2185.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:50:47.399 [info] <0.1465.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.1465.0>
2016-04-12 08:50:47.982 [info] <0.1579.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.1579.0>
2016-04-12 08:50:47.320 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:50:47.397 [info] <0.2325.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.2325.0>
2016-04-12 08:50:47.976 [info] <0.2457.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.2457.0>
2016-04-12 08:50:48.346 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:50:48.347 [error] <0.2452.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.2469.0> exit with reason killed in context child_terminated
2016-04-12 08:50:48.347 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:50:48.347 [error] <0.1633.0> gen_server <0.1633.0> terminated with reason: killed
2016-04-12 08:50:48.347 [error] <0.2452.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.2469.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:50:48.347 [error] <0.1633.0> CRASH REPORT Process <0.1633.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:50:48.353 [error] <0.2450.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.2452.0> exit with reason killed in context child_terminated
2016-04-12 08:50:48.353 [error] <0.2450.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.2452.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:50:48.347 [error] <0.1570.0> CRASH REPORT Process <0.1570.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:50:48.353 [error] <0.2448.0> CRASH REPORT Process <0.2448.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:50:48.347 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:50:48.425 [info] <0.1666.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.1666.0>
2016-04-12 08:50:48.437 [info] <0.7.0> Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:50:48.792 [error] <0.1660.0> Mnesia2('d523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'): ** ERROR ** mnesia2_event got unexpected event: {'EXIT',<0.1663.0>,killed}

2016-04-12 08:50:48.792 [error] <0.1659.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.1661.0> exit with reason killed in context child_terminated
2016-04-12 08:50:48.353 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:50:48.422 [info] <0.2580.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.2580.0>
2016-04-12 08:50:48.729 [info] <0.7.0> Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:50:49.042 [error] <0.2575.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.2594.0> exit with reason killed in context child_terminated
2016-04-12 08:50:49.042 [error] <0.2575.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.2594.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:50:49.043 [error] <0.2573.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.2575.0> exit with reason killed in context child_terminated
2016-04-12 08:50:49.043 [error] <0.2573.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.2575.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:50:49.043 [error] <0.2577.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-12 08:50:49.043 [error] <0.2577.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:50:49.043 [error] <0.2576.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-12 08:50:49.043 [error] <0.2576.0> CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:50:49.043 [error] <0.2579.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-12 08:50:49.043 [error] <0.2579.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:50:49.044 [info] <0.7.0> Application mnesia2 exited with reason: shutdown
2016-04-12 08:50:49.502 [info] <0.2710.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.2710.0>
2016-04-12 08:50:49.608 [info] <0.2804.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.2804.0>
2016-04-12 08:50:50.857 [info] <0.2914.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.2914.0>
2016-04-12 08:50:50.862 [info] <0.7.0> Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:50:52.120 [error] <0.2909.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.2925.0> exit with reason killed in context child_terminated
2016-04-12 08:50:52.121 [error] <0.2909.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.2925.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:50:52.122 [error] <0.2905.0> CRASH REPORT Process <0.2905.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:50:52.122 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:50:54.206 [info] <0.3020.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.3020.0>
2016-04-12 08:50:54.210 [info] <0.7.0> Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:50:54.213 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:50:54.220 [info] <0.3068.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.3068.0>
2016-04-12 08:50:54.226 [info] <0.3116.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.3116.0>
2016-04-12 08:50:56.315 [info] <0.3188.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.3188.0>
2016-04-12 08:50:56.319 [info] <0.7.0> Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:50:56.345 [error] <0.3179.0> CRASH REPORT Process <0.3179.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:50:56.345 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:50:58.384 [info] <0.3271.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.3271.0>
2016-04-12 08:50:58.388 [info] <0.7.0> Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:50:58.392 [info] <0.3265.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Restore aborted. mnesia2_config_backup:open_read["NonExisting.FILE"] -> {enoent,error}

2016-04-12 08:50:58.394 [info] <0.3265.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Restore aborted. mnesia2_config_backup:open_read["/home/travis/build/lrascao/mnesia2/logs/ct_run.test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12.2016-04-12_08.50.13/Mnesia2.test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12/LATEST.LOG"] -> badarg

2016-04-12 08:50:58.395 [error] <0.3307.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}}} ({error,{already_started,<0.3347.0>}})

2016-04-12 08:50:58.395 [error] <0.3311.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_11,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_11,shutdown]}}}} ({error,{already_started,<0.3347.0>}})

2016-04-12 08:50:58.395 [error] <0.3313.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_13,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_13,shutdown]}}}} ({error,{already_started,<0.3347.0>}})

2016-04-12 08:50:58.395 [error] <0.3312.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_12,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_12,shutdown]}}}} ({error,{already_started,<0.3347.0>}})

2016-04-12 08:50:58.396 [error] <0.3310.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_10,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_10,shutdown]}}}} ({error,{already_started,<0.3347.0>}})

2016-04-12 08:50:58.396 [error] <0.3315.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_15,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_15,shutdown]}}}} ({error,{already_started,<0.3347.0>}})

2016-04-12 08:50:58.396 [error] <0.3317.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_17,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_17,shutdown]}}}} ({error,{already_started,<0.3347.0>}})

2016-04-12 08:50:58.396 [error] <0.3316.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_16,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_16,shutdown]}}}} ({error,{already_started,<0.3347.0>}})

2016-04-12 08:51:00.481 [warning] <0.6.0> lager_error_logger_h dropped 15 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:51:00.482 [info] <0.3390.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): mnesia2_monitor starting: <0.3392.0>

2016-04-12 08:51:00.482 [info] <0.3390.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Mnesia2 debug level set to verbose
2016-04-12 08:51:00.483 [info] <0.3390.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): mnesia2_subscr starting: <0.3393.0>

2016-04-12 08:51:00.483 [info] <0.3390.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): mnesia2_locker starting: <0.3394.0>

2016-04-12 08:51:00.483 [info] <0.3390.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): mnesia2_recover starting: <0.3395.0>

2016-04-12 08:51:00.483 [info] <0.3390.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): mnesia2_tm starting: <0.3396.0>

2016-04-12 08:51:00.484 [info] <0.3390.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Schema initiated from: default

2016-04-12 08:51:00.484 [info] <0.3396.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.3396.0>
2016-04-12 08:51:00.484 [info] <0.3390.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): mnesia2_controller starting: <0.3399.0>

2016-04-12 08:51:00.485 [info] <0.3390.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): mnesia2_late_loader starting: <0.3400.0>

2016-04-12 08:51:00.486 [info] <0.3390.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Intend to load tables: []

2016-04-12 08:51:00.486 [info] <0.3390.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): mnesia2_tm_1 starting: <0.3402.0>

2016-04-12 08:51:00.486 [info] <0.3390.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): mnesia2_tm_2 starting: <0.3403.0>

2016-04-12 08:51:00.487 [info] <0.3390.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): mnesia2_tm_3 starting: <0.3404.0>

2016-04-12 08:51:00.487 [info] <0.3390.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): mnesia2_tm_4 starting: <0.3405.0>

2016-04-12 08:51:00.487 [info] <0.3390.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): mnesia2_tm_5 starting: <0.3406.0>

2016-04-12 08:51:00.487 [info] <0.3390.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): mnesia2_tm_6 starting: <0.3407.0>

2016-04-12 08:51:00.488 [info] <0.3390.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): mnesia2_tm_7 starting: <0.3408.0>

2016-04-12 08:51:00.488 [info] <0.3390.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): mnesia2_tm_8 starting: <0.3409.0>

2016-04-12 08:51:02.512 [warning] <0.6.0> lager_error_logger_h dropped 19 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:51:02.513 [info] <0.3446.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): mnesia2_monitor starting: <0.3448.0>

2016-04-12 08:51:02.513 [info] <0.3446.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Version: "1.0.0"

2016-04-12 08:51:02.513 [info] <0.3446.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env access_module: mnesia2

2016-04-12 08:51:02.514 [info] <0.3446.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env auto_repair: true

2016-04-12 08:51:02.514 [info] <0.3446.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env backup_module: mnesia2_backup

2016-04-12 08:51:02.514 [info] <0.3446.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env debug: debug

2016-04-12 08:51:02.515 [info] <0.3446.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12.2016-04-12_08.50.13/Mnesia2.test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12"

2016-04-12 08:51:02.515 [info] <0.3446.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env dump_disc_copies_at_startup: true

2016-04-12 08:51:02.516 [info] <0.3446.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env dump_log_load_regulation: false

2016-04-12 08:51:02.516 [info] <0.3446.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env dump_log_time_threshold: 180000

2016-04-12 08:51:02.517 [info] <0.3446.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env dump_log_update_in_place: true

2016-04-12 08:51:02.517 [info] <0.3446.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env dump_log_write_threshold: 1000

2016-04-12 08:51:02.518 [info] <0.3446.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env event_module: mnesia2_event

2016-04-12 08:51:02.518 [info] <0.3446.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env extra_db_nodes: []

2016-04-12 08:51:02.519 [info] <0.3446.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env ignore_fallback_at_startup: false

2016-04-12 08:51:02.519 [info] <0.3446.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env fallback_error_function: {mnesia2,lkill}

2016-04-12 08:51:02.520 [info] <0.3446.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env max_wait_for_decision: infinity

2016-04-12 08:51:02.524 [info] <0.3446.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env schema_location: opt_disc

2016-04-12 08:51:02.524 [info] <0.3446.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env core_dir: false

2016-04-12 08:51:02.525 [info] <0.3452.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.3452.0>
2016-04-12 08:51:02.526 [info] <0.3446.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env pid_sort_order: false

2016-04-12 08:51:04.559 [warning] <0.6.0> lager_error_logger_h dropped 45 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:51:04.559 [info] <0.3527.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): mnesia2_monitor starting: <0.3529.0>

2016-04-12 08:51:04.560 [info] <0.3527.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Version: "1.0.0"

2016-04-12 08:51:04.561 [info] <0.3527.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env access_module: mnesia2

2016-04-12 08:51:04.561 [info] <0.3527.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env auto_repair: true

2016-04-12 08:51:04.561 [info] <0.3527.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env backup_module: mnesia2_backup

2016-04-12 08:51:04.562 [info] <0.3527.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env debug: trace

2016-04-12 08:51:04.562 [info] <0.3527.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12.2016-04-12_08.50.13/Mnesia2.test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12"

2016-04-12 08:51:04.562 [info] <0.3527.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env dump_disc_copies_at_startup: true

2016-04-12 08:51:04.562 [info] <0.3527.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env dump_log_load_regulation: false

2016-04-12 08:51:04.563 [info] <0.3527.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env dump_log_time_threshold: 180000

2016-04-12 08:51:04.563 [info] <0.3527.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env dump_log_update_in_place: true

2016-04-12 08:51:04.564 [info] <0.3527.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env dump_log_write_threshold: 1000

2016-04-12 08:51:04.564 [info] <0.3527.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env event_module: mnesia2_event

2016-04-12 08:51:04.564 [info] <0.3527.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env extra_db_nodes: []

2016-04-12 08:51:04.564 [info] <0.3527.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env ignore_fallback_at_startup: false

2016-04-12 08:51:04.564 [info] <0.3527.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env fallback_error_function: {mnesia2,lkill}

2016-04-12 08:51:04.565 [info] <0.3527.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env max_wait_for_decision: infinity

2016-04-12 08:51:04.565 [info] <0.3527.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env schema_location: opt_disc

2016-04-12 08:51:04.565 [info] <0.3527.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env core_dir: false

2016-04-12 08:51:04.565 [info] <0.3527.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env pid_sort_order: false

2016-04-12 08:51:04.565 [info] <0.3527.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env no_table_loaders: 2

2016-04-12 08:51:04.565 [info] <0.3527.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env dc_dump_limit: 4

2016-04-12 08:51:04.566 [info] <0.3527.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env send_compressed: 0

2016-04-12 08:51:04.566 [info] <0.3527.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env send_max_packets: 20

2016-04-12 08:51:04.566 [info] <0.3527.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env send_max_transfer_size: 7500

2016-04-12 08:51:04.566 [info] <0.3527.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env async_dirty_buffer_size: 524288

2016-04-12 08:51:04.567 [info] <0.3527.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env async_dirty_max_buffer_file_size: 100000000

2016-04-12 08:51:04.567 [info] <0.3527.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env async_dirty_tx_backlog_threshold: 200000

2016-04-12 08:51:04.567 [info] <0.3527.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env async_dirty_buffer_min_runtime: 10000

2016-04-12 08:51:04.567 [info] <0.3527.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env async_dirty_buffer_drained_cutoff: 5

2016-04-12 08:51:04.567 [info] <0.3527.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Mnesia2 debug level set to trace
2016-04-12 08:51:04.568 [info] <0.3533.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.3533.0>
2016-04-12 08:51:04.569 [info] <0.3527.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): mnesia2_subscr starting: <0.3530.0>

2016-04-12 08:51:04.569 [info] <0.3527.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): mnesia2_locker starting: <0.3531.0>

2016-04-12 08:51:04.569 [info] <0.3527.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): mnesia2_recover starting: <0.3532.0>

2016-04-12 08:51:04.569 [info] <0.3527.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): mnesia2_tm starting: <0.3533.0>

2016-04-12 08:51:04.569 [info] <0.3527.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Schema initiated from: default

2016-04-12 08:51:04.569 [info] <0.3527.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): debug fun {mnesia2_tm,init} in ets mnesia2_debug does not exist, ignoring
2016-04-12 08:51:04.570 [info] <0.3527.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): mnesia2_controller starting: <0.3536.0>

2016-04-12 08:51:04.570 [info] <0.3527.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): mnesia2_late_loader starting: <0.3537.0>

2016-04-12 08:51:04.571 [info] <0.3527.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Intend to load tables: []

2016-04-12 08:51:06.597 [warning] <0.6.0> lager_error_logger_h dropped 41 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:51:06.597 [info] <0.3608.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): mnesia2_monitor starting: <0.3610.0>

2016-04-12 08:51:06.598 [info] <0.3608.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Version: "1.0.0"

2016-04-12 08:51:06.599 [info] <0.3608.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env access_module: mnesia2

2016-04-12 08:51:06.599 [info] <0.3608.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env auto_repair: true

2016-04-12 08:51:06.599 [info] <0.3608.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env backup_module: mnesia2_backup

2016-04-12 08:51:06.600 [info] <0.3608.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env debug: debug

2016-04-12 08:51:06.600 [info] <0.3608.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12.2016-04-12_08.50.13/Mnesia2.test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12"

2016-04-12 08:51:06.601 [info] <0.3608.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env dump_disc_copies_at_startup: true

2016-04-12 08:51:06.601 [info] <0.3614.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.3614.0>
2016-04-12 08:51:06.601 [info] <0.3608.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env dump_log_load_regulation: false

2016-04-12 08:51:06.601 [info] <0.3608.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env dump_log_time_threshold: 180000

2016-04-12 08:51:06.602 [info] <0.3608.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env dump_log_update_in_place: true

2016-04-12 08:51:06.602 [info] <0.3608.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env dump_log_write_threshold: 1000

2016-04-12 08:51:06.603 [info] <0.3608.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env event_module: mnesia2_event

2016-04-12 08:51:06.603 [info] <0.3608.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env extra_db_nodes: []

2016-04-12 08:51:08.627 [warning] <0.6.0> lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:51:08.629 [info] <0.3664.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.3664.0>
2016-04-12 08:51:08.632 [info] <0.7.0> Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:51:08.633 [error] <0.3655.0> CRASH REPORT Process <0.3655.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:51:08.633 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:51:10.727 [info] <0.3728.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.3728.0>
2016-04-12 08:51:10.730 [info] <0.7.0> Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:51:10.732 [error] <0.3719.0> CRASH REPORT Process <0.3719.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:51:10.732 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:51:11.839 [info] <0.3799.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.3799.0>
2016-04-12 08:51:11.842 [info] <0.7.0> Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:51:11.847 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:51:11.855 [info] <0.3860.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.3860.0>
2016-04-12 08:51:14.726 [error] <0.3854.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-12 08:51:21.676 [error] <0.3854.0> Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-12 08:51:26.926 [error] <0.3851.0> CRASH REPORT Process <0.3851.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:51:26.926 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:51:29.327 [info] <0.4382.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.4382.0>
2016-04-12 08:51:29.329 [info] <0.7.0> Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:51:35.351 [error] <0.4373.0> CRASH REPORT Process <0.4373.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:51:35.352 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:51:37.686 [info] <0.4482.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.4482.0>
2016-04-12 08:51:37.689 [info] <0.7.0> Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:51:38.848 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:51:40.987 [info] <0.4598.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.4598.0>
2016-04-12 08:51:40.992 [info] <0.7.0> Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:51:41.002 [error] <0.4593.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.4609.0> exit with reason killed in context child_terminated
2016-04-12 08:51:41.003 [error] <0.4593.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.4609.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:51:41.004 [error] <0.4589.0> CRASH REPORT Process <0.4589.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:51:41.004 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:51:43.046 [info] <0.4665.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.4665.0>
2016-04-12 08:51:43.050 [info] <0.7.0> Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:51:43.084 [error] <0.4656.0> CRASH REPORT Process <0.4656.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:51:43.084 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:51:45.214 [warning] <0.6.0> lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:51:45.229 [info] <0.1794.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.1794.0>
2016-04-12 08:51:45.240 [info] <0.7.0> Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:51:45.227 [info] <0.4757.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.4757.0>
2016-04-12 08:51:45.548 [info] <0.7.0> Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:51:46.549 [error] <0.1847.0> gen_server <0.1847.0> terminated with reason: killed
2016-04-12 08:51:46.549 [error] <0.1847.0> CRASH REPORT Process <0.1847.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:51:46.550 [error] <0.1785.0> CRASH REPORT Process <0.1785.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:51:46.550 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:51:48.584 [info] <0.1863.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.1863.0>
2016-04-12 08:51:48.589 [info] <0.7.0> Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:51:49.592 [error] <0.4750.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.4752.0> exit with reason killed in context child_terminated
2016-04-12 08:51:49.592 [error] <0.4750.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.4752.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:51:49.592 [error] <0.4753.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-12 08:51:49.592 [error] <0.4756.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-12 08:51:49.592 [error] <0.4756.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:51:49.596 [info] <0.7.0> Application mnesia2 exited with reason: shutdown
2016-04-12 08:51:50.661 [error] <0.1856.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.1858.0> exit with reason killed in context child_terminated
2016-04-12 08:51:50.661 [error] <0.1856.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.1858.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:51:50.661 [error] <0.1859.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-12 08:51:50.661 [error] <0.1859.0> CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:51:50.661 [error] <0.1862.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-12 08:51:50.661 [error] <0.1862.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:51:50.663 [info] <0.7.0> Application mnesia2 exited with reason: shutdown
2016-04-12 08:51:51.757 [info] <0.1946.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.1946.0>
2016-04-12 08:51:51.761 [info] <0.7.0> Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:51:51.762 [error] <0.1936.0> CRASH REPORT Process <0.1936.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:51:51.737 [info] <0.4864.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.4864.0>
2016-04-12 08:51:51.741 [info] <0.7.0> Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:51:51.763 [error] <0.4855.0> CRASH REPORT Process <0.4855.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:51:51.764 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:51:52.685 [info] <0.4939.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.4939.0>
2016-04-12 08:51:52.687 [info] <0.7.0> Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:51:51.762 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:51:57.199 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:51:57.276 [info] <0.5063.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.5063.0>
2016-04-12 08:51:57.282 [info] <0.7.0> Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:51:57.265 [info] <0.2015.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.2015.0>
2016-04-12 08:51:57.266 [info] <0.7.0> Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:52:08.890 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:52:08.893 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:52:10.072 [info] <0.2137.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.2137.0>
2016-04-12 08:52:10.090 [info] <0.7.0> Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:52:10.111 [error] <0.2189.0> gen_server <0.2189.0> terminated with reason: killed
2016-04-12 08:52:10.111 [error] <0.2189.0> CRASH REPORT Process <0.2189.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:10.111 [error] <0.2128.0> CRASH REPORT Process <0.2128.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:10.064 [info] <0.5194.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.5194.0>
2016-04-12 08:52:10.075 [info] <0.7.0> Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:52:10.133 [error] <0.5185.0> CRASH REPORT Process <0.5185.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:10.133 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:10.169 [info] <0.5282.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.5282.0>
2016-04-12 08:52:10.111 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:10.414 [info] <0.2225.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.2225.0>
2016-04-12 08:52:11.943 [warning] <0.6.0> lager_error_logger_h dropped 28 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:52:11.943 [error] <0.2220.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.2244.0> exit with reason killed in context child_terminated
2016-04-12 08:52:11.943 [error] <0.2220.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.2244.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:52:11.944 [error] <0.2216.0> CRASH REPORT Process <0.2216.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:11.944 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:13.038 [info] <0.2328.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.2328.0>
2016-04-12 08:52:13.050 [info] <0.7.0> Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:52:13.066 [error] <0.2341.0> gen_server <0.2341.0> terminated with reason: killed
2016-04-12 08:52:13.016 [warning] <0.6.0> lager_error_logger_h dropped 12 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:52:13.021 [info] <0.5405.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.5405.0>
2016-04-12 08:52:13.024 [info] <0.7.0> Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:52:13.067 [error] <0.5400.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.5416.0> exit with reason killed in context child_terminated
2016-04-12 08:52:13.067 [error] <0.5400.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.5416.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:52:13.066 [error] <0.2341.0> CRASH REPORT Process <0.2341.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:13.069 [error] <0.5398.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.5400.0> exit with reason killed in context child_terminated
2016-04-12 08:52:13.067 [error] <0.2319.0> CRASH REPORT Process <0.2319.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:13.069 [error] <0.5398.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.5400.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:52:13.069 [error] <0.5402.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-12 08:52:13.069 [error] <0.5402.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:13.067 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:15.196 [info] <0.2403.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.2403.0>
2016-04-12 08:52:15.203 [info] <0.7.0> Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:52:15.216 [error] <0.2415.0> gen_server <0.2415.0> terminated with reason: killed
2016-04-12 08:52:15.166 [warning] <0.6.0> lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:52:15.188 [info] <0.5516.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.5516.0>
2016-04-12 08:52:15.190 [info] <0.7.0> Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:52:15.217 [error] <0.5578.0> gen_server <0.5578.0> terminated with reason: killed
2016-04-12 08:52:15.217 [error] <0.5578.0> CRASH REPORT Process <0.5578.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:15.216 [error] <0.2415.0> CRASH REPORT Process <0.2415.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:15.218 [error] <0.5507.0> CRASH REPORT Process <0.5507.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:15.216 [error] <0.2394.0> CRASH REPORT Process <0.2394.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:15.218 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:15.217 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:17.242 [info] <0.2462.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.2462.0>
2016-04-12 08:52:17.243 [info] <0.7.0> Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:52:18.240 [info] <0.5596.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.5596.0>
2016-04-12 08:52:18.257 [info] <0.7.0> Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:52:18.294 [error] <0.5591.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.5613.0> exit with reason killed in context child_terminated
2016-04-12 08:52:18.294 [error] <0.5591.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.5613.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:52:18.296 [error] <0.5657.0> gen_server <0.5657.0> terminated with reason: killed
2016-04-12 08:52:18.296 [error] <0.5657.0> CRASH REPORT Process <0.5657.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:18.296 [error] <0.5587.0> CRASH REPORT Process <0.5587.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:18.296 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:19.718 [error] <0.2453.0> CRASH REPORT Process <0.2453.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:19.718 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:20.816 [info] <0.5721.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.5721.0>
2016-04-12 08:52:20.820 [info] <0.7.0> Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:52:21.226 [error] <0.5774.0> gen_server <0.5774.0> terminated with reason: killed
2016-04-12 08:52:20.824 [info] <0.2551.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.2551.0>
2016-04-12 08:52:20.829 [info] <0.7.0> Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:52:21.228 [error] <0.2602.0> gen_server <0.2602.0> terminated with reason: killed
2016-04-12 08:52:21.112 [info] <0.7.0> Application lager started on node 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:52:21.112 [info] <0.7.0> Application poolgirl started on node 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:52:21.149 [info] <0.101.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.101.0>
2016-04-12 08:52:21.171 [info] <0.7.0> Application mnesia2 started on node 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:52:21.232 [error] <0.92.0> CRASH REPORT Process <0.92.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:21.228 [error] <0.2602.0> CRASH REPORT Process <0.2602.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:21.226 [error] <0.5774.0> CRASH REPORT Process <0.5774.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:21.229 [error] <0.2564.0> gen_server <0.2564.0> terminated with reason: killed
2016-04-12 08:52:21.226 [error] <0.5766.0> gen_server <0.5766.0> terminated with reason: killed
2016-04-12 08:52:21.227 [error] <0.5766.0> CRASH REPORT Process <0.5766.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:21.229 [error] <0.2564.0> CRASH REPORT Process <0.2564.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:21.229 [error] <0.2542.0> CRASH REPORT Process <0.2542.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:21.228 [error] <0.5712.0> CRASH REPORT Process <0.5712.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:21.232 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:21.229 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:21.228 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:23.466 [info] <0.2632.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.2632.0>
2016-04-12 08:52:23.482 [info] <0.7.0> Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:52:23.487 [error] <0.2623.0> CRASH REPORT Process <0.2623.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:23.455 [info] <0.5816.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.5816.0>
2016-04-12 08:52:23.457 [info] <0.7.0> Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:52:23.488 [error] <0.5807.0> CRASH REPORT Process <0.5807.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:23.488 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:23.487 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:25.590 [info] <0.2702.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.2702.0>
2016-04-12 08:52:25.595 [info] <0.7.0> Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:52:25.622 [error] <0.2693.0> CRASH REPORT Process <0.2693.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:25.574 [info] <0.5910.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.5910.0>
2016-04-12 08:52:25.578 [info] <0.7.0> Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:52:25.620 [error] <0.5954.0> gen_server <0.5954.0> terminated with reason: killed
2016-04-12 08:52:25.620 [error] <0.5954.0> CRASH REPORT Process <0.5954.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:25.621 [error] <0.5901.0> CRASH REPORT Process <0.5901.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:25.621 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:25.622 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:27.896 [info] <0.2777.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.2777.0>
2016-04-12 08:52:27.900 [info] <0.7.0> Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:52:28.202 [error] <0.2830.0> gen_server <0.2830.0> terminated with reason: killed
2016-04-12 08:52:28.202 [error] <0.2830.0> CRASH REPORT Process <0.2830.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:28.203 [error] <0.2768.0> CRASH REPORT Process <0.2768.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:27.892 [info] <0.5996.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.5996.0>
2016-04-12 08:52:28.199 [info] <0.7.0> Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:52:28.203 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:29.234 [error] <0.5987.0> CRASH REPORT Process <0.5987.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:29.234 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:31.387 [info] <0.2848.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.2848.0>
2016-04-12 08:52:31.389 [info] <0.7.0> Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:52:37.825 [info] <0.6075.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.6075.0>
2016-04-12 08:52:37.844 [info] <0.7.0> Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:52:37.860 [error] <0.6138.0> gen_server <0.6138.0> terminated with reason: killed
2016-04-12 08:52:37.862 [error] <0.2917.0> gen_server <0.2917.0> terminated with reason: killed
2016-04-12 08:52:37.860 [error] <0.6138.0> CRASH REPORT Process <0.6138.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:37.861 [error] <0.6066.0> CRASH REPORT Process <0.6066.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:37.862 [error] <0.2917.0> CRASH REPORT Process <0.2917.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:37.863 [error] <0.2839.0> CRASH REPORT Process <0.2839.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:37.861 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:37.863 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:39.090 [info] <0.2947.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.2947.0>
2016-04-12 08:52:39.102 [info] <0.7.0> Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:52:39.177 [error] <0.3010.0> gen_server <0.3010.0> terminated with reason: killed
2016-04-12 08:52:39.177 [error] <0.3010.0> CRASH REPORT Process <0.3010.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:39.177 [error] <0.2999.0> gen_server <0.2999.0> terminated with reason: killed
2016-04-12 08:52:39.177 [error] <0.2999.0> CRASH REPORT Process <0.2999.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:39.177 [error] <0.2938.0> CRASH REPORT Process <0.2938.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:39.068 [info] <0.6185.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.6185.0>
2016-04-12 08:52:39.071 [info] <0.7.0> Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:52:39.253 [error] <0.6272.0> gen_server <0.6272.0> terminated with reason: killed
2016-04-12 08:52:39.253 [error] <0.6272.0> CRASH REPORT Process <0.6272.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:39.253 [error] <0.6249.0> gen_server <0.6249.0> terminated with reason: killed
2016-04-12 08:52:39.253 [error] <0.6249.0> CRASH REPORT Process <0.6249.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:39.254 [error] <0.6288.0> gen_server <0.6288.0> terminated with reason: killed
2016-04-12 08:52:39.254 [error] <0.6288.0> CRASH REPORT Process <0.6288.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:39.255 [error] <0.6176.0> CRASH REPORT Process <0.6176.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:39.113 [info] <0.191.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.191.0>
2016-04-12 08:52:39.118 [info] <0.7.0> Application mnesia2 started on node 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:52:39.274 [error] <0.274.0> gen_server <0.274.0> terminated with reason: killed
2016-04-12 08:52:39.274 [error] <0.274.0> CRASH REPORT Process <0.274.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:39.275 [error] <0.182.0> CRASH REPORT Process <0.182.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:39.255 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:39.362 [info] <0.6307.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.6307.0>
2016-04-12 08:52:39.177 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:39.218 [info] <0.3038.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.3038.0>
2016-04-12 08:52:39.330 [info] <0.3133.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.3133.0>
2016-04-12 08:52:39.275 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:39.373 [info] <0.295.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.295.0>
2016-04-12 08:52:39.381 [info] <0.7.0> Application mnesia2 started on node 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:52:40.211 [error] <0.368.0> gen_server <0.368.0> terminated with reason: killed
2016-04-12 08:52:40.212 [error] <0.368.0> CRASH REPORT Process <0.368.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:40.212 [error] <0.357.0> gen_server <0.357.0> terminated with reason: killed
2016-04-12 08:52:40.213 [error] <0.357.0> CRASH REPORT Process <0.357.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:40.223 [error] <0.286.0> CRASH REPORT Process <0.286.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:40.223 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:40.246 [info] <0.392.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.392.0>
2016-04-12 08:52:40.248 [info] <0.7.0> Application mnesia2 started on node 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:52:42.312 [warning] <0.6.0> lager_error_logger_h dropped 4 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:52:42.312 [error] <0.6405.0> gen_server <0.6405.0> terminated with reason: killed
2016-04-12 08:52:42.312 [error] <0.6405.0> CRASH REPORT Process <0.6405.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:42.313 [error] <0.6377.0> gen_server <0.6377.0> terminated with reason: killed
2016-04-12 08:52:42.313 [error] <0.6377.0> CRASH REPORT Process <0.6377.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:42.315 [error] <0.6298.0> CRASH REPORT Process <0.6298.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:42.334 [warning] <0.6.0> lager_error_logger_h dropped 25 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:52:42.334 [error] <0.3226.0> gen_server <0.3226.0> terminated with reason: killed
2016-04-12 08:52:42.334 [error] <0.3226.0> CRASH REPORT Process <0.3226.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:42.335 [error] <0.3124.0> CRASH REPORT Process <0.3124.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:42.358 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:52:42.397 [info] <0.498.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.498.0>
2016-04-12 08:52:42.398 [info] <0.7.0> Application mnesia2 started on node 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:52:42.980 [error] <0.489.0> CRASH REPORT Process <0.489.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:42.315 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:42.432 [info] <0.6424.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.6424.0>
2016-04-12 08:52:42.470 [info] <0.7.0> Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:52:43.225 [error] <0.6517.0> gen_server <0.6517.0> terminated with reason: killed
2016-04-12 08:52:43.225 [error] <0.6517.0> CRASH REPORT Process <0.6517.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:43.226 [error] <0.6415.0> CRASH REPORT Process <0.6415.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:42.335 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:42.434 [info] <0.3247.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.3247.0>
2016-04-12 08:52:42.448 [info] <0.7.0> Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:52:43.246 [error] <0.3335.0> gen_server <0.3335.0> terminated with reason: killed
2016-04-12 08:52:43.247 [error] <0.3335.0> CRASH REPORT Process <0.3335.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:43.247 [error] <0.3238.0> CRASH REPORT Process <0.3238.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:43.226 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:43.247 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:42.981 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:43.012 [info] <0.596.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.596.0>
2016-04-12 08:52:43.013 [info] <0.7.0> Application mnesia2 started on node 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:52:43.289 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:52:43.308 [info] <0.697.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.697.0>
2016-04-12 08:52:43.366 [info] <0.3356.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.3356.0>
2016-04-12 08:52:43.372 [info] <0.7.0> Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:52:44.186 [error] <0.3416.0> gen_server <0.3416.0> terminated with reason: killed
2016-04-12 08:52:44.186 [error] <0.3416.0> CRASH REPORT Process <0.3416.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:44.187 [error] <0.3428.0> gen_server <0.3428.0> terminated with reason: killed
2016-04-12 08:52:44.187 [error] <0.3428.0> CRASH REPORT Process <0.3428.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:44.187 [error] <0.3347.0> CRASH REPORT Process <0.3347.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:44.187 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:44.255 [info] <0.3451.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.3451.0>
2016-04-12 08:52:44.267 [info] <0.7.0> Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:52:44.294 [error] <0.3464.0> gen_server <0.3464.0> terminated with reason: killed
2016-04-12 08:52:44.294 [error] <0.3464.0> CRASH REPORT Process <0.3464.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:44.294 [error] <0.3482.0> gen_server <0.3482.0> terminated with reason: killed
2016-04-12 08:52:44.295 [error] <0.3482.0> CRASH REPORT Process <0.3482.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:43.340 [info] <0.6534.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.6534.0>
2016-04-12 08:52:43.654 [info] <0.7.0> Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:52:45.316 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:52:45.320 [info] <0.3529.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.3529.0>
2016-04-12 08:52:45.337 [info] <0.7.0> Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:52:45.406 [error] <0.3520.0> CRASH REPORT Process <0.3520.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:45.407 [error] <0.6601.0> gen_server <0.6601.0> terminated with reason: killed
2016-04-12 08:52:45.407 [error] <0.822.0> gen_server <0.822.0> terminated with reason: killed
2016-04-12 08:52:45.407 [error] <0.6601.0> CRASH REPORT Process <0.6601.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:45.407 [error] <0.822.0> CRASH REPORT Process <0.822.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:45.408 [error] <0.6525.0> CRASH REPORT Process <0.6525.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:45.409 [error] <0.688.0> CRASH REPORT Process <0.688.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:45.406 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:45.502 [info] <0.3608.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.3608.0>
2016-04-12 08:52:45.607 [info] <0.3702.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.3702.0>
2016-04-12 08:52:45.729 [info] <0.3792.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.3792.0>
2016-04-12 08:52:45.809 [info] <0.3892.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.3892.0>
2016-04-12 08:52:46.391 [warning] <0.6.0> lager_error_logger_h dropped 48 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:52:46.391 [error] <0.3947.0> gen_server <0.3947.0> terminated with reason: killed
2016-04-12 08:52:46.391 [error] <0.3947.0> CRASH REPORT Process <0.3947.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:46.393 [error] <0.3883.0> CRASH REPORT Process <0.3883.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:45.408 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:45.481 [info] <0.6680.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.6680.0>
2016-04-12 08:52:45.484 [info] <0.7.0> Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:52:45.791 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:52:46.335 [info] <0.6793.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.6793.0>
2016-04-12 08:52:46.362 [info] <0.7.0> Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:52:46.389 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:52:45.409 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:46.393 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:46.957 [info] <0.3974.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.3974.0>
2016-04-12 08:52:47.010 [info] <0.7.0> Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:52:46.440 [info] <0.6876.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.6876.0>
2016-04-12 08:52:47.510 [error] <0.6867.0> CRASH REPORT Process <0.6867.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:47.508 [error] <0.4025.0> gen_server <0.4025.0> terminated with reason: killed
2016-04-12 08:52:47.508 [error] <0.4025.0> CRASH REPORT Process <0.4025.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:47.509 [error] <0.3965.0> CRASH REPORT Process <0.3965.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:47.618 [info] <0.849.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.849.0>
2016-04-12 08:52:47.960 [info] <0.7.0> Application mnesia2 started on node 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:52:48.051 [error] <0.913.0> gen_server <0.913.0> terminated with reason: killed
2016-04-12 08:52:47.510 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:47.597 [info] <0.6977.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.6977.0>
2016-04-12 08:52:47.599 [info] <0.7.0> Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:52:48.050 [error] <0.7041.0> gen_server <0.7041.0> terminated with reason: killed
2016-04-12 08:52:47.509 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:47.656 [info] <0.4067.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.4067.0>
2016-04-12 08:52:47.662 [info] <0.7.0> Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:52:48.053 [error] <0.4120.0> gen_server <0.4120.0> terminated with reason: killed
2016-04-12 08:52:48.050 [error] <0.7041.0> CRASH REPORT Process <0.7041.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:48.050 [error] <0.7034.0> gen_server <0.7034.0> terminated with reason: killed
2016-04-12 08:52:48.053 [error] <0.4120.0> CRASH REPORT Process <0.4120.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:48.051 [error] <0.913.0> CRASH REPORT Process <0.913.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:48.050 [error] <0.7034.0> CRASH REPORT Process <0.7034.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:48.054 [error] <0.4057.0> CRASH REPORT Process <0.4057.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:48.053 [error] <0.840.0> CRASH REPORT Process <0.840.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:48.052 [error] <0.6968.0> CRASH REPORT Process <0.6968.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:48.054 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:48.086 [info] <0.4157.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.4157.0>
2016-04-12 08:52:48.088 [info] <0.7.0> Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:52:48.158 [error] <0.4212.0> gen_server <0.4212.0> terminated with reason: killed
2016-04-12 08:52:48.054 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:48.084 [info] <0.954.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.954.0>
2016-04-12 08:52:48.086 [info] <0.7.0> Application mnesia2 started on node 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:52:48.158 [error] <0.1003.0> gen_server <0.1003.0> terminated with reason: killed
2016-04-12 08:52:48.053 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:48.124 [info] <0.7089.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.7089.0>
2016-04-12 08:52:48.135 [info] <0.7.0> Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:52:48.160 [error] <0.7157.0> gen_server <0.7157.0> terminated with reason: killed
2016-04-12 08:52:48.161 [error] <0.7157.0> CRASH REPORT Process <0.7157.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:48.161 [error] <0.7128.0> gen_server <0.7128.0> terminated with reason: killed
2016-04-12 08:52:48.162 [error] <0.7128.0> CRASH REPORT Process <0.7128.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:48.158 [error] <0.1003.0> CRASH REPORT Process <0.1003.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:48.158 [error] <0.4212.0> CRASH REPORT Process <0.4212.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:48.161 [error] <0.4148.0> CRASH REPORT Process <0.4148.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:48.158 [error] <0.1012.0> gen_server <0.1012.0> terminated with reason: killed
2016-04-12 08:52:48.158 [error] <0.1012.0> CRASH REPORT Process <0.1012.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:48.228 [info] <0.7181.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.7181.0>
2016-04-12 08:52:48.161 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:48.206 [info] <0.4235.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.4235.0>
2016-04-12 08:52:48.206 [info] <0.1031.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.1031.0>
2016-04-12 08:52:58.244 [error] <0.7174.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at undefined exit with reason killed in context start_error
2016-04-12 08:52:58.244 [error] <0.7177.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-12 08:52:58.244 [error] <0.7180.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-12 08:52:58.244 [error] <0.7180.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:58.244 [error] <0.7200.0> gen_server mnesia2_snmp_sup terminated with reason: killed
2016-04-12 08:52:58.244 [error] <0.7200.0> CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:58.244 [error] <0.7178.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-12 08:52:58.244 [error] <0.7178.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:58.244 [error] <0.7172.0> CRASH REPORT Process <0.7172.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}} in application_master:init/4 line 133
2016-04-12 08:52:58.244 [info] <0.7.0> Application mnesia2 exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}}
2016-04-12 08:52:58.244 [error] <0.7177.0> CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:58.344 [error] <0.4279.0> gen_server <0.4279.0> terminated with reason: killed
2016-04-12 08:52:58.346 [warning] <0.6.0> lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:52:58.346 [error] <0.1026.0> Supervisor mnesia2_kernel_sup had child mnesia2_controller started with mnesia2_controller:start() at <0.1034.0> exit with reason killed in context child_terminated
2016-04-12 08:52:58.344 [error] <0.4279.0> CRASH REPORT Process <0.4279.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:58.345 [error] <0.4226.0> CRASH REPORT Process <0.4226.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:58.347 [error] <0.1026.0> Supervisor mnesia2_kernel_sup had child mnesia2_controller started with mnesia2_controller:start() at <0.1034.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:52:58.347 [error] <0.1080.0> gen_server <0.1080.0> terminated with reason: killed
2016-04-12 08:52:58.347 [error] <0.1080.0> CRASH REPORT Process <0.1080.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-12 08:52:58.347 [error] <0.1022.0> CRASH REPORT Process <0.1022.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:58.345 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:58.347 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:53:01.091 [info] <0.7290.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.7290.0>
2016-04-12 08:53:01.094 [info] <0.7.0> Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:53:05.491 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:53:05.653 [info] <0.7426.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.7426.0>
2016-04-12 08:53:05.974 [info] <0.7.0> Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:53:05.654 [info] <0.4326.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.4326.0>
2016-04-12 08:53:05.695 [info] <0.7.0> Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:53:05.656 [info] <0.1127.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.1127.0>
2016-04-12 08:53:05.681 [info] <0.7.0> Application mnesia2 started on node 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:53:12.072 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:53:12.245 [info] <0.1242.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.1242.0>
2016-04-12 08:53:12.550 [info] <0.7.0> Application mnesia2 started on node 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:53:12.080 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:53:12.217 [info] <0.7555.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.7555.0>
2016-04-12 08:53:12.220 [info] <0.7.0> Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:53:12.103 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:53:12.248 [info] <0.4442.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.4442.0>
2016-04-12 08:53:12.265 [info] <0.7.0> Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:53:18.681 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:53:18.828 [info] <0.7684.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.7684.0>
2016-04-12 08:53:18.831 [info] <0.7.0> Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:53:18.680 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:53:18.872 [info] <0.4557.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.4557.0>
2016-04-12 08:53:18.888 [info] <0.7.0> Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:53:18.674 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:53:18.842 [info] <0.1358.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.1358.0>
2016-04-12 08:53:19.148 [info] <0.7.0> Application mnesia2 started on node 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:53:41.700 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:53:41.740 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:53:41.740 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:53:43.210 [info] <0.2484.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.2484.0>
2016-04-12 08:53:43.515 [info] <0.7.0> Application mnesia2 started on node 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:53:43.213 [info] <0.8823.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.8823.0>
2016-04-12 08:53:43.230 [info] <0.7.0> Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:53:43.212 [info] <0.5680.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.5680.0>
2016-04-12 08:53:43.233 [info] <0.7.0> Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:53:49.925 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:53:50.095 [info] <0.8960.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.8960.0>
2016-04-12 08:53:50.099 [info] <0.7.0> Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:53:49.948 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:53:50.123 [info] <0.2610.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.2610.0>
2016-04-12 08:53:50.138 [info] <0.7.0> Application mnesia2 started on node 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:53:49.961 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:53:50.102 [info] <0.5806.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.5806.0>
2016-04-12 08:53:50.423 [info] <0.7.0> Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:53:56.828 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:53:57.003 [info] <0.4079.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.4079.0>
2016-04-12 08:53:57.027 [info] <0.7.0> Application mnesia2 started on node 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:53:56.830 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:53:56.997 [info] <0.10441.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.10441.0>
2016-04-12 08:53:57.000 [info] <0.7.0> Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:53:56.833 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:53:57.009 [info] <0.7278.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.7278.0>
2016-04-12 08:53:57.050 [info] <0.7.0> Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:54:03.380 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:54:03.557 [info] <0.7625.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.7625.0>
2016-04-12 08:54:03.607 [info] <0.7.0> Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:54:03.408 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:54:03.536 [info] <0.12164.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.12164.0>
2016-04-12 08:54:03.538 [info] <0.7.0> Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:54:03.409 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:54:03.567 [info] <0.5337.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.5337.0>
2016-04-12 08:54:03.575 [info] <0.7.0> Application mnesia2 started on node 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:54:09.787 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:54:09.951 [info] <0.5449.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.5449.0>
2016-04-12 08:54:10.263 [info] <0.7.0> Application mnesia2 started on node 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:54:09.798 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:54:09.948 [info] <0.12294.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.12294.0>
2016-04-12 08:54:10.254 [info] <0.7.0> Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:54:09.818 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:54:09.976 [info] <0.8420.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.8420.0>
2016-04-12 08:54:09.982 [info] <0.7.0> Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
2016-04-12 08:54:16.520 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:54:16.524 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:54:16.526 [info] <0.7.0> Application mnesia2 exited with reason: stopped
