--- Test run on 2016/04/10 22:34:15 ---
Converting "/home/travis/build/lrascao/mnesia2/." to "/home/travis/build/lrascao/mnesia2" and re-inserting with add_patha/1


Common Test v1.11.1 starting (cwd is /home/travis/build/lrascao/mnesia2)


Common Test: Running make in test directories...
Recompile: mnesia2_extra_light_SUITE
Recompile: ts_install_cth
ts_install_cth.erl:247: Warning: erlang:now/0: Deprecated BIF. See the "Time and Time Correction in Erlang" chapter of the ERTS User's Guide for more information.
Recompile: mt
Recompile: mnesia2_trans_access_test
Recompile: mnesia2_tpcb
Recompile: mnesia2_test_lib
Recompile: mnesia2_schema_recovery_test
mnesia2_schema_recovery_test.erl:261: Warning: variable 'Bad' is unused
Recompile: mnesia2_registry_test
Recompile: mnesia2_recovery_test
mnesia2_recovery_test.erl:1571: Warning: variable 'Config' is unused
Recompile: mnesia2_qlc_test
Recompile: mnesia2_nice_coverage_test
Recompile: mnesia2_meter
Recompile: mnesia2_measure_test
Recompile: mnesia2_majority_test
Recompile: mnesia2_isolation_test
Recompile: mnesia2_install_test
Recompile: mnesia2_inconsistent_database_test
Recompile: mnesia2_frag_test
Recompile: mnesia2_frag_hash_test
Recompile: mnesia2_examples_test
Recompile: mnesia2_evil_coverage_test
Recompile: mnesia2_evil_backup
Recompile: mnesia2_durability_test
Recompile: mnesia2_dirty_access_test
Recompile: mnesia2_dbn_meters
Recompile: mnesia2_cost
Recompile: mnesia2_consistency_test
Recompile: mnesia2_config_test
Recompile: mnesia2_config_event
Recompile: mnesia2_config_backup
Recompile: mnesia2_atomicity_test

CWD set to: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15.2016-04-10_22.34.16"

TEST INFO: 1 test(s), 52 case(s) in 1 suite(s)

Cover compiling 'mnesia2' (32 files) - this may take some time... done

Testing lrascao.mnesia2.mnesia2_extra_light_SUITE: Starting test, 52 test cases

----------------------------------------------------
2016-04-10 22:34:35.943
starting test group: extra_light


----------------------------------------------------
2016-04-10 22:34:35.968
starting test group: install


----------------------------------------------------
2016-04-10 22:34:36.046
starting test case: silly_durability

22:34:36.123 [info] Application lager started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:34:36.123 [info] Application poolgirl started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:34:36.145 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.495.0>
22:34:36.163 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.563.0>

----------------------------------------------------
2016-04-10 22:34:36.167
ending test case: silly_durability


----------------------------------------------------
2016-04-10 22:34:36.192
starting test case: silly_move

22:34:36.675 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.673.0>
22:34:36.884 [info] Application lager started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:34:36.884 [info] Application poolgirl started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:34:36.935 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.100.0>

----------------------------------------------------
2016-04-10 22:34:37.084
ending test case: silly_move


----------------------------------------------------
2016-04-10 22:34:37.109
starting test case: silly_upgrade

22:34:37.113 [error] gen_server mnesia2_recover terminated with reason: killed
22:34:37.113 [error] CRASH REPORT Process <0.664.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:34:37.113 [info] Application mnesia2 exited with reason: killed
22:34:37.113 [error] CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:34:37.113 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.95.0> exit with reason killed in context child_terminated
22:34:37.113 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.95.0> exit with reason reached_max_restart_intensity in context shutdown
22:34:37.113 [error] gen_server mnesia2_subscr terminated with reason: killed
22:34:37.113 [error] CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:34:37.113 [error] gen_server mnesia2_monitor terminated with reason: killed
22:34:37.113 [info] Application mnesia2 exited with reason: shutdown
22:34:37.157 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.800.0>
22:34:37.160 [info] Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:34:37.161 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.216.0>
22:34:37.329 [error] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): ** ERROR ** (ignoring core) ** FATAL ** A fallback is installed and Mnesia2 must be restarted. Forcing shutdown after mnesia2_down from 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'...

22:34:37.329 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_locker:start() at <0.798.0> exit with reason killed in context child_terminated
22:34:37.329 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_locker:start() at <0.798.0> exit with reason reached_max_restart_intensity in context shutdown
22:34:37.331 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.795.0> exit with reason shutdown in context child_terminated
22:34:37.370 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.928.0>
22:34:37.376 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.369.0>
22:34:37.437 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.1028.0>
22:34:37.457 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.459.0>

----------------------------------------------------
2016-04-10 22:34:37.975
ending test case: silly_upgrade


----------------------------------------------------
2016-04-10 22:34:38.053
ending test group: install


----------------------------------------------------
2016-04-10 22:34:38.079
starting test group: nice


----------------------------------------------------
2016-04-10 22:34:38.156
starting test case: nice

22:34:38.158 [warning] lager_error_logger_h dropped 7 messages in the last second that exceeded the limit of 50 messages/sec
22:34:38.159 [warning] lager_error_logger_h dropped 41 messages in the last second that exceeded the limit of 50 messages/sec
22:34:38.158 [error] gen_server <0.1089.0> terminated with reason: killed
22:34:38.159 [error] CRASH REPORT Process <0.450.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:34:38.159 [info] Application mnesia2 exited with reason: killed
22:34:38.158 [error] CRASH REPORT Process <0.1089.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:34:38.160 [error] CRASH REPORT Process <0.1019.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:34:38.160 [info] Application mnesia2 exited with reason: killed
22:34:38.208 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.1151.0>
22:34:38.210 [info] Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:34:38.213 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.548.0>
22:34:38.216 [info] Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:34:38.305 [info] Application mnesia2 exited with reason: stopped
22:34:38.320 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.1263.0>

----------------------------------------------------
2016-04-10 22:34:38.494
ending test case: nice


----------------------------------------------------
2016-04-10 22:34:38.574
ending test group: nice


----------------------------------------------------
2016-04-10 22:34:38.600
starting test group: qlc


----------------------------------------------------
2016-04-10 22:34:38.704
starting test case: dirty_nice_ram_copies

22:34:38.706 [error] gen_server <0.661.0> terminated with reason: killed
22:34:38.706 [error] CRASH REPORT Process <0.661.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:34:38.707 [error] CRASH REPORT Process <0.539.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:34:38.707 [info] Application mnesia2 exited with reason: killed
22:34:38.773 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.1495.0>
22:34:38.778 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.762.0>

----------------------------------------------------
2016-04-10 22:34:38.867
ending test case: dirty_nice_ram_copies


----------------------------------------------------
2016-04-10 22:34:38.895
starting test case: dirty_nice_disc_copies

22:34:38.966 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.1609.0>
22:34:38.971 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.861.0>

----------------------------------------------------
2016-04-10 22:34:39.043
ending test case: dirty_nice_disc_copies


----------------------------------------------------
2016-04-10 22:34:39.070
starting test case: dirty_nice_disc_only_copies

22:34:39.072 [warning] lager_error_logger_h dropped 35 messages in the last second that exceeded the limit of 50 messages/sec
22:34:39.072 [warning] lager_error_logger_h dropped 8 messages in the last second that exceeded the limit of 50 messages/sec
22:34:39.072 [error] gen_server <0.1665.0> terminated with reason: killed
22:34:39.072 [error] gen_server mnesia2_subscr terminated with reason: killed
22:34:39.072 [error] CRASH REPORT Process <0.1665.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:34:39.072 [error] CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:34:39.073 [error] CRASH REPORT Process <0.1600.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:34:39.073 [info] Application mnesia2 exited with reason: killed
22:34:39.072 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.856.0> exit with reason killed in context child_terminated
22:34:39.072 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.856.0> exit with reason reached_max_restart_intensity in context shutdown
22:34:39.072 [error] gen_server mnesia2_monitor terminated with reason: killed
22:34:39.072 [error] gen_server mnesia2_recover terminated with reason: killed
22:34:39.072 [error] CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:34:39.073 [error] CRASH REPORT Process <0.852.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:34:39.073 [info] Application mnesia2 exited with reason: killed
22:34:39.133 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.1726.0>
22:34:39.135 [info] Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:34:39.175 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.962.0>

----------------------------------------------------
2016-04-10 22:34:39.279
ending test case: dirty_nice_disc_only_copies


----------------------------------------------------
2016-04-10 22:34:39.368
starting test case: trans_nice_ram_copies

22:34:39.372 [error] CRASH REPORT Process <0.1717.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:34:39.372 [info] Application mnesia2 exited with reason: killed
22:34:39.437 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.1852.0>
22:34:39.451 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.1068.0>

----------------------------------------------------
2016-04-10 22:34:39.548
ending test case: trans_nice_ram_copies


----------------------------------------------------
2016-04-10 22:34:39.588
starting test case: trans_nice_disc_copies

22:34:39.661 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.1983.0>
22:34:39.668 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.1167.0>

----------------------------------------------------
2016-04-10 22:34:39.760
ending test case: trans_nice_disc_copies


----------------------------------------------------
2016-04-10 22:34:39.800
starting test case: trans_nice_disc_only_copies

22:34:39.869 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.1268.0>
22:34:39.870 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.2116.0>
22:34:40.172 [warning] lager_error_logger_h dropped 7 messages in the last second that exceeded the limit of 50 messages/sec
22:34:40.174 [info] Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'

----------------------------------------------------
2016-04-10 22:34:40.306
ending test case: trans_nice_disc_only_copies


----------------------------------------------------
2016-04-10 22:34:40.357
starting test case: atomic_eval

22:34:40.360 [warning] lager_error_logger_h dropped 8 messages in the last second that exceeded the limit of 50 messages/sec
22:34:40.360 [error] gen_server <0.2169.0> terminated with reason: killed
22:34:40.359 [error] gen_server <0.1320.0> terminated with reason: killed
22:34:40.360 [error] CRASH REPORT Process <0.2169.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:34:40.359 [error] CRASH REPORT Process <0.1320.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:34:40.360 [error] CRASH REPORT Process <0.2107.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:34:40.360 [info] Application mnesia2 exited with reason: killed
22:34:40.360 [error] CRASH REPORT Process <0.1259.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:34:40.360 [info] Application mnesia2 exited with reason: killed
22:34:40.421 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.2255.0>
22:34:40.424 [info] Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:34:40.427 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.1377.0>

----------------------------------------------------
2016-04-10 22:34:40.553
ending test case: atomic_eval


----------------------------------------------------
2016-04-10 22:34:40.630
starting test case: frag

22:34:40.632 [error] gen_server <0.2311.0> terminated with reason: killed
22:34:40.632 [error] CRASH REPORT Process <0.2311.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:34:40.705 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.2386.0>
22:34:40.708 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.1464.0>
22:34:41.010 [info] Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'

----------------------------------------------------
2016-04-10 22:34:41.108
ending test case: frag


----------------------------------------------------
2016-04-10 22:34:41.143
starting test case: info

22:34:41.145 [warning] lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
22:34:41.145 [error] gen_server <0.1517.0> terminated with reason: killed
22:34:41.147 [error] CRASH REPORT Process <0.2377.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:34:41.147 [info] Application mnesia2 exited with reason: killed
22:34:41.145 [error] CRASH REPORT Process <0.1517.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:34:41.145 [error] CRASH REPORT Process <0.1455.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:34:41.145 [info] Application mnesia2 exited with reason: killed
22:34:41.199 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.2519.0>
22:34:41.217 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.1577.0>
22:34:41.221 [info] Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'

----------------------------------------------------
2016-04-10 22:34:41.307
ending test case: info


----------------------------------------------------
2016-04-10 22:34:41.333
starting test case: mnesia2_down

22:34:41.336 [error] CRASH REPORT Process <0.1568.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:34:41.336 [info] Application mnesia2 exited with reason: killed
22:34:41.393 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.2642.0>
22:34:41.397 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.1664.0>
---> Participant transactions <--- 
---> Coordinator transactions <---
Tid: 10 (owned by <0.2719.0>) 

----------------------------------------------------
2016-04-10 22:34:41.471
ending test case: mnesia2_down


----------------------------------------------------
2016-04-10 22:34:41.564
ending test group: qlc


----------------------------------------------------
2016-04-10 22:34:41.590
starting test group: registry


----------------------------------------------------
2016-04-10 22:34:41.669
starting test case: good_dump

22:34:41.707 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.2770.0>

----------------------------------------------------
2016-04-10 22:34:41.716
ending test case: good_dump


----------------------------------------------------
2016-04-10 22:34:41.744
starting test case: bad_dump

22:34:41.780 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.2864.0>

----------------------------------------------------
2016-04-10 22:34:41.789
ending test case: bad_dump


----------------------------------------------------
2016-04-10 22:34:41.868
ending test group: registry


----------------------------------------------------
2016-04-10 22:34:41.894
starting test group: config


----------------------------------------------------
2016-04-10 22:34:41.971
starting test case: access_module

22:34:43.005 [warning] lager_error_logger_h dropped 7 messages in the last second that exceeded the limit of 50 messages/sec
22:34:43.011 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.2974.0>
22:34:43.013 [info] Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:34:44.391 [error] CRASH REPORT Process <0.2965.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:34:44.391 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:34:45.413
ending test case: access_module


----------------------------------------------------
2016-04-10 22:34:45.440
starting test case: auto_repair

22:34:46.470 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.3080.0>
22:34:46.473 [info] Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:34:46.475 [info] Application mnesia2 exited with reason: stopped
22:34:46.476 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.3128.0>
22:34:46.480 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.3176.0>

----------------------------------------------------
2016-04-10 22:34:47.496
ending test case: auto_repair


----------------------------------------------------
2016-04-10 22:34:47.522
starting test case: backup_module

22:34:49.111 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.3248.0>
22:34:49.114 [info] Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:34:49.141 [error] CRASH REPORT Process <0.3239.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:34:49.141 [info] Application mnesia2 exited with reason: killed
22:34:51.176 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.3331.0>
22:34:51.179 [info] Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:34:51.183 [info] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Restore aborted. mnesia2_config_backup:open_read["NonExisting.FILE"] -> {enoent,error}

22:34:51.184 [info] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Restore aborted. mnesia2_config_backup:open_read["/home/travis/build/lrascao/mnesia2/logs/ct_run.test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15.2016-04-10_22.34.16/Mnesia2.test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15/LATEST.LOG"] -> badarg

22:34:51.185 [error] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

22:34:51.185 [error] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

22:34:51.185 [error] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

22:34:51.186 [error] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

22:34:51.186 [error] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

22:34:51.186 [error] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

22:34:51.186 [error] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

22:34:51.186 [error] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_13,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_13,shutdown]}}}} ({error,{already_started,<0.3407.0>}})


----------------------------------------------------
2016-04-10 22:34:52.207
ending test case: backup_module


----------------------------------------------------
2016-04-10 22:34:52.233
starting test case: debug

22:34:53.263 [warning] lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
22:34:53.263 [info] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): mnesia2_monitor starting: <0.3452.0>

22:34:53.264 [info] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Mnesia2 debug level set to verbose
22:34:53.265 [info] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): mnesia2_subscr starting: <0.3453.0>

22:34:53.265 [info] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): mnesia2_locker starting: <0.3454.0>

22:34:53.265 [info] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): mnesia2_recover starting: <0.3455.0>

22:34:53.266 [info] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): mnesia2_tm starting: <0.3456.0>

22:34:53.266 [info] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Schema initiated from: default

22:34:53.267 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.3456.0>
22:34:53.268 [info] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): mnesia2_controller starting: <0.3459.0>

22:34:53.268 [info] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): mnesia2_late_loader starting: <0.3460.0>

22:34:53.269 [info] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Intend to load tables: []

22:34:53.270 [info] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): mnesia2_tm_1 starting: <0.3462.0>

22:34:53.270 [info] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): mnesia2_tm_2 starting: <0.3463.0>

22:34:53.271 [info] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): mnesia2_tm_3 starting: <0.3464.0>

22:34:55.294 [warning] lager_error_logger_h dropped 13 messages in the last second that exceeded the limit of 50 messages/sec
22:34:55.294 [info] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): mnesia2_monitor starting: <0.3517.0>

22:34:55.295 [info] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Version: "1.0.0"

22:34:55.295 [info] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Env access_module: mnesia2

22:34:55.296 [info] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Env auto_repair: true

22:34:55.296 [info] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Env backup_module: mnesia2_backup

22:34:55.296 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.3521.0>
22:34:55.297 [info] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Env debug: debug

22:34:55.298 [info] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15.2016-04-10_22.34.16/Mnesia2.test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15"

22:34:55.299 [info] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Env dump_disc_copies_at_startup: true

22:34:57.322 [warning] lager_error_logger_h dropped 7 messages in the last second that exceeded the limit of 50 messages/sec
22:34:57.322 [info] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): mnesia2_monitor starting: <0.3570.0>

22:34:57.323 [info] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Version: "1.0.0"

22:34:57.323 [info] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Env access_module: mnesia2

22:34:57.323 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.3574.0>
22:34:57.324 [info] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Env auto_repair: true

22:34:57.325 [info] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Env backup_module: mnesia2_backup

22:34:57.325 [info] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Env debug: trace

22:34:57.325 [info] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15.2016-04-10_22.34.16/Mnesia2.test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15"

22:34:57.326 [info] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Env dump_disc_copies_at_startup: true

22:34:57.326 [info] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Env dump_log_load_regulation: false

22:34:59.350 [warning] lager_error_logger_h dropped 15 messages in the last second that exceeded the limit of 50 messages/sec
22:34:59.350 [info] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): mnesia2_monitor starting: <0.3638.0>

22:34:59.350 [info] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Version: "1.0.0"

22:34:59.350 [info] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Env access_module: mnesia2

22:34:59.350 [info] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Env auto_repair: true

22:34:59.350 [info] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Env backup_module: mnesia2_backup

22:34:59.350 [info] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Env debug: debug

22:34:59.351 [info] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15.2016-04-10_22.34.16/Mnesia2.test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15"

22:34:59.351 [info] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Env dump_disc_copies_at_startup: true

22:34:59.352 [info] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Env dump_log_load_regulation: false

22:34:59.352 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.3642.0>
22:34:59.352 [info] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Env dump_log_time_threshold: 180000

22:34:59.353 [info] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Env dump_log_update_in_place: true

22:34:59.354 [info] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Env dump_log_write_threshold: 1000

22:35:01.377 [warning] lager_error_logger_h dropped 11 messages in the last second that exceeded the limit of 50 messages/sec
22:35:01.378 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.3706.0>
22:35:01.381 [info] Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:35:01.381 [error] CRASH REPORT Process <0.3697.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:35:01.381 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:35:02.406
ending test case: debug


----------------------------------------------------
2016-04-10 22:35:02.433
starting test case: dir

22:35:03.462 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.3770.0>
22:35:03.464 [info] Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:35:03.465 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.3771.0> exit with reason killed in context child_terminated
22:35:03.465 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.3771.0> exit with reason reached_max_restart_intensity in context shutdown
22:35:03.466 [error] CRASH REPORT Process <0.3761.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:35:03.466 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:35:04.499
ending test case: dir


----------------------------------------------------
2016-04-10 22:35:04.536
starting test case: dump_log_load_regulation

22:35:04.615 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.3841.0>
22:35:04.617 [info] Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:35:04.621 [info] Application mnesia2 exited with reason: stopped
22:35:04.627 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.3902.0>
22:35:07.613 [warning] lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
22:35:07.613 [warning] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

22:35:09.273 [warning] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

22:35:17.445 [warning] Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

22:35:19.697 [error] CRASH REPORT Process <0.3893.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:35:19.697 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:35:20.720
ending test case: dump_log_load_regulation


----------------------------------------------------
2016-04-10 22:35:20.787
starting test case: dump_log_time_threshold

22:35:21.827 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.4536.0>
22:35:21.829 [info] Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:35:27.836 [error] CRASH REPORT Process <0.4527.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:35:27.836 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:35:28.859
ending test case: dump_log_time_threshold


----------------------------------------------------
2016-04-10 22:35:28.885
starting test case: dump_log_write_threshold

22:35:29.944 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.4636.0>
22:35:29.946 [info] Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:35:30.963 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:35:31.976
ending test case: dump_log_write_threshold


----------------------------------------------------
2016-04-10 22:35:32.027
starting test case: dump_log_update_in_place

22:35:33.083 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.4752.0>
22:35:33.084 [info] Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:35:33.090 [error] CRASH REPORT Process <0.4743.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:35:33.090 [info] Application mnesia2 exited with reason: killed
22:35:35.120 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.4819.0>
22:35:35.123 [info] Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:35:35.146 [error] CRASH REPORT Process <0.4810.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:35:35.146 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:35:36.169
ending test case: dump_log_update_in_place


----------------------------------------------------
2016-04-10 22:35:36.195
starting test case: event_module

22:35:37.246 [warning] lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
22:35:37.262 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.4911.0>
22:35:37.265 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.1791.0>
22:35:37.283 [info] Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:35:37.567 [info] Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
Got event: {mnesia2_system_event,
               {mnesia2_up,
                   'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'}}
Got event: {mnesia2_system_event,
               {mnesia2_up,
                   'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'}}
Got event: {mnesia2_system_event,
               {mnesia2_down,
                   'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'}}
22:35:38.568 [error] gen_server <0.1844.0> terminated with reason: killed
22:35:38.568 [error] CRASH REPORT Process <0.1844.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:35:38.569 [error] CRASH REPORT Process <0.1782.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:35:38.569 [info] Application mnesia2 exited with reason: killed
22:35:40.601 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.1860.0>
Got event: {mnesia2_system_event,
               {mnesia2_up,
                   'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'}}
Got event: {mnesia2_system_event,
               {mnesia2_up,
                   'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'}}
22:35:40.617 [info] Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
Got event: {mnesia2_system_event,
               {mnesia2_down,
                   'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'}}
22:35:41.619 [error] gen_server <0.4975.0> terminated with reason: killed
22:35:41.619 [error] CRASH REPORT Process <0.4975.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:35:41.620 [error] CRASH REPORT Process <0.4902.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:35:41.620 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:35:42.641
ending test case: event_module


----------------------------------------------------
2016-04-10 22:35:42.668
starting test case: inconsistent_database

22:35:42.669 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.1873.0> exit with reason killed in context child_terminated
22:35:42.670 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.1873.0> exit with reason reached_max_restart_intensity in context shutdown
22:35:42.670 [error] CRASH REPORT Process <0.1851.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:35:42.670 [info] Application mnesia2 exited with reason: killed
22:35:43.738 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.5018.0>
22:35:43.740 [info] Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:35:43.765 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.1942.0>
22:35:43.768 [info] Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:35:43.770 [error] CRASH REPORT Process <0.5009.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:35:43.770 [info] Application mnesia2 exited with reason: killed
22:35:43.770 [error] gen_server <0.1993.0> terminated with reason: killed
22:35:43.770 [error] CRASH REPORT Process <0.1993.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:35:43.770 [error] CRASH REPORT Process <0.1932.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:35:43.771 [info] Application mnesia2 exited with reason: killed
22:35:43.812 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.5093.0>
22:35:47.670 [warning] lager_error_logger_h dropped 25 messages in the last second that exceeded the limit of 50 messages/sec
22:35:47.670 [info] Application mnesia2 exited with reason: stopped
22:35:47.753 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.2016.0>
22:35:47.754 [info] Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:35:47.761 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.5217.0>
22:35:47.765 [info] Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:35:57.112 [info] Application mnesia2 exited with reason: stopped
22:35:57.113 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:35:58.165
ending test case: inconsistent_database


----------------------------------------------------
2016-04-10 22:35:58.192
starting test case: max_wait_for_decision


----------------------------------------------------
2016-04-10 22:35:58.193
ending test case: max_wait_for_decision


----------------------------------------------------
2016-04-10 22:35:58.218
starting test case: send_compressed

22:35:58.252 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.5348.0>
22:35:58.255 [info] Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:35:58.258 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.2138.0>
22:35:58.262 [info] Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:35:58.314 [error] gen_server <0.2190.0> terminated with reason: killed
22:35:58.314 [error] CRASH REPORT Process <0.2190.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:35:58.314 [error] CRASH REPORT Process <0.2129.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:35:58.314 [info] Application mnesia2 exited with reason: killed
22:35:58.336 [error] CRASH REPORT Process <0.5339.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:35:58.336 [info] Application mnesia2 exited with reason: killed
22:35:58.366 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.5436.0>
22:35:58.556 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.2226.0>

----------------------------------------------------
2016-04-10 22:35:59.962
ending test case: send_compressed


----------------------------------------------------
2016-04-10 22:35:59.989
starting test case: app_test


----------------------------------------------------
2016-04-10 22:35:59.995
ending test case: app_test


----------------------------------------------------
2016-04-10 22:36:00.046
starting test case: start_one_disc_full_then_one_disc_less

22:36:00.049 [warning] lager_error_logger_h dropped 14 messages in the last second that exceeded the limit of 50 messages/sec
22:36:00.049 [error] CRASH REPORT Process <0.2217.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:36:00.049 [info] Application mnesia2 exited with reason: killed
22:36:01.109 [warning] lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
22:36:01.115 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.5559.0>
22:36:01.117 [info] Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:36:01.122 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.2329.0>
22:36:01.127 [info] Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:36:01.138 [error] gen_server <0.5623.0> terminated with reason: killed
22:36:01.138 [error] CRASH REPORT Process <0.5623.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:36:01.138 [error] CRASH REPORT Process <0.5550.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:36:01.138 [info] Application mnesia2 exited with reason: killed
22:36:01.139 [error] gen_server <0.2340.0> terminated with reason: killed
22:36:01.139 [error] CRASH REPORT Process <0.2340.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:36:01.139 [error] CRASH REPORT Process <0.2320.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:36:01.139 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:36:02.171
ending test case: start_one_disc_full_then_one_disc_less


----------------------------------------------------
2016-04-10 22:36:02.198
starting test case: start_first_one_disc_less_then_one_disc_full

22:36:03.493 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.5670.0>
22:36:03.495 [info] Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:36:03.503 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.2404.0>
22:36:03.508 [info] Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:36:03.511 [error] gen_server <0.2415.0> terminated with reason: killed
22:36:03.512 [error] gen_server <0.5732.0> terminated with reason: killed
22:36:03.511 [error] CRASH REPORT Process <0.2415.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:36:03.512 [error] CRASH REPORT Process <0.5732.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:36:03.512 [error] CRASH REPORT Process <0.2395.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:36:03.512 [info] Application mnesia2 exited with reason: killed
22:36:03.512 [error] CRASH REPORT Process <0.5661.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:36:03.512 [info] Application mnesia2 exited with reason: killed
22:36:05.536 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.2463.0>
22:36:05.537 [info] Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:36:05.544 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.5750.0>
22:36:05.551 [info] Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:36:05.571 [error] CRASH REPORT Process <0.5741.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:36:05.571 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:36:06.598
ending test case: start_first_one_disc_less_then_one_disc_full


----------------------------------------------------
2016-04-10 22:36:06.624
starting test case: start_first_one_disc_less_then_two_more_disc_less

22:36:07.014 [error] CRASH REPORT Process <0.2454.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:36:07.015 [info] Application mnesia2 exited with reason: killed
22:36:08.113 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.5875.0>
22:36:08.115 [info] Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:36:08.126 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.2552.0>
22:36:08.130 [info] Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:36:08.356 [info] Application lager started on node 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:36:08.356 [info] Application poolgirl started on node 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:36:08.381 [info] starting mnesia2_tm, 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.102.0>
22:36:08.398 [info] Application mnesia2 started on node 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:36:08.461 [error] CRASH REPORT Process <0.5866.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:36:08.461 [info] Application mnesia2 exited with reason: killed
22:36:08.460 [error] gen_server <0.2603.0> terminated with reason: killed
22:36:08.460 [error] CRASH REPORT Process <0.2603.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:36:08.460 [error] gen_server <0.2564.0> terminated with reason: killed
22:36:08.461 [error] CRASH REPORT Process <0.2564.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:36:08.461 [error] CRASH REPORT Process <0.2543.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:36:08.461 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:36:09.487
ending test case: start_first_one_disc_less_then_two_more_disc_less


----------------------------------------------------
2016-04-10 22:36:09.516
starting test case: schema_location_and_extra_db_nodes_combinations

22:36:10.570 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.5970.0>
22:36:10.573 [info] Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:36:10.582 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.2633.0>
22:36:10.590 [info] Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:36:10.603 [error] gen_server <0.2644.0> terminated with reason: killed
22:36:10.610 [error] gen_server <0.6034.0> terminated with reason: killed
22:36:10.603 [error] CRASH REPORT Process <0.2644.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:36:10.610 [error] CRASH REPORT Process <0.6034.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:36:10.603 [error] CRASH REPORT Process <0.2624.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:36:10.603 [info] Application mnesia2 exited with reason: killed
22:36:10.613 [error] CRASH REPORT Process <0.5961.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:36:10.613 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:36:11.634
ending test case: schema_location_and_extra_db_nodes_combinations


----------------------------------------------------
2016-04-10 22:36:11.661
starting test case: table_load_to_disc_less_nodes

22:36:12.727 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.6064.0>
22:36:12.730 [info] Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:36:12.731 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.2703.0>
22:36:12.734 [info] Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:36:12.740 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.2705.0> exit with reason killed in context child_terminated
22:36:12.741 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.6059.0> exit with reason killed in context child_terminated
22:36:12.740 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.2705.0> exit with reason reached_max_restart_intensity in context shutdown
22:36:12.741 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.6059.0> exit with reason reached_max_restart_intensity in context shutdown
22:36:12.740 [error] gen_server <0.2716.0> terminated with reason: killed
22:36:12.741 [error] gen_server mnesia2_subscr terminated with reason: killed
22:36:12.740 [error] CRASH REPORT Process <0.2716.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:36:12.741 [error] CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:36:12.740 [error] CRASH REPORT Process <0.2694.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:36:12.740 [info] Application mnesia2 exited with reason: killed
22:36:12.741 [error] gen_server mnesia2_snmp_sup terminated with reason: killed
22:36:12.742 [error] CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:36:12.743 [info] Application mnesia2 exited with reason: shutdown

----------------------------------------------------
2016-04-10 22:36:13.767
ending test case: table_load_to_disc_less_nodes


----------------------------------------------------
2016-04-10 22:36:13.794
starting test case: schema_merge

22:36:14.884 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.6150.0>
22:36:14.887 [info] Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:36:14.901 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.2778.0>
22:36:14.924 [info] Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:36:14.927 [error] gen_server <0.2832.0> terminated with reason: killed
22:36:14.927 [error] CRASH REPORT Process <0.2832.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:36:14.928 [error] CRASH REPORT Process <0.2769.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:36:14.928 [info] Application mnesia2 exited with reason: killed
22:36:15.954 [error] CRASH REPORT Process <0.6141.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:36:15.954 [info] Application mnesia2 exited with reason: killed
22:36:17.989 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.2848.0>
22:36:17.991 [info] Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:36:23.025 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.6228.0>
22:36:23.034 [info] Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:36:23.040 [error] gen_server <0.6275.0> terminated with reason: killed
22:36:23.040 [error] CRASH REPORT Process <0.6275.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:36:23.041 [error] gen_server <0.2917.0> terminated with reason: killed
22:36:23.041 [error] CRASH REPORT Process <0.6219.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:36:23.041 [info] Application mnesia2 exited with reason: killed
22:36:23.041 [error] CRASH REPORT Process <0.2917.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:36:23.041 [error] CRASH REPORT Process <0.2839.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:36:23.041 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:36:24.066
ending test case: schema_merge


----------------------------------------------------
2016-04-10 22:36:24.124
starting test case: dynamic_basic

22:36:24.194 [warning] lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
22:36:24.509 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.6338.0>
22:36:24.512 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.2947.0>
22:36:24.538 [info] Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:36:24.557 [info] starting mnesia2_tm, 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.192.0>
22:36:24.562 [info] Application mnesia2 started on node 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:36:24.815 [info] Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:36:24.885 [error] CRASH REPORT Process <0.2938.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:36:24.886 [info] Application mnesia2 exited with reason: killed
22:36:24.922 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.3039.0>
22:36:25.187 [info] Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:36:25.205 [error] gen_server <0.6403.0> terminated with reason: killed
22:36:25.205 [error] CRASH REPORT Process <0.6403.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:36:25.206 [error] CRASH REPORT Process <0.6329.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:36:25.206 [info] Application mnesia2 exited with reason: killed
22:36:25.226 [error] gen_server <0.276.0> terminated with reason: killed
22:36:25.227 [error] CRASH REPORT Process <0.276.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:36:25.227 [error] CRASH REPORT Process <0.183.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:36:25.227 [info] Application mnesia2 exited with reason: killed
22:36:25.251 [info] Application mnesia2 exited with reason: stopped
22:36:25.282 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.3134.0>
22:36:25.315 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.6458.0>
22:36:25.321 [info] starting mnesia2_tm, 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.296.0>
22:36:25.327 [info] Application mnesia2 started on node 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:36:25.337 [info] Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:36:25.873 [error] gen_server <0.368.0> terminated with reason: killed
22:36:25.873 [error] CRASH REPORT Process <0.368.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:36:25.873 [error] gen_server <0.358.0> terminated with reason: killed
22:36:25.874 [error] CRASH REPORT Process <0.358.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:36:25.900 [info] starting mnesia2_tm, 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.391.0>
22:36:27.950 [error] gen_server <0.6553.0> terminated with reason: killed
22:36:27.950 [error] gen_server <0.6523.0> terminated with reason: killed
22:36:27.950 [error] CRASH REPORT Process <0.6553.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:36:27.951 [error] CRASH REPORT Process <0.6523.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:36:27.951 [error] CRASH REPORT Process <0.6448.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:36:27.951 [info] Application mnesia2 exited with reason: killed
22:36:27.973 [warning] lager_error_logger_h dropped 6 messages in the last second that exceeded the limit of 50 messages/sec
22:36:27.973 [error] gen_server <0.3227.0> terminated with reason: killed
22:36:27.973 [error] CRASH REPORT Process <0.3227.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:36:27.973 [error] CRASH REPORT Process <0.3125.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:36:27.973 [info] Application mnesia2 exited with reason: killed
22:36:27.997 [warning] lager_error_logger_h dropped 16 messages in the last second that exceeded the limit of 50 messages/sec
22:36:27.997 [info] Application mnesia2 exited with reason: stopped
22:36:28.015 [info] starting mnesia2_tm, 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.497.0>
22:36:28.017 [info] Application mnesia2 started on node 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:36:28.057 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.6572.0>
22:36:28.062 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.3248.0>
22:36:28.085 [info] Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:36:28.364 [info] Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:36:28.887 [error] gen_server <0.565.0> terminated with reason: killed
22:36:28.887 [error] CRASH REPORT Process <0.565.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:36:28.888 [error] CRASH REPORT Process <0.488.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:36:28.888 [info] Application mnesia2 exited with reason: killed
22:36:28.912 [info] starting mnesia2_tm, 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.596.0>
22:36:28.914 [info] Application mnesia2 started on node 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:36:28.998 [error] gen_server <0.6668.0> terminated with reason: killed
22:36:28.998 [error] CRASH REPORT Process <0.6668.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:36:28.998 [error] gen_server <0.6661.0> terminated with reason: killed
22:36:28.998 [error] CRASH REPORT Process <0.6661.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:36:29.003 [error] CRASH REPORT Process <0.6563.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:36:29.003 [info] Application mnesia2 exited with reason: killed
22:36:29.022 [error] gen_server <0.3337.0> terminated with reason: killed
22:36:29.023 [error] CRASH REPORT Process <0.3337.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:36:29.023 [error] CRASH REPORT Process <0.3239.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:36:29.023 [info] Application mnesia2 exited with reason: killed
22:36:29.051 [info] Application mnesia2 exited with reason: stopped
22:36:29.075 [info] starting mnesia2_tm, 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.697.0>
22:36:29.077 [info] Application mnesia2 started on node 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:36:29.111 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.6685.0>
22:36:29.131 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.3356.0>
22:36:29.139 [info] Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:36:29.431 [info] Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:36:29.950 [error] gen_server <0.3425.0> terminated with reason: killed
22:36:29.951 [error] CRASH REPORT Process <0.3425.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:36:29.952 [error] gen_server <0.3406.0> terminated with reason: killed
22:36:29.952 [error] CRASH REPORT Process <0.3406.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:36:29.995 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.3451.0>
22:36:30.012 [info] Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:36:30.065 [error] gen_server <0.3499.0> terminated with reason: killed
22:36:30.065 [error] CRASH REPORT Process <0.3499.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:36:30.065 [error] gen_server <0.3509.0> terminated with reason: killed
22:36:30.065 [error] CRASH REPORT Process <0.3509.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:36:30.066 [error] gen_server <0.3464.0> terminated with reason: killed
22:36:30.066 [error] CRASH REPORT Process <0.3464.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:36:30.066 [error] CRASH REPORT Process <0.3442.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:36:30.067 [info] Application mnesia2 exited with reason: killed
22:36:31.100 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.3529.0>
22:36:31.109 [info] Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'

----------------------------------------------------
2016-04-10 22:36:31.121
ending test case: dynamic_basic


----------------------------------------------------
2016-04-10 22:36:31.148
starting test case: dynamic_ext

22:36:31.151 [error] CRASH REPORT Process <0.3520.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:36:31.151 [error] gen_server <0.6798.0> terminated with reason: killed
22:36:31.151 [info] Application mnesia2 exited with reason: killed
22:36:31.151 [error] CRASH REPORT Process <0.6798.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:36:31.153 [error] gen_server <0.821.0> terminated with reason: killed
22:36:31.152 [error] CRASH REPORT Process <0.6676.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:36:31.152 [info] Application mnesia2 exited with reason: killed
22:36:31.153 [error] CRASH REPORT Process <0.821.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:36:31.153 [error] gen_server <0.812.0> terminated with reason: killed
22:36:31.153 [error] CRASH REPORT Process <0.812.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:36:31.154 [error] CRASH REPORT Process <0.688.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:36:31.154 [info] Application mnesia2 exited with reason: killed
22:36:31.213 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.6831.0>
22:36:31.215 [info] Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:36:31.236 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.3608.0>
22:36:31.300 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.3702.0>
22:36:31.365 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.3792.0>
22:36:31.433 [info] Application mnesia2 exited with reason: stopped
22:36:31.450 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.3892.0>
22:36:31.967 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.6944.0>
22:36:32.015 [info] Application mnesia2 exited with reason: stopped
22:36:32.016 [warning] lager_error_logger_h dropped 10 messages in the last second that exceeded the limit of 50 messages/sec
22:36:32.017 [error] CRASH REPORT Process <0.3883.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:36:32.017 [info] Application mnesia2 exited with reason: killed
22:36:32.052 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.7027.0>
22:36:32.056 [info] Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:36:32.559 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.3974.0>
22:36:32.595 [info] Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'

----------------------------------------------------
2016-04-10 22:36:32.606
ending test case: dynamic_ext


----------------------------------------------------
2016-04-10 22:36:32.633
starting test case: dynamic_bad

22:36:32.641 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_controller:start() at <0.3978.0> exit with reason killed in context child_terminated
22:36:32.641 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_controller:start() at <0.3978.0> exit with reason reached_max_restart_intensity in context shutdown
22:36:32.644 [error] CRASH REPORT Process <0.7018.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:36:32.644 [info] Application mnesia2 exited with reason: killed
22:36:32.642 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.3976.0> exit with reason killed in context shutdown_error
22:36:32.643 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.3969.0> exit with reason shutdown in context child_terminated
22:36:32.722 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.7128.0>
22:36:32.734 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.4066.0>
22:36:32.734 [info] starting mnesia2_tm, 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.849.0>
22:36:32.740 [info] Application mnesia2 started on node 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:36:33.028 [info] Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:36:33.219 [warning] lager_error_logger_h dropped 32 messages in the last second that exceeded the limit of 50 messages/sec
22:36:33.223 [error] gen_server <0.7192.0> terminated with reason: killed
22:36:33.220 [error] gen_server <0.913.0> terminated with reason: killed
22:36:33.223 [error] CRASH REPORT Process <0.7192.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:36:33.219 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.4081.0> exit with reason killed in context child_terminated
22:36:33.220 [error] CRASH REPORT Process <0.913.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:36:33.219 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.4081.0> exit with reason reached_max_restart_intensity in context shutdown
22:36:33.223 [error] gen_server <0.7187.0> terminated with reason: killed
22:36:33.223 [error] CRASH REPORT Process <0.7187.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:36:33.220 [error] gen_server <0.906.0> terminated with reason: killed
22:36:33.223 [error] CRASH REPORT Process <0.7119.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:36:33.223 [info] Application mnesia2 exited with reason: killed
22:36:33.220 [error] CRASH REPORT Process <0.906.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:36:33.220 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_controller:start() at <0.4083.0> exit with reason killed in context shutdown_error
22:36:33.221 [error] CRASH REPORT Process <0.840.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:36:33.221 [info] Application mnesia2 exited with reason: killed
22:36:33.244 [info] starting mnesia2_tm, 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.954.0>
22:36:33.221 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.4061.0> exit with reason shutdown in context child_terminated
22:36:33.245 [info] Application mnesia2 started on node 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:36:33.221 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.4061.0> exit with reason reached_max_restart_intensity in context shutdown
22:36:33.221 [info] Application mnesia2 exited with reason: shutdown
22:36:33.284 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.7240.0>
22:36:33.244 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.4158.0>
22:36:33.246 [info] Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:36:33.322 [error] gen_server <0.1003.0> terminated with reason: killed
22:36:33.322 [error] CRASH REPORT Process <0.1003.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:36:33.323 [error] gen_server <0.1012.0> terminated with reason: killed
22:36:33.323 [error] CRASH REPORT Process <0.1012.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:36:33.323 [error] gen_server <0.998.0> terminated with reason: killed
22:36:33.323 [error] CRASH REPORT Process <0.998.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:36:33.346 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.4236.0>
22:36:33.323 [error] CRASH REPORT Process <0.945.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:36:33.323 [info] Application mnesia2 exited with reason: killed
22:36:33.348 [info] starting mnesia2_tm, 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.1031.0>
22:36:33.376 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.7332.0>
22:36:43.384 [warning] lager_error_logger_h dropped 35 messages in the last second that exceeded the limit of 50 messages/sec

----------------------------------------------------
2016-04-10 22:36:43.386
ending test case: dynamic_bad

22:36:43.384 [error] gen_server mnesia2_monitor terminated with reason: killed
22:36:43.384 [error] gen_server mnesia2_recover terminated with reason: killed
22:36:43.384 [error] CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:36:43.384 [error] gen_server mnesia2_snmp_sup terminated with reason: killed
22:36:43.384 [error] CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:36:43.384 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at undefined exit with reason killed in context start_error
22:36:43.384 [error] gen_server mnesia2_subscr terminated with reason: killed
22:36:43.384 [error] CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:36:43.384 [error] CRASH REPORT Process <0.7323.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}} in application_master:init/4 line 134
22:36:43.385 [info] Application mnesia2 exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}}
22:36:43.386 [error] CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826

----------------------------------------------------
2016-04-10 22:36:43.467
starting test case: unknown_config

22:36:43.470 [error] gen_server <0.4280.0> terminated with reason: killed
22:36:43.470 [error] CRASH REPORT Process <0.4280.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:36:43.472 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.1032.0> exit with reason killed in context child_terminated
22:36:43.470 [error] CRASH REPORT Process <0.4227.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:36:43.470 [info] Application mnesia2 exited with reason: killed
22:36:43.472 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.1032.0> exit with reason reached_max_restart_intensity in context shutdown
22:36:43.473 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.1026.0> exit with reason shutdown in context child_terminated
22:36:43.474 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.1026.0> exit with reason reached_max_restart_intensity in context shutdown
22:36:43.476 [info] Application mnesia2 exited with reason: shutdown

----------------------------------------------------
2016-04-10 22:36:45.537
ending test case: unknown_config


----------------------------------------------------
2016-04-10 22:36:45.630
ending test group: config


----------------------------------------------------
2016-04-10 22:36:45.659
starting test group: examples


----------------------------------------------------
2016-04-10 22:36:45.748
starting test case: bup


----------------------------------------------------
2016-04-10 22:36:45.778
ending test case: bup


- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Error detected: error
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Testing lrascao.mnesia2.mnesia2_extra_light_SUITE: *** FAILED test case 41 of 52 ***

----------------------------------------------------
2016-04-10 22:36:45.809
starting test case: company


----------------------------------------------------
2016-04-10 22:36:45.810
ending test case: company


----------------------------------------------------
2016-04-10 22:36:45.839
starting test case: meter

22:36:45.904 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.7441.0>
22:36:45.907 [info] Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:36:50.306 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:36:50.323
ending test case: meter


----------------------------------------------------
2016-04-10 22:36:50.376
starting test case: replica_test

22:36:50.467 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.4327.0>
22:36:50.480 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.7577.0>
22:36:50.482 [info] starting mnesia2_tm, 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.1127.0>
22:36:50.494 [info] Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:36:50.499 [info] Application mnesia2 started on node 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:36:50.773 [info] Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:36:56.893 [info] Application mnesia2 exited with reason: stopped
22:36:56.897 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:36:56.901
ending test case: replica_test

22:36:56.900 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:36:56.939
starting test case: sticky_replica_test

22:36:57.022 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.7706.0>
22:36:57.027 [info] Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:36:57.037 [info] starting mnesia2_tm, 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.1240.0>
22:36:57.039 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.4445.0>
22:36:57.045 [info] Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:36:57.342 [info] Application mnesia2 started on node 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:37:03.420 [info] Application mnesia2 exited with reason: stopped
22:37:03.424 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:37:03.431
ending test case: sticky_replica_test

22:37:03.430 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:37:03.470
starting test case: dist_test

22:37:03.580 [info] starting mnesia2_tm, 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.1356.0>
22:37:03.582 [info] Application mnesia2 started on node 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:37:03.588 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.7835.0>
22:37:03.588 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.4560.0>
22:37:03.619 [info] Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:37:03.628 [info] Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:37:23.178 [info] Application mnesia2 exited with reason: stopped
22:37:23.179 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:37:23.193
ending test case: dist_test

22:37:23.185 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:37:23.243
starting test case: conflict_test

22:37:23.328 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.8972.0>
22:37:23.330 [info] Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:37:23.336 [info] starting mnesia2_tm, 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.2481.0>
22:37:23.342 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.5684.0>
22:37:23.354 [info] Application mnesia2 started on node 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:37:23.381 [info] Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:37:30.073 [info] Application mnesia2 exited with reason: stopped
22:37:30.071 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:37:30.083
ending test case: conflict_test

22:37:30.083 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:37:30.119
starting test case: frag_test

22:37:30.215 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.9111.0>
22:37:30.217 [info] Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:37:30.220 [info] starting mnesia2_tm, 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.2606.0>
22:37:30.238 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.5807.0>
22:37:30.248 [info] Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:37:30.525 [info] Application mnesia2 started on node 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:37:36.872 [info] Application mnesia2 exited with reason: stopped
22:37:36.893 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:37:36.908
ending test case: frag_test

22:37:36.908 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:37:36.935
starting test case: frag2_test

22:37:37.032 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.10591.0>
22:37:37.035 [info] Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:37:37.040 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.7277.0>
22:37:37.043 [info] starting mnesia2_tm, 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.4078.0>
22:37:37.049 [info] Application mnesia2 started on node 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:37:37.345 [info] Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:37:43.546 [info] Application mnesia2 exited with reason: stopped
22:37:43.569 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:37:43.579
ending test case: frag2_test

22:37:43.579 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:37:43.607
starting test case: remote_test

22:37:43.702 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.11002.0>
22:37:43.704 [info] Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:37:43.708 [info] starting mnesia2_tm, 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.6119.0>
22:37:43.741 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.8378.0>
22:37:43.757 [info] Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:37:44.044 [info] Application mnesia2 started on node 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:37:50.163 [info] Application mnesia2 exited with reason: stopped
22:37:50.164 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:37:50.168
ending test case: remote_test

22:37:50.168 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:37:50.195
starting test case: remote_frag2_test

22:37:50.294 [info] starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.11132.0>
22:37:50.297 [info] starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.8492.0>
22:37:50.301 [info] starting mnesia2_tm, 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.6914.0>
22:37:50.305 [info] Application mnesia2 started on node 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:37:50.599 [info] Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:37:50.603 [info] Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
22:37:56.794 [info] Application mnesia2 exited with reason: stopped
22:37:56.795 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:37:56.809
ending test case: remote_frag2_test

22:37:56.803 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:37:56.927
ending test group: examples


----------------------------------------------------
2016-04-10 22:37:56.953
ending test group: extra_light


----------------------------------------------------
2016-04-10 22:37:56.979
starting test case: clean_up_suite


----------------------------------------------------
2016-04-10 22:37:57.000
ending test case: clean_up_suite

Testing lrascao.mnesia2.mnesia2_extra_light_SUITE: TEST COMPLETE, 51 ok, 1 failed of 52 test cases

Cover analysing... done

Updating /home/travis/build/lrascao/mnesia2/logs/index.html... done
Updating /home/travis/build/lrascao/mnesia2/logs/all_runs.html... done

