2016-04-10 22:34:46.635 [info] <0.7.0> Application lager started on node 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:34:46.635 [info] <0.7.0> Application poolgirl started on node 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:34:46.658 [info] <0.495.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.495.0>
2016-04-10 22:34:46.677 [info] <0.563.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.563.0>
2016-04-10 22:34:47.078 [error] <0.554.0> CRASH REPORT Process <0.554.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:47.078 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:34:47.171 [info] <0.673.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.673.0>
2016-04-10 22:34:47.173 [info] <0.7.0> Application mnesia2 started on node 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:34:47.580 [error] <0.730.0> gen_server <0.730.0> terminated with reason: killed
2016-04-10 22:34:47.580 [error] <0.730.0> CRASH REPORT Process <0.730.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:34:47.581 [error] <0.664.0> CRASH REPORT Process <0.664.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:47.386 [info] <0.7.0> Application lager started on node 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:34:47.386 [info] <0.7.0> Application poolgirl started on node 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:34:47.437 [info] <0.100.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.100.0>
2016-04-10 22:34:47.656 [info] <0.216.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.216.0>
2016-04-10 22:34:47.881 [info] <0.369.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.369.0>
2016-04-10 22:34:47.965 [info] <0.459.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.459.0>
2016-04-10 22:34:47.647 [info] <0.799.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.799.0>
2016-04-10 22:34:47.851 [info] <0.927.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.927.0>
2016-04-10 22:34:47.957 [info] <0.1027.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.1027.0>
2016-04-10 22:34:48.746 [warning] <0.6.0> lager_error_logger_h dropped 48 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:34:48.747 [error] <0.1018.0> CRASH REPORT Process <0.1018.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:48.746 [warning] <0.6.0> lager_error_logger_h dropped 57 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:34:48.746 [error] <0.450.0> CRASH REPORT Process <0.450.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:48.747 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:34:48.798 [info] <0.1150.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.1150.0>
2016-04-10 22:34:48.801 [info] <0.7.0> Application mnesia2 started on node 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:34:48.973 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:34:48.989 [info] <0.1262.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.1262.0>
2016-04-10 22:34:49.369 [warning] <0.6.0> lager_error_logger_h dropped 16 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:34:49.369 [error] <0.1292.0> gen_server <0.1292.0> terminated with reason: killed
2016-04-10 22:34:48.746 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:34:48.805 [info] <0.548.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.548.0>
2016-04-10 22:34:48.820 [info] <0.7.0> Application mnesia2 started on node 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:34:49.371 [error] <0.661.0> gen_server <0.661.0> terminated with reason: killed
2016-04-10 22:34:49.370 [error] <0.1292.0> CRASH REPORT Process <0.1292.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:34:49.370 [error] <0.1253.0> CRASH REPORT Process <0.1253.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:49.371 [error] <0.661.0> CRASH REPORT Process <0.661.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:34:49.371 [error] <0.539.0> CRASH REPORT Process <0.539.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:49.371 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:34:49.458 [info] <0.762.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.762.0>
2016-04-10 22:34:49.462 [info] <0.7.0> Application mnesia2 started on node 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:34:49.573 [error] <0.816.0> gen_server <0.816.0> terminated with reason: killed
2016-04-10 22:34:49.370 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:34:49.420 [info] <0.1494.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.1494.0>
2016-04-10 22:34:49.423 [info] <0.7.0> Application mnesia2 started on node 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:34:49.575 [error] <0.1488.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): ** ERROR ** mnesia2_event got unexpected event: {'EXIT',<0.1491.0>,killed}

2016-04-10 22:34:49.573 [error] <0.816.0> CRASH REPORT Process <0.816.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:34:49.575 [error] <0.1487.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.1489.0> exit with reason killed in context child_terminated
2016-04-10 22:34:49.574 [error] <0.753.0> CRASH REPORT Process <0.753.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:49.653 [info] <0.1608.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.1608.0>
2016-04-10 22:34:49.574 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:34:49.661 [info] <0.862.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.862.0>
2016-04-10 22:34:49.870 [info] <0.1724.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.1724.0>
2016-04-10 22:34:50.091 [warning] <0.6.0> lager_error_logger_h dropped 7 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:34:50.091 [error] <0.1719.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.1736.0> exit with reason killed in context child_terminated
2016-04-10 22:34:49.892 [info] <0.963.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.963.0>
2016-04-10 22:34:50.093 [warning] <0.6.0> lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:34:50.093 [error] <0.954.0> CRASH REPORT Process <0.954.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:50.091 [error] <0.1719.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.1736.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:34:50.093 [error] <0.1719.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_controller:start() at <0.1738.0> exit with reason killed in context shutdown_error
2016-04-10 22:34:50.093 [error] <0.1718.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): ** ERROR ** mnesia2_recover got unexpected info: {'EXIT',<0.1738.0>,killed}

2016-04-10 22:34:50.094 [error] <0.1780.0> gen_server <0.1780.0> terminated with reason: killed
2016-04-10 22:34:50.094 [error] <0.1780.0> CRASH REPORT Process <0.1780.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:34:50.095 [error] <0.1715.0> CRASH REPORT Process <0.1715.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:50.093 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:34:50.151 [info] <0.1069.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.1069.0>
2016-04-10 22:34:50.172 [info] <0.7.0> Application mnesia2 started on node 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:34:50.331 [error] <0.1060.0> CRASH REPORT Process <0.1060.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:50.095 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:34:50.146 [info] <0.1850.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.1850.0>
2016-04-10 22:34:50.390 [info] <0.1981.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.1981.0>
2016-04-10 22:34:50.608 [info] <0.2114.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.2114.0>
2016-04-10 22:34:50.331 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:34:50.407 [info] <0.1168.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.1168.0>
2016-04-10 22:34:50.629 [info] <0.1269.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.1269.0>
2016-04-10 22:34:50.923 [info] <0.2254.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.2254.0>
2016-04-10 22:34:51.135 [warning] <0.6.0> lager_error_logger_h dropped 4 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:34:51.135 [error] <0.2249.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.2266.0> exit with reason killed in context child_terminated
2016-04-10 22:34:50.929 [info] <0.1375.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.1375.0>
2016-04-10 22:34:51.134 [warning] <0.6.0> lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:34:51.134 [error] <0.1427.0> gen_server <0.1427.0> terminated with reason: killed
2016-04-10 22:34:51.135 [error] <0.2249.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.2266.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:34:51.135 [error] <0.1427.0> CRASH REPORT Process <0.1427.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:34:51.137 [error] <0.2249.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_controller:start() at <0.2268.0> exit with reason killed in context shutdown_error
2016-04-10 22:34:51.135 [error] <0.1366.0> CRASH REPORT Process <0.1366.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:51.137 [error] <0.2248.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): ** ERROR ** mnesia2_recover got unexpected info: {'EXIT',<0.2268.0>,killed}

2016-04-10 22:34:51.138 [error] <0.2310.0> gen_server <0.2310.0> terminated with reason: killed
2016-04-10 22:34:51.138 [error] <0.2310.0> CRASH REPORT Process <0.2310.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:34:51.138 [error] <0.2245.0> CRASH REPORT Process <0.2245.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:51.135 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:34:51.217 [info] <0.1462.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.1462.0>
2016-04-10 22:34:51.240 [info] <0.7.0> Application mnesia2 started on node 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:34:51.664 [error] <0.1453.0> CRASH REPORT Process <0.1453.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:51.138 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:34:51.200 [info] <0.2385.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.2385.0>
2016-04-10 22:34:51.716 [info] <0.2518.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.2518.0>
2016-04-10 22:34:51.664 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:34:51.730 [info] <0.1575.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.1575.0>
2016-04-10 22:34:52.019 [warning] <0.6.0> lager_error_logger_h dropped 4 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:34:52.022 [info] <0.7.0> Application mnesia2 started on node 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:34:52.210 [error] <0.2509.0> CRASH REPORT Process <0.2509.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:52.207 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:34:52.208 [error] <0.1629.0> gen_server <0.1629.0> terminated with reason: killed
2016-04-10 22:34:52.208 [error] <0.1629.0> CRASH REPORT Process <0.1629.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:34:52.208 [error] <0.1566.0> CRASH REPORT Process <0.1566.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:52.208 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:34:52.301 [info] <0.1663.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.1663.0>
2016-04-10 22:34:52.306 [info] <0.7.0> Application mnesia2 started on node 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:34:52.348 [error] <0.1705.0> gen_server <0.1705.0> terminated with reason: killed
2016-04-10 22:34:52.348 [error] <0.1705.0> CRASH REPORT Process <0.1705.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:34:52.210 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:34:52.282 [info] <0.2642.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.2642.0>
2016-04-10 22:34:52.630 [info] <0.2770.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.2770.0>
2016-04-10 22:34:52.725 [info] <0.2864.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.2864.0>
2016-04-10 22:34:54.080 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:34:54.086 [info] <0.2974.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.2974.0>
2016-04-10 22:34:54.088 [info] <0.7.0> Application mnesia2 started on node 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:34:55.271 [error] <0.2965.0> CRASH REPORT Process <0.2965.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:55.271 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:34:57.353 [info] <0.3080.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.3080.0>
2016-04-10 22:34:57.355 [info] <0.7.0> Application mnesia2 started on node 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:34:57.357 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:34:57.358 [info] <0.3128.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.3128.0>
2016-04-10 22:34:57.363 [info] <0.3176.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.3176.0>
2016-04-10 22:34:59.460 [info] <0.3248.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.3248.0>
2016-04-10 22:34:59.463 [info] <0.7.0> Application mnesia2 started on node 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:34:59.480 [error] <0.3239.0> CRASH REPORT Process <0.3239.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:59.480 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:35:01.533 [info] <0.3331.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.3331.0>
2016-04-10 22:35:01.536 [info] <0.7.0> Application mnesia2 started on node 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:35:01.541 [info] <0.3325.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Restore aborted. mnesia2_config_backup:open_read["NonExisting.FILE"] -> {enoent,error}

2016-04-10 22:35:01.542 [info] <0.3325.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Restore aborted. mnesia2_config_backup:open_read["/home/travis/build/lrascao/mnesia2/logs/ct_run.test7517@testing-worker-linux-docker-c74eb140-3365-linux-12.2016-04-10_22.34.24/Mnesia2.test7517@testing-worker-linux-docker-c74eb140-3365-linux-12/LATEST.LOG"] -> badarg

2016-04-10 22:35:01.543 [info] <0.3407.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): mnesia2_tm_14 terminated: shutdown

2016-04-10 22:35:01.543 [error] <0.3359.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 22:35:01.544 [error] <0.3361.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 22:35:01.544 [error] <0.3360.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 22:35:01.544 [error] <0.3358.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 22:35:01.544 [error] <0.3364.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_6,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_6,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 22:35:01.544 [error] <0.3365.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 22:35:01.544 [error] <0.3369.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 22:35:03.628 [warning] <0.6.0> lager_error_logger_h dropped 9 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:35:03.632 [info] <0.3441.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): mnesia2_monitor starting: <0.3443.0>

2016-04-10 22:35:03.635 [info] <0.3441.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Mnesia2 debug level set to verbose
2016-04-10 22:35:03.637 [info] <0.3447.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.3447.0>
2016-04-10 22:35:03.639 [info] <0.7.0> Application mnesia2 started on node 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:35:03.641 [error] <0.3455.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}}} ({error,{already_started,<0.3486.0>}})

2016-04-10 22:35:03.641 [error] <0.3457.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}}} ({error,{already_started,<0.3486.0>}})

2016-04-10 22:35:03.641 [error] <0.3456.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}}} ({error,{already_started,<0.3486.0>}})

2016-04-10 22:35:03.642 [error] <0.3454.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}}} ({error,{already_started,<0.3486.0>}})

2016-04-10 22:35:05.664 [warning] <0.6.0> lager_error_logger_h dropped 27 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:35:05.665 [info] <0.3522.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): mnesia2_monitor starting: <0.3524.0>

2016-04-10 22:35:05.666 [info] <0.3522.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Version: "1.0.0"

2016-04-10 22:35:05.666 [info] <0.3522.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env access_module: mnesia2

2016-04-10 22:35:05.667 [info] <0.3522.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env auto_repair: true

2016-04-10 22:35:05.667 [info] <0.3522.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env backup_module: mnesia2_backup

2016-04-10 22:35:05.667 [info] <0.3522.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env debug: debug

2016-04-10 22:35:05.667 [info] <0.3522.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test7517@testing-worker-linux-docker-c74eb140-3365-linux-12.2016-04-10_22.34.24/Mnesia2.test7517@testing-worker-linux-docker-c74eb140-3365-linux-12"

2016-04-10 22:35:05.667 [info] <0.3522.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env dump_disc_copies_at_startup: true

2016-04-10 22:35:05.667 [info] <0.3522.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env dump_log_load_regulation: false

2016-04-10 22:35:05.668 [info] <0.3522.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env dump_log_time_threshold: 180000

2016-04-10 22:35:05.668 [info] <0.3522.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env dump_log_update_in_place: true

2016-04-10 22:35:05.668 [info] <0.3522.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env dump_log_write_threshold: 1000

2016-04-10 22:35:05.668 [info] <0.3522.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env event_module: mnesia2_event

2016-04-10 22:35:05.668 [info] <0.3522.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env extra_db_nodes: []

2016-04-10 22:35:05.668 [info] <0.3522.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env ignore_fallback_at_startup: false

2016-04-10 22:35:05.668 [info] <0.3522.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env fallback_error_function: {mnesia2,lkill}

2016-04-10 22:35:05.668 [info] <0.3522.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env max_wait_for_decision: infinity

2016-04-10 22:35:05.668 [info] <0.3522.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env schema_location: opt_disc

2016-04-10 22:35:05.669 [info] <0.3522.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env core_dir: false

2016-04-10 22:35:05.669 [info] <0.3522.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env pid_sort_order: false

2016-04-10 22:35:05.669 [info] <0.3522.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env no_table_loaders: 2

2016-04-10 22:35:05.669 [info] <0.3522.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env dc_dump_limit: 4

2016-04-10 22:35:05.669 [info] <0.3522.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env send_compressed: 0

2016-04-10 22:35:05.670 [info] <0.3522.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env send_max_packets: 20

2016-04-10 22:35:05.670 [info] <0.3522.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env send_max_transfer_size: 7500

2016-04-10 22:35:05.670 [info] <0.3522.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env async_dirty_buffer_size: 524288

2016-04-10 22:35:05.670 [info] <0.3522.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env async_dirty_max_buffer_file_size: 100000000

2016-04-10 22:35:05.670 [info] <0.3522.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env async_dirty_tx_backlog_threshold: 200000

2016-04-10 22:35:05.670 [info] <0.3522.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env async_dirty_buffer_min_runtime: 10000

2016-04-10 22:35:05.670 [info] <0.3522.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env async_dirty_buffer_drained_cutoff: 5

2016-04-10 22:35:05.670 [info] <0.3522.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Mnesia2 debug level set to debug
2016-04-10 22:35:05.670 [info] <0.3522.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): mnesia2_subscr starting: <0.3525.0>

2016-04-10 22:35:05.670 [info] <0.3522.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): mnesia2_locker starting: <0.3526.0>

2016-04-10 22:35:05.670 [info] <0.3522.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): mnesia2_recover starting: <0.3527.0>

2016-04-10 22:35:05.671 [info] <0.3528.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.3528.0>
2016-04-10 22:35:05.671 [info] <0.3522.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): mnesia2_tm starting: <0.3528.0>

2016-04-10 22:35:05.671 [info] <0.3522.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Schema initiated from: default

2016-04-10 22:35:05.671 [info] <0.3522.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): debug fun {mnesia2_tm,init} in ets mnesia2_debug does not exist, ignoring
2016-04-10 22:35:05.672 [info] <0.3522.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): mnesia2_controller starting: <0.3531.0>

2016-04-10 22:35:07.696 [warning] <0.6.0> lager_error_logger_h dropped 29 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:35:07.696 [info] <0.3602.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): mnesia2_monitor starting: <0.3604.0>

2016-04-10 22:35:07.697 [info] <0.3602.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Version: "1.0.0"

2016-04-10 22:35:07.698 [info] <0.3602.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env access_module: mnesia2

2016-04-10 22:35:07.698 [info] <0.3602.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env auto_repair: true

2016-04-10 22:35:07.698 [info] <0.3602.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env backup_module: mnesia2_backup

2016-04-10 22:35:07.698 [info] <0.3602.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env debug: trace

2016-04-10 22:35:07.698 [info] <0.3602.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test7517@testing-worker-linux-docker-c74eb140-3365-linux-12.2016-04-10_22.34.24/Mnesia2.test7517@testing-worker-linux-docker-c74eb140-3365-linux-12"

2016-04-10 22:35:07.698 [info] <0.3602.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env dump_disc_copies_at_startup: true

2016-04-10 22:35:07.699 [info] <0.3602.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env dump_log_load_regulation: false

2016-04-10 22:35:07.699 [info] <0.3602.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env dump_log_time_threshold: 180000

2016-04-10 22:35:07.699 [info] <0.3602.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env dump_log_update_in_place: true

2016-04-10 22:35:07.699 [info] <0.3602.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env dump_log_write_threshold: 1000

2016-04-10 22:35:07.700 [info] <0.3602.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env event_module: mnesia2_event

2016-04-10 22:35:07.700 [info] <0.3602.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env extra_db_nodes: []

2016-04-10 22:35:07.700 [info] <0.3602.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env ignore_fallback_at_startup: false

2016-04-10 22:35:07.700 [info] <0.3602.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env fallback_error_function: {mnesia2,lkill}

2016-04-10 22:35:07.701 [info] <0.3602.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env max_wait_for_decision: infinity

2016-04-10 22:35:07.701 [info] <0.3602.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env schema_location: opt_disc

2016-04-10 22:35:07.701 [info] <0.3608.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.3608.0>
2016-04-10 22:35:07.702 [info] <0.3602.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env core_dir: false

2016-04-10 22:35:07.702 [info] <0.3602.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env pid_sort_order: false

2016-04-10 22:35:07.702 [info] <0.3602.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env no_table_loaders: 2

2016-04-10 22:35:07.703 [info] <0.3602.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env dc_dump_limit: 4

2016-04-10 22:35:07.703 [info] <0.3602.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env send_compressed: 0

2016-04-10 22:35:07.703 [info] <0.3602.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env send_max_packets: 20

2016-04-10 22:35:07.703 [info] <0.3602.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env send_max_transfer_size: 7500

2016-04-10 22:35:07.704 [info] <0.3602.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env async_dirty_buffer_size: 524288

2016-04-10 22:35:07.704 [info] <0.3602.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env async_dirty_max_buffer_file_size: 100000000

2016-04-10 22:35:09.729 [warning] <0.6.0> lager_error_logger_h dropped 37 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:35:09.730 [info] <0.3684.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): mnesia2_monitor starting: <0.3686.0>

2016-04-10 22:35:09.730 [info] <0.3684.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Version: "1.0.0"

2016-04-10 22:35:09.731 [info] <0.3684.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env access_module: mnesia2

2016-04-10 22:35:09.731 [info] <0.3684.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env auto_repair: true

2016-04-10 22:35:09.731 [info] <0.3684.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env backup_module: mnesia2_backup

2016-04-10 22:35:09.731 [info] <0.3684.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env debug: debug

2016-04-10 22:35:09.731 [info] <0.3684.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test7517@testing-worker-linux-docker-c74eb140-3365-linux-12.2016-04-10_22.34.24/Mnesia2.test7517@testing-worker-linux-docker-c74eb140-3365-linux-12"

2016-04-10 22:35:09.731 [info] <0.3684.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env dump_disc_copies_at_startup: true

2016-04-10 22:35:09.732 [info] <0.3684.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env dump_log_load_regulation: false

2016-04-10 22:35:09.732 [info] <0.3684.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env dump_log_time_threshold: 180000

2016-04-10 22:35:09.732 [info] <0.3684.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env dump_log_update_in_place: true

2016-04-10 22:35:09.733 [info] <0.3684.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env dump_log_write_threshold: 1000

2016-04-10 22:35:09.733 [info] <0.3690.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.3690.0>
2016-04-10 22:35:09.733 [info] <0.3684.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env event_module: mnesia2_event

2016-04-10 22:35:09.733 [info] <0.3684.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env extra_db_nodes: []

2016-04-10 22:35:09.733 [info] <0.3684.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env ignore_fallback_at_startup: false

2016-04-10 22:35:09.733 [info] <0.3684.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env fallback_error_function: {mnesia2,lkill}

2016-04-10 22:35:09.733 [info] <0.3684.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env max_wait_for_decision: infinity

2016-04-10 22:35:09.734 [info] <0.3684.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env schema_location: opt_disc

2016-04-10 22:35:09.734 [info] <0.3684.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env core_dir: false

2016-04-10 22:35:09.734 [info] <0.3684.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env pid_sort_order: false

2016-04-10 22:35:09.734 [info] <0.3684.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env no_table_loaders: 2

2016-04-10 22:35:09.734 [info] <0.3684.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env dc_dump_limit: 4

2016-04-10 22:35:09.734 [info] <0.3684.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env send_compressed: 0

2016-04-10 22:35:09.734 [info] <0.3684.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env send_max_packets: 20

2016-04-10 22:35:09.734 [info] <0.3684.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env send_max_transfer_size: 7500

2016-04-10 22:35:09.735 [info] <0.3684.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env async_dirty_buffer_size: 524288

2016-04-10 22:35:09.735 [info] <0.3684.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env async_dirty_max_buffer_file_size: 100000000

2016-04-10 22:35:09.735 [info] <0.3684.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env async_dirty_tx_backlog_threshold: 200000

2016-04-10 22:35:09.735 [info] <0.3684.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env async_dirty_buffer_min_runtime: 10000

2016-04-10 22:35:09.735 [info] <0.3684.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Env async_dirty_buffer_drained_cutoff: 5

2016-04-10 22:35:09.735 [info] <0.3684.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): Mnesia2 debug level set to debug
2016-04-10 22:35:09.736 [info] <0.3684.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): mnesia2_subscr starting: <0.3687.0>

2016-04-10 22:35:09.736 [info] <0.3684.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): mnesia2_locker starting: <0.3688.0>

2016-04-10 22:35:09.736 [info] <0.3684.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): mnesia2_recover starting: <0.3689.0>

2016-04-10 22:35:11.761 [warning] <0.6.0> lager_error_logger_h dropped 69 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:35:11.763 [info] <0.3772.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.3772.0>
2016-04-10 22:35:11.765 [info] <0.7.0> Application mnesia2 started on node 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:35:11.766 [error] <0.3763.0> CRASH REPORT Process <0.3763.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:35:11.766 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:35:13.851 [info] <0.3836.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.3836.0>
2016-04-10 22:35:13.855 [info] <0.7.0> Application mnesia2 started on node 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:35:13.856 [error] <0.3827.0> CRASH REPORT Process <0.3827.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:35:13.856 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:35:14.958 [info] <0.3907.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.3907.0>
2016-04-10 22:35:14.960 [info] <0.7.0> Application mnesia2 started on node 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:35:14.963 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:35:14.969 [info] <0.3968.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.3968.0>
2016-04-10 22:35:16.675 [warning] <0.3962.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:35:19.240 [warning] <0.3962.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:35:19.662 [warning] <0.3962.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:35:22.251 [warning] <0.3962.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:35:30.022 [error] <0.3959.0> CRASH REPORT Process <0.3959.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:35:30.022 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:35:32.139 [info] <0.4537.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.4537.0>
2016-04-10 22:35:32.141 [info] <0.7.0> Application mnesia2 started on node 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:35:38.149 [error] <0.4528.0> CRASH REPORT Process <0.4528.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:35:38.149 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:35:40.242 [info] <0.4637.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.4637.0>
2016-04-10 22:35:40.245 [info] <0.7.0> Application mnesia2 started on node 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:35:41.272 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:35:43.390 [info] <0.4753.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.4753.0>
2016-04-10 22:35:43.393 [info] <0.7.0> Application mnesia2 started on node 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:35:43.398 [error] <0.4744.0> CRASH REPORT Process <0.4744.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:35:43.398 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:35:45.432 [info] <0.4820.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.4820.0>
2016-04-10 22:35:45.435 [info] <0.7.0> Application mnesia2 started on node 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:35:45.474 [error] <0.4811.0> CRASH REPORT Process <0.4811.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:35:45.474 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:35:47.586 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:35:47.599 [info] <0.1790.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.1790.0>
2016-04-10 22:35:47.609 [info] <0.7.0> Application mnesia2 started on node 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:35:47.596 [info] <0.4912.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.4912.0>
2016-04-10 22:35:47.910 [info] <0.7.0> Application mnesia2 started on node 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:35:48.912 [error] <0.1843.0> gen_server <0.1843.0> terminated with reason: killed
2016-04-10 22:35:48.913 [error] <0.1843.0> CRASH REPORT Process <0.1843.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:35:48.913 [error] <0.1781.0> CRASH REPORT Process <0.1781.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:35:48.913 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:35:50.963 [info] <0.1859.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.1859.0>
2016-04-10 22:35:50.966 [info] <0.7.0> Application mnesia2 started on node 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:35:51.968 [error] <0.4976.0> gen_server <0.4976.0> terminated with reason: killed
2016-04-10 22:35:51.968 [error] <0.4976.0> CRASH REPORT Process <0.4976.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:35:51.969 [error] <0.4903.0> CRASH REPORT Process <0.4903.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:35:51.969 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:35:53.033 [error] <0.1850.0> CRASH REPORT Process <0.1850.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:35:53.033 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:35:54.156 [info] <0.1941.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.1941.0>
2016-04-10 22:35:54.159 [info] <0.7.0> Application mnesia2 started on node 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:35:54.160 [error] <0.1935.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_controller:start() at <0.1955.0> exit with reason killed in context child_terminated
2016-04-10 22:35:54.146 [info] <0.5019.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.5019.0>
2016-04-10 22:35:54.148 [info] <0.7.0> Application mnesia2 started on node 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:35:54.162 [error] <0.5010.0> CRASH REPORT Process <0.5010.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:35:54.160 [error] <0.1935.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_controller:start() at <0.1955.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:35:54.160 [error] <0.1931.0> CRASH REPORT Process <0.1931.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:35:54.162 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:35:54.213 [info] <0.5094.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.5094.0>
2016-04-10 22:35:54.160 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:35:58.639 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:35:58.696 [info] <0.5218.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.5218.0>
2016-04-10 22:35:58.701 [info] <0.7.0> Application mnesia2 started on node 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:35:58.687 [info] <0.2010.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.2010.0>
2016-04-10 22:35:58.689 [info] <0.7.0> Application mnesia2 started on node 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:36:08.427 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:36:08.444 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:36:09.581 [info] <0.2132.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.2132.0>
2016-04-10 22:36:09.585 [info] <0.7.0> Application mnesia2 started on node 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:36:09.618 [error] <0.2179.0> gen_server <0.2179.0> terminated with reason: killed
2016-04-10 22:36:09.618 [error] <0.2179.0> CRASH REPORT Process <0.2179.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:09.619 [error] <0.2123.0> CRASH REPORT Process <0.2123.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:09.549 [info] <0.5349.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.5349.0>
2016-04-10 22:36:09.551 [info] <0.7.0> Application mnesia2 started on node 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:36:09.640 [error] <0.5340.0> CRASH REPORT Process <0.5340.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:09.640 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:09.671 [info] <0.5437.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.5437.0>
2016-04-10 22:36:10.247 [error] <0.5428.0> CRASH REPORT Process <0.5428.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:10.247 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:09.619 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:09.897 [info] <0.2220.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.2220.0>
2016-04-10 22:36:11.366 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:36:11.366 [error] <0.2215.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.2239.0> exit with reason killed in context child_terminated
2016-04-10 22:36:11.366 [error] <0.2215.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.2239.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:36:11.367 [error] <0.2211.0> CRASH REPORT Process <0.2211.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:11.367 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:12.427 [info] <0.2323.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.2323.0>
2016-04-10 22:36:12.432 [info] <0.7.0> Application mnesia2 started on node 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:36:12.443 [error] <0.2334.0> gen_server <0.2334.0> terminated with reason: killed
2016-04-10 22:36:12.420 [info] <0.5560.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.5560.0>
2016-04-10 22:36:12.422 [info] <0.7.0> Application mnesia2 started on node 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:36:12.444 [error] <0.5551.0> CRASH REPORT Process <0.5551.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:12.443 [error] <0.2334.0> CRASH REPORT Process <0.2334.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:12.444 [error] <0.2314.0> CRASH REPORT Process <0.2314.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:12.445 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:12.444 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:14.559 [info] <0.2398.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.2398.0>
2016-04-10 22:36:14.567 [info] <0.7.0> Application mnesia2 started on node 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:36:14.580 [error] <0.2409.0> gen_server <0.2409.0> terminated with reason: killed
2016-04-10 22:36:14.550 [info] <0.5671.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.5671.0>
2016-04-10 22:36:14.553 [info] <0.7.0> Application mnesia2 started on node 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:36:14.582 [error] <0.5662.0> CRASH REPORT Process <0.5662.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:14.580 [error] <0.2409.0> CRASH REPORT Process <0.2409.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:14.580 [error] <0.2389.0> CRASH REPORT Process <0.2389.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:14.582 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:14.580 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:16.612 [info] <0.5751.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.5751.0>
2016-04-10 22:36:16.628 [info] <0.7.0> Application mnesia2 started on node 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:36:16.639 [error] <0.5812.0> gen_server <0.5812.0> terminated with reason: killed
2016-04-10 22:36:16.639 [error] <0.5812.0> CRASH REPORT Process <0.5812.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:16.640 [error] <0.5742.0> CRASH REPORT Process <0.5742.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:16.605 [info] <0.2457.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.2457.0>
2016-04-10 22:36:16.606 [info] <0.7.0> Application mnesia2 started on node 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:36:16.640 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:18.061 [error] <0.2448.0> CRASH REPORT Process <0.2448.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:18.061 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:19.168 [info] <0.2546.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.2546.0>
2016-04-10 22:36:19.184 [info] <0.7.0> Application mnesia2 started on node 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:36:19.482 [error] <0.2597.0> gen_server <0.2597.0> terminated with reason: killed
2016-04-10 22:36:19.163 [info] <0.5876.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.5876.0>
2016-04-10 22:36:19.165 [info] <0.7.0> Application mnesia2 started on node 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:36:19.482 [error] <0.5869.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.5871.0> exit with reason killed in context child_terminated
2016-04-10 22:36:19.482 [error] <0.5869.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.5871.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:36:19.482 [error] <0.2597.0> CRASH REPORT Process <0.2597.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:19.482 [error] <0.5870.0> Mnesia2('test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'): ** ERROR ** mnesia2_event got unexpected event: {'EXIT',<0.5873.0>,killed}

2016-04-10 22:36:19.483 [error] <0.2558.0> gen_server <0.2558.0> terminated with reason: killed
2016-04-10 22:36:19.482 [error] <0.5872.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-10 22:36:19.483 [error] <0.2558.0> CRASH REPORT Process <0.2558.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:19.482 [error] <0.5875.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-10 22:36:19.483 [error] <0.2537.0> CRASH REPORT Process <0.2537.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:19.482 [error] <0.5875.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:19.484 [info] <0.7.0> Application mnesia2 exited with reason: shutdown
2016-04-10 22:36:19.483 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:19.401 [info] <0.7.0> Application lager started on node 'd546613o546619n546617@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:36:19.401 [info] <0.7.0> Application poolgirl started on node 'd546613o546619n546617@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:36:19.424 [info] <0.102.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546613o546619n546617@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.102.0>
2016-04-10 22:36:19.440 [info] <0.7.0> Application mnesia2 started on node 'd546613o546619n546617@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:36:21.578 [info] <0.5971.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.5971.0>
2016-04-10 22:36:21.580 [info] <0.7.0> Application mnesia2 started on node 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:36:21.592 [error] <0.6035.0> gen_server <0.6035.0> terminated with reason: killed
2016-04-10 22:36:21.585 [info] <0.2628.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.2628.0>
2016-04-10 22:36:21.590 [info] <0.7.0> Application mnesia2 started on node 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:36:21.593 [error] <0.2619.0> CRASH REPORT Process <0.2619.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:21.592 [error] <0.6035.0> CRASH REPORT Process <0.6035.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:21.593 [error] <0.5962.0> CRASH REPORT Process <0.5962.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:21.593 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:21.593 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:23.703 [info] <0.2698.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.2698.0>
2016-04-10 22:36:23.707 [info] <0.7.0> Application mnesia2 started on node 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:36:23.724 [error] <0.2709.0> gen_server <0.2709.0> terminated with reason: killed
2016-04-10 22:36:23.699 [info] <0.6065.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.6065.0>
2016-04-10 22:36:23.701 [info] <0.7.0> Application mnesia2 started on node 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:36:23.726 [error] <0.6109.0> gen_server <0.6109.0> terminated with reason: killed
2016-04-10 22:36:23.724 [error] <0.2709.0> CRASH REPORT Process <0.2709.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:23.726 [error] <0.6109.0> CRASH REPORT Process <0.6109.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:23.725 [error] <0.2689.0> CRASH REPORT Process <0.2689.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:23.727 [error] <0.6056.0> CRASH REPORT Process <0.6056.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:23.727 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:23.725 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:25.853 [info] <0.2773.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.2773.0>
2016-04-10 22:36:25.868 [info] <0.7.0> Application mnesia2 started on node 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:36:25.877 [error] <0.2825.0> gen_server <0.2825.0> terminated with reason: killed
2016-04-10 22:36:25.877 [error] <0.2825.0> CRASH REPORT Process <0.2825.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:25.878 [error] <0.2764.0> CRASH REPORT Process <0.2764.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:25.832 [info] <0.6151.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.6151.0>
2016-04-10 22:36:25.835 [info] <0.7.0> Application mnesia2 started on node 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:36:25.878 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:26.905 [error] <0.6142.0> CRASH REPORT Process <0.6142.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:26.905 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:28.938 [info] <0.2843.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.2843.0>
2016-04-10 22:36:28.940 [info] <0.7.0> Application mnesia2 started on node 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:36:34.008 [error] <0.2910.0> gen_server <0.2910.0> terminated with reason: killed
2016-04-10 22:36:33.961 [info] <0.6229.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.6229.0>
2016-04-10 22:36:33.988 [info] <0.7.0> Application mnesia2 started on node 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:36:34.010 [error] <0.6282.0> gen_server <0.6282.0> terminated with reason: killed
2016-04-10 22:36:34.008 [error] <0.2910.0> CRASH REPORT Process <0.2910.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:34.010 [error] <0.6282.0> CRASH REPORT Process <0.6282.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:34.009 [error] <0.2834.0> CRASH REPORT Process <0.2834.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:34.011 [error] <0.6220.0> CRASH REPORT Process <0.6220.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:34.011 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:34.009 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:35.187 [info] <0.2942.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.2942.0>
2016-04-10 22:36:35.203 [info] <0.7.0> Application mnesia2 started on node 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:36:35.277 [error] <0.3003.0> gen_server <0.3003.0> terminated with reason: killed
2016-04-10 22:36:35.277 [error] <0.3003.0> CRASH REPORT Process <0.3003.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:35.277 [error] <0.2994.0> gen_server <0.2994.0> terminated with reason: killed
2016-04-10 22:36:35.278 [error] <0.2994.0> CRASH REPORT Process <0.2994.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:35.278 [error] <0.2933.0> CRASH REPORT Process <0.2933.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:35.179 [info] <0.6339.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.6339.0>
2016-04-10 22:36:35.181 [info] <0.7.0> Application mnesia2 started on node 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:36:35.380 [error] <0.6330.0> CRASH REPORT Process <0.6330.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:35.214 [info] <0.193.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546613o546619n546617@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.193.0>
2016-04-10 22:36:35.219 [info] <0.7.0> Application mnesia2 started on node 'd546613o546619n546617@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:36:35.402 [error] <0.278.0> gen_server <0.278.0> terminated with reason: killed
2016-04-10 22:36:35.402 [error] <0.278.0> CRASH REPORT Process <0.278.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:35.571 [info] <0.297.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546613o546619n546617@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.297.0>
2016-04-10 22:36:36.122 [warning] <0.6.0> lager_error_logger_h dropped 30 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:36:36.122 [error] <0.367.0> gen_server <0.367.0> terminated with reason: killed
2016-04-10 22:36:36.122 [error] <0.367.0> CRASH REPORT Process <0.367.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:36.122 [error] <0.288.0> CRASH REPORT Process <0.288.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:35.381 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:35.574 [info] <0.6461.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.6461.0>
2016-04-10 22:36:35.278 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:35.304 [info] <0.3033.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.3033.0>
2016-04-10 22:36:35.439 [info] <0.3128.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.3128.0>
2016-04-10 22:36:36.122 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:36.146 [info] <0.393.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546613o546619n546617@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.393.0>
2016-04-10 22:36:36.147 [info] <0.7.0> Application mnesia2 started on node 'd546613o546619n546617@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:36:38.185 [warning] <0.6.0> lager_error_logger_h dropped 20 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:36:38.185 [error] <0.6559.0> gen_server <0.6559.0> terminated with reason: killed
2016-04-10 22:36:38.186 [error] <0.6559.0> CRASH REPORT Process <0.6559.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:38.186 [error] <0.6529.0> gen_server <0.6529.0> terminated with reason: killed
2016-04-10 22:36:38.186 [error] <0.6529.0> CRASH REPORT Process <0.6529.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:38.186 [error] <0.6452.0> CRASH REPORT Process <0.6452.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:38.207 [warning] <0.6.0> lager_error_logger_h dropped 33 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:36:38.207 [error] <0.3119.0> CRASH REPORT Process <0.3119.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:38.233 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:36:38.255 [info] <0.499.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546613o546619n546617@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.499.0>
2016-04-10 22:36:38.257 [info] <0.7.0> Application mnesia2 started on node 'd546613o546619n546617@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:36:38.842 [error] <0.572.0> gen_server <0.572.0> terminated with reason: killed
2016-04-10 22:36:38.842 [error] <0.572.0> CRASH REPORT Process <0.572.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:38.842 [error] <0.566.0> gen_server <0.566.0> terminated with reason: killed
2016-04-10 22:36:38.843 [error] <0.566.0> CRASH REPORT Process <0.566.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:38.843 [error] <0.490.0> CRASH REPORT Process <0.490.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:38.207 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:38.302 [info] <0.3242.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.3242.0>
2016-04-10 22:36:38.307 [info] <0.7.0> Application mnesia2 started on node 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:36:38.962 [error] <0.3233.0> CRASH REPORT Process <0.3233.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:38.186 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:38.301 [info] <0.6576.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.6576.0>
2016-04-10 22:36:38.328 [info] <0.7.0> Application mnesia2 started on node 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:36:39.001 [warning] <0.6.0> lager_error_logger_h dropped 6 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:36:39.024 [info] <0.6686.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.6686.0>
2016-04-10 22:36:38.962 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:39.027 [info] <0.3351.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.3351.0>
2016-04-10 22:36:39.043 [info] <0.7.0> Application mnesia2 started on node 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:36:38.843 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:38.867 [info] <0.597.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546613o546619n546617@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.597.0>
2016-04-10 22:36:38.998 [info] <0.698.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546613o546619n546617@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.698.0>
2016-04-10 22:36:39.847 [error] <0.3421.0> gen_server <0.3421.0> terminated with reason: killed
2016-04-10 22:36:39.847 [error] <0.3421.0> CRASH REPORT Process <0.3421.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:39.847 [error] <0.3390.0> gen_server <0.3390.0> terminated with reason: killed
2016-04-10 22:36:39.847 [error] <0.3390.0> CRASH REPORT Process <0.3390.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:39.848 [error] <0.3342.0> CRASH REPORT Process <0.3342.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:39.329 [info] <0.7.0> Application mnesia2 started on node 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:36:39.848 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:39.898 [info] <0.3447.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.3447.0>
2016-04-10 22:36:41.047 [error] <0.6681.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.6707.0> exit with reason killed in context child_terminated
2016-04-10 22:36:41.048 [error] <0.6681.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.6707.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:36:40.984 [warning] <0.6.0> lager_error_logger_h dropped 32 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:36:41.001 [info] <0.3525.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.3525.0>
2016-04-10 22:36:41.009 [info] <0.7.0> Application mnesia2 started on node 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:36:41.052 [error] <0.3573.0> gen_server <0.3573.0> terminated with reason: killed
2016-04-10 22:36:41.048 [error] <0.6799.0> gen_server <0.6799.0> terminated with reason: killed
2016-04-10 22:36:41.049 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:36:41.049 [error] <0.771.0> gen_server <0.771.0> terminated with reason: killed
2016-04-10 22:36:41.048 [error] <0.6799.0> CRASH REPORT Process <0.6799.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:41.052 [error] <0.3573.0> CRASH REPORT Process <0.3573.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:41.049 [error] <0.771.0> CRASH REPORT Process <0.771.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:41.048 [error] <0.6754.0> gen_server <0.6754.0> terminated with reason: killed
2016-04-10 22:36:41.052 [error] <0.3538.0> gen_server <0.3538.0> terminated with reason: killed
2016-04-10 22:36:41.048 [error] <0.6754.0> CRASH REPORT Process <0.6754.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:41.058 [error] <0.689.0> CRASH REPORT Process <0.689.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:41.052 [error] <0.3538.0> CRASH REPORT Process <0.3538.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:41.049 [error] <0.6677.0> CRASH REPORT Process <0.6677.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:41.052 [error] <0.3516.0> CRASH REPORT Process <0.3516.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:41.052 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:41.145 [info] <0.3603.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.3603.0>
2016-04-10 22:36:41.149 [info] <0.7.0> Application mnesia2 started on node 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:36:41.190 [error] <0.3655.0> gen_server <0.3655.0> terminated with reason: killed
2016-04-10 22:36:41.190 [error] <0.3655.0> CRASH REPORT Process <0.3655.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:41.191 [error] <0.3594.0> CRASH REPORT Process <0.3594.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:41.191 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:41.224 [info] <0.3698.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.3698.0>
2016-04-10 22:36:41.294 [info] <0.3788.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.3788.0>
2016-04-10 22:36:41.377 [info] <0.3888.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.3888.0>
2016-04-10 22:36:41.049 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:41.130 [info] <0.6832.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.6832.0>
2016-04-10 22:36:41.132 [info] <0.7.0> Application mnesia2 started on node 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:36:41.375 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:36:41.891 [info] <0.6945.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.6945.0>
2016-04-10 22:36:41.979 [info] <0.7028.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.7028.0>
2016-04-10 22:36:41.058 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:42.482 [warning] <0.6.0> lager_error_logger_h dropped 36 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:36:42.502 [info] <0.3970.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.3970.0>
2016-04-10 22:36:42.515 [info] <0.7.0> Application mnesia2 started on node 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:36:42.557 [error] <0.4021.0> gen_server <0.4021.0> terminated with reason: killed
2016-04-10 22:36:42.558 [error] <0.7019.0> CRASH REPORT Process <0.7019.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:42.557 [error] <0.4021.0> CRASH REPORT Process <0.4021.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:42.558 [error] <0.3961.0> CRASH REPORT Process <0.3961.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:42.635 [info] <0.850.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546613o546619n546617@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.850.0>
2016-04-10 22:36:42.644 [info] <0.7.0> Application mnesia2 started on node 'd546613o546619n546617@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:36:42.723 [error] <0.840.0> CRASH REPORT Process <0.840.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:42.558 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:42.608 [info] <0.7129.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.7129.0>
2016-04-10 22:36:42.610 [info] <0.7.0> Application mnesia2 started on node 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:36:42.721 [error] <0.7185.0> Supervisor {<0.7185.0>,poolgirl_sup} had child undefined started with {mnesia2_async_dirty_sender,start_link,undefined} at <0.7188.0> exit with reason {aborted,{node_not_running,'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'}} in context child_terminated
2016-04-10 22:36:42.721 [error] <0.7185.0> gen_server <0.7185.0> terminated with reason: killed
2016-04-10 22:36:42.721 [error] <0.7185.0> CRASH REPORT Process <0.7185.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:42.724 [error] <0.7120.0> CRASH REPORT Process <0.7120.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:42.723 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:42.749 [info] <0.952.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546613o546619n546617@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.952.0>
2016-04-10 22:36:42.751 [info] <0.7.0> Application mnesia2 started on node 'd546613o546619n546617@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:36:42.789 [error] <0.1001.0> gen_server <0.1001.0> terminated with reason: killed
2016-04-10 22:36:42.789 [error] <0.1001.0> CRASH REPORT Process <0.1001.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:42.790 [error] <0.1010.0> gen_server <0.1010.0> terminated with reason: killed
2016-04-10 22:36:42.790 [error] <0.1010.0> CRASH REPORT Process <0.1010.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:42.790 [error] <0.996.0> gen_server <0.996.0> terminated with reason: killed
2016-04-10 22:36:42.790 [error] <0.996.0> CRASH REPORT Process <0.996.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:42.558 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:42.635 [info] <0.4063.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.4063.0>
2016-04-10 22:36:42.752 [info] <0.4154.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.4154.0>
2016-04-10 22:36:42.822 [info] <0.4232.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.4232.0>
2016-04-10 22:36:42.771 [info] <0.7240.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.7240.0>
2016-04-10 22:36:42.840 [info] <0.7332.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.7332.0>
2016-04-10 22:36:42.823 [info] <0.1029.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546613o546619n546617@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.1029.0>
2016-04-10 22:36:52.848 [warning] <0.6.0> lager_error_logger_h dropped 28 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:36:52.848 [error] <0.7325.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at undefined exit with reason killed in context start_error
2016-04-10 22:36:52.848 [error] <0.7328.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-10 22:36:52.848 [error] <0.7329.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-10 22:36:52.848 [error] <0.7329.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:52.848 [error] <0.7323.0> CRASH REPORT Process <0.7323.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}} in application_master:init/4 line 134
2016-04-10 22:36:52.849 [info] <0.7.0> Application mnesia2 exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}}
2016-04-10 22:36:52.849 [error] <0.7331.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-10 22:36:52.849 [error] <0.7331.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:52.849 [error] <0.7351.0> gen_server mnesia2_snmp_sup terminated with reason: killed
2016-04-10 22:36:52.849 [error] <0.7351.0> CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:52.850 [error] <0.7328.0> CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:52.943 [warning] <0.6.0> lager_error_logger_h dropped 25 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:36:52.943 [error] <0.4223.0> CRASH REPORT Process <0.4223.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:52.942 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:36:52.942 [error] <0.1078.0> gen_server <0.1078.0> terminated with reason: killed
2016-04-10 22:36:52.942 [error] <0.1078.0> CRASH REPORT Process <0.1078.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:52.942 [error] <0.1073.0> gen_server <0.1073.0> terminated with reason: killed
2016-04-10 22:36:52.942 [error] <0.1073.0> CRASH REPORT Process <0.1073.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:52.943 [error] <0.1020.0> CRASH REPORT Process <0.1020.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:52.943 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:52.943 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:55.328 [info] <0.7441.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.7441.0>
2016-04-10 22:36:55.330 [info] <0.7.0> Application mnesia2 started on node 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:36:59.720 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:36:59.864 [info] <0.7577.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.7577.0>
2016-04-10 22:37:00.169 [info] <0.7.0> Application mnesia2 started on node 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:36:59.867 [info] <0.1125.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546613o546619n546617@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.1125.0>
2016-04-10 22:37:00.187 [info] <0.7.0> Application mnesia2 started on node 'd546613o546619n546617@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:36:59.870 [info] <0.4323.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.4323.0>
2016-04-10 22:36:59.888 [info] <0.7.0> Application mnesia2 started on node 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:37:06.284 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:06.433 [info] <0.1242.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546613o546619n546617@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.1242.0>
2016-04-10 22:37:06.738 [info] <0.7.0> Application mnesia2 started on node 'd546613o546619n546617@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:37:06.292 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:06.431 [info] <0.7707.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.7707.0>
2016-04-10 22:37:06.736 [info] <0.7.0> Application mnesia2 started on node 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:37:06.301 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:06.465 [info] <0.4438.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.4438.0>
2016-04-10 22:37:06.479 [info] <0.7.0> Application mnesia2 started on node 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:37:12.835 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:12.978 [info] <0.1359.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546613o546619n546617@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.1359.0>
2016-04-10 22:37:13.300 [info] <0.7.0> Application mnesia2 started on node 'd546613o546619n546617@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:37:12.860 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:12.972 [info] <0.7837.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.7837.0>
2016-04-10 22:37:12.974 [info] <0.7.0> Application mnesia2 started on node 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:37:12.860 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:12.997 [info] <0.4553.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.4553.0>
2016-04-10 22:37:13.005 [info] <0.7.0> Application mnesia2 started on node 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:37:29.606 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:29.739 [info] <0.8976.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.8976.0>
2016-04-10 22:37:29.741 [info] <0.7.0> Application mnesia2 started on node 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:37:29.609 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:29.749 [info] <0.5677.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.5677.0>
2016-04-10 22:37:29.760 [info] <0.7.0> Application mnesia2 started on node 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:37:29.607 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:29.749 [info] <0.2486.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546613o546619n546617@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.2486.0>
2016-04-10 22:37:29.757 [info] <0.7.0> Application mnesia2 started on node 'd546613o546619n546617@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:37:36.234 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:36.359 [info] <0.5801.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.5801.0>
2016-04-10 22:37:36.690 [info] <0.7.0> Application mnesia2 started on node 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:37:36.237 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:36.374 [info] <0.2610.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546613o546619n546617@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.2610.0>
2016-04-10 22:37:36.389 [info] <0.7.0> Application mnesia2 started on node 'd546613o546619n546617@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:37:36.227 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:36.358 [info] <0.9114.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.9114.0>
2016-04-10 22:37:36.663 [info] <0.7.0> Application mnesia2 started on node 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:37:43.062 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:43.208 [info] <0.10595.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.10595.0>
2016-04-10 22:37:43.516 [info] <0.7.0> Application mnesia2 started on node 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:37:43.065 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:43.221 [info] <0.7274.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.7274.0>
2016-04-10 22:37:43.259 [info] <0.7.0> Application mnesia2 started on node 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:37:43.079 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:43.210 [info] <0.4080.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546613o546619n546617@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.4080.0>
2016-04-10 22:37:43.234 [info] <0.7.0> Application mnesia2 started on node 'd546613o546619n546617@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:37:49.735 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:49.924 [info] <0.8363.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.8363.0>
2016-04-10 22:37:49.938 [info] <0.7.0> Application mnesia2 started on node 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:37:49.752 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:49.916 [info] <0.11043.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.11043.0>
2016-04-10 22:37:49.919 [info] <0.7.0> Application mnesia2 started on node 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:37:49.779 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:49.922 [info] <0.6145.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546613o546619n546617@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.6145.0>
2016-04-10 22:37:50.226 [info] <0.7.0> Application mnesia2 started on node 'd546613o546619n546617@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:37:56.351 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:56.517 [info] <0.11172.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.11172.0>
2016-04-10 22:37:56.822 [info] <0.7.0> Application mnesia2 started on node 'test7517@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:37:56.376 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:56.524 [info] <0.8478.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.8478.0>
2016-04-10 22:37:56.527 [info] <0.7.0> Application mnesia2 started on node 'd546599o546625n546623@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:37:56.388 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:56.519 [info] <0.6940.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd546613o546619n546617@testing-worker-linux-docker-c74eb140-3365-linux-12', <0.6940.0>
2016-04-10 22:37:56.522 [info] <0.7.0> Application mnesia2 started on node 'd546613o546619n546617@testing-worker-linux-docker-c74eb140-3365-linux-12'
2016-04-10 22:38:02.995 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:38:02.990 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:38:03.019 [info] <0.7.0> Application mnesia2 exited with reason: stopped
