2016-04-10 22:39:16.045 [info] <0.7.0> Application lager started on node 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:39:16.045 [info] <0.7.0> Application poolgirl started on node 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:39:16.098 [info] <0.99.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.99.0>
2016-04-10 22:39:16.108 [info] <0.7.0> Application mnesia2 started on node 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:39:16.252 [error] <0.155.0> gen_server <0.155.0> terminated with reason: killed
2016-04-10 22:39:15.254 [info] <0.7.0> Application lager started on node 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:39:15.254 [info] <0.7.0> Application poolgirl started on node 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:39:15.280 [info] <0.494.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.494.0>
2016-04-10 22:39:15.303 [info] <0.562.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.562.0>
2016-04-10 22:39:15.817 [info] <0.672.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.672.0>
2016-04-10 22:39:16.253 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:16.252 [error] <0.155.0> CRASH REPORT Process <0.155.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:39:16.253 [error] <0.90.0> CRASH REPORT Process <0.90.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:16.253 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:16.295 [info] <0.798.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.798.0>
2016-04-10 22:39:16.297 [info] <0.7.0> Application mnesia2 started on node 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:39:16.473 [error] <0.792.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): ** ERROR ** (ignoring core) ** FATAL ** A fallback is installed and Mnesia2 must be restarted. Forcing shutdown after mnesia2_down from 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9'...

2016-04-10 22:39:16.475 [error] <0.793.0> Supervisor mnesia2_kernel_sup had child mnesia2_locker started with mnesia2_locker:start() at <0.796.0> exit with reason killed in context child_terminated
2016-04-10 22:39:16.475 [error] <0.793.0> Supervisor mnesia2_kernel_sup had child mnesia2_locker started with mnesia2_locker:start() at <0.796.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:39:16.253 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:16.309 [info] <0.215.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.215.0>
2016-04-10 22:39:16.578 [info] <0.368.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.368.0>
2016-04-10 22:39:16.512 [info] <0.926.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.926.0>
2016-04-10 22:39:17.121 [warning] <0.6.0> lager_error_logger_h dropped 14 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:39:17.121 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:39:17.134 [info] <0.1026.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.1026.0>
2016-04-10 22:39:17.136 [info] <0.7.0> Application mnesia2 started on node 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:39:17.120 [warning] <0.6.0> lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:39:17.120 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:39:17.151 [info] <0.458.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.458.0>
2016-04-10 22:39:17.158 [info] <0.7.0> Application mnesia2 started on node 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:39:17.877 [error] <0.516.0> gen_server <0.516.0> terminated with reason: killed
2016-04-10 22:39:17.878 [error] <0.1019.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.1021.0> exit with reason killed in context child_terminated
2016-04-10 22:39:17.877 [error] <0.516.0> CRASH REPORT Process <0.516.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:39:17.878 [error] <0.1019.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.1021.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:39:17.877 [error] <0.449.0> CRASH REPORT Process <0.449.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:17.879 [error] <0.1017.0> CRASH REPORT Process <0.1017.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:17.877 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:17.946 [info] <0.547.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.547.0>
2016-04-10 22:39:18.787 [error] <0.664.0> gen_server <0.664.0> terminated with reason: killed
2016-04-10 22:39:18.787 [error] <0.664.0> CRASH REPORT Process <0.664.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:39:18.787 [error] <0.538.0> CRASH REPORT Process <0.538.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:17.879 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:17.945 [info] <0.1149.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.1149.0>
2016-04-10 22:39:18.249 [info] <0.7.0> Application mnesia2 started on node 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:39:18.346 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:39:18.358 [info] <0.1262.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.1262.0>
2016-04-10 22:39:18.831 [info] <0.1494.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.1494.0>
2016-04-10 22:39:18.787 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:18.836 [info] <0.763.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.763.0>
2016-04-10 22:39:18.839 [info] <0.7.0> Application mnesia2 started on node 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:39:18.960 [error] <0.754.0> CRASH REPORT Process <0.754.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:19.002 [info] <0.1608.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.1608.0>
2016-04-10 22:39:19.002 [warning] <0.6.0> lager_error_logger_h dropped 7 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:39:19.004 [info] <0.7.0> Application mnesia2 started on node 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:39:19.148 [error] <0.1664.0> gen_server <0.1664.0> terminated with reason: killed
2016-04-10 22:39:18.960 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:19.008 [info] <0.862.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.862.0>
2016-04-10 22:39:19.046 [info] <0.7.0> Application mnesia2 started on node 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:39:19.148 [error] <0.853.0> CRASH REPORT Process <0.853.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:19.148 [error] <0.1664.0> CRASH REPORT Process <0.1664.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:39:19.149 [error] <0.1599.0> CRASH REPORT Process <0.1599.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:19.149 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:19.218 [info] <0.963.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.963.0>
2016-04-10 22:39:19.513 [info] <0.1069.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.1069.0>
2016-04-10 22:39:19.718 [info] <0.1168.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.1168.0>
2016-04-10 22:39:19.149 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:19.213 [info] <0.1724.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.1724.0>
2016-04-10 22:39:19.493 [info] <0.1850.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.1850.0>
2016-04-10 22:39:19.712 [info] <0.1981.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.1981.0>
2016-04-10 22:39:19.946 [info] <0.2114.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.2114.0>
2016-04-10 22:39:19.949 [info] <0.1269.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.1269.0>
2016-04-10 22:39:20.468 [warning] <0.6.0> lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:39:20.468 [error] <0.1324.0> gen_server <0.1324.0> terminated with reason: killed
2016-04-10 22:39:20.249 [warning] <0.6.0> lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:39:20.251 [info] <0.7.0> Application mnesia2 started on node 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:39:20.471 [error] <0.2105.0> CRASH REPORT Process <0.2105.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:20.468 [error] <0.1324.0> CRASH REPORT Process <0.1324.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:39:20.469 [error] <0.1260.0> CRASH REPORT Process <0.1260.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:20.469 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:20.549 [info] <0.1376.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.1376.0>
2016-04-10 22:39:20.552 [info] <0.7.0> Application mnesia2 started on node 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:39:20.745 [error] <0.1425.0> gen_server <0.1425.0> terminated with reason: killed
2016-04-10 22:39:20.745 [error] <0.1425.0> CRASH REPORT Process <0.1425.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:39:20.822 [info] <0.1463.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.1463.0>
2016-04-10 22:39:21.020 [warning] <0.6.0> lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:39:21.040 [info] <0.1575.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.1575.0>
2016-04-10 22:39:21.043 [info] <0.7.0> Application mnesia2 started on node 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:39:21.200 [error] <0.1627.0> gen_server <0.1627.0> terminated with reason: killed
2016-04-10 22:39:20.471 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:20.543 [info] <0.2255.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.2255.0>
2016-04-10 22:39:20.817 [info] <0.2386.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.2386.0>
2016-04-10 22:39:21.021 [warning] <0.6.0> lager_error_logger_h dropped 26 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:39:21.036 [info] <0.2518.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.2518.0>
2016-04-10 22:39:21.039 [info] <0.7.0> Application mnesia2 started on node 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:39:21.202 [error] <0.2572.0> gen_server <0.2572.0> terminated with reason: killed
2016-04-10 22:39:21.200 [error] <0.1627.0> CRASH REPORT Process <0.1627.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:39:21.202 [error] <0.2572.0> CRASH REPORT Process <0.2572.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:39:21.200 [error] <0.1566.0> CRASH REPORT Process <0.1566.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:21.203 [error] <0.2509.0> CRASH REPORT Process <0.2509.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:21.203 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:21.201 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:21.256 [info] <0.1662.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.1662.0>
2016-04-10 22:39:21.252 [info] <0.2641.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.2641.0>
2016-04-10 22:39:21.553 [info] <0.2769.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.2769.0>
2016-04-10 22:39:21.630 [info] <0.2863.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.2863.0>
2016-04-10 22:39:22.860 [warning] <0.6.0> lager_error_logger_h dropped 8 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:39:22.865 [info] <0.2973.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.2973.0>
2016-04-10 22:39:22.867 [info] <0.7.0> Application mnesia2 started on node 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:39:24.079 [error] <0.2964.0> CRASH REPORT Process <0.2964.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:24.079 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:26.159 [info] <0.3079.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.3079.0>
2016-04-10 22:39:26.162 [info] <0.7.0> Application mnesia2 started on node 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:39:26.164 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:39:26.166 [info] <0.3127.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.3127.0>
2016-04-10 22:39:26.170 [info] <0.3175.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.3175.0>
2016-04-10 22:39:28.274 [info] <0.3247.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.3247.0>
2016-04-10 22:39:28.277 [info] <0.7.0> Application mnesia2 started on node 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:39:28.289 [error] <0.3242.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.3258.0> exit with reason killed in context child_terminated
2016-04-10 22:39:28.290 [error] <0.3242.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.3258.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:39:28.290 [error] <0.3238.0> CRASH REPORT Process <0.3238.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:28.290 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:30.329 [info] <0.3330.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.3330.0>
2016-04-10 22:39:30.333 [info] <0.7.0> Application mnesia2 started on node 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:39:30.339 [info] <0.3324.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Restore aborted. mnesia2_config_backup:open_read["NonExisting.FILE"] -> {enoent,error}

2016-04-10 22:39:30.339 [info] <0.3324.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Restore aborted. mnesia2_config_backup:open_read["/home/travis/build/lrascao/mnesia2/logs/ct_run.test7510@testing-worker-linux-docker-c74eb140-3365-linux-9.2016-04-10_22.38.49/Mnesia2.test7510@testing-worker-linux-docker-c74eb140-3365-linux-9/LATEST.LOG"] -> badarg

2016-04-10 22:39:30.340 [error] <0.3384.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_23,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_23,shutdown]}}}} ({error,{already_started,<0.3408.0>}})

2016-04-10 22:39:30.340 [error] <0.3386.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_25,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_25,shutdown]}}}} ({error,{already_started,<0.3408.0>}})

2016-04-10 22:39:30.341 [error] <0.3385.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_24,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_24,shutdown]}}}} ({error,{already_started,<0.3408.0>}})

2016-04-10 22:39:30.341 [error] <0.3388.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_27,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_27,shutdown]}}}} ({error,{already_started,<0.3408.0>}})

2016-04-10 22:39:30.341 [error] <0.3390.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_29,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_29,shutdown]}}}} ({error,{already_started,<0.3408.0>}})

2016-04-10 22:39:30.341 [error] <0.3389.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_28,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_28,shutdown]}}}} ({error,{already_started,<0.3408.0>}})

2016-04-10 22:39:32.438 [warning] <0.6.0> lager_error_logger_h dropped 18 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:39:32.438 [info] <0.3446.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): mnesia2_monitor starting: <0.3448.0>

2016-04-10 22:39:32.439 [info] <0.3446.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Mnesia2 debug level set to verbose
2016-04-10 22:39:32.440 [info] <0.3446.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): mnesia2_subscr starting: <0.3449.0>

2016-04-10 22:39:32.440 [info] <0.3446.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): mnesia2_locker starting: <0.3450.0>

2016-04-10 22:39:32.440 [info] <0.3446.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): mnesia2_recover starting: <0.3451.0>

2016-04-10 22:39:32.440 [info] <0.3446.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): mnesia2_tm starting: <0.3452.0>

2016-04-10 22:39:32.441 [info] <0.3446.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Schema initiated from: default

2016-04-10 22:39:32.441 [info] <0.3452.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.3452.0>
2016-04-10 22:39:32.441 [info] <0.3446.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): mnesia2_controller starting: <0.3455.0>

2016-04-10 22:39:32.441 [info] <0.3446.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): mnesia2_late_loader starting: <0.3456.0>

2016-04-10 22:39:32.442 [info] <0.3446.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Intend to load tables: []

2016-04-10 22:39:32.442 [info] <0.3446.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): mnesia2_tm_1 starting: <0.3458.0>

2016-04-10 22:39:32.443 [info] <0.3446.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): mnesia2_tm_2 starting: <0.3459.0>

2016-04-10 22:39:32.443 [info] <0.3446.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): mnesia2_tm_3 starting: <0.3460.0>

2016-04-10 22:39:32.443 [info] <0.3446.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): mnesia2_tm_4 starting: <0.3461.0>

2016-04-10 22:39:32.444 [info] <0.3446.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): mnesia2_tm_5 starting: <0.3462.0>

2016-04-10 22:39:32.444 [info] <0.3446.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): mnesia2_tm_6 starting: <0.3463.0>

2016-04-10 22:39:32.444 [info] <0.3446.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): mnesia2_tm_7 starting: <0.3464.0>

2016-04-10 22:39:34.468 [warning] <0.6.0> lager_error_logger_h dropped 15 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:39:34.468 [info] <0.3508.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): mnesia2_monitor starting: <0.3510.0>

2016-04-10 22:39:34.469 [info] <0.3508.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Version: "1.0.0"

2016-04-10 22:39:34.469 [info] <0.3508.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env access_module: mnesia2

2016-04-10 22:39:34.469 [info] <0.3508.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env auto_repair: true

2016-04-10 22:39:34.469 [info] <0.3508.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env backup_module: mnesia2_backup

2016-04-10 22:39:34.470 [info] <0.3508.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env debug: debug

2016-04-10 22:39:34.470 [info] <0.3508.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test7510@testing-worker-linux-docker-c74eb140-3365-linux-9.2016-04-10_22.38.49/Mnesia2.test7510@testing-worker-linux-docker-c74eb140-3365-linux-9"

2016-04-10 22:39:34.470 [info] <0.3508.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env dump_disc_copies_at_startup: true

2016-04-10 22:39:34.470 [info] <0.3508.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env dump_log_load_regulation: false

2016-04-10 22:39:34.470 [info] <0.3508.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env dump_log_time_threshold: 180000

2016-04-10 22:39:34.470 [info] <0.3508.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env dump_log_update_in_place: true

2016-04-10 22:39:34.470 [info] <0.3508.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env dump_log_write_threshold: 1000

2016-04-10 22:39:34.471 [info] <0.3508.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env event_module: mnesia2_event

2016-04-10 22:39:34.471 [info] <0.3508.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env extra_db_nodes: []

2016-04-10 22:39:34.471 [info] <0.3508.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env ignore_fallback_at_startup: false

2016-04-10 22:39:34.471 [info] <0.3508.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env fallback_error_function: {mnesia2,lkill}

2016-04-10 22:39:34.471 [info] <0.3508.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env max_wait_for_decision: infinity

2016-04-10 22:39:34.471 [info] <0.3508.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env schema_location: opt_disc

2016-04-10 22:39:34.472 [info] <0.3508.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env core_dir: false

2016-04-10 22:39:34.472 [info] <0.3508.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env pid_sort_order: false

2016-04-10 22:39:34.472 [info] <0.3508.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env no_table_loaders: 2

2016-04-10 22:39:34.473 [info] <0.3514.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.3514.0>
2016-04-10 22:39:34.473 [info] <0.3508.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env dc_dump_limit: 4

2016-04-10 22:39:34.473 [info] <0.3508.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env send_compressed: 0

2016-04-10 22:39:34.473 [info] <0.3508.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env send_max_packets: 20

2016-04-10 22:39:34.473 [info] <0.3508.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env send_max_transfer_size: 7500

2016-04-10 22:39:34.473 [info] <0.3508.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env async_dirty_buffer_size: 524288

2016-04-10 22:39:34.474 [info] <0.3508.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env async_dirty_max_buffer_file_size: 100000000

2016-04-10 22:39:34.474 [info] <0.3508.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env async_dirty_tx_backlog_threshold: 200000

2016-04-10 22:39:34.474 [info] <0.3508.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env async_dirty_buffer_min_runtime: 10000

2016-04-10 22:39:34.475 [info] <0.3508.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env async_dirty_buffer_drained_cutoff: 5

2016-04-10 22:39:34.475 [info] <0.3508.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Mnesia2 debug level set to debug
2016-04-10 22:39:34.475 [info] <0.3508.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): mnesia2_subscr starting: <0.3511.0>

2016-04-10 22:39:36.500 [warning] <0.6.0> lager_error_logger_h dropped 10 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:39:36.500 [info] <0.3560.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): mnesia2_monitor starting: <0.3562.0>

2016-04-10 22:39:36.501 [info] <0.3560.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Version: "1.0.0"

2016-04-10 22:39:36.501 [info] <0.3560.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env access_module: mnesia2

2016-04-10 22:39:36.501 [info] <0.3560.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env auto_repair: true

2016-04-10 22:39:36.501 [info] <0.3560.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env backup_module: mnesia2_backup

2016-04-10 22:39:36.501 [info] <0.3560.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env debug: trace

2016-04-10 22:39:36.502 [info] <0.3560.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test7510@testing-worker-linux-docker-c74eb140-3365-linux-9.2016-04-10_22.38.49/Mnesia2.test7510@testing-worker-linux-docker-c74eb140-3365-linux-9"

2016-04-10 22:39:36.502 [info] <0.3560.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env dump_disc_copies_at_startup: true

2016-04-10 22:39:36.502 [info] <0.3560.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env dump_log_load_regulation: false

2016-04-10 22:39:36.502 [info] <0.3560.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env dump_log_time_threshold: 180000

2016-04-10 22:39:36.502 [info] <0.3560.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env dump_log_update_in_place: true

2016-04-10 22:39:36.502 [info] <0.3560.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env dump_log_write_threshold: 1000

2016-04-10 22:39:36.502 [info] <0.3560.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env event_module: mnesia2_event

2016-04-10 22:39:36.502 [info] <0.3560.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env extra_db_nodes: []

2016-04-10 22:39:36.502 [info] <0.3560.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env ignore_fallback_at_startup: false

2016-04-10 22:39:36.503 [info] <0.3560.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env fallback_error_function: {mnesia2,lkill}

2016-04-10 22:39:36.503 [info] <0.3560.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env max_wait_for_decision: infinity

2016-04-10 22:39:36.503 [info] <0.3560.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env schema_location: opt_disc

2016-04-10 22:39:36.503 [info] <0.3560.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env core_dir: false

2016-04-10 22:39:36.503 [info] <0.3560.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env pid_sort_order: false

2016-04-10 22:39:36.503 [info] <0.3560.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env no_table_loaders: 2

2016-04-10 22:39:36.503 [info] <0.3560.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env dc_dump_limit: 4

2016-04-10 22:39:36.503 [info] <0.3560.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env send_compressed: 0

2016-04-10 22:39:36.503 [info] <0.3560.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env send_max_packets: 20

2016-04-10 22:39:36.503 [info] <0.3560.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env send_max_transfer_size: 7500

2016-04-10 22:39:36.503 [info] <0.3560.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env async_dirty_buffer_size: 524288

2016-04-10 22:39:36.504 [info] <0.3560.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env async_dirty_max_buffer_file_size: 100000000

2016-04-10 22:39:36.504 [info] <0.3560.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env async_dirty_tx_backlog_threshold: 200000

2016-04-10 22:39:36.504 [info] <0.3560.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env async_dirty_buffer_min_runtime: 10000

2016-04-10 22:39:36.504 [info] <0.3560.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env async_dirty_buffer_drained_cutoff: 5

2016-04-10 22:39:36.504 [info] <0.3560.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Mnesia2 debug level set to trace
2016-04-10 22:39:36.504 [info] <0.3560.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): mnesia2_subscr starting: <0.3563.0>

2016-04-10 22:39:36.504 [info] <0.3560.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): mnesia2_locker starting: <0.3564.0>

2016-04-10 22:39:36.505 [info] <0.3560.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): mnesia2_recover starting: <0.3565.0>

2016-04-10 22:39:36.505 [info] <0.3560.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): mnesia2_tm starting: <0.3566.0>

2016-04-10 22:39:36.506 [info] <0.3560.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Schema initiated from: default

2016-04-10 22:39:36.506 [info] <0.3566.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.3566.0>
2016-04-10 22:39:36.506 [info] <0.3560.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): debug fun {mnesia2_tm,init} in ets mnesia2_debug does not exist, ignoring
2016-04-10 22:39:36.507 [info] <0.3560.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): mnesia2_controller starting: <0.3569.0>

2016-04-10 22:39:36.507 [info] <0.3560.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): mnesia2_late_loader starting: <0.3570.0>

2016-04-10 22:39:36.508 [info] <0.3560.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Intend to load tables: []

2016-04-10 22:39:38.537 [warning] <0.6.0> lager_error_logger_h dropped 12 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:39:38.538 [info] <0.3616.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): mnesia2_monitor starting: <0.3618.0>

2016-04-10 22:39:38.538 [info] <0.3616.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Version: "1.0.0"

2016-04-10 22:39:38.539 [info] <0.3616.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env access_module: mnesia2

2016-04-10 22:39:38.539 [info] <0.3616.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env auto_repair: true

2016-04-10 22:39:38.539 [info] <0.3616.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env backup_module: mnesia2_backup

2016-04-10 22:39:38.539 [info] <0.3616.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env debug: debug

2016-04-10 22:39:38.539 [info] <0.3616.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test7510@testing-worker-linux-docker-c74eb140-3365-linux-9.2016-04-10_22.38.49/Mnesia2.test7510@testing-worker-linux-docker-c74eb140-3365-linux-9"

2016-04-10 22:39:38.540 [info] <0.3616.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env dump_disc_copies_at_startup: true

2016-04-10 22:39:38.540 [info] <0.3616.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env dump_log_load_regulation: false

2016-04-10 22:39:38.540 [info] <0.3616.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env dump_log_time_threshold: 180000

2016-04-10 22:39:38.541 [info] <0.3622.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.3622.0>
2016-04-10 22:39:38.541 [info] <0.3616.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env dump_log_update_in_place: true

2016-04-10 22:39:38.541 [info] <0.3616.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env dump_log_write_threshold: 1000

2016-04-10 22:39:38.541 [info] <0.3616.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env event_module: mnesia2_event

2016-04-10 22:39:38.542 [info] <0.3616.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env extra_db_nodes: []

2016-04-10 22:39:38.542 [info] <0.3616.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env ignore_fallback_at_startup: false

2016-04-10 22:39:38.542 [info] <0.3616.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env fallback_error_function: {mnesia2,lkill}

2016-04-10 22:39:38.542 [info] <0.3616.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env max_wait_for_decision: infinity

2016-04-10 22:39:38.543 [info] <0.3616.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Env schema_location: opt_disc

2016-04-10 22:39:40.566 [warning] <0.6.0> lager_error_logger_h dropped 14 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:39:40.568 [info] <0.3674.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.3674.0>
2016-04-10 22:39:40.571 [info] <0.7.0> Application mnesia2 started on node 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:39:40.572 [error] <0.3665.0> CRASH REPORT Process <0.3665.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:40.572 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:42.666 [info] <0.3738.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.3738.0>
2016-04-10 22:39:42.669 [info] <0.7.0> Application mnesia2 started on node 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:39:42.670 [error] <0.3729.0> CRASH REPORT Process <0.3729.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:42.670 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:43.760 [info] <0.3809.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.3809.0>
2016-04-10 22:39:43.762 [info] <0.7.0> Application mnesia2 started on node 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:39:43.765 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:39:43.771 [info] <0.3870.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.3870.0>
2016-04-10 22:39:54.291 [error] <0.3864.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:39:58.837 [error] <0.3861.0> CRASH REPORT Process <0.3861.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:58.837 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:40:00.978 [info] <0.4491.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.4491.0>
2016-04-10 22:40:00.980 [info] <0.7.0> Application mnesia2 started on node 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:40:07.002 [error] <0.4482.0> CRASH REPORT Process <0.4482.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:07.002 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:40:09.091 [info] <0.4591.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.4591.0>
2016-04-10 22:40:09.094 [info] <0.7.0> Application mnesia2 started on node 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:40:10.111 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:40:12.218 [info] <0.4707.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.4707.0>
2016-04-10 22:40:12.220 [info] <0.7.0> Application mnesia2 started on node 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:40:12.225 [error] <0.4698.0> CRASH REPORT Process <0.4698.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:12.225 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:40:14.359 [info] <0.4774.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.4774.0>
2016-04-10 22:40:14.362 [info] <0.7.0> Application mnesia2 started on node 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:40:14.387 [error] <0.4765.0> CRASH REPORT Process <0.4765.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:14.387 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:40:16.484 [warning] <0.6.0> lager_error_logger_h dropped 33 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:40:16.513 [info] <0.1790.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.1790.0>
2016-04-10 22:40:16.516 [info] <0.7.0> Application mnesia2 started on node 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:40:16.505 [info] <0.4866.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.4866.0>
2016-04-10 22:40:16.508 [info] <0.7.0> Application mnesia2 started on node 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:40:17.518 [error] <0.1841.0> gen_server <0.1841.0> terminated with reason: killed
2016-04-10 22:40:17.519 [error] <0.1841.0> CRASH REPORT Process <0.1841.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:40:17.519 [error] <0.1780.0> CRASH REPORT Process <0.1780.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:17.519 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:40:20.135 [info] <0.1857.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.1857.0>
2016-04-10 22:40:20.138 [info] <0.7.0> Application mnesia2 started on node 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:40:21.140 [error] <0.4929.0> gen_server <0.4929.0> terminated with reason: killed
2016-04-10 22:40:21.140 [error] <0.4929.0> CRASH REPORT Process <0.4929.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:40:21.141 [error] <0.4857.0> CRASH REPORT Process <0.4857.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:21.141 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:40:22.192 [error] <0.1848.0> CRASH REPORT Process <0.1848.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:22.192 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:40:23.295 [info] <0.4972.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.4972.0>
2016-04-10 22:40:23.298 [info] <0.7.0> Application mnesia2 started on node 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:40:23.317 [error] <0.4963.0> CRASH REPORT Process <0.4963.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:23.303 [info] <0.1939.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.1939.0>
2016-04-10 22:40:23.315 [info] <0.7.0> Application mnesia2 started on node 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:40:23.317 [error] <0.1929.0> CRASH REPORT Process <0.1929.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:23.317 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:40:23.380 [info] <0.5047.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.5047.0>
2016-04-10 22:40:23.317 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:40:27.694 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:40:27.756 [info] <0.5171.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.5171.0>
2016-04-10 22:40:27.761 [info] <0.7.0> Application mnesia2 started on node 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:40:27.748 [info] <0.2008.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.2008.0>
2016-04-10 22:40:27.749 [info] <0.7.0> Application mnesia2 started on node 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:40:37.337 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:40:37.338 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:40:38.505 [info] <0.2130.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.2130.0>
2016-04-10 22:40:38.509 [info] <0.7.0> Application mnesia2 started on node 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:40:38.546 [error] emulator Error in process <0.2198.0> on node 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9' with exit value: {badarg,[{erlang,unlink,[undefined],[]},{mnesia2_tm,commit_participant,6,[{file,"src/mnesia2_tm.erl"},{line,1873}]}]}


2016-04-10 22:40:38.546 [error] <0.2121.0> CRASH REPORT Process <0.2121.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:38.484 [info] <0.5302.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.5302.0>
2016-04-10 22:40:38.487 [info] <0.7.0> Application mnesia2 started on node 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:40:38.567 [error] <0.5293.0> CRASH REPORT Process <0.5293.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:38.567 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:40:38.610 [info] <0.5390.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.5390.0>
2016-04-10 22:40:39.209 [error] <0.5461.0> gen_server <0.5461.0> terminated with reason: killed
2016-04-10 22:40:39.210 [error] <0.5461.0> CRASH REPORT Process <0.5461.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:40:39.210 [error] <0.5381.0> CRASH REPORT Process <0.5381.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:39.210 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:40:38.546 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:40:38.841 [info] <0.2218.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.2218.0>
2016-04-10 22:40:40.331 [warning] <0.6.0> lager_error_logger_h dropped 12 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:40:40.331 [error] <0.2209.0> CRASH REPORT Process <0.2209.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:40.331 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:40:41.391 [info] <0.2321.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.2321.0>
2016-04-10 22:40:41.398 [info] <0.7.0> Application mnesia2 started on node 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:40:41.430 [error] <0.2341.0> gen_server <0.2341.0> terminated with reason: killed
2016-04-10 22:40:41.384 [info] <0.5513.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.5513.0>
2016-04-10 22:40:41.386 [info] <0.7.0> Application mnesia2 started on node 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:40:41.432 [error] <0.5577.0> gen_server <0.5577.0> terminated with reason: killed
2016-04-10 22:40:41.430 [error] <0.2341.0> CRASH REPORT Process <0.2341.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:40:41.432 [error] <0.5577.0> CRASH REPORT Process <0.5577.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:40:41.431 [error] <0.2312.0> CRASH REPORT Process <0.2312.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:41.433 [error] <0.5504.0> CRASH REPORT Process <0.5504.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:41.433 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:40:41.431 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:40:43.531 [info] <0.2396.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.2396.0>
2016-04-10 22:40:43.537 [info] <0.7.0> Application mnesia2 started on node 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:40:43.539 [error] <0.2387.0> CRASH REPORT Process <0.2387.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:43.523 [info] <0.5624.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.5624.0>
2016-04-10 22:40:43.526 [info] <0.7.0> Application mnesia2 started on node 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:40:43.539 [error] <0.5688.0> gen_server <0.5688.0> terminated with reason: killed
2016-04-10 22:40:43.539 [error] <0.5688.0> CRASH REPORT Process <0.5688.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:40:43.540 [error] <0.5615.0> CRASH REPORT Process <0.5615.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:43.541 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:40:43.539 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:40:45.578 [info] <0.5704.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.5704.0>
2016-04-10 22:40:45.593 [info] <0.7.0> Application mnesia2 started on node 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:40:45.604 [error] <0.5763.0> gen_server <0.5763.0> terminated with reason: killed
2016-04-10 22:40:45.604 [error] <0.5763.0> CRASH REPORT Process <0.5763.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:40:45.604 [error] <0.5695.0> CRASH REPORT Process <0.5695.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:45.567 [info] <0.2455.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.2455.0>
2016-04-10 22:40:45.568 [info] <0.7.0> Application mnesia2 started on node 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:40:45.604 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:40:47.053 [error] <0.2446.0> CRASH REPORT Process <0.2446.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:47.053 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:40:48.163 [info] <0.5829.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.5829.0>
2016-04-10 22:40:48.165 [info] <0.7.0> Application mnesia2 started on node 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:40:48.466 [error] <0.5823.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): ** ERROR ** mnesia2_event got unexpected event: {'EXIT',<0.5826.0>,killed}

2016-04-10 22:40:48.169 [info] <0.2544.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.2544.0>
2016-04-10 22:40:48.177 [info] <0.7.0> Application mnesia2 started on node 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:40:48.465 [error] <0.2595.0> gen_server <0.2595.0> terminated with reason: killed
2016-04-10 22:40:48.466 [error] <0.5822.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.5824.0> exit with reason killed in context child_terminated
2016-04-10 22:40:48.465 [error] <0.2595.0> CRASH REPORT Process <0.2595.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:40:48.466 [error] <0.5822.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.5824.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:40:48.466 [error] <0.2585.0> gen_server <0.2585.0> terminated with reason: killed
2016-04-10 22:40:48.466 [error] <0.5825.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-10 22:40:48.466 [error] <0.5828.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-10 22:40:48.466 [error] <0.5828.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:40:48.466 [error] <0.2585.0> CRASH REPORT Process <0.2585.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:40:48.466 [error] <0.2535.0> CRASH REPORT Process <0.2535.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:48.468 [info] <0.7.0> Application mnesia2 exited with reason: shutdown
2016-04-10 22:40:48.466 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:40:48.382 [info] <0.7.0> Application lager started on node 'd686212o686220n686220@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:40:48.382 [info] <0.7.0> Application poolgirl started on node 'd686212o686220n686220@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:40:48.407 [info] <0.101.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686212o686220n686220@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.101.0>
2016-04-10 22:40:48.423 [info] <0.7.0> Application mnesia2 started on node 'd686212o686220n686220@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:40:50.585 [info] <0.5924.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.5924.0>
2016-04-10 22:40:50.587 [info] <0.7.0> Application mnesia2 started on node 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:40:50.619 [error] <0.5988.0> gen_server <0.5988.0> terminated with reason: killed
2016-04-10 22:40:50.609 [info] <0.2626.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.2626.0>
2016-04-10 22:40:50.614 [info] <0.7.0> Application mnesia2 started on node 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:40:50.619 [error] <0.2617.0> CRASH REPORT Process <0.2617.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:50.619 [error] <0.5988.0> CRASH REPORT Process <0.5988.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:40:50.621 [error] <0.5915.0> CRASH REPORT Process <0.5915.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:50.621 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:40:50.620 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:40:52.709 [info] <0.2696.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.2696.0>
2016-04-10 22:40:52.713 [info] <0.7.0> Application mnesia2 started on node 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:40:52.716 [error] <0.2708.0> gen_server <0.2708.0> terminated with reason: killed
2016-04-10 22:40:52.705 [info] <0.6018.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.6018.0>
2016-04-10 22:40:52.707 [info] <0.7.0> Application mnesia2 started on node 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:40:52.717 [error] <0.6009.0> CRASH REPORT Process <0.6009.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:52.717 [error] <0.2708.0> CRASH REPORT Process <0.2708.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:40:52.717 [error] <0.2687.0> CRASH REPORT Process <0.2687.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:52.717 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:40:52.717 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:40:54.839 [info] <0.2771.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.2771.0>
2016-04-10 22:40:54.844 [info] <0.7.0> Application mnesia2 started on node 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:40:54.845 [error] <0.2820.0> gen_server <0.2820.0> terminated with reason: killed
2016-04-10 22:40:54.846 [error] <0.2820.0> CRASH REPORT Process <0.2820.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:40:54.846 [error] <0.2762.0> CRASH REPORT Process <0.2762.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:54.833 [info] <0.6104.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.6104.0>
2016-04-10 22:40:54.836 [info] <0.7.0> Application mnesia2 started on node 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:40:54.846 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:40:55.878 [error] <0.6095.0> CRASH REPORT Process <0.6095.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:55.878 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:40:57.929 [info] <0.2841.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.2841.0>
2016-04-10 22:40:57.931 [info] <0.7.0> Application mnesia2 started on node 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:41:02.969 [info] <0.6182.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.6182.0>
2016-04-10 22:41:03.000 [info] <0.7.0> Application mnesia2 started on node 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:41:03.010 [error] <0.6245.0> gen_server <0.6245.0> terminated with reason: killed
2016-04-10 22:41:03.012 [error] <0.2908.0> gen_server <0.2908.0> terminated with reason: killed
2016-04-10 22:41:03.010 [error] <0.6245.0> CRASH REPORT Process <0.6245.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:03.012 [error] <0.2908.0> CRASH REPORT Process <0.2908.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:03.010 [error] <0.6173.0> CRASH REPORT Process <0.6173.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:03.012 [error] <0.2832.0> CRASH REPORT Process <0.2832.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:03.010 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:03.012 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:04.197 [info] <0.2940.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.2940.0>
2016-04-10 22:41:04.507 [info] <0.7.0> Application mnesia2 started on node 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:41:04.551 [error] <0.2999.0> gen_server <0.2999.0> terminated with reason: killed
2016-04-10 22:41:04.551 [error] <0.2999.0> CRASH REPORT Process <0.2999.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:04.552 [error] <0.3004.0> gen_server <0.3004.0> terminated with reason: killed
2016-04-10 22:41:04.552 [error] <0.3004.0> CRASH REPORT Process <0.3004.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:04.552 [error] <0.2931.0> CRASH REPORT Process <0.2931.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:04.182 [info] <0.6292.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.6292.0>
2016-04-10 22:41:04.185 [info] <0.7.0> Application mnesia2 started on node 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:41:05.091 [error] <0.6379.0> gen_server <0.6379.0> terminated with reason: killed
2016-04-10 22:41:05.091 [error] <0.6379.0> CRASH REPORT Process <0.6379.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:05.091 [error] <0.6349.0> gen_server <0.6349.0> terminated with reason: killed
2016-04-10 22:41:05.092 [error] <0.6349.0> CRASH REPORT Process <0.6349.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:05.092 [error] <0.6395.0> gen_server <0.6395.0> terminated with reason: killed
2016-04-10 22:41:05.092 [error] <0.6395.0> CRASH REPORT Process <0.6395.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:05.092 [error] <0.6283.0> CRASH REPORT Process <0.6283.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:04.141 [warning] <0.6.0> lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:41:04.205 [info] <0.191.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686212o686220n686220@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.191.0>
2016-04-10 22:41:04.218 [info] <0.7.0> Application mnesia2 started on node 'd686212o686220n686220@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:41:05.113 [error] <0.182.0> CRASH REPORT Process <0.182.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:05.113 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:05.092 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:04.552 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:04.579 [info] <0.3032.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.3032.0>
2016-04-10 22:41:05.066 [info] <0.7.0> Application mnesia2 started on node 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:41:05.136 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:41:05.174 [info] <0.3127.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.3127.0>
2016-04-10 22:41:05.203 [info] <0.296.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686212o686220n686220@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.296.0>
2016-04-10 22:41:05.507 [info] <0.7.0> Application mnesia2 started on node 'd686212o686220n686220@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:41:06.011 [error] <0.371.0> gen_server <0.371.0> terminated with reason: killed
2016-04-10 22:41:06.011 [error] <0.371.0> CRASH REPORT Process <0.371.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:06.011 [error] <0.361.0> gen_server <0.361.0> terminated with reason: killed
2016-04-10 22:41:06.012 [error] <0.361.0> CRASH REPORT Process <0.361.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:06.013 [error] <0.287.0> CRASH REPORT Process <0.287.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:06.013 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:06.038 [info] <0.395.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686212o686220n686220@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.395.0>
2016-04-10 22:41:06.039 [info] <0.7.0> Application mnesia2 started on node 'd686212o686220n686220@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:41:05.207 [info] <0.6414.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.6414.0>
2016-04-10 22:41:05.214 [info] <0.7.0> Application mnesia2 started on node 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:41:08.120 [error] <0.6510.0> gen_server <0.6510.0> terminated with reason: killed
2016-04-10 22:41:08.120 [error] <0.6510.0> CRASH REPORT Process <0.6510.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:08.120 [error] <0.6480.0> gen_server <0.6480.0> terminated with reason: killed
2016-04-10 22:41:08.120 [error] <0.6480.0> CRASH REPORT Process <0.6480.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:08.120 [error] <0.6405.0> CRASH REPORT Process <0.6405.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:08.142 [error] <0.3219.0> gen_server <0.3219.0> terminated with reason: killed
2016-04-10 22:41:08.142 [error] <0.3219.0> CRASH REPORT Process <0.3219.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:08.142 [error] <0.3118.0> CRASH REPORT Process <0.3118.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:08.166 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:41:08.177 [info] <0.501.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686212o686220n686220@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.501.0>
2016-04-10 22:41:08.178 [info] <0.7.0> Application mnesia2 started on node 'd686212o686220n686220@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:41:08.762 [error] <0.575.0> gen_server <0.575.0> terminated with reason: killed
2016-04-10 22:41:08.762 [error] <0.575.0> CRASH REPORT Process <0.575.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:08.762 [error] <0.567.0> gen_server <0.567.0> terminated with reason: killed
2016-04-10 22:41:08.762 [error] <0.567.0> CRASH REPORT Process <0.567.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:08.762 [error] <0.492.0> CRASH REPORT Process <0.492.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:08.120 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:08.241 [info] <0.6529.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.6529.0>
2016-04-10 22:41:08.252 [info] <0.7.0> Application mnesia2 started on node 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:41:08.855 [error] <0.6620.0> gen_server <0.6620.0> terminated with reason: killed
2016-04-10 22:41:08.855 [error] <0.6620.0> CRASH REPORT Process <0.6620.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:08.856 [error] <0.6615.0> gen_server <0.6615.0> terminated with reason: killed
2016-04-10 22:41:08.856 [error] <0.6615.0> CRASH REPORT Process <0.6615.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:08.856 [error] <0.6567.0> gen_server <0.6567.0> terminated with reason: killed
2016-04-10 22:41:08.856 [error] <0.6567.0> CRASH REPORT Process <0.6567.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:08.856 [error] <0.6520.0> CRASH REPORT Process <0.6520.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:08.142 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:08.216 [info] <0.3240.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.3240.0>
2016-04-10 22:41:08.221 [info] <0.7.0> Application mnesia2 started on node 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:41:08.876 [error] <0.3327.0> gen_server <0.3327.0> terminated with reason: killed
2016-04-10 22:41:08.876 [error] <0.3327.0> CRASH REPORT Process <0.3327.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:08.856 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:08.947 [info] <0.6637.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.6637.0>
2016-04-10 22:41:08.946 [info] <0.3348.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.3348.0>
2016-04-10 22:41:08.762 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:08.793 [info] <0.601.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686212o686220n686220@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.601.0>
2016-04-10 22:41:08.917 [info] <0.702.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686212o686220n686220@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.702.0>
2016-04-10 22:41:09.249 [warning] <0.6.0> lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:41:09.249 [info] <0.7.0> Application mnesia2 started on node 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:41:09.753 [error] <0.3415.0> gen_server <0.3415.0> terminated with reason: killed
2016-04-10 22:41:09.753 [error] <0.3422.0> gen_server <0.3422.0> terminated with reason: killed
2016-04-10 22:41:09.753 [error] <0.3415.0> CRASH REPORT Process <0.3415.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:09.753 [error] <0.3422.0> CRASH REPORT Process <0.3422.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:09.753 [error] <0.3339.0> CRASH REPORT Process <0.3339.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:09.753 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:09.799 [info] <0.3446.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.3446.0>
2016-04-10 22:41:10.850 [info] <0.3524.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.3524.0>
2016-04-10 22:41:10.868 [info] <0.7.0> Application mnesia2 started on node 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:41:10.931 [error] <0.3515.0> CRASH REPORT Process <0.3515.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:10.931 [warning] <0.6.0> lager_error_logger_h dropped 34 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:41:10.931 [error] <0.6628.0> CRASH REPORT Process <0.6628.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:10.932 [error] <0.697.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.717.0> exit with reason killed in context child_terminated
2016-04-10 22:41:10.932 [error] <0.697.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.717.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:41:10.933 [error] <0.697.0> Supervisor mnesia2_kernel_sup had child mnesia2_controller started with mnesia2_controller:start() at <0.719.0> exit with reason killed in context shutdown_error
2016-04-10 22:41:10.933 [error] <0.695.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.697.0> exit with reason killed in context child_terminated
2016-04-10 22:41:10.933 [error] <0.695.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.697.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:41:10.933 [error] <0.698.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-10 22:41:10.933 [error] <0.699.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-10 22:41:10.933 [error] <0.699.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:10.934 [error] <0.698.0> CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:10.931 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:11.005 [info] <0.3602.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.3602.0>
2016-04-10 22:41:11.009 [info] <0.7.0> Application mnesia2 started on node 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:41:11.051 [error] <0.3652.0> gen_server <0.3652.0> terminated with reason: killed
2016-04-10 22:41:11.051 [error] <0.3652.0> CRASH REPORT Process <0.3652.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:11.051 [error] <0.3593.0> CRASH REPORT Process <0.3593.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:11.051 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:11.077 [info] <0.3697.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.3697.0>
2016-04-10 22:41:11.145 [info] <0.3787.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.3787.0>
2016-04-10 22:41:11.187 [info] <0.3887.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.3887.0>
2016-04-10 22:41:10.932 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:10.992 [info] <0.6782.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.6782.0>
2016-04-10 22:41:10.994 [info] <0.7.0> Application mnesia2 started on node 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:41:11.185 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:41:11.744 [info] <0.6895.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.6895.0>
2016-04-10 22:41:11.757 [info] <0.7.0> Application mnesia2 started on node 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:41:11.772 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:41:11.810 [info] <0.6978.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.6978.0>
2016-04-10 22:41:10.935 [info] <0.7.0> Application mnesia2 exited with reason: shutdown
2016-04-10 22:41:12.482 [error] <0.7043.0> gen_server <0.7043.0> terminated with reason: killed
2016-04-10 22:41:12.312 [warning] <0.6.0> lager_error_logger_h dropped 38 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:41:12.314 [info] <0.3969.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.3969.0>
2016-04-10 22:41:12.428 [info] <0.7.0> Application mnesia2 started on node 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:41:12.482 [error] <0.3964.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.3971.0> exit with reason killed in context child_terminated
2016-04-10 22:41:12.483 [error] <0.7043.0> CRASH REPORT Process <0.7043.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:12.483 [error] <0.6969.0> CRASH REPORT Process <0.6969.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:12.483 [error] <0.3964.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.3971.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:41:12.486 [error] <0.3966.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-10 22:41:12.486 [error] <0.3966.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:12.486 [error] <0.3965.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-10 22:41:12.486 [error] <0.3965.0> CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:12.568 [info] <0.853.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686212o686220n686220@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.853.0>
2016-04-10 22:41:12.872 [info] <0.7.0> Application mnesia2 started on node 'd686212o686220n686220@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:41:12.948 [error] <0.848.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.868.0> exit with reason killed in context child_terminated
2016-04-10 22:41:12.483 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:12.560 [info] <0.7079.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.7079.0>
2016-04-10 22:41:12.564 [info] <0.7.0> Application mnesia2 started on node 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:41:12.948 [error] <0.7142.0> gen_server <0.7142.0> terminated with reason: killed
2016-04-10 22:41:12.948 [error] <0.7142.0> CRASH REPORT Process <0.7142.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:12.948 [error] <0.848.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.868.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:41:12.949 [error] <0.846.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.848.0> exit with reason shutdown in context child_terminated
2016-04-10 22:41:12.949 [error] <0.846.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.848.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:41:12.950 [info] <0.7.0> Application mnesia2 exited with reason: shutdown
2016-04-10 22:41:12.978 [info] <0.958.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686212o686220n686220@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.958.0>
2016-04-10 22:41:13.026 [error] <0.1007.0> gen_server <0.1007.0> terminated with reason: killed
2016-04-10 22:41:12.571 [info] <0.4061.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.4061.0>
2016-04-10 22:41:12.980 [info] <0.4153.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.4153.0>
2016-04-10 22:41:13.026 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:41:13.026 [error] <0.4144.0> CRASH REPORT Process <0.4144.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:13.026 [error] <0.1007.0> CRASH REPORT Process <0.1007.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:13.000 [info] <0.7190.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.7190.0>
2016-04-10 22:41:13.000 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:41:13.008 [info] <0.7.0> Application mnesia2 started on node 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:41:13.030 [error] <0.7181.0> CRASH REPORT Process <0.7181.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:13.026 [error] <0.1017.0> gen_server <0.1017.0> terminated with reason: killed
2016-04-10 22:41:13.027 [error] <0.1017.0> CRASH REPORT Process <0.1017.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:13.027 [error] <0.1002.0> gen_server <0.1002.0> terminated with reason: killed
2016-04-10 22:41:13.027 [error] <0.1002.0> CRASH REPORT Process <0.1002.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:13.027 [error] <0.949.0> CRASH REPORT Process <0.949.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:13.027 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:13.053 [info] <0.4230.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.4230.0>
2016-04-10 22:41:13.054 [info] <0.7.0> Application mnesia2 started on node 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:41:13.030 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:13.098 [info] <0.7282.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.7282.0>
2016-04-10 22:41:13.027 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:13.051 [info] <0.1036.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686212o686220n686220@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.1036.0>
2016-04-10 22:41:23.105 [error] <0.7275.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at undefined exit with reason killed in context start_error
2016-04-10 22:41:23.105 [error] <0.7278.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-10 22:41:23.105 [error] <0.7281.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-10 22:41:23.105 [error] <0.7281.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:23.105 [error] <0.7301.0> gen_server mnesia2_snmp_sup terminated with reason: killed
2016-04-10 22:41:23.105 [error] <0.7301.0> CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:23.105 [error] <0.7279.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-10 22:41:23.105 [error] <0.7279.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:23.105 [error] <0.7273.0> CRASH REPORT Process <0.7273.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}} in application_master:init/4 line 133
2016-04-10 22:41:23.105 [info] <0.7.0> Application mnesia2 exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}}
2016-04-10 22:41:23.106 [error] <0.7278.0> CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:23.205 [error] <0.1027.0> CRASH REPORT Process <0.1027.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:23.205 [error] <0.4274.0> gen_server <0.4274.0> terminated with reason: killed
2016-04-10 22:41:23.205 [error] <0.4274.0> CRASH REPORT Process <0.4274.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:23.206 [error] <0.4221.0> CRASH REPORT Process <0.4221.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:23.206 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:23.205 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:25.614 [info] <0.7391.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.7391.0>
2016-04-10 22:41:25.616 [info] <0.7.0> Application mnesia2 started on node 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:41:30.586 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:41:30.734 [info] <0.7527.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.7527.0>
2016-04-10 22:41:31.041 [info] <0.7.0> Application mnesia2 started on node 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:41:30.736 [info] <0.4320.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.4320.0>
2016-04-10 22:41:31.057 [info] <0.7.0> Application mnesia2 started on node 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:41:30.754 [info] <0.1133.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686212o686220n686220@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.1133.0>
2016-04-10 22:41:30.764 [info] <0.7.0> Application mnesia2 started on node 'd686212o686220n686220@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:41:37.177 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:41:37.322 [info] <0.1247.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686212o686220n686220@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.1247.0>
2016-04-10 22:41:37.628 [info] <0.7.0> Application mnesia2 started on node 'd686212o686220n686220@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:41:37.201 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:41:37.327 [info] <0.4438.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.4438.0>
2016-04-10 22:41:37.339 [info] <0.7.0> Application mnesia2 started on node 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:41:37.204 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:41:37.324 [info] <0.7657.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.7657.0>
2016-04-10 22:41:37.636 [info] <0.7.0> Application mnesia2 started on node 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:41:43.779 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:41:43.917 [info] <0.1366.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686212o686220n686220@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.1366.0>
2016-04-10 22:41:43.922 [info] <0.7.0> Application mnesia2 started on node 'd686212o686220n686220@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:41:43.777 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:41:43.915 [info] <0.4552.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.4552.0>
2016-04-10 22:41:44.219 [info] <0.7.0> Application mnesia2 started on node 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:41:43.780 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:41:43.907 [info] <0.7787.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.7787.0>
2016-04-10 22:41:43.910 [info] <0.7.0> Application mnesia2 started on node 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:42:02.662 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:02.784 [info] <0.8925.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.8925.0>
2016-04-10 22:42:02.787 [info] <0.7.0> Application mnesia2 started on node 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:42:02.649 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:02.808 [info] <0.2489.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686212o686220n686220@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.2489.0>
2016-04-10 22:42:02.822 [info] <0.7.0> Application mnesia2 started on node 'd686212o686220n686220@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:42:02.644 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:02.814 [info] <0.5678.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.5678.0>
2016-04-10 22:42:02.818 [info] <0.7.0> Application mnesia2 started on node 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:42:09.203 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:09.341 [info] <0.2615.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686212o686220n686220@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.2615.0>
2016-04-10 22:42:09.356 [info] <0.7.0> Application mnesia2 started on node 'd686212o686220n686220@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:42:09.203 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:09.327 [info] <0.9064.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.9064.0>
2016-04-10 22:42:09.329 [info] <0.7.0> Application mnesia2 started on node 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:42:09.208 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:09.346 [info] <0.5800.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.5800.0>
2016-04-10 22:42:09.349 [info] <0.7.0> Application mnesia2 started on node 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:42:15.680 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:15.811 [info] <0.10545.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.10545.0>
2016-04-10 22:42:16.140 [info] <0.7.0> Application mnesia2 started on node 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:42:15.693 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:15.835 [info] <0.4086.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686212o686220n686220@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.4086.0>
2016-04-10 22:42:16.148 [info] <0.7.0> Application mnesia2 started on node 'd686212o686220n686220@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:42:15.703 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:15.841 [info] <0.7268.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.7268.0>
2016-04-10 22:42:15.849 [info] <0.7.0> Application mnesia2 started on node 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:42:22.458 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:22.608 [info] <0.10891.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.10891.0>
2016-04-10 22:42:22.611 [info] <0.7.0> Application mnesia2 started on node 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:42:22.461 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:22.650 [info] <0.8963.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.8963.0>
2016-04-10 22:42:22.657 [info] <0.7.0> Application mnesia2 started on node 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:42:22.466 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:22.647 [info] <0.5308.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686212o686220n686220@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.5308.0>
2016-04-10 22:42:22.951 [info] <0.7.0> Application mnesia2 started on node 'd686212o686220n686220@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:42:29.177 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:29.321 [info] <0.9755.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.9755.0>
2016-04-10 22:42:29.334 [info] <0.7.0> Application mnesia2 started on node 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:42:29.182 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:29.298 [info] <0.11020.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.11020.0>
2016-04-10 22:42:29.304 [info] <0.7.0> Application mnesia2 started on node 'test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:42:29.178 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:29.319 [info] <0.5425.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd686212o686220n686220@testing-worker-linux-docker-c74eb140-3365-linux-9', <0.5425.0>
2016-04-10 22:42:29.624 [info] <0.7.0> Application mnesia2 started on node 'd686212o686220n686220@testing-worker-linux-docker-c74eb140-3365-linux-9'
2016-04-10 22:42:35.860 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:35.893 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:35.866 [info] <0.7.0> Application mnesia2 exited with reason: stopped
