2016-04-12 08:45:30.770 [info] <0.7.0> Application lager started on node 'test8404@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:45:30.770 [info] <0.7.0> Application poolgirl started on node 'test8404@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:45:30.794 [info] <0.494.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.494.0>
2016-04-12 08:45:30.817 [info] <0.562.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.562.0>
2016-04-12 08:45:31.201 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:45:31.201 [error] <0.553.0> CRASH REPORT Process <0.553.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:45:31.201 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:31.316 [info] <0.672.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.672.0>
2016-04-12 08:45:31.319 [info] <0.7.0> Application mnesia2 started on node 'test8404@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:45:31.534 [info] <0.7.0> Application lager started on node 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:45:31.535 [info] <0.7.0> Application poolgirl started on node 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:45:31.601 [info] <0.99.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.99.0>
2016-04-12 08:45:32.001 [error] <0.155.0> gen_server <0.155.0> terminated with reason: killed
2016-04-12 08:45:32.002 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:45:32.001 [error] <0.155.0> CRASH REPORT Process <0.155.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:45:32.002 [error] <0.90.0> CRASH REPORT Process <0.90.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:45:32.002 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:32.058 [info] <0.799.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.799.0>
2016-04-12 08:45:32.061 [info] <0.7.0> Application mnesia2 started on node 'test8404@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:45:32.363 [error] <0.793.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): ** ERROR ** (ignoring core) ** FATAL ** A fallback is installed and Mnesia2 must be restarted. Forcing shutdown after mnesia2_down from 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6'...

2016-04-12 08:45:32.363 [error] <0.794.0> Supervisor mnesia2_kernel_sup had child mnesia2_locker started with mnesia2_locker:start() at <0.797.0> exit with reason killed in context child_terminated
2016-04-12 08:45:32.363 [error] <0.794.0> Supervisor mnesia2_kernel_sup had child mnesia2_locker started with mnesia2_locker:start() at <0.797.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:45:32.365 [error] <0.792.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.794.0> exit with reason shutdown in context child_terminated
2016-04-12 08:45:32.366 [error] <0.792.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.794.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:45:32.002 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:32.064 [info] <0.215.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.215.0>
2016-04-12 08:45:32.068 [info] <0.7.0> Application mnesia2 started on node 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:45:32.359 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:45:32.410 [info] <0.368.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.368.0>
2016-04-12 08:45:32.505 [info] <0.461.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.461.0>
2016-04-12 08:45:32.366 [info] <0.7.0> Application mnesia2 exited with reason: shutdown
2016-04-12 08:45:32.411 [info] <0.927.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.927.0>
2016-04-12 08:45:32.501 [info] <0.1025.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.1025.0>
2016-04-12 08:45:32.791 [info] <0.1148.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.1148.0>
2016-04-12 08:45:32.793 [info] <0.550.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.550.0>
2016-04-12 08:45:33.656 [warning] <0.6.0> lager_error_logger_h dropped 57 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:45:33.656 [error] <0.541.0> CRASH REPORT Process <0.541.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:45:33.656 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:33.717 [info] <0.766.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.766.0>
2016-04-12 08:45:33.725 [info] <0.7.0> Application mnesia2 started on node 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:45:33.849 [error] <0.757.0> CRASH REPORT Process <0.757.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:45:33.095 [warning] <0.6.0> lager_error_logger_h dropped 21 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:45:33.096 [info] <0.7.0> Application mnesia2 started on node 'test8404@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:45:33.202 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:45:33.222 [info] <0.1261.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.1261.0>
2016-04-12 08:45:33.712 [info] <0.1493.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.1493.0>
2016-04-12 08:45:33.909 [info] <0.1607.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.1607.0>
2016-04-12 08:45:34.212 [warning] <0.6.0> lager_error_logger_h dropped 10 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:45:34.214 [info] <0.7.0> Application mnesia2 started on node 'test8404@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:45:34.319 [error] <0.1650.0> gen_server <0.1650.0> terminated with reason: killed
2016-04-12 08:45:33.849 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:33.912 [info] <0.865.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.865.0>
2016-04-12 08:45:34.320 [error] <0.859.0> Mnesia2('d1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6'): ** ERROR ** mnesia2_event got unexpected event: {'EXIT',<0.862.0>,killed}

2016-04-12 08:45:34.319 [error] <0.1650.0> CRASH REPORT Process <0.1650.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:45:34.319 [error] <0.1598.0> CRASH REPORT Process <0.1598.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:45:34.321 [error] <0.858.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.860.0> exit with reason killed in context child_terminated
2016-04-12 08:45:34.321 [error] <0.858.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.860.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:45:34.321 [error] <0.861.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-12 08:45:34.321 [error] <0.864.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-12 08:45:34.321 [error] <0.864.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:45:34.322 [error] <0.861.0> CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:45:34.323 [error] <0.856.0> CRASH REPORT Process <0.856.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:45:34.323 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:34.393 [info] <0.968.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.968.0>
2016-04-12 08:45:34.648 [info] <0.1073.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.1073.0>
2016-04-12 08:45:34.319 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:34.386 [info] <0.1725.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.1725.0>
2016-04-12 08:45:34.643 [info] <0.1851.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.1851.0>
2016-04-12 08:45:34.880 [info] <0.1982.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.1982.0>
2016-04-12 08:45:35.034 [warning] <0.6.0> lager_error_logger_h dropped 36 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:45:35.034 [error] <0.1977.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.1994.0> exit with reason killed in context child_terminated
2016-04-12 08:45:34.885 [info] <0.1172.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.1172.0>
2016-04-12 08:45:35.034 [warning] <0.6.0> lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:45:35.034 [error] <0.1226.0> gen_server <0.1226.0> terminated with reason: killed
2016-04-12 08:45:35.034 [error] <0.1226.0> CRASH REPORT Process <0.1226.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:45:35.034 [error] <0.1977.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.1994.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:45:35.034 [error] <0.1163.0> CRASH REPORT Process <0.1163.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:45:35.035 [error] <0.1977.0> Supervisor mnesia2_kernel_sup had child mnesia2_controller started with mnesia2_controller:start() at <0.1996.0> exit with reason killed in context shutdown_error
2016-04-12 08:45:35.036 [error] <0.1975.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.1977.0> exit with reason killed in context child_terminated
2016-04-12 08:45:35.036 [error] <0.1975.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.1977.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:45:35.036 [error] <0.1979.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-12 08:45:35.036 [error] <0.1979.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:45:35.036 [error] <0.1978.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-12 08:45:35.036 [error] <0.1978.0> CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:45:35.036 [error] <0.2094.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): ** ERROR ** mnesia2_recover got unexpected info: {'EXIT',<0.1996.0>,killed}

2016-04-12 08:45:35.034 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:35.328 [info] <0.1273.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.1273.0>
2016-04-12 08:45:35.331 [info] <0.7.0> Application mnesia2 started on node 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:45:35.522 [error] <0.1327.0> gen_server <0.1327.0> terminated with reason: killed
2016-04-12 08:45:35.522 [error] <0.1327.0> CRASH REPORT Process <0.1327.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:45:35.618 [info] <0.1379.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.1379.0>
2016-04-12 08:45:35.887 [info] <0.1466.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.1466.0>
2016-04-12 08:45:36.014 [error] <0.1520.0> gen_server <0.1520.0> terminated with reason: killed
2016-04-12 08:45:35.039 [info] <0.7.0> Application mnesia2 exited with reason: shutdown
2016-04-12 08:45:35.323 [info] <0.2116.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.2116.0>
2016-04-12 08:45:35.613 [info] <0.2256.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.2256.0>
2016-04-12 08:45:35.870 [info] <0.2387.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.2387.0>
2016-04-12 08:45:36.015 [warning] <0.6.0> lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:45:36.015 [error] <0.2443.0> gen_server <0.2443.0> terminated with reason: killed
2016-04-12 08:45:36.015 [error] <0.2443.0> CRASH REPORT Process <0.2443.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:45:36.014 [error] <0.1520.0> CRASH REPORT Process <0.1520.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:45:36.016 [error] <0.2378.0> CRASH REPORT Process <0.2378.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:45:36.015 [error] <0.1457.0> CRASH REPORT Process <0.1457.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:45:36.016 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:36.079 [info] <0.2519.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.2519.0>
2016-04-12 08:45:36.083 [info] <0.7.0> Application mnesia2 started on node 'test8404@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:45:36.015 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:36.087 [info] <0.1579.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.1579.0>
2016-04-12 08:45:36.094 [info] <0.7.0> Application mnesia2 started on node 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:45:36.264 [error] <0.1569.0> CRASH REPORT Process <0.1569.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:45:36.265 [error] <0.2510.0> CRASH REPORT Process <0.2510.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:45:36.264 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:36.352 [info] <0.1665.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.1665.0>
2016-04-12 08:45:36.265 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:36.319 [info] <0.2642.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.2642.0>
2016-04-12 08:45:36.677 [info] <0.2770.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.2770.0>
2016-04-12 08:45:36.750 [info] <0.2864.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.2864.0>
2016-04-12 08:45:37.978 [warning] <0.6.0> lager_error_logger_h dropped 5 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:45:37.984 [info] <0.2974.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.2974.0>
2016-04-12 08:45:37.986 [info] <0.7.0> Application mnesia2 started on node 'test8404@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:45:39.218 [error] <0.2965.0> CRASH REPORT Process <0.2965.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:45:39.219 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:41.312 [info] <0.3080.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.3080.0>
2016-04-12 08:45:41.314 [info] <0.7.0> Application mnesia2 started on node 'test8404@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:45:41.315 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:45:41.317 [info] <0.3128.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.3128.0>
2016-04-12 08:45:41.323 [info] <0.3176.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.3176.0>
2016-04-12 08:45:43.421 [info] <0.3248.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.3248.0>
2016-04-12 08:45:43.424 [info] <0.7.0> Application mnesia2 started on node 'test8404@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:45:43.435 [error] <0.3243.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.3259.0> exit with reason killed in context child_terminated
2016-04-12 08:45:43.436 [error] <0.3243.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.3259.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:45:43.437 [error] <0.3239.0> CRASH REPORT Process <0.3239.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:45:43.437 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:45.486 [info] <0.3331.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.3331.0>
2016-04-12 08:45:45.489 [info] <0.7.0> Application mnesia2 started on node 'test8404@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:45:45.493 [info] <0.3325.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Restore aborted. mnesia2_config_backup:open_read["NonExisting.FILE"] -> {enoent,error}

2016-04-12 08:45:45.493 [info] <0.3325.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Restore aborted. mnesia2_config_backup:open_read["/home/travis/build/lrascao/mnesia2/logs/ct_run.test8404@testing-worker-linux-docker-de687427-3348-linux-6.2016-04-12_08.45.05/Mnesia2.test8404@testing-worker-linux-docker-de687427-3348-linux-6/LATEST.LOG"] -> badarg

2016-04-12 08:45:45.494 [error] <0.3357.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_1,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_1,shutdown]}}}} ({error,{already_started,<0.3412.0>}})

2016-04-12 08:45:45.494 [error] <0.3361.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}}} ({error,{already_started,<0.3412.0>}})

2016-04-12 08:45:45.494 [error] <0.3359.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}}} ({error,{already_started,<0.3412.0>}})

2016-04-12 08:45:45.495 [error] <0.3367.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}}} ({error,{already_started,<0.3412.0>}})

2016-04-12 08:45:45.495 [error] <0.3358.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}}} ({error,{already_started,<0.3412.0>}})

2016-04-12 08:45:45.495 [error] <0.3366.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}}} ({error,{already_started,<0.3412.0>}})

2016-04-12 08:45:47.590 [warning] <0.6.0> lager_error_logger_h dropped 25 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:45:47.590 [info] <0.3457.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): mnesia2_monitor starting: <0.3459.0>

2016-04-12 08:45:47.591 [info] <0.3457.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Mnesia2 debug level set to verbose
2016-04-12 08:45:47.591 [info] <0.3457.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): mnesia2_subscr starting: <0.3460.0>

2016-04-12 08:45:47.592 [info] <0.3457.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): mnesia2_locker starting: <0.3461.0>

2016-04-12 08:45:47.592 [info] <0.3463.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.3463.0>
2016-04-12 08:45:47.592 [info] <0.3457.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): mnesia2_recover starting: <0.3462.0>

2016-04-12 08:45:47.592 [info] <0.3457.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): mnesia2_tm starting: <0.3463.0>

2016-04-12 08:45:47.593 [info] <0.3457.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Schema initiated from: default

2016-04-12 08:45:47.593 [info] <0.3457.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): mnesia2_controller starting: <0.3466.0>

2016-04-12 08:45:49.622 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:45:49.622 [info] <0.3509.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): mnesia2_monitor starting: <0.3511.0>

2016-04-12 08:45:49.623 [info] <0.3515.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.3515.0>
2016-04-12 08:45:49.625 [info] <0.7.0> Application mnesia2 started on node 'test8404@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:45:49.627 [error] <0.3523.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}}} ({error,{already_started,<0.3554.0>}})

2016-04-12 08:45:49.627 [error] <0.3525.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}}} ({error,{already_started,<0.3554.0>}})

2016-04-12 08:45:49.627 [error] <0.3524.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}}} ({error,{already_started,<0.3554.0>}})

2016-04-12 08:45:49.627 [error] <0.3522.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}}} ({error,{already_started,<0.3554.0>}})

2016-04-12 08:45:49.627 [error] <0.3527.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}}} ({error,{already_started,<0.3554.0>}})

2016-04-12 08:45:51.648 [warning] <0.6.0> lager_error_logger_h dropped 26 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:45:51.648 [info] <0.3590.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): mnesia2_monitor starting: <0.3592.0>

2016-04-12 08:45:51.649 [info] <0.3590.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Version: "1.0.0"

2016-04-12 08:45:51.649 [info] <0.3590.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Env access_module: mnesia2

2016-04-12 08:45:51.650 [info] <0.3590.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Env auto_repair: true

2016-04-12 08:45:51.650 [info] <0.3590.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Env backup_module: mnesia2_backup

2016-04-12 08:45:51.650 [info] <0.3590.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Env debug: trace

2016-04-12 08:45:51.650 [info] <0.3590.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test8404@testing-worker-linux-docker-de687427-3348-linux-6.2016-04-12_08.45.05/Mnesia2.test8404@testing-worker-linux-docker-de687427-3348-linux-6"

2016-04-12 08:45:51.651 [info] <0.3590.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Env dump_disc_copies_at_startup: true

2016-04-12 08:45:51.651 [info] <0.3590.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Env dump_log_load_regulation: false

2016-04-12 08:45:51.651 [info] <0.3590.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Env dump_log_time_threshold: 180000

2016-04-12 08:45:51.651 [info] <0.3590.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Env dump_log_update_in_place: true

2016-04-12 08:45:51.651 [info] <0.3590.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Env dump_log_write_threshold: 1000

2016-04-12 08:45:51.651 [info] <0.3590.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Env event_module: mnesia2_event

2016-04-12 08:45:51.652 [info] <0.3590.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Env extra_db_nodes: []

2016-04-12 08:45:51.652 [info] <0.3590.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Env ignore_fallback_at_startup: false

2016-04-12 08:45:51.652 [info] <0.3590.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Env fallback_error_function: {mnesia2,lkill}

2016-04-12 08:45:51.652 [info] <0.3590.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Env max_wait_for_decision: infinity

2016-04-12 08:45:51.652 [info] <0.3590.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Env schema_location: opt_disc

2016-04-12 08:45:51.652 [info] <0.3590.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Env core_dir: false

2016-04-12 08:45:51.653 [info] <0.3590.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Env pid_sort_order: false

2016-04-12 08:45:51.653 [info] <0.3596.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.3596.0>
2016-04-12 08:45:51.653 [info] <0.3590.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Env no_table_loaders: 2

2016-04-12 08:45:51.654 [info] <0.3590.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Env dc_dump_limit: 4

2016-04-12 08:45:51.654 [info] <0.3590.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Env send_compressed: 0

2016-04-12 08:45:51.654 [info] <0.3590.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Env send_max_packets: 20

2016-04-12 08:45:51.654 [info] <0.3590.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Env send_max_transfer_size: 7500

2016-04-12 08:45:51.655 [info] <0.3590.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Env async_dirty_buffer_size: 524288

2016-04-12 08:45:51.655 [info] <0.3590.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Env async_dirty_max_buffer_file_size: 100000000

2016-04-12 08:45:53.680 [warning] <0.6.0> lager_error_logger_h dropped 28 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:45:53.680 [info] <0.3661.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): mnesia2_monitor starting: <0.3663.0>

2016-04-12 08:45:53.681 [info] <0.3661.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Version: "1.0.0"

2016-04-12 08:45:53.681 [info] <0.3661.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Env access_module: mnesia2

2016-04-12 08:45:53.681 [info] <0.3661.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Env auto_repair: true

2016-04-12 08:45:53.682 [info] <0.3661.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Env backup_module: mnesia2_backup

2016-04-12 08:45:53.682 [info] <0.3661.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Env debug: debug

2016-04-12 08:45:53.682 [info] <0.3661.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test8404@testing-worker-linux-docker-de687427-3348-linux-6.2016-04-12_08.45.05/Mnesia2.test8404@testing-worker-linux-docker-de687427-3348-linux-6"

2016-04-12 08:45:53.683 [info] <0.3661.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Env dump_disc_copies_at_startup: true

2016-04-12 08:45:53.683 [info] <0.3661.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Env dump_log_load_regulation: false

2016-04-12 08:45:53.683 [info] <0.3667.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.3667.0>
2016-04-12 08:45:53.684 [info] <0.3661.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Env dump_log_time_threshold: 180000

2016-04-12 08:45:53.684 [info] <0.3661.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Env dump_log_update_in_place: true

2016-04-12 08:45:53.684 [info] <0.3661.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Env dump_log_write_threshold: 1000

2016-04-12 08:45:53.684 [info] <0.3661.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Env event_module: mnesia2_event

2016-04-12 08:45:53.684 [info] <0.3661.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Env extra_db_nodes: []

2016-04-12 08:45:53.685 [info] <0.3661.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Env ignore_fallback_at_startup: false

2016-04-12 08:45:53.685 [info] <0.3661.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Env fallback_error_function: {mnesia2,lkill}

2016-04-12 08:45:53.685 [info] <0.3661.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Env max_wait_for_decision: infinity

2016-04-12 08:45:53.686 [info] <0.3661.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Env schema_location: opt_disc

2016-04-12 08:45:53.686 [info] <0.3661.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Env core_dir: false

2016-04-12 08:45:53.686 [info] <0.3661.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): Env pid_sort_order: false

2016-04-12 08:45:55.713 [warning] <0.6.0> lager_error_logger_h dropped 5 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:45:55.715 [info] <0.3718.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.3718.0>
2016-04-12 08:45:55.717 [info] <0.7.0> Application mnesia2 started on node 'test8404@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:45:55.718 [error] <0.3709.0> CRASH REPORT Process <0.3709.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:45:55.718 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:57.798 [info] <0.3782.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.3782.0>
2016-04-12 08:45:57.800 [info] <0.7.0> Application mnesia2 started on node 'test8404@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:45:57.801 [error] <0.3773.0> CRASH REPORT Process <0.3773.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:45:57.801 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:58.898 [info] <0.3853.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.3853.0>
2016-04-12 08:45:58.901 [info] <0.7.0> Application mnesia2 started on node 'test8404@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:45:58.903 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:45:58.910 [info] <0.3914.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.3914.0>
2016-04-12 08:46:13.858 [warning] <0.6.0> lager_error_logger_h dropped 30 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:46:13.858 [error] <0.3908.0> Mnesia2('test8404@testing-worker-linux-docker-de687427-3348-linux-6'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-12 08:46:13.995 [error] <0.3905.0> CRASH REPORT Process <0.3905.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:46:13.995 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:46:16.127 [info] <0.4509.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.4509.0>
2016-04-12 08:46:16.130 [info] <0.7.0> Application mnesia2 started on node 'test8404@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:46:22.138 [error] <0.4504.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.4520.0> exit with reason killed in context child_terminated
2016-04-12 08:46:22.138 [error] <0.4504.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.4520.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:46:22.139 [error] <0.4500.0> CRASH REPORT Process <0.4500.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:46:22.139 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:46:24.239 [info] <0.4609.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.4609.0>
2016-04-12 08:46:24.242 [info] <0.7.0> Application mnesia2 started on node 'test8404@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:46:25.261 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:46:27.380 [info] <0.4725.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.4725.0>
2016-04-12 08:46:27.383 [info] <0.7.0> Application mnesia2 started on node 'test8404@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:46:27.388 [error] <0.4716.0> CRASH REPORT Process <0.4716.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:46:27.388 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:46:29.786 [info] <0.4792.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.4792.0>
2016-04-12 08:46:29.789 [info] <0.7.0> Application mnesia2 started on node 'test8404@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:46:29.817 [error] <0.4783.0> CRASH REPORT Process <0.4783.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:46:29.817 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:46:31.918 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:46:31.934 [info] <0.1792.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.1792.0>
2016-04-12 08:46:31.938 [info] <0.7.0> Application mnesia2 started on node 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:46:31.927 [info] <0.4884.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.4884.0>
2016-04-12 08:46:31.930 [info] <0.7.0> Application mnesia2 started on node 'test8404@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:46:32.940 [error] <0.1844.0> gen_server <0.1844.0> terminated with reason: killed
2016-04-12 08:46:32.940 [error] <0.1844.0> CRASH REPORT Process <0.1844.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:46:32.941 [error] <0.1783.0> CRASH REPORT Process <0.1783.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:46:32.942 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:46:34.974 [info] <0.1860.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.1860.0>
2016-04-12 08:46:34.979 [info] <0.7.0> Application mnesia2 started on node 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:46:35.988 [error] <0.4947.0> gen_server <0.4947.0> terminated with reason: killed
2016-04-12 08:46:35.989 [error] <0.4947.0> CRASH REPORT Process <0.4947.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:46:35.989 [error] <0.4875.0> CRASH REPORT Process <0.4875.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:46:35.989 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:46:37.041 [error] <0.1851.0> CRASH REPORT Process <0.1851.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:46:37.041 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:46:38.121 [info] <0.4990.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.4990.0>
2016-04-12 08:46:38.124 [info] <0.7.0> Application mnesia2 started on node 'test8404@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:46:38.149 [error] <0.4981.0> CRASH REPORT Process <0.4981.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:46:38.132 [info] <0.1941.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.1941.0>
2016-04-12 08:46:38.138 [info] <0.7.0> Application mnesia2 started on node 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:46:38.148 [error] <0.1986.0> gen_server <0.1986.0> terminated with reason: killed
2016-04-12 08:46:38.148 [error] <0.1986.0> CRASH REPORT Process <0.1986.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:46:38.149 [error] <0.1932.0> CRASH REPORT Process <0.1932.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:46:38.150 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:46:38.207 [info] <0.5065.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.5065.0>
2016-04-12 08:46:38.149 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:46:42.632 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:46:42.741 [info] <0.5189.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.5189.0>
2016-04-12 08:46:42.747 [info] <0.7.0> Application mnesia2 started on node 'test8404@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:46:42.731 [info] <0.2016.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.2016.0>
2016-04-12 08:46:42.732 [info] <0.7.0> Application mnesia2 started on node 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:46:53.886 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:46:53.905 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:46:55.061 [info] <0.2138.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.2138.0>
2016-04-12 08:46:55.065 [info] <0.7.0> Application mnesia2 started on node 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:46:55.525 [error] <0.2193.0> gen_server <0.2193.0> terminated with reason: killed
2016-04-12 08:46:55.059 [info] <0.5320.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.5320.0>
2016-04-12 08:46:55.364 [info] <0.7.0> Application mnesia2 started on node 'test8404@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:46:55.547 [error] <0.5377.0> gen_server <0.5377.0> terminated with reason: killed
2016-04-12 08:46:55.525 [error] <0.2193.0> CRASH REPORT Process <0.2193.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:46:55.547 [error] <0.5377.0> CRASH REPORT Process <0.5377.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:46:55.525 [error] <0.2129.0> CRASH REPORT Process <0.2129.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:46:55.548 [error] <0.5311.0> CRASH REPORT Process <0.5311.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:46:55.548 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:46:55.664 [info] <0.5409.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.5409.0>
2016-04-12 08:46:55.525 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:46:55.912 [info] <0.2227.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.2227.0>
2016-04-12 08:46:56.280 [warning] <0.6.0> lager_error_logger_h dropped 32 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:46:56.280 [error] <0.5478.0> gen_server <0.5478.0> terminated with reason: killed
2016-04-12 08:46:56.280 [error] <0.5478.0> CRASH REPORT Process <0.5478.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:46:56.280 [error] <0.5400.0> CRASH REPORT Process <0.5400.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:46:56.280 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:46:57.390 [error] <0.2218.0> CRASH REPORT Process <0.2218.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:46:57.390 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:46:58.460 [info] <0.2330.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.2330.0>
2016-04-12 08:46:58.481 [info] <0.7.0> Application mnesia2 started on node 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:46:58.494 [error] <0.2373.0> gen_server <0.2373.0> terminated with reason: killed
2016-04-12 08:46:58.452 [info] <0.5532.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.5532.0>
2016-04-12 08:46:58.454 [info] <0.7.0> Application mnesia2 started on node 'test8404@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:46:58.496 [error] <0.5594.0> gen_server <0.5594.0> terminated with reason: killed
2016-04-12 08:46:58.496 [error] <0.5594.0> CRASH REPORT Process <0.5594.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:46:58.494 [error] <0.2373.0> CRASH REPORT Process <0.2373.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:46:58.497 [error] <0.5523.0> CRASH REPORT Process <0.5523.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:46:58.495 [error] <0.2321.0> CRASH REPORT Process <0.2321.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:46:58.497 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:46:58.495 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:00.614 [info] <0.2405.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.2405.0>
2016-04-12 08:47:00.620 [info] <0.7.0> Application mnesia2 started on node 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:47:00.623 [error] <0.2417.0> gen_server <0.2417.0> terminated with reason: killed
2016-04-12 08:47:00.605 [info] <0.5643.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.5643.0>
2016-04-12 08:47:00.610 [info] <0.7.0> Application mnesia2 started on node 'test8404@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:47:00.623 [error] <0.5707.0> gen_server <0.5707.0> terminated with reason: killed
2016-04-12 08:47:00.623 [error] <0.5707.0> CRASH REPORT Process <0.5707.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:47:00.623 [error] <0.2417.0> CRASH REPORT Process <0.2417.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:47:00.623 [error] <0.2396.0> CRASH REPORT Process <0.2396.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:47:00.626 [error] <0.5634.0> CRASH REPORT Process <0.5634.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:47:00.627 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:00.623 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:02.683 [info] <0.5723.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.5723.0>
2016-04-12 08:47:02.692 [info] <0.7.0> Application mnesia2 started on node 'test8404@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:47:02.998 [error] <0.5784.0> gen_server <0.5784.0> terminated with reason: killed
2016-04-12 08:47:02.998 [error] <0.5784.0> CRASH REPORT Process <0.5784.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:47:02.999 [error] <0.5714.0> CRASH REPORT Process <0.5714.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:47:02.677 [info] <0.2465.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.2465.0>
2016-04-12 08:47:02.982 [info] <0.7.0> Application mnesia2 started on node 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:47:02.999 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:04.388 [error] <0.2455.0> CRASH REPORT Process <0.2455.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:47:04.388 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:05.488 [info] <0.2551.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.2551.0>
2016-04-12 08:47:05.492 [info] <0.7.0> Application mnesia2 started on node 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:47:05.945 [error] <0.2564.0> gen_server <0.2564.0> terminated with reason: killed
2016-04-12 08:47:05.481 [info] <0.5850.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.5850.0>
2016-04-12 08:47:05.484 [info] <0.7.0> Application mnesia2 started on node 'test8404@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:47:05.948 [error] <0.5903.0> gen_server <0.5903.0> terminated with reason: killed
2016-04-12 08:47:05.945 [error] <0.2564.0> CRASH REPORT Process <0.2564.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:47:05.948 [error] <0.5903.0> CRASH REPORT Process <0.5903.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:47:05.945 [error] <0.2602.0> gen_server <0.2602.0> terminated with reason: killed
2016-04-12 08:47:05.949 [error] <0.5841.0> CRASH REPORT Process <0.5841.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:47:05.945 [error] <0.2602.0> CRASH REPORT Process <0.2602.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:47:05.946 [error] <0.2542.0> CRASH REPORT Process <0.2542.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:47:05.949 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:05.946 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:05.810 [info] <0.7.0> Application lager started on node 'd1408340o1408336n1408334@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:47:05.810 [info] <0.7.0> Application poolgirl started on node 'd1408340o1408336n1408334@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:47:05.848 [info] <0.99.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408340o1408336n1408334@testing-worker-linux-docker-de687427-3348-linux-6', <0.99.0>
2016-04-12 08:47:05.881 [info] <0.7.0> Application mnesia2 started on node 'd1408340o1408336n1408334@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:47:08.054 [info] <0.2632.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.2632.0>
2016-04-12 08:47:08.061 [info] <0.7.0> Application mnesia2 started on node 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:47:08.071 [error] <0.2644.0> gen_server <0.2644.0> terminated with reason: killed
2016-04-12 08:47:08.047 [info] <0.5945.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.5945.0>
2016-04-12 08:47:08.049 [info] <0.7.0> Application mnesia2 started on node 'test8404@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:47:08.074 [error] <0.5936.0> CRASH REPORT Process <0.5936.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:47:08.071 [error] <0.2644.0> CRASH REPORT Process <0.2644.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:47:08.072 [error] <0.2623.0> CRASH REPORT Process <0.2623.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:47:08.074 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:08.072 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:10.185 [info] <0.2702.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.2702.0>
2016-04-12 08:47:10.190 [info] <0.7.0> Application mnesia2 started on node 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:47:10.194 [error] <0.2714.0> gen_server <0.2714.0> terminated with reason: killed
2016-04-12 08:47:10.180 [info] <0.6039.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.6039.0>
2016-04-12 08:47:10.183 [info] <0.7.0> Application mnesia2 started on node 'test8404@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:47:10.196 [error] <0.6083.0> gen_server <0.6083.0> terminated with reason: killed
2016-04-12 08:47:10.196 [error] <0.6083.0> CRASH REPORT Process <0.6083.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:47:10.198 [error] <0.6030.0> CRASH REPORT Process <0.6030.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:47:10.194 [error] <0.2714.0> CRASH REPORT Process <0.2714.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:47:10.195 [error] <0.2693.0> CRASH REPORT Process <0.2693.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:47:10.198 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:10.195 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:12.332 [info] <0.2777.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.2777.0>
2016-04-12 08:47:12.337 [info] <0.7.0> Application mnesia2 started on node 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:47:12.340 [error] <0.2768.0> CRASH REPORT Process <0.2768.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:47:12.313 [info] <0.6125.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.6125.0>
2016-04-12 08:47:12.317 [info] <0.7.0> Application mnesia2 started on node 'test8404@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:47:12.340 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:13.367 [error] <0.6116.0> CRASH REPORT Process <0.6116.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:47:13.367 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:15.400 [info] <0.2844.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.2844.0>
2016-04-12 08:47:15.402 [info] <0.7.0> Application mnesia2 started on node 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:47:20.419 [info] <0.6203.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.6203.0>
2016-04-12 08:47:20.450 [info] <0.7.0> Application mnesia2 started on node 'test8404@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:47:20.458 [error] <0.6255.0> gen_server <0.6255.0> terminated with reason: killed
2016-04-12 08:47:20.458 [error] <0.6255.0> CRASH REPORT Process <0.6255.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:47:20.457 [error] <0.2911.0> gen_server <0.2911.0> terminated with reason: killed
2016-04-12 08:47:20.459 [error] <0.6194.0> CRASH REPORT Process <0.6194.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:47:20.457 [error] <0.2911.0> CRASH REPORT Process <0.2911.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:47:20.458 [error] <0.2835.0> CRASH REPORT Process <0.2835.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:47:20.460 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:20.458 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:23.218 [info] <0.2943.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.2943.0>
2016-04-12 08:47:23.230 [info] <0.7.0> Application mnesia2 started on node 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:47:23.573 [error] <0.3008.0> gen_server <0.3008.0> terminated with reason: killed
2016-04-12 08:47:23.573 [error] <0.3001.0> gen_server <0.3001.0> terminated with reason: killed
2016-04-12 08:47:23.573 [error] <0.3008.0> CRASH REPORT Process <0.3008.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:47:23.573 [error] <0.3001.0> CRASH REPORT Process <0.3001.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:47:23.573 [error] <0.2934.0> CRASH REPORT Process <0.2934.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:47:23.207 [info] <0.6313.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.6313.0>
2016-04-12 08:47:23.513 [info] <0.7.0> Application mnesia2 started on node 'test8404@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:47:23.642 [error] <0.6416.0> gen_server <0.6416.0> terminated with reason: killed
2016-04-12 08:47:23.642 [error] <0.6416.0> CRASH REPORT Process <0.6416.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:47:23.642 [error] <0.6400.0> gen_server <0.6400.0> terminated with reason: killed
2016-04-12 08:47:23.642 [error] <0.6400.0> CRASH REPORT Process <0.6400.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:47:23.645 [error] <0.6304.0> CRASH REPORT Process <0.6304.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:47:23.134 [warning] <0.6.0> lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:47:23.243 [info] <0.189.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408340o1408336n1408334@testing-worker-linux-docker-de687427-3348-linux-6', <0.189.0>
2016-04-12 08:47:23.250 [info] <0.7.0> Application mnesia2 started on node 'd1408340o1408336n1408334@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:47:23.664 [error] <0.272.0> gen_server <0.272.0> terminated with reason: killed
2016-04-12 08:47:23.664 [error] <0.272.0> CRASH REPORT Process <0.272.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:47:23.747 [info] <0.293.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408340o1408336n1408334@testing-worker-linux-docker-de687427-3348-linux-6', <0.293.0>
2016-04-12 08:47:23.646 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:23.745 [info] <0.6435.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.6435.0>
2016-04-12 08:47:23.574 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:23.605 [info] <0.3036.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.3036.0>
2016-04-12 08:47:23.702 [info] <0.3131.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.3131.0>
2016-04-12 08:47:24.301 [warning] <0.6.0> lager_error_logger_h dropped 34 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:47:24.301 [error] <0.359.0> gen_server <0.359.0> terminated with reason: killed
2016-04-12 08:47:24.301 [error] <0.359.0> CRASH REPORT Process <0.359.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:47:24.302 [error] <0.354.0> gen_server <0.354.0> terminated with reason: killed
2016-04-12 08:47:24.302 [error] <0.354.0> CRASH REPORT Process <0.354.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:47:24.302 [error] <0.284.0> CRASH REPORT Process <0.284.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:47:24.302 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:24.329 [info] <0.389.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408340o1408336n1408334@testing-worker-linux-docker-de687427-3348-linux-6', <0.389.0>
2016-04-12 08:47:24.333 [info] <0.7.0> Application mnesia2 started on node 'd1408340o1408336n1408334@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:47:26.377 [warning] <0.6.0> lager_error_logger_h dropped 16 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:47:26.377 [error] <0.6531.0> gen_server <0.6531.0> terminated with reason: killed
2016-04-12 08:47:26.377 [error] <0.6531.0> CRASH REPORT Process <0.6531.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:47:26.378 [error] <0.6426.0> CRASH REPORT Process <0.6426.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:47:26.400 [warning] <0.6.0> lager_error_logger_h dropped 21 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:47:26.400 [error] <0.3224.0> gen_server <0.3224.0> terminated with reason: killed
2016-04-12 08:47:26.401 [error] <0.3224.0> CRASH REPORT Process <0.3224.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:47:26.401 [error] <0.3122.0> CRASH REPORT Process <0.3122.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:47:26.437 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:47:26.450 [info] <0.495.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408340o1408336n1408334@testing-worker-linux-docker-de687427-3348-linux-6', <0.495.0>
2016-04-12 08:47:26.452 [info] <0.7.0> Application mnesia2 started on node 'd1408340o1408336n1408334@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:47:27.037 [error] <0.567.0> gen_server <0.567.0> terminated with reason: killed
2016-04-12 08:47:27.037 [error] <0.567.0> CRASH REPORT Process <0.567.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:47:27.038 [error] <0.486.0> CRASH REPORT Process <0.486.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:47:26.379 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:26.470 [info] <0.6550.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.6550.0>
2016-04-12 08:47:26.519 [info] <0.7.0> Application mnesia2 started on node 'test8404@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:47:27.133 [error] <0.6545.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.6566.0> exit with reason killed in context child_terminated
2016-04-12 08:47:27.134 [error] <0.6545.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.6566.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:47:27.135 [error] <0.6643.0> gen_server <0.6643.0> terminated with reason: killed
2016-04-12 08:47:27.135 [error] <0.6643.0> CRASH REPORT Process <0.6643.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:47:27.136 [error] <0.6638.0> gen_server <0.6638.0> terminated with reason: killed
2016-04-12 08:47:27.136 [error] <0.6638.0> CRASH REPORT Process <0.6638.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:47:27.137 [error] <0.6541.0> CRASH REPORT Process <0.6541.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:47:26.401 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:26.471 [info] <0.3245.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.3245.0>
2016-04-12 08:47:26.498 [info] <0.7.0> Application mnesia2 started on node 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:47:27.166 [error] <0.3333.0> gen_server <0.3333.0> terminated with reason: killed
2016-04-12 08:47:27.166 [error] <0.3333.0> CRASH REPORT Process <0.3333.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:47:27.166 [error] <0.3236.0> CRASH REPORT Process <0.3236.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:47:27.137 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:27.237 [info] <0.6660.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.6660.0>
2016-04-12 08:47:27.166 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:27.245 [info] <0.3354.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.3354.0>
2016-04-12 08:47:27.268 [info] <0.7.0> Application mnesia2 started on node 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:47:27.038 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:27.063 [info] <0.593.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408340o1408336n1408334@testing-worker-linux-docker-de687427-3348-linux-6', <0.593.0>
2016-04-12 08:47:27.064 [info] <0.7.0> Application mnesia2 started on node 'd1408340o1408336n1408334@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:47:27.190 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:47:27.203 [info] <0.694.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408340o1408336n1408334@testing-worker-linux-docker-de687427-3348-linux-6', <0.694.0>
2016-04-12 08:47:28.293 [error] <0.3426.0> gen_server <0.3426.0> terminated with reason: killed
2016-04-12 08:47:28.293 [error] <0.3426.0> CRASH REPORT Process <0.3426.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:47:28.293 [error] <0.3415.0> gen_server <0.3415.0> terminated with reason: killed
2016-04-12 08:47:28.293 [error] <0.3415.0> CRASH REPORT Process <0.3415.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:47:28.294 [error] <0.3345.0> CRASH REPORT Process <0.3345.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:47:28.294 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:28.330 [info] <0.3450.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.3450.0>
2016-04-12 08:47:28.368 [info] <0.7.0> Application mnesia2 started on node 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:47:28.384 [error] <0.3441.0> CRASH REPORT Process <0.3441.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:47:27.547 [info] <0.7.0> Application mnesia2 started on node 'test8404@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:47:28.384 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:29.408 [info] <0.3528.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.3528.0>
2016-04-12 08:47:29.419 [info] <0.7.0> Application mnesia2 started on node 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:47:29.484 [error] <0.3542.0> gen_server <0.3542.0> terminated with reason: killed
2016-04-12 08:47:29.482 [error] <0.689.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.709.0> exit with reason killed in context child_terminated
2016-04-12 08:47:29.483 [error] <0.6774.0> gen_server <0.6774.0> terminated with reason: killed
2016-04-12 08:47:29.484 [error] <0.3542.0> CRASH REPORT Process <0.3542.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:47:29.483 [error] <0.6774.0> CRASH REPORT Process <0.6774.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:47:29.486 [error] <0.3553.0> gen_server <0.3553.0> terminated with reason: killed
2016-04-12 08:47:29.483 [error] <0.689.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.709.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:47:29.489 [error] <0.6651.0> CRASH REPORT Process <0.6651.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:47:29.486 [error] <0.3553.0> CRASH REPORT Process <0.3553.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:47:29.484 [error] <0.687.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.689.0> exit with reason killed in context child_terminated
2016-04-12 08:47:29.486 [error] <0.3519.0> CRASH REPORT Process <0.3519.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:47:29.484 [error] <0.687.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.689.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:47:29.484 [error] <0.690.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-12 08:47:29.484 [error] <0.693.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-12 08:47:29.484 [error] <0.693.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:47:29.484 [error] <0.691.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-12 08:47:29.484 [error] <0.691.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:47:29.486 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:29.560 [info] <0.3607.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.3607.0>
2016-04-12 08:47:29.698 [info] <0.3702.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.3702.0>
2016-04-12 08:47:29.787 [info] <0.3792.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.3792.0>
2016-04-12 08:47:29.849 [info] <0.3892.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.3892.0>
2016-04-12 08:47:30.417 [warning] <0.6.0> lager_error_logger_h dropped 31 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:47:30.417 [error] <0.3883.0> CRASH REPORT Process <0.3883.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:47:29.485 [info] <0.7.0> Application mnesia2 exited with reason: shutdown
2016-04-12 08:47:29.490 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:29.551 [info] <0.6806.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.6806.0>
2016-04-12 08:47:29.553 [info] <0.7.0> Application mnesia2 started on node 'test8404@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:47:29.847 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:47:30.367 [info] <0.6920.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.6920.0>
2016-04-12 08:47:30.393 [info] <0.7.0> Application mnesia2 started on node 'test8404@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:47:30.415 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:47:30.454 [info] <0.7003.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.7003.0>
2016-04-12 08:47:31.037 [error] <0.6994.0> CRASH REPORT Process <0.6994.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:47:30.417 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:30.960 [info] <0.3974.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.3974.0>
2016-04-12 08:47:30.975 [info] <0.7.0> Application mnesia2 started on node 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:47:31.040 [error] <0.4025.0> gen_server <0.4025.0> terminated with reason: killed
2016-04-12 08:47:31.040 [error] <0.4025.0> CRASH REPORT Process <0.4025.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:47:31.041 [error] <0.3965.0> CRASH REPORT Process <0.3965.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:47:31.041 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:31.117 [info] <0.4066.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.4066.0>
2016-04-12 08:47:31.139 [info] <0.7.0> Application mnesia2 started on node 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:47:31.037 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:31.114 [info] <0.7104.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.7104.0>
2016-04-12 08:47:31.136 [info] <0.7.0> Application mnesia2 started on node 'test8404@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:47:31.494 [error] <0.7095.0> CRASH REPORT Process <0.7095.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:47:31.495 [error] <0.4059.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.4061.0> exit with reason killed in context child_terminated
2016-04-12 08:47:31.112 [info] <0.845.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408340o1408336n1408334@testing-worker-linux-docker-de687427-3348-linux-6', <0.845.0>
2016-04-12 08:47:31.416 [info] <0.7.0> Application mnesia2 started on node 'd1408340o1408336n1408334@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:47:31.499 [error] <0.905.0> gen_server <0.905.0> terminated with reason: killed
2016-04-12 08:47:31.495 [error] <0.4059.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.4061.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:47:31.499 [error] <0.905.0> CRASH REPORT Process <0.905.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:47:31.495 [error] <0.4063.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-12 08:47:31.499 [error] <0.836.0> CRASH REPORT Process <0.836.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:47:31.495 [error] <0.4063.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:47:31.495 [error] <0.4062.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-12 08:47:31.495 [error] <0.4065.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-12 08:47:31.497 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:31.586 [info] <0.7214.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.7214.0>
2016-04-12 08:47:31.695 [info] <0.7306.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.7306.0>
2016-04-12 08:47:31.499 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:31.533 [info] <0.952.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408340o1408336n1408334@testing-worker-linux-docker-de687427-3348-linux-6', <0.952.0>
2016-04-12 08:47:31.645 [info] <0.1030.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408340o1408336n1408334@testing-worker-linux-docker-de687427-3348-linux-6', <0.1030.0>
2016-04-12 08:47:31.533 [info] <0.4158.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.4158.0>
2016-04-12 08:47:31.647 [info] <0.4237.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.4237.0>
2016-04-12 08:47:41.703 [error] <0.7299.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at undefined exit with reason killed in context start_error
2016-04-12 08:47:41.703 [error] <0.7302.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-12 08:47:41.703 [error] <0.7305.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-12 08:47:41.703 [error] <0.7305.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:47:41.703 [error] <0.7325.0> gen_server mnesia2_snmp_sup terminated with reason: killed
2016-04-12 08:47:41.703 [error] <0.7325.0> CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:47:41.703 [error] <0.7303.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-12 08:47:41.703 [error] <0.7303.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:47:41.704 [error] <0.7297.0> CRASH REPORT Process <0.7297.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}} in application_master:init/4 line 133
2016-04-12 08:47:41.704 [info] <0.7.0> Application mnesia2 exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}}
2016-04-12 08:47:41.704 [error] <0.7302.0> CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:47:41.788 [warning] <0.6.0> lager_error_logger_h dropped 10 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:47:41.788 [error] <0.4281.0> gen_server <0.4281.0> terminated with reason: killed
2016-04-12 08:47:41.789 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:47:41.789 [error] <0.1074.0> gen_server <0.1074.0> terminated with reason: killed
2016-04-12 08:47:41.789 [error] <0.4281.0> CRASH REPORT Process <0.4281.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:47:41.789 [error] <0.1074.0> CRASH REPORT Process <0.1074.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-12 08:47:41.789 [error] <0.4228.0> CRASH REPORT Process <0.4228.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:47:41.789 [error] <0.1021.0> CRASH REPORT Process <0.1021.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:47:41.789 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:41.789 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:44.182 [info] <0.7415.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.7415.0>
2016-04-12 08:47:44.184 [info] <0.7.0> Application mnesia2 started on node 'test8404@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:47:48.361 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:47:48.496 [info] <0.7551.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.7551.0>
2016-04-12 08:47:48.829 [info] <0.7.0> Application mnesia2 started on node 'test8404@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:47:48.498 [info] <0.1126.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408340o1408336n1408334@testing-worker-linux-docker-de687427-3348-linux-6', <0.1126.0>
2016-04-12 08:47:48.509 [info] <0.7.0> Application mnesia2 started on node 'd1408340o1408336n1408334@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:47:48.511 [info] <0.4328.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.4328.0>
2016-04-12 08:47:48.516 [info] <0.7.0> Application mnesia2 started on node 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:47:54.928 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:47:55.093 [info] <0.1243.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408340o1408336n1408334@testing-worker-linux-docker-de687427-3348-linux-6', <0.1243.0>
2016-04-12 08:47:55.404 [info] <0.7.0> Application mnesia2 started on node 'd1408340o1408336n1408334@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:47:54.934 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:47:55.094 [info] <0.4441.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.4441.0>
2016-04-12 08:47:55.106 [info] <0.7.0> Application mnesia2 started on node 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:47:54.936 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:47:55.089 [info] <0.7682.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.7682.0>
2016-04-12 08:47:55.395 [info] <0.7.0> Application mnesia2 started on node 'test8404@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:48:01.500 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:01.667 [info] <0.7812.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.7812.0>
2016-04-12 08:48:01.670 [info] <0.7.0> Application mnesia2 started on node 'test8404@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:48:01.522 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:01.672 [info] <0.1360.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408340o1408336n1408334@testing-worker-linux-docker-de687427-3348-linux-6', <0.1360.0>
2016-04-12 08:48:01.687 [info] <0.7.0> Application mnesia2 started on node 'd1408340o1408336n1408334@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:48:01.524 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:01.676 [info] <0.4556.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.4556.0>
2016-04-12 08:48:01.681 [info] <0.7.0> Application mnesia2 started on node 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:48:22.566 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:22.712 [info] <0.8951.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.8951.0>
2016-04-12 08:48:23.016 [info] <0.7.0> Application mnesia2 started on node 'test8404@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:48:22.569 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:22.714 [info] <0.2485.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408340o1408336n1408334@testing-worker-linux-docker-de687427-3348-linux-6', <0.2485.0>
2016-04-12 08:48:22.730 [info] <0.7.0> Application mnesia2 started on node 'd1408340o1408336n1408334@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:48:22.566 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:22.723 [info] <0.5679.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.5679.0>
2016-04-12 08:48:22.734 [info] <0.7.0> Application mnesia2 started on node 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:48:29.354 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:29.478 [info] <0.2611.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408340o1408336n1408334@testing-worker-linux-docker-de687427-3348-linux-6', <0.2611.0>
2016-04-12 08:48:29.486 [info] <0.7.0> Application mnesia2 started on node 'd1408340o1408336n1408334@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:48:29.358 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:29.466 [info] <0.5801.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.5801.0>
2016-04-12 08:48:29.489 [info] <0.7.0> Application mnesia2 started on node 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:48:29.353 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:29.466 [info] <0.9091.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.9091.0>
2016-04-12 08:48:29.782 [info] <0.7.0> Application mnesia2 started on node 'test8404@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:48:36.666 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:37.328 [info] <0.4083.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408340o1408336n1408334@testing-worker-linux-docker-de687427-3348-linux-6', <0.4083.0>
2016-04-12 08:48:37.357 [info] <0.7.0> Application mnesia2 started on node 'd1408340o1408336n1408334@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:48:36.686 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:37.329 [info] <0.7273.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.7273.0>
2016-04-12 08:48:37.340 [info] <0.7.0> Application mnesia2 started on node 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:48:36.675 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:37.302 [info] <0.10571.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.10571.0>
2016-04-12 08:48:37.304 [info] <0.7.0> Application mnesia2 started on node 'test8404@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:48:43.573 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:43.738 [info] <0.10994.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.10994.0>
2016-04-12 08:48:43.741 [info] <0.7.0> Application mnesia2 started on node 'test8404@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:48:43.587 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:43.786 [info] <0.8315.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.8315.0>
2016-04-12 08:48:43.792 [info] <0.7.0> Application mnesia2 started on node 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:48:43.599 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:43.764 [info] <0.6077.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408340o1408336n1408334@testing-worker-linux-docker-de687427-3348-linux-6', <0.6077.0>
2016-04-12 08:48:44.085 [info] <0.7.0> Application mnesia2 started on node 'd1408340o1408336n1408334@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:48:50.248 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:50.475 [info] <0.8429.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6', <0.8429.0>
2016-04-12 08:48:50.480 [info] <0.7.0> Application mnesia2 started on node 'd1408334o1408342n1408342@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:48:50.254 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:50.451 [info] <0.11123.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8404@testing-worker-linux-docker-de687427-3348-linux-6', <0.11123.0>
2016-04-12 08:48:50.454 [info] <0.7.0> Application mnesia2 started on node 'test8404@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:48:50.257 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:50.483 [info] <0.6871.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1408340o1408336n1408334@testing-worker-linux-docker-de687427-3348-linux-6', <0.6871.0>
2016-04-12 08:48:50.499 [info] <0.7.0> Application mnesia2 started on node 'd1408340o1408336n1408334@testing-worker-linux-docker-de687427-3348-linux-6'
2016-04-12 08:48:56.828 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:56.814 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:56.802 [info] <0.7.0> Application mnesia2 exited with reason: stopped
