2016-04-12 08:45:35.977 [info] <0.7.0> Application lager started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:45:35.977 [info] <0.7.0> Application poolgirl started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:45:36.001 [info] <0.495.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.495.0>
2016-04-12 08:45:36.004 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:45:36.014 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:45:36.035 [info] <0.563.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.563.0>
2016-04-12 08:45:36.038 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:45:36.469 [error] <0.554.0> CRASH REPORT Process <0.554.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:36.608 [info] <0.673.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.673.0>
2016-04-12 08:45:36.827 [info] <0.7.0> Application lager started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:45:36.828 [info] <0.7.0> Application poolgirl started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:45:36.879 [info] <0.100.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.100.0>
2016-04-12 08:45:37.549 [error] <0.156.0> gen_server <0.156.0> terminated with reason: killed
2016-04-12 08:45:37.371 [warning] <0.6.0> lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:45:37.550 [error] <0.730.0> gen_server <0.730.0> terminated with reason: killed
2016-04-12 08:45:37.550 [error] <0.156.0> CRASH REPORT Process <0.156.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:45:37.550 [error] <0.730.0> CRASH REPORT Process <0.730.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:45:37.550 [error] <0.91.0> CRASH REPORT Process <0.91.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:37.550 [error] <0.664.0> CRASH REPORT Process <0.664.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:37.550 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:37.627 [info] <0.216.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.216.0>
2016-04-12 08:45:37.631 [info] <0.7.0> Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:45:37.551 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:37.598 [info] <0.800.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.800.0>
2016-04-12 08:45:37.904 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:45:38.100 [error] <0.794.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): ** ERROR ** (ignoring core) ** FATAL ** A fallback is installed and Mnesia2 must be restarted. Forcing shutdown after mnesia2_down from 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'...

2016-04-12 08:45:38.100 [error] <0.795.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_locker:start() at <0.798.0> exit with reason killed in context child_terminated
2016-04-12 08:45:38.100 [error] <0.795.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_locker:start() at <0.798.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:45:38.102 [error] <0.793.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.795.0> exit with reason shutdown in context child_terminated
2016-04-12 08:45:38.103 [error] <0.793.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.795.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:45:38.103 [info] <0.7.0> Application mnesia2 exited with reason: shutdown
2016-04-12 08:45:38.142 [info] <0.929.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.929.0>
2016-04-12 08:45:38.144 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:45:38.190 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:45:38.243 [info] <0.1029.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.1029.0>
2016-04-12 08:45:38.091 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:45:38.150 [info] <0.370.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.370.0>
2016-04-12 08:45:38.155 [info] <0.7.0> Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:45:38.192 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:45:38.254 [info] <0.461.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.461.0>
2016-04-12 08:45:39.005 [warning] <0.6.0> lager_error_logger_h dropped 21 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:45:39.028 [info] <0.550.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.550.0>
2016-04-12 08:45:39.037 [info] <0.7.0> Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:45:39.885 [error] <0.541.0> CRASH REPORT Process <0.541.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:39.004 [warning] <0.6.0> lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:45:39.026 [info] <0.1152.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.1152.0>
2016-04-12 08:45:39.331 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:45:39.448 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:45:39.461 [info] <0.1265.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.1265.0>
2016-04-12 08:45:39.941 [info] <0.1497.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.1497.0>
2016-04-12 08:45:40.245 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:45:40.246 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:45:40.374 [error] <0.1488.0> CRASH REPORT Process <0.1488.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:39.885 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:39.944 [info] <0.765.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.765.0>
2016-04-12 08:45:40.373 [warning] <0.6.0> lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:45:40.373 [error] <0.760.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.779.0> exit with reason killed in context child_terminated
2016-04-12 08:45:40.373 [error] <0.760.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.779.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:45:40.374 [error] <0.761.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-12 08:45:40.374 [error] <0.761.0> CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:45:40.374 [error] <0.764.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-12 08:45:40.374 [error] <0.764.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:45:40.374 [error] <0.758.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.760.0> exit with reason killed in context child_terminated
2016-04-12 08:45:40.374 [error] <0.758.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.760.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:45:40.374 [error] <0.762.0> gen_server mnesia2_subscr terminated with reason: {aborted,{node_not_running,'d1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'}} in mnesia2:abort/1 line 313
2016-04-12 08:45:40.374 [error] <0.762.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: {aborted,{node_not_running,'d1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'}} in gen_server:terminate/7 line 814
2016-04-12 08:45:40.375 [info] <0.7.0> Application mnesia2 exited with reason: shutdown
2016-04-12 08:45:40.462 [info] <0.865.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.865.0>
2016-04-12 08:45:40.643 [info] <0.966.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.966.0>
2016-04-12 08:45:40.374 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:40.456 [info] <0.1612.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.1612.0>
2016-04-12 08:45:40.637 [info] <0.1728.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.1728.0>
2016-04-12 08:45:41.114 [warning] <0.6.0> lager_error_logger_h dropped 31 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:45:41.153 [info] <0.1854.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.1854.0>
2016-04-12 08:45:41.458 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:45:41.604 [error] <0.1845.0> CRASH REPORT Process <0.1845.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:41.114 [warning] <0.6.0> lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:45:41.156 [info] <0.1072.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.1072.0>
2016-04-12 08:45:41.158 [info] <0.7.0> Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:45:41.604 [error] <0.1127.0> gen_server <0.1127.0> terminated with reason: killed
2016-04-12 08:45:41.604 [error] <0.1127.0> CRASH REPORT Process <0.1127.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:45:41.604 [error] <0.1063.0> CRASH REPORT Process <0.1063.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:41.604 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:41.672 [info] <0.1172.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.1172.0>
2016-04-12 08:45:41.889 [info] <0.1273.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.1273.0>
2016-04-12 08:45:41.604 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:41.655 [info] <0.1986.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.1986.0>
2016-04-12 08:45:41.885 [info] <0.2119.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.2119.0>
2016-04-12 08:45:42.465 [warning] <0.6.0> lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:45:42.465 [error] <0.2175.0> gen_server <0.2175.0> terminated with reason: killed
2016-04-12 08:45:42.466 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:45:42.466 [error] <0.1327.0> gen_server <0.1327.0> terminated with reason: killed
2016-04-12 08:45:42.465 [error] <0.2175.0> CRASH REPORT Process <0.2175.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:45:42.466 [error] <0.1327.0> CRASH REPORT Process <0.1327.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:45:42.466 [error] <0.2110.0> CRASH REPORT Process <0.2110.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:42.466 [error] <0.1264.0> CRASH REPORT Process <0.1264.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:42.466 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:42.524 [info] <0.2259.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.2259.0>
2016-04-12 08:45:42.527 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:45:43.339 [error] <0.2315.0> gen_server <0.2315.0> terminated with reason: killed
2016-04-12 08:45:42.467 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:42.544 [info] <0.1379.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.1379.0>
2016-04-12 08:45:42.547 [info] <0.7.0> Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:45:43.338 [error] <0.1433.0> gen_server <0.1433.0> terminated with reason: killed
2016-04-12 08:45:43.339 [error] <0.2315.0> CRASH REPORT Process <0.2315.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:45:43.338 [error] <0.1433.0> CRASH REPORT Process <0.1433.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:45:43.340 [error] <0.2250.0> CRASH REPORT Process <0.2250.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:43.338 [error] <0.1370.0> CRASH REPORT Process <0.1370.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:43.338 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:43.403 [info] <0.1466.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.1466.0>
2016-04-12 08:45:43.406 [info] <0.7.0> Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:45:43.340 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:43.399 [info] <0.2390.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.2390.0>
2016-04-12 08:45:43.842 [error] <0.1459.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.1461.0> exit with reason killed in context child_terminated
2016-04-12 08:45:43.705 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:45:43.844 [error] <0.2381.0> CRASH REPORT Process <0.2381.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:43.843 [error] <0.1459.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.1461.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:45:43.843 [error] <0.1460.0> Mnesia2('d1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'): ** ERROR ** mnesia2_event got unexpected event: {'EXIT',<0.1463.0>,killed}

2016-04-12 08:45:43.843 [error] <0.1462.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-12 08:45:43.941 [info] <0.1580.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.1580.0>
2016-04-12 08:45:44.080 [warning] <0.6.0> lager_error_logger_h dropped 11 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:45:44.080 [error] <0.1633.0> gen_server <0.1633.0> terminated with reason: killed
2016-04-12 08:45:43.844 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:43.907 [info] <0.2524.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.2524.0>
2016-04-12 08:45:44.081 [warning] <0.6.0> lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:45:44.081 [error] <0.2580.0> gen_server <0.2580.0> terminated with reason: killed
2016-04-12 08:45:44.081 [error] <0.2580.0> CRASH REPORT Process <0.2580.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:45:44.080 [error] <0.1633.0> CRASH REPORT Process <0.1633.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:45:44.081 [error] <0.2515.0> CRASH REPORT Process <0.2515.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:44.081 [error] <0.1570.0> CRASH REPORT Process <0.1570.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:44.081 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:44.154 [info] <0.1666.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.1666.0>
2016-04-12 08:45:44.157 [info] <0.7.0> Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:45:44.228 [error] <0.1718.0> gen_server <0.1718.0> terminated with reason: killed
2016-04-12 08:45:44.228 [error] <0.1718.0> CRASH REPORT Process <0.1718.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:45:44.081 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:44.149 [info] <0.2647.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.2647.0>
2016-04-12 08:45:44.151 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:45:44.464 [error] <0.2638.0> CRASH REPORT Process <0.2638.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:44.464 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:44.509 [info] <0.2775.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.2775.0>
2016-04-12 08:45:44.606 [info] <0.2869.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.2869.0>
2016-04-12 08:45:45.842 [info] <0.2979.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.2979.0>
2016-04-12 08:45:45.845 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:45:47.038 [error] <0.2970.0> CRASH REPORT Process <0.2970.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:47.038 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:49.150 [info] <0.3085.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.3085.0>
2016-04-12 08:45:49.152 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:45:49.153 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:45:49.155 [info] <0.3133.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.3133.0>
2016-04-12 08:45:49.159 [info] <0.3181.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.3181.0>
2016-04-12 08:45:51.246 [info] <0.3253.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.3253.0>
2016-04-12 08:45:51.248 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:45:51.263 [error] <0.3244.0> CRASH REPORT Process <0.3244.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:51.263 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:53.304 [info] <0.3336.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.3336.0>
2016-04-12 08:45:53.307 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:45:53.316 [info] <0.3330.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Restore aborted. mnesia2_config_backup:open_read["NonExisting.FILE"] -> {enoent,error}

2016-04-12 08:45:53.317 [info] <0.3330.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Restore aborted. mnesia2_config_backup:open_read["/home/travis/build/lrascao/mnesia2/logs/ct_run.test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14.2016-04-12_08.45.13/Mnesia2.test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14/LATEST.LOG"] -> badarg

2016-04-12 08:45:53.318 [error] <0.3369.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}}} ({error,{already_started,<0.3412.0>}})

2016-04-12 08:45:53.318 [error] <0.3383.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_20,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_20,shutdown]}}}} ({error,{already_started,<0.3412.0>}})

2016-04-12 08:45:53.318 [error] <0.3390.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_25,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_25,shutdown]}}}} ({error,{already_started,<0.3412.0>}})

2016-04-12 08:45:53.318 [error] <0.3388.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_24,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_24,shutdown]}}}} ({error,{already_started,<0.3412.0>}})

2016-04-12 08:45:53.318 [error] <0.3392.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_27,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_27,shutdown]}}}} ({error,{already_started,<0.3412.0>}})

2016-04-12 08:45:53.318 [error] <0.3394.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_29,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_29,shutdown]}}}} ({error,{already_started,<0.3412.0>}})

2016-04-12 08:45:53.318 [error] <0.3393.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_28,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_28,shutdown]}}}} ({error,{already_started,<0.3412.0>}})

2016-04-12 08:45:53.318 [error] <0.3397.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_32,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_32,shutdown]}}}} ({error,{already_started,<0.3412.0>}})

2016-04-12 08:45:55.395 [warning] <0.6.0> lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:45:55.396 [info] <0.3457.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): mnesia2_monitor starting: <0.3459.0>

2016-04-12 08:45:55.396 [info] <0.3457.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Mnesia2 debug level set to verbose
2016-04-12 08:45:55.398 [info] <0.3463.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.3463.0>
2016-04-12 08:45:55.402 [info] <0.3457.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): mnesia2_subscr starting: <0.3460.0>

2016-04-12 08:45:55.402 [info] <0.3457.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): mnesia2_locker starting: <0.3461.0>

2016-04-12 08:45:55.402 [info] <0.3457.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): mnesia2_recover starting: <0.3462.0>

2016-04-12 08:45:55.402 [info] <0.3457.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): mnesia2_tm starting: <0.3463.0>

2016-04-12 08:45:55.402 [info] <0.3457.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Schema initiated from: default

2016-04-12 08:45:55.403 [info] <0.3457.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): mnesia2_controller starting: <0.3466.0>

2016-04-12 08:45:55.403 [info] <0.3457.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): mnesia2_late_loader starting: <0.3467.0>

2016-04-12 08:45:55.403 [info] <0.3457.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Intend to load tables: []

2016-04-12 08:45:55.403 [info] <0.3457.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): mnesia2_tm_1 starting: <0.3469.0>

2016-04-12 08:45:55.403 [info] <0.3457.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): mnesia2_tm_2 starting: <0.3470.0>

2016-04-12 08:45:55.404 [info] <0.3457.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): mnesia2_tm_3 starting: <0.3471.0>

2016-04-12 08:45:55.404 [info] <0.3457.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): mnesia2_tm_4 starting: <0.3472.0>

2016-04-12 08:45:55.404 [info] <0.3457.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): mnesia2_tm_5 starting: <0.3473.0>

2016-04-12 08:45:55.405 [info] <0.3457.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): mnesia2_tm_6 starting: <0.3474.0>

2016-04-12 08:45:55.405 [info] <0.3457.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): mnesia2_tm_7 starting: <0.3475.0>

2016-04-12 08:45:55.405 [info] <0.3457.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): mnesia2_tm_8 starting: <0.3476.0>

2016-04-12 08:45:57.424 [warning] <0.6.0> lager_error_logger_h dropped 49 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:45:57.424 [info] <0.3538.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): mnesia2_monitor starting: <0.3540.0>

2016-04-12 08:45:57.424 [info] <0.3538.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Version: "1.0.0"

2016-04-12 08:45:57.424 [info] <0.3538.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env access_module: mnesia2

2016-04-12 08:45:57.424 [info] <0.3538.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env auto_repair: true

2016-04-12 08:45:57.425 [info] <0.3538.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env backup_module: mnesia2_backup

2016-04-12 08:45:57.425 [info] <0.3538.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env debug: debug

2016-04-12 08:45:57.425 [info] <0.3538.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14.2016-04-12_08.45.13/Mnesia2.test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14"

2016-04-12 08:45:57.427 [info] <0.3544.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.3544.0>
2016-04-12 08:45:59.452 [warning] <0.6.0> lager_error_logger_h dropped 30 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:45:59.452 [info] <0.3619.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): mnesia2_monitor starting: <0.3621.0>

2016-04-12 08:45:59.452 [info] <0.3619.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Version: "1.0.0"

2016-04-12 08:45:59.453 [info] <0.3619.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env access_module: mnesia2

2016-04-12 08:45:59.453 [info] <0.3619.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env auto_repair: true

2016-04-12 08:45:59.453 [info] <0.3619.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env backup_module: mnesia2_backup

2016-04-12 08:45:59.454 [info] <0.3619.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env debug: trace

2016-04-12 08:45:59.454 [info] <0.3625.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.3625.0>
2016-04-12 08:45:59.455 [info] <0.3619.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14.2016-04-12_08.45.13/Mnesia2.test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14"

2016-04-12 08:45:59.455 [info] <0.3619.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env dump_disc_copies_at_startup: true

2016-04-12 08:45:59.456 [info] <0.3619.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env dump_log_load_regulation: false

2016-04-12 08:45:59.456 [info] <0.3619.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env dump_log_time_threshold: 180000

2016-04-12 08:46:01.481 [warning] <0.6.0> lager_error_logger_h dropped 27 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:46:01.481 [info] <0.3699.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): mnesia2_monitor starting: <0.3701.0>

2016-04-12 08:46:01.481 [info] <0.3699.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Version: "1.0.0"

2016-04-12 08:46:01.481 [info] <0.3699.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env access_module: mnesia2

2016-04-12 08:46:01.482 [info] <0.3699.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env auto_repair: true

2016-04-12 08:46:01.482 [info] <0.3699.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env backup_module: mnesia2_backup

2016-04-12 08:46:01.482 [info] <0.3699.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env debug: debug

2016-04-12 08:46:01.482 [info] <0.3699.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14.2016-04-12_08.45.13/Mnesia2.test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14"

2016-04-12 08:46:01.482 [info] <0.3699.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env dump_disc_copies_at_startup: true

2016-04-12 08:46:01.482 [info] <0.3699.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env dump_log_load_regulation: false

2016-04-12 08:46:01.482 [info] <0.3699.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env dump_log_time_threshold: 180000

2016-04-12 08:46:01.482 [info] <0.3699.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env dump_log_update_in_place: true

2016-04-12 08:46:01.483 [info] <0.3699.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env dump_log_write_threshold: 1000

2016-04-12 08:46:01.483 [info] <0.3699.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env event_module: mnesia2_event

2016-04-12 08:46:01.483 [info] <0.3699.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env extra_db_nodes: []

2016-04-12 08:46:01.483 [info] <0.3699.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env ignore_fallback_at_startup: false

2016-04-12 08:46:01.483 [info] <0.3699.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env fallback_error_function: {mnesia2,lkill}

2016-04-12 08:46:01.483 [info] <0.3699.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env max_wait_for_decision: infinity

2016-04-12 08:46:01.483 [info] <0.3699.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env schema_location: opt_disc

2016-04-12 08:46:01.483 [info] <0.3699.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env core_dir: false

2016-04-12 08:46:01.484 [info] <0.3699.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env pid_sort_order: false

2016-04-12 08:46:01.484 [info] <0.3699.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env no_table_loaders: 2

2016-04-12 08:46:01.484 [info] <0.3699.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env dc_dump_limit: 4

2016-04-12 08:46:01.484 [info] <0.3699.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env send_compressed: 0

2016-04-12 08:46:01.485 [info] <0.3699.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env send_max_packets: 20

2016-04-12 08:46:01.485 [info] <0.3699.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env send_max_transfer_size: 7500

2016-04-12 08:46:01.485 [info] <0.3699.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env async_dirty_buffer_size: 524288

2016-04-12 08:46:01.486 [info] <0.3699.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env async_dirty_max_buffer_file_size: 100000000

2016-04-12 08:46:01.486 [info] <0.3699.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env async_dirty_tx_backlog_threshold: 200000

2016-04-12 08:46:01.486 [info] <0.3699.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env async_dirty_buffer_min_runtime: 10000

2016-04-12 08:46:01.486 [info] <0.3699.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env async_dirty_buffer_drained_cutoff: 5

2016-04-12 08:46:01.486 [info] <0.3699.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Mnesia2 debug level set to debug
2016-04-12 08:46:01.487 [info] <0.3699.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): mnesia2_subscr starting: <0.3702.0>

2016-04-12 08:46:01.487 [info] <0.3699.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): mnesia2_locker starting: <0.3703.0>

2016-04-12 08:46:01.487 [info] <0.3699.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): mnesia2_recover starting: <0.3704.0>

2016-04-12 08:46:01.487 [info] <0.3699.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): mnesia2_tm starting: <0.3705.0>

2016-04-12 08:46:01.488 [info] <0.3699.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Schema initiated from: default

2016-04-12 08:46:01.488 [info] <0.3705.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.3705.0>
2016-04-12 08:46:01.488 [info] <0.3699.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): debug fun {mnesia2_tm,init} in ets mnesia2_debug does not exist, ignoring
2016-04-12 08:46:01.489 [info] <0.3699.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): mnesia2_controller starting: <0.3708.0>

2016-04-12 08:46:03.513 [warning] <0.6.0> lager_error_logger_h dropped 10 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:46:03.514 [info] <0.3761.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.3761.0>
2016-04-12 08:46:03.517 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:46:03.517 [error] <0.3752.0> CRASH REPORT Process <0.3752.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:46:03.517 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:46:06.577 [info] <0.3825.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.3825.0>
2016-04-12 08:46:06.580 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:46:06.580 [error] <0.3818.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.3820.0> exit with reason killed in context child_terminated
2016-04-12 08:46:06.581 [error] <0.3818.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.3820.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:46:06.581 [error] <0.3821.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-12 08:46:06.581 [error] <0.3821.0> CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:46:06.581 [error] <0.3816.0> CRASH REPORT Process <0.3816.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:46:06.581 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:46:07.685 [info] <0.3896.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.3896.0>
2016-04-12 08:46:07.687 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:46:07.692 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:46:07.700 [info] <0.3957.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.3957.0>
2016-04-12 08:46:14.620 [warning] <0.3951.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-12 08:46:22.780 [error] <0.3948.0> CRASH REPORT Process <0.3948.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:46:22.780 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:46:24.911 [info] <0.4487.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.4487.0>
2016-04-12 08:46:24.914 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:46:30.924 [error] <0.4478.0> CRASH REPORT Process <0.4478.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:46:30.924 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:46:33.053 [info] <0.4587.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.4587.0>
2016-04-12 08:46:33.056 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:46:34.085 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:46:36.278 [info] <0.4703.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.4703.0>
2016-04-12 08:46:36.280 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:46:36.292 [error] <0.4694.0> CRASH REPORT Process <0.4694.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:46:36.292 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:46:38.352 [info] <0.4770.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.4770.0>
2016-04-12 08:46:38.355 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:46:38.383 [error] <0.4761.0> CRASH REPORT Process <0.4761.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:46:38.383 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:46:40.524 [info] <0.4862.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.4862.0>
2016-04-12 08:46:40.527 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:46:40.532 [info] <0.1793.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.1793.0>
2016-04-12 08:46:40.541 [info] <0.7.0> Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:46:41.543 [error] <0.1845.0> gen_server <0.1845.0> terminated with reason: killed
2016-04-12 08:46:41.543 [error] <0.1845.0> CRASH REPORT Process <0.1845.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:46:41.544 [error] <0.1784.0> CRASH REPORT Process <0.1784.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:46:41.544 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:46:44.215 [info] <0.1861.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.1861.0>
2016-04-12 08:46:44.220 [info] <0.7.0> Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:46:45.224 [error] <0.4925.0> gen_server <0.4925.0> terminated with reason: killed
2016-04-12 08:46:45.224 [error] <0.4925.0> CRASH REPORT Process <0.4925.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:46:45.224 [error] <0.4853.0> CRASH REPORT Process <0.4853.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:46:45.225 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:46:46.289 [error] <0.1852.0> CRASH REPORT Process <0.1852.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:46:47.528 [info] <0.4968.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.4968.0>
2016-04-12 08:46:47.835 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:46:47.836 [error] <0.4959.0> CRASH REPORT Process <0.4959.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:46:46.289 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:46:47.531 [info] <0.1942.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.1942.0>
2016-04-12 08:46:47.542 [info] <0.7.0> Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:46:47.838 [error] <0.1937.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.1957.0> exit with reason killed in context child_terminated
2016-04-12 08:46:47.838 [error] <0.1937.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.1957.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:46:47.839 [error] <0.1937.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_controller:start() at <0.1959.0> exit with reason killed in context shutdown_error
2016-04-12 08:46:47.840 [error] <0.1997.0> gen_server <0.1997.0> terminated with reason: killed
2016-04-12 08:46:47.840 [error] <0.1997.0> CRASH REPORT Process <0.1997.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:46:47.840 [error] <0.1933.0> CRASH REPORT Process <0.1933.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:46:47.841 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:46:47.837 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:46:47.888 [info] <0.5044.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.5044.0>
2016-04-12 08:46:52.069 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:46:52.167 [info] <0.5168.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.5168.0>
2016-04-12 08:46:52.171 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:46:52.158 [info] <0.2019.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.2019.0>
2016-04-12 08:46:52.160 [info] <0.7.0> Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:47:07.312 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:47:07.332 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:47:08.490 [info] <0.2141.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.2141.0>
2016-04-12 08:47:08.495 [info] <0.7.0> Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:47:08.553 [error] <0.2195.0> gen_server <0.2195.0> terminated with reason: killed
2016-04-12 08:47:08.553 [error] <0.2195.0> CRASH REPORT Process <0.2195.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:08.554 [error] <0.2132.0> CRASH REPORT Process <0.2132.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:08.482 [info] <0.5299.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.5299.0>
2016-04-12 08:47:08.486 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:47:08.575 [error] <0.5290.0> CRASH REPORT Process <0.5290.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:08.575 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:08.609 [info] <0.5387.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.5387.0>
2016-04-12 08:47:08.554 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:10.613 [warning] <0.6.0> lager_error_logger_h dropped 27 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:47:10.613 [error] <0.5458.0> gen_server <0.5458.0> terminated with reason: killed
2016-04-12 08:47:10.613 [error] <0.5458.0> CRASH REPORT Process <0.5458.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:10.615 [error] <0.5378.0> CRASH REPORT Process <0.5378.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:10.050 [info] <0.2229.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.2229.0>
2016-04-12 08:47:10.060 [info] <0.7.0> Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:47:10.615 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:11.747 [error] <0.2220.0> CRASH REPORT Process <0.2220.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:11.748 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:16.515 [info] <0.2332.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.2332.0>
2016-04-12 08:47:16.534 [info] <0.7.0> Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:47:16.565 [error] <0.2323.0> CRASH REPORT Process <0.2323.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:16.424 [info] <0.5510.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.5510.0>
2016-04-12 08:47:16.426 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:47:16.566 [error] <0.5574.0> gen_server <0.5574.0> terminated with reason: killed
2016-04-12 08:47:16.566 [error] <0.5574.0> CRASH REPORT Process <0.5574.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:16.567 [error] <0.5501.0> CRASH REPORT Process <0.5501.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:16.567 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:16.565 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:18.708 [info] <0.2407.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.2407.0>
2016-04-12 08:47:18.716 [info] <0.7.0> Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:47:18.720 [error] <0.2418.0> gen_server <0.2418.0> terminated with reason: killed
2016-04-12 08:47:18.698 [info] <0.5621.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.5621.0>
2016-04-12 08:47:18.702 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:47:18.720 [error] <0.5685.0> gen_server <0.5685.0> terminated with reason: killed
2016-04-12 08:47:18.720 [error] <0.2418.0> CRASH REPORT Process <0.2418.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:18.720 [error] <0.5685.0> CRASH REPORT Process <0.5685.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:18.720 [error] <0.2398.0> CRASH REPORT Process <0.2398.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:18.722 [error] <0.5612.0> CRASH REPORT Process <0.5612.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:18.722 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:18.720 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:20.787 [info] <0.5701.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.5701.0>
2016-04-12 08:47:20.798 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:47:20.833 [error] <0.5696.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.5718.0> exit with reason killed in context child_terminated
2016-04-12 08:47:20.833 [error] <0.5696.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.5718.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:47:20.836 [error] <0.5743.0> gen_server <0.5743.0> terminated with reason: killed
2016-04-12 08:47:20.836 [error] <0.5743.0> CRASH REPORT Process <0.5743.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:20.837 [error] <0.5692.0> CRASH REPORT Process <0.5692.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:20.747 [info] <0.2466.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.2466.0>
2016-04-12 08:47:20.749 [info] <0.7.0> Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:47:20.837 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:22.307 [error] <0.2457.0> CRASH REPORT Process <0.2457.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:22.307 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:23.392 [info] <0.5826.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.5826.0>
2016-04-12 08:47:23.395 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:47:23.830 [error] <0.5871.0> gen_server <0.5871.0> terminated with reason: killed
2016-04-12 08:47:23.400 [info] <0.2553.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.2553.0>
2016-04-12 08:47:23.406 [info] <0.7.0> Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:47:23.832 [error] <0.2604.0> gen_server <0.2604.0> terminated with reason: killed
2016-04-12 08:47:23.830 [error] <0.5871.0> CRASH REPORT Process <0.5871.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:23.832 [error] <0.2604.0> CRASH REPORT Process <0.2604.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:23.830 [error] <0.5880.0> gen_server <0.5880.0> terminated with reason: killed
2016-04-12 08:47:23.832 [error] <0.2565.0> gen_server <0.2565.0> terminated with reason: killed
2016-04-12 08:47:23.832 [error] <0.2565.0> CRASH REPORT Process <0.2565.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:23.831 [error] <0.5880.0> CRASH REPORT Process <0.5880.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:23.833 [error] <0.2544.0> CRASH REPORT Process <0.2544.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:23.831 [error] <0.5817.0> CRASH REPORT Process <0.5817.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:23.831 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:23.833 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:23.707 [info] <0.7.0> Application lager started on node 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:47:23.708 [info] <0.7.0> Application poolgirl started on node 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:47:23.743 [info] <0.100.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.100.0>
2016-04-12 08:47:23.767 [info] <0.7.0> Application mnesia2 started on node 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:47:25.986 [info] <0.2634.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.2634.0>
2016-04-12 08:47:25.994 [info] <0.7.0> Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:47:26.011 [error] <0.2645.0> gen_server <0.2645.0> terminated with reason: killed
2016-04-12 08:47:25.976 [info] <0.5921.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.5921.0>
2016-04-12 08:47:25.979 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:47:26.015 [error] <0.5917.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-12 08:47:26.015 [error] <0.5917.0> CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:26.011 [error] <0.2645.0> CRASH REPORT Process <0.2645.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:26.015 [error] <0.5915.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): ** ERROR ** mnesia2_event got unexpected event: {'EXIT',<0.5918.0>,killed}

2016-04-12 08:47:26.012 [error] <0.2625.0> CRASH REPORT Process <0.2625.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:26.015 [error] <0.5915.0> CRASH REPORT Process mnesia2_event with 0 neighbours exited with reason: killed in gen_event:terminate_server/4 line 315
2016-04-12 08:47:26.017 [error] <0.5912.0> CRASH REPORT Process <0.5912.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:26.018 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:26.012 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:28.136 [info] <0.2704.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.2704.0>
2016-04-12 08:47:28.142 [info] <0.7.0> Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:47:28.152 [error] <0.2695.0> CRASH REPORT Process <0.2695.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:28.116 [info] <0.6015.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.6015.0>
2016-04-12 08:47:28.119 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:47:28.152 [error] <0.6006.0> CRASH REPORT Process <0.6006.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:28.153 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:28.153 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:30.324 [info] <0.2780.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.2780.0>
2016-04-12 08:47:30.332 [info] <0.7.0> Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:47:30.355 [error] <0.2770.0> CRASH REPORT Process <0.2770.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:30.297 [info] <0.6101.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.6101.0>
2016-04-12 08:47:30.300 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:47:30.355 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:31.396 [error] <0.6092.0> CRASH REPORT Process <0.6092.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:31.396 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:33.441 [info] <0.2849.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.2849.0>
2016-04-12 08:47:33.443 [info] <0.7.0> Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:47:38.467 [info] <0.6179.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.6179.0>
2016-04-12 08:47:38.478 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:47:38.504 [error] <0.6218.0> gen_server <0.6218.0> terminated with reason: killed
2016-04-12 08:47:38.493 [error] <0.2916.0> gen_server <0.2916.0> terminated with reason: killed
2016-04-12 08:47:38.494 [error] <0.2916.0> CRASH REPORT Process <0.2916.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:38.504 [error] <0.6218.0> CRASH REPORT Process <0.6218.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:38.494 [error] <0.2840.0> CRASH REPORT Process <0.2840.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:38.506 [error] <0.6170.0> CRASH REPORT Process <0.6170.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:38.506 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:38.494 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:39.712 [info] <0.2948.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.2948.0>
2016-04-12 08:47:39.726 [info] <0.7.0> Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:47:39.846 [error] <0.3011.0> gen_server <0.3011.0> terminated with reason: killed
2016-04-12 08:47:39.846 [error] <0.3011.0> CRASH REPORT Process <0.3011.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:39.846 [error] <0.2987.0> gen_server <0.2987.0> terminated with reason: killed
2016-04-12 08:47:39.846 [error] <0.2987.0> CRASH REPORT Process <0.2987.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:39.847 [error] <0.2939.0> CRASH REPORT Process <0.2939.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:39.702 [info] <0.6289.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.6289.0>
2016-04-12 08:47:39.705 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:47:39.927 [error] <0.6353.0> gen_server <0.6353.0> terminated with reason: killed
2016-04-12 08:47:39.927 [error] <0.6353.0> CRASH REPORT Process <0.6353.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:39.928 [error] <0.6392.0> gen_server <0.6392.0> terminated with reason: killed
2016-04-12 08:47:39.928 [error] <0.6392.0> CRASH REPORT Process <0.6392.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:39.929 [error] <0.6280.0> CRASH REPORT Process <0.6280.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:39.658 [warning] <0.6.0> lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:47:39.773 [info] <0.190.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.190.0>
2016-04-12 08:47:39.779 [info] <0.7.0> Application mnesia2 started on node 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:47:39.950 [error] <0.181.0> CRASH REPORT Process <0.181.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:39.950 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:40.064 [info] <0.294.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.294.0>
2016-04-12 08:47:40.088 [info] <0.7.0> Application mnesia2 started on node 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:47:39.929 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:40.059 [info] <0.6411.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.6411.0>
2016-04-12 08:47:40.366 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:47:39.847 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:39.877 [info] <0.3039.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.3039.0>
2016-04-12 08:47:40.021 [info] <0.3134.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.3134.0>
2016-04-12 08:47:40.025 [info] <0.7.0> Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:47:40.891 [error] <0.368.0> gen_server <0.368.0> terminated with reason: killed
2016-04-12 08:47:40.891 [error] <0.368.0> CRASH REPORT Process <0.368.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:40.891 [error] <0.356.0> gen_server <0.356.0> terminated with reason: killed
2016-04-12 08:47:40.892 [error] <0.356.0> CRASH REPORT Process <0.356.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:40.894 [error] <0.285.0> CRASH REPORT Process <0.285.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:40.894 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:40.925 [info] <0.392.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.392.0>
2016-04-12 08:47:43.036 [error] <0.6512.0> gen_server <0.6512.0> terminated with reason: killed
2016-04-12 08:47:43.037 [error] <0.6512.0> CRASH REPORT Process <0.6512.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:43.037 [error] <0.6481.0> gen_server <0.6481.0> terminated with reason: killed
2016-04-12 08:47:43.057 [error] <0.3129.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.3149.0> exit with reason killed in context child_terminated
2016-04-12 08:47:43.037 [error] <0.6481.0> CRASH REPORT Process <0.6481.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:43.037 [error] <0.6402.0> CRASH REPORT Process <0.6402.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:43.057 [error] <0.3129.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.3149.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:47:43.058 [error] <0.3226.0> gen_server <0.3226.0> terminated with reason: killed
2016-04-12 08:47:43.058 [error] <0.3226.0> CRASH REPORT Process <0.3226.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:43.058 [error] <0.3125.0> CRASH REPORT Process <0.3125.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:43.085 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:47:43.136 [info] <0.498.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.498.0>
2016-04-12 08:47:43.137 [info] <0.7.0> Application mnesia2 started on node 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:47:44.007 [error] <0.571.0> gen_server <0.571.0> terminated with reason: killed
2016-04-12 08:47:44.007 [error] <0.571.0> CRASH REPORT Process <0.571.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:43.037 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:43.170 [info] <0.6529.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.6529.0>
2016-04-12 08:47:43.479 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:47:44.008 [error] <0.565.0> gen_server <0.565.0> terminated with reason: killed
2016-04-12 08:47:43.058 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:43.172 [info] <0.3247.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.3247.0>
2016-04-12 08:47:43.201 [info] <0.7.0> Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:47:44.008 [error] <0.565.0> CRASH REPORT Process <0.565.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:44.008 [error] <0.489.0> CRASH REPORT Process <0.489.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:44.009 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:44.040 [info] <0.596.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.596.0>
2016-04-12 08:47:44.042 [info] <0.7.0> Application mnesia2 started on node 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:47:44.160 [error] <0.6617.0> gen_server <0.6617.0> terminated with reason: killed
2016-04-12 08:47:44.160 [error] <0.6617.0> CRASH REPORT Process <0.6617.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:44.164 [error] <0.6520.0> CRASH REPORT Process <0.6520.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:44.180 [error] <0.3335.0> gen_server <0.3335.0> terminated with reason: killed
2016-04-12 08:47:44.180 [error] <0.3335.0> CRASH REPORT Process <0.3335.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:44.181 [error] <0.3238.0> CRASH REPORT Process <0.3238.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:44.164 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:44.313 [info] <0.6641.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.6641.0>
2016-04-12 08:47:44.623 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:47:44.181 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:44.318 [info] <0.3356.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.3356.0>
2016-04-12 08:47:44.337 [info] <0.7.0> Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:47:45.164 [error] <0.3347.0> CRASH REPORT Process <0.3347.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:45.164 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:44.208 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:47:44.232 [info] <0.697.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.697.0>
2016-04-12 08:47:45.210 [info] <0.3452.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.3452.0>
2016-04-12 08:47:45.228 [info] <0.7.0> Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:47:45.248 [error] <0.3478.0> gen_server <0.3478.0> terminated with reason: killed
2016-04-12 08:47:45.248 [error] <0.3478.0> CRASH REPORT Process <0.3478.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:45.248 [error] <0.3465.0> gen_server <0.3465.0> terminated with reason: killed
2016-04-12 08:47:45.248 [error] <0.3465.0> CRASH REPORT Process <0.3465.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:45.249 [error] <0.3508.0> gen_server <0.3508.0> terminated with reason: killed
2016-04-12 08:47:45.249 [error] <0.3508.0> CRASH REPORT Process <0.3508.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:45.249 [error] <0.3443.0> CRASH REPORT Process <0.3443.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:45.249 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:46.276 [info] <0.3530.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.3530.0>
2016-04-12 08:47:46.309 [info] <0.7.0> Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:47:46.377 [error] <0.3543.0> gen_server <0.3543.0> terminated with reason: killed
2016-04-12 08:47:46.376 [error] <0.6754.0> gen_server <0.6754.0> terminated with reason: killed
2016-04-12 08:47:46.379 [error] <0.692.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.712.0> exit with reason killed in context child_terminated
2016-04-12 08:47:46.377 [error] <0.3543.0> CRASH REPORT Process <0.3543.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:46.376 [error] <0.6754.0> CRASH REPORT Process <0.6754.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:46.380 [error] <0.692.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.712.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:47:46.377 [error] <0.6632.0> CRASH REPORT Process <0.6632.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:46.379 [error] <0.3521.0> CRASH REPORT Process <0.3521.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:46.380 [error] <0.820.0> gen_server <0.820.0> terminated with reason: killed
2016-04-12 08:47:46.380 [error] <0.820.0> CRASH REPORT Process <0.820.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:46.380 [error] <0.812.0> gen_server <0.812.0> terminated with reason: killed
2016-04-12 08:47:46.380 [error] <0.812.0> CRASH REPORT Process <0.812.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:46.380 [error] <0.771.0> gen_server <0.771.0> terminated with reason: killed
2016-04-12 08:47:46.380 [error] <0.771.0> CRASH REPORT Process <0.771.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:46.381 [error] <0.688.0> CRASH REPORT Process <0.688.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:46.379 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:46.472 [info] <0.3608.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.3608.0>
2016-04-12 08:47:46.893 [info] <0.3704.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.3704.0>
2016-04-12 08:47:46.993 [info] <0.3794.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.3794.0>
2016-04-12 08:47:47.017 [warning] <0.6.0> lager_error_logger_h dropped 24 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:47:47.017 [error] <0.3856.0> gen_server <0.3856.0> terminated with reason: killed
2016-04-12 08:47:47.017 [error] <0.3856.0> CRASH REPORT Process <0.3856.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:47.018 [error] <0.3785.0> CRASH REPORT Process <0.3785.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:47.018 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:47.074 [info] <0.3894.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.3894.0>
2016-04-12 08:47:47.076 [info] <0.7.0> Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:47:46.377 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:46.468 [info] <0.6787.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.6787.0>
2016-04-12 08:47:46.777 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:47:47.060 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:47:46.381 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:47.708 [error] <0.3949.0> gen_server <0.3949.0> terminated with reason: killed
2016-04-12 08:47:47.708 [error] <0.3949.0> CRASH REPORT Process <0.3949.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:47.622 [info] <0.6901.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.6901.0>
2016-04-12 08:47:47.661 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:47:47.707 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:47:48.039 [info] <0.6984.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.6984.0>
2016-04-12 08:47:48.043 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:47:48.652 [error] <0.7048.0> gen_server <0.7048.0> terminated with reason: killed
2016-04-12 08:47:48.554 [info] <0.3976.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.3976.0>
2016-04-12 08:47:48.587 [info] <0.7.0> Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:47:48.653 [error] <0.4024.0> gen_server <0.4024.0> terminated with reason: killed
2016-04-12 08:47:48.652 [error] <0.7048.0> CRASH REPORT Process <0.7048.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:48.653 [error] <0.4024.0> CRASH REPORT Process <0.4024.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:48.655 [error] <0.6975.0> CRASH REPORT Process <0.6975.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:48.654 [error] <0.3967.0> CRASH REPORT Process <0.3967.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:48.654 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:48.655 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:48.736 [info] <0.7085.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.7085.0>
2016-04-12 08:47:49.045 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:47:48.743 [info] <0.4068.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.4068.0>
2016-04-12 08:47:48.744 [info] <0.848.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.848.0>
2016-04-12 08:47:48.763 [info] <0.7.0> Application mnesia2 started on node 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:47:50.300 [error] <0.903.0> gen_server <0.903.0> terminated with reason: killed
2016-04-12 08:47:50.302 [error] <0.7149.0> gen_server <0.7149.0> terminated with reason: killed
2016-04-12 08:47:50.303 [warning] <0.6.0> lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:47:50.303 [error] <0.4131.0> gen_server <0.4131.0> terminated with reason: killed
2016-04-12 08:47:50.302 [error] <0.7149.0> CRASH REPORT Process <0.7149.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:50.300 [error] <0.903.0> CRASH REPORT Process <0.903.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:50.304 [error] <0.4131.0> CRASH REPORT Process <0.4131.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:50.302 [error] <0.7076.0> CRASH REPORT Process <0.7076.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:50.301 [error] <0.839.0> CRASH REPORT Process <0.839.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:50.304 [error] <0.4059.0> CRASH REPORT Process <0.4059.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:50.304 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:50.329 [info] <0.4161.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.4161.0>
2016-04-12 08:47:50.330 [info] <0.7.0> Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:47:50.428 [error] <0.4216.0> gen_server <0.4216.0> terminated with reason: killed
2016-04-12 08:47:50.301 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:50.331 [info] <0.951.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.951.0>
2016-04-12 08:47:50.333 [info] <0.7.0> Application mnesia2 started on node 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:47:50.427 [error] <0.1000.0> gen_server <0.1000.0> terminated with reason: killed
2016-04-12 08:47:50.427 [error] <0.1000.0> CRASH REPORT Process <0.1000.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:50.427 [error] <0.1009.0> gen_server <0.1009.0> terminated with reason: killed
2016-04-12 08:47:50.302 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:50.390 [info] <0.7197.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.7197.0>
2016-04-12 08:47:50.415 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:47:50.440 [error] <0.7264.0> gen_server <0.7264.0> terminated with reason: killed
2016-04-12 08:47:50.428 [error] <0.4216.0> CRASH REPORT Process <0.4216.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:50.427 [error] <0.1009.0> CRASH REPORT Process <0.1009.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:50.440 [error] <0.7264.0> CRASH REPORT Process <0.7264.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:50.428 [error] <0.995.0> gen_server <0.995.0> terminated with reason: killed
2016-04-12 08:47:50.440 [error] <0.7259.0> gen_server <0.7259.0> terminated with reason: killed
2016-04-12 08:47:50.441 [error] <0.7259.0> CRASH REPORT Process <0.7259.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:50.428 [error] <0.995.0> CRASH REPORT Process <0.995.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:50.429 [error] <0.942.0> CRASH REPORT Process <0.942.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:50.441 [error] <0.7188.0> CRASH REPORT Process <0.7188.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:50.442 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:50.528 [info] <0.7289.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.7289.0>
2016-04-12 08:47:50.537 [error] <0.7283.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): ** ERROR ** (core dumped to file: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14.2016-04-12_08.45.13/Mnesia2Core.test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14_1460_450870_536736")
 ** FATAL ** Failed to merge schema: Bad cookie in table definition tab1: 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14' = {cstruct,tab1,set,['d1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14','d1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14'],['test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'],[],0,read_write,false,[],[],false,tab1,[key,val],[],[],[],{{1460450870282104696,-576460752303402878,1},'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'},{{2,0},[]}}, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14' = {cstruct,tab1,set,['d1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14'],[],[],0,read_write,false,[],[],false,tab1,[key,val],[],[],[],{{1460450870476728941,-576460752303421247,1},'d1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14'},{{2,0},[]}}


2016-04-12 08:47:50.429 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:50.468 [info] <0.1028.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.1028.0>
2016-04-12 08:47:50.467 [info] <0.4239.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.4239.0>
2016-04-12 08:48:00.538 [error] <0.7282.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at undefined exit with reason killed in context start_error
2016-04-12 08:48:00.538 [error] <0.7285.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-12 08:48:00.538 [error] <0.7288.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-12 08:48:00.538 [error] <0.7288.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:48:00.538 [error] <0.7308.0> gen_server mnesia2_snmp_sup terminated with reason: killed
2016-04-12 08:48:00.538 [error] <0.7308.0> CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:48:00.538 [error] <0.7286.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-12 08:48:00.538 [error] <0.7286.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:48:00.538 [error] <0.7280.0> CRASH REPORT Process <0.7280.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}} in application_master:init/4 line 134
2016-04-12 08:48:00.539 [info] <0.7.0> Application mnesia2 exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}}
2016-04-12 08:48:00.539 [error] <0.7285.0> CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:48:00.664 [error] <0.1077.0> gen_server <0.1077.0> terminated with reason: killed
2016-04-12 08:48:00.664 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:48:00.664 [error] <0.4283.0> gen_server <0.4283.0> terminated with reason: killed
2016-04-12 08:48:00.664 [error] <0.1077.0> CRASH REPORT Process <0.1077.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:48:00.664 [error] <0.4283.0> CRASH REPORT Process <0.4283.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:48:00.664 [error] <0.1072.0> gen_server <0.1072.0> terminated with reason: killed
2016-04-12 08:48:00.665 [error] <0.4230.0> CRASH REPORT Process <0.4230.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:48:00.665 [error] <0.1072.0> CRASH REPORT Process <0.1072.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:48:00.665 [error] <0.1019.0> CRASH REPORT Process <0.1019.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:48:00.665 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:48:00.665 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:48:03.195 [info] <0.7398.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.7398.0>
2016-04-12 08:48:03.198 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:48:08.969 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:09.127 [info] <0.7534.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.7534.0>
2016-04-12 08:48:09.435 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:48:09.128 [info] <0.4330.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.4330.0>
2016-04-12 08:48:09.166 [info] <0.7.0> Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:48:09.131 [info] <0.1124.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.1124.0>
2016-04-12 08:48:09.190 [info] <0.7.0> Application mnesia2 started on node 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:48:15.864 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:16.044 [info] <0.4446.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.4446.0>
2016-04-12 08:48:16.067 [info] <0.7.0> Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:48:15.866 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:16.021 [info] <0.7664.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.7664.0>
2016-04-12 08:48:16.025 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:48:15.898 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:16.031 [info] <0.1239.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.1239.0>
2016-04-12 08:48:16.348 [info] <0.7.0> Application mnesia2 started on node 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:48:22.488 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:22.675 [info] <0.4562.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.4562.0>
2016-04-12 08:48:22.707 [info] <0.7.0> Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:48:22.490 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:22.656 [info] <0.7793.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.7793.0>
2016-04-12 08:48:22.659 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:48:22.505 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:22.683 [info] <0.1354.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.1354.0>
2016-04-12 08:48:22.693 [info] <0.7.0> Application mnesia2 started on node 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:48:47.145 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:47.722 [info] <0.8932.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.8932.0>
2016-04-12 08:48:47.726 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:48:47.171 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:47.761 [info] <0.5688.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.5688.0>
2016-04-12 08:48:47.766 [info] <0.7.0> Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:48:47.166 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:47.738 [info] <0.2477.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.2477.0>
2016-04-12 08:48:47.755 [info] <0.7.0> Application mnesia2 started on node 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:48:54.154 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:54.318 [info] <0.5810.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.5810.0>
2016-04-12 08:48:54.624 [info] <0.7.0> Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:48:54.168 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:54.305 [info] <0.9071.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.9071.0>
2016-04-12 08:48:54.308 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:48:54.172 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:54.322 [info] <0.2601.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.2601.0>
2016-04-12 08:48:54.348 [info] <0.7.0> Application mnesia2 started on node 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:49:01.188 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:49:01.368 [info] <0.4071.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.4071.0>
2016-04-12 08:49:01.388 [info] <0.7.0> Application mnesia2 started on node 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:49:01.197 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:49:01.333 [info] <0.10551.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.10551.0>
2016-04-12 08:49:01.643 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:49:01.198 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:49:01.336 [info] <0.7282.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.7282.0>
2016-04-12 08:49:01.673 [info] <0.7.0> Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:49:08.012 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:49:08.182 [info] <0.10856.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.10856.0>
2016-04-12 08:49:08.502 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:49:08.014 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:49:08.201 [info] <0.5905.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.5905.0>
2016-04-12 08:49:08.509 [info] <0.7.0> Application mnesia2 started on node 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:49:08.029 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:49:08.205 [info] <0.8279.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.8279.0>
2016-04-12 08:49:08.219 [info] <0.7.0> Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:49:14.679 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:49:14.840 [info] <0.8394.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.8394.0>
2016-04-12 08:49:14.842 [info] <0.7.0> Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:49:14.684 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:49:14.846 [info] <0.10986.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.10986.0>
2016-04-12 08:49:14.852 [info] <0.7.0> Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:49:14.688 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:49:14.868 [info] <0.6703.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.6703.0>
2016-04-12 08:49:14.875 [info] <0.7.0> Application mnesia2 started on node 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14'
2016-04-12 08:49:21.168 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:49:21.159 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:49:21.166 [info] <0.7.0> Application mnesia2 exited with reason: stopped
