2016-04-10 16:45:18.749 [info] <0.7.0> Application lager started on node 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:45:18.749 [info] <0.7.0> Application poolgirl started on node 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:45:18.823 [info] <0.494.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.494.0>
2016-04-10 16:45:19.005 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:45:19.042 [info] <0.562.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.562.0>
2016-04-10 16:45:19.044 [info] <0.7.0> Application mnesia2 started on node 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:45:19.426 [error] <0.553.0> CRASH REPORT Process <0.553.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:45:19.426 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:45:19.580 [info] <0.672.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.672.0>
2016-04-10 16:45:19.785 [info] <0.7.0> Application lager started on node 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:45:19.785 [info] <0.7.0> Application poolgirl started on node 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:45:19.845 [info] <0.99.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.99.0>
2016-04-10 16:45:20.058 [error] <0.155.0> gen_server <0.155.0> terminated with reason: killed
2016-04-10 16:45:20.058 [error] <0.155.0> CRASH REPORT Process <0.155.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:45:20.060 [error] <0.729.0> gen_server <0.729.0> terminated with reason: killed
2016-04-10 16:45:20.058 [error] <0.90.0> CRASH REPORT Process <0.90.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:45:20.060 [error] <0.729.0> CRASH REPORT Process <0.729.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:45:20.060 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:45:20.060 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:45:20.103 [info] <0.798.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.798.0>
2016-04-10 16:45:20.105 [info] <0.7.0> Application mnesia2 started on node 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:45:20.442 [error] <0.792.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): ** ERROR ** (ignoring core) ** FATAL ** A fallback is installed and Mnesia2 must be restarted. Forcing shutdown after mnesia2_down from 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4'...

2016-04-10 16:45:20.442 [error] <0.793.0> Supervisor mnesia2_kernel_sup had child mnesia2_locker started with mnesia2_locker:start() at <0.796.0> exit with reason killed in context child_terminated
2016-04-10 16:45:20.058 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:45:20.120 [info] <0.215.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.215.0>
2016-04-10 16:45:20.124 [info] <0.7.0> Application mnesia2 started on node 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:45:20.443 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:45:20.493 [info] <0.368.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.368.0>
2016-04-10 16:45:20.473 [info] <0.926.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.926.0>
2016-04-10 16:45:21.033 [warning] <0.6.0> lager_error_logger_h dropped 24 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:45:21.033 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:45:21.046 [info] <0.1026.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.1026.0>
2016-04-10 16:45:21.048 [info] <0.7.0> Application mnesia2 started on node 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:45:21.031 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:45:21.050 [info] <0.458.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.458.0>
2016-04-10 16:45:21.053 [info] <0.7.0> Application mnesia2 started on node 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:45:21.786 [error] <0.514.0> gen_server <0.514.0> terminated with reason: killed
2016-04-10 16:45:21.787 [error] <0.1017.0> CRASH REPORT Process <0.1017.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:45:21.786 [error] <0.514.0> CRASH REPORT Process <0.514.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:45:21.786 [error] <0.449.0> CRASH REPORT Process <0.449.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:45:21.786 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:45:21.852 [info] <0.547.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.547.0>
2016-04-10 16:45:22.410 [error] <0.662.0> gen_server <0.662.0> terminated with reason: killed
2016-04-10 16:45:21.787 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:45:21.834 [info] <0.1149.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.1149.0>
2016-04-10 16:45:21.980 [info] <0.1261.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.1261.0>
2016-04-10 16:45:22.411 [warning] <0.6.0> lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:45:22.411 [error] <0.1252.0> CRASH REPORT Process <0.1252.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:45:22.410 [error] <0.662.0> CRASH REPORT Process <0.662.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:45:22.411 [error] <0.538.0> CRASH REPORT Process <0.538.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:45:22.411 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:45:22.492 [info] <0.761.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.761.0>
2016-04-10 16:45:22.496 [info] <0.7.0> Application mnesia2 started on node 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:45:22.631 [error] <0.815.0> gen_server <0.815.0> terminated with reason: killed
2016-04-10 16:45:22.412 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:45:22.472 [info] <0.1493.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.1493.0>
2016-04-10 16:45:22.474 [info] <0.7.0> Application mnesia2 started on node 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:45:22.633 [error] <0.1547.0> gen_server <0.1547.0> terminated with reason: killed
2016-04-10 16:45:22.631 [error] <0.815.0> CRASH REPORT Process <0.815.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:45:22.643 [error] <0.1547.0> CRASH REPORT Process <0.1547.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:45:22.644 [error] <0.1484.0> CRASH REPORT Process <0.1484.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:45:22.644 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:45:22.689 [info] <0.1607.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.1607.0>
2016-04-10 16:45:22.695 [info] <0.860.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.860.0>
2016-04-10 16:45:22.915 [info] <0.961.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.961.0>
2016-04-10 16:45:23.126 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:45:23.126 [error] <0.1013.0> gen_server <0.1013.0> terminated with reason: killed
2016-04-10 16:45:22.911 [info] <0.1723.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.1723.0>
2016-04-10 16:45:23.129 [warning] <0.6.0> lager_error_logger_h dropped 40 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:45:23.129 [error] <0.1779.0> gen_server <0.1779.0> terminated with reason: killed
2016-04-10 16:45:23.126 [error] <0.1013.0> CRASH REPORT Process <0.1013.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:45:23.129 [error] <0.1779.0> CRASH REPORT Process <0.1779.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:45:23.129 [error] <0.1714.0> CRASH REPORT Process <0.1714.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:45:23.126 [error] <0.952.0> CRASH REPORT Process <0.952.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:45:23.126 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:45:23.205 [info] <0.1067.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.1067.0>
2016-04-10 16:45:23.208 [info] <0.7.0> Application mnesia2 started on node 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:45:23.353 [error] <0.1119.0> gen_server <0.1119.0> terminated with reason: killed
2016-04-10 16:45:23.129 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:45:23.200 [info] <0.1849.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.1849.0>
2016-04-10 16:45:23.203 [info] <0.7.0> Application mnesia2 started on node 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:45:23.355 [error] <0.1903.0> gen_server <0.1903.0> terminated with reason: killed
2016-04-10 16:45:23.353 [error] <0.1119.0> CRASH REPORT Process <0.1119.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:45:23.355 [error] <0.1903.0> CRASH REPORT Process <0.1903.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:45:23.407 [info] <0.1980.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.1980.0>
2016-04-10 16:45:23.688 [info] <0.2113.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.2113.0>
2016-04-10 16:45:23.413 [info] <0.1166.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.1166.0>
2016-04-10 16:45:23.701 [info] <0.1267.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.1267.0>
2016-04-10 16:45:23.976 [info] <0.1373.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.1373.0>
2016-04-10 16:45:24.186 [warning] <0.6.0> lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:45:24.186 [error] <0.1427.0> gen_server <0.1427.0> terminated with reason: killed
2016-04-10 16:45:23.971 [info] <0.2253.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.2253.0>
2016-04-10 16:45:24.187 [warning] <0.6.0> lager_error_logger_h dropped 18 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:45:24.187 [error] <0.2309.0> gen_server <0.2309.0> terminated with reason: killed
2016-04-10 16:45:24.187 [error] <0.2309.0> CRASH REPORT Process <0.2309.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:45:24.186 [error] <0.1427.0> CRASH REPORT Process <0.1427.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:45:24.188 [error] <0.2244.0> CRASH REPORT Process <0.2244.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:45:24.187 [error] <0.1364.0> CRASH REPORT Process <0.1364.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:45:24.187 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:45:24.329 [info] <0.1460.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.1460.0>
2016-04-10 16:45:24.332 [info] <0.7.0> Application mnesia2 started on node 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:45:24.188 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:45:24.323 [info] <0.2384.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.2384.0>
2016-04-10 16:45:24.325 [info] <0.7.0> Application mnesia2 started on node 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:45:24.497 [error] <0.2440.0> gen_server <0.2440.0> terminated with reason: killed
2016-04-10 16:45:24.497 [error] <0.1514.0> gen_server <0.1514.0> terminated with reason: killed
2016-04-10 16:45:24.497 [error] <0.2440.0> CRASH REPORT Process <0.2440.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:45:24.497 [error] <0.1514.0> CRASH REPORT Process <0.1514.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:45:24.558 [info] <0.2516.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.2516.0>
2016-04-10 16:45:24.796 [info] <0.2639.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.2639.0>
2016-04-10 16:45:25.115 [warning] <0.6.0> lager_error_logger_h dropped 12 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:45:25.115 [error] <0.2630.0> CRASH REPORT Process <0.2630.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:45:25.115 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:45:25.151 [info] <0.2767.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.2767.0>
2016-04-10 16:45:25.153 [info] <0.7.0> Application mnesia2 started on node 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:45:25.189 [error] <0.2758.0> CRASH REPORT Process <0.2758.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:45:24.562 [info] <0.1572.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.1572.0>
2016-04-10 16:45:24.805 [info] <0.1660.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.1660.0>
2016-04-10 16:45:25.189 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:45:25.224 [info] <0.2861.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.2861.0>
2016-04-10 16:45:26.464 [info] <0.2971.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.2971.0>
2016-04-10 16:45:26.466 [info] <0.7.0> Application mnesia2 started on node 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:45:27.671 [error] <0.2962.0> CRASH REPORT Process <0.2962.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:45:27.671 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:45:29.763 [info] <0.3077.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.3077.0>
2016-04-10 16:45:29.765 [info] <0.7.0> Application mnesia2 started on node 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:45:29.767 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:45:29.768 [info] <0.3125.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.3125.0>
2016-04-10 16:45:29.773 [info] <0.3173.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.3173.0>
2016-04-10 16:45:31.866 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:45:31.872 [info] <0.3245.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.3245.0>
2016-04-10 16:45:31.874 [info] <0.7.0> Application mnesia2 started on node 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:45:31.888 [error] <0.3236.0> CRASH REPORT Process <0.3236.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:45:31.888 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:45:34.319 [info] <0.3328.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.3328.0>
2016-04-10 16:45:34.322 [info] <0.7.0> Application mnesia2 started on node 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:45:34.328 [info] <0.3322.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Restore aborted. mnesia2_config_backup:open_read["NonExisting.FILE"] -> {enoent,error}

2016-04-10 16:45:34.328 [info] <0.3322.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Restore aborted. mnesia2_config_backup:open_read["/home/travis/build/lrascao/mnesia2/logs/ct_run.test1018@testing-worker-linux-docker-236c71da-3354-linux-4.2016-04-10_16.44.52/Mnesia2.test1018@testing-worker-linux-docker-236c71da-3354-linux-4/LATEST.LOG"] -> badarg

2016-04-10 16:45:34.328 [error] <0.3321.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.3323.0> exit with reason killed in context child_terminated
2016-04-10 16:45:34.329 [error] <0.3321.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.3323.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 16:45:34.329 [info] <0.3427.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): mnesia2_tm_24 terminated: shutdown

2016-04-10 16:45:34.329 [info] <0.3427.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): mnesia2_tm_28 terminated: shutdown

2016-04-10 16:45:34.330 [error] <0.3354.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_1,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_1,shutdown]}}}} ({error,{already_started,<0.3427.0>}})

2016-04-10 16:45:34.330 [error] <0.3356.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}}} ({error,{already_started,<0.3427.0>}})

2016-04-10 16:45:34.330 [error] <0.3358.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}}} ({error,{already_started,<0.3427.0>}})

2016-04-10 16:45:34.330 [error] <0.3357.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}}} ({error,{already_started,<0.3427.0>}})

2016-04-10 16:45:34.330 [error] <0.3355.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}}} ({error,{already_started,<0.3427.0>}})

2016-04-10 16:45:34.330 [error] <0.3360.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}}} ({error,{already_started,<0.3427.0>}})

2016-04-10 16:45:34.331 [error] <0.3362.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}}} ({error,{already_started,<0.3427.0>}})

2016-04-10 16:45:34.331 [error] <0.3361.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}}} ({error,{already_started,<0.3427.0>}})

2016-04-10 16:45:34.331 [error] <0.3364.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_11,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_11,shutdown]}}}} ({error,{already_started,<0.3427.0>}})

2016-04-10 16:45:34.331 [error] <0.3366.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_13,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_13,shutdown]}}}} ({error,{already_started,<0.3427.0>}})

2016-04-10 16:45:34.331 [error] <0.3365.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_12,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_12,shutdown]}}}} ({error,{already_started,<0.3427.0>}})

2016-04-10 16:45:34.331 [error] <0.3363.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_10,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_10,shutdown]}}}} ({error,{already_started,<0.3427.0>}})

2016-04-10 16:45:34.331 [error] <0.3368.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_15,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_15,shutdown]}}}} ({error,{already_started,<0.3427.0>}})

2016-04-10 16:45:34.331 [error] <0.3370.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_17,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_17,shutdown]}}}} ({error,{already_started,<0.3427.0>}})

2016-04-10 16:45:34.331 [error] <0.3369.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_16,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_16,shutdown]}}}} ({error,{already_started,<0.3427.0>}})

2016-04-10 16:45:34.331 [error] <0.3372.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_19,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_19,shutdown]}}}} ({error,{already_started,<0.3427.0>}})

2016-04-10 16:45:34.332 [error] <0.3374.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_21,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_21,shutdown]}}}} ({error,{already_started,<0.3427.0>}})

2016-04-10 16:45:34.332 [error] <0.3373.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_20,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_20,shutdown]}}}} ({error,{already_started,<0.3427.0>}})

2016-04-10 16:45:34.332 [error] <0.3371.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_18,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_18,shutdown]}}}} ({error,{already_started,<0.3427.0>}})

2016-04-10 16:45:34.332 [error] <0.3367.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_14,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_14,shutdown]}}}} ({error,{already_started,<0.3427.0>}})

2016-04-10 16:45:34.377 [error] <0.3376.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_23,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_23,shutdown]}}}} ({error,{already_started,<0.3427.0>}})

2016-04-10 16:45:34.377 [error] <0.3378.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_25,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_25,shutdown]}}}} ({error,{already_started,<0.3427.0>}})

2016-04-10 16:45:34.377 [error] <0.3380.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_27,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_27,shutdown]}}}} ({error,{already_started,<0.3427.0>}})

2016-04-10 16:45:34.377 [info] <0.3427.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): mnesia2_tm_32 terminated: shutdown

2016-04-10 16:45:34.377 [error] <0.3319.0> CRASH REPORT Process <0.3319.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:45:34.377 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:45:36.421 [info] <0.3446.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): mnesia2_monitor starting: <0.3448.0>

2016-04-10 16:45:36.422 [info] <0.3446.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Mnesia2 debug level set to verbose
2016-04-10 16:45:36.422 [info] <0.3446.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): mnesia2_subscr starting: <0.3449.0>

2016-04-10 16:45:36.422 [info] <0.3446.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): mnesia2_locker starting: <0.3450.0>

2016-04-10 16:45:36.423 [info] <0.3446.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): mnesia2_recover starting: <0.3451.0>

2016-04-10 16:45:36.423 [info] <0.3446.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): mnesia2_tm starting: <0.3452.0>

2016-04-10 16:45:36.423 [info] <0.3446.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Schema initiated from: default

2016-04-10 16:45:36.424 [info] <0.3452.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.3452.0>
2016-04-10 16:45:36.424 [info] <0.3446.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): mnesia2_controller starting: <0.3455.0>

2016-04-10 16:45:36.424 [info] <0.3446.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): mnesia2_late_loader starting: <0.3456.0>

2016-04-10 16:45:36.425 [info] <0.3446.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Intend to load tables: []

2016-04-10 16:45:36.425 [info] <0.3446.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): mnesia2_tm_1 starting: <0.3458.0>

2016-04-10 16:45:36.425 [info] <0.3446.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): mnesia2_tm_2 starting: <0.3459.0>

2016-04-10 16:45:36.425 [info] <0.3446.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): mnesia2_tm_3 starting: <0.3460.0>

2016-04-10 16:45:36.426 [info] <0.3446.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): mnesia2_tm_4 starting: <0.3461.0>

2016-04-10 16:45:36.426 [info] <0.3446.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): mnesia2_tm_5 starting: <0.3462.0>

2016-04-10 16:45:36.426 [info] <0.3446.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): mnesia2_tm_6 starting: <0.3463.0>

2016-04-10 16:45:36.426 [info] <0.3446.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): mnesia2_tm_7 starting: <0.3464.0>

2016-04-10 16:45:36.426 [info] <0.3446.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): mnesia2_tm_8 starting: <0.3465.0>

2016-04-10 16:45:36.426 [info] <0.3446.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): mnesia2_tm_9 starting: <0.3466.0>

2016-04-10 16:45:36.427 [info] <0.3446.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): mnesia2_tm_10 starting: <0.3467.0>

2016-04-10 16:45:36.427 [info] <0.3446.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): mnesia2_tm_11 starting: <0.3468.0>

2016-04-10 16:45:36.427 [info] <0.3446.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): mnesia2_tm_12 starting: <0.3469.0>

2016-04-10 16:45:36.427 [info] <0.3446.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): mnesia2_tm_13 starting: <0.3470.0>

2016-04-10 16:45:36.427 [info] <0.7.0> Application mnesia2 started on node 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:45:36.427 [info] <0.3446.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): mnesia2_tm_14 starting: <0.3471.0>

2016-04-10 16:45:36.428 [info] <0.3512.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): mnesia2_tm_24 terminated: shutdown

2016-04-10 16:45:36.429 [error] <0.3458.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_1,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_1,shutdown]}}}} ({error,{already_started,<0.3512.0>}})

2016-04-10 16:45:36.429 [error] <0.3460.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}}} ({error,{already_started,<0.3512.0>}})

2016-04-10 16:45:36.429 [error] <0.3462.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}}} ({error,{already_started,<0.3512.0>}})

2016-04-10 16:45:36.429 [error] <0.3461.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}}} ({error,{already_started,<0.3512.0>}})

2016-04-10 16:45:36.430 [error] <0.3459.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}}} ({error,{already_started,<0.3512.0>}})

2016-04-10 16:45:36.430 [error] <0.3464.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}}} ({error,{already_started,<0.3512.0>}})

2016-04-10 16:45:36.430 [error] <0.3465.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}}} ({error,{already_started,<0.3512.0>}})

2016-04-10 16:45:36.430 [error] <0.3466.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}}} ({error,{already_started,<0.3512.0>}})

2016-04-10 16:45:36.430 [error] <0.3468.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_11,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_11,shutdown]}}}} ({error,{already_started,<0.3512.0>}})

2016-04-10 16:45:38.450 [warning] <0.6.0> lager_error_logger_h dropped 13 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:45:38.450 [info] <0.3517.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): mnesia2_monitor starting: <0.3519.0>

2016-04-10 16:45:38.451 [info] <0.3517.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Version: "1.0.0"

2016-04-10 16:45:38.451 [info] <0.3517.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env access_module: mnesia2

2016-04-10 16:45:38.451 [info] <0.3517.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env auto_repair: true

2016-04-10 16:45:38.451 [info] <0.3517.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env backup_module: mnesia2_backup

2016-04-10 16:45:38.451 [info] <0.3517.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env debug: debug

2016-04-10 16:45:38.451 [info] <0.3517.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test1018@testing-worker-linux-docker-236c71da-3354-linux-4.2016-04-10_16.44.52/Mnesia2.test1018@testing-worker-linux-docker-236c71da-3354-linux-4"

2016-04-10 16:45:38.451 [info] <0.3517.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env dump_disc_copies_at_startup: true

2016-04-10 16:45:38.452 [info] <0.3517.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env dump_log_load_regulation: false

2016-04-10 16:45:38.452 [info] <0.3517.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env dump_log_time_threshold: 180000

2016-04-10 16:45:38.452 [info] <0.3517.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env dump_log_update_in_place: true

2016-04-10 16:45:38.452 [info] <0.3517.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env dump_log_write_threshold: 1000

2016-04-10 16:45:38.452 [info] <0.3517.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env event_module: mnesia2_event

2016-04-10 16:45:38.452 [info] <0.3517.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env extra_db_nodes: []

2016-04-10 16:45:38.452 [info] <0.3517.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env ignore_fallback_at_startup: false

2016-04-10 16:45:38.452 [info] <0.3517.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env fallback_error_function: {mnesia2,lkill}

2016-04-10 16:45:38.452 [info] <0.3517.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env max_wait_for_decision: infinity

2016-04-10 16:45:38.452 [info] <0.3517.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env schema_location: opt_disc

2016-04-10 16:45:38.453 [info] <0.3517.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env core_dir: false

2016-04-10 16:45:38.453 [info] <0.3517.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env pid_sort_order: false

2016-04-10 16:45:38.453 [info] <0.3517.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env no_table_loaders: 2

2016-04-10 16:45:38.453 [info] <0.3517.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env dc_dump_limit: 4

2016-04-10 16:45:38.453 [info] <0.3517.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env send_compressed: 0

2016-04-10 16:45:38.453 [info] <0.3517.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env send_max_packets: 20

2016-04-10 16:45:38.453 [info] <0.3517.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env send_max_transfer_size: 7500

2016-04-10 16:45:38.453 [info] <0.3517.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Mnesia2 debug level set to debug
2016-04-10 16:45:38.453 [info] <0.3517.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): mnesia2_subscr starting: <0.3520.0>

2016-04-10 16:45:38.453 [info] <0.3517.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): mnesia2_locker starting: <0.3521.0>

2016-04-10 16:45:38.454 [info] <0.3517.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): mnesia2_recover starting: <0.3522.0>

2016-04-10 16:45:38.454 [info] <0.3517.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): mnesia2_tm starting: <0.3523.0>

2016-04-10 16:45:38.454 [info] <0.3517.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Schema initiated from: default

2016-04-10 16:45:38.454 [info] <0.3523.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.3523.0>
2016-04-10 16:45:38.454 [info] <0.3517.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): debug fun {mnesia2_tm,init} in ets mnesia2_debug does not exist, ignoring
2016-04-10 16:45:38.454 [info] <0.3517.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): mnesia2_controller starting: <0.3526.0>

2016-04-10 16:45:38.455 [info] <0.3517.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): mnesia2_late_loader starting: <0.3527.0>

2016-04-10 16:45:38.455 [info] <0.3517.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Intend to load tables: []

2016-04-10 16:45:38.455 [info] <0.3517.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): debug fun {mnesia2_controller,late_disc_load} in ets mnesia2_debug does not exist, ignoring
2016-04-10 16:45:38.456 [info] <0.3517.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): mnesia2_tm_1 starting: <0.3529.0>

2016-04-10 16:45:40.481 [warning] <0.6.0> lager_error_logger_h dropped 45 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:45:40.481 [info] <0.3598.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): mnesia2_monitor starting: <0.3600.0>

2016-04-10 16:45:40.481 [info] <0.3598.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Version: "1.0.0"

2016-04-10 16:45:40.482 [info] <0.3598.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env access_module: mnesia2

2016-04-10 16:45:40.482 [info] <0.3598.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env auto_repair: true

2016-04-10 16:45:40.482 [info] <0.3598.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env backup_module: mnesia2_backup

2016-04-10 16:45:40.482 [info] <0.3598.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env debug: trace

2016-04-10 16:45:40.482 [info] <0.3598.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test1018@testing-worker-linux-docker-236c71da-3354-linux-4.2016-04-10_16.44.52/Mnesia2.test1018@testing-worker-linux-docker-236c71da-3354-linux-4"

2016-04-10 16:45:40.482 [info] <0.3598.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env dump_disc_copies_at_startup: true

2016-04-10 16:45:40.483 [info] <0.3598.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env dump_log_load_regulation: false

2016-04-10 16:45:40.483 [info] <0.3598.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env dump_log_time_threshold: 180000

2016-04-10 16:45:40.483 [info] <0.3598.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env dump_log_update_in_place: true

2016-04-10 16:45:40.483 [info] <0.3598.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env dump_log_write_threshold: 1000

2016-04-10 16:45:40.483 [info] <0.3598.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env event_module: mnesia2_event

2016-04-10 16:45:40.483 [info] <0.3598.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env extra_db_nodes: []

2016-04-10 16:45:40.484 [info] <0.3598.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env ignore_fallback_at_startup: false

2016-04-10 16:45:40.484 [info] <0.3598.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env fallback_error_function: {mnesia2,lkill}

2016-04-10 16:45:40.484 [info] <0.3598.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env max_wait_for_decision: infinity

2016-04-10 16:45:40.484 [info] <0.3598.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env schema_location: opt_disc

2016-04-10 16:45:40.484 [info] <0.3604.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.3604.0>
2016-04-10 16:45:40.485 [info] <0.3598.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env core_dir: false

2016-04-10 16:45:40.485 [info] <0.3598.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env pid_sort_order: false

2016-04-10 16:45:40.485 [info] <0.3598.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env no_table_loaders: 2

2016-04-10 16:45:40.485 [info] <0.3598.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env dc_dump_limit: 4

2016-04-10 16:45:40.485 [info] <0.3598.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env send_compressed: 0

2016-04-10 16:45:40.486 [info] <0.3598.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env send_max_packets: 20

2016-04-10 16:45:40.486 [info] <0.3598.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env send_max_transfer_size: 7500

2016-04-10 16:45:40.486 [info] <0.3598.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Mnesia2 debug level set to trace
2016-04-10 16:45:40.486 [info] <0.3598.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): mnesia2_subscr starting: <0.3601.0>

2016-04-10 16:45:40.486 [info] <0.3598.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): mnesia2_locker starting: <0.3602.0>

2016-04-10 16:45:40.487 [info] <0.3598.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): mnesia2_recover starting: <0.3603.0>

2016-04-10 16:45:40.487 [info] <0.3598.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): mnesia2_tm starting: <0.3604.0>

2016-04-10 16:45:42.512 [warning] <0.6.0> lager_error_logger_h dropped 11 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:45:42.512 [info] <0.3649.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): mnesia2_monitor starting: <0.3651.0>

2016-04-10 16:45:42.513 [info] <0.3649.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Version: "1.0.0"

2016-04-10 16:45:42.513 [info] <0.3649.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env access_module: mnesia2

2016-04-10 16:45:42.513 [info] <0.3649.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env auto_repair: true

2016-04-10 16:45:42.513 [info] <0.3649.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env backup_module: mnesia2_backup

2016-04-10 16:45:42.513 [info] <0.3649.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env debug: debug

2016-04-10 16:45:42.513 [info] <0.3649.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test1018@testing-worker-linux-docker-236c71da-3354-linux-4.2016-04-10_16.44.52/Mnesia2.test1018@testing-worker-linux-docker-236c71da-3354-linux-4"

2016-04-10 16:45:42.513 [info] <0.3649.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env dump_disc_copies_at_startup: true

2016-04-10 16:45:42.514 [info] <0.3649.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env dump_log_load_regulation: false

2016-04-10 16:45:42.514 [info] <0.3649.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env dump_log_time_threshold: 180000

2016-04-10 16:45:42.514 [info] <0.3655.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.3655.0>
2016-04-10 16:45:42.514 [info] <0.3649.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env dump_log_update_in_place: true

2016-04-10 16:45:42.515 [info] <0.3649.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env dump_log_write_threshold: 1000

2016-04-10 16:45:42.515 [info] <0.3649.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env event_module: mnesia2_event

2016-04-10 16:45:42.515 [info] <0.3649.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env extra_db_nodes: []

2016-04-10 16:45:42.516 [info] <0.3649.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env ignore_fallback_at_startup: false

2016-04-10 16:45:42.516 [info] <0.3649.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Env fallback_error_function: {mnesia2,lkill}

2016-04-10 16:45:44.540 [warning] <0.6.0> lager_error_logger_h dropped 37 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:45:44.541 [info] <0.3735.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.3735.0>
2016-04-10 16:45:44.543 [info] <0.7.0> Application mnesia2 started on node 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:45:44.544 [error] <0.3726.0> CRASH REPORT Process <0.3726.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:45:44.544 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:45:46.624 [info] <0.3799.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.3799.0>
2016-04-10 16:45:46.626 [info] <0.7.0> Application mnesia2 started on node 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:45:46.628 [error] <0.3790.0> CRASH REPORT Process <0.3790.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:45:46.628 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:45:47.726 [info] <0.3870.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.3870.0>
2016-04-10 16:45:47.728 [info] <0.7.0> Application mnesia2 started on node 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:45:47.731 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:45:47.738 [info] <0.3931.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.3931.0>
2016-04-10 16:45:49.993 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:45:49.994 [error] <0.3925.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 16:45:54.963 [error] <0.3925.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 16:45:59.429 [error] <0.3925.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 16:46:02.783 [error] <0.3922.0> CRASH REPORT Process <0.3922.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:46:02.783 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:46:04.910 [info] <0.4552.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.4552.0>
2016-04-10 16:46:04.912 [info] <0.7.0> Application mnesia2 started on node 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:46:10.919 [error] <0.4543.0> CRASH REPORT Process <0.4543.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:46:10.919 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:46:13.010 [info] <0.4652.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.4652.0>
2016-04-10 16:46:13.012 [info] <0.7.0> Application mnesia2 started on node 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:46:14.029 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:46:16.149 [info] <0.4768.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.4768.0>
2016-04-10 16:46:16.151 [info] <0.7.0> Application mnesia2 started on node 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:46:16.156 [error] <0.4759.0> CRASH REPORT Process <0.4759.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:46:16.156 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:46:18.196 [info] <0.4835.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.4835.0>
2016-04-10 16:46:18.198 [info] <0.7.0> Application mnesia2 started on node 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:46:18.221 [error] <0.4826.0> CRASH REPORT Process <0.4826.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:46:18.221 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:46:20.356 [warning] <0.6.0> lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:46:20.367 [info] <0.1787.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.1787.0>
2016-04-10 16:46:20.370 [info] <0.7.0> Application mnesia2 started on node 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:46:20.359 [info] <0.4927.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.4927.0>
2016-04-10 16:46:20.361 [info] <0.7.0> Application mnesia2 started on node 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:46:21.372 [error] <0.1834.0> gen_server <0.1834.0> terminated with reason: killed
2016-04-10 16:46:21.372 [error] <0.1834.0> CRASH REPORT Process <0.1834.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:46:21.373 [error] <0.1777.0> CRASH REPORT Process <0.1777.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:46:21.373 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:46:23.422 [info] <0.1854.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.1854.0>
2016-04-10 16:46:23.426 [info] <0.7.0> Application mnesia2 started on node 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:46:24.427 [error] <0.4922.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.4939.0> exit with reason killed in context child_terminated
2016-04-10 16:46:24.427 [error] <0.4922.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.4939.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 16:46:24.429 [error] <0.4990.0> gen_server <0.4990.0> terminated with reason: killed
2016-04-10 16:46:24.429 [error] <0.4990.0> CRASH REPORT Process <0.4990.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:46:24.429 [error] <0.4918.0> CRASH REPORT Process <0.4918.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:46:24.429 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:46:25.482 [error] <0.1845.0> CRASH REPORT Process <0.1845.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:46:25.482 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:46:26.588 [info] <0.5033.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.5033.0>
2016-04-10 16:46:26.591 [info] <0.7.0> Application mnesia2 started on node 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:46:26.611 [error] <0.5024.0> CRASH REPORT Process <0.5024.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:46:26.605 [info] <0.1935.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.1935.0>
2016-04-10 16:46:26.609 [info] <0.7.0> Application mnesia2 started on node 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:46:26.612 [error] <0.1926.0> CRASH REPORT Process <0.1926.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:46:26.611 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:46:26.662 [info] <0.5108.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.5108.0>
2016-04-10 16:46:26.612 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:46:30.822 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:46:30.895 [info] <0.5232.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.5232.0>
2016-04-10 16:46:30.900 [info] <0.7.0> Application mnesia2 started on node 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:46:30.886 [info] <0.2005.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.2005.0>
2016-04-10 16:46:30.888 [info] <0.7.0> Application mnesia2 started on node 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:46:39.990 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:46:39.992 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:46:41.170 [info] <0.2128.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.2128.0>
2016-04-10 16:46:41.174 [info] <0.7.0> Application mnesia2 started on node 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:46:41.212 [error] <0.2179.0> gen_server <0.2179.0> terminated with reason: killed
2016-04-10 16:46:41.212 [error] <0.2179.0> CRASH REPORT Process <0.2179.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:46:41.213 [error] <0.2119.0> CRASH REPORT Process <0.2119.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:46:41.158 [info] <0.5363.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.5363.0>
2016-04-10 16:46:41.161 [info] <0.7.0> Application mnesia2 started on node 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:46:41.235 [error] <0.5354.0> CRASH REPORT Process <0.5354.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:46:41.236 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:46:41.281 [info] <0.5451.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.5451.0>
2016-04-10 16:46:41.213 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:46:41.481 [info] <0.2215.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.2215.0>
2016-04-10 16:46:43.099 [warning] <0.6.0> lager_error_logger_h dropped 15 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:46:43.099 [error] <0.2210.0> Supervisor mnesia2_kernel_sup had child mnesia2_controller started with mnesia2_controller:start() at <0.2236.0> exit with reason killed in context child_terminated
2016-04-10 16:46:43.100 [error] <0.2210.0> Supervisor mnesia2_kernel_sup had child mnesia2_controller started with mnesia2_controller:start() at <0.2236.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 16:46:43.100 [error] <0.2210.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.2234.0> exit with reason killed in context shutdown_error
2016-04-10 16:46:43.101 [error] <0.2208.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.2210.0> exit with reason killed in context child_terminated
2016-04-10 16:46:43.101 [error] <0.2208.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.2210.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 16:46:43.101 [error] <0.2211.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-10 16:46:43.101 [error] <0.2211.0> CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:46:43.101 [error] <0.2214.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-10 16:46:43.101 [error] <0.2214.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:46:43.102 [info] <0.7.0> Application mnesia2 exited with reason: shutdown
2016-04-10 16:46:44.172 [info] <0.2319.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.2319.0>
2016-04-10 16:46:44.191 [info] <0.7.0> Application mnesia2 started on node 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:46:44.204 [error] <0.2331.0> gen_server <0.2331.0> terminated with reason: killed
2016-04-10 16:46:44.156 [warning] <0.6.0> lager_error_logger_h dropped 37 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:46:44.163 [info] <0.5574.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.5574.0>
2016-04-10 16:46:44.166 [info] <0.7.0> Application mnesia2 started on node 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:46:44.213 [error] <0.5638.0> gen_server <0.5638.0> terminated with reason: killed
2016-04-10 16:46:44.205 [error] <0.2331.0> CRASH REPORT Process <0.2331.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:46:44.213 [error] <0.5638.0> CRASH REPORT Process <0.5638.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:46:44.205 [error] <0.2310.0> CRASH REPORT Process <0.2310.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:46:44.214 [error] <0.5565.0> CRASH REPORT Process <0.5565.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:46:44.215 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:46:44.205 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:46:46.329 [info] <0.2394.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.2394.0>
2016-04-10 16:46:46.335 [info] <0.7.0> Application mnesia2 started on node 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:46:46.344 [error] <0.2389.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.2396.0> exit with reason killed in context child_terminated
2016-04-10 16:46:46.323 [info] <0.5685.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.5685.0>
2016-04-10 16:46:46.325 [info] <0.7.0> Application mnesia2 started on node 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:46:46.346 [error] <0.5749.0> gen_server <0.5749.0> terminated with reason: killed
2016-04-10 16:46:46.345 [error] <0.2389.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.2396.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 16:46:46.346 [error] <0.5749.0> CRASH REPORT Process <0.5749.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:46:46.345 [error] <0.2406.0> gen_server <0.2406.0> terminated with reason: killed
2016-04-10 16:46:46.348 [error] <0.5676.0> CRASH REPORT Process <0.5676.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:46:46.345 [error] <0.2406.0> CRASH REPORT Process <0.2406.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:46:46.345 [error] <0.2385.0> CRASH REPORT Process <0.2385.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:46:46.349 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:46:46.345 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:46:48.389 [info] <0.5765.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.5765.0>
2016-04-10 16:46:48.399 [info] <0.7.0> Application mnesia2 started on node 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:46:48.428 [error] <0.5760.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.5782.0> exit with reason killed in context child_terminated
2016-04-10 16:46:48.428 [error] <0.5760.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.5782.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 16:46:48.428 [error] <0.5826.0> gen_server <0.5826.0> terminated with reason: killed
2016-04-10 16:46:48.429 [error] <0.5826.0> CRASH REPORT Process <0.5826.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:46:48.429 [error] <0.5756.0> CRASH REPORT Process <0.5756.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:46:48.375 [info] <0.2453.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.2453.0>
2016-04-10 16:46:48.376 [info] <0.7.0> Application mnesia2 started on node 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:46:48.429 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:46:49.871 [error] <0.2444.0> CRASH REPORT Process <0.2444.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:46:49.871 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:46:50.985 [info] <0.2540.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.2540.0>
2016-04-10 16:46:50.991 [info] <0.7.0> Application mnesia2 started on node 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:46:51.382 [error] <0.2553.0> gen_server <0.2553.0> terminated with reason: killed
2016-04-10 16:46:50.979 [info] <0.5890.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.5890.0>
2016-04-10 16:46:50.982 [info] <0.7.0> Application mnesia2 started on node 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:46:51.382 [error] <0.5943.0> gen_server <0.5943.0> terminated with reason: killed
2016-04-10 16:46:51.382 [error] <0.5943.0> CRASH REPORT Process <0.5943.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:46:51.382 [error] <0.2553.0> CRASH REPORT Process <0.2553.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:46:51.382 [error] <0.5935.0> gen_server <0.5935.0> terminated with reason: killed
2016-04-10 16:46:51.382 [error] <0.2531.0> CRASH REPORT Process <0.2531.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:46:51.382 [error] <0.5935.0> CRASH REPORT Process <0.5935.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:46:51.383 [error] <0.5881.0> CRASH REPORT Process <0.5881.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:46:51.383 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:46:51.382 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:46:51.267 [info] <0.7.0> Application lager started on node 'd1225785o1225987n1225982@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:46:51.267 [info] <0.7.0> Application poolgirl started on node 'd1225785o1225987n1225982@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:46:51.307 [info] <0.100.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225785o1225987n1225982@testing-worker-linux-docker-236c71da-3354-linux-4', <0.100.0>
2016-04-10 16:46:51.326 [info] <0.7.0> Application mnesia2 started on node 'd1225785o1225987n1225982@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:46:53.499 [info] <0.5985.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.5985.0>
2016-04-10 16:46:53.502 [info] <0.7.0> Application mnesia2 started on node 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:46:53.515 [error] <0.5976.0> CRASH REPORT Process <0.5976.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:46:53.506 [info] <0.2621.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.2621.0>
2016-04-10 16:46:53.512 [info] <0.7.0> Application mnesia2 started on node 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:46:53.516 [error] <0.2645.0> gen_server <0.2645.0> terminated with reason: killed
2016-04-10 16:46:53.516 [error] <0.2645.0> CRASH REPORT Process <0.2645.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:46:53.516 [error] <0.2612.0> CRASH REPORT Process <0.2612.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:46:53.515 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:46:53.516 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:46:55.636 [info] <0.2691.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.2691.0>
2016-04-10 16:46:55.640 [info] <0.7.0> Application mnesia2 started on node 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:46:55.652 [error] <0.2703.0> gen_server <0.2703.0> terminated with reason: killed
2016-04-10 16:46:55.623 [info] <0.6079.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.6079.0>
2016-04-10 16:46:55.625 [info] <0.7.0> Application mnesia2 started on node 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:46:55.654 [error] <0.6124.0> gen_server <0.6124.0> terminated with reason: killed
2016-04-10 16:46:55.654 [error] <0.6124.0> CRASH REPORT Process <0.6124.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:46:55.653 [error] <0.2703.0> CRASH REPORT Process <0.2703.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:46:55.655 [error] <0.6070.0> CRASH REPORT Process <0.6070.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:46:55.653 [error] <0.2682.0> CRASH REPORT Process <0.2682.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:46:55.655 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:46:55.653 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:46:57.780 [info] <0.2766.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.2766.0>
2016-04-10 16:46:57.783 [info] <0.7.0> Application mnesia2 started on node 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:46:58.105 [error] <0.2821.0> gen_server <0.2821.0> terminated with reason: killed
2016-04-10 16:46:58.105 [error] <0.2821.0> CRASH REPORT Process <0.2821.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:46:58.105 [error] <0.2757.0> CRASH REPORT Process <0.2757.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:46:57.777 [info] <0.6165.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.6165.0>
2016-04-10 16:46:58.081 [info] <0.7.0> Application mnesia2 started on node 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:46:58.105 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:46:59.133 [error] <0.6156.0> CRASH REPORT Process <0.6156.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:46:59.133 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:47:01.179 [info] <0.2837.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.2837.0>
2016-04-10 16:47:01.180 [info] <0.7.0> Application mnesia2 started on node 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:47:06.211 [info] <0.6244.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.6244.0>
2016-04-10 16:47:06.220 [info] <0.7.0> Application mnesia2 started on node 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:47:06.228 [error] <0.6301.0> gen_server <0.6301.0> terminated with reason: killed
2016-04-10 16:47:06.227 [error] <0.2832.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.2850.0> exit with reason killed in context child_terminated
2016-04-10 16:47:06.228 [error] <0.6301.0> CRASH REPORT Process <0.6301.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:06.227 [error] <0.2832.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.2850.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 16:47:06.230 [error] <0.6235.0> CRASH REPORT Process <0.6235.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:47:06.227 [error] <0.2904.0> gen_server <0.2904.0> terminated with reason: killed
2016-04-10 16:47:06.227 [error] <0.2904.0> CRASH REPORT Process <0.2904.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:06.227 [error] <0.2828.0> CRASH REPORT Process <0.2828.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:47:06.230 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:47:06.227 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:47:07.400 [info] <0.2936.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.2936.0>
2016-04-10 16:47:07.410 [info] <0.7.0> Application mnesia2 started on node 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:47:07.493 [error] <0.2997.0> gen_server <0.2997.0> terminated with reason: killed
2016-04-10 16:47:07.493 [error] <0.2997.0> CRASH REPORT Process <0.2997.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:07.493 [error] <0.2988.0> gen_server <0.2988.0> terminated with reason: killed
2016-04-10 16:47:07.493 [error] <0.2988.0> CRASH REPORT Process <0.2988.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:07.493 [error] <0.2927.0> CRASH REPORT Process <0.2927.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:47:07.378 [info] <0.6354.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.6354.0>
2016-04-10 16:47:07.380 [info] <0.7.0> Application mnesia2 started on node 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:47:07.556 [error] <0.6349.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.6366.0> exit with reason killed in context child_terminated
2016-04-10 16:47:07.558 [error] <0.6349.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.6366.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 16:47:07.558 [error] <0.6457.0> gen_server <0.6457.0> terminated with reason: killed
2016-04-10 16:47:07.558 [error] <0.6457.0> CRASH REPORT Process <0.6457.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:07.558 [error] <0.6441.0> gen_server <0.6441.0> terminated with reason: killed
2016-04-10 16:47:07.558 [error] <0.6441.0> CRASH REPORT Process <0.6441.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:07.558 [error] <0.6418.0> gen_server <0.6418.0> terminated with reason: killed
2016-04-10 16:47:07.558 [error] <0.6418.0> CRASH REPORT Process <0.6418.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:07.559 [error] <0.6345.0> CRASH REPORT Process <0.6345.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:47:07.350 [warning] <0.6.0> lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:47:07.431 [info] <0.190.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225785o1225987n1225982@testing-worker-linux-docker-236c71da-3354-linux-4', <0.190.0>
2016-04-10 16:47:07.435 [info] <0.7.0> Application mnesia2 started on node 'd1225785o1225987n1225982@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:47:07.584 [error] <0.273.0> gen_server <0.273.0> terminated with reason: killed
2016-04-10 16:47:07.584 [error] <0.273.0> CRASH REPORT Process <0.273.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:07.680 [info] <0.294.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225785o1225987n1225982@testing-worker-linux-docker-236c71da-3354-linux-4', <0.294.0>
2016-04-10 16:47:07.559 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:47:07.663 [info] <0.6476.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.6476.0>
2016-04-10 16:47:07.493 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:47:07.519 [info] <0.3027.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.3027.0>
2016-04-10 16:47:07.638 [info] <0.3122.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.3122.0>
2016-04-10 16:47:08.821 [warning] <0.6.0> lager_error_logger_h dropped 20 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:47:08.821 [error] <0.356.0> gen_server <0.356.0> terminated with reason: killed
2016-04-10 16:47:08.821 [error] <0.356.0> CRASH REPORT Process <0.356.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:08.821 [error] <0.368.0> gen_server <0.368.0> terminated with reason: killed
2016-04-10 16:47:08.821 [error] <0.368.0> CRASH REPORT Process <0.368.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:08.821 [error] <0.285.0> CRASH REPORT Process <0.285.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:47:08.821 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:47:08.847 [info] <0.391.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225785o1225987n1225982@testing-worker-linux-docker-236c71da-3354-linux-4', <0.391.0>
2016-04-10 16:47:08.848 [info] <0.7.0> Application mnesia2 started on node 'd1225785o1225987n1225982@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:47:10.894 [warning] <0.6.0> lager_error_logger_h dropped 10 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:47:10.894 [error] <0.6575.0> gen_server <0.6575.0> terminated with reason: killed
2016-04-10 16:47:10.894 [error] <0.6575.0> CRASH REPORT Process <0.6575.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:10.894 [error] <0.6547.0> gen_server <0.6547.0> terminated with reason: killed
2016-04-10 16:47:10.895 [error] <0.6547.0> CRASH REPORT Process <0.6547.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:10.895 [error] <0.6467.0> CRASH REPORT Process <0.6467.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:47:10.916 [warning] <0.6.0> lager_error_logger_h dropped 30 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:47:10.916 [error] <0.3113.0> CRASH REPORT Process <0.3113.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:47:10.940 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:47:10.992 [info] <0.497.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225785o1225987n1225982@testing-worker-linux-docker-236c71da-3354-linux-4', <0.497.0>
2016-04-10 16:47:10.993 [info] <0.7.0> Application mnesia2 started on node 'd1225785o1225987n1225982@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:47:11.849 [error] <0.571.0> gen_server <0.571.0> terminated with reason: killed
2016-04-10 16:47:11.851 [error] <0.571.0> CRASH REPORT Process <0.571.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:11.851 [error] <0.564.0> gen_server <0.564.0> terminated with reason: killed
2016-04-10 16:47:11.851 [error] <0.564.0> CRASH REPORT Process <0.564.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:11.851 [error] <0.488.0> CRASH REPORT Process <0.488.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:47:10.896 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:47:11.017 [info] <0.6594.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.6594.0>
2016-04-10 16:47:11.324 [info] <0.7.0> Application mnesia2 started on node 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:47:10.916 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:47:11.020 [info] <0.3235.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.3235.0>
2016-04-10 16:47:11.031 [info] <0.7.0> Application mnesia2 started on node 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:47:11.851 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:47:11.875 [info] <0.596.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225785o1225987n1225982@testing-worker-linux-docker-236c71da-3354-linux-4', <0.596.0>
2016-04-10 16:47:11.876 [info] <0.7.0> Application mnesia2 started on node 'd1225785o1225987n1225982@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:47:11.947 [error] <0.6683.0> gen_server <0.6683.0> terminated with reason: killed
2016-04-10 16:47:11.947 [error] <0.6683.0> CRASH REPORT Process <0.6683.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:11.948 [error] <0.6663.0> gen_server <0.6663.0> terminated with reason: killed
2016-04-10 16:47:11.948 [error] <0.6663.0> CRASH REPORT Process <0.6663.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:11.948 [error] <0.6689.0> gen_server <0.6689.0> terminated with reason: killed
2016-04-10 16:47:11.948 [error] <0.6689.0> CRASH REPORT Process <0.6689.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:11.950 [error] <0.6585.0> CRASH REPORT Process <0.6585.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:47:11.968 [error] <0.3322.0> gen_server <0.3322.0> terminated with reason: killed
2016-04-10 16:47:11.968 [error] <0.3322.0> CRASH REPORT Process <0.3322.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:11.969 [error] <0.3226.0> CRASH REPORT Process <0.3226.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:47:11.969 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:47:12.051 [info] <0.3343.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.3343.0>
2016-04-10 16:47:12.062 [info] <0.7.0> Application mnesia2 started on node 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:47:12.875 [error] <0.3412.0> gen_server <0.3412.0> terminated with reason: killed
2016-04-10 16:47:12.875 [error] <0.3412.0> CRASH REPORT Process <0.3412.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:12.875 [error] <0.3395.0> gen_server <0.3395.0> terminated with reason: killed
2016-04-10 16:47:12.875 [error] <0.3395.0> CRASH REPORT Process <0.3395.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:12.876 [error] <0.3334.0> CRASH REPORT Process <0.3334.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:47:11.950 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:47:12.029 [info] <0.6707.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.6707.0>
2016-04-10 16:47:12.347 [info] <0.7.0> Application mnesia2 started on node 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:47:12.876 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:47:12.970 [info] <0.3438.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.3438.0>
2016-04-10 16:47:11.993 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:47:12.005 [info] <0.697.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225785o1225987n1225982@testing-worker-linux-docker-236c71da-3354-linux-4', <0.697.0>
2016-04-10 16:47:12.007 [info] <0.7.0> Application mnesia2 started on node 'd1225785o1225987n1225982@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:47:13.000 [error] <0.3452.0> gen_server <0.3452.0> terminated with reason: killed
2016-04-10 16:47:13.000 [error] <0.3452.0> CRASH REPORT Process <0.3452.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:13.000 [error] <0.3494.0> gen_server <0.3494.0> terminated with reason: killed
2016-04-10 16:47:13.000 [error] <0.3494.0> CRASH REPORT Process <0.3494.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:13.000 [error] <0.3486.0> gen_server <0.3486.0> terminated with reason: killed
2016-04-10 16:47:13.001 [error] <0.3486.0> CRASH REPORT Process <0.3486.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:13.001 [error] <0.3429.0> CRASH REPORT Process <0.3429.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:47:13.001 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:47:14.115 [error] <0.6820.0> gen_server <0.6820.0> terminated with reason: killed
2016-04-10 16:47:14.026 [info] <0.3516.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.3516.0>
2016-04-10 16:47:14.043 [info] <0.7.0> Application mnesia2 started on node 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:47:14.116 [error] <0.3564.0> gen_server <0.3564.0> terminated with reason: killed
2016-04-10 16:47:14.118 [error] <0.823.0> gen_server <0.823.0> terminated with reason: killed
2016-04-10 16:47:14.115 [error] <0.6820.0> CRASH REPORT Process <0.6820.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:14.118 [error] <0.823.0> CRASH REPORT Process <0.823.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:14.117 [error] <0.3564.0> CRASH REPORT Process <0.3564.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:14.115 [error] <0.6771.0> gen_server <0.6771.0> terminated with reason: killed
2016-04-10 16:47:14.118 [error] <0.812.0> gen_server <0.812.0> terminated with reason: killed
2016-04-10 16:47:14.119 [error] <0.3507.0> CRASH REPORT Process <0.3507.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:47:14.115 [error] <0.6771.0> CRASH REPORT Process <0.6771.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:14.118 [error] <0.812.0> CRASH REPORT Process <0.812.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:14.115 [error] <0.6698.0> CRASH REPORT Process <0.6698.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:47:14.118 [error] <0.771.0> gen_server <0.771.0> terminated with reason: killed
2016-04-10 16:47:14.118 [error] <0.771.0> CRASH REPORT Process <0.771.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:14.118 [error] <0.688.0> CRASH REPORT Process <0.688.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:47:14.119 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:47:14.213 [info] <0.3594.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.3594.0>
2016-04-10 16:47:14.230 [info] <0.7.0> Application mnesia2 started on node 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:47:14.305 [info] <0.3689.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.3689.0>
2016-04-10 16:47:14.417 [info] <0.3779.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.3779.0>
2016-04-10 16:47:14.480 [info] <0.3879.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.3879.0>
2016-04-10 16:47:15.034 [warning] <0.6.0> lager_error_logger_h dropped 5 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:47:15.034 [error] <0.3870.0> CRASH REPORT Process <0.3870.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:47:14.115 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:47:14.206 [info] <0.6853.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.6853.0>
2016-04-10 16:47:14.208 [info] <0.7.0> Application mnesia2 started on node 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:47:14.463 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:47:14.997 [info] <0.6967.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.6967.0>
2016-04-10 16:47:15.018 [info] <0.7.0> Application mnesia2 started on node 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:47:15.032 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:47:15.077 [info] <0.7050.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.7050.0>
2016-04-10 16:47:15.079 [info] <0.7.0> Application mnesia2 started on node 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:47:14.118 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:47:15.794 [error] <0.7041.0> CRASH REPORT Process <0.7041.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:47:15.034 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:47:15.583 [info] <0.3961.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.3961.0>
2016-04-10 16:47:15.715 [info] <0.7.0> Application mnesia2 started on node 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:47:15.795 [error] <0.4000.0> gen_server <0.4000.0> terminated with reason: killed
2016-04-10 16:47:15.795 [error] <0.4000.0> CRASH REPORT Process <0.4000.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:15.796 [error] <0.3952.0> CRASH REPORT Process <0.3952.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:47:15.796 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:47:15.879 [info] <0.4053.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.4053.0>
2016-04-10 16:47:15.794 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:47:15.871 [info] <0.7151.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.7151.0>
2016-04-10 16:47:16.178 [info] <0.7.0> Application mnesia2 started on node 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:47:16.255 [error] <0.7199.0> gen_server <0.7199.0> terminated with reason: killed
2016-04-10 16:47:16.253 [warning] <0.6.0> lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:47:16.253 [error] <0.4111.0> gen_server <0.4111.0> terminated with reason: killed
2016-04-10 16:47:15.873 [info] <0.849.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225785o1225987n1225982@testing-worker-linux-docker-236c71da-3354-linux-4', <0.849.0>
2016-04-10 16:47:15.887 [info] <0.7.0> Application mnesia2 started on node 'd1225785o1225987n1225982@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:47:16.256 [error] <0.913.0> gen_server <0.913.0> terminated with reason: killed
2016-04-10 16:47:16.255 [error] <0.7199.0> CRASH REPORT Process <0.7199.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:16.254 [error] <0.4111.0> CRASH REPORT Process <0.4111.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:16.255 [error] <0.7214.0> gen_server <0.7214.0> terminated with reason: killed
2016-04-10 16:47:16.256 [error] <0.913.0> CRASH REPORT Process <0.913.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:16.255 [error] <0.7214.0> CRASH REPORT Process <0.7214.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:16.254 [error] <0.4106.0> gen_server <0.4106.0> terminated with reason: killed
2016-04-10 16:47:16.256 [error] <0.906.0> gen_server <0.906.0> terminated with reason: killed
2016-04-10 16:47:16.255 [error] <0.7142.0> CRASH REPORT Process <0.7142.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:47:16.256 [error] <0.906.0> CRASH REPORT Process <0.906.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:16.254 [error] <0.4106.0> CRASH REPORT Process <0.4106.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:16.259 [error] <0.840.0> CRASH REPORT Process <0.840.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:47:16.254 [error] <0.4044.0> CRASH REPORT Process <0.4044.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:47:16.259 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:47:16.285 [info] <0.954.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225785o1225987n1225982@testing-worker-linux-docker-236c71da-3354-linux-4', <0.954.0>
2016-04-10 16:47:16.286 [info] <0.7.0> Application mnesia2 started on node 'd1225785o1225987n1225982@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:47:16.332 [error] <0.1013.0> gen_server <0.1013.0> terminated with reason: killed
2016-04-10 16:47:16.332 [error] <0.1013.0> CRASH REPORT Process <0.1013.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:16.332 [error] <0.1003.0> gen_server <0.1003.0> terminated with reason: killed
2016-04-10 16:47:16.333 [error] <0.1003.0> CRASH REPORT Process <0.1003.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:16.333 [error] <0.945.0> CRASH REPORT Process <0.945.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:47:16.255 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:47:16.304 [info] <0.7264.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.7264.0>
2016-04-10 16:47:16.382 [info] <0.7356.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.7356.0>
2016-04-10 16:47:16.333 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:47:16.355 [info] <0.1033.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225785o1225987n1225982@testing-worker-linux-docker-236c71da-3354-linux-4', <0.1033.0>
2016-04-10 16:47:16.254 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:47:16.287 [info] <0.4143.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.4143.0>
2016-04-10 16:47:16.288 [info] <0.7.0> Application mnesia2 started on node 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:47:16.356 [info] <0.4221.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.4221.0>
2016-04-10 16:47:26.389 [warning] <0.6.0> lager_error_logger_h dropped 5 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:47:26.389 [error] <0.7349.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at undefined exit with reason killed in context start_error
2016-04-10 16:47:26.389 [error] <0.7352.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-10 16:47:26.389 [error] <0.7355.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-10 16:47:26.389 [error] <0.7355.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:26.389 [error] <0.7375.0> gen_server mnesia2_snmp_sup terminated with reason: killed
2016-04-10 16:47:26.390 [error] <0.7375.0> CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:26.390 [error] <0.7353.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-10 16:47:26.390 [error] <0.7353.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:26.390 [error] <0.7347.0> CRASH REPORT Process <0.7347.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}} in application_master:init/4 line 133
2016-04-10 16:47:26.390 [error] <0.7352.0> CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:26.475 [warning] <0.6.0> lager_error_logger_h dropped 4 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:47:26.476 [error] <0.4265.0> gen_server <0.4265.0> terminated with reason: killed
2016-04-10 16:47:26.476 [warning] <0.6.0> lager_error_logger_h dropped 40 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:47:26.476 [error] <0.1082.0> gen_server <0.1082.0> terminated with reason: killed
2016-04-10 16:47:26.476 [error] <0.4265.0> CRASH REPORT Process <0.4265.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:26.476 [error] <0.1082.0> CRASH REPORT Process <0.1082.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:26.476 [error] <0.4212.0> CRASH REPORT Process <0.4212.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:47:26.476 [error] <0.1077.0> gen_server <0.1077.0> terminated with reason: killed
2016-04-10 16:47:26.476 [error] <0.1077.0> CRASH REPORT Process <0.1077.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:26.476 [error] <0.1024.0> CRASH REPORT Process <0.1024.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:47:26.390 [info] <0.7.0> Application mnesia2 exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}}
2016-04-10 16:47:26.476 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:47:26.476 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:47:28.879 [info] <0.7465.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.7465.0>
2016-04-10 16:47:28.881 [info] <0.7.0> Application mnesia2 started on node 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:47:32.847 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:47:33.014 [info] <0.7601.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.7601.0>
2016-04-10 16:47:33.321 [info] <0.7.0> Application mnesia2 started on node 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:47:33.021 [info] <0.4311.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.4311.0>
2016-04-10 16:47:33.347 [info] <0.7.0> Application mnesia2 started on node 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:47:33.024 [info] <0.1130.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225785o1225987n1225982@testing-worker-linux-docker-236c71da-3354-linux-4', <0.1130.0>
2016-04-10 16:47:33.044 [info] <0.7.0> Application mnesia2 started on node 'd1225785o1225987n1225982@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:47:39.445 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:47:39.598 [info] <0.1245.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225785o1225987n1225982@testing-worker-linux-docker-236c71da-3354-linux-4', <0.1245.0>
2016-04-10 16:47:39.903 [info] <0.7.0> Application mnesia2 started on node 'd1225785o1225987n1225982@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:47:39.453 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:47:39.591 [info] <0.7731.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.7731.0>
2016-04-10 16:47:39.600 [info] <0.7.0> Application mnesia2 started on node 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:47:39.464 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:47:39.601 [info] <0.4428.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.4428.0>
2016-04-10 16:47:39.628 [info] <0.7.0> Application mnesia2 started on node 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:47:45.996 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:47:46.160 [info] <0.1362.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225785o1225987n1225982@testing-worker-linux-docker-236c71da-3354-linux-4', <0.1362.0>
2016-04-10 16:47:46.171 [info] <0.7.0> Application mnesia2 started on node 'd1225785o1225987n1225982@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:47:45.995 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:47:46.140 [info] <0.4542.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.4542.0>
2016-04-10 16:47:46.464 [info] <0.7.0> Application mnesia2 started on node 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:47:46.001 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:47:46.129 [info] <0.7860.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.7860.0>
2016-04-10 16:47:46.134 [info] <0.7.0> Application mnesia2 started on node 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:48:06.760 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:48:06.911 [info] <0.8998.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.8998.0>
2016-04-10 16:48:07.216 [info] <0.7.0> Application mnesia2 started on node 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:48:06.782 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:48:06.916 [info] <0.2487.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225785o1225987n1225982@testing-worker-linux-docker-236c71da-3354-linux-4', <0.2487.0>
2016-04-10 16:48:06.929 [info] <0.7.0> Application mnesia2 started on node 'd1225785o1225987n1225982@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:48:06.774 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:48:06.916 [info] <0.5667.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.5667.0>
2016-04-10 16:48:07.221 [info] <0.7.0> Application mnesia2 started on node 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:48:13.736 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:48:13.843 [info] <0.9137.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.9137.0>
2016-04-10 16:48:13.848 [info] <0.7.0> Application mnesia2 started on node 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:48:13.733 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:48:13.842 [info] <0.5794.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.5794.0>
2016-04-10 16:48:14.146 [info] <0.7.0> Application mnesia2 started on node 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:48:13.740 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:48:13.876 [info] <0.2612.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225785o1225987n1225982@testing-worker-linux-docker-236c71da-3354-linux-4', <0.2612.0>
2016-04-10 16:48:13.890 [info] <0.7.0> Application mnesia2 started on node 'd1225785o1225987n1225982@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:48:20.504 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:48:20.616 [info] <0.10617.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.10617.0>
2016-04-10 16:48:20.619 [info] <0.7.0> Application mnesia2 started on node 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:48:20.507 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:48:20.641 [info] <0.4081.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225785o1225987n1225982@testing-worker-linux-docker-236c71da-3354-linux-4', <0.4081.0>
2016-04-10 16:48:20.945 [info] <0.7.0> Application mnesia2 started on node 'd1225785o1225987n1225982@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:48:20.506 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:48:20.642 [info] <0.7269.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.7269.0>
2016-04-10 16:48:20.661 [info] <0.7.0> Application mnesia2 started on node 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:48:27.220 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:48:27.360 [info] <0.5363.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225785o1225987n1225982@testing-worker-linux-docker-236c71da-3354-linux-4', <0.5363.0>
2016-04-10 16:48:27.374 [info] <0.7.0> Application mnesia2 started on node 'd1225785o1225987n1225982@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:48:27.225 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:48:27.343 [info] <0.10977.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.10977.0>
2016-04-10 16:48:27.352 [info] <0.7.0> Application mnesia2 started on node 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:48:27.245 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:48:27.360 [info] <0.9009.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.9009.0>
2016-04-10 16:48:27.368 [info] <0.7.0> Application mnesia2 started on node 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:48:33.532 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:48:33.680 [info] <0.5477.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225785o1225987n1225982@testing-worker-linux-docker-236c71da-3354-linux-4', <0.5477.0>
2016-04-10 16:48:33.706 [info] <0.7.0> Application mnesia2 started on node 'd1225785o1225987n1225982@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:48:33.537 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:48:33.658 [info] <0.11106.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4', <0.11106.0>
2016-04-10 16:48:33.661 [info] <0.7.0> Application mnesia2 started on node 'test1018@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:48:33.536 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:48:33.670 [info] <0.9803.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4', <0.9803.0>
2016-04-10 16:48:33.983 [info] <0.7.0> Application mnesia2 started on node 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4'
2016-04-10 16:48:40.260 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:48:40.241 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:48:40.245 [info] <0.7.0> Application mnesia2 exited with reason: stopped
