2016-04-10 22:49:31.840 [info] <0.7.0> Application lager started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:49:31.840 [info] <0.7.0> Application poolgirl started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:49:31.865 [info] <0.494.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.494.0>
2016-04-10 22:49:31.887 [info] <0.562.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.562.0>
2016-04-10 22:49:32.278 [error] <0.553.0> CRASH REPORT Process <0.553.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:49:32.278 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:49:32.372 [info] <0.672.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.672.0>
2016-04-10 22:49:32.375 [info] <0.7.0> Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:49:32.828 [error] <0.729.0> gen_server <0.729.0> terminated with reason: killed
2016-04-10 22:49:32.828 [error] <0.729.0> CRASH REPORT Process <0.729.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:49:32.828 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:49:32.929 [info] <0.799.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.799.0>
2016-04-10 22:49:33.180 [warning] <0.6.0> lager_error_logger_h dropped 13 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:49:33.180 [error] <0.793.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): ** ERROR ** (ignoring core) ** FATAL ** A fallback is installed and Mnesia2 must be restarted. Forcing shutdown after mnesia2_down from 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'...

2016-04-10 22:49:33.180 [error] <0.794.0> Supervisor mnesia2_kernel_sup had child mnesia2_locker started with mnesia2_locker:start() at <0.797.0> exit with reason killed in context child_terminated
2016-04-10 22:49:33.180 [error] <0.794.0> Supervisor mnesia2_kernel_sup had child mnesia2_locker started with mnesia2_locker:start() at <0.797.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:49:33.182 [error] <0.792.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.794.0> exit with reason shutdown in context child_terminated
2016-04-10 22:49:33.182 [error] <0.792.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.794.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:49:32.590 [info] <0.7.0> Application lager started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:49:32.590 [info] <0.7.0> Application poolgirl started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:49:32.642 [info] <0.99.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.99.0>
2016-04-10 22:49:32.935 [info] <0.216.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.216.0>
2016-04-10 22:49:33.178 [warning] <0.6.0> lager_error_logger_h dropped 6 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:49:33.178 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:49:33.214 [info] <0.368.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.368.0>
2016-04-10 22:49:33.218 [info] <0.7.0> Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:49:33.275 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:49:33.293 [info] <0.458.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.458.0>
2016-04-10 22:49:33.184 [info] <0.7.0> Application mnesia2 exited with reason: shutdown
2016-04-10 22:49:33.207 [info] <0.927.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.927.0>
2016-04-10 22:49:33.209 [info] <0.7.0> Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:49:33.288 [info] <0.1027.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.1027.0>
2016-04-10 22:49:34.008 [warning] <0.6.0> lager_error_logger_h dropped 32 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:49:34.008 [error] <0.514.0> gen_server <0.514.0> terminated with reason: killed
2016-04-10 22:49:34.011 [error] <0.1018.0> CRASH REPORT Process <0.1018.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:49:34.008 [error] <0.514.0> CRASH REPORT Process <0.514.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:49:34.008 [error] <0.449.0> CRASH REPORT Process <0.449.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:49:34.008 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:49:34.078 [info] <0.547.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.547.0>
2016-04-10 22:49:34.085 [info] <0.7.0> Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:49:34.921 [error] <0.663.0> gen_server <0.663.0> terminated with reason: killed
2016-04-10 22:49:34.921 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:49:34.993 [info] <0.762.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.762.0>
2016-04-10 22:49:34.011 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:49:34.075 [info] <0.1150.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.1150.0>
2016-04-10 22:49:34.379 [info] <0.7.0> Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:49:34.497 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:49:34.528 [info] <0.1263.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.1263.0>
2016-04-10 22:49:34.988 [info] <0.1495.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.1495.0>
2016-04-10 22:49:35.132 [error] <0.1486.0> CRASH REPORT Process <0.1486.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:49:35.132 [error] <0.753.0> CRASH REPORT Process <0.753.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:49:35.132 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:49:35.190 [info] <0.1609.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.1609.0>
2016-04-10 22:49:35.495 [info] <0.7.0> Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:49:35.616 [error] <0.1600.0> CRASH REPORT Process <0.1600.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:49:35.132 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:49:35.194 [info] <0.861.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.861.0>
2016-04-10 22:49:35.197 [info] <0.7.0> Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:49:35.615 [error] <0.916.0> gen_server <0.916.0> terminated with reason: killed
2016-04-10 22:49:35.615 [error] <0.916.0> CRASH REPORT Process <0.916.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:49:35.615 [error] <0.852.0> CRASH REPORT Process <0.852.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:49:35.616 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:49:35.677 [info] <0.1726.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.1726.0>
2016-04-10 22:49:36.007 [warning] <0.6.0> lager_error_logger_h dropped 20 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:49:36.025 [info] <0.1852.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.1852.0>
2016-04-10 22:49:36.027 [info] <0.7.0> Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:49:35.615 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:49:35.682 [info] <0.963.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.963.0>
2016-04-10 22:49:36.007 [warning] <0.6.0> lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:49:36.033 [info] <0.1069.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.1069.0>
2016-04-10 22:49:36.047 [info] <0.7.0> Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:49:36.204 [error] <0.1908.0> gen_server <0.1908.0> terminated with reason: killed
2016-04-10 22:49:36.202 [error] <0.1121.0> gen_server <0.1121.0> terminated with reason: killed
2016-04-10 22:49:36.204 [error] <0.1908.0> CRASH REPORT Process <0.1908.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:49:36.202 [error] <0.1121.0> CRASH REPORT Process <0.1121.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:49:36.205 [error] <0.1843.0> CRASH REPORT Process <0.1843.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:49:36.203 [error] <0.1060.0> CRASH REPORT Process <0.1060.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:49:36.205 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:49:36.278 [info] <0.1983.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.1983.0>
2016-04-10 22:49:36.501 [info] <0.2116.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.2116.0>
2016-04-10 22:49:36.787 [info] <0.2256.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.2256.0>
2016-04-10 22:49:37.031 [warning] <0.6.0> lager_error_logger_h dropped 23 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:49:37.074 [info] <0.2387.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.2387.0>
2016-04-10 22:49:36.203 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:49:36.281 [info] <0.1168.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.1168.0>
2016-04-10 22:49:36.507 [info] <0.1269.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.1269.0>
2016-04-10 22:49:36.791 [info] <0.1375.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.1375.0>
2016-04-10 22:49:37.030 [warning] <0.6.0> lager_error_logger_h dropped 6 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:49:37.077 [info] <0.1462.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.1462.0>
2016-04-10 22:49:37.081 [info] <0.7.0> Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:49:37.379 [info] <0.7.0> Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:49:37.528 [error] <0.2378.0> CRASH REPORT Process <0.2378.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:49:37.526 [error] <0.1457.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.1476.0> exit with reason killed in context child_terminated
2016-04-10 22:49:37.527 [error] <0.1457.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.1476.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:49:37.527 [error] <0.1459.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-10 22:49:37.527 [error] <0.1459.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:49:37.527 [error] <0.1455.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.1457.0> exit with reason killed in context child_terminated
2016-04-10 22:49:37.528 [error] <0.1455.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.1457.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:49:37.528 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:49:37.598 [info] <0.2521.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.2521.0>
2016-04-10 22:49:37.789 [info] <0.2644.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.2644.0>
2016-04-10 22:49:38.089 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:49:38.089 [error] <0.2640.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-10 22:49:38.089 [error] <0.2640.0> CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:49:38.089 [error] <0.2643.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-10 22:49:38.089 [error] <0.2643.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:49:38.089 [error] <0.2638.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): ** ERROR ** mnesia2_event got unexpected event: {'EXIT',<0.2641.0>,killed}

2016-04-10 22:49:38.090 [error] <0.2638.0> CRASH REPORT Process mnesia2_event with 0 neighbours exited with reason: killed in gen_event:terminate_server/4 line 304
2016-04-10 22:49:38.090 [error] <0.2635.0> CRASH REPORT Process <0.2635.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:49:38.090 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:49:38.117 [info] <0.2772.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.2772.0>
2016-04-10 22:49:38.196 [info] <0.2866.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.2866.0>
2016-04-10 22:49:37.603 [info] <0.1575.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.1575.0>
2016-04-10 22:49:37.807 [info] <0.1662.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.1662.0>
2016-04-10 22:49:39.441 [warning] <0.6.0> lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:49:39.450 [info] <0.2976.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.2976.0>
2016-04-10 22:49:39.454 [info] <0.7.0> Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:49:40.668 [error] <0.2967.0> CRASH REPORT Process <0.2967.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:49:40.668 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:49:42.747 [info] <0.3082.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.3082.0>
2016-04-10 22:49:42.749 [info] <0.7.0> Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:49:42.751 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:49:42.752 [info] <0.3130.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.3130.0>
2016-04-10 22:49:42.771 [info] <0.3178.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.3178.0>
2016-04-10 22:49:45.241 [warning] <0.6.0> lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:49:45.247 [info] <0.3250.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.3250.0>
2016-04-10 22:49:45.249 [info] <0.7.0> Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:49:45.261 [error] <0.3241.0> CRASH REPORT Process <0.3241.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:49:45.261 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:49:47.310 [info] <0.3333.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.3333.0>
2016-04-10 22:49:47.314 [info] <0.7.0> Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:49:47.319 [info] <0.3327.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Restore aborted. mnesia2_config_backup:open_read["NonExisting.FILE"] -> {enoent,error}

2016-04-10 22:49:47.319 [info] <0.3327.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Restore aborted. mnesia2_config_backup:open_read["/home/travis/build/lrascao/mnesia2/logs/ct_run.test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2.2016-04-10_22.49.07/Mnesia2.test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2/LATEST.LOG"] -> badarg

2016-04-10 22:49:47.320 [error] <0.3361.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}}} ({error,{already_started,<0.3409.0>}})

2016-04-10 22:49:47.320 [info] <0.3409.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_tm_19 terminated: shutdown

2016-04-10 22:49:47.321 [error] <0.3363.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}}} ({error,{already_started,<0.3409.0>}})

2016-04-10 22:49:47.321 [error] <0.3362.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}}} ({error,{already_started,<0.3409.0>}})

2016-04-10 22:49:47.321 [error] <0.3360.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}}} ({error,{already_started,<0.3409.0>}})

2016-04-10 22:49:47.321 [error] <0.3367.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}}} ({error,{already_started,<0.3409.0>}})

2016-04-10 22:49:47.321 [error] <0.3369.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}}} ({error,{already_started,<0.3409.0>}})

2016-04-10 22:49:47.321 [error] <0.3375.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_13,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_13,shutdown]}}}} ({error,{already_started,<0.3409.0>}})

2016-04-10 22:49:49.410 [warning] <0.6.0> lager_error_logger_h dropped 6 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:49:49.410 [info] <0.3441.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_monitor starting: <0.3443.0>

2016-04-10 22:49:49.411 [info] <0.3441.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Mnesia2 debug level set to verbose
2016-04-10 22:49:49.411 [info] <0.3441.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_subscr starting: <0.3444.0>

2016-04-10 22:49:49.411 [info] <0.3441.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_locker starting: <0.3445.0>

2016-04-10 22:49:49.411 [info] <0.3441.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_recover starting: <0.3446.0>

2016-04-10 22:49:49.412 [info] <0.3441.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_tm starting: <0.3447.0>

2016-04-10 22:49:49.412 [info] <0.3441.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Schema initiated from: default

2016-04-10 22:49:49.412 [info] <0.3447.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.3447.0>
2016-04-10 22:49:49.412 [info] <0.3441.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_controller starting: <0.3450.0>

2016-04-10 22:49:49.413 [info] <0.3441.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_late_loader starting: <0.3451.0>

2016-04-10 22:49:49.413 [info] <0.3441.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Intend to load tables: []

2016-04-10 22:49:49.414 [info] <0.3441.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_tm_1 starting: <0.3453.0>

2016-04-10 22:49:49.414 [info] <0.3441.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_tm_2 starting: <0.3454.0>

2016-04-10 22:49:49.414 [info] <0.3441.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_tm_3 starting: <0.3455.0>

2016-04-10 22:49:49.414 [info] <0.3441.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_tm_4 starting: <0.3456.0>

2016-04-10 22:49:49.414 [info] <0.3441.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_tm_5 starting: <0.3457.0>

2016-04-10 22:49:49.415 [info] <0.3441.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_tm_6 starting: <0.3458.0>

2016-04-10 22:49:49.415 [info] <0.3441.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_tm_7 starting: <0.3459.0>

2016-04-10 22:49:49.415 [info] <0.3441.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_tm_8 starting: <0.3460.0>

2016-04-10 22:49:49.415 [info] <0.3441.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_tm_9 starting: <0.3461.0>

2016-04-10 22:49:49.415 [info] <0.3441.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_tm_10 starting: <0.3462.0>

2016-04-10 22:49:51.439 [warning] <0.6.0> lager_error_logger_h dropped 7 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:49:51.439 [info] <0.3491.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_monitor starting: <0.3493.0>

2016-04-10 22:49:51.440 [info] <0.3491.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Version: "1.0.0"

2016-04-10 22:49:51.440 [info] <0.3491.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env access_module: mnesia2

2016-04-10 22:49:51.440 [info] <0.3491.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env auto_repair: true

2016-04-10 22:49:51.440 [info] <0.3491.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env backup_module: mnesia2_backup

2016-04-10 22:49:51.440 [info] <0.3491.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env debug: debug

2016-04-10 22:49:51.440 [info] <0.3491.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2.2016-04-10_22.49.07/Mnesia2.test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2"

2016-04-10 22:49:51.440 [info] <0.3491.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env dump_disc_copies_at_startup: true

2016-04-10 22:49:51.441 [info] <0.3491.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env dump_log_load_regulation: false

2016-04-10 22:49:51.441 [info] <0.3491.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env dump_log_time_threshold: 180000

2016-04-10 22:49:51.441 [info] <0.3491.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env dump_log_update_in_place: true

2016-04-10 22:49:51.441 [info] <0.3491.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env dump_log_write_threshold: 1000

2016-04-10 22:49:51.441 [info] <0.3491.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env event_module: mnesia2_event

2016-04-10 22:49:51.441 [info] <0.3491.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env extra_db_nodes: []

2016-04-10 22:49:51.441 [info] <0.3491.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env ignore_fallback_at_startup: false

2016-04-10 22:49:51.441 [info] <0.3491.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env fallback_error_function: {mnesia2,lkill}

2016-04-10 22:49:51.441 [info] <0.3491.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env max_wait_for_decision: infinity

2016-04-10 22:49:51.442 [info] <0.3491.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env schema_location: opt_disc

2016-04-10 22:49:51.442 [info] <0.3491.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env core_dir: false

2016-04-10 22:49:51.442 [info] <0.3491.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env pid_sort_order: false

2016-04-10 22:49:51.442 [info] <0.3491.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env no_table_loaders: 2

2016-04-10 22:49:51.442 [info] <0.3491.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env dc_dump_limit: 4

2016-04-10 22:49:51.442 [info] <0.3491.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env send_compressed: 0

2016-04-10 22:49:51.442 [info] <0.3491.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env send_max_packets: 20

2016-04-10 22:49:51.442 [info] <0.3491.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env send_max_transfer_size: 7500

2016-04-10 22:49:51.444 [info] <0.3491.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env async_dirty_buffer_size: 524288

2016-04-10 22:49:51.444 [info] <0.3491.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env async_dirty_max_buffer_file_size: 100000000

2016-04-10 22:49:51.444 [info] <0.3491.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env async_dirty_tx_backlog_threshold: 200000

2016-04-10 22:49:51.445 [info] <0.3491.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env async_dirty_buffer_min_runtime: 10000

2016-04-10 22:49:51.445 [info] <0.3491.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env async_dirty_buffer_drained_cutoff: 5

2016-04-10 22:49:51.445 [info] <0.3497.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.3497.0>
2016-04-10 22:49:51.446 [info] <0.3491.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Mnesia2 debug level set to debug
2016-04-10 22:49:51.446 [info] <0.3491.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_subscr starting: <0.3494.0>

2016-04-10 22:49:51.446 [info] <0.3491.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_locker starting: <0.3495.0>

2016-04-10 22:49:51.446 [info] <0.3491.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_recover starting: <0.3496.0>

2016-04-10 22:49:51.447 [info] <0.3491.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_tm starting: <0.3497.0>

2016-04-10 22:49:51.447 [info] <0.3491.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Schema initiated from: default

2016-04-10 22:49:53.474 [warning] <0.6.0> lager_error_logger_h dropped 10 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:49:53.474 [info] <0.3544.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_monitor starting: <0.3546.0>

2016-04-10 22:49:53.474 [info] <0.3544.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Version: "1.0.0"

2016-04-10 22:49:53.474 [info] <0.3544.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env access_module: mnesia2

2016-04-10 22:49:53.476 [info] <0.3550.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.3550.0>
2016-04-10 22:49:53.478 [info] <0.7.0> Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:49:53.480 [error] <0.3541.0> CRASH REPORT Process <0.3541.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:49:53.480 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:49:55.501 [info] <0.3593.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_monitor starting: <0.3595.0>

2016-04-10 22:49:55.502 [info] <0.3593.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Version: "1.0.0"

2016-04-10 22:49:55.502 [info] <0.3593.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env access_module: mnesia2

2016-04-10 22:49:55.502 [info] <0.3593.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env auto_repair: true

2016-04-10 22:49:55.502 [info] <0.3593.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env backup_module: mnesia2_backup

2016-04-10 22:49:55.503 [info] <0.3593.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env debug: debug

2016-04-10 22:49:55.503 [info] <0.3593.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2.2016-04-10_22.49.07/Mnesia2.test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2"

2016-04-10 22:49:55.503 [info] <0.3599.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.3599.0>
2016-04-10 22:49:55.503 [info] <0.3593.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env dump_disc_copies_at_startup: true

2016-04-10 22:49:55.504 [info] <0.3593.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env dump_log_load_regulation: false

2016-04-10 22:49:55.504 [info] <0.3593.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env dump_log_time_threshold: 180000

2016-04-10 22:49:55.504 [info] <0.3593.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env dump_log_update_in_place: true

2016-04-10 22:49:55.504 [info] <0.3593.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env dump_log_write_threshold: 1000

2016-04-10 22:49:55.505 [info] <0.3593.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env event_module: mnesia2_event

2016-04-10 22:49:55.505 [info] <0.3593.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env extra_db_nodes: []

2016-04-10 22:49:55.505 [info] <0.3593.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env ignore_fallback_at_startup: false

2016-04-10 22:49:57.529 [warning] <0.6.0> lager_error_logger_h dropped 7 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:49:57.531 [info] <0.3655.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.3655.0>
2016-04-10 22:49:57.533 [info] <0.7.0> Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:49:57.534 [error] <0.3646.0> CRASH REPORT Process <0.3646.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:49:57.534 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:49:59.627 [info] <0.3719.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.3719.0>
2016-04-10 22:49:59.629 [info] <0.7.0> Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:49:59.630 [error] <0.3710.0> CRASH REPORT Process <0.3710.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:49:59.630 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:00.731 [info] <0.3790.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.3790.0>
2016-04-10 22:50:00.733 [info] <0.7.0> Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:50:00.736 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:50:00.742 [info] <0.3851.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.3851.0>
2016-04-10 22:50:10.660 [error] <0.3845.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:50:11.873 [error] <0.3845.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:50:12.410 [error] <0.3845.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:50:15.792 [error] <0.3845.0> Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:50:15.916 [error] <0.3842.0> CRASH REPORT Process <0.3842.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:15.916 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:18.042 [info] <0.4446.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.4446.0>
2016-04-10 22:50:18.044 [info] <0.7.0> Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:50:24.051 [error] <0.4437.0> CRASH REPORT Process <0.4437.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:24.051 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:26.140 [info] <0.4546.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.4546.0>
2016-04-10 22:50:26.142 [info] <0.7.0> Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:50:27.158 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:50:29.280 [info] <0.4662.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.4662.0>
2016-04-10 22:50:29.283 [info] <0.7.0> Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:50:29.290 [error] <0.4653.0> CRASH REPORT Process <0.4653.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:29.290 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:31.407 [info] <0.4729.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.4729.0>
2016-04-10 22:50:31.410 [info] <0.7.0> Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:50:31.446 [error] <0.4720.0> CRASH REPORT Process <0.4720.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:31.446 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:33.548 [warning] <0.6.0> lager_error_logger_h dropped 13 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:50:33.570 [info] <0.1789.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.1789.0>
2016-04-10 22:50:33.582 [info] <0.7.0> Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:50:33.567 [info] <0.4821.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.4821.0>
2016-04-10 22:50:33.872 [info] <0.7.0> Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:50:34.873 [error] <0.1842.0> gen_server <0.1842.0> terminated with reason: killed
2016-04-10 22:50:34.873 [error] <0.1842.0> CRASH REPORT Process <0.1842.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:50:34.874 [error] <0.1780.0> CRASH REPORT Process <0.1780.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:34.874 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:36.931 [info] <0.1858.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.1858.0>
2016-04-10 22:50:36.935 [info] <0.7.0> Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:50:37.937 [error] <0.4885.0> gen_server <0.4885.0> terminated with reason: killed
2016-04-10 22:50:37.937 [error] <0.4885.0> CRASH REPORT Process <0.4885.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:50:37.937 [error] <0.4812.0> CRASH REPORT Process <0.4812.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:37.938 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:38.990 [error] <0.1849.0> CRASH REPORT Process <0.1849.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:38.990 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:40.681 [info] <0.4928.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.4928.0>
2016-04-10 22:50:40.684 [info] <0.7.0> Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:50:40.692 [error] <0.4919.0> CRASH REPORT Process <0.4919.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:40.687 [info] <0.1939.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.1939.0>
2016-04-10 22:50:40.690 [info] <0.7.0> Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:50:40.694 [error] <0.1985.0> gen_server <0.1985.0> terminated with reason: killed
2016-04-10 22:50:40.694 [error] <0.1985.0> CRASH REPORT Process <0.1985.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:50:40.694 [error] <0.1930.0> CRASH REPORT Process <0.1930.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:40.693 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:40.838 [info] <0.5008.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.5008.0>
2016-04-10 22:50:40.694 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:45.043 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:50:45.084 [info] <0.5132.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.5132.0>
2016-04-10 22:50:45.089 [info] <0.7.0> Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:50:45.075 [info] <0.2014.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.2014.0>
2016-04-10 22:50:45.077 [info] <0.7.0> Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:50:56.050 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:50:56.057 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:50:57.193 [info] <0.2136.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.2136.0>
2016-04-10 22:50:57.197 [info] <0.7.0> Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:50:57.244 [error] <0.2180.0> gen_server <0.2180.0> terminated with reason: killed
2016-04-10 22:50:57.244 [error] <0.2180.0> CRASH REPORT Process <0.2180.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:50:57.244 [error] <0.2127.0> CRASH REPORT Process <0.2127.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:57.183 [info] <0.5263.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.5263.0>
2016-04-10 22:50:57.185 [info] <0.7.0> Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:50:57.266 [error] <0.5254.0> CRASH REPORT Process <0.5254.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:57.266 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:57.301 [info] <0.5351.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.5351.0>
2016-04-10 22:50:57.245 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:57.536 [info] <0.2224.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.2224.0>
2016-04-10 22:50:59.086 [error] <0.2215.0> CRASH REPORT Process <0.2215.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:59.086 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:00.159 [info] <0.2327.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.2327.0>
2016-04-10 22:51:00.165 [info] <0.7.0> Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:51:00.188 [error] <0.2339.0> gen_server <0.2339.0> terminated with reason: killed
2016-04-10 22:51:00.141 [warning] <0.6.0> lager_error_logger_h dropped 12 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:51:00.146 [info] <0.5474.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.5474.0>
2016-04-10 22:51:00.148 [info] <0.7.0> Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:51:00.189 [error] <0.5467.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.5469.0> exit with reason killed in context child_terminated
2016-04-10 22:51:00.189 [error] <0.5467.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.5469.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:51:00.189 [error] <0.5473.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-10 22:51:00.189 [error] <0.5473.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:51:00.189 [error] <0.5465.0> CRASH REPORT Process <0.5465.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:51:00.188 [error] <0.2339.0> CRASH REPORT Process <0.2339.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:51:00.188 [error] <0.2318.0> CRASH REPORT Process <0.2318.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:51:00.189 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:00.188 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:02.291 [info] <0.2402.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.2402.0>
2016-04-10 22:51:02.304 [info] <0.7.0> Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:51:02.308 [error] <0.2414.0> gen_server <0.2414.0> terminated with reason: killed
2016-04-10 22:51:02.285 [info] <0.5585.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.5585.0>
2016-04-10 22:51:02.286 [info] <0.7.0> Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:51:02.308 [error] <0.5649.0> gen_server <0.5649.0> terminated with reason: killed
2016-04-10 22:51:02.308 [error] <0.5649.0> CRASH REPORT Process <0.5649.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:51:02.308 [error] <0.2414.0> CRASH REPORT Process <0.2414.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:51:02.308 [error] <0.5576.0> CRASH REPORT Process <0.5576.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:51:02.308 [error] <0.2393.0> CRASH REPORT Process <0.2393.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:51:02.308 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:02.308 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:04.495 [info] <0.5665.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.5665.0>
2016-04-10 22:51:04.507 [info] <0.7.0> Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:51:04.547 [error] <0.5700.0> gen_server <0.5700.0> terminated with reason: killed
2016-04-10 22:51:04.547 [error] <0.5700.0> CRASH REPORT Process <0.5700.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:51:04.547 [error] <0.5656.0> CRASH REPORT Process <0.5656.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:51:04.334 [info] <0.2461.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.2461.0>
2016-04-10 22:51:04.335 [info] <0.7.0> Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:51:04.547 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:05.969 [error] <0.2452.0> CRASH REPORT Process <0.2452.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:51:05.969 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:07.064 [info] <0.5790.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.5790.0>
2016-04-10 22:51:07.067 [info] <0.7.0> Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:51:07.550 [error] <0.5843.0> gen_server <0.5843.0> terminated with reason: killed
2016-04-10 22:51:07.071 [info] <0.2550.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.2550.0>
2016-04-10 22:51:07.077 [info] <0.7.0> Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:51:07.553 [error] <0.2601.0> gen_server <0.2601.0> terminated with reason: killed
2016-04-10 22:51:07.553 [error] <0.2601.0> CRASH REPORT Process <0.2601.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:51:07.551 [error] <0.5843.0> CRASH REPORT Process <0.5843.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:51:07.553 [error] <0.2592.0> gen_server <0.2592.0> terminated with reason: killed
2016-04-10 22:51:07.552 [error] <0.5781.0> CRASH REPORT Process <0.5781.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:51:07.553 [error] <0.2592.0> CRASH REPORT Process <0.2592.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:51:07.556 [error] <0.2541.0> CRASH REPORT Process <0.2541.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:51:07.552 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:07.556 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:07.420 [info] <0.7.0> Application lager started on node 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:51:07.421 [info] <0.7.0> Application poolgirl started on node 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:51:07.475 [info] <0.101.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.101.0>
2016-04-10 22:51:07.506 [info] <0.7.0> Application mnesia2 started on node 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:51:10.240 [info] <0.2631.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.2631.0>
2016-04-10 22:51:10.247 [info] <0.7.0> Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:51:10.251 [error] <0.2643.0> gen_server <0.2643.0> terminated with reason: killed
2016-04-10 22:51:09.740 [info] <0.5885.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.5885.0>
2016-04-10 22:51:09.742 [info] <0.7.0> Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:51:10.254 [error] <0.5949.0> gen_server <0.5949.0> terminated with reason: killed
2016-04-10 22:51:10.251 [error] <0.2643.0> CRASH REPORT Process <0.2643.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:51:10.255 [error] <0.5949.0> CRASH REPORT Process <0.5949.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:51:10.252 [error] <0.2622.0> CRASH REPORT Process <0.2622.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:51:10.256 [error] <0.5876.0> CRASH REPORT Process <0.5876.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:51:10.256 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:10.252 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:12.346 [info] <0.5979.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.5979.0>
2016-04-10 22:51:12.348 [info] <0.7.0> Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:51:12.375 [error] <0.6023.0> gen_server <0.6023.0> terminated with reason: killed
2016-04-10 22:51:12.350 [info] <0.2701.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.2701.0>
2016-04-10 22:51:12.354 [info] <0.7.0> Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:51:12.374 [error] <0.2692.0> CRASH REPORT Process <0.2692.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:51:12.375 [error] <0.6023.0> CRASH REPORT Process <0.6023.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:51:12.375 [error] <0.5970.0> CRASH REPORT Process <0.5970.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:51:12.375 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:12.375 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:14.582 [info] <0.2776.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.2776.0>
2016-04-10 22:51:14.585 [info] <0.7.0> Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:51:14.589 [error] <0.2830.0> gen_server <0.2830.0> terminated with reason: killed
2016-04-10 22:51:14.589 [error] <0.2830.0> CRASH REPORT Process <0.2830.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:51:14.589 [error] <0.2767.0> CRASH REPORT Process <0.2767.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:51:14.547 [info] <0.6065.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.6065.0>
2016-04-10 22:51:14.550 [info] <0.7.0> Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:51:14.589 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:15.616 [error] <0.6056.0> CRASH REPORT Process <0.6056.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:51:15.616 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:17.648 [info] <0.2846.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.2846.0>
2016-04-10 22:51:17.649 [info] <0.7.0> Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:51:22.692 [info] <0.6143.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.6143.0>
2016-04-10 22:51:22.701 [info] <0.7.0> Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:51:22.708 [error] <0.6204.0> gen_server <0.6204.0> terminated with reason: killed
2016-04-10 22:51:22.706 [error] <0.2841.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.2859.0> exit with reason killed in context child_terminated
2016-04-10 22:51:22.708 [error] <0.6204.0> CRASH REPORT Process <0.6204.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:51:22.708 [error] <0.6134.0> CRASH REPORT Process <0.6134.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:51:22.706 [error] <0.2841.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.2859.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:51:22.706 [error] <0.2913.0> gen_server <0.2913.0> terminated with reason: killed
2016-04-10 22:51:22.707 [error] <0.2913.0> CRASH REPORT Process <0.2913.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:51:22.707 [error] <0.2837.0> CRASH REPORT Process <0.2837.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:51:22.708 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:22.707 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:23.898 [info] <0.2945.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.2945.0>
2016-04-10 22:51:23.901 [info] <0.7.0> Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:51:23.981 [error] <0.2997.0> gen_server <0.2997.0> terminated with reason: killed
2016-04-10 22:51:23.981 [error] <0.2997.0> CRASH REPORT Process <0.2997.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:51:23.982 [error] <0.3008.0> gen_server <0.3008.0> terminated with reason: killed
2016-04-10 22:51:23.982 [error] <0.3008.0> CRASH REPORT Process <0.3008.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:51:23.982 [error] <0.2936.0> CRASH REPORT Process <0.2936.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:51:23.883 [info] <0.6253.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.6253.0>
2016-04-10 22:51:23.885 [info] <0.7.0> Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:51:24.060 [error] <0.6244.0> CRASH REPORT Process <0.6244.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:51:23.855 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:51:23.907 [info] <0.191.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.191.0>
2016-04-10 22:51:23.912 [info] <0.7.0> Application mnesia2 started on node 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:51:24.080 [error] <0.274.0> gen_server <0.274.0> terminated with reason: killed
2016-04-10 22:51:24.080 [error] <0.274.0> CRASH REPORT Process <0.274.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:51:24.081 [error] <0.182.0> CRASH REPORT Process <0.182.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:51:24.081 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:24.167 [info] <0.295.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.295.0>
2016-04-10 22:51:24.183 [info] <0.7.0> Application mnesia2 started on node 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:51:24.060 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:24.164 [info] <0.6375.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.6375.0>
2016-04-10 22:51:24.469 [info] <0.7.0> Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:51:23.982 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:24.009 [info] <0.3036.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.3036.0>
2016-04-10 22:51:24.037 [info] <0.7.0> Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:51:24.108 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:51:24.121 [info] <0.3131.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.3131.0>
2016-04-10 22:51:24.989 [error] <0.367.0> gen_server <0.367.0> terminated with reason: killed
2016-04-10 22:51:24.989 [error] <0.367.0> CRASH REPORT Process <0.367.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:51:24.989 [error] <0.356.0> gen_server <0.356.0> terminated with reason: killed
2016-04-10 22:51:24.989 [error] <0.356.0> CRASH REPORT Process <0.356.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:51:25.015 [info] <0.391.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.391.0>
2016-04-10 22:51:25.017 [info] <0.7.0> Application mnesia2 started on node 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:51:27.082 [error] <0.6473.0> gen_server <0.6473.0> terminated with reason: killed
2016-04-10 22:51:27.082 [error] <0.6473.0> CRASH REPORT Process <0.6473.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:51:27.083 [error] <0.6443.0> gen_server <0.6443.0> terminated with reason: killed
2016-04-10 22:51:27.083 [error] <0.6443.0> CRASH REPORT Process <0.6443.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:51:27.084 [error] <0.6366.0> CRASH REPORT Process <0.6366.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:51:27.103 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:51:27.103 [error] <0.3224.0> gen_server <0.3224.0> terminated with reason: killed
2016-04-10 22:51:27.104 [error] <0.3224.0> CRASH REPORT Process <0.3224.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:51:27.104 [error] <0.3122.0> CRASH REPORT Process <0.3122.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:51:27.127 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:51:27.160 [info] <0.497.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.497.0>
2016-04-10 22:51:27.161 [info] <0.7.0> Application mnesia2 started on node 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:51:27.706 [error] <0.488.0> CRASH REPORT Process <0.488.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:51:27.084 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:27.184 [info] <0.6492.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.6492.0>
2016-04-10 22:51:27.192 [info] <0.7.0> Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:51:27.815 [error] <0.6580.0> gen_server <0.6580.0> terminated with reason: killed
2016-04-10 22:51:27.815 [error] <0.6580.0> CRASH REPORT Process <0.6580.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:51:27.815 [error] <0.6585.0> gen_server <0.6585.0> terminated with reason: killed
2016-04-10 22:51:27.816 [error] <0.6585.0> CRASH REPORT Process <0.6585.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:51:27.816 [error] <0.6566.0> gen_server <0.6566.0> terminated with reason: killed
2016-04-10 22:51:27.816 [error] <0.6566.0> CRASH REPORT Process <0.6566.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:51:27.816 [error] <0.6483.0> CRASH REPORT Process <0.6483.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:51:27.104 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:27.185 [info] <0.3245.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.3245.0>
2016-04-10 22:51:27.199 [info] <0.7.0> Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:51:27.828 [error] <0.3333.0> gen_server <0.3333.0> terminated with reason: killed
2016-04-10 22:51:27.828 [error] <0.3333.0> CRASH REPORT Process <0.3333.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:51:27.816 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:27.895 [info] <0.6604.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.6604.0>
2016-04-10 22:51:27.896 [info] <0.3354.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.3354.0>
2016-04-10 22:51:27.706 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:27.741 [info] <0.595.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.595.0>
2016-04-10 22:51:27.865 [info] <0.696.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.696.0>
2016-04-10 22:51:28.725 [warning] <0.6.0> lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:51:28.725 [error] <0.3425.0> gen_server <0.3425.0> terminated with reason: killed
2016-04-10 22:51:28.725 [error] <0.3425.0> CRASH REPORT Process <0.3425.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:51:28.725 [error] <0.3410.0> gen_server <0.3410.0> terminated with reason: killed
2016-04-10 22:51:28.725 [error] <0.3410.0> CRASH REPORT Process <0.3410.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:51:28.725 [error] <0.3345.0> CRASH REPORT Process <0.3345.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:51:28.201 [info] <0.7.0> Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:51:28.725 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:28.769 [info] <0.3451.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.3451.0>
2016-04-10 22:51:28.777 [info] <0.7.0> Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:51:29.842 [warning] <0.6.0> lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:51:29.845 [info] <0.3529.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.3529.0>
2016-04-10 22:51:29.855 [info] <0.7.0> Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:51:29.907 [error] <0.3543.0> gen_server <0.3543.0> terminated with reason: killed
2016-04-10 22:51:29.909 [error] <0.6716.0> gen_server <0.6716.0> terminated with reason: killed
2016-04-10 22:51:29.907 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:51:29.907 [error] <0.819.0> gen_server <0.819.0> terminated with reason: killed
2016-04-10 22:51:29.907 [error] <0.3543.0> CRASH REPORT Process <0.3543.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:51:29.908 [error] <0.3520.0> CRASH REPORT Process <0.3520.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:51:29.907 [error] <0.819.0> CRASH REPORT Process <0.819.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:51:29.909 [error] <0.6716.0> CRASH REPORT Process <0.6716.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:51:29.912 [error] <0.6667.0> gen_server <0.6667.0> terminated with reason: killed
2016-04-10 22:51:29.907 [error] <0.809.0> gen_server <0.809.0> terminated with reason: killed
2016-04-10 22:51:29.912 [error] <0.6667.0> CRASH REPORT Process <0.6667.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:51:29.907 [error] <0.809.0> CRASH REPORT Process <0.809.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:51:29.907 [error] <0.768.0> gen_server <0.768.0> terminated with reason: killed
2016-04-10 22:51:29.913 [error] <0.6595.0> CRASH REPORT Process <0.6595.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:51:29.907 [error] <0.768.0> CRASH REPORT Process <0.768.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:51:29.908 [error] <0.687.0> CRASH REPORT Process <0.687.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:51:29.908 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:30.003 [info] <0.3607.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.3607.0>
2016-04-10 22:51:30.007 [info] <0.7.0> Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:51:30.053 [error] <0.3598.0> CRASH REPORT Process <0.3598.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:51:30.053 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:30.080 [info] <0.3702.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.3702.0>
2016-04-10 22:51:30.155 [info] <0.3792.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.3792.0>
2016-04-10 22:51:30.219 [info] <0.3892.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.3892.0>
2016-04-10 22:51:29.908 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:29.913 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:29.983 [info] <0.6749.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.6749.0>
2016-04-10 22:51:29.986 [info] <0.7.0> Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:51:30.217 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:51:30.733 [info] <0.6862.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.6862.0>
2016-04-10 22:51:30.748 [info] <0.7.0> Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:51:30.776 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:51:30.813 [info] <0.6945.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.6945.0>
2016-04-10 22:51:31.380 [error] <0.7010.0> gen_server <0.7010.0> terminated with reason: killed
2016-04-10 22:51:31.316 [warning] <0.6.0> lager_error_logger_h dropped 42 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:51:31.318 [info] <0.3974.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.3974.0>
2016-04-10 22:51:31.332 [info] <0.7.0> Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:51:31.382 [error] <0.3965.0> CRASH REPORT Process <0.3965.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:51:31.380 [error] <0.7010.0> CRASH REPORT Process <0.7010.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:51:31.380 [error] <0.6936.0> CRASH REPORT Process <0.6936.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:51:31.466 [info] <0.846.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.846.0>
2016-04-10 22:51:31.770 [info] <0.7.0> Application mnesia2 started on node 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:51:31.842 [error] <0.908.0> gen_server <0.908.0> terminated with reason: killed
2016-04-10 22:51:31.380 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:31.459 [info] <0.7046.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.7046.0>
2016-04-10 22:51:31.461 [info] <0.7.0> Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:51:31.843 [error] <0.7109.0> gen_server <0.7109.0> terminated with reason: killed
2016-04-10 22:51:31.844 [error] <0.7109.0> CRASH REPORT Process <0.7109.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:51:31.842 [error] <0.908.0> CRASH REPORT Process <0.908.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:51:31.843 [error] <0.903.0> gen_server <0.903.0> terminated with reason: killed
2016-04-10 22:51:31.843 [error] <0.903.0> CRASH REPORT Process <0.903.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:51:31.843 [error] <0.837.0> CRASH REPORT Process <0.837.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:51:31.382 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:31.468 [info] <0.4066.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.4066.0>
2016-04-10 22:51:31.869 [info] <0.4158.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.4158.0>
2016-04-10 22:51:31.944 [info] <0.4237.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.4237.0>
2016-04-10 22:51:31.894 [info] <0.7157.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.7157.0>
2016-04-10 22:51:31.964 [info] <0.7249.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.7249.0>
2016-04-10 22:51:31.843 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:31.867 [info] <0.951.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.951.0>
2016-04-10 22:51:31.943 [info] <0.1029.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.1029.0>
2016-04-10 22:51:41.984 [warning] <0.6.0> lager_error_logger_h dropped 5 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:51:41.984 [error] <0.7242.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at undefined exit with reason killed in context start_error
2016-04-10 22:51:41.984 [error] <0.7245.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-10 22:51:41.984 [error] <0.7248.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-10 22:51:41.984 [error] <0.7248.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:51:41.984 [error] <0.7268.0> gen_server mnesia2_snmp_sup terminated with reason: killed
2016-04-10 22:51:41.984 [error] <0.7268.0> CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:51:41.984 [error] <0.7246.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-10 22:51:41.984 [error] <0.7246.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:51:41.984 [error] <0.7240.0> CRASH REPORT Process <0.7240.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}} in application_master:init/4 line 133
2016-04-10 22:51:41.985 [info] <0.7.0> Application mnesia2 exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}}
2016-04-10 22:51:41.985 [error] <0.7245.0> CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:51:42.069 [warning] <0.6.0> lager_error_logger_h dropped 4 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:51:42.069 [error] <0.4281.0> gen_server <0.4281.0> terminated with reason: killed
2016-04-10 22:51:42.070 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:51:42.070 [error] <0.1078.0> gen_server <0.1078.0> terminated with reason: killed
2016-04-10 22:51:42.070 [error] <0.4281.0> CRASH REPORT Process <0.4281.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:51:42.070 [error] <0.1078.0> CRASH REPORT Process <0.1078.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:51:42.070 [error] <0.4228.0> CRASH REPORT Process <0.4228.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:51:42.070 [error] <0.1073.0> gen_server <0.1073.0> terminated with reason: killed
2016-04-10 22:51:42.070 [error] <0.1073.0> CRASH REPORT Process <0.1073.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:51:42.070 [error] <0.1020.0> CRASH REPORT Process <0.1020.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:51:42.070 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:42.070 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:44.459 [info] <0.7358.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.7358.0>
2016-04-10 22:51:44.462 [info] <0.7.0> Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:51:48.748 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:51:48.917 [info] <0.7494.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.7494.0>
2016-04-10 22:51:48.920 [info] <0.7.0> Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:51:48.931 [info] <0.1125.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.1125.0>
2016-04-10 22:51:48.943 [info] <0.7.0> Application mnesia2 started on node 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:51:48.931 [info] <0.4328.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.4328.0>
2016-04-10 22:51:48.937 [info] <0.7.0> Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:51:55.208 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:51:55.360 [info] <0.1240.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.1240.0>
2016-04-10 22:51:55.372 [info] <0.7.0> Application mnesia2 started on node 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:51:55.209 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:51:55.350 [info] <0.7623.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.7623.0>
2016-04-10 22:51:55.353 [info] <0.7.0> Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:51:55.226 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:51:55.359 [info] <0.4444.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.4444.0>
2016-04-10 22:51:55.663 [info] <0.7.0> Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:52:01.765 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:52:01.894 [info] <0.1353.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.1353.0>
2016-04-10 22:52:01.911 [info] <0.7.0> Application mnesia2 started on node 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:52:01.765 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:52:01.884 [info] <0.7752.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.7752.0>
2016-04-10 22:52:02.189 [info] <0.7.0> Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:52:01.770 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:52:01.900 [info] <0.4560.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.4560.0>
2016-04-10 22:52:01.905 [info] <0.7.0> Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:52:18.789 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:52:18.918 [info] <0.8892.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.8892.0>
2016-04-10 22:52:18.920 [info] <0.7.0> Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:52:18.791 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:52:18.924 [info] <0.5682.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.5682.0>
2016-04-10 22:52:18.930 [info] <0.7.0> Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:52:18.792 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:52:18.924 [info] <0.2479.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.2479.0>
2016-04-10 22:52:18.944 [info] <0.7.0> Application mnesia2 started on node 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:52:25.297 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:52:25.463 [info] <0.5807.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.5807.0>
2016-04-10 22:52:25.468 [info] <0.7.0> Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:52:25.303 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:52:25.447 [info] <0.2603.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.2603.0>
2016-04-10 22:52:25.751 [info] <0.7.0> Application mnesia2 started on node 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:52:25.302 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:52:25.443 [info] <0.9030.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.9030.0>
2016-04-10 22:52:25.748 [info] <0.7.0> Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:52:32.070 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:52:32.225 [info] <0.4076.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.4076.0>
2016-04-10 22:52:32.529 [info] <0.7.0> Application mnesia2 started on node 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:52:32.076 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:52:32.228 [info] <0.7277.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.7277.0>
2016-04-10 22:52:32.236 [info] <0.7.0> Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:52:32.078 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:52:32.219 [info] <0.10511.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.10511.0>
2016-04-10 22:52:32.222 [info] <0.7.0> Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:52:38.767 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:52:38.924 [info] <0.10952.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.10952.0>
2016-04-10 22:52:38.927 [info] <0.7.0> Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:52:38.781 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:52:38.932 [info] <0.6124.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.6124.0>
2016-04-10 22:52:39.007 [info] <0.7.0> Application mnesia2 started on node 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:52:38.800 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:52:38.933 [info] <0.8351.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.8351.0>
2016-04-10 22:52:38.945 [info] <0.7.0> Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:52:45.217 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:52:45.336 [info] <0.11081.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.11081.0>
2016-04-10 22:52:45.340 [info] <0.7.0> Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:52:45.216 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:52:45.337 [info] <0.8467.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.8467.0>
2016-04-10 22:52:45.663 [info] <0.7.0> Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:52:45.232 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:52:45.358 [info] <0.6916.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.6916.0>
2016-04-10 22:52:45.362 [info] <0.7.0> Application mnesia2 started on node 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2'
2016-04-10 22:52:51.844 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:52:51.845 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:52:51.845 [info] <0.7.0> Application mnesia2 exited with reason: stopped
