2016-04-10 22:34:49.929 [info] <0.7.0> Application lager started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:34:49.929 [info] <0.7.0> Application poolgirl started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:34:49.952 [info] <0.495.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.495.0>
2016-04-10 22:34:49.972 [info] <0.563.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.563.0>
2016-04-10 22:34:50.382 [error] <0.554.0> CRASH REPORT Process <0.554.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:50.382 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:34:50.531 [info] <0.673.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.673.0>
2016-04-10 22:34:50.535 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:34:50.982 [error] <0.664.0> CRASH REPORT Process <0.664.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:51.041 [info] <0.799.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.799.0>
2016-04-10 22:34:51.348 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:34:51.603 [error] <0.793.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): ** ERROR ** (ignoring core) ** FATAL ** A fallback is installed and Mnesia2 must be restarted. Forcing shutdown after mnesia2_down from 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12'...

2016-04-10 22:34:51.603 [error] <0.794.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_locker:start() at <0.797.0> exit with reason killed in context child_terminated
2016-04-10 22:34:51.604 [error] <0.794.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_locker:start() at <0.797.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:34:51.605 [error] <0.792.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.794.0> exit with reason shutdown in context child_terminated
2016-04-10 22:34:51.605 [error] <0.792.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.794.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:34:50.749 [info] <0.7.0> Application lager started on node 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:34:50.749 [info] <0.7.0> Application poolgirl started on node 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:34:50.815 [info] <0.100.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.100.0>
2016-04-10 22:34:51.023 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:34:51.059 [info] <0.216.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.216.0>
2016-04-10 22:34:51.064 [info] <0.7.0> Application mnesia2 started on node 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:34:51.597 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:34:51.653 [info] <0.370.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.370.0>
2016-04-10 22:34:51.608 [info] <0.7.0> Application mnesia2 exited with reason: shutdown
2016-04-10 22:34:51.637 [info] <0.928.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.928.0>
2016-04-10 22:34:52.189 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:34:52.189 [error] <0.922.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): ** ERROR ** (ignoring core) ** FATAL ** A fallback is installed and Mnesia2 must be restarted. Forcing shutdown after mnesia2_down from 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12'...

2016-04-10 22:34:52.190 [error] <0.923.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_locker:start() at <0.926.0> exit with reason killed in context shutdown_error
2016-04-10 22:34:52.192 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:34:52.210 [info] <0.1028.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.1028.0>
2016-04-10 22:34:52.516 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:34:52.192 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:34:52.239 [info] <0.460.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.460.0>
2016-04-10 22:34:52.252 [info] <0.7.0> Application mnesia2 started on node 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:34:53.273 [error] <0.1022.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): ** ERROR ** mnesia2_event got unexpected event: {'EXIT',<0.1025.0>,killed}

2016-04-10 22:34:53.273 [error] <0.517.0> gen_server <0.517.0> terminated with reason: killed
2016-04-10 22:34:53.274 [error] <0.1089.0> gen_server <0.1089.0> terminated with reason: killed
2016-04-10 22:34:53.273 [error] <0.517.0> CRASH REPORT Process <0.517.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:34:53.274 [error] <0.1089.0> CRASH REPORT Process <0.1089.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:34:53.273 [error] <0.451.0> CRASH REPORT Process <0.451.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:53.274 [error] <0.1019.0> CRASH REPORT Process <0.1019.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:53.273 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:34:53.359 [info] <0.549.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.549.0>
2016-04-10 22:34:53.363 [info] <0.7.0> Application mnesia2 started on node 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:34:53.938 [error] <0.662.0> gen_server <0.662.0> terminated with reason: killed
2016-04-10 22:34:53.939 [error] <0.662.0> CRASH REPORT Process <0.662.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:34:53.939 [error] <0.540.0> CRASH REPORT Process <0.540.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:53.939 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:34:54.020 [info] <0.763.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.763.0>
2016-04-10 22:34:54.025 [info] <0.7.0> Application mnesia2 started on node 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:34:54.145 [error] <0.815.0> gen_server <0.815.0> terminated with reason: killed
2016-04-10 22:34:53.274 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:34:53.351 [info] <0.1153.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.1153.0>
2016-04-10 22:34:53.353 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:34:53.474 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:34:53.500 [info] <0.1265.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.1265.0>
2016-04-10 22:34:54.004 [info] <0.1497.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.1497.0>
2016-04-10 22:34:54.005 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:34:54.007 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:34:54.145 [error] <0.1553.0> gen_server <0.1553.0> terminated with reason: killed
2016-04-10 22:34:54.146 [error] <0.815.0> CRASH REPORT Process <0.815.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:34:54.145 [error] <0.1553.0> CRASH REPORT Process <0.1553.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:34:54.148 [error] <0.754.0> CRASH REPORT Process <0.754.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:54.147 [error] <0.1488.0> CRASH REPORT Process <0.1488.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:54.148 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:34:54.147 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:34:54.433 [info] <0.862.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.862.0>
2016-04-10 22:34:54.665 [info] <0.963.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.963.0>
2016-04-10 22:34:54.901 [info] <0.1069.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.1069.0>
2016-04-10 22:34:55.388 [warning] <0.6.0> lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:34:55.389 [error] <0.1124.0> gen_server <0.1124.0> terminated with reason: killed
2016-04-10 22:34:54.420 [info] <0.1611.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.1611.0>
2016-04-10 22:34:54.660 [info] <0.1727.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.1727.0>
2016-04-10 22:34:54.899 [info] <0.1853.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.1853.0>
2016-04-10 22:34:55.204 [warning] <0.6.0> lager_error_logger_h dropped 39 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:34:55.205 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:34:55.391 [error] <0.1910.0> gen_server <0.1910.0> terminated with reason: killed
2016-04-10 22:34:55.391 [error] <0.1910.0> CRASH REPORT Process <0.1910.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:34:55.389 [error] <0.1124.0> CRASH REPORT Process <0.1124.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:34:55.392 [error] <0.1844.0> CRASH REPORT Process <0.1844.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:55.389 [error] <0.1060.0> CRASH REPORT Process <0.1060.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:55.392 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:34:55.389 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:34:55.452 [info] <0.1169.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.1169.0>
2016-04-10 22:34:55.463 [info] <0.7.0> Application mnesia2 started on node 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:34:56.185 [error] <0.1224.0> gen_server <0.1224.0> terminated with reason: killed
2016-04-10 22:34:56.185 [error] <0.1224.0> CRASH REPORT Process <0.1224.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:34:55.446 [info] <0.1985.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.1985.0>
2016-04-10 22:34:56.187 [warning] <0.6.0> lager_error_logger_h dropped 32 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:34:56.187 [error] <0.2039.0> gen_server <0.2039.0> terminated with reason: killed
2016-04-10 22:34:56.186 [error] <0.1160.0> CRASH REPORT Process <0.1160.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:56.188 [error] <0.2039.0> CRASH REPORT Process <0.2039.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:34:56.189 [error] <0.1976.0> CRASH REPORT Process <0.1976.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:56.190 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:34:56.256 [info] <0.2119.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.2119.0>
2016-04-10 22:34:56.186 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:34:56.259 [info] <0.1271.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.1271.0>
2016-04-10 22:34:56.266 [info] <0.7.0> Application mnesia2 started on node 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:34:56.794 [error] <0.1327.0> gen_server <0.1327.0> terminated with reason: killed
2016-04-10 22:34:56.563 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:34:56.797 [error] <0.2176.0> gen_server <0.2176.0> terminated with reason: killed
2016-04-10 22:34:56.794 [error] <0.1327.0> CRASH REPORT Process <0.1327.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:34:56.797 [error] <0.2176.0> CRASH REPORT Process <0.2176.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:34:56.795 [error] <0.1262.0> CRASH REPORT Process <0.1262.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:56.795 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:34:57.077 [info] <0.1379.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.1379.0>
2016-04-10 22:34:57.086 [info] <0.7.0> Application mnesia2 started on node 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:34:57.291 [error] <0.1431.0> gen_server <0.1431.0> terminated with reason: killed
2016-04-10 22:34:57.071 [info] <0.2260.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.2260.0>
2016-04-10 22:34:57.074 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:34:57.293 [error] <0.2316.0> gen_server <0.2316.0> terminated with reason: killed
2016-04-10 22:34:57.292 [error] <0.1431.0> CRASH REPORT Process <0.1431.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:34:57.292 [error] <0.1370.0> CRASH REPORT Process <0.1370.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:57.293 [error] <0.2316.0> CRASH REPORT Process <0.2316.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:34:57.293 [error] <0.2251.0> CRASH REPORT Process <0.2251.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:57.293 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:34:57.360 [info] <0.2391.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.2391.0>
2016-04-10 22:34:57.292 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:34:57.382 [info] <0.1466.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.1466.0>
2016-04-10 22:34:57.937 [info] <0.1578.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.1578.0>
2016-04-10 22:34:58.406 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:34:58.406 [error] <0.1631.0> gen_server <0.1631.0> terminated with reason: killed
2016-04-10 22:34:57.933 [info] <0.2523.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.2523.0>
2016-04-10 22:34:58.237 [warning] <0.6.0> lager_error_logger_h dropped 6 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:34:58.249 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:34:58.409 [error] <0.2563.0> gen_server <0.2563.0> terminated with reason: killed
2016-04-10 22:34:58.406 [error] <0.1631.0> CRASH REPORT Process <0.1631.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:34:58.409 [error] <0.2563.0> CRASH REPORT Process <0.2563.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:34:58.406 [error] <0.1569.0> CRASH REPORT Process <0.1569.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:58.409 [error] <0.2514.0> CRASH REPORT Process <0.2514.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:58.407 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:34:58.479 [info] <0.1666.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.1666.0>
2016-04-10 22:34:58.494 [info] <0.7.0> Application mnesia2 started on node 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:34:58.585 [error] <0.1711.0> gen_server <0.1711.0> terminated with reason: killed
2016-04-10 22:34:58.585 [error] <0.1711.0> CRASH REPORT Process <0.1711.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:34:58.409 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:34:58.475 [info] <0.2647.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.2647.0>
2016-04-10 22:34:58.862 [info] <0.2775.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.2775.0>
2016-04-10 22:34:58.961 [info] <0.2869.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.2869.0>
2016-04-10 22:35:00.222 [warning] <0.6.0> lager_error_logger_h dropped 10 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:35:00.228 [info] <0.2979.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.2979.0>
2016-04-10 22:35:00.231 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:35:01.753 [error] <0.2974.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.2990.0> exit with reason killed in context child_terminated
2016-04-10 22:35:01.754 [error] <0.2974.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.2990.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:35:01.756 [error] <0.2970.0> CRASH REPORT Process <0.2970.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:35:01.757 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:35:03.839 [info] <0.3085.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.3085.0>
2016-04-10 22:35:03.842 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:35:03.845 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:35:03.847 [info] <0.3133.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.3133.0>
2016-04-10 22:35:03.851 [info] <0.3181.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.3181.0>
2016-04-10 22:35:05.962 [info] <0.3253.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.3253.0>
2016-04-10 22:35:05.966 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:35:06.024 [error] <0.3244.0> CRASH REPORT Process <0.3244.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:35:06.024 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:35:08.096 [info] <0.3336.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.3336.0>
2016-04-10 22:35:08.099 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:35:08.127 [info] <0.3330.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): Restore aborted. mnesia2_config_backup:open_read["NonExisting.FILE"] -> {enoent,error}

2016-04-10 22:35:08.127 [info] <0.3330.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): Restore aborted. mnesia2_config_backup:open_read["/home/travis/build/lrascao/mnesia2/logs/ct_run.test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12.2016-04-10_22.34.22/Mnesia2.test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12/LATEST.LOG"] -> badarg

2016-04-10 22:35:08.127 [error] <0.3331.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.3355.0> exit with reason killed in context child_terminated
2016-04-10 22:35:08.128 [error] <0.3331.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.3355.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:35:08.129 [info] <0.3413.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): mnesia2_tm_5 terminated: shutdown

2016-04-10 22:35:08.129 [error] <0.3364.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}}} ({error,{already_started,<0.3413.0>}})

2016-04-10 22:35:08.129 [info] <0.3413.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): mnesia2_tm_4 terminated: shutdown

2016-04-10 22:35:08.129 [info] <0.3413.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): mnesia2_tm_1 terminated: shutdown

2016-04-10 22:35:08.130 [info] <0.3413.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): mnesia2_tm_2 terminated: shutdown

2016-04-10 22:35:08.130 [info] <0.3413.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): mnesia2_tm_7 terminated: shutdown

2016-04-10 22:35:10.209 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:35:10.211 [info] <0.3439.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.3439.0>
2016-04-10 22:35:10.216 [info] <0.3433.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): mnesia2_monitor starting: <0.3435.0>

2016-04-10 22:35:10.216 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:35:10.216 [info] <0.3433.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): Mnesia2 debug level set to verbose
2016-04-10 22:35:10.217 [error] <0.3447.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}}} ({error,{already_started,<0.3478.0>}})

2016-04-10 22:35:10.217 [error] <0.3449.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}}} ({error,{already_started,<0.3478.0>}})

2016-04-10 22:35:10.217 [error] <0.3448.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}}} ({error,{already_started,<0.3478.0>}})

2016-04-10 22:35:10.217 [error] <0.3446.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}}} ({error,{already_started,<0.3478.0>}})

2016-04-10 22:35:12.245 [warning] <0.6.0> lager_error_logger_h dropped 28 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:35:12.246 [info] <0.3515.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): mnesia2_monitor starting: <0.3517.0>

2016-04-10 22:35:12.246 [info] <0.3515.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): Version: "1.0.0"

2016-04-10 22:35:12.248 [info] <0.3515.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): Env access_module: mnesia2

2016-04-10 22:35:12.248 [info] <0.3521.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.3521.0>
2016-04-10 22:35:12.251 [info] <0.3515.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): Env auto_repair: true

2016-04-10 22:35:12.251 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:35:12.252 [info] <0.3579.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): mnesia2_tm_14 terminated: shutdown

2016-04-10 22:35:12.252 [info] <0.3579.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): mnesia2_tm_24 terminated: shutdown

2016-04-10 22:35:14.274 [warning] <0.6.0> lager_error_logger_h dropped 20 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:35:14.275 [info] <0.3586.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): mnesia2_monitor starting: <0.3588.0>

2016-04-10 22:35:14.275 [info] <0.3586.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): Version: "1.0.0"

2016-04-10 22:35:14.275 [info] <0.3586.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): Env access_module: mnesia2

2016-04-10 22:35:14.275 [info] <0.3586.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): Env auto_repair: true

2016-04-10 22:35:14.275 [info] <0.3586.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): Env backup_module: mnesia2_backup

2016-04-10 22:35:14.275 [info] <0.3586.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): Env debug: trace

2016-04-10 22:35:14.276 [info] <0.3586.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12.2016-04-10_22.34.22/Mnesia2.test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12"

2016-04-10 22:35:14.276 [info] <0.3586.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): Env dump_disc_copies_at_startup: true

2016-04-10 22:35:14.276 [info] <0.3586.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): Env dump_log_load_regulation: false

2016-04-10 22:35:14.276 [info] <0.3586.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): Env dump_log_time_threshold: 180000

2016-04-10 22:35:14.277 [info] <0.3586.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): Env dump_log_update_in_place: true

2016-04-10 22:35:14.277 [info] <0.3586.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): Env dump_log_write_threshold: 1000

2016-04-10 22:35:14.278 [info] <0.3586.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): Env event_module: mnesia2_event

2016-04-10 22:35:14.278 [info] <0.3592.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.3592.0>
2016-04-10 22:35:14.278 [info] <0.3586.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): Env extra_db_nodes: []

2016-04-10 22:35:14.278 [info] <0.3586.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): Env ignore_fallback_at_startup: false

2016-04-10 22:35:14.278 [info] <0.3586.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): Env fallback_error_function: {mnesia2,lkill}

2016-04-10 22:35:14.278 [info] <0.3586.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): Env max_wait_for_decision: infinity

2016-04-10 22:35:14.279 [info] <0.3586.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): Env schema_location: opt_disc

2016-04-10 22:35:14.279 [info] <0.3586.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): Env core_dir: false

2016-04-10 22:35:14.279 [info] <0.3586.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): Env pid_sort_order: false

2016-04-10 22:35:14.280 [info] <0.3586.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): Env no_table_loaders: 2

2016-04-10 22:35:14.280 [info] <0.3586.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): Env dc_dump_limit: 4

2016-04-10 22:35:14.280 [info] <0.3586.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): Env send_compressed: 0

2016-04-10 22:35:14.280 [info] <0.3586.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): Env send_max_packets: 20

2016-04-10 22:35:14.280 [info] <0.3586.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): Env send_max_transfer_size: 7500

2016-04-10 22:35:14.280 [info] <0.3586.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): Env async_dirty_buffer_size: 524288

2016-04-10 22:35:16.305 [warning] <0.6.0> lager_error_logger_h dropped 39 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:35:16.306 [info] <0.3668.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): mnesia2_monitor starting: <0.3670.0>

2016-04-10 22:35:16.306 [info] <0.3668.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): Version: "1.0.0"

2016-04-10 22:35:16.307 [info] <0.3668.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): Env access_module: mnesia2

2016-04-10 22:35:16.307 [info] <0.3668.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): Env auto_repair: true

2016-04-10 22:35:16.307 [info] <0.3668.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): Env backup_module: mnesia2_backup

2016-04-10 22:35:16.308 [info] <0.3668.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): Env debug: debug

2016-04-10 22:35:16.308 [info] <0.3674.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.3674.0>
2016-04-10 22:35:16.308 [info] <0.3668.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12.2016-04-10_22.34.22/Mnesia2.test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12"

2016-04-10 22:35:16.309 [info] <0.3668.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): Env dump_disc_copies_at_startup: true

2016-04-10 22:35:16.309 [info] <0.3668.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): Env dump_log_load_regulation: false

2016-04-10 22:35:18.334 [warning] <0.6.0> lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:35:18.335 [info] <0.3726.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.3726.0>
2016-04-10 22:35:18.337 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:35:18.338 [error] <0.3717.0> CRASH REPORT Process <0.3717.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:35:18.338 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:35:20.450 [info] <0.3790.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.3790.0>
2016-04-10 22:35:20.460 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:35:20.462 [error] <0.3781.0> CRASH REPORT Process <0.3781.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:35:20.462 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:35:21.593 [info] <0.3861.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.3861.0>
2016-04-10 22:35:21.595 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:35:21.604 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:35:21.614 [info] <0.3922.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.3922.0>
2016-04-10 22:35:27.597 [warning] <0.3916.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:35:36.386 [warning] <0.3916.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:35:36.687 [error] <0.3913.0> CRASH REPORT Process <0.3913.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:35:36.687 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:35:38.831 [info] <0.4413.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.4413.0>
2016-04-10 22:35:38.834 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:35:44.844 [error] <0.4404.0> CRASH REPORT Process <0.4404.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:35:44.844 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:35:46.938 [info] <0.4513.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.4513.0>
2016-04-10 22:35:46.941 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:35:47.966 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:35:50.095 [info] <0.4629.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.4629.0>
2016-04-10 22:35:50.098 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:35:50.108 [error] <0.4624.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.4640.0> exit with reason killed in context child_terminated
2016-04-10 22:35:50.109 [error] <0.4624.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.4640.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:35:50.110 [error] <0.4620.0> CRASH REPORT Process <0.4620.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:35:50.110 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:35:52.154 [info] <0.4696.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.4696.0>
2016-04-10 22:35:52.157 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:35:52.192 [error] <0.4687.0> CRASH REPORT Process <0.4687.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:35:52.192 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:35:54.286 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:35:54.299 [info] <0.1793.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.1793.0>
2016-04-10 22:35:54.309 [info] <0.7.0> Application mnesia2 started on node 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:35:54.296 [info] <0.4788.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.4788.0>
2016-04-10 22:35:54.602 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:35:55.603 [error] <0.1846.0> gen_server <0.1846.0> terminated with reason: killed
2016-04-10 22:35:55.604 [error] <0.1846.0> CRASH REPORT Process <0.1846.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:35:55.604 [error] <0.1784.0> CRASH REPORT Process <0.1784.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:35:55.604 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:35:57.638 [info] <0.1862.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.1862.0>
2016-04-10 22:35:57.649 [info] <0.7.0> Application mnesia2 started on node 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:35:58.652 [error] <0.4852.0> gen_server <0.4852.0> terminated with reason: killed
2016-04-10 22:35:58.652 [error] <0.4852.0> CRASH REPORT Process <0.4852.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:35:58.653 [error] <0.4779.0> CRASH REPORT Process <0.4779.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:35:58.653 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:35:59.709 [error] <0.1853.0> CRASH REPORT Process <0.1853.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:35:59.709 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:00.803 [info] <0.4895.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.4895.0>
2016-04-10 22:36:00.806 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:36:00.827 [error] <0.4886.0> CRASH REPORT Process <0.4886.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:00.813 [info] <0.1943.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.1943.0>
2016-04-10 22:36:00.818 [info] <0.7.0> Application mnesia2 started on node 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:36:00.819 [error] <0.1934.0> CRASH REPORT Process <0.1934.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:00.827 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:00.881 [info] <0.4970.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.4970.0>
2016-04-10 22:36:00.819 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:06.899 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:36:06.962 [info] <0.5094.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.5094.0>
2016-04-10 22:36:06.972 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:36:06.953 [info] <0.2013.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.2013.0>
2016-04-10 22:36:06.955 [info] <0.7.0> Application mnesia2 started on node 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:36:19.763 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:36:19.762 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:36:20.904 [info] <0.2135.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.2135.0>
2016-04-10 22:36:20.912 [info] <0.7.0> Application mnesia2 started on node 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:36:20.966 [error] <0.2187.0> gen_server <0.2187.0> terminated with reason: killed
2016-04-10 22:36:20.966 [error] <0.2187.0> CRASH REPORT Process <0.2187.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:20.967 [error] <0.2126.0> CRASH REPORT Process <0.2126.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:20.884 [info] <0.5225.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.5225.0>
2016-04-10 22:36:20.887 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:36:20.989 [error] <0.5216.0> CRASH REPORT Process <0.5216.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:20.989 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:21.021 [info] <0.5313.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.5313.0>
2016-04-10 22:36:21.025 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:36:21.807 [error] <0.5384.0> gen_server <0.5384.0> terminated with reason: killed
2016-04-10 22:36:21.807 [error] <0.5384.0> CRASH REPORT Process <0.5384.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:21.808 [error] <0.5304.0> CRASH REPORT Process <0.5304.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:21.808 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:20.967 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:21.289 [info] <0.2223.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.2223.0>
2016-04-10 22:36:21.295 [info] <0.7.0> Application mnesia2 started on node 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:36:22.942 [error] <0.2214.0> CRASH REPORT Process <0.2214.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:22.942 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:24.015 [info] <0.2326.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.2326.0>
2016-04-10 22:36:24.022 [info] <0.7.0> Application mnesia2 started on node 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:36:24.034 [error] <0.2337.0> gen_server <0.2337.0> terminated with reason: killed
2016-04-10 22:36:24.005 [info] <0.5436.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.5436.0>
2016-04-10 22:36:24.008 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:36:24.035 [error] <0.5432.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-10 22:36:24.035 [error] <0.5435.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-10 22:36:24.035 [error] <0.5435.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:24.036 [error] <0.5430.0> Mnesia2('test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'): ** ERROR ** mnesia2_event got unexpected event: {'EXIT',<0.5433.0>,killed}

2016-04-10 22:36:24.036 [error] <0.5430.0> CRASH REPORT Process mnesia2_event with 0 neighbours exited with reason: killed in gen_event:terminate_server/4 line 315
2016-04-10 22:36:24.034 [error] <0.2337.0> CRASH REPORT Process <0.2337.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:24.043 [error] <0.5427.0> CRASH REPORT Process <0.5427.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:24.035 [error] <0.2317.0> CRASH REPORT Process <0.2317.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:24.043 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:24.035 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:26.357 [info] <0.2402.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.2402.0>
2016-04-10 22:36:26.367 [info] <0.7.0> Application mnesia2 started on node 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:36:26.372 [error] <0.2393.0> CRASH REPORT Process <0.2393.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:26.348 [info] <0.5547.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.5547.0>
2016-04-10 22:36:26.350 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:36:26.374 [error] <0.5538.0> CRASH REPORT Process <0.5538.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:26.374 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:26.372 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:28.409 [info] <0.5628.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.5628.0>
2016-04-10 22:36:28.432 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:36:28.464 [error] <0.5665.0> gen_server <0.5665.0> terminated with reason: killed
2016-04-10 22:36:28.465 [error] <0.5665.0> CRASH REPORT Process <0.5665.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:28.465 [error] <0.5618.0> CRASH REPORT Process <0.5618.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:28.399 [info] <0.2461.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.2461.0>
2016-04-10 22:36:28.401 [info] <0.7.0> Application mnesia2 started on node 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:36:28.465 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:29.890 [error] <0.2452.0> CRASH REPORT Process <0.2452.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:29.890 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:30.988 [info] <0.2550.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.2550.0>
2016-04-10 22:36:30.998 [info] <0.7.0> Application mnesia2 started on node 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:36:31.325 [error] <0.2601.0> gen_server <0.2601.0> terminated with reason: killed
2016-04-10 22:36:30.982 [info] <0.5752.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.5752.0>
2016-04-10 22:36:30.984 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:36:31.326 [error] <0.5797.0> gen_server <0.5797.0> terminated with reason: killed
2016-04-10 22:36:31.326 [error] <0.5797.0> CRASH REPORT Process <0.5797.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:31.325 [error] <0.2601.0> CRASH REPORT Process <0.2601.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:31.327 [error] <0.5743.0> CRASH REPORT Process <0.5743.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:31.325 [error] <0.2562.0> gen_server <0.2562.0> terminated with reason: killed
2016-04-10 22:36:31.325 [error] <0.2562.0> CRASH REPORT Process <0.2562.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:31.326 [error] <0.2541.0> CRASH REPORT Process <0.2541.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:31.327 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:31.230 [info] <0.7.0> Application lager started on node 'd1322911o1322917n1322920@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:36:31.231 [info] <0.7.0> Application poolgirl started on node 'd1322911o1322917n1322920@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:36:31.257 [info] <0.102.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322911o1322917n1322920@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.102.0>
2016-04-10 22:36:31.275 [info] <0.7.0> Application mnesia2 started on node 'd1322911o1322917n1322920@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:36:31.326 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:33.561 [info] <0.2631.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.2631.0>
2016-04-10 22:36:33.616 [info] <0.7.0> Application mnesia2 started on node 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:36:33.659 [error] <0.2640.0> gen_server <0.2640.0> terminated with reason: killed
2016-04-10 22:36:33.508 [info] <0.5847.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.5847.0>
2016-04-10 22:36:33.511 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:36:33.661 [error] <0.5911.0> gen_server <0.5911.0> terminated with reason: killed
2016-04-10 22:36:33.661 [error] <0.5911.0> CRASH REPORT Process <0.5911.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:33.659 [error] <0.2640.0> CRASH REPORT Process <0.2640.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:33.662 [error] <0.5838.0> CRASH REPORT Process <0.5838.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:33.662 [error] <0.2622.0> CRASH REPORT Process <0.2622.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:33.662 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:33.662 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:35.756 [info] <0.5941.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.5941.0>
2016-04-10 22:36:35.760 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:36:35.784 [error] <0.5985.0> gen_server <0.5985.0> terminated with reason: killed
2016-04-10 22:36:35.762 [info] <0.2701.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.2701.0>
2016-04-10 22:36:35.772 [info] <0.7.0> Application mnesia2 started on node 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:36:35.788 [error] <0.2692.0> CRASH REPORT Process <0.2692.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:35.784 [error] <0.5985.0> CRASH REPORT Process <0.5985.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:35.786 [error] <0.5932.0> CRASH REPORT Process <0.5932.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:35.786 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:35.788 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:37.928 [info] <0.2776.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.2776.0>
2016-04-10 22:36:37.936 [info] <0.7.0> Application mnesia2 started on node 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:36:37.941 [error] <0.2828.0> gen_server <0.2828.0> terminated with reason: killed
2016-04-10 22:36:37.941 [error] <0.2828.0> CRASH REPORT Process <0.2828.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:37.942 [error] <0.2767.0> CRASH REPORT Process <0.2767.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:37.917 [info] <0.6027.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.6027.0>
2016-04-10 22:36:37.920 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:36:37.942 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:38.972 [error] <0.6018.0> CRASH REPORT Process <0.6018.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:38.972 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:41.006 [info] <0.2846.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.2846.0>
2016-04-10 22:36:41.008 [info] <0.7.0> Application mnesia2 started on node 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:36:46.046 [info] <0.6105.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.6105.0>
2016-04-10 22:36:46.063 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:36:46.074 [error] <0.6168.0> gen_server <0.6168.0> terminated with reason: killed
2016-04-10 22:36:46.071 [error] <0.2913.0> gen_server <0.2913.0> terminated with reason: killed
2016-04-10 22:36:46.074 [error] <0.6168.0> CRASH REPORT Process <0.6168.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:46.079 [error] <0.6096.0> CRASH REPORT Process <0.6096.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:46.071 [error] <0.2913.0> CRASH REPORT Process <0.2913.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:46.072 [error] <0.2837.0> CRASH REPORT Process <0.2837.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:46.080 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:46.072 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:49.327 [info] <0.2945.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.2945.0>
2016-04-10 22:36:49.337 [info] <0.7.0> Application mnesia2 started on node 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:36:49.648 [error] <0.2940.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.2958.0> exit with reason killed in context child_terminated
2016-04-10 22:36:49.189 [warning] <0.6.0> lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:36:49.348 [info] <0.192.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322911o1322917n1322920@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.192.0>
2016-04-10 22:36:49.420 [info] <0.7.0> Application mnesia2 started on node 'd1322911o1322917n1322920@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:36:49.304 [info] <0.6215.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.6215.0>
2016-04-10 22:36:49.306 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:36:49.648 [error] <0.2940.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.2958.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:36:49.649 [error] <0.2936.0> CRASH REPORT Process <0.2936.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:51.281 [error] <0.6318.0> gen_server <0.6318.0> terminated with reason: killed
2016-04-10 22:36:51.303 [error] <0.277.0> gen_server <0.277.0> terminated with reason: killed
2016-04-10 22:36:51.281 [error] <0.6318.0> CRASH REPORT Process <0.6318.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:51.303 [error] <0.277.0> CRASH REPORT Process <0.277.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:51.281 [error] <0.6302.0> gen_server <0.6302.0> terminated with reason: killed
2016-04-10 22:36:51.304 [error] <0.183.0> CRASH REPORT Process <0.183.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:51.281 [error] <0.6302.0> CRASH REPORT Process <0.6302.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:51.281 [error] <0.6279.0> gen_server <0.6279.0> terminated with reason: killed
2016-04-10 22:36:51.281 [error] <0.6279.0> CRASH REPORT Process <0.6279.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:51.282 [error] <0.6206.0> CRASH REPORT Process <0.6206.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:49.649 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:51.106 [info] <0.3036.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.3036.0>
2016-04-10 22:36:51.226 [info] <0.7.0> Application mnesia2 started on node 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:36:51.336 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:36:51.383 [info] <0.3131.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.3131.0>
2016-04-10 22:36:51.384 [info] <0.7.0> Application mnesia2 started on node 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:36:51.282 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:51.494 [info] <0.6337.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.6337.0>
2016-04-10 22:36:51.505 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:36:51.304 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:51.463 [info] <0.296.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322911o1322917n1322920@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.296.0>
2016-04-10 22:36:51.767 [info] <0.7.0> Application mnesia2 started on node 'd1322911o1322917n1322920@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:36:52.282 [error] <0.370.0> gen_server <0.370.0> terminated with reason: killed
2016-04-10 22:36:52.282 [error] <0.370.0> CRASH REPORT Process <0.370.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:52.282 [error] <0.362.0> gen_server <0.362.0> terminated with reason: killed
2016-04-10 22:36:52.282 [error] <0.362.0> CRASH REPORT Process <0.362.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:52.283 [error] <0.287.0> CRASH REPORT Process <0.287.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:52.283 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:52.322 [info] <0.395.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322911o1322917n1322920@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.395.0>
2016-04-10 22:36:52.323 [info] <0.7.0> Application mnesia2 started on node 'd1322911o1322917n1322920@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:36:54.448 [error] <0.6433.0> gen_server <0.6433.0> terminated with reason: killed
2016-04-10 22:36:54.448 [error] <0.6433.0> CRASH REPORT Process <0.6433.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:54.448 [error] <0.6402.0> gen_server <0.6402.0> terminated with reason: killed
2016-04-10 22:36:54.469 [error] <0.3223.0> gen_server <0.3223.0> terminated with reason: killed
2016-04-10 22:36:54.448 [error] <0.6402.0> CRASH REPORT Process <0.6402.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:54.469 [error] <0.3223.0> CRASH REPORT Process <0.3223.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:54.449 [error] <0.6328.0> CRASH REPORT Process <0.6328.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:54.470 [error] <0.3122.0> CRASH REPORT Process <0.3122.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:54.449 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:55.308 [info] <0.6452.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.6452.0>
2016-04-10 22:36:54.470 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:55.333 [info] <0.3244.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.3244.0>
2016-04-10 22:36:55.352 [info] <0.7.0> Application mnesia2 started on node 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:36:54.520 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:36:54.820 [info] <0.501.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322911o1322917n1322920@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.501.0>
2016-04-10 22:36:54.822 [info] <0.7.0> Application mnesia2 started on node 'd1322911o1322917n1322920@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:36:56.131 [error] <0.575.0> gen_server <0.575.0> terminated with reason: killed
2016-04-10 22:36:56.132 [error] <0.575.0> CRASH REPORT Process <0.575.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:56.132 [error] <0.492.0> CRASH REPORT Process <0.492.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:55.616 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:36:56.234 [error] <0.6541.0> gen_server <0.6541.0> terminated with reason: killed
2016-04-10 22:36:56.234 [error] <0.6541.0> CRASH REPORT Process <0.6541.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:56.234 [error] <0.6546.0> gen_server <0.6546.0> terminated with reason: killed
2016-04-10 22:36:56.255 [error] <0.3331.0> gen_server <0.3331.0> terminated with reason: killed
2016-04-10 22:36:56.234 [error] <0.6546.0> CRASH REPORT Process <0.6546.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:56.234 [error] <0.6523.0> gen_server <0.6523.0> terminated with reason: killed
2016-04-10 22:36:56.255 [error] <0.3331.0> CRASH REPORT Process <0.3331.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:56.234 [error] <0.6523.0> CRASH REPORT Process <0.6523.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:56.256 [error] <0.3235.0> CRASH REPORT Process <0.3235.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:56.235 [error] <0.6443.0> CRASH REPORT Process <0.6443.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:56.235 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:56.343 [info] <0.6565.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.6565.0>
2016-04-10 22:36:56.356 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:36:56.256 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:56.345 [info] <0.3352.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.3352.0>
2016-04-10 22:36:56.372 [info] <0.7.0> Application mnesia2 started on node 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:36:56.901 [error] <0.3343.0> CRASH REPORT Process <0.3343.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:56.902 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:56.939 [info] <0.3448.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.3448.0>
2016-04-10 22:36:57.003 [warning] <0.6.0> lager_error_logger_h dropped 31 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:36:57.003 [error] <0.3506.0> gen_server <0.3506.0> terminated with reason: killed
2016-04-10 22:36:57.003 [error] <0.3506.0> CRASH REPORT Process <0.3506.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:57.004 [error] <0.3496.0> gen_server <0.3496.0> terminated with reason: killed
2016-04-10 22:36:57.004 [error] <0.3496.0> CRASH REPORT Process <0.3496.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:57.004 [error] <0.3460.0> gen_server <0.3460.0> terminated with reason: killed
2016-04-10 22:36:57.004 [error] <0.3460.0> CRASH REPORT Process <0.3460.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:57.004 [error] <0.3439.0> CRASH REPORT Process <0.3439.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:56.132 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:56.161 [info] <0.600.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322911o1322917n1322920@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.600.0>
2016-04-10 22:36:56.163 [info] <0.7.0> Application mnesia2 started on node 'd1322911o1322917n1322920@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:36:56.284 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:36:56.310 [info] <0.701.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322911o1322917n1322920@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.701.0>
2016-04-10 22:36:57.004 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:58.107 [error] <0.6677.0> gen_server <0.6677.0> terminated with reason: killed
2016-04-10 22:36:58.028 [info] <0.3526.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.3526.0>
2016-04-10 22:36:58.039 [info] <0.7.0> Application mnesia2 started on node 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:36:58.110 [error] <0.3539.0> gen_server <0.3539.0> terminated with reason: killed
2016-04-10 22:36:58.111 [error] <0.696.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.716.0> exit with reason killed in context child_terminated
2016-04-10 22:36:58.107 [error] <0.6677.0> CRASH REPORT Process <0.6677.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:58.110 [error] <0.3539.0> CRASH REPORT Process <0.3539.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:58.111 [error] <0.696.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.716.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:36:58.110 [error] <0.3544.0> gen_server <0.3544.0> terminated with reason: killed
2016-04-10 22:36:58.107 [error] <0.6615.0> gen_server <0.6615.0> terminated with reason: killed
2016-04-10 22:36:58.112 [error] <0.768.0> gen_server <0.768.0> terminated with reason: killed
2016-04-10 22:36:58.110 [error] <0.3544.0> CRASH REPORT Process <0.3544.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:58.112 [error] <0.768.0> CRASH REPORT Process <0.768.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:58.108 [error] <0.6615.0> CRASH REPORT Process <0.6615.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:58.111 [error] <0.3517.0> CRASH REPORT Process <0.3517.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:58.119 [error] <0.824.0> gen_server <0.824.0> terminated with reason: killed
2016-04-10 22:36:58.121 [error] <0.6556.0> CRASH REPORT Process <0.6556.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:58.119 [error] <0.824.0> CRASH REPORT Process <0.824.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:58.120 [error] <0.692.0> CRASH REPORT Process <0.692.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:58.111 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:58.264 [info] <0.3604.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.3604.0>
2016-04-10 22:36:58.358 [info] <0.3699.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.3699.0>
2016-04-10 22:36:58.524 [info] <0.3789.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.3789.0>
2016-04-10 22:36:58.636 [info] <0.3889.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.3889.0>
2016-04-10 22:36:58.121 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:58.256 [info] <0.6709.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.6709.0>
2016-04-10 22:36:58.260 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:36:58.633 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:36:58.120 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:59.223 [warning] <0.6.0> lager_error_logger_h dropped 41 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:36:59.223 [error] <0.3944.0> gen_server <0.3944.0> terminated with reason: killed
2016-04-10 22:36:59.223 [error] <0.3944.0> CRASH REPORT Process <0.3944.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:59.223 [error] <0.3880.0> CRASH REPORT Process <0.3880.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:59.223 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:59.783 [info] <0.3971.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.3971.0>
2016-04-10 22:36:59.815 [info] <0.7.0> Application mnesia2 started on node 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:36:59.862 [error] <0.4022.0> gen_server <0.4022.0> terminated with reason: killed
2016-04-10 22:36:59.862 [error] <0.4022.0> CRASH REPORT Process <0.4022.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:59.166 [info] <0.6822.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.6822.0>
2016-04-10 22:36:59.190 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:36:59.222 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:36:59.265 [info] <0.6905.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.6905.0>
2016-04-10 22:36:59.947 [info] <0.7006.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.7006.0>
2016-04-10 22:36:59.959 [info] <0.4063.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.4063.0>
2016-04-10 22:37:00.253 [warning] <0.6.0> lager_error_logger_h dropped 5 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:37:00.256 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:37:00.365 [error] <0.6997.0> CRASH REPORT Process <0.6997.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:59.953 [info] <0.852.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322911o1322917n1322920@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.852.0>
2016-04-10 22:37:00.262 [info] <0.7.0> Application mnesia2 started on node 'd1322911o1322917n1322920@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:37:00.369 [error] <0.843.0> CRASH REPORT Process <0.843.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:37:00.368 [error] <0.4123.0> gen_server <0.4123.0> terminated with reason: killed
2016-04-10 22:37:00.368 [error] <0.4123.0> CRASH REPORT Process <0.4123.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:37:00.369 [error] <0.4054.0> CRASH REPORT Process <0.4054.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:37:00.369 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:37:00.392 [info] <0.4155.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.4155.0>
2016-04-10 22:37:00.394 [info] <0.7.0> Application mnesia2 started on node 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:37:00.464 [error] <0.4199.0> gen_server <0.4199.0> terminated with reason: killed
2016-04-10 22:37:00.369 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:37:00.399 [info] <0.958.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322911o1322917n1322920@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.958.0>
2016-04-10 22:37:00.402 [info] <0.7.0> Application mnesia2 started on node 'd1322911o1322917n1322920@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:37:00.468 [error] <0.949.0> CRASH REPORT Process <0.949.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:37:00.464 [error] <0.4199.0> CRASH REPORT Process <0.4199.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:37:00.468 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:37:00.491 [info] <0.1037.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322911o1322917n1322920@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.1037.0>
2016-04-10 22:37:00.366 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:37:00.438 [info] <0.7118.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.7118.0>
2016-04-10 22:37:00.549 [info] <0.7211.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.7211.0>
2016-04-10 22:37:00.495 [info] <0.4233.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.4233.0>
2016-04-10 22:37:10.562 [warning] <0.6.0> lager_error_logger_h dropped 20 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:37:10.562 [error] <0.7204.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at undefined exit with reason killed in context start_error
2016-04-10 22:37:10.562 [error] <0.7207.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-10 22:37:10.562 [error] <0.7210.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-10 22:37:10.562 [error] <0.7210.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:37:10.562 [error] <0.7230.0> gen_server mnesia2_snmp_sup terminated with reason: killed
2016-04-10 22:37:10.562 [error] <0.7230.0> CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:37:10.562 [error] <0.7208.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-10 22:37:10.562 [error] <0.7208.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:37:10.563 [error] <0.7202.0> CRASH REPORT Process <0.7202.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}} in application_master:init/4 line 134
2016-04-10 22:37:10.563 [error] <0.7207.0> CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:37:10.679 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:37:10.679 [error] <0.4224.0> CRASH REPORT Process <0.4224.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:37:10.682 [error] <0.1081.0> gen_server <0.1081.0> terminated with reason: killed
2016-04-10 22:37:10.682 [error] <0.1081.0> CRASH REPORT Process <0.1081.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:37:10.682 [error] <0.1086.0> gen_server <0.1086.0> terminated with reason: killed
2016-04-10 22:37:10.682 [error] <0.1086.0> CRASH REPORT Process <0.1086.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:37:10.682 [error] <0.1028.0> CRASH REPORT Process <0.1028.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:37:10.563 [info] <0.7.0> Application mnesia2 exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}}
2016-04-10 22:37:10.679 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:37:10.682 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:37:13.132 [info] <0.7320.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.7320.0>
2016-04-10 22:37:13.136 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:37:19.163 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:19.475 [info] <0.7456.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.7456.0>
2016-04-10 22:37:19.486 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:37:19.474 [info] <0.4323.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.4323.0>
2016-04-10 22:37:19.501 [info] <0.7.0> Application mnesia2 started on node 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:37:19.476 [info] <0.1134.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322911o1322917n1322920@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.1134.0>
2016-04-10 22:37:19.541 [info] <0.7.0> Application mnesia2 started on node 'd1322911o1322917n1322920@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:37:25.886 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:26.013 [info] <0.4438.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.4438.0>
2016-04-10 22:37:26.026 [info] <0.7.0> Application mnesia2 started on node 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:37:25.888 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:25.998 [info] <0.7585.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.7585.0>
2016-04-10 22:37:26.001 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:37:25.910 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:26.005 [info] <0.1248.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322911o1322917n1322920@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.1248.0>
2016-04-10 22:37:26.055 [info] <0.7.0> Application mnesia2 started on node 'd1322911o1322917n1322920@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:37:32.196 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:32.354 [info] <0.7715.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.7715.0>
2016-04-10 22:37:32.660 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:37:32.192 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:32.365 [info] <0.1364.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322911o1322917n1322920@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.1364.0>
2016-04-10 22:37:32.376 [info] <0.7.0> Application mnesia2 started on node 'd1322911o1322917n1322920@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:37:32.200 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:32.356 [info] <0.4550.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.4550.0>
2016-04-10 22:37:32.381 [info] <0.7.0> Application mnesia2 started on node 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:37:52.368 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:52.596 [info] <0.2486.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322911o1322917n1322920@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.2486.0>
2016-04-10 22:37:52.618 [info] <0.7.0> Application mnesia2 started on node 'd1322911o1322917n1322920@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:37:52.370 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:52.586 [info] <0.5677.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.5677.0>
2016-04-10 22:37:52.632 [info] <0.7.0> Application mnesia2 started on node 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:37:52.372 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:52.582 [info] <0.8854.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.8854.0>
2016-04-10 22:37:52.889 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:37:59.439 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:59.544 [info] <0.8995.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.8995.0>
2016-04-10 22:37:59.547 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:37:59.442 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:59.553 [info] <0.2611.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322911o1322917n1322920@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.2611.0>
2016-04-10 22:37:59.573 [info] <0.7.0> Application mnesia2 started on node 'd1322911o1322917n1322920@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:37:59.437 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:59.552 [info] <0.5802.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.5802.0>
2016-04-10 22:37:59.857 [info] <0.7.0> Application mnesia2 started on node 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:38:06.280 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:38:06.433 [info] <0.7274.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.7274.0>
2016-04-10 22:38:06.744 [info] <0.7.0> Application mnesia2 started on node 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:38:06.281 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:38:06.440 [info] <0.4081.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322911o1322917n1322920@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.4081.0>
2016-04-10 22:38:06.446 [info] <0.7.0> Application mnesia2 started on node 'd1322911o1322917n1322920@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:38:06.283 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:38:06.411 [info] <0.10475.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.10475.0>
2016-04-10 22:38:06.415 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:38:13.026 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:38:13.161 [info] <0.12185.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.12185.0>
2016-04-10 22:38:13.163 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:38:13.035 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:38:13.180 [info] <0.8345.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.8345.0>
2016-04-10 22:38:13.186 [info] <0.7.0> Application mnesia2 started on node 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:38:13.029 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:38:13.178 [info] <0.4688.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322911o1322917n1322920@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.4688.0>
2016-04-10 22:38:13.482 [info] <0.7.0> Application mnesia2 started on node 'd1322911o1322917n1322920@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:38:19.660 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:38:19.804 [info] <0.4804.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322911o1322917n1322920@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.4804.0>
2016-04-10 22:38:20.108 [info] <0.7.0> Application mnesia2 started on node 'd1322911o1322917n1322920@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:38:19.663 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:38:19.805 [info] <0.12314.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.12314.0>
2016-04-10 22:38:20.125 [info] <0.7.0> Application mnesia2 started on node 'test3810@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:38:19.669 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:38:19.820 [info] <0.9139.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12', <0.9139.0>
2016-04-10 22:38:19.843 [info] <0.7.0> Application mnesia2 started on node 'd1322936o1322928n1322928@testing-worker-linux-docker-571fe1d0-3352-linux-12'
2016-04-10 22:38:26.401 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:38:26.377 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:38:26.378 [info] <0.7.0> Application mnesia2 exited with reason: stopped
