2016-04-10 22:45:19.403 [info] <0.7.0> Application lager started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:45:19.404 [info] <0.7.0> Application poolgirl started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:45:19.439 [info] <0.495.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.495.0>
2016-04-10 22:45:20.109 [info] <0.563.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.563.0>
2016-04-10 22:45:20.114 [info] <0.7.0> Application mnesia2 started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:45:20.655 [error] <0.554.0> CRASH REPORT Process <0.554.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:45:20.655 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:45:20.800 [info] <0.673.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.673.0>
2016-04-10 22:45:21.193 [warning] <0.6.0> lager_error_logger_h dropped 15 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:45:21.350 [error] <0.730.0> gen_server <0.730.0> terminated with reason: killed
2016-04-10 22:45:21.350 [error] <0.730.0> CRASH REPORT Process <0.730.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:45:21.097 [info] <0.7.0> Application lager started on node 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:45:21.097 [info] <0.7.0> Application poolgirl started on node 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:45:21.173 [info] <0.100.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.100.0>
2016-04-10 22:45:21.190 [info] <0.7.0> Application mnesia2 started on node 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:45:21.351 [error] <0.93.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.95.0> exit with reason killed in context child_terminated
2016-04-10 22:45:21.351 [error] <0.664.0> CRASH REPORT Process <0.664.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:45:21.351 [error] <0.93.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.95.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:45:21.351 [error] <0.97.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-10 22:45:21.351 [error] <0.97.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:45:21.351 [error] <0.96.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-10 22:45:21.351 [error] <0.96.0> CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:45:21.351 [error] <0.115.0> gen_server mnesia2_snmp_sup terminated with reason: killed
2016-04-10 22:45:21.352 [error] <0.115.0> CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:45:21.351 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:45:21.428 [info] <0.799.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.799.0>
2016-04-10 22:45:21.434 [info] <0.7.0> Application mnesia2 started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:45:21.685 [error] <0.793.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): ** ERROR ** (ignoring core) ** FATAL ** A fallback is installed and Mnesia2 must be restarted. Forcing shutdown after mnesia2_down from 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10'...

2016-04-10 22:45:21.354 [info] <0.7.0> Application mnesia2 exited with reason: shutdown
2016-04-10 22:45:21.446 [info] <0.216.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.216.0>
2016-04-10 22:45:21.762 [info] <0.369.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.369.0>
2016-04-10 22:45:21.858 [info] <0.459.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.459.0>
2016-04-10 22:45:22.656 [warning] <0.6.0> lager_error_logger_h dropped 29 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:45:22.656 [error] <0.515.0> gen_server <0.515.0> terminated with reason: killed
2016-04-10 22:45:21.742 [info] <0.927.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.927.0>
2016-04-10 22:45:21.837 [info] <0.1027.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.1027.0>
2016-04-10 22:45:22.657 [warning] <0.6.0> lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:45:22.657 [error] <0.1018.0> CRASH REPORT Process <0.1018.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:45:22.656 [error] <0.515.0> CRASH REPORT Process <0.515.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:45:22.656 [error] <0.450.0> CRASH REPORT Process <0.450.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:45:22.658 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:45:22.721 [info] <0.1150.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.1150.0>
2016-04-10 22:45:22.724 [info] <0.7.0> Application mnesia2 started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:45:22.912 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:45:22.931 [info] <0.1262.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.1262.0>
2016-04-10 22:45:23.461 [warning] <0.6.0> lager_error_logger_h dropped 20 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:45:23.461 [error] <0.1297.0> gen_server <0.1297.0> terminated with reason: killed
2016-04-10 22:45:22.656 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:45:22.756 [info] <0.548.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.548.0>
2016-04-10 22:45:22.763 [info] <0.7.0> Application mnesia2 started on node 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:45:23.463 [error] <0.541.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.543.0> exit with reason killed in context child_terminated
2016-04-10 22:45:23.462 [error] <0.1297.0> CRASH REPORT Process <0.1297.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:45:23.463 [error] <0.541.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.543.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:45:23.462 [error] <0.1253.0> CRASH REPORT Process <0.1253.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:45:23.463 [error] <0.547.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-10 22:45:23.463 [error] <0.547.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:45:23.464 [error] <0.544.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-10 22:45:23.465 [info] <0.7.0> Application mnesia2 exited with reason: shutdown
2016-04-10 22:45:23.462 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:45:23.624 [info] <0.1495.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.1495.0>
2016-04-10 22:45:23.628 [info] <0.7.0> Application mnesia2 started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:45:23.681 [info] <0.763.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.763.0>
2016-04-10 22:45:23.692 [info] <0.7.0> Application mnesia2 started on node 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:45:23.805 [error] <0.803.0> gen_server <0.803.0> terminated with reason: killed
2016-04-10 22:45:23.808 [error] <0.1551.0> gen_server <0.1551.0> terminated with reason: killed
2016-04-10 22:45:23.805 [error] <0.803.0> CRASH REPORT Process <0.803.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:45:23.808 [error] <0.1551.0> CRASH REPORT Process <0.1551.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:45:23.873 [info] <0.1609.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.1609.0>
2016-04-10 22:45:24.081 [warning] <0.6.0> lager_error_logger_h dropped 4 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:45:24.081 [error] <0.1663.0> gen_server <0.1663.0> terminated with reason: killed
2016-04-10 22:45:23.882 [info] <0.862.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.862.0>
2016-04-10 22:45:24.077 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:45:24.077 [error] <0.905.0> gen_server <0.905.0> terminated with reason: killed
2016-04-10 22:45:24.082 [error] <0.1663.0> CRASH REPORT Process <0.1663.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:45:24.077 [error] <0.905.0> CRASH REPORT Process <0.905.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:45:24.084 [error] <0.1600.0> CRASH REPORT Process <0.1600.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:45:24.078 [error] <0.853.0> CRASH REPORT Process <0.853.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:45:24.078 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:45:24.143 [info] <0.963.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.963.0>
2016-04-10 22:45:24.449 [info] <0.7.0> Application mnesia2 started on node 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:45:24.084 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:45:24.139 [info] <0.1725.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.1725.0>
2016-04-10 22:45:24.153 [info] <0.7.0> Application mnesia2 started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:45:24.693 [error] <0.1724.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-10 22:45:24.691 [error] <0.1017.0> gen_server <0.1017.0> terminated with reason: killed
2016-04-10 22:45:24.693 [error] <0.1724.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:45:24.691 [error] <0.1017.0> CRASH REPORT Process <0.1017.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:45:24.750 [info] <0.1851.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.1851.0>
2016-04-10 22:45:24.752 [info] <0.1071.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.1071.0>
2016-04-10 22:45:25.265 [error] <0.1126.0> gen_server <0.1126.0> terminated with reason: killed
2016-04-10 22:45:25.056 [warning] <0.6.0> lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:45:25.056 [info] <0.7.0> Application mnesia2 started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:45:25.269 [error] <0.1842.0> CRASH REPORT Process <0.1842.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:45:25.265 [error] <0.1126.0> CRASH REPORT Process <0.1126.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:45:25.266 [error] <0.1062.0> CRASH REPORT Process <0.1062.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:45:25.266 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:45:25.368 [info] <0.1171.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.1171.0>
2016-04-10 22:45:25.384 [info] <0.7.0> Application mnesia2 started on node 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:45:25.606 [error] <0.1212.0> gen_server <0.1212.0> terminated with reason: killed
2016-04-10 22:45:25.606 [error] <0.1212.0> CRASH REPORT Process <0.1212.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:45:25.673 [info] <0.1272.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.1272.0>
2016-04-10 22:45:25.269 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:45:25.345 [info] <0.1983.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.1983.0>
2016-04-10 22:45:25.662 [info] <0.2116.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.2116.0>
2016-04-10 22:45:26.000 [warning] <0.6.0> lager_error_logger_h dropped 9 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:45:26.020 [info] <0.2256.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.2256.0>
2016-04-10 22:45:26.024 [info] <0.7.0> Application mnesia2 started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:45:26.007 [warning] <0.6.0> lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:45:26.034 [info] <0.1380.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.1380.0>
2016-04-10 22:45:26.044 [info] <0.7.0> Application mnesia2 started on node 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:45:26.313 [error] <0.1371.0> CRASH REPORT Process <0.1371.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:45:26.317 [error] <0.2312.0> gen_server <0.2312.0> terminated with reason: killed
2016-04-10 22:45:26.317 [error] <0.2312.0> CRASH REPORT Process <0.2312.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:45:26.318 [error] <0.2247.0> CRASH REPORT Process <0.2247.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:45:26.313 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:45:26.405 [info] <0.1466.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.1466.0>
2016-04-10 22:45:26.699 [info] <0.1578.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.1578.0>
2016-04-10 22:45:26.319 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:45:26.396 [info] <0.2387.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.2387.0>
2016-04-10 22:45:26.698 [info] <0.2519.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.2519.0>
2016-04-10 22:45:27.002 [warning] <0.6.0> lager_error_logger_h dropped 23 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:45:27.005 [info] <0.7.0> Application mnesia2 started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:45:27.184 [error] <0.2573.0> gen_server <0.2573.0> terminated with reason: killed
2016-04-10 22:45:27.181 [error] <0.1632.0> gen_server <0.1632.0> terminated with reason: killed
2016-04-10 22:45:27.184 [error] <0.2573.0> CRASH REPORT Process <0.2573.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:45:27.181 [error] <0.1632.0> CRASH REPORT Process <0.1632.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:45:27.185 [error] <0.2510.0> CRASH REPORT Process <0.2510.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:45:27.182 [error] <0.1569.0> CRASH REPORT Process <0.1569.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:45:27.185 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:45:27.251 [info] <0.2642.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.2642.0>
2016-04-10 22:45:27.182 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:45:27.255 [info] <0.1667.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.1667.0>
2016-04-10 22:45:27.281 [info] <0.7.0> Application mnesia2 started on node 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:45:27.643 [error] <0.1720.0> gen_server <0.1720.0> terminated with reason: killed
2016-04-10 22:45:27.643 [error] <0.1720.0> CRASH REPORT Process <0.1720.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:45:27.925 [info] <0.2771.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.2771.0>
2016-04-10 22:45:28.006 [warning] <0.6.0> lager_error_logger_h dropped 19 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:45:28.031 [info] <0.2865.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.2865.0>
2016-04-10 22:45:28.035 [info] <0.7.0> Application mnesia2 started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:45:28.044 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:45:29.299 [info] <0.2975.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.2975.0>
2016-04-10 22:45:29.302 [info] <0.7.0> Application mnesia2 started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:45:30.629 [error] <0.2966.0> CRASH REPORT Process <0.2966.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:45:30.629 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:45:32.731 [info] <0.3081.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.3081.0>
2016-04-10 22:45:32.734 [info] <0.7.0> Application mnesia2 started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:45:32.738 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:45:32.740 [info] <0.3129.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.3129.0>
2016-04-10 22:45:32.747 [info] <0.3177.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.3177.0>
2016-04-10 22:45:44.020 [info] <0.3249.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.3249.0>
2016-04-10 22:45:44.024 [info] <0.7.0> Application mnesia2 started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:45:44.059 [error] <0.3240.0> CRASH REPORT Process <0.3240.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:45:44.059 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:45:46.099 [info] <0.3332.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.3332.0>
2016-04-10 22:45:46.104 [info] <0.7.0> Application mnesia2 started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:45:46.125 [info] <0.3326.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Restore aborted. mnesia2_config_backup:open_read["NonExisting.FILE"] -> {enoent,error}

2016-04-10 22:45:46.126 [info] <0.3326.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Restore aborted. mnesia2_config_backup:open_read["/home/travis/build/lrascao/mnesia2/logs/ct_run.test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10.2016-04-10_22.44.46/Mnesia2.test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10/LATEST.LOG"] -> badarg

2016-04-10 22:45:46.128 [error] <0.3380.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_19,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_19,shutdown]}}}} ({error,{already_started,<0.3408.0>}})

2016-04-10 22:45:46.129 [error] <0.3382.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_21,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_21,shutdown]}}}} ({error,{already_started,<0.3408.0>}})

2016-04-10 22:45:46.129 [error] <0.3381.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_20,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_20,shutdown]}}}} ({error,{already_started,<0.3408.0>}})

2016-04-10 22:45:46.129 [error] <0.3384.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_23,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_23,shutdown]}}}} ({error,{already_started,<0.3408.0>}})

2016-04-10 22:45:46.129 [error] <0.3386.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_25,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_25,shutdown]}}}} ({error,{already_started,<0.3408.0>}})

2016-04-10 22:45:46.129 [error] <0.3385.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_24,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_24,shutdown]}}}} ({error,{already_started,<0.3408.0>}})

2016-04-10 22:45:46.129 [error] <0.3388.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_27,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_27,shutdown]}}}} ({error,{already_started,<0.3408.0>}})

2016-04-10 22:45:46.129 [error] <0.3390.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_29,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_29,shutdown]}}}} ({error,{already_started,<0.3408.0>}})

2016-04-10 22:45:48.225 [warning] <0.6.0> lager_error_logger_h dropped 8 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:45:48.226 [info] <0.3441.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): mnesia2_monitor starting: <0.3443.0>

2016-04-10 22:45:48.227 [info] <0.3441.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Mnesia2 debug level set to verbose
2016-04-10 22:45:48.228 [info] <0.3441.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): mnesia2_subscr starting: <0.3444.0>

2016-04-10 22:45:48.228 [info] <0.3441.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): mnesia2_locker starting: <0.3445.0>

2016-04-10 22:45:48.228 [info] <0.3441.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): mnesia2_recover starting: <0.3446.0>

2016-04-10 22:45:48.229 [info] <0.3441.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): mnesia2_tm starting: <0.3447.0>

2016-04-10 22:45:48.229 [info] <0.3441.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Schema initiated from: default

2016-04-10 22:45:48.229 [info] <0.3447.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.3447.0>
2016-04-10 22:45:48.230 [info] <0.3441.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): mnesia2_controller starting: <0.3450.0>

2016-04-10 22:45:48.230 [info] <0.3441.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): mnesia2_late_loader starting: <0.3451.0>

2016-04-10 22:45:48.231 [info] <0.3441.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Intend to load tables: []

2016-04-10 22:45:48.232 [info] <0.3441.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): mnesia2_tm_1 starting: <0.3453.0>

2016-04-10 22:45:48.232 [info] <0.3441.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): mnesia2_tm_2 starting: <0.3454.0>

2016-04-10 22:45:48.233 [info] <0.3441.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): mnesia2_tm_3 starting: <0.3455.0>

2016-04-10 22:45:50.259 [info] <0.3490.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): mnesia2_monitor starting: <0.3492.0>

2016-04-10 22:45:50.260 [info] <0.3490.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Version: "1.0.0"

2016-04-10 22:45:50.260 [info] <0.3490.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env access_module: mnesia2

2016-04-10 22:45:50.260 [info] <0.3490.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env auto_repair: true

2016-04-10 22:45:50.260 [info] <0.3490.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env backup_module: mnesia2_backup

2016-04-10 22:45:50.260 [info] <0.3490.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env debug: debug

2016-04-10 22:45:50.260 [info] <0.3490.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10.2016-04-10_22.44.46/Mnesia2.test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10"

2016-04-10 22:45:50.261 [info] <0.3490.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env dump_disc_copies_at_startup: true

2016-04-10 22:45:50.261 [info] <0.3490.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env dump_log_load_regulation: false

2016-04-10 22:45:50.262 [info] <0.3490.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env dump_log_time_threshold: 180000

2016-04-10 22:45:50.262 [info] <0.3490.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env dump_log_update_in_place: true

2016-04-10 22:45:50.263 [info] <0.3490.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env dump_log_write_threshold: 1000

2016-04-10 22:45:50.263 [info] <0.3490.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env event_module: mnesia2_event

2016-04-10 22:45:50.263 [info] <0.3490.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env extra_db_nodes: []

2016-04-10 22:45:50.264 [info] <0.3490.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env ignore_fallback_at_startup: false

2016-04-10 22:45:50.264 [info] <0.3490.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env fallback_error_function: {mnesia2,lkill}

2016-04-10 22:45:50.264 [info] <0.3490.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env max_wait_for_decision: infinity

2016-04-10 22:45:50.264 [info] <0.3490.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env schema_location: opt_disc

2016-04-10 22:45:50.264 [info] <0.3490.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env core_dir: false

2016-04-10 22:45:50.265 [info] <0.3496.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.3496.0>
2016-04-10 22:45:50.265 [info] <0.3490.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env pid_sort_order: false

2016-04-10 22:45:50.265 [info] <0.3490.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env no_table_loaders: 2

2016-04-10 22:45:50.266 [info] <0.3490.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env dc_dump_limit: 4

2016-04-10 22:45:50.266 [info] <0.3490.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env send_compressed: 0

2016-04-10 22:45:50.267 [info] <0.3490.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env send_max_packets: 20

2016-04-10 22:45:50.267 [info] <0.3490.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env send_max_transfer_size: 7500

2016-04-10 22:45:50.267 [info] <0.3490.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env async_dirty_buffer_size: 524288

2016-04-10 22:45:50.267 [info] <0.3490.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env async_dirty_max_buffer_file_size: 100000000

2016-04-10 22:45:50.267 [info] <0.3490.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env async_dirty_tx_backlog_threshold: 200000

2016-04-10 22:45:50.267 [info] <0.3490.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env async_dirty_buffer_min_runtime: 10000

2016-04-10 22:45:50.268 [info] <0.3490.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env async_dirty_buffer_drained_cutoff: 5

2016-04-10 22:45:50.268 [info] <0.3490.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Mnesia2 debug level set to debug
2016-04-10 22:45:50.269 [info] <0.3490.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): mnesia2_subscr starting: <0.3493.0>

2016-04-10 22:45:50.269 [info] <0.3490.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): mnesia2_locker starting: <0.3494.0>

2016-04-10 22:45:50.269 [info] <0.3490.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): mnesia2_recover starting: <0.3495.0>

2016-04-10 22:45:50.269 [info] <0.3490.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): mnesia2_tm starting: <0.3496.0>

2016-04-10 22:45:50.269 [info] <0.3490.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Schema initiated from: default

2016-04-10 22:45:50.270 [info] <0.3490.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): debug fun {mnesia2_tm,init} in ets mnesia2_debug does not exist, ignoring
2016-04-10 22:45:52.296 [warning] <0.6.0> lager_error_logger_h dropped 10 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:45:52.296 [info] <0.3544.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): mnesia2_monitor starting: <0.3546.0>

2016-04-10 22:45:52.296 [info] <0.3544.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Version: "1.0.0"

2016-04-10 22:45:52.296 [info] <0.3544.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env access_module: mnesia2

2016-04-10 22:45:52.296 [info] <0.3544.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env auto_repair: true

2016-04-10 22:45:52.297 [info] <0.3544.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env backup_module: mnesia2_backup

2016-04-10 22:45:52.297 [info] <0.3544.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env debug: trace

2016-04-10 22:45:52.298 [info] <0.3544.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10.2016-04-10_22.44.46/Mnesia2.test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10"

2016-04-10 22:45:52.298 [info] <0.3544.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env dump_disc_copies_at_startup: true

2016-04-10 22:45:52.298 [info] <0.3544.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env dump_log_load_regulation: false

2016-04-10 22:45:52.298 [info] <0.3544.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env dump_log_time_threshold: 180000

2016-04-10 22:45:52.299 [info] <0.3544.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env dump_log_update_in_place: true

2016-04-10 22:45:52.299 [info] <0.3544.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env dump_log_write_threshold: 1000

2016-04-10 22:45:52.299 [info] <0.3544.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env event_module: mnesia2_event

2016-04-10 22:45:52.299 [info] <0.3544.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env extra_db_nodes: []

2016-04-10 22:45:52.299 [info] <0.3544.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env ignore_fallback_at_startup: false

2016-04-10 22:45:52.299 [info] <0.3544.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env fallback_error_function: {mnesia2,lkill}

2016-04-10 22:45:52.299 [info] <0.3544.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env max_wait_for_decision: infinity

2016-04-10 22:45:52.300 [info] <0.3544.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env schema_location: opt_disc

2016-04-10 22:45:52.300 [info] <0.3544.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env core_dir: false

2016-04-10 22:45:52.300 [info] <0.3544.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env pid_sort_order: false

2016-04-10 22:45:52.300 [info] <0.3544.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env no_table_loaders: 2

2016-04-10 22:45:52.300 [info] <0.3544.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env dc_dump_limit: 4

2016-04-10 22:45:52.300 [info] <0.3544.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env send_compressed: 0

2016-04-10 22:45:52.301 [info] <0.3544.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env send_max_packets: 20

2016-04-10 22:45:52.301 [info] <0.3544.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env send_max_transfer_size: 7500

2016-04-10 22:45:52.301 [info] <0.3544.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env async_dirty_buffer_size: 524288

2016-04-10 22:45:52.302 [info] <0.3544.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env async_dirty_max_buffer_file_size: 100000000

2016-04-10 22:45:52.302 [info] <0.3550.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.3550.0>
2016-04-10 22:45:52.302 [info] <0.3544.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env async_dirty_tx_backlog_threshold: 200000

2016-04-10 22:45:52.302 [info] <0.3544.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env async_dirty_buffer_min_runtime: 10000

2016-04-10 22:45:52.302 [info] <0.3544.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env async_dirty_buffer_drained_cutoff: 5

2016-04-10 22:45:52.303 [info] <0.3544.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Mnesia2 debug level set to trace
2016-04-10 22:45:52.303 [info] <0.3544.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): mnesia2_subscr starting: <0.3547.0>

2016-04-10 22:45:52.304 [info] <0.3544.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): mnesia2_locker starting: <0.3548.0>

2016-04-10 22:45:52.304 [info] <0.3544.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): mnesia2_recover starting: <0.3549.0>

2016-04-10 22:45:52.304 [info] <0.3544.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): mnesia2_tm starting: <0.3550.0>

2016-04-10 22:45:52.305 [info] <0.3544.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Schema initiated from: default

2016-04-10 22:45:52.305 [info] <0.3544.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): debug fun {mnesia2_tm,init} in ets mnesia2_debug does not exist, ignoring
2016-04-10 22:45:52.305 [info] <0.3544.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): mnesia2_controller starting: <0.3553.0>

2016-04-10 22:45:52.305 [info] <0.3544.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): mnesia2_late_loader starting: <0.3554.0>

2016-04-10 22:45:52.311 [info] <0.3544.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Intend to load tables: []

2016-04-10 22:45:54.353 [warning] <0.6.0> lager_error_logger_h dropped 61 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:45:54.353 [info] <0.3622.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): mnesia2_monitor starting: <0.3624.0>

2016-04-10 22:45:54.354 [info] <0.3622.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Version: "1.0.0"

2016-04-10 22:45:54.354 [info] <0.3622.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env access_module: mnesia2

2016-04-10 22:45:54.355 [info] <0.3622.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env auto_repair: true

2016-04-10 22:45:54.355 [info] <0.3622.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env backup_module: mnesia2_backup

2016-04-10 22:45:54.355 [info] <0.3622.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env debug: debug

2016-04-10 22:45:54.356 [info] <0.3622.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10.2016-04-10_22.44.46/Mnesia2.test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10"

2016-04-10 22:45:54.356 [info] <0.3622.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env dump_disc_copies_at_startup: true

2016-04-10 22:45:54.356 [info] <0.3622.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env dump_log_load_regulation: false

2016-04-10 22:45:54.357 [info] <0.3622.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env dump_log_time_threshold: 180000

2016-04-10 22:45:54.357 [info] <0.3622.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env dump_log_update_in_place: true

2016-04-10 22:45:54.357 [info] <0.3622.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env dump_log_write_threshold: 1000

2016-04-10 22:45:54.357 [info] <0.3622.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env event_module: mnesia2_event

2016-04-10 22:45:54.357 [info] <0.3622.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env extra_db_nodes: []

2016-04-10 22:45:54.358 [info] <0.3622.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env ignore_fallback_at_startup: false

2016-04-10 22:45:54.358 [info] <0.3622.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env fallback_error_function: {mnesia2,lkill}

2016-04-10 22:45:54.358 [info] <0.3622.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env max_wait_for_decision: infinity

2016-04-10 22:45:54.358 [info] <0.3622.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env schema_location: opt_disc

2016-04-10 22:45:54.359 [info] <0.3622.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env core_dir: false

2016-04-10 22:45:54.359 [info] <0.3622.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env pid_sort_order: false

2016-04-10 22:45:54.359 [info] <0.3622.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env no_table_loaders: 2

2016-04-10 22:45:54.359 [info] <0.3622.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env dc_dump_limit: 4

2016-04-10 22:45:54.359 [info] <0.3622.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env send_compressed: 0

2016-04-10 22:45:54.360 [info] <0.3622.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env send_max_packets: 20

2016-04-10 22:45:54.360 [info] <0.3622.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env send_max_transfer_size: 7500

2016-04-10 22:45:54.360 [info] <0.3622.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env async_dirty_buffer_size: 524288

2016-04-10 22:45:54.360 [info] <0.3622.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env async_dirty_max_buffer_file_size: 100000000

2016-04-10 22:45:54.361 [info] <0.3622.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env async_dirty_tx_backlog_threshold: 200000

2016-04-10 22:45:54.361 [info] <0.3622.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env async_dirty_buffer_min_runtime: 10000

2016-04-10 22:45:54.361 [info] <0.3622.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Env async_dirty_buffer_drained_cutoff: 5

2016-04-10 22:45:54.361 [info] <0.3622.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Mnesia2 debug level set to debug
2016-04-10 22:45:54.362 [info] <0.3622.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): mnesia2_subscr starting: <0.3625.0>

2016-04-10 22:45:54.362 [info] <0.3622.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): mnesia2_locker starting: <0.3626.0>

2016-04-10 22:45:54.362 [info] <0.3622.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): mnesia2_recover starting: <0.3627.0>

2016-04-10 22:45:54.363 [info] <0.3622.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): mnesia2_tm starting: <0.3628.0>

2016-04-10 22:45:54.363 [info] <0.3622.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): Schema initiated from: default

2016-04-10 22:45:54.363 [info] <0.3628.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.3628.0>
2016-04-10 22:45:54.363 [info] <0.3622.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): debug fun {mnesia2_tm,init} in ets mnesia2_debug does not exist, ignoring
2016-04-10 22:45:54.364 [info] <0.3622.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): mnesia2_controller starting: <0.3631.0>

2016-04-10 22:45:54.364 [info] <0.3622.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): mnesia2_late_loader starting: <0.3632.0>

2016-04-10 22:45:56.391 [warning] <0.6.0> lager_error_logger_h dropped 34 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:45:56.393 [info] <0.3677.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.3677.0>
2016-04-10 22:45:56.397 [info] <0.7.0> Application mnesia2 started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:45:56.399 [error] <0.3668.0> CRASH REPORT Process <0.3668.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:45:56.399 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:45:58.499 [info] <0.3741.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.3741.0>
2016-04-10 22:45:58.503 [info] <0.7.0> Application mnesia2 started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:45:58.505 [error] <0.3732.0> CRASH REPORT Process <0.3732.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:45:58.505 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:45:59.633 [info] <0.3812.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.3812.0>
2016-04-10 22:45:59.637 [info] <0.7.0> Application mnesia2 started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:45:59.642 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:45:59.668 [info] <0.3873.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.3873.0>
2016-04-10 22:46:11.701 [warning] <0.3867.0> Mnesia2('test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:46:14.736 [error] <0.3864.0> CRASH REPORT Process <0.3864.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:46:14.737 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:46:16.909 [info] <0.4312.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.4312.0>
2016-04-10 22:46:16.913 [info] <0.7.0> Application mnesia2 started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:46:22.923 [error] <0.4303.0> CRASH REPORT Process <0.4303.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:46:22.923 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:46:29.988 [info] <0.4412.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.4412.0>
2016-04-10 22:46:29.991 [info] <0.7.0> Application mnesia2 started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:46:31.036 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:46:33.180 [info] <0.4528.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.4528.0>
2016-04-10 22:46:33.184 [info] <0.7.0> Application mnesia2 started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:46:33.206 [error] <0.4519.0> CRASH REPORT Process <0.4519.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:46:33.206 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:46:35.241 [info] <0.4595.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.4595.0>
2016-04-10 22:46:35.245 [info] <0.7.0> Application mnesia2 started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:46:35.285 [error] <0.4586.0> CRASH REPORT Process <0.4586.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:46:35.285 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:46:37.404 [info] <0.4687.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.4687.0>
2016-04-10 22:46:37.713 [info] <0.7.0> Application mnesia2 started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:46:37.421 [info] <0.1795.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.1795.0>
2016-04-10 22:46:37.437 [info] <0.7.0> Application mnesia2 started on node 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:46:38.715 [error] <0.1849.0> gen_server <0.1849.0> terminated with reason: killed
2016-04-10 22:46:38.716 [error] <0.1849.0> CRASH REPORT Process <0.1849.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:46:38.717 [error] <0.1786.0> CRASH REPORT Process <0.1786.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:46:38.717 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:46:40.752 [info] <0.1865.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.1865.0>
2016-04-10 22:46:40.760 [info] <0.7.0> Application mnesia2 started on node 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:46:41.763 [error] <0.4680.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.4682.0> exit with reason killed in context child_terminated
2016-04-10 22:46:41.763 [error] <0.4680.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.4682.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:46:41.763 [error] <0.4684.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-10 22:46:41.763 [error] <0.4684.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:46:41.765 [info] <0.7.0> Application mnesia2 exited with reason: shutdown
2016-04-10 22:46:42.821 [error] <0.1856.0> CRASH REPORT Process <0.1856.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:46:42.822 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:46:43.929 [info] <0.1947.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.1947.0>
2016-04-10 22:46:43.944 [info] <0.7.0> Application mnesia2 started on node 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:46:43.947 [error] <0.1985.0> gen_server <0.1985.0> terminated with reason: killed
2016-04-10 22:46:43.901 [info] <0.4793.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.4793.0>
2016-04-10 22:46:43.904 [info] <0.7.0> Application mnesia2 started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:46:43.950 [error] <0.4784.0> CRASH REPORT Process <0.4784.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:46:43.947 [error] <0.1985.0> CRASH REPORT Process <0.1985.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:46:43.948 [error] <0.1937.0> CRASH REPORT Process <0.1937.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:46:43.950 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:46:44.004 [info] <0.4868.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.4868.0>
2016-04-10 22:46:44.008 [info] <0.7.0> Application mnesia2 started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:46:43.948 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:46:50.883 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:46:50.969 [info] <0.4992.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.4992.0>
2016-04-10 22:46:50.977 [info] <0.7.0> Application mnesia2 started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:46:50.957 [info] <0.2021.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.2021.0>
2016-04-10 22:46:50.958 [info] <0.7.0> Application mnesia2 started on node 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:47:06.558 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:47:06.562 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:47:14.371 [info] <0.2143.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.2143.0>
2016-04-10 22:47:14.378 [info] <0.7.0> Application mnesia2 started on node 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:47:14.446 [error] <0.2197.0> gen_server <0.2197.0> terminated with reason: killed
2016-04-10 22:47:14.446 [error] <0.2197.0> CRASH REPORT Process <0.2197.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:47:14.446 [error] <0.2134.0> CRASH REPORT Process <0.2134.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:47:14.362 [info] <0.5123.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.5123.0>
2016-04-10 22:47:14.368 [info] <0.7.0> Application mnesia2 started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:47:14.477 [error] <0.5114.0> CRASH REPORT Process <0.5114.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:47:14.477 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:14.514 [info] <0.5211.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.5211.0>
2016-04-10 22:47:14.447 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:14.879 [info] <0.2231.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.2231.0>
2016-04-10 22:47:15.533 [warning] <0.6.0> lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:47:15.533 [error] <0.5282.0> gen_server <0.5282.0> terminated with reason: killed
2016-04-10 22:47:15.533 [error] <0.5282.0> CRASH REPORT Process <0.5282.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:47:15.535 [error] <0.5202.0> CRASH REPORT Process <0.5202.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:47:15.535 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:16.677 [error] <0.2222.0> CRASH REPORT Process <0.2222.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:47:16.677 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:17.761 [info] <0.2334.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.2334.0>
2016-04-10 22:47:17.769 [info] <0.7.0> Application mnesia2 started on node 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:47:17.801 [error] <0.2345.0> gen_server <0.2345.0> terminated with reason: killed
2016-04-10 22:47:17.751 [info] <0.5334.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.5334.0>
2016-04-10 22:47:17.755 [info] <0.7.0> Application mnesia2 started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:47:17.804 [error] <0.5398.0> gen_server <0.5398.0> terminated with reason: killed
2016-04-10 22:47:17.801 [error] <0.2345.0> CRASH REPORT Process <0.2345.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:47:17.804 [error] <0.5398.0> CRASH REPORT Process <0.5398.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:47:17.802 [error] <0.2325.0> CRASH REPORT Process <0.2325.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:47:17.806 [error] <0.5325.0> CRASH REPORT Process <0.5325.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:47:17.806 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:17.802 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:19.944 [info] <0.2409.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.2409.0>
2016-04-10 22:47:19.952 [info] <0.7.0> Application mnesia2 started on node 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:47:19.956 [error] <0.2400.0> CRASH REPORT Process <0.2400.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:47:19.934 [info] <0.5445.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.5445.0>
2016-04-10 22:47:19.938 [info] <0.7.0> Application mnesia2 started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:47:19.958 [error] <0.5441.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-10 22:47:19.958 [error] <0.5444.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-10 22:47:19.958 [error] <0.5444.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:47:19.958 [error] <0.5439.0> CRASH REPORT Process mnesia2_event with 0 neighbours exited with reason: killed in gen_event:terminate_server/4 line 315
2016-04-10 22:47:19.962 [error] <0.5436.0> CRASH REPORT Process <0.5436.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:47:19.962 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:19.956 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:22.003 [info] <0.5525.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.5525.0>
2016-04-10 22:47:22.012 [info] <0.7.0> Application mnesia2 started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:47:22.030 [error] <0.5572.0> gen_server <0.5572.0> terminated with reason: killed
2016-04-10 22:47:22.030 [error] <0.5572.0> CRASH REPORT Process <0.5572.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:47:22.030 [error] <0.5516.0> CRASH REPORT Process <0.5516.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:47:21.990 [info] <0.2469.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.2469.0>
2016-04-10 22:47:21.992 [info] <0.7.0> Application mnesia2 started on node 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:47:22.030 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:23.522 [error] <0.2460.0> CRASH REPORT Process <0.2460.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:47:23.522 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:24.641 [info] <0.2558.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.2558.0>
2016-04-10 22:47:24.649 [info] <0.7.0> Application mnesia2 started on node 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:47:25.182 [error] <0.2549.0> CRASH REPORT Process <0.2549.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:47:24.632 [info] <0.5650.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.5650.0>
2016-04-10 22:47:24.636 [info] <0.7.0> Application mnesia2 started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:47:25.184 [error] <0.5703.0> gen_server <0.5703.0> terminated with reason: killed
2016-04-10 22:47:25.184 [error] <0.5703.0> CRASH REPORT Process <0.5703.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:47:25.047 [info] <0.7.0> Application lager started on node 'd642213o642203n642202@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:47:25.047 [info] <0.7.0> Application poolgirl started on node 'd642213o642203n642202@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:47:25.085 [info] <0.102.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642213o642203n642202@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.102.0>
2016-04-10 22:47:25.112 [info] <0.7.0> Application mnesia2 started on node 'd642213o642203n642202@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:47:25.191 [error] <0.93.0> CRASH REPORT Process <0.93.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:47:25.184 [error] <0.5695.0> gen_server <0.5695.0> terminated with reason: killed
2016-04-10 22:47:25.185 [error] <0.5695.0> CRASH REPORT Process <0.5695.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:47:25.185 [error] <0.5641.0> CRASH REPORT Process <0.5641.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:47:25.185 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:25.182 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:25.192 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:27.302 [info] <0.5745.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.5745.0>
2016-04-10 22:47:27.305 [info] <0.7.0> Application mnesia2 started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:47:27.326 [error] <0.5809.0> gen_server <0.5809.0> terminated with reason: killed
2016-04-10 22:47:27.313 [info] <0.2639.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.2639.0>
2016-04-10 22:47:27.322 [info] <0.7.0> Application mnesia2 started on node 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:47:27.329 [error] <0.2630.0> CRASH REPORT Process <0.2630.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:47:27.326 [error] <0.5809.0> CRASH REPORT Process <0.5809.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:47:27.338 [error] <0.5736.0> CRASH REPORT Process <0.5736.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:47:27.339 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:27.329 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:29.446 [info] <0.2709.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.2709.0>
2016-04-10 22:47:29.451 [info] <0.7.0> Application mnesia2 started on node 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:47:29.458 [error] <0.2720.0> gen_server <0.2720.0> terminated with reason: killed
2016-04-10 22:47:29.438 [info] <0.5839.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.5839.0>
2016-04-10 22:47:29.442 [info] <0.7.0> Application mnesia2 started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:47:29.460 [error] <0.5883.0> gen_server <0.5883.0> terminated with reason: killed
2016-04-10 22:47:29.458 [error] <0.2720.0> CRASH REPORT Process <0.2720.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:47:29.460 [error] <0.5883.0> CRASH REPORT Process <0.5883.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:47:29.458 [error] <0.2700.0> CRASH REPORT Process <0.2700.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:47:29.460 [error] <0.5830.0> CRASH REPORT Process <0.5830.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:47:29.460 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:29.458 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:31.613 [info] <0.2784.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.2784.0>
2016-04-10 22:47:31.633 [info] <0.7.0> Application mnesia2 started on node 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:47:31.636 [error] <0.2819.0> gen_server <0.2819.0> terminated with reason: killed
2016-04-10 22:47:31.636 [error] <0.2819.0> CRASH REPORT Process <0.2819.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:47:31.636 [error] <0.2775.0> CRASH REPORT Process <0.2775.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:47:31.603 [info] <0.5925.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.5925.0>
2016-04-10 22:47:31.608 [info] <0.7.0> Application mnesia2 started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:47:31.636 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:32.676 [error] <0.5916.0> CRASH REPORT Process <0.5916.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:47:32.676 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:34.711 [info] <0.2854.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.2854.0>
2016-04-10 22:47:34.713 [info] <0.7.0> Application mnesia2 started on node 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:47:39.756 [info] <0.6003.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.6003.0>
2016-04-10 22:47:39.782 [info] <0.7.0> Application mnesia2 started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:47:39.793 [error] <0.6041.0> gen_server <0.6041.0> terminated with reason: killed
2016-04-10 22:47:39.793 [error] <0.6041.0> CRASH REPORT Process <0.6041.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:47:39.791 [error] <0.2923.0> gen_server <0.2923.0> terminated with reason: killed
2016-04-10 22:47:39.793 [error] <0.5994.0> CRASH REPORT Process <0.5994.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:47:39.791 [error] <0.2923.0> CRASH REPORT Process <0.2923.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:47:39.791 [error] <0.2845.0> CRASH REPORT Process <0.2845.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:47:39.793 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:39.791 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:41.013 [info] <0.2953.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.2953.0>
2016-04-10 22:47:41.038 [info] <0.7.0> Application mnesia2 started on node 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:47:41.384 [error] <0.3015.0> gen_server <0.3015.0> terminated with reason: killed
2016-04-10 22:47:41.384 [error] <0.3015.0> CRASH REPORT Process <0.3015.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:47:41.384 [error] <0.3010.0> gen_server <0.3010.0> terminated with reason: killed
2016-04-10 22:47:41.384 [error] <0.3010.0> CRASH REPORT Process <0.3010.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:47:41.384 [error] <0.2944.0> CRASH REPORT Process <0.2944.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:47:41.009 [info] <0.6113.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.6113.0>
2016-04-10 22:47:41.318 [info] <0.7.0> Application mnesia2 started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:47:41.486 [error] <0.6200.0> gen_server <0.6200.0> terminated with reason: killed
2016-04-10 22:47:41.486 [error] <0.6200.0> CRASH REPORT Process <0.6200.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:47:41.486 [error] <0.6178.0> gen_server <0.6178.0> terminated with reason: killed
2016-04-10 22:47:41.487 [error] <0.6178.0> CRASH REPORT Process <0.6178.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:47:41.488 [error] <0.6104.0> CRASH REPORT Process <0.6104.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:47:41.103 [info] <0.192.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642213o642203n642202@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.192.0>
2016-04-10 22:47:41.118 [info] <0.7.0> Application mnesia2 started on node 'd642213o642203n642202@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:47:41.506 [error] <0.275.0> gen_server <0.275.0> terminated with reason: killed
2016-04-10 22:47:41.506 [error] <0.275.0> CRASH REPORT Process <0.275.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:47:41.509 [error] <0.183.0> CRASH REPORT Process <0.183.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:47:41.488 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:41.615 [info] <0.6236.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.6236.0>
2016-04-10 22:47:41.385 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:41.419 [info] <0.3045.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.3045.0>
2016-04-10 22:47:41.575 [info] <0.3140.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.3140.0>
2016-04-10 22:47:41.509 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:41.633 [info] <0.296.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642213o642203n642202@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.296.0>
2016-04-10 22:47:41.664 [info] <0.7.0> Application mnesia2 started on node 'd642213o642203n642202@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:47:42.465 [error] <0.366.0> gen_server <0.366.0> terminated with reason: killed
2016-04-10 22:47:42.465 [error] <0.366.0> CRASH REPORT Process <0.366.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:47:42.467 [error] <0.357.0> gen_server <0.357.0> terminated with reason: killed
2016-04-10 22:47:42.468 [error] <0.357.0> CRASH REPORT Process <0.357.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:47:42.470 [error] <0.287.0> CRASH REPORT Process <0.287.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:47:42.470 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:42.495 [info] <0.392.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642213o642203n642202@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.392.0>
2016-04-10 22:47:42.497 [info] <0.7.0> Application mnesia2 started on node 'd642213o642203n642202@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:47:44.612 [warning] <0.6.0> lager_error_logger_h dropped 33 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:47:44.612 [error] <0.6227.0> CRASH REPORT Process <0.6227.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:47:44.632 [warning] <0.6.0> lager_error_logger_h dropped 19 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:47:44.632 [error] <0.3233.0> gen_server <0.3233.0> terminated with reason: killed
2016-04-10 22:47:44.632 [error] <0.3233.0> CRASH REPORT Process <0.3233.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:47:44.633 [error] <0.3131.0> CRASH REPORT Process <0.3131.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:47:44.657 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:47:44.675 [info] <0.498.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642213o642203n642202@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.498.0>
2016-04-10 22:47:44.678 [info] <0.7.0> Application mnesia2 started on node 'd642213o642203n642202@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:47:45.281 [error] <0.572.0> gen_server <0.572.0> terminated with reason: killed
2016-04-10 22:47:45.281 [error] <0.572.0> CRASH REPORT Process <0.572.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:47:45.281 [error] <0.566.0> gen_server <0.566.0> terminated with reason: killed
2016-04-10 22:47:45.281 [error] <0.566.0> CRASH REPORT Process <0.566.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:47:45.281 [error] <0.489.0> CRASH REPORT Process <0.489.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:47:44.612 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:44.709 [info] <0.6353.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.6353.0>
2016-04-10 22:47:44.763 [info] <0.7.0> Application mnesia2 started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:47:45.387 [error] <0.6348.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.6369.0> exit with reason killed in context child_terminated
2016-04-10 22:47:45.387 [error] <0.6348.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.6369.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:47:45.391 [error] <0.6346.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.6348.0> exit with reason shutdown in context child_terminated
2016-04-10 22:47:45.391 [error] <0.6346.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.6348.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:47:44.633 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:44.717 [info] <0.3254.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.3254.0>
2016-04-10 22:47:44.741 [info] <0.7.0> Application mnesia2 started on node 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:47:45.405 [error] <0.3339.0> gen_server <0.3339.0> terminated with reason: killed
2016-04-10 22:47:45.405 [error] <0.3339.0> CRASH REPORT Process <0.3339.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:47:45.407 [error] <0.3245.0> CRASH REPORT Process <0.3245.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:47:45.395 [info] <0.7.0> Application mnesia2 exited with reason: shutdown
2016-04-10 22:47:45.495 [info] <0.6465.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.6465.0>
2016-04-10 22:47:45.407 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:45.498 [info] <0.3360.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.3360.0>
2016-04-10 22:47:45.530 [info] <0.7.0> Application mnesia2 started on node 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:47:45.281 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:45.316 [info] <0.598.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642213o642203n642202@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.598.0>
2016-04-10 22:47:45.319 [info] <0.7.0> Application mnesia2 started on node 'd642213o642203n642202@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:47:45.431 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:47:45.455 [info] <0.699.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642213o642203n642202@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.699.0>
2016-04-10 22:47:45.832 [error] <0.3351.0> CRASH REPORT Process <0.3351.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:47:45.804 [info] <0.7.0> Application mnesia2 started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:47:45.832 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:46.750 [info] <0.3456.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.3456.0>
2016-04-10 22:47:46.786 [info] <0.7.0> Application mnesia2 started on node 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:47:46.815 [error] <0.3514.0> gen_server <0.3514.0> terminated with reason: killed
2016-04-10 22:47:46.815 [error] <0.3514.0> CRASH REPORT Process <0.3514.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:47:46.840 [error] <0.3469.0> gen_server <0.3469.0> terminated with reason: killed
2016-04-10 22:47:46.840 [error] <0.3469.0> CRASH REPORT Process <0.3469.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:47:46.840 [error] <0.3482.0> gen_server <0.3482.0> terminated with reason: killed
2016-04-10 22:47:46.840 [error] <0.3482.0> CRASH REPORT Process <0.3482.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:47:46.840 [error] <0.3447.0> CRASH REPORT Process <0.3447.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:47:46.840 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:47.861 [info] <0.3534.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.3534.0>
2016-04-10 22:47:47.877 [info] <0.7.0> Application mnesia2 started on node 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:47:47.925 [error] <0.3525.0> CRASH REPORT Process <0.3525.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:47:47.927 [error] <0.6460.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.6486.0> exit with reason killed in context child_terminated
2016-04-10 22:47:47.927 [error] <0.6460.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.6486.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:47:47.930 [error] <0.6458.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.6460.0> exit with reason killed in context child_terminated
2016-04-10 22:47:47.928 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:47:47.928 [error] <0.772.0> gen_server <0.772.0> terminated with reason: killed
2016-04-10 22:47:47.930 [error] <0.6458.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.6460.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:47:47.930 [error] <0.6462.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-10 22:47:47.931 [error] <0.6462.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:47:47.931 [error] <0.6461.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-10 22:47:47.931 [error] <0.6464.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-10 22:47:47.931 [error] <0.6464.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:47:47.928 [error] <0.772.0> CRASH REPORT Process <0.772.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:47:47.929 [error] <0.690.0> CRASH REPORT Process <0.690.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:47:47.926 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:48.028 [info] <0.3612.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.3612.0>
2016-04-10 22:47:48.037 [info] <0.7.0> Application mnesia2 started on node 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:47:48.377 [error] <0.3667.0> gen_server <0.3667.0> terminated with reason: killed
2016-04-10 22:47:48.377 [error] <0.3667.0> CRASH REPORT Process <0.3667.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:47:48.377 [error] <0.3603.0> CRASH REPORT Process <0.3603.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:47:48.377 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:48.415 [info] <0.3708.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.3708.0>
2016-04-10 22:47:48.506 [info] <0.3798.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.3798.0>
2016-04-10 22:47:48.591 [info] <0.3898.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.3898.0>
2016-04-10 22:47:47.934 [info] <0.7.0> Application mnesia2 exited with reason: shutdown
2016-04-10 22:47:48.010 [info] <0.6611.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.6611.0>
2016-04-10 22:47:48.317 [info] <0.7.0> Application mnesia2 started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:47:48.588 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:47:47.930 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:49.172 [warning] <0.6.0> lager_error_logger_h dropped 32 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:47:49.172 [error] <0.3889.0> CRASH REPORT Process <0.3889.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:47:49.172 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:49.720 [info] <0.3980.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.3980.0>
2016-04-10 22:47:49.784 [info] <0.7.0> Application mnesia2 started on node 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:47:49.847 [error] <0.4031.0> gen_server <0.4031.0> terminated with reason: killed
2016-04-10 22:47:49.847 [error] <0.4031.0> CRASH REPORT Process <0.4031.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:47:49.847 [error] <0.3971.0> CRASH REPORT Process <0.3971.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:47:49.112 [info] <0.6725.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.6725.0>
2016-04-10 22:47:49.133 [info] <0.7.0> Application mnesia2 started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:47:49.169 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:47:49.212 [info] <0.6808.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.6808.0>
2016-04-10 22:47:49.978 [info] <0.6909.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.6909.0>
2016-04-10 22:47:49.848 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:49.976 [info] <0.4072.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.4072.0>
2016-04-10 22:47:50.281 [warning] <0.6.0> lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:47:50.285 [info] <0.7.0> Application mnesia2 started on node 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:47:50.385 [error] <0.4135.0> gen_server <0.4135.0> terminated with reason: killed
2016-04-10 22:47:49.982 [info] <0.851.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642213o642203n642202@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.851.0>
2016-04-10 22:47:50.003 [info] <0.7.0> Application mnesia2 started on node 'd642213o642203n642202@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:47:50.385 [error] <0.847.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-10 22:47:50.390 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:47:50.391 [error] <0.6900.0> CRASH REPORT Process <0.6900.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:47:50.385 [error] <0.850.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-10 22:47:50.385 [error] <0.4135.0> CRASH REPORT Process <0.4135.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:47:50.386 [error] <0.4120.0> gen_server <0.4120.0> terminated with reason: killed
2016-04-10 22:47:50.385 [error] <0.850.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:47:50.386 [error] <0.4120.0> CRASH REPORT Process <0.4120.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:47:50.386 [error] <0.4063.0> CRASH REPORT Process <0.4063.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:47:50.385 [error] <0.844.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.846.0> exit with reason killed in context child_terminated
2016-04-10 22:47:50.385 [error] <0.844.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.846.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:47:50.386 [error] <0.867.0> gen_server mnesia2_snmp_sup terminated with reason: killed
2016-04-10 22:47:50.386 [error] <0.867.0> CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:47:50.386 [error] <0.848.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-10 22:47:50.386 [error] <0.848.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:47:50.391 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:50.474 [info] <0.7019.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.7019.0>
2016-04-10 22:47:50.502 [info] <0.7.0> Application mnesia2 started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:47:50.523 [error] <0.7087.0> gen_server <0.7087.0> terminated with reason: killed
2016-04-10 22:47:50.523 [error] <0.7087.0> CRASH REPORT Process <0.7087.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:47:50.523 [error] <0.7081.0> gen_server <0.7081.0> terminated with reason: killed
2016-04-10 22:47:50.524 [error] <0.7081.0> CRASH REPORT Process <0.7081.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:47:50.388 [info] <0.7.0> Application mnesia2 exited with reason: shutdown
2016-04-10 22:47:50.416 [info] <0.957.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642213o642203n642202@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.957.0>
2016-04-10 22:47:50.555 [info] <0.1035.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642213o642203n642202@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.1035.0>
2016-04-10 22:47:50.386 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:50.414 [info] <0.4167.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.4167.0>
2016-04-10 22:47:50.558 [info] <0.4244.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.4244.0>
2016-04-10 22:47:50.596 [info] <0.7111.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.7111.0>
2016-04-10 22:48:00.608 [error] <0.7104.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at undefined exit with reason killed in context start_error
2016-04-10 22:48:00.608 [error] <0.7107.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-10 22:48:00.608 [error] <0.7110.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-10 22:48:00.608 [error] <0.7110.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:48:00.608 [error] <0.7130.0> gen_server mnesia2_snmp_sup terminated with reason: killed
2016-04-10 22:48:00.608 [error] <0.7130.0> CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:48:00.608 [error] <0.7108.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-10 22:48:00.608 [error] <0.7108.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:48:00.609 [error] <0.7102.0> CRASH REPORT Process <0.7102.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}} in application_master:init/4 line 134
2016-04-10 22:48:00.609 [info] <0.7.0> Application mnesia2 exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}}
2016-04-10 22:48:00.610 [error] <0.7107.0> CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:48:00.741 [warning] <0.6.0> lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:48:00.741 [error] <0.4235.0> CRASH REPORT Process <0.4235.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:48:00.740 [warning] <0.6.0> lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:48:00.740 [error] <0.1084.0> gen_server <0.1084.0> terminated with reason: killed
2016-04-10 22:48:00.740 [error] <0.1084.0> CRASH REPORT Process <0.1084.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:48:00.741 [error] <0.1079.0> gen_server <0.1079.0> terminated with reason: killed
2016-04-10 22:48:00.741 [error] <0.1079.0> CRASH REPORT Process <0.1079.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:48:00.741 [error] <0.1026.0> CRASH REPORT Process <0.1026.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:48:00.741 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:48:00.742 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:48:03.215 [info] <0.7221.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.7221.0>
2016-04-10 22:48:03.219 [info] <0.7.0> Application mnesia2 started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:48:10.076 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:48:10.337 [info] <0.7357.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.7357.0>
2016-04-10 22:48:10.645 [info] <0.7.0> Application mnesia2 started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:48:10.339 [info] <0.1133.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642213o642203n642202@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.1133.0>
2016-04-10 22:48:10.663 [info] <0.7.0> Application mnesia2 started on node 'd642213o642203n642202@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:48:10.341 [info] <0.4335.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.4335.0>
2016-04-10 22:48:10.373 [info] <0.7.0> Application mnesia2 started on node 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:48:16.823 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:48:16.988 [info] <0.4450.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.4450.0>
2016-04-10 22:48:17.063 [info] <0.7.0> Application mnesia2 started on node 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:48:16.831 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:48:16.988 [info] <0.7487.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.7487.0>
2016-04-10 22:48:17.051 [info] <0.7.0> Application mnesia2 started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:48:16.840 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:48:16.996 [info] <0.1250.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642213o642203n642202@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.1250.0>
2016-04-10 22:48:17.006 [info] <0.7.0> Application mnesia2 started on node 'd642213o642203n642202@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:48:23.205 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:48:23.378 [info] <0.4566.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.4566.0>
2016-04-10 22:48:23.424 [info] <0.7.0> Application mnesia2 started on node 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:48:23.220 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:48:23.367 [info] <0.7616.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.7616.0>
2016-04-10 22:48:23.371 [info] <0.7.0> Application mnesia2 started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:48:23.233 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:48:23.387 [info] <0.1363.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642213o642203n642202@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.1363.0>
2016-04-10 22:48:23.394 [info] <0.7.0> Application mnesia2 started on node 'd642213o642203n642202@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:48:48.718 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:48:49.281 [info] <0.8755.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.8755.0>
2016-04-10 22:48:49.285 [info] <0.7.0> Application mnesia2 started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:48:49.052 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:48:49.292 [info] <0.2485.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642213o642203n642202@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.2485.0>
2016-04-10 22:48:49.327 [info] <0.7.0> Application mnesia2 started on node 'd642213o642203n642202@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:48:49.075 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:48:49.292 [info] <0.5691.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.5691.0>
2016-04-10 22:48:49.315 [info] <0.7.0> Application mnesia2 started on node 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:48:55.721 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:48:55.890 [info] <0.2610.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642213o642203n642202@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.2610.0>
2016-04-10 22:48:55.912 [info] <0.7.0> Application mnesia2 started on node 'd642213o642203n642202@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:48:55.722 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:48:55.869 [info] <0.8893.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.8893.0>
2016-04-10 22:48:55.872 [info] <0.7.0> Application mnesia2 started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:48:55.720 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:48:55.889 [info] <0.5815.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.5815.0>
2016-04-10 22:48:56.194 [info] <0.7.0> Application mnesia2 started on node 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:49:02.757 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:49:02.953 [info] <0.10373.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.10373.0>
2016-04-10 22:49:02.959 [info] <0.7.0> Application mnesia2 started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:49:02.764 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:49:02.971 [info] <0.7288.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.7288.0>
2016-04-10 22:49:03.279 [info] <0.7.0> Application mnesia2 started on node 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:49:02.782 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:49:02.973 [info] <0.4081.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642213o642203n642202@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.4081.0>
2016-04-10 22:49:03.002 [info] <0.7.0> Application mnesia2 started on node 'd642213o642203n642202@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:49:09.640 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:49:09.833 [info] <0.10671.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.10671.0>
2016-04-10 22:49:10.142 [info] <0.7.0> Application mnesia2 started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:49:09.654 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:49:09.814 [info] <0.8979.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.8979.0>
2016-04-10 22:49:10.121 [info] <0.7.0> Application mnesia2 started on node 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:49:09.658 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:49:09.838 [info] <0.5248.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642213o642203n642202@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.5248.0>
2016-04-10 22:49:09.846 [info] <0.7.0> Application mnesia2 started on node 'd642213o642203n642202@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:49:16.351 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:49:16.538 [info] <0.5363.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642213o642203n642202@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.5363.0>
2016-04-10 22:49:16.550 [info] <0.7.0> Application mnesia2 started on node 'd642213o642203n642202@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:49:16.354 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:49:16.529 [info] <0.10801.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.10801.0>
2016-04-10 22:49:16.840 [info] <0.7.0> Application mnesia2 started on node 'test2866@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:49:16.390 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:49:16.534 [info] <0.9775.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10', <0.9775.0>
2016-04-10 22:49:16.853 [info] <0.7.0> Application mnesia2 started on node 'd642221o642195n642193@testing-worker-linux-docker-71fc02f6-3370-linux-10'
2016-04-10 22:49:30.925 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:49:30.906 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:49:30.929 [info] <0.7.0> Application mnesia2 exited with reason: stopped
