--- Test run on 2016/04/12 08:50:13 ---
Converting "/home/travis/build/lrascao/mnesia2/." to "/home/travis/build/lrascao/mnesia2" and re-inserting with add_patha/1


Common Test v1.8 starting (cwd is /home/travis/build/lrascao/mnesia2)


Common Test: Running make in test directories...
Recompile: mnesia2_extra_light_SUITE
Recompile: ts_install_cth
Recompile: mt
Recompile: mnesia2_trans_access_test
Recompile: mnesia2_tpcb
Recompile: mnesia2_test_lib
Recompile: mnesia2_schema_recovery_test
mnesia2_schema_recovery_test.erl:261: Warning: variable 'Bad' is unused
Recompile: mnesia2_registry_test
Recompile: mnesia2_recovery_test
mnesia2_recovery_test.erl:1571: Warning: variable 'Config' is unused
Recompile: mnesia2_qlc_test
Recompile: mnesia2_nice_coverage_test
Recompile: mnesia2_meter
Recompile: mnesia2_measure_test
Recompile: mnesia2_majority_test
Recompile: mnesia2_isolation_test
Recompile: mnesia2_install_test
Recompile: mnesia2_inconsistent_database_test
Recompile: mnesia2_frag_test
Recompile: mnesia2_frag_hash_test
Recompile: mnesia2_examples_test
Recompile: mnesia2_evil_coverage_test
Recompile: mnesia2_evil_backup
Recompile: mnesia2_durability_test
Recompile: mnesia2_dirty_access_test
Recompile: mnesia2_dbn_meters
Recompile: mnesia2_cost
Recompile: mnesia2_consistency_test
Recompile: mnesia2_config_test
Recompile: mnesia2_config_event
Recompile: mnesia2_config_backup
Recompile: mnesia2_atomicity_test

CWD set to: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12.2016-04-12_08.50.13"

TEST INFO: 1 test(s), 52 case(s) in 1 suite(s)

Cover compiling 'mnesia2' (32 files) - this may take some time... done

Testing lrascao.mnesia2.mnesia2_extra_light_SUITE: Starting test, 52 test cases

----------------------------------------------------
2016-04-12 08:50:40.574
starting test group: extra_light


----------------------------------------------------
2016-04-12 08:50:40.616
starting test group: install


----------------------------------------------------
2016-04-12 08:50:40.701
starting test case: silly_durability

08:50:40.848 [info] Application lager started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:50:40.848 [info] Application poolgirl started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:50:40.884 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.430.0>
08:50:40.909 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.498.0>

----------------------------------------------------
2016-04-12 08:50:40.918
ending test case: silly_durability


----------------------------------------------------
2016-04-12 08:50:40.944
starting test case: silly_move

08:50:41.324 [error] CRASH REPORT Process <0.489.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:50:41.324 [info] Application mnesia2 exited with reason: killed
08:50:41.468 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.608.0>
08:50:41.471 [info] Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:50:41.819 [info] Application lager started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:50:41.819 [info] Application poolgirl started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:50:41.908 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.99.0>

----------------------------------------------------
2016-04-12 08:50:42.086
ending test case: silly_move


----------------------------------------------------
2016-04-12 08:50:42.113
starting test case: silly_upgrade

08:50:42.115 [error] gen_server <0.155.0> terminated with reason: killed
08:50:42.118 [error] gen_server <0.665.0> terminated with reason: killed
08:50:42.115 [error] CRASH REPORT Process <0.155.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:50:42.118 [error] CRASH REPORT Process <0.665.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:50:42.117 [error] CRASH REPORT Process <0.90.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:50:42.117 [info] Application mnesia2 exited with reason: killed
08:50:42.119 [error] CRASH REPORT Process <0.599.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:50:42.119 [info] Application mnesia2 exited with reason: killed
08:50:42.184 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.735.0>
08:50:42.187 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.215.0>
08:50:42.203 [info] Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:50:42.491 [info] Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:50:42.793 [info] Application mnesia2 exited with reason: stopped
08:50:42.793 [error] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): ** ERROR ** (ignoring core) ** FATAL ** A fallback is installed and Mnesia2 must be restarted. Forcing shutdown after mnesia2_down from 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'...

08:50:42.794 [error] Supervisor mnesia2_kernel_sup had child mnesia2_locker started with mnesia2_locker:start() at <0.733.0> exit with reason killed in context child_terminated
08:50:42.794 [error] Supervisor mnesia2_kernel_sup had child mnesia2_locker started with mnesia2_locker:start() at <0.733.0> exit with reason reached_max_restart_intensity in context shutdown
08:50:42.797 [error] Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.730.0> exit with reason shutdown in context child_terminated
08:50:42.797 [error] Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.730.0> exit with reason reached_max_restart_intensity in context shutdown
08:50:42.848 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.864.0>
08:50:42.876 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.369.0>
08:50:42.958 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.964.0>
08:50:42.967 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.460.0>

----------------------------------------------------
2016-04-12 08:50:43.491
ending test case: silly_upgrade


----------------------------------------------------
2016-04-12 08:50:43.580
ending test group: install


----------------------------------------------------
2016-04-12 08:50:43.609
starting test group: nice


----------------------------------------------------
2016-04-12 08:50:43.692
starting test case: nice

08:50:43.697 [warning] lager_error_logger_h dropped 32 messages in the last second that exceeded the limit of 50 messages/sec
08:50:43.696 [error] Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.979.0> exit with reason killed in context child_terminated
08:50:43.697 [error] gen_server <0.518.0> terminated with reason: killed
08:50:43.696 [error] Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.979.0> exit with reason reached_max_restart_intensity in context shutdown
08:50:43.698 [error] CRASH REPORT Process <0.955.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:50:43.698 [info] Application mnesia2 exited with reason: killed
08:50:43.698 [error] CRASH REPORT Process <0.518.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:50:43.698 [error] CRASH REPORT Process <0.451.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:50:43.698 [info] Application mnesia2 exited with reason: killed
08:50:43.764 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.1087.0>
08:50:43.768 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.549.0>
08:50:43.778 [info] Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:50:44.070 [info] Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:50:44.207 [info] Application mnesia2 exited with reason: stopped
08:50:44.220 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.1200.0>
08:50:44.227 [info] Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'

----------------------------------------------------
2016-04-12 08:50:44.508
ending test case: nice


----------------------------------------------------
2016-04-12 08:50:44.590
ending test group: nice


----------------------------------------------------
2016-04-12 08:50:44.629
starting test group: qlc


----------------------------------------------------
2016-04-12 08:50:44.742
starting test case: dirty_nice_ram_copies

08:50:44.745 [error] gen_server <0.1237.0> terminated with reason: killed
08:50:44.745 [error] CRASH REPORT Process <0.1237.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:50:44.746 [error] Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.544.0> exit with reason killed in context child_terminated
08:50:44.746 [error] CRASH REPORT Process <0.1191.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:50:44.746 [info] Application mnesia2 exited with reason: killed
08:50:44.747 [error] Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.544.0> exit with reason reached_max_restart_intensity in context shutdown
08:50:44.747 [error] gen_server mnesia2_snmp_sup terminated with reason: killed
08:50:44.747 [error] CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:50:44.747 [error] gen_server mnesia2_recover terminated with reason: killed
08:50:44.747 [error] CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:50:44.747 [error] gen_server mnesia2_subscr terminated with reason: killed
08:50:44.747 [error] CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:50:44.747 [error] gen_server mnesia2_monitor terminated with reason: killed
08:50:44.747 [error] CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:50:44.749 [info] Application mnesia2 exited with reason: shutdown
08:50:44.813 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.1432.0>
08:50:44.840 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.764.0>

----------------------------------------------------
2016-04-12 08:50:44.942
ending test case: dirty_nice_ram_copies


----------------------------------------------------
2016-04-12 08:50:44.972
starting test case: dirty_nice_disc_copies

08:50:45.026 [warning] lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
08:50:45.027 [warning] lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
08:50:45.053 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.1546.0>
08:50:45.057 [info] Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:50:45.060 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.863.0>
08:50:45.069 [info] Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'

----------------------------------------------------
2016-04-12 08:50:45.174
ending test case: dirty_nice_disc_copies


----------------------------------------------------
2016-04-12 08:50:45.208
starting test case: dirty_nice_disc_only_copies

08:50:45.211 [error] CRASH REPORT Process <0.1537.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:50:45.212 [info] Application mnesia2 exited with reason: killed
08:50:45.212 [error] CRASH REPORT Process <0.854.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:50:45.212 [info] Application mnesia2 exited with reason: killed
08:50:45.275 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.1662.0>
08:50:45.293 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.964.0>

----------------------------------------------------
2016-04-12 08:50:45.736
ending test case: dirty_nice_disc_only_copies


----------------------------------------------------
2016-04-12 08:50:45.842
starting test case: trans_nice_ram_copies

08:50:45.909 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.1789.0>
08:50:45.915 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.1071.0>

----------------------------------------------------
2016-04-12 08:50:46.083
ending test case: trans_nice_ram_copies


----------------------------------------------------
2016-04-12 08:50:46.112
starting test case: trans_nice_disc_copies

08:50:46.115 [warning] lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
08:50:46.119 [warning] lager_error_logger_h dropped 10 messages in the last second that exceeded the limit of 50 messages/sec
08:50:46.119 [error] CRASH REPORT Process <0.1780.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:50:46.120 [info] Application mnesia2 exited with reason: killed
08:50:46.115 [error] gen_server <0.1125.0> terminated with reason: killed
08:50:46.115 [error] CRASH REPORT Process <0.1125.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:50:46.116 [error] CRASH REPORT Process <0.1062.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:50:46.116 [info] Application mnesia2 exited with reason: killed
08:50:46.183 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.1920.0>
08:50:46.188 [info] Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:50:46.204 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.1170.0>
08:50:46.216 [info] Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'

----------------------------------------------------
2016-04-12 08:50:46.342
ending test case: trans_nice_disc_copies


----------------------------------------------------
2016-04-12 08:50:46.370
starting test case: trans_nice_disc_only_copies

08:50:46.373 [error] CRASH REPORT Process <0.1161.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:50:46.373 [info] Application mnesia2 exited with reason: killed
08:50:46.375 [error] CRASH REPORT Process <0.1911.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:50:46.375 [info] Application mnesia2 exited with reason: killed
08:50:46.458 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.2053.0>
08:50:46.462 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.1271.0>

----------------------------------------------------
2016-04-12 08:50:46.951
ending test case: trans_nice_disc_only_copies


----------------------------------------------------
2016-04-12 08:50:47.019
starting test case: atomic_eval

08:50:47.023 [error] CRASH REPORT Process <0.2044.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:50:47.023 [info] Application mnesia2 exited with reason: killed
08:50:47.024 [error] gen_server <0.1326.0> terminated with reason: killed
08:50:47.024 [error] CRASH REPORT Process <0.1326.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:50:47.025 [error] CRASH REPORT Process <0.1262.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:50:47.025 [info] Application mnesia2 exited with reason: killed
08:50:47.092 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.2194.0>
08:50:47.095 [info] Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:50:47.101 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.1378.0>
08:50:47.104 [info] Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'

----------------------------------------------------
2016-04-12 08:50:47.232
ending test case: atomic_eval


----------------------------------------------------
2016-04-12 08:50:47.316
starting test case: frag

08:50:47.318 [error] gen_server <0.1432.0> terminated with reason: killed
08:50:47.319 [error] gen_server <0.2250.0> terminated with reason: killed
08:50:47.318 [error] CRASH REPORT Process <0.1432.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:50:47.319 [error] CRASH REPORT Process <0.2250.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:50:47.320 [error] CRASH REPORT Process <0.2185.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:50:47.320 [info] Application mnesia2 exited with reason: killed
08:50:47.397 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.2325.0>
08:50:47.399 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.1465.0>

----------------------------------------------------
2016-04-12 08:50:47.870
ending test case: frag


----------------------------------------------------
2016-04-12 08:50:47.898
starting test case: info

08:50:47.976 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.2457.0>
08:50:47.982 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.1579.0>

----------------------------------------------------
2016-04-12 08:50:48.316
ending test case: info


----------------------------------------------------
2016-04-12 08:50:48.343
starting test case: mnesia2_down

08:50:48.346 [warning] lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
08:50:48.347 [warning] lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
08:50:48.347 [error] Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.2469.0> exit with reason killed in context child_terminated
08:50:48.347 [error] gen_server <0.1633.0> terminated with reason: killed
08:50:48.347 [error] Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.2469.0> exit with reason reached_max_restart_intensity in context shutdown
08:50:48.347 [error] CRASH REPORT Process <0.1633.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:50:48.353 [error] Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.2452.0> exit with reason killed in context child_terminated
08:50:48.353 [error] Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.2452.0> exit with reason reached_max_restart_intensity in context shutdown
08:50:48.347 [error] CRASH REPORT Process <0.1570.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:50:48.347 [info] Application mnesia2 exited with reason: killed
08:50:48.353 [error] CRASH REPORT Process <0.2448.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:50:48.353 [info] Application mnesia2 exited with reason: killed
08:50:48.422 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.2580.0>
08:50:48.425 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.1666.0>
08:50:48.437 [info] Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:50:48.729 [info] Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
---> Participant transactions <--- 
---> Coordinator transactions <---
Tid: 14 (owned by <0.2658.0>) 
08:50:48.792 [error] Mnesia2('d523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'): ** ERROR ** mnesia2_event got unexpected event: {'EXIT',<0.1663.0>,killed}

08:50:48.792 [error] Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.1661.0> exit with reason killed in context child_terminated

----------------------------------------------------
2016-04-12 08:50:48.816
ending test case: mnesia2_down


----------------------------------------------------
2016-04-12 08:50:48.919
ending test group: qlc


----------------------------------------------------
2016-04-12 08:50:48.945
starting test group: registry


----------------------------------------------------
2016-04-12 08:50:49.039
starting test case: good_dump

08:50:49.042 [error] Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.2594.0> exit with reason killed in context child_terminated
08:50:49.042 [error] Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.2594.0> exit with reason reached_max_restart_intensity in context shutdown
08:50:49.043 [error] Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.2575.0> exit with reason killed in context child_terminated
08:50:49.043 [error] Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.2575.0> exit with reason reached_max_restart_intensity in context shutdown
08:50:49.043 [error] gen_server mnesia2_subscr terminated with reason: killed
08:50:49.043 [error] CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:50:49.043 [error] gen_server mnesia2_monitor terminated with reason: killed
08:50:49.043 [error] CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:50:49.043 [error] gen_server mnesia2_recover terminated with reason: killed
08:50:49.043 [error] CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:50:49.044 [info] Application mnesia2 exited with reason: shutdown
08:50:49.502 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.2710.0>

----------------------------------------------------
2016-04-12 08:50:49.534
ending test case: good_dump


----------------------------------------------------
2016-04-12 08:50:49.564
starting test case: bad_dump

08:50:49.608 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.2804.0>

----------------------------------------------------
2016-04-12 08:50:49.616
ending test case: bad_dump


----------------------------------------------------
2016-04-12 08:50:49.698
ending test group: registry


----------------------------------------------------
2016-04-12 08:50:49.724
starting test group: config


----------------------------------------------------
2016-04-12 08:50:49.804
starting test case: access_module

08:50:50.857 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.2914.0>
08:50:50.862 [info] Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:50:52.120 [error] Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.2925.0> exit with reason killed in context child_terminated
08:50:52.121 [error] Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.2925.0> exit with reason reached_max_restart_intensity in context shutdown
08:50:52.122 [error] CRASH REPORT Process <0.2905.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:50:52.122 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-12 08:50:53.145
ending test case: access_module


----------------------------------------------------
2016-04-12 08:50:53.173
starting test case: auto_repair

08:50:54.206 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.3020.0>
08:50:54.210 [info] Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:50:54.213 [info] Application mnesia2 exited with reason: stopped
08:50:54.220 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.3068.0>
08:50:54.226 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.3116.0>

----------------------------------------------------
2016-04-12 08:50:55.243
ending test case: auto_repair


----------------------------------------------------
2016-04-12 08:50:55.271
starting test case: backup_module

08:50:56.315 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.3188.0>
08:50:56.319 [info] Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:50:56.345 [error] CRASH REPORT Process <0.3179.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:50:56.345 [info] Application mnesia2 exited with reason: killed
08:50:58.384 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.3271.0>
08:50:58.388 [info] Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:50:58.392 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Restore aborted. mnesia2_config_backup:open_read["NonExisting.FILE"] -> {enoent,error}

08:50:58.394 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Restore aborted. mnesia2_config_backup:open_read["/home/travis/build/lrascao/mnesia2/logs/ct_run.test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12.2016-04-12_08.50.13/Mnesia2.test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12/LATEST.LOG"] -> badarg

08:50:58.395 [error] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}}} ({error,{already_started,<0.3347.0>}})

08:50:58.395 [error] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_11,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_11,shutdown]}}}} ({error,{already_started,<0.3347.0>}})

08:50:58.395 [error] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_13,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_13,shutdown]}}}} ({error,{already_started,<0.3347.0>}})

08:50:58.395 [error] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_12,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_12,shutdown]}}}} ({error,{already_started,<0.3347.0>}})

08:50:58.396 [error] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_10,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_10,shutdown]}}}} ({error,{already_started,<0.3347.0>}})

08:50:58.396 [error] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_15,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_15,shutdown]}}}} ({error,{already_started,<0.3347.0>}})

08:50:58.396 [error] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_17,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_17,shutdown]}}}} ({error,{already_started,<0.3347.0>}})

08:50:58.396 [error] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_16,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_16,shutdown]}}}} ({error,{already_started,<0.3347.0>}})


----------------------------------------------------
2016-04-12 08:50:59.424
ending test case: backup_module


----------------------------------------------------
2016-04-12 08:50:59.451
starting test case: debug

08:51:00.481 [warning] lager_error_logger_h dropped 15 messages in the last second that exceeded the limit of 50 messages/sec
08:51:00.482 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): mnesia2_monitor starting: <0.3392.0>

08:51:00.482 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Mnesia2 debug level set to verbose
08:51:00.483 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): mnesia2_subscr starting: <0.3393.0>

08:51:00.483 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): mnesia2_locker starting: <0.3394.0>

08:51:00.483 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): mnesia2_recover starting: <0.3395.0>

08:51:00.483 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): mnesia2_tm starting: <0.3396.0>

08:51:00.484 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Schema initiated from: default

08:51:00.484 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.3396.0>
08:51:00.484 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): mnesia2_controller starting: <0.3399.0>

08:51:00.485 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): mnesia2_late_loader starting: <0.3400.0>

08:51:00.486 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Intend to load tables: []

08:51:00.486 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): mnesia2_tm_1 starting: <0.3402.0>

08:51:00.486 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): mnesia2_tm_2 starting: <0.3403.0>

08:51:00.487 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): mnesia2_tm_3 starting: <0.3404.0>

08:51:00.487 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): mnesia2_tm_4 starting: <0.3405.0>

08:51:00.487 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): mnesia2_tm_5 starting: <0.3406.0>

08:51:00.487 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): mnesia2_tm_6 starting: <0.3407.0>

08:51:00.488 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): mnesia2_tm_7 starting: <0.3408.0>

08:51:00.488 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): mnesia2_tm_8 starting: <0.3409.0>

08:51:02.512 [warning] lager_error_logger_h dropped 19 messages in the last second that exceeded the limit of 50 messages/sec
08:51:02.513 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): mnesia2_monitor starting: <0.3448.0>

08:51:02.513 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Version: "1.0.0"

08:51:02.513 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env access_module: mnesia2

08:51:02.514 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env auto_repair: true

08:51:02.514 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env backup_module: mnesia2_backup

08:51:02.514 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env debug: debug

08:51:02.515 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12.2016-04-12_08.50.13/Mnesia2.test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12"

08:51:02.515 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env dump_disc_copies_at_startup: true

08:51:02.516 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env dump_log_load_regulation: false

08:51:02.516 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env dump_log_time_threshold: 180000

08:51:02.517 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env dump_log_update_in_place: true

08:51:02.517 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env dump_log_write_threshold: 1000

08:51:02.518 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env event_module: mnesia2_event

08:51:02.518 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env extra_db_nodes: []

08:51:02.519 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env ignore_fallback_at_startup: false

08:51:02.519 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env fallback_error_function: {mnesia2,lkill}

08:51:02.520 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env max_wait_for_decision: infinity

08:51:02.524 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env schema_location: opt_disc

08:51:02.524 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env core_dir: false

08:51:02.525 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.3452.0>
08:51:02.526 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env pid_sort_order: false

08:51:04.559 [warning] lager_error_logger_h dropped 45 messages in the last second that exceeded the limit of 50 messages/sec
08:51:04.559 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): mnesia2_monitor starting: <0.3529.0>

08:51:04.560 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Version: "1.0.0"

08:51:04.561 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env access_module: mnesia2

08:51:04.561 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env auto_repair: true

08:51:04.561 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env backup_module: mnesia2_backup

08:51:04.562 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env debug: trace

08:51:04.562 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12.2016-04-12_08.50.13/Mnesia2.test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12"

08:51:04.562 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env dump_disc_copies_at_startup: true

08:51:04.562 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env dump_log_load_regulation: false

08:51:04.563 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env dump_log_time_threshold: 180000

08:51:04.563 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env dump_log_update_in_place: true

08:51:04.564 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env dump_log_write_threshold: 1000

08:51:04.564 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env event_module: mnesia2_event

08:51:04.564 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env extra_db_nodes: []

08:51:04.564 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env ignore_fallback_at_startup: false

08:51:04.564 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env fallback_error_function: {mnesia2,lkill}

08:51:04.565 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env max_wait_for_decision: infinity

08:51:04.565 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env schema_location: opt_disc

08:51:04.565 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env core_dir: false

08:51:04.565 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env pid_sort_order: false

08:51:04.565 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env no_table_loaders: 2

08:51:04.565 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env dc_dump_limit: 4

08:51:04.566 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env send_compressed: 0

08:51:04.566 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env send_max_packets: 20

08:51:04.566 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env send_max_transfer_size: 7500

08:51:04.566 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env async_dirty_buffer_size: 524288

08:51:04.567 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env async_dirty_max_buffer_file_size: 100000000

08:51:04.567 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env async_dirty_tx_backlog_threshold: 200000

08:51:04.567 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env async_dirty_buffer_min_runtime: 10000

08:51:04.567 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env async_dirty_buffer_drained_cutoff: 5

08:51:04.567 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Mnesia2 debug level set to trace
08:51:04.568 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.3533.0>
08:51:04.569 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): mnesia2_subscr starting: <0.3530.0>

08:51:04.569 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): mnesia2_locker starting: <0.3531.0>

08:51:04.569 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): mnesia2_recover starting: <0.3532.0>

08:51:04.569 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): mnesia2_tm starting: <0.3533.0>

08:51:04.569 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Schema initiated from: default

08:51:04.569 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): debug fun {mnesia2_tm,init} in ets mnesia2_debug does not exist, ignoring
08:51:04.570 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): mnesia2_controller starting: <0.3536.0>

08:51:04.570 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): mnesia2_late_loader starting: <0.3537.0>

08:51:04.571 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Intend to load tables: []

08:51:06.597 [warning] lager_error_logger_h dropped 41 messages in the last second that exceeded the limit of 50 messages/sec
08:51:06.597 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): mnesia2_monitor starting: <0.3610.0>

08:51:06.598 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Version: "1.0.0"

08:51:06.599 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env access_module: mnesia2

08:51:06.599 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env auto_repair: true

08:51:06.599 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env backup_module: mnesia2_backup

08:51:06.600 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env debug: debug

08:51:06.600 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12.2016-04-12_08.50.13/Mnesia2.test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12"

08:51:06.601 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env dump_disc_copies_at_startup: true

08:51:06.601 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.3614.0>
08:51:06.601 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env dump_log_load_regulation: false

08:51:06.601 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env dump_log_time_threshold: 180000

08:51:06.602 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env dump_log_update_in_place: true

08:51:06.602 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env dump_log_write_threshold: 1000

08:51:06.603 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env event_module: mnesia2_event

08:51:06.603 [info] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): Env extra_db_nodes: []

08:51:08.627 [warning] lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
08:51:08.629 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.3664.0>
08:51:08.632 [info] Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:51:08.633 [error] CRASH REPORT Process <0.3655.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:51:08.633 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-12 08:51:09.664
ending test case: debug


----------------------------------------------------
2016-04-12 08:51:09.694
starting test case: dir

08:51:10.727 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.3728.0>
08:51:10.730 [info] Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:51:10.732 [error] CRASH REPORT Process <0.3719.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:51:10.732 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-12 08:51:11.765
ending test case: dir


----------------------------------------------------
2016-04-12 08:51:11.801
starting test case: dump_log_load_regulation

08:51:11.839 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.3799.0>
08:51:11.842 [info] Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:51:11.847 [info] Application mnesia2 exited with reason: stopped
08:51:11.855 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.3860.0>
08:51:14.726 [error] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

08:51:21.676 [error] Mnesia2('test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

08:51:26.926 [error] CRASH REPORT Process <0.3851.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:51:26.926 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-12 08:51:27.948
ending test case: dump_log_load_regulation


----------------------------------------------------
2016-04-12 08:51:28.026
starting test case: dump_log_time_threshold

08:51:29.327 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.4382.0>
08:51:29.329 [info] Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:51:35.351 [error] CRASH REPORT Process <0.4373.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:51:35.352 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-12 08:51:36.374
ending test case: dump_log_time_threshold


----------------------------------------------------
2016-04-12 08:51:36.403
starting test case: dump_log_write_threshold

08:51:37.686 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.4482.0>
08:51:37.689 [info] Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:51:38.848 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-12 08:51:39.862
ending test case: dump_log_write_threshold


----------------------------------------------------
2016-04-12 08:51:39.933
starting test case: dump_log_update_in_place

08:51:40.987 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.4598.0>
08:51:40.992 [info] Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:51:41.002 [error] Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.4609.0> exit with reason killed in context child_terminated
08:51:41.003 [error] Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.4609.0> exit with reason reached_max_restart_intensity in context shutdown
08:51:41.004 [error] CRASH REPORT Process <0.4589.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:51:41.004 [info] Application mnesia2 exited with reason: killed
08:51:43.046 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.4665.0>
08:51:43.050 [info] Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:51:43.084 [error] CRASH REPORT Process <0.4656.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:51:43.084 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-12 08:51:44.120
ending test case: dump_log_update_in_place


----------------------------------------------------
2016-04-12 08:51:44.148
starting test case: event_module

08:51:45.214 [warning] lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
08:51:45.227 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.4757.0>
08:51:45.229 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.1794.0>
08:51:45.240 [info] Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
Got event: {mnesia2_system_event,
               {mnesia2_up,
                   'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'}}
Got event: {mnesia2_system_event,
               {mnesia2_up,
                   'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'}}
08:51:45.548 [info] Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
Got event: {mnesia2_system_event,
               {mnesia2_down,
                   'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'}}
08:51:46.549 [error] gen_server <0.1847.0> terminated with reason: killed
08:51:46.549 [error] CRASH REPORT Process <0.1847.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:51:46.550 [error] CRASH REPORT Process <0.1785.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:51:46.550 [info] Application mnesia2 exited with reason: killed
08:51:48.584 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.1863.0>
Got event: {mnesia2_system_event,
               {mnesia2_up,
                   'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'}}
08:51:48.589 [info] Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
Got event: {mnesia2_system_event,
               {mnesia2_up,
                   'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'}}
Got event: {'EXIT',<0.4754.0>,killed}
08:51:49.592 [error] Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.4752.0> exit with reason killed in context child_terminated
Got event: {mnesia2_system_event,
               {mnesia2_down,
                   'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'}}
08:51:49.592 [error] Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.4752.0> exit with reason reached_max_restart_intensity in context shutdown
08:51:49.592 [error] gen_server mnesia2_monitor terminated with reason: killed
08:51:49.592 [error] gen_server mnesia2_recover terminated with reason: killed
08:51:49.592 [error] CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:51:49.596 [info] Application mnesia2 exited with reason: shutdown

----------------------------------------------------
2016-04-12 08:51:50.618
ending test case: event_module


----------------------------------------------------
2016-04-12 08:51:50.646
starting test case: inconsistent_database

Got event: {'EXIT',<37236.1860.0>,killed}
08:51:50.661 [error] Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.1858.0> exit with reason killed in context child_terminated
08:51:50.661 [error] Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.1858.0> exit with reason reached_max_restart_intensity in context shutdown
08:51:50.661 [error] gen_server mnesia2_monitor terminated with reason: killed
08:51:50.661 [error] CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:51:50.661 [error] gen_server mnesia2_recover terminated with reason: killed
08:51:50.661 [error] CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:51:50.663 [info] Application mnesia2 exited with reason: shutdown
08:51:51.737 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.4864.0>
08:51:51.741 [info] Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:51:51.757 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.1946.0>
08:51:51.761 [info] Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:51:51.762 [error] CRASH REPORT Process <0.1936.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:51:51.762 [info] Application mnesia2 exited with reason: killed
08:51:51.763 [error] CRASH REPORT Process <0.4855.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:51:51.764 [info] Application mnesia2 exited with reason: killed
08:51:52.685 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.4939.0>
08:51:52.687 [info] Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:51:57.199 [info] Application mnesia2 exited with reason: stopped
08:51:57.265 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.2015.0>
08:51:57.266 [info] Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:51:57.276 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.5063.0>
08:51:57.282 [info] Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:52:08.890 [info] Application mnesia2 exited with reason: stopped
08:52:08.893 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-12 08:52:09.936
ending test case: inconsistent_database


----------------------------------------------------
2016-04-12 08:52:09.979
starting test case: max_wait_for_decision


----------------------------------------------------
2016-04-12 08:52:09.981
ending test case: max_wait_for_decision


----------------------------------------------------
2016-04-12 08:52:10.009
starting test case: send_compressed

08:52:10.064 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.5194.0>
08:52:10.072 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.2137.0>
08:52:10.075 [info] Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:52:10.090 [info] Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:52:10.111 [error] gen_server <0.2189.0> terminated with reason: killed
08:52:10.111 [error] CRASH REPORT Process <0.2189.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:52:10.111 [error] CRASH REPORT Process <0.2128.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:52:10.111 [info] Application mnesia2 exited with reason: killed
08:52:10.133 [error] CRASH REPORT Process <0.5185.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:52:10.133 [info] Application mnesia2 exited with reason: killed
08:52:10.169 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.5282.0>
08:52:10.414 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.2225.0>

----------------------------------------------------
2016-04-12 08:52:11.839
ending test case: send_compressed


----------------------------------------------------
2016-04-12 08:52:11.866
starting test case: app_test


----------------------------------------------------
2016-04-12 08:52:11.887
ending test case: app_test


----------------------------------------------------
2016-04-12 08:52:11.940
starting test case: start_one_disc_full_then_one_disc_less

08:52:11.943 [warning] lager_error_logger_h dropped 28 messages in the last second that exceeded the limit of 50 messages/sec
08:52:11.943 [error] Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.2244.0> exit with reason killed in context child_terminated
08:52:11.943 [error] Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.2244.0> exit with reason reached_max_restart_intensity in context shutdown
08:52:11.944 [error] CRASH REPORT Process <0.2216.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:52:11.944 [info] Application mnesia2 exited with reason: killed
08:52:13.016 [warning] lager_error_logger_h dropped 12 messages in the last second that exceeded the limit of 50 messages/sec
08:52:13.021 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.5405.0>
08:52:13.024 [info] Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:52:13.038 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.2328.0>
08:52:13.050 [info] Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:52:13.067 [error] Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.5416.0> exit with reason killed in context child_terminated
08:52:13.066 [error] gen_server <0.2341.0> terminated with reason: killed
08:52:13.067 [error] Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.5416.0> exit with reason reached_max_restart_intensity in context shutdown
08:52:13.066 [error] CRASH REPORT Process <0.2341.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:52:13.069 [error] Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.5400.0> exit with reason killed in context child_terminated
08:52:13.067 [error] CRASH REPORT Process <0.2319.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:52:13.067 [info] Application mnesia2 exited with reason: killed
08:52:13.069 [error] Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.5400.0> exit with reason reached_max_restart_intensity in context shutdown
08:52:13.069 [error] gen_server mnesia2_subscr terminated with reason: killed
08:52:13.069 [error] CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746

----------------------------------------------------
2016-04-12 08:52:14.095
ending test case: start_one_disc_full_then_one_disc_less


----------------------------------------------------
2016-04-12 08:52:14.124
starting test case: start_first_one_disc_less_then_one_disc_full

08:52:15.166 [warning] lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
08:52:15.188 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.5516.0>
08:52:15.190 [info] Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:52:15.196 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.2403.0>
08:52:15.203 [info] Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:52:15.217 [error] gen_server <0.5578.0> terminated with reason: killed
08:52:15.216 [error] gen_server <0.2415.0> terminated with reason: killed
08:52:15.217 [error] CRASH REPORT Process <0.5578.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:52:15.216 [error] CRASH REPORT Process <0.2415.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:52:15.218 [error] CRASH REPORT Process <0.5507.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:52:15.218 [info] Application mnesia2 exited with reason: killed
08:52:15.216 [error] CRASH REPORT Process <0.2394.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:52:15.217 [info] Application mnesia2 exited with reason: killed
08:52:17.242 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.2462.0>
08:52:17.243 [info] Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:52:18.240 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.5596.0>
08:52:18.257 [info] Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:52:18.294 [error] Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.5613.0> exit with reason killed in context child_terminated
08:52:18.294 [error] Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.5613.0> exit with reason reached_max_restart_intensity in context shutdown
08:52:18.296 [error] gen_server <0.5657.0> terminated with reason: killed
08:52:18.296 [error] CRASH REPORT Process <0.5657.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:52:18.296 [error] CRASH REPORT Process <0.5587.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:52:18.296 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-12 08:52:19.320
ending test case: start_first_one_disc_less_then_one_disc_full


----------------------------------------------------
2016-04-12 08:52:19.347
starting test case: start_first_one_disc_less_then_two_more_disc_less

08:52:19.718 [error] CRASH REPORT Process <0.2453.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:52:19.718 [info] Application mnesia2 exited with reason: killed
08:52:20.816 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.5721.0>
08:52:20.820 [info] Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:52:20.824 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.2551.0>
08:52:20.829 [info] Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:52:21.112 [info] Application lager started on node 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:52:21.112 [info] Application poolgirl started on node 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:52:21.149 [info] starting mnesia2_tm, 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.101.0>
08:52:21.171 [info] Application mnesia2 started on node 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12'

----------------------------------------------------
2016-04-12 08:52:22.362
ending test case: start_first_one_disc_less_then_two_more_disc_less

08:52:21.232 [error] CRASH REPORT Process <0.92.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:52:21.228 [error] gen_server <0.2602.0> terminated with reason: killed
08:52:21.232 [info] Application mnesia2 exited with reason: killed
08:52:21.226 [error] gen_server <0.5774.0> terminated with reason: killed
08:52:21.228 [error] CRASH REPORT Process <0.2602.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:52:21.226 [error] CRASH REPORT Process <0.5774.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746

----------------------------------------------------
2016-04-12 08:52:22.394
starting test case: schema_location_and_extra_db_nodes_combinations

08:52:21.229 [error] gen_server <0.2564.0> terminated with reason: killed
08:52:21.226 [error] gen_server <0.5766.0> terminated with reason: killed
08:52:21.229 [error] CRASH REPORT Process <0.2564.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:52:21.227 [error] CRASH REPORT Process <0.5766.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:52:21.229 [error] CRASH REPORT Process <0.2542.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:52:21.229 [info] Application mnesia2 exited with reason: killed
08:52:21.228 [error] CRASH REPORT Process <0.5712.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:52:21.228 [info] Application mnesia2 exited with reason: killed
08:52:23.455 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.5816.0>
08:52:23.457 [info] Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:52:23.466 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.2632.0>
08:52:23.482 [info] Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:52:23.487 [error] CRASH REPORT Process <0.2623.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:52:23.487 [info] Application mnesia2 exited with reason: killed
08:52:23.488 [error] CRASH REPORT Process <0.5807.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:52:23.488 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-12 08:52:24.510
ending test case: schema_location_and_extra_db_nodes_combinations


----------------------------------------------------
2016-04-12 08:52:24.539
starting test case: table_load_to_disc_less_nodes

08:52:25.574 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.5910.0>
08:52:25.578 [info] Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:52:25.590 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.2702.0>
08:52:25.595 [info] Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:52:25.620 [error] gen_server <0.5954.0> terminated with reason: killed
08:52:25.622 [error] CRASH REPORT Process <0.2693.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:52:25.622 [info] Application mnesia2 exited with reason: killed
08:52:25.620 [error] CRASH REPORT Process <0.5954.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:52:25.621 [error] CRASH REPORT Process <0.5901.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:52:25.621 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-12 08:52:26.649
ending test case: table_load_to_disc_less_nodes


----------------------------------------------------
2016-04-12 08:52:26.694
starting test case: schema_merge

08:52:27.892 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.5996.0>
08:52:27.896 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.2777.0>
08:52:27.900 [info] Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:52:28.199 [info] Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:52:28.202 [error] gen_server <0.2830.0> terminated with reason: killed
08:52:28.202 [error] CRASH REPORT Process <0.2830.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:52:28.203 [error] CRASH REPORT Process <0.2768.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:52:28.203 [info] Application mnesia2 exited with reason: killed
08:52:29.234 [error] CRASH REPORT Process <0.5987.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:52:29.234 [info] Application mnesia2 exited with reason: killed
08:52:31.387 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.2848.0>
08:52:31.389 [info] Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:52:37.825 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.6075.0>
08:52:37.844 [info] Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:52:37.860 [error] gen_server <0.6138.0> terminated with reason: killed
08:52:37.860 [error] CRASH REPORT Process <0.6138.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:52:37.861 [error] CRASH REPORT Process <0.6066.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:52:37.861 [info] Application mnesia2 exited with reason: killed
08:52:37.862 [error] gen_server <0.2917.0> terminated with reason: killed
08:52:37.862 [error] CRASH REPORT Process <0.2917.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:52:37.863 [error] CRASH REPORT Process <0.2839.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:52:37.863 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-12 08:52:38.904
ending test case: schema_merge


----------------------------------------------------
2016-04-12 08:52:38.957
starting test case: dynamic_basic

08:52:39.068 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.6185.0>
08:52:39.071 [info] Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:52:39.090 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.2947.0>
08:52:39.102 [info] Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:52:39.113 [info] starting mnesia2_tm, 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.191.0>
08:52:39.118 [info] Application mnesia2 started on node 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:52:39.177 [error] gen_server <0.3010.0> terminated with reason: killed
08:52:39.177 [error] CRASH REPORT Process <0.3010.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:52:39.177 [error] gen_server <0.2999.0> terminated with reason: killed
08:52:39.177 [error] CRASH REPORT Process <0.2999.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:52:39.177 [error] CRASH REPORT Process <0.2938.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:52:39.177 [info] Application mnesia2 exited with reason: killed
08:52:39.218 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.3038.0>
08:52:39.253 [error] gen_server <0.6272.0> terminated with reason: killed
08:52:39.253 [error] CRASH REPORT Process <0.6272.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:52:39.253 [error] gen_server <0.6249.0> terminated with reason: killed
08:52:39.253 [error] CRASH REPORT Process <0.6249.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:52:39.254 [error] gen_server <0.6288.0> terminated with reason: killed
08:52:39.254 [error] CRASH REPORT Process <0.6288.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:52:39.255 [error] CRASH REPORT Process <0.6176.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:52:39.255 [info] Application mnesia2 exited with reason: killed
08:52:39.274 [error] gen_server <0.274.0> terminated with reason: killed
08:52:39.274 [error] CRASH REPORT Process <0.274.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:52:39.275 [error] CRASH REPORT Process <0.182.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:52:39.275 [info] Application mnesia2 exited with reason: killed
08:52:39.330 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.3133.0>
08:52:39.362 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.6307.0>
08:52:39.373 [info] starting mnesia2_tm, 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.295.0>
08:52:39.381 [info] Application mnesia2 started on node 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:52:40.211 [error] gen_server <0.368.0> terminated with reason: killed
08:52:40.212 [error] CRASH REPORT Process <0.368.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:52:40.212 [error] gen_server <0.357.0> terminated with reason: killed
08:52:40.213 [error] CRASH REPORT Process <0.357.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:52:40.223 [error] CRASH REPORT Process <0.286.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:52:40.223 [info] Application mnesia2 exited with reason: killed
08:52:40.246 [info] starting mnesia2_tm, 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.392.0>
08:52:40.248 [info] Application mnesia2 started on node 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:52:42.312 [warning] lager_error_logger_h dropped 4 messages in the last second that exceeded the limit of 50 messages/sec
08:52:42.312 [error] gen_server <0.6405.0> terminated with reason: killed
08:52:42.312 [error] CRASH REPORT Process <0.6405.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:52:42.313 [error] gen_server <0.6377.0> terminated with reason: killed
08:52:42.313 [error] CRASH REPORT Process <0.6377.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:52:42.315 [error] CRASH REPORT Process <0.6298.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:52:42.315 [info] Application mnesia2 exited with reason: killed
08:52:42.334 [warning] lager_error_logger_h dropped 25 messages in the last second that exceeded the limit of 50 messages/sec
08:52:42.334 [error] gen_server <0.3226.0> terminated with reason: killed
08:52:42.334 [error] CRASH REPORT Process <0.3226.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:52:42.335 [error] CRASH REPORT Process <0.3124.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:52:42.335 [info] Application mnesia2 exited with reason: killed
08:52:42.358 [info] Application mnesia2 exited with reason: stopped
08:52:42.397 [info] starting mnesia2_tm, 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.498.0>
08:52:42.398 [info] Application mnesia2 started on node 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:52:42.432 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.6424.0>
08:52:42.434 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.3247.0>
08:52:42.448 [info] Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:52:42.470 [info] Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:52:42.980 [error] CRASH REPORT Process <0.489.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:52:42.981 [info] Application mnesia2 exited with reason: killed
08:52:43.012 [info] starting mnesia2_tm, 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.596.0>
08:52:43.013 [info] Application mnesia2 started on node 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:52:43.225 [error] gen_server <0.6517.0> terminated with reason: killed
08:52:43.225 [error] CRASH REPORT Process <0.6517.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:52:43.226 [error] CRASH REPORT Process <0.6415.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:52:43.226 [info] Application mnesia2 exited with reason: killed
08:52:43.246 [error] gen_server <0.3335.0> terminated with reason: killed
08:52:43.247 [error] CRASH REPORT Process <0.3335.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:52:43.247 [error] CRASH REPORT Process <0.3238.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:52:43.247 [info] Application mnesia2 exited with reason: killed
08:52:43.289 [info] Application mnesia2 exited with reason: stopped
08:52:43.308 [info] starting mnesia2_tm, 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.697.0>
08:52:43.340 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.6534.0>
08:52:43.366 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.3356.0>
08:52:43.372 [info] Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:52:43.654 [info] Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:52:44.186 [error] gen_server <0.3416.0> terminated with reason: killed
08:52:44.186 [error] CRASH REPORT Process <0.3416.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:52:44.187 [error] gen_server <0.3428.0> terminated with reason: killed
08:52:44.187 [error] CRASH REPORT Process <0.3428.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:52:44.187 [error] CRASH REPORT Process <0.3347.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:52:44.187 [info] Application mnesia2 exited with reason: killed
08:52:44.255 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.3451.0>
08:52:44.267 [info] Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:52:44.294 [error] gen_server <0.3464.0> terminated with reason: killed
08:52:44.294 [error] CRASH REPORT Process <0.3464.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:52:44.294 [error] gen_server <0.3482.0> terminated with reason: killed
08:52:44.295 [error] CRASH REPORT Process <0.3482.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:52:45.316 [warning] lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
08:52:45.320 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.3529.0>
08:52:45.337 [info] Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'

----------------------------------------------------
2016-04-12 08:52:45.361
ending test case: dynamic_basic


----------------------------------------------------
2016-04-12 08:52:45.402
starting test case: dynamic_ext

08:52:45.407 [error] gen_server <0.6601.0> terminated with reason: killed
08:52:45.406 [error] CRASH REPORT Process <0.3520.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:52:45.407 [error] gen_server <0.822.0> terminated with reason: killed
08:52:45.406 [info] Application mnesia2 exited with reason: killed
08:52:45.407 [error] CRASH REPORT Process <0.6601.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:52:45.407 [error] CRASH REPORT Process <0.822.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:52:45.408 [error] CRASH REPORT Process <0.6525.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:52:45.408 [info] Application mnesia2 exited with reason: killed
08:52:45.409 [error] CRASH REPORT Process <0.688.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:52:45.409 [info] Application mnesia2 exited with reason: killed
08:52:45.481 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.6680.0>
08:52:45.484 [info] Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:52:45.502 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.3608.0>
08:52:45.607 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.3702.0>
08:52:45.729 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.3792.0>
08:52:45.791 [info] Application mnesia2 exited with reason: stopped
08:52:45.809 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.3892.0>
08:52:46.335 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.6793.0>
08:52:46.362 [info] Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:52:46.389 [info] Application mnesia2 exited with reason: stopped
08:52:46.391 [warning] lager_error_logger_h dropped 48 messages in the last second that exceeded the limit of 50 messages/sec
08:52:46.391 [error] gen_server <0.3947.0> terminated with reason: killed
08:52:46.391 [error] CRASH REPORT Process <0.3947.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:52:46.393 [error] CRASH REPORT Process <0.3883.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:52:46.393 [info] Application mnesia2 exited with reason: killed
08:52:46.440 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.6876.0>
08:52:46.957 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.3974.0>
08:52:47.010 [info] Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'

----------------------------------------------------
2016-04-12 08:52:47.477
ending test case: dynamic_ext


----------------------------------------------------
2016-04-12 08:52:47.505
starting test case: dynamic_bad

08:52:47.508 [error] gen_server <0.4025.0> terminated with reason: killed
08:52:47.510 [error] CRASH REPORT Process <0.6867.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:52:47.510 [info] Application mnesia2 exited with reason: killed
08:52:47.508 [error] CRASH REPORT Process <0.4025.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:52:47.509 [error] CRASH REPORT Process <0.3965.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:52:47.509 [info] Application mnesia2 exited with reason: killed
08:52:47.597 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.6977.0>
08:52:47.599 [info] Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:52:47.618 [info] starting mnesia2_tm, 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.849.0>
08:52:47.656 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.4067.0>
08:52:47.662 [info] Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:52:47.960 [info] Application mnesia2 started on node 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:52:48.050 [error] gen_server <0.7041.0> terminated with reason: killed
08:52:48.050 [error] CRASH REPORT Process <0.7041.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:52:48.053 [error] gen_server <0.4120.0> terminated with reason: killed
08:52:48.050 [error] gen_server <0.7034.0> terminated with reason: killed
08:52:48.051 [error] gen_server <0.913.0> terminated with reason: killed
08:52:48.053 [error] CRASH REPORT Process <0.4120.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:52:48.051 [error] CRASH REPORT Process <0.913.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:52:48.054 [error] CRASH REPORT Process <0.4057.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:52:48.053 [error] CRASH REPORT Process <0.840.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:52:48.050 [error] CRASH REPORT Process <0.7034.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:52:48.054 [info] Application mnesia2 exited with reason: killed
08:52:48.054 [info] Application mnesia2 exited with reason: killed
08:52:48.084 [info] starting mnesia2_tm, 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.954.0>
08:52:48.086 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.4157.0>
08:52:48.086 [info] Application mnesia2 started on node 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:52:48.088 [info] Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:52:48.052 [error] CRASH REPORT Process <0.6968.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:52:48.053 [info] Application mnesia2 exited with reason: killed
08:52:48.124 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.7089.0>
08:52:48.135 [info] Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:52:48.160 [error] gen_server <0.7157.0> terminated with reason: killed
08:52:48.161 [error] CRASH REPORT Process <0.7157.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:52:48.161 [error] gen_server <0.7128.0> terminated with reason: killed
08:52:48.162 [error] CRASH REPORT Process <0.7128.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:52:48.158 [error] gen_server <0.1003.0> terminated with reason: killed
08:52:48.158 [error] gen_server <0.4212.0> terminated with reason: killed
08:52:48.158 [error] CRASH REPORT Process <0.4212.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:52:48.158 [error] CRASH REPORT Process <0.1003.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:52:48.161 [error] CRASH REPORT Process <0.4148.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:52:48.158 [error] gen_server <0.1012.0> terminated with reason: killed
08:52:48.161 [info] Application mnesia2 exited with reason: killed
08:52:48.206 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.4235.0>
08:52:48.158 [error] CRASH REPORT Process <0.1012.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:52:48.206 [info] starting mnesia2_tm, 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.1031.0>
08:52:48.228 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.7181.0>

----------------------------------------------------
2016-04-12 08:52:58.249
ending test case: dynamic_bad

08:52:58.244 [error] Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at undefined exit with reason killed in context start_error
08:52:58.244 [error] gen_server mnesia2_monitor terminated with reason: killed
08:52:58.244 [error] gen_server mnesia2_recover terminated with reason: killed
08:52:58.244 [error] CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:52:58.244 [error] gen_server mnesia2_snmp_sup terminated with reason: killed
08:52:58.244 [error] CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:52:58.244 [error] gen_server mnesia2_subscr terminated with reason: killed
08:52:58.244 [error] CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:52:58.244 [error] CRASH REPORT Process <0.7172.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}} in application_master:init/4 line 133
08:52:58.244 [info] Application mnesia2 exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}}
08:52:58.244 [error] CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746

----------------------------------------------------
2016-04-12 08:52:58.341
starting test case: unknown_config

08:52:58.346 [warning] lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
08:52:58.344 [error] gen_server <0.4279.0> terminated with reason: killed
08:52:58.344 [error] CRASH REPORT Process <0.4279.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:52:58.346 [error] Supervisor mnesia2_kernel_sup had child mnesia2_controller started with mnesia2_controller:start() at <0.1034.0> exit with reason killed in context child_terminated
08:52:58.345 [error] CRASH REPORT Process <0.4226.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:52:58.345 [info] Application mnesia2 exited with reason: killed
08:52:58.347 [error] Supervisor mnesia2_kernel_sup had child mnesia2_controller started with mnesia2_controller:start() at <0.1034.0> exit with reason reached_max_restart_intensity in context shutdown
08:52:58.347 [error] gen_server <0.1080.0> terminated with reason: killed
08:52:58.347 [error] CRASH REPORT Process <0.1080.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
08:52:58.347 [error] CRASH REPORT Process <0.1022.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
08:52:58.347 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-12 08:53:00.416
ending test case: unknown_config


----------------------------------------------------
2016-04-12 08:53:00.506
ending test group: config


----------------------------------------------------
2016-04-12 08:53:00.535
starting test group: examples


----------------------------------------------------
2016-04-12 08:53:00.630
starting test case: bup


----------------------------------------------------
2016-04-12 08:53:00.658
ending test case: bup


- - - - - - - - - - - - - - - - - - - - - - - - - -
Error detected: error
- - - - - - - - - - - - - - - - - - - - - - - - - -

Testing lrascao.mnesia2.mnesia2_extra_light_SUITE: *** FAILED test case 41 of 52 ***

----------------------------------------------------
2016-04-12 08:53:00.690
starting test case: company


----------------------------------------------------
2016-04-12 08:53:00.692
ending test case: company


----------------------------------------------------
2016-04-12 08:53:00.720
starting test case: meter

08:53:01.091 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.7290.0>
08:53:01.094 [info] Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:53:05.491 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-12 08:53:05.495
ending test case: meter


----------------------------------------------------
2016-04-12 08:53:05.549
starting test case: replica_test

08:53:05.653 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.7426.0>
08:53:05.654 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.4326.0>
08:53:05.656 [info] starting mnesia2_tm, 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.1127.0>
08:53:05.681 [info] Application mnesia2 started on node 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:53:05.695 [info] Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:53:05.974 [info] Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:53:12.072 [info] Application mnesia2 exited with reason: stopped
08:53:12.080 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-12 08:53:12.103
ending test case: replica_test

08:53:12.103 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-12 08:53:12.134
starting test case: sticky_replica_test

08:53:12.217 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.7555.0>
08:53:12.220 [info] Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:53:12.245 [info] starting mnesia2_tm, 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.1242.0>
08:53:12.248 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.4442.0>
08:53:12.265 [info] Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:53:12.550 [info] Application mnesia2 started on node 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:53:18.674 [info] Application mnesia2 exited with reason: stopped
08:53:18.680 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-12 08:53:18.681
ending test case: sticky_replica_test

08:53:18.681 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-12 08:53:18.719
starting test case: dist_test

08:53:18.828 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.7684.0>
08:53:18.831 [info] Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:53:18.842 [info] starting mnesia2_tm, 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.1358.0>
08:53:18.872 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.4557.0>
08:53:18.888 [info] Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:53:19.148 [info] Application mnesia2 started on node 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:53:41.700 [info] Application mnesia2 exited with reason: stopped
08:53:41.740 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-12 08:53:41.741
ending test case: dist_test

08:53:41.740 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-12 08:53:41.792
starting test case: conflict_test

08:53:43.210 [info] starting mnesia2_tm, 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.2484.0>
08:53:43.213 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.8823.0>
08:53:43.212 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.5680.0>
08:53:43.230 [info] Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:53:43.233 [info] Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:53:43.515 [info] Application mnesia2 started on node 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:53:49.925 [info] Application mnesia2 exited with reason: stopped
08:53:49.948 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-12 08:53:49.961
ending test case: conflict_test

08:53:49.961 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-12 08:53:49.993
starting test case: frag_test

08:53:50.095 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.8960.0>
08:53:50.099 [info] Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:53:50.102 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.5806.0>
08:53:50.123 [info] starting mnesia2_tm, 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.2610.0>
08:53:50.138 [info] Application mnesia2 started on node 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:53:50.423 [info] Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:53:56.828 [info] Application mnesia2 exited with reason: stopped
08:53:56.830 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-12 08:53:56.834
ending test case: frag_test

08:53:56.833 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-12 08:53:56.897
starting test case: frag2_test

08:53:56.997 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.10441.0>
08:53:57.000 [info] Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:53:57.003 [info] starting mnesia2_tm, 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.4079.0>
08:53:57.009 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.7278.0>
08:53:57.027 [info] Application mnesia2 started on node 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:53:57.050 [info] Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:54:03.380 [info] Application mnesia2 exited with reason: stopped
08:54:03.408 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-12 08:54:03.409
ending test case: frag2_test

08:54:03.409 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-12 08:54:03.440
starting test case: remote_test

08:54:03.536 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.12164.0>
08:54:03.538 [info] Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:54:03.557 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.7625.0>
08:54:03.567 [info] starting mnesia2_tm, 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.5337.0>
08:54:03.575 [info] Application mnesia2 started on node 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:54:03.607 [info] Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:54:09.787 [info] Application mnesia2 exited with reason: stopped
08:54:09.798 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-12 08:54:09.818
ending test case: remote_test

08:54:09.818 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-12 08:54:09.848
starting test case: remote_frag2_test

08:54:09.948 [info] starting mnesia2_tm, 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.12294.0>
08:54:09.951 [info] starting mnesia2_tm, 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.5449.0>
08:54:09.976 [info] starting mnesia2_tm, 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12', <0.8420.0>
08:54:09.982 [info] Application mnesia2 started on node 'd523303o523309n523311@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:54:10.254 [info] Application mnesia2 started on node 'test4438@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:54:10.263 [info] Application mnesia2 started on node 'd523358o523350n523353@testing-worker-linux-docker-0c73b48b-3366-linux-12'
08:54:16.520 [info] Application mnesia2 exited with reason: stopped
08:54:16.524 [info] Application mnesia2 exited with reason: stopped
08:54:16.526 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-12 08:54:16.526
ending test case: remote_frag2_test


----------------------------------------------------
2016-04-12 08:54:16.657
ending test group: examples


----------------------------------------------------
2016-04-12 08:54:16.687
ending test group: extra_light


----------------------------------------------------
2016-04-12 08:54:16.712
starting test case: clean_up_suite


----------------------------------------------------
2016-04-12 08:54:16.746
ending test case: clean_up_suite

Testing lrascao.mnesia2.mnesia2_extra_light_SUITE: TEST COMPLETE, 51 ok, 1 failed of 52 test cases

Cover analysing...
Updating /home/travis/build/lrascao/mnesia2/logs/index.html... done
Updating /home/travis/build/lrascao/mnesia2/logs/all_runs.html... done

