2016-04-10 22:34:36.884 [info] <0.7.0> Application lager started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:34:36.884 [info] <0.7.0> Application poolgirl started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:34:36.935 [info] <0.100.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.100.0>
2016-04-10 22:34:37.113 [error] <0.99.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-10 22:34:36.123 [info] <0.7.0> Application lager started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:34:36.123 [info] <0.7.0> Application poolgirl started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:34:36.145 [info] <0.495.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.495.0>
2016-04-10 22:34:36.163 [info] <0.563.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.563.0>
2016-04-10 22:34:36.675 [info] <0.673.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.673.0>
2016-04-10 22:34:37.113 [error] <0.664.0> CRASH REPORT Process <0.664.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:37.113 [error] <0.99.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:34:37.113 [error] <0.93.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.95.0> exit with reason killed in context child_terminated
2016-04-10 22:34:37.113 [error] <0.93.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.95.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:34:37.113 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:34:37.113 [error] <0.97.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-10 22:34:37.113 [error] <0.97.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:34:37.113 [error] <0.96.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-10 22:34:37.157 [info] <0.800.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.800.0>
2016-04-10 22:34:37.160 [info] <0.7.0> Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:34:37.329 [error] <0.794.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): ** ERROR ** (ignoring core) ** FATAL ** A fallback is installed and Mnesia2 must be restarted. Forcing shutdown after mnesia2_down from 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'...

2016-04-10 22:34:37.329 [error] <0.795.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_locker:start() at <0.798.0> exit with reason killed in context child_terminated
2016-04-10 22:34:37.329 [error] <0.795.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_locker:start() at <0.798.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:34:37.331 [error] <0.793.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.795.0> exit with reason shutdown in context child_terminated
2016-04-10 22:34:37.113 [info] <0.7.0> Application mnesia2 exited with reason: shutdown
2016-04-10 22:34:37.161 [info] <0.216.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.216.0>
2016-04-10 22:34:37.376 [info] <0.369.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.369.0>
2016-04-10 22:34:37.457 [info] <0.459.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.459.0>
2016-04-10 22:34:37.370 [info] <0.928.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.928.0>
2016-04-10 22:34:37.437 [info] <0.1028.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.1028.0>
2016-04-10 22:34:38.158 [warning] <0.6.0> lager_error_logger_h dropped 7 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:34:38.158 [error] <0.1089.0> gen_server <0.1089.0> terminated with reason: killed
2016-04-10 22:34:38.159 [warning] <0.6.0> lager_error_logger_h dropped 41 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:34:38.159 [error] <0.450.0> CRASH REPORT Process <0.450.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:38.158 [error] <0.1089.0> CRASH REPORT Process <0.1089.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:34:38.160 [error] <0.1019.0> CRASH REPORT Process <0.1019.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:38.159 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:34:38.213 [info] <0.548.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.548.0>
2016-04-10 22:34:38.216 [info] <0.7.0> Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:34:38.706 [error] <0.661.0> gen_server <0.661.0> terminated with reason: killed
2016-04-10 22:34:38.706 [error] <0.661.0> CRASH REPORT Process <0.661.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:34:38.707 [error] <0.539.0> CRASH REPORT Process <0.539.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:38.160 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:34:38.208 [info] <0.1151.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.1151.0>
2016-04-10 22:34:38.210 [info] <0.7.0> Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:34:38.305 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:34:38.320 [info] <0.1263.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.1263.0>
2016-04-10 22:34:38.773 [info] <0.1495.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.1495.0>
2016-04-10 22:34:38.966 [info] <0.1609.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.1609.0>
2016-04-10 22:34:39.072 [warning] <0.6.0> lager_error_logger_h dropped 8 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:34:39.072 [error] <0.1665.0> gen_server <0.1665.0> terminated with reason: killed
2016-04-10 22:34:38.707 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:34:38.778 [info] <0.762.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.762.0>
2016-04-10 22:34:38.971 [info] <0.861.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.861.0>
2016-04-10 22:34:39.072 [warning] <0.6.0> lager_error_logger_h dropped 35 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:34:39.072 [error] <0.858.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-10 22:34:39.072 [error] <0.1665.0> CRASH REPORT Process <0.1665.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:34:39.072 [error] <0.858.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:34:39.073 [error] <0.1600.0> CRASH REPORT Process <0.1600.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:39.072 [error] <0.854.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.856.0> exit with reason killed in context child_terminated
2016-04-10 22:34:39.072 [error] <0.854.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.856.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:34:39.072 [error] <0.857.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-10 22:34:39.072 [error] <0.860.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-10 22:34:39.072 [error] <0.860.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:34:39.073 [error] <0.852.0> CRASH REPORT Process <0.852.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:39.073 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:34:39.073 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:34:39.133 [info] <0.1726.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.1726.0>
2016-04-10 22:34:39.135 [info] <0.7.0> Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:34:39.372 [error] <0.1717.0> CRASH REPORT Process <0.1717.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:39.175 [info] <0.962.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.962.0>
2016-04-10 22:34:39.451 [info] <0.1068.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.1068.0>
2016-04-10 22:34:39.668 [info] <0.1167.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.1167.0>
2016-04-10 22:34:39.869 [info] <0.1268.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.1268.0>
2016-04-10 22:34:40.172 [warning] <0.6.0> lager_error_logger_h dropped 7 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:34:40.174 [info] <0.7.0> Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:34:39.372 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:34:39.437 [info] <0.1852.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.1852.0>
2016-04-10 22:34:39.661 [info] <0.1983.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.1983.0>
2016-04-10 22:34:39.870 [info] <0.2116.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.2116.0>
2016-04-10 22:34:40.360 [warning] <0.6.0> lager_error_logger_h dropped 8 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:34:40.360 [error] <0.2169.0> gen_server <0.2169.0> terminated with reason: killed
2016-04-10 22:34:40.359 [error] <0.1320.0> gen_server <0.1320.0> terminated with reason: killed
2016-04-10 22:34:40.360 [error] <0.2169.0> CRASH REPORT Process <0.2169.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:34:40.359 [error] <0.1320.0> CRASH REPORT Process <0.1320.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:34:40.360 [error] <0.2107.0> CRASH REPORT Process <0.2107.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:40.360 [error] <0.1259.0> CRASH REPORT Process <0.1259.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:40.360 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:34:40.421 [info] <0.2255.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.2255.0>
2016-04-10 22:34:40.424 [info] <0.7.0> Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:34:40.632 [error] <0.2311.0> gen_server <0.2311.0> terminated with reason: killed
2016-04-10 22:34:40.632 [error] <0.2311.0> CRASH REPORT Process <0.2311.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:34:40.360 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:34:40.427 [info] <0.1377.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.1377.0>
2016-04-10 22:34:40.708 [info] <0.1464.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.1464.0>
2016-04-10 22:34:41.145 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:34:41.145 [error] <0.1517.0> gen_server <0.1517.0> terminated with reason: killed
2016-04-10 22:34:40.705 [info] <0.2386.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.2386.0>
2016-04-10 22:34:41.010 [info] <0.7.0> Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:34:41.147 [error] <0.2377.0> CRASH REPORT Process <0.2377.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:41.145 [error] <0.1517.0> CRASH REPORT Process <0.1517.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:34:41.145 [error] <0.1455.0> CRASH REPORT Process <0.1455.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:41.145 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:34:41.217 [info] <0.1577.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.1577.0>
2016-04-10 22:34:41.221 [info] <0.7.0> Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:34:41.336 [error] <0.1568.0> CRASH REPORT Process <0.1568.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:41.336 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:34:41.147 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:34:41.199 [info] <0.2519.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.2519.0>
2016-04-10 22:34:41.393 [info] <0.2642.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.2642.0>
2016-04-10 22:34:41.707 [info] <0.2770.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.2770.0>
2016-04-10 22:34:41.780 [info] <0.2864.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.2864.0>
2016-04-10 22:34:41.397 [info] <0.1664.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.1664.0>
2016-04-10 22:34:43.005 [warning] <0.6.0> lager_error_logger_h dropped 7 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:34:43.011 [info] <0.2974.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.2974.0>
2016-04-10 22:34:43.013 [info] <0.7.0> Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:34:44.391 [error] <0.2965.0> CRASH REPORT Process <0.2965.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:44.391 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:34:46.470 [info] <0.3080.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.3080.0>
2016-04-10 22:34:46.473 [info] <0.7.0> Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:34:46.475 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:34:46.476 [info] <0.3128.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.3128.0>
2016-04-10 22:34:46.480 [info] <0.3176.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.3176.0>
2016-04-10 22:34:49.111 [info] <0.3248.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.3248.0>
2016-04-10 22:34:49.114 [info] <0.7.0> Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:34:49.141 [error] <0.3239.0> CRASH REPORT Process <0.3239.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:49.141 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:34:51.176 [info] <0.3331.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.3331.0>
2016-04-10 22:34:51.179 [info] <0.7.0> Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:34:51.183 [info] <0.3325.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Restore aborted. mnesia2_config_backup:open_read["NonExisting.FILE"] -> {enoent,error}

2016-04-10 22:34:51.184 [info] <0.3325.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Restore aborted. mnesia2_config_backup:open_read["/home/travis/build/lrascao/mnesia2/logs/ct_run.test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15.2016-04-10_22.34.16/Mnesia2.test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15/LATEST.LOG"] -> badarg

2016-04-10 22:34:51.185 [error] <0.3359.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 22:34:51.185 [error] <0.3362.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 22:34:51.185 [error] <0.3360.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 22:34:51.186 [error] <0.3358.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 22:34:51.186 [error] <0.3365.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 22:34:51.186 [error] <0.3367.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 22:34:51.186 [error] <0.3366.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 22:34:51.186 [error] <0.3373.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_13,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_13,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 22:34:53.263 [warning] <0.6.0> lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:34:53.263 [info] <0.3450.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): mnesia2_monitor starting: <0.3452.0>

2016-04-10 22:34:53.264 [info] <0.3450.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Mnesia2 debug level set to verbose
2016-04-10 22:34:53.265 [info] <0.3450.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): mnesia2_subscr starting: <0.3453.0>

2016-04-10 22:34:53.265 [info] <0.3450.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): mnesia2_locker starting: <0.3454.0>

2016-04-10 22:34:53.265 [info] <0.3450.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): mnesia2_recover starting: <0.3455.0>

2016-04-10 22:34:53.266 [info] <0.3450.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): mnesia2_tm starting: <0.3456.0>

2016-04-10 22:34:53.266 [info] <0.3450.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Schema initiated from: default

2016-04-10 22:34:53.267 [info] <0.3456.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.3456.0>
2016-04-10 22:34:53.268 [info] <0.3450.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): mnesia2_controller starting: <0.3459.0>

2016-04-10 22:34:53.268 [info] <0.3450.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): mnesia2_late_loader starting: <0.3460.0>

2016-04-10 22:34:53.269 [info] <0.3450.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Intend to load tables: []

2016-04-10 22:34:53.270 [info] <0.3450.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): mnesia2_tm_1 starting: <0.3462.0>

2016-04-10 22:34:53.270 [info] <0.3450.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): mnesia2_tm_2 starting: <0.3463.0>

2016-04-10 22:34:53.271 [info] <0.3450.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): mnesia2_tm_3 starting: <0.3464.0>

2016-04-10 22:34:55.294 [warning] <0.6.0> lager_error_logger_h dropped 13 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:34:55.294 [info] <0.3515.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): mnesia2_monitor starting: <0.3517.0>

2016-04-10 22:34:55.295 [info] <0.3515.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Version: "1.0.0"

2016-04-10 22:34:55.295 [info] <0.3515.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Env access_module: mnesia2

2016-04-10 22:34:55.296 [info] <0.3515.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Env auto_repair: true

2016-04-10 22:34:55.296 [info] <0.3515.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Env backup_module: mnesia2_backup

2016-04-10 22:34:55.296 [info] <0.3521.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.3521.0>
2016-04-10 22:34:55.297 [info] <0.3515.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Env debug: debug

2016-04-10 22:34:55.298 [info] <0.3515.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15.2016-04-10_22.34.16/Mnesia2.test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15"

2016-04-10 22:34:55.299 [info] <0.3515.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Env dump_disc_copies_at_startup: true

2016-04-10 22:34:57.322 [warning] <0.6.0> lager_error_logger_h dropped 7 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:34:57.322 [info] <0.3568.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): mnesia2_monitor starting: <0.3570.0>

2016-04-10 22:34:57.323 [info] <0.3568.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Version: "1.0.0"

2016-04-10 22:34:57.323 [info] <0.3568.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Env access_module: mnesia2

2016-04-10 22:34:57.323 [info] <0.3574.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.3574.0>
2016-04-10 22:34:57.324 [info] <0.3568.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Env auto_repair: true

2016-04-10 22:34:57.325 [info] <0.3568.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Env backup_module: mnesia2_backup

2016-04-10 22:34:57.325 [info] <0.3568.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Env debug: trace

2016-04-10 22:34:57.325 [info] <0.3568.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15.2016-04-10_22.34.16/Mnesia2.test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15"

2016-04-10 22:34:57.326 [info] <0.3568.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Env dump_disc_copies_at_startup: true

2016-04-10 22:34:57.326 [info] <0.3568.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Env dump_log_load_regulation: false

2016-04-10 22:34:59.350 [warning] <0.6.0> lager_error_logger_h dropped 15 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:34:59.350 [info] <0.3636.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): mnesia2_monitor starting: <0.3638.0>

2016-04-10 22:34:59.350 [info] <0.3636.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Version: "1.0.0"

2016-04-10 22:34:59.350 [info] <0.3636.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Env access_module: mnesia2

2016-04-10 22:34:59.350 [info] <0.3636.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Env auto_repair: true

2016-04-10 22:34:59.350 [info] <0.3636.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Env backup_module: mnesia2_backup

2016-04-10 22:34:59.350 [info] <0.3636.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Env debug: debug

2016-04-10 22:34:59.351 [info] <0.3636.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15.2016-04-10_22.34.16/Mnesia2.test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15"

2016-04-10 22:34:59.351 [info] <0.3636.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Env dump_disc_copies_at_startup: true

2016-04-10 22:34:59.352 [info] <0.3636.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Env dump_log_load_regulation: false

2016-04-10 22:34:59.352 [info] <0.3642.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.3642.0>
2016-04-10 22:34:59.352 [info] <0.3636.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Env dump_log_time_threshold: 180000

2016-04-10 22:34:59.353 [info] <0.3636.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Env dump_log_update_in_place: true

2016-04-10 22:34:59.354 [info] <0.3636.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Env dump_log_write_threshold: 1000

2016-04-10 22:35:01.377 [warning] <0.6.0> lager_error_logger_h dropped 11 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:35:01.378 [info] <0.3706.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.3706.0>
2016-04-10 22:35:01.381 [info] <0.7.0> Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:35:01.381 [error] <0.3697.0> CRASH REPORT Process <0.3697.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:35:01.381 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:35:03.462 [info] <0.3770.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.3770.0>
2016-04-10 22:35:03.464 [info] <0.7.0> Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:35:03.465 [error] <0.3765.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.3771.0> exit with reason killed in context child_terminated
2016-04-10 22:35:03.465 [error] <0.3765.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.3771.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:35:03.466 [error] <0.3761.0> CRASH REPORT Process <0.3761.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:35:03.466 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:35:04.615 [info] <0.3841.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.3841.0>
2016-04-10 22:35:04.617 [info] <0.7.0> Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:35:04.621 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:35:04.627 [info] <0.3902.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.3902.0>
2016-04-10 22:35:07.613 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:35:07.613 [warning] <0.3896.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:35:09.273 [warning] <0.3896.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:35:17.445 [warning] <0.3896.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:35:19.697 [error] <0.3893.0> CRASH REPORT Process <0.3893.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:35:19.697 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:35:21.827 [info] <0.4536.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.4536.0>
2016-04-10 22:35:21.829 [info] <0.7.0> Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:35:27.836 [error] <0.4527.0> CRASH REPORT Process <0.4527.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:35:27.836 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:35:29.944 [info] <0.4636.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.4636.0>
2016-04-10 22:35:29.946 [info] <0.7.0> Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:35:30.963 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:35:33.083 [info] <0.4752.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.4752.0>
2016-04-10 22:35:33.084 [info] <0.7.0> Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:35:33.090 [error] <0.4743.0> CRASH REPORT Process <0.4743.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:35:33.090 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:35:35.120 [info] <0.4819.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.4819.0>
2016-04-10 22:35:35.123 [info] <0.7.0> Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:35:35.146 [error] <0.4810.0> CRASH REPORT Process <0.4810.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:35:35.146 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:35:37.246 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:35:37.265 [info] <0.1791.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.1791.0>
2016-04-10 22:35:37.283 [info] <0.7.0> Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:35:37.262 [info] <0.4911.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.4911.0>
2016-04-10 22:35:37.567 [info] <0.7.0> Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:35:38.568 [error] <0.1844.0> gen_server <0.1844.0> terminated with reason: killed
2016-04-10 22:35:38.568 [error] <0.1844.0> CRASH REPORT Process <0.1844.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:35:38.569 [error] <0.1782.0> CRASH REPORT Process <0.1782.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:35:38.569 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:35:40.601 [info] <0.1860.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.1860.0>
2016-04-10 22:35:40.617 [info] <0.7.0> Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:35:41.619 [error] <0.4975.0> gen_server <0.4975.0> terminated with reason: killed
2016-04-10 22:35:41.619 [error] <0.4975.0> CRASH REPORT Process <0.4975.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:35:41.620 [error] <0.4902.0> CRASH REPORT Process <0.4902.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:35:41.620 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:35:42.669 [error] <0.1855.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.1873.0> exit with reason killed in context child_terminated
2016-04-10 22:35:42.670 [error] <0.1855.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.1873.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:35:42.670 [error] <0.1851.0> CRASH REPORT Process <0.1851.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:35:42.670 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:35:43.738 [info] <0.5018.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.5018.0>
2016-04-10 22:35:43.740 [info] <0.7.0> Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:35:43.770 [error] <0.5009.0> CRASH REPORT Process <0.5009.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:35:43.765 [info] <0.1942.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.1942.0>
2016-04-10 22:35:43.768 [info] <0.7.0> Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:35:43.770 [error] <0.1993.0> gen_server <0.1993.0> terminated with reason: killed
2016-04-10 22:35:43.770 [error] <0.1993.0> CRASH REPORT Process <0.1993.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:35:43.770 [error] <0.1932.0> CRASH REPORT Process <0.1932.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:35:43.770 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:35:43.812 [info] <0.5093.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.5093.0>
2016-04-10 22:35:43.771 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:35:47.670 [warning] <0.6.0> lager_error_logger_h dropped 25 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:35:47.670 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:35:47.761 [info] <0.5217.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.5217.0>
2016-04-10 22:35:47.765 [info] <0.7.0> Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:35:47.753 [info] <0.2016.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.2016.0>
2016-04-10 22:35:47.754 [info] <0.7.0> Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:35:57.112 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:35:57.113 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:35:58.258 [info] <0.2138.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.2138.0>
2016-04-10 22:35:58.262 [info] <0.7.0> Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:35:58.314 [error] <0.2190.0> gen_server <0.2190.0> terminated with reason: killed
2016-04-10 22:35:58.314 [error] <0.2190.0> CRASH REPORT Process <0.2190.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:35:58.314 [error] <0.2129.0> CRASH REPORT Process <0.2129.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:35:58.252 [info] <0.5348.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.5348.0>
2016-04-10 22:35:58.255 [info] <0.7.0> Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:35:58.336 [error] <0.5339.0> CRASH REPORT Process <0.5339.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:35:58.336 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:35:58.366 [info] <0.5436.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.5436.0>
2016-04-10 22:35:58.314 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:35:58.556 [info] <0.2226.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.2226.0>
2016-04-10 22:36:00.049 [warning] <0.6.0> lager_error_logger_h dropped 14 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:36:00.049 [error] <0.2217.0> CRASH REPORT Process <0.2217.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:00.049 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:01.109 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:36:01.115 [info] <0.5559.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.5559.0>
2016-04-10 22:36:01.117 [info] <0.7.0> Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:36:01.138 [error] <0.5623.0> gen_server <0.5623.0> terminated with reason: killed
2016-04-10 22:36:01.122 [info] <0.2329.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.2329.0>
2016-04-10 22:36:01.127 [info] <0.7.0> Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:36:01.139 [error] <0.2340.0> gen_server <0.2340.0> terminated with reason: killed
2016-04-10 22:36:01.138 [error] <0.5623.0> CRASH REPORT Process <0.5623.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:01.138 [error] <0.5550.0> CRASH REPORT Process <0.5550.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:01.139 [error] <0.2340.0> CRASH REPORT Process <0.2340.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:01.139 [error] <0.2320.0> CRASH REPORT Process <0.2320.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:01.138 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:01.139 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:03.503 [info] <0.2404.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.2404.0>
2016-04-10 22:36:03.508 [info] <0.7.0> Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:36:03.511 [error] <0.2415.0> gen_server <0.2415.0> terminated with reason: killed
2016-04-10 22:36:03.493 [info] <0.5670.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.5670.0>
2016-04-10 22:36:03.495 [info] <0.7.0> Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:36:03.512 [error] <0.5732.0> gen_server <0.5732.0> terminated with reason: killed
2016-04-10 22:36:03.511 [error] <0.2415.0> CRASH REPORT Process <0.2415.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:03.512 [error] <0.5732.0> CRASH REPORT Process <0.5732.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:03.512 [error] <0.2395.0> CRASH REPORT Process <0.2395.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:03.512 [error] <0.5661.0> CRASH REPORT Process <0.5661.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:03.512 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:03.512 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:05.544 [info] <0.5750.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.5750.0>
2016-04-10 22:36:05.551 [info] <0.7.0> Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:36:05.571 [error] <0.5741.0> CRASH REPORT Process <0.5741.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:05.536 [info] <0.2463.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.2463.0>
2016-04-10 22:36:05.537 [info] <0.7.0> Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:36:05.571 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:07.014 [error] <0.2454.0> CRASH REPORT Process <0.2454.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:07.015 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:08.126 [info] <0.2552.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.2552.0>
2016-04-10 22:36:08.130 [info] <0.7.0> Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:36:08.460 [error] <0.2603.0> gen_server <0.2603.0> terminated with reason: killed
2016-04-10 22:36:08.113 [info] <0.5875.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.5875.0>
2016-04-10 22:36:08.115 [info] <0.7.0> Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:36:08.461 [error] <0.5866.0> CRASH REPORT Process <0.5866.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:08.460 [error] <0.2603.0> CRASH REPORT Process <0.2603.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:08.460 [error] <0.2564.0> gen_server <0.2564.0> terminated with reason: killed
2016-04-10 22:36:08.461 [error] <0.2564.0> CRASH REPORT Process <0.2564.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:08.461 [error] <0.2543.0> CRASH REPORT Process <0.2543.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:08.461 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:08.461 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:08.356 [info] <0.7.0> Application lager started on node 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:36:08.356 [info] <0.7.0> Application poolgirl started on node 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:36:08.381 [info] <0.102.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.102.0>
2016-04-10 22:36:08.398 [info] <0.7.0> Application mnesia2 started on node 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:36:10.582 [info] <0.2633.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.2633.0>
2016-04-10 22:36:10.590 [info] <0.7.0> Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:36:10.603 [error] <0.2644.0> gen_server <0.2644.0> terminated with reason: killed
2016-04-10 22:36:10.570 [info] <0.5970.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.5970.0>
2016-04-10 22:36:10.573 [info] <0.7.0> Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:36:10.610 [error] <0.6034.0> gen_server <0.6034.0> terminated with reason: killed
2016-04-10 22:36:10.603 [error] <0.2644.0> CRASH REPORT Process <0.2644.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:10.610 [error] <0.6034.0> CRASH REPORT Process <0.6034.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:10.603 [error] <0.2624.0> CRASH REPORT Process <0.2624.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:10.613 [error] <0.5961.0> CRASH REPORT Process <0.5961.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:10.613 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:10.603 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:12.731 [info] <0.2703.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.2703.0>
2016-04-10 22:36:12.734 [info] <0.7.0> Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:36:12.740 [error] <0.2698.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.2705.0> exit with reason killed in context child_terminated
2016-04-10 22:36:12.727 [info] <0.6064.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.6064.0>
2016-04-10 22:36:12.730 [info] <0.7.0> Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:36:12.741 [error] <0.6057.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.6059.0> exit with reason killed in context child_terminated
2016-04-10 22:36:12.740 [error] <0.2698.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.2705.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:36:12.741 [error] <0.6057.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.6059.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:36:12.740 [error] <0.2716.0> gen_server <0.2716.0> terminated with reason: killed
2016-04-10 22:36:12.741 [error] <0.6061.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-10 22:36:12.740 [error] <0.2716.0> CRASH REPORT Process <0.2716.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:12.741 [error] <0.6061.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:12.740 [error] <0.2694.0> CRASH REPORT Process <0.2694.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:12.741 [error] <0.6066.0> gen_server mnesia2_snmp_sup terminated with reason: killed
2016-04-10 22:36:12.742 [error] <0.6066.0> CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:12.743 [info] <0.7.0> Application mnesia2 exited with reason: shutdown
2016-04-10 22:36:12.740 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:14.901 [info] <0.2778.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.2778.0>
2016-04-10 22:36:14.924 [info] <0.7.0> Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:36:14.927 [error] <0.2832.0> gen_server <0.2832.0> terminated with reason: killed
2016-04-10 22:36:14.927 [error] <0.2832.0> CRASH REPORT Process <0.2832.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:14.928 [error] <0.2769.0> CRASH REPORT Process <0.2769.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:14.884 [info] <0.6150.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.6150.0>
2016-04-10 22:36:14.887 [info] <0.7.0> Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:36:14.928 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:15.954 [error] <0.6141.0> CRASH REPORT Process <0.6141.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:15.954 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:17.989 [info] <0.2848.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.2848.0>
2016-04-10 22:36:17.991 [info] <0.7.0> Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:36:23.025 [info] <0.6228.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.6228.0>
2016-04-10 22:36:23.034 [info] <0.7.0> Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:36:23.040 [error] <0.6275.0> gen_server <0.6275.0> terminated with reason: killed
2016-04-10 22:36:23.041 [error] <0.2917.0> gen_server <0.2917.0> terminated with reason: killed
2016-04-10 22:36:23.040 [error] <0.6275.0> CRASH REPORT Process <0.6275.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:23.041 [error] <0.6219.0> CRASH REPORT Process <0.6219.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:23.041 [error] <0.2917.0> CRASH REPORT Process <0.2917.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:23.041 [error] <0.2839.0> CRASH REPORT Process <0.2839.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:23.041 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:23.041 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:24.512 [info] <0.2947.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.2947.0>
2016-04-10 22:36:24.538 [info] <0.7.0> Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:36:24.885 [error] <0.2938.0> CRASH REPORT Process <0.2938.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:24.194 [warning] <0.6.0> lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:36:24.557 [info] <0.192.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.192.0>
2016-04-10 22:36:24.562 [info] <0.7.0> Application mnesia2 started on node 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:36:24.509 [info] <0.6338.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.6338.0>
2016-04-10 22:36:24.815 [info] <0.7.0> Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:36:25.205 [error] <0.6403.0> gen_server <0.6403.0> terminated with reason: killed
2016-04-10 22:36:25.205 [error] <0.6403.0> CRASH REPORT Process <0.6403.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:25.206 [error] <0.6329.0> CRASH REPORT Process <0.6329.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:25.226 [error] <0.276.0> gen_server <0.276.0> terminated with reason: killed
2016-04-10 22:36:25.227 [error] <0.276.0> CRASH REPORT Process <0.276.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:25.227 [error] <0.183.0> CRASH REPORT Process <0.183.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:25.206 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:25.315 [info] <0.6458.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.6458.0>
2016-04-10 22:36:25.337 [info] <0.7.0> Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:36:24.886 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:24.922 [info] <0.3039.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.3039.0>
2016-04-10 22:36:25.187 [info] <0.7.0> Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:36:25.251 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:36:25.282 [info] <0.3134.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.3134.0>
2016-04-10 22:36:25.227 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:25.321 [info] <0.296.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.296.0>
2016-04-10 22:36:25.327 [info] <0.7.0> Application mnesia2 started on node 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:36:25.873 [error] <0.368.0> gen_server <0.368.0> terminated with reason: killed
2016-04-10 22:36:25.873 [error] <0.368.0> CRASH REPORT Process <0.368.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:25.873 [error] <0.358.0> gen_server <0.358.0> terminated with reason: killed
2016-04-10 22:36:25.874 [error] <0.358.0> CRASH REPORT Process <0.358.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:25.900 [info] <0.391.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.391.0>
2016-04-10 22:36:27.950 [error] <0.6553.0> gen_server <0.6553.0> terminated with reason: killed
2016-04-10 22:36:27.950 [error] <0.6523.0> gen_server <0.6523.0> terminated with reason: killed
2016-04-10 22:36:27.950 [error] <0.6553.0> CRASH REPORT Process <0.6553.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:27.951 [error] <0.6523.0> CRASH REPORT Process <0.6523.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:27.951 [error] <0.6448.0> CRASH REPORT Process <0.6448.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:27.973 [warning] <0.6.0> lager_error_logger_h dropped 6 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:36:27.973 [error] <0.3227.0> gen_server <0.3227.0> terminated with reason: killed
2016-04-10 22:36:27.973 [error] <0.3227.0> CRASH REPORT Process <0.3227.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:27.973 [error] <0.3125.0> CRASH REPORT Process <0.3125.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:27.997 [warning] <0.6.0> lager_error_logger_h dropped 16 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:36:27.997 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:36:28.015 [info] <0.497.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.497.0>
2016-04-10 22:36:28.017 [info] <0.7.0> Application mnesia2 started on node 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:36:28.887 [error] <0.565.0> gen_server <0.565.0> terminated with reason: killed
2016-04-10 22:36:28.887 [error] <0.565.0> CRASH REPORT Process <0.565.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:28.888 [error] <0.488.0> CRASH REPORT Process <0.488.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:27.951 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:28.057 [info] <0.6572.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.6572.0>
2016-04-10 22:36:28.364 [info] <0.7.0> Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:36:27.973 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:28.062 [info] <0.3248.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.3248.0>
2016-04-10 22:36:28.085 [info] <0.7.0> Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:36:28.888 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:28.912 [info] <0.596.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.596.0>
2016-04-10 22:36:28.914 [info] <0.7.0> Application mnesia2 started on node 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:36:28.998 [error] <0.6668.0> gen_server <0.6668.0> terminated with reason: killed
2016-04-10 22:36:28.998 [error] <0.6668.0> CRASH REPORT Process <0.6668.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:28.998 [error] <0.6661.0> gen_server <0.6661.0> terminated with reason: killed
2016-04-10 22:36:28.998 [error] <0.6661.0> CRASH REPORT Process <0.6661.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:29.003 [error] <0.6563.0> CRASH REPORT Process <0.6563.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:29.022 [error] <0.3337.0> gen_server <0.3337.0> terminated with reason: killed
2016-04-10 22:36:29.023 [error] <0.3337.0> CRASH REPORT Process <0.3337.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:29.023 [error] <0.3239.0> CRASH REPORT Process <0.3239.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:29.023 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:29.131 [info] <0.3356.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.3356.0>
2016-04-10 22:36:29.139 [info] <0.7.0> Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:36:29.950 [error] <0.3425.0> gen_server <0.3425.0> terminated with reason: killed
2016-04-10 22:36:29.951 [error] <0.3425.0> CRASH REPORT Process <0.3425.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:29.952 [error] <0.3406.0> gen_server <0.3406.0> terminated with reason: killed
2016-04-10 22:36:29.952 [error] <0.3406.0> CRASH REPORT Process <0.3406.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:29.003 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:29.111 [info] <0.6685.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.6685.0>
2016-04-10 22:36:29.431 [info] <0.7.0> Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:36:29.995 [info] <0.3451.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.3451.0>
2016-04-10 22:36:30.012 [info] <0.7.0> Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:36:29.051 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:36:29.075 [info] <0.697.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.697.0>
2016-04-10 22:36:29.077 [info] <0.7.0> Application mnesia2 started on node 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:36:30.065 [error] <0.3499.0> gen_server <0.3499.0> terminated with reason: killed
2016-04-10 22:36:30.065 [error] <0.3499.0> CRASH REPORT Process <0.3499.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:30.065 [error] <0.3509.0> gen_server <0.3509.0> terminated with reason: killed
2016-04-10 22:36:30.065 [error] <0.3509.0> CRASH REPORT Process <0.3509.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:30.066 [error] <0.3464.0> gen_server <0.3464.0> terminated with reason: killed
2016-04-10 22:36:30.066 [error] <0.3464.0> CRASH REPORT Process <0.3464.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:30.066 [error] <0.3442.0> CRASH REPORT Process <0.3442.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:30.067 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:31.100 [info] <0.3529.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.3529.0>
2016-04-10 22:36:31.109 [info] <0.7.0> Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:36:31.151 [error] <0.3520.0> CRASH REPORT Process <0.3520.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:31.151 [error] <0.6798.0> gen_server <0.6798.0> terminated with reason: killed
2016-04-10 22:36:31.153 [error] <0.821.0> gen_server <0.821.0> terminated with reason: killed
2016-04-10 22:36:31.151 [error] <0.6798.0> CRASH REPORT Process <0.6798.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:31.152 [error] <0.6676.0> CRASH REPORT Process <0.6676.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:31.153 [error] <0.821.0> CRASH REPORT Process <0.821.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:31.153 [error] <0.812.0> gen_server <0.812.0> terminated with reason: killed
2016-04-10 22:36:31.153 [error] <0.812.0> CRASH REPORT Process <0.812.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:31.154 [error] <0.688.0> CRASH REPORT Process <0.688.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:31.151 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:31.236 [info] <0.3608.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.3608.0>
2016-04-10 22:36:31.300 [info] <0.3702.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.3702.0>
2016-04-10 22:36:31.365 [info] <0.3792.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.3792.0>
2016-04-10 22:36:31.450 [info] <0.3892.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.3892.0>
2016-04-10 22:36:32.016 [warning] <0.6.0> lager_error_logger_h dropped 10 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:36:32.017 [error] <0.3883.0> CRASH REPORT Process <0.3883.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:32.017 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:31.152 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:31.213 [info] <0.6831.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.6831.0>
2016-04-10 22:36:31.215 [info] <0.7.0> Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:36:31.433 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:36:31.967 [info] <0.6944.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.6944.0>
2016-04-10 22:36:32.015 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:36:32.052 [info] <0.7027.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.7027.0>
2016-04-10 22:36:32.056 [info] <0.7.0> Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:36:31.154 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:32.559 [info] <0.3974.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.3974.0>
2016-04-10 22:36:32.595 [info] <0.7.0> Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:36:32.641 [error] <0.3969.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_controller:start() at <0.3978.0> exit with reason killed in context child_terminated
2016-04-10 22:36:32.641 [error] <0.3969.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_controller:start() at <0.3978.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:36:32.644 [error] <0.7018.0> CRASH REPORT Process <0.7018.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:32.642 [error] <0.3969.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.3976.0> exit with reason killed in context shutdown_error
2016-04-10 22:36:32.643 [error] <0.3967.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.3969.0> exit with reason shutdown in context child_terminated
2016-04-10 22:36:32.734 [info] <0.849.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.849.0>
2016-04-10 22:36:32.740 [info] <0.7.0> Application mnesia2 started on node 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:36:33.220 [error] <0.913.0> gen_server <0.913.0> terminated with reason: killed
2016-04-10 22:36:32.644 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:32.722 [info] <0.7128.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.7128.0>
2016-04-10 22:36:33.028 [info] <0.7.0> Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:36:33.223 [error] <0.7192.0> gen_server <0.7192.0> terminated with reason: killed
2016-04-10 22:36:32.734 [info] <0.4066.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.4066.0>
2016-04-10 22:36:33.219 [warning] <0.6.0> lager_error_logger_h dropped 32 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:36:33.219 [error] <0.4061.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.4081.0> exit with reason killed in context child_terminated
2016-04-10 22:36:33.223 [error] <0.7192.0> CRASH REPORT Process <0.7192.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:33.220 [error] <0.913.0> CRASH REPORT Process <0.913.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:33.223 [error] <0.7187.0> gen_server <0.7187.0> terminated with reason: killed
2016-04-10 22:36:33.219 [error] <0.4061.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.4081.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:36:33.220 [error] <0.906.0> gen_server <0.906.0> terminated with reason: killed
2016-04-10 22:36:33.223 [error] <0.7187.0> CRASH REPORT Process <0.7187.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:33.220 [error] <0.4061.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_controller:start() at <0.4083.0> exit with reason killed in context shutdown_error
2016-04-10 22:36:33.223 [error] <0.7119.0> CRASH REPORT Process <0.7119.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:33.220 [error] <0.906.0> CRASH REPORT Process <0.906.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:33.221 [error] <0.840.0> CRASH REPORT Process <0.840.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:33.221 [error] <0.4059.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.4061.0> exit with reason shutdown in context child_terminated
2016-04-10 22:36:33.221 [error] <0.4059.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.4061.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:36:33.221 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:33.244 [info] <0.954.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.954.0>
2016-04-10 22:36:33.245 [info] <0.7.0> Application mnesia2 started on node 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:36:33.322 [error] <0.1003.0> gen_server <0.1003.0> terminated with reason: killed
2016-04-10 22:36:33.322 [error] <0.1003.0> CRASH REPORT Process <0.1003.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:33.323 [error] <0.1012.0> gen_server <0.1012.0> terminated with reason: killed
2016-04-10 22:36:33.323 [error] <0.1012.0> CRASH REPORT Process <0.1012.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:33.323 [error] <0.998.0> gen_server <0.998.0> terminated with reason: killed
2016-04-10 22:36:33.323 [error] <0.998.0> CRASH REPORT Process <0.998.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:33.323 [error] <0.945.0> CRASH REPORT Process <0.945.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:33.221 [info] <0.7.0> Application mnesia2 exited with reason: shutdown
2016-04-10 22:36:33.244 [info] <0.4158.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.4158.0>
2016-04-10 22:36:33.246 [info] <0.7.0> Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:36:33.346 [info] <0.4236.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.4236.0>
2016-04-10 22:36:33.223 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:33.284 [info] <0.7240.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.7240.0>
2016-04-10 22:36:33.376 [info] <0.7332.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.7332.0>
2016-04-10 22:36:33.323 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:33.348 [info] <0.1031.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.1031.0>
2016-04-10 22:36:43.384 [warning] <0.6.0> lager_error_logger_h dropped 35 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:36:43.384 [error] <0.7328.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-10 22:36:43.384 [error] <0.7331.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-10 22:36:43.384 [error] <0.7331.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:43.384 [error] <0.7351.0> gen_server mnesia2_snmp_sup terminated with reason: killed
2016-04-10 22:36:43.384 [error] <0.7351.0> CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:43.384 [error] <0.7325.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at undefined exit with reason killed in context start_error
2016-04-10 22:36:43.384 [error] <0.7329.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-10 22:36:43.384 [error] <0.7329.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:43.384 [error] <0.7323.0> CRASH REPORT Process <0.7323.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}} in application_master:init/4 line 134
2016-04-10 22:36:43.385 [info] <0.7.0> Application mnesia2 exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}}
2016-04-10 22:36:43.386 [error] <0.7328.0> CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:43.470 [error] <0.4280.0> gen_server <0.4280.0> terminated with reason: killed
2016-04-10 22:36:43.472 [error] <0.1026.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.1032.0> exit with reason killed in context child_terminated
2016-04-10 22:36:43.470 [error] <0.4280.0> CRASH REPORT Process <0.4280.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:43.470 [error] <0.4227.0> CRASH REPORT Process <0.4227.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:43.472 [error] <0.1026.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.1032.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:36:43.473 [error] <0.1024.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.1026.0> exit with reason shutdown in context child_terminated
2016-04-10 22:36:43.474 [error] <0.1024.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.1026.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:36:43.470 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:36:43.476 [info] <0.7.0> Application mnesia2 exited with reason: shutdown
2016-04-10 22:36:45.904 [info] <0.7441.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.7441.0>
2016-04-10 22:36:45.907 [info] <0.7.0> Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:36:50.306 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:36:50.480 [info] <0.7577.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.7577.0>
2016-04-10 22:36:50.494 [info] <0.7.0> Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:36:50.467 [info] <0.4327.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.4327.0>
2016-04-10 22:36:50.773 [info] <0.7.0> Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:36:50.482 [info] <0.1127.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.1127.0>
2016-04-10 22:36:50.499 [info] <0.7.0> Application mnesia2 started on node 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:36:56.893 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:36:57.037 [info] <0.1240.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.1240.0>
2016-04-10 22:36:57.342 [info] <0.7.0> Application mnesia2 started on node 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:36:56.897 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:36:57.022 [info] <0.7706.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.7706.0>
2016-04-10 22:36:57.027 [info] <0.7.0> Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:36:56.900 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:36:57.039 [info] <0.4445.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.4445.0>
2016-04-10 22:36:57.045 [info] <0.7.0> Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:37:03.420 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:03.580 [info] <0.1356.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.1356.0>
2016-04-10 22:37:03.582 [info] <0.7.0> Application mnesia2 started on node 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:37:03.424 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:03.588 [info] <0.7835.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.7835.0>
2016-04-10 22:37:03.619 [info] <0.7.0> Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:37:03.430 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:03.588 [info] <0.4560.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.4560.0>
2016-04-10 22:37:03.628 [info] <0.7.0> Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:37:23.179 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:23.328 [info] <0.8972.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.8972.0>
2016-04-10 22:37:23.330 [info] <0.7.0> Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:37:23.178 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:23.336 [info] <0.2481.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.2481.0>
2016-04-10 22:37:23.354 [info] <0.7.0> Application mnesia2 started on node 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:37:23.185 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:23.342 [info] <0.5684.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.5684.0>
2016-04-10 22:37:23.381 [info] <0.7.0> Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:37:30.071 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:30.238 [info] <0.5807.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.5807.0>
2016-04-10 22:37:30.248 [info] <0.7.0> Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:37:30.083 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:30.220 [info] <0.2606.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.2606.0>
2016-04-10 22:37:30.525 [info] <0.7.0> Application mnesia2 started on node 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:37:30.073 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:30.215 [info] <0.9111.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.9111.0>
2016-04-10 22:37:30.217 [info] <0.7.0> Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:37:36.872 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:37.032 [info] <0.10591.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.10591.0>
2016-04-10 22:37:37.035 [info] <0.7.0> Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:37:36.893 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:37.040 [info] <0.7277.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.7277.0>
2016-04-10 22:37:37.345 [info] <0.7.0> Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:37:36.908 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:37.043 [info] <0.4078.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.4078.0>
2016-04-10 22:37:37.049 [info] <0.7.0> Application mnesia2 started on node 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:37:43.546 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:43.702 [info] <0.11002.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.11002.0>
2016-04-10 22:37:43.704 [info] <0.7.0> Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:37:43.569 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:43.708 [info] <0.6119.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.6119.0>
2016-04-10 22:37:44.044 [info] <0.7.0> Application mnesia2 started on node 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:37:43.579 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:43.741 [info] <0.8378.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.8378.0>
2016-04-10 22:37:43.757 [info] <0.7.0> Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:37:50.163 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:50.297 [info] <0.8492.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.8492.0>
2016-04-10 22:37:50.603 [info] <0.7.0> Application mnesia2 started on node 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:37:50.164 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:50.294 [info] <0.11132.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.11132.0>
2016-04-10 22:37:50.599 [info] <0.7.0> Application mnesia2 started on node 'test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:37:50.168 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:50.301 [info] <0.6914.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15', <0.6914.0>
2016-04-10 22:37:50.305 [info] <0.7.0> Application mnesia2 started on node 'd923288o923280n923280@testing-worker-linux-docker-03d9c4fa-3371-linux-15'
2016-04-10 22:37:56.803 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:56.795 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:37:56.794 [info] <0.7.0> Application mnesia2 exited with reason: stopped
