2016-04-10 16:45:21.422 [info] <0.7.0> Application lager started on node 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:45:21.422 [info] <0.7.0> Application poolgirl started on node 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:45:21.456 [info] <0.495.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.495.0>
2016-04-10 16:45:21.485 [info] <0.563.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.563.0>
2016-04-10 16:45:22.269 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:45:22.278 [info] <0.673.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.673.0>
2016-04-10 16:45:22.281 [info] <0.7.0> Application mnesia2 started on node 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:45:22.762 [error] <0.664.0> CRASH REPORT Process <0.664.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:45:22.762 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:45:22.819 [info] <0.799.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.799.0>
2016-04-10 16:45:23.062 [warning] <0.6.0> lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:45:23.063 [error] <0.793.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): ** ERROR ** (ignoring core) ** FATAL ** A fallback is installed and Mnesia2 must be restarted. Forcing shutdown after mnesia2_down from 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13'...

2016-04-10 16:45:23.063 [error] <0.794.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_locker:start() at <0.797.0> exit with reason killed in context child_terminated
2016-04-10 16:45:23.063 [error] <0.794.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_locker:start() at <0.797.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 16:45:23.066 [error] <0.792.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.794.0> exit with reason shutdown in context child_terminated
2016-04-10 16:45:23.066 [error] <0.792.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.794.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 16:45:22.484 [info] <0.7.0> Application lager started on node 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:45:22.484 [info] <0.7.0> Application poolgirl started on node 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:45:22.556 [info] <0.100.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.100.0>
2016-04-10 16:45:22.838 [info] <0.216.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.216.0>
2016-04-10 16:45:23.069 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:45:23.112 [info] <0.369.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.369.0>
2016-04-10 16:45:23.128 [info] <0.7.0> Application mnesia2 started on node 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:45:23.670 [error] <0.363.0> Mnesia2('d702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13'): ** ERROR ** (ignoring core) ** FATAL ** A fallback is installed and Mnesia2 must be restarted. Forcing shutdown after mnesia2_down from 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'...

2016-04-10 16:45:23.068 [info] <0.7.0> Application mnesia2 exited with reason: shutdown
2016-04-10 16:45:23.094 [info] <0.927.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.927.0>
2016-04-10 16:45:23.097 [info] <0.7.0> Application mnesia2 started on node 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:45:23.698 [info] <0.1027.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.1027.0>
2016-04-10 16:45:24.467 [warning] <0.6.0> lager_error_logger_h dropped 29 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:45:24.467 [error] <0.1022.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.1042.0> exit with reason killed in context child_terminated
2016-04-10 16:45:23.674 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:45:23.728 [info] <0.459.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.459.0>
2016-04-10 16:45:24.468 [warning] <0.6.0> lager_error_logger_h dropped 32 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:45:24.468 [error] <0.517.0> gen_server <0.517.0> terminated with reason: killed
2016-04-10 16:45:24.468 [error] <0.517.0> CRASH REPORT Process <0.517.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:45:24.467 [error] <0.1022.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.1042.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 16:45:24.469 [error] <0.450.0> CRASH REPORT Process <0.450.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:45:24.469 [error] <0.1088.0> gen_server <0.1088.0> terminated with reason: killed
2016-04-10 16:45:24.469 [error] <0.1088.0> CRASH REPORT Process <0.1088.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:45:24.470 [error] <0.1018.0> CRASH REPORT Process <0.1018.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:45:24.469 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:45:24.554 [info] <0.548.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.548.0>
2016-04-10 16:45:24.558 [info] <0.7.0> Application mnesia2 started on node 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:45:24.470 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:45:24.526 [info] <0.1150.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.1150.0>
2016-04-10 16:45:24.528 [info] <0.7.0> Application mnesia2 started on node 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:45:24.688 [info] <0.1262.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.1262.0>
2016-04-10 16:45:25.160 [error] <0.1322.0> gen_server <0.1322.0> terminated with reason: killed
2016-04-10 16:45:25.158 [error] <0.661.0> gen_server <0.661.0> terminated with reason: killed
2016-04-10 16:45:25.160 [error] <0.1322.0> CRASH REPORT Process <0.1322.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:45:25.158 [error] <0.661.0> CRASH REPORT Process <0.661.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:45:25.160 [error] <0.1253.0> CRASH REPORT Process <0.1253.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:45:25.159 [error] <0.539.0> CRASH REPORT Process <0.539.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:45:25.159 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:45:25.239 [info] <0.762.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.762.0>
2016-04-10 16:45:25.251 [info] <0.7.0> Application mnesia2 started on node 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:45:25.402 [error] <0.816.0> gen_server <0.816.0> terminated with reason: killed
2016-04-10 16:45:25.160 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:45:25.230 [info] <0.1494.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.1494.0>
2016-04-10 16:45:25.232 [info] <0.7.0> Application mnesia2 started on node 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:45:25.407 [error] <0.1550.0> gen_server <0.1550.0> terminated with reason: killed
2016-04-10 16:45:25.403 [error] <0.816.0> CRASH REPORT Process <0.816.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:45:25.407 [error] <0.1550.0> CRASH REPORT Process <0.1550.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:45:25.404 [error] <0.753.0> CRASH REPORT Process <0.753.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:45:25.486 [info] <0.1608.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.1608.0>
2016-04-10 16:45:25.726 [info] <0.1724.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.1724.0>
2016-04-10 16:45:26.000 [error] <0.1715.0> CRASH REPORT Process <0.1715.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:45:25.404 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:45:25.493 [info] <0.861.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.861.0>
2016-04-10 16:45:25.735 [info] <0.962.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.962.0>
2016-04-10 16:45:26.056 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:45:26.076 [info] <0.1068.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.1068.0>
2016-04-10 16:45:26.088 [info] <0.7.0> Application mnesia2 started on node 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:45:26.000 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:45:26.073 [info] <0.1850.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.1850.0>
2016-04-10 16:45:26.380 [info] <0.7.0> Application mnesia2 started on node 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:45:26.552 [error] <0.1907.0> gen_server <0.1907.0> terminated with reason: killed
2016-04-10 16:45:26.555 [error] <0.1123.0> gen_server <0.1123.0> terminated with reason: killed
2016-04-10 16:45:26.555 [error] <0.1123.0> CRASH REPORT Process <0.1123.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:45:26.552 [error] <0.1907.0> CRASH REPORT Process <0.1907.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:45:26.556 [error] <0.1059.0> CRASH REPORT Process <0.1059.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:45:26.553 [error] <0.1841.0> CRASH REPORT Process <0.1841.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:45:26.553 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:45:26.708 [info] <0.1982.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.1982.0>
2016-04-10 16:45:27.005 [warning] <0.6.0> lager_error_logger_h dropped 18 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:45:27.012 [info] <0.2115.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.2115.0>
2016-04-10 16:45:27.016 [info] <0.7.0> Application mnesia2 started on node 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:45:27.231 [error] <0.2106.0> CRASH REPORT Process <0.2106.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:45:26.556 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:45:26.722 [info] <0.1168.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.1168.0>
2016-04-10 16:45:27.004 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:45:27.021 [info] <0.1270.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.1270.0>
2016-04-10 16:45:27.027 [info] <0.7.0> Application mnesia2 started on node 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:45:27.233 [error] <0.1261.0> CRASH REPORT Process <0.1261.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:45:27.231 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:45:27.302 [info] <0.2255.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.2255.0>
2016-04-10 16:45:27.550 [info] <0.2386.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.2386.0>
2016-04-10 16:45:27.233 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:45:27.323 [info] <0.1376.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.1376.0>
2016-04-10 16:45:28.000 [warning] <0.6.0> lager_error_logger_h dropped 9 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:45:28.000 [error] <0.2427.0> gen_server <0.2427.0> terminated with reason: killed
2016-04-10 16:45:28.000 [error] <0.2427.0> CRASH REPORT Process <0.2427.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:45:28.001 [error] <0.2377.0> CRASH REPORT Process <0.2377.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:45:27.566 [info] <0.1463.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.1463.0>
2016-04-10 16:45:28.055 [warning] <0.6.0> lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:45:28.077 [info] <0.1576.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.1576.0>
2016-04-10 16:45:28.088 [info] <0.7.0> Application mnesia2 started on node 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:45:28.246 [error] <0.1630.0> gen_server <0.1630.0> terminated with reason: killed
2016-04-10 16:45:28.001 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:45:28.071 [info] <0.2519.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.2519.0>
2016-04-10 16:45:28.074 [info] <0.7.0> Application mnesia2 started on node 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:45:28.248 [error] <0.2514.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.2531.0> exit with reason killed in context child_terminated
2016-04-10 16:45:28.247 [error] <0.1630.0> CRASH REPORT Process <0.1630.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:45:28.248 [error] <0.2514.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.2531.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 16:45:28.247 [error] <0.1567.0> CRASH REPORT Process <0.1567.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:45:28.247 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:45:28.326 [info] <0.1663.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.1663.0>
2016-04-10 16:45:28.307 [info] <0.2642.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.2642.0>
2016-04-10 16:45:28.629 [info] <0.2770.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.2770.0>
2016-04-10 16:45:28.730 [info] <0.2864.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.2864.0>
2016-04-10 16:45:29.964 [warning] <0.6.0> lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:45:29.972 [info] <0.2974.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.2974.0>
2016-04-10 16:45:29.974 [info] <0.7.0> Application mnesia2 started on node 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:45:31.165 [error] <0.2965.0> CRASH REPORT Process <0.2965.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:45:31.165 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:45:33.247 [info] <0.3080.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.3080.0>
2016-04-10 16:45:33.249 [info] <0.7.0> Application mnesia2 started on node 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:45:33.251 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:45:33.252 [info] <0.3128.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.3128.0>
2016-04-10 16:45:33.256 [info] <0.3176.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.3176.0>
2016-04-10 16:45:35.826 [info] <0.3248.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.3248.0>
2016-04-10 16:45:35.829 [info] <0.7.0> Application mnesia2 started on node 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:45:35.878 [error] <0.3239.0> CRASH REPORT Process <0.3239.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:45:35.878 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:45:38.227 [info] <0.3331.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.3331.0>
2016-04-10 16:45:38.230 [info] <0.7.0> Application mnesia2 started on node 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:45:38.278 [info] <0.3325.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Restore aborted. mnesia2_config_backup:open_read["NonExisting.FILE"] -> {enoent,error}

2016-04-10 16:45:38.280 [error] <0.3361.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.281 [error] <0.3363.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.281 [error] <0.3365.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.281 [error] <0.3364.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.281 [error] <0.3367.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_11,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_11,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.281 [error] <0.3368.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_12,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_12,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.281 [error] <0.3366.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_10,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_10,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.281 [error] <0.3373.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_17,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_17,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.281 [error] <0.3372.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_16,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_16,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.281 [error] <0.3375.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_19,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_19,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.282 [error] <0.3377.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_21,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_21,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.282 [error] <0.3376.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_20,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_20,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.282 [error] <0.3374.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_18,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_18,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.282 [error] <0.3379.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_23,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_23,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.282 [error] <0.3381.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_25,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_25,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.282 [error] <0.3380.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_24,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_24,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.282 [error] <0.3383.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_27,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_27,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.282 [error] <0.3385.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_29,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_29,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.282 [error] <0.3384.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_28,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_28,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.282 [error] <0.3388.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_32,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_32,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.283 [error] <0.3387.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_31,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_31,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.283 [error] <0.3386.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_30,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_30,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.283 [error] <0.3382.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_26,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_26,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.283 [error] <0.3378.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_22,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_22,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.283 [error] <0.3362.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_6,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_6,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.283 [info] <0.3407.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): mnesia2_tm_3 terminated: shutdown

2016-04-10 16:45:38.286 [info] <0.3407.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): mnesia2_tm_1 terminated: shutdown

2016-04-10 16:45:38.286 [info] <0.3407.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): mnesia2_tm_4 terminated: shutdown

2016-04-10 16:45:38.286 [info] <0.3407.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): mnesia2_tm_2 terminated: shutdown

2016-04-10 16:45:38.286 [info] <0.3407.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): mnesia2_tm_13 terminated: shutdown

2016-04-10 16:45:38.286 [error] <0.3322.0> CRASH REPORT Process <0.3322.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:45:38.286 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:45:40.374 [info] <0.3451.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): mnesia2_monitor starting: <0.3453.0>

2016-04-10 16:45:40.376 [info] <0.3451.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Mnesia2 debug level set to verbose
2016-04-10 16:45:40.376 [info] <0.3451.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): mnesia2_subscr starting: <0.3454.0>

2016-04-10 16:45:40.376 [info] <0.3451.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): mnesia2_locker starting: <0.3455.0>

2016-04-10 16:45:40.377 [info] <0.3451.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): mnesia2_recover starting: <0.3456.0>

2016-04-10 16:45:40.377 [info] <0.3457.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.3457.0>
2016-04-10 16:45:40.377 [info] <0.3451.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): mnesia2_tm starting: <0.3457.0>

2016-04-10 16:45:40.378 [info] <0.3451.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Schema initiated from: default

2016-04-10 16:45:40.379 [info] <0.7.0> Application mnesia2 started on node 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:45:40.381 [error] <0.3465.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.381 [error] <0.3467.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.381 [error] <0.3466.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.381 [error] <0.3464.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.381 [error] <0.3469.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.381 [error] <0.3471.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.381 [error] <0.3470.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.381 [error] <0.3473.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_11,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_11,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.381 [error] <0.3475.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_13,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_13,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.382 [error] <0.3474.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_12,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_12,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.382 [error] <0.3472.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_10,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_10,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.382 [error] <0.3477.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_15,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_15,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.382 [error] <0.3479.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_17,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_17,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.382 [error] <0.3478.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_16,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_16,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.382 [error] <0.3481.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_19,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_19,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.382 [error] <0.3483.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_21,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_21,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.382 [error] <0.3482.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_20,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_20,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.382 [error] <0.3480.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_18,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_18,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.382 [error] <0.3476.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_14,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_14,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.382 [error] <0.3485.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_23,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_23,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.382 [error] <0.3487.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_25,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_25,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.382 [error] <0.3486.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_24,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_24,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.383 [error] <0.3489.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_27,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_27,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.383 [error] <0.3491.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_29,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_29,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.383 [error] <0.3490.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_28,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_28,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.383 [error] <0.3494.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_32,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_32,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:42.402 [warning] <0.6.0> lager_error_logger_h dropped 5 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:45:42.403 [info] <0.3532.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): mnesia2_monitor starting: <0.3534.0>

2016-04-10 16:45:42.403 [info] <0.3532.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Version: "1.0.0"

2016-04-10 16:45:42.404 [info] <0.3532.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env access_module: mnesia2

2016-04-10 16:45:42.404 [info] <0.3532.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env auto_repair: true

2016-04-10 16:45:42.404 [info] <0.3532.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env backup_module: mnesia2_backup

2016-04-10 16:45:42.404 [info] <0.3532.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env debug: debug

2016-04-10 16:45:42.405 [info] <0.3532.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test7357@testing-worker-linux-docker-6a120f93-3374-linux-13.2016-04-10_16.45.00/Mnesia2.test7357@testing-worker-linux-docker-6a120f93-3374-linux-13"

2016-04-10 16:45:42.405 [info] <0.3532.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env dump_disc_copies_at_startup: true

2016-04-10 16:45:42.405 [info] <0.3532.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env dump_log_load_regulation: false

2016-04-10 16:45:42.405 [info] <0.3532.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env dump_log_time_threshold: 180000

2016-04-10 16:45:42.405 [info] <0.3532.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env dump_log_update_in_place: true

2016-04-10 16:45:42.405 [info] <0.3532.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env dump_log_write_threshold: 1000

2016-04-10 16:45:42.406 [info] <0.3532.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env event_module: mnesia2_event

2016-04-10 16:45:42.406 [info] <0.3532.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env extra_db_nodes: []

2016-04-10 16:45:42.406 [info] <0.3532.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env ignore_fallback_at_startup: false

2016-04-10 16:45:42.406 [info] <0.3532.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env fallback_error_function: {mnesia2,lkill}

2016-04-10 16:45:42.406 [info] <0.3532.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env max_wait_for_decision: infinity

2016-04-10 16:45:42.406 [info] <0.3532.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env schema_location: opt_disc

2016-04-10 16:45:42.406 [info] <0.3532.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env core_dir: false

2016-04-10 16:45:42.407 [info] <0.3532.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env pid_sort_order: false

2016-04-10 16:45:42.407 [info] <0.3532.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env no_table_loaders: 2

2016-04-10 16:45:42.407 [info] <0.3532.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env dc_dump_limit: 4

2016-04-10 16:45:42.407 [info] <0.3532.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env send_compressed: 0

2016-04-10 16:45:42.407 [info] <0.3532.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env send_max_packets: 20

2016-04-10 16:45:42.407 [info] <0.3532.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env send_max_transfer_size: 7500

2016-04-10 16:45:42.407 [info] <0.3532.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Mnesia2 debug level set to debug
2016-04-10 16:45:42.407 [info] <0.3532.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): mnesia2_subscr starting: <0.3535.0>

2016-04-10 16:45:42.408 [info] <0.3532.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): mnesia2_locker starting: <0.3536.0>

2016-04-10 16:45:42.408 [info] <0.3532.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): mnesia2_recover starting: <0.3537.0>

2016-04-10 16:45:42.408 [info] <0.3532.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): mnesia2_tm starting: <0.3538.0>

2016-04-10 16:45:42.409 [info] <0.3532.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Schema initiated from: default

2016-04-10 16:45:42.409 [info] <0.3538.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.3538.0>
2016-04-10 16:45:42.409 [info] <0.3532.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): debug fun {mnesia2_tm,init} in ets mnesia2_debug does not exist, ignoring
2016-04-10 16:45:42.409 [info] <0.3532.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): mnesia2_controller starting: <0.3541.0>

2016-04-10 16:45:42.410 [info] <0.3532.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): mnesia2_late_loader starting: <0.3542.0>

2016-04-10 16:45:42.410 [info] <0.3532.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Intend to load tables: []

2016-04-10 16:45:42.410 [info] <0.3532.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): debug fun {mnesia2_controller,late_disc_load} in ets mnesia2_debug does not exist, ignoring
2016-04-10 16:45:44.435 [warning] <0.6.0> lager_error_logger_h dropped 40 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:45:44.436 [info] <0.3614.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): mnesia2_monitor starting: <0.3616.0>

2016-04-10 16:45:44.436 [info] <0.3614.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Version: "1.0.0"

2016-04-10 16:45:44.437 [info] <0.3614.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env access_module: mnesia2

2016-04-10 16:45:44.437 [info] <0.3614.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env auto_repair: true

2016-04-10 16:45:44.437 [info] <0.3614.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env backup_module: mnesia2_backup

2016-04-10 16:45:44.438 [info] <0.3614.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env debug: trace

2016-04-10 16:45:44.438 [info] <0.3614.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test7357@testing-worker-linux-docker-6a120f93-3374-linux-13.2016-04-10_16.45.00/Mnesia2.test7357@testing-worker-linux-docker-6a120f93-3374-linux-13"

2016-04-10 16:45:44.438 [info] <0.3620.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.3620.0>
2016-04-10 16:45:44.439 [info] <0.3614.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env dump_disc_copies_at_startup: true

2016-04-10 16:45:44.439 [info] <0.3614.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env dump_log_load_regulation: false

2016-04-10 16:45:44.439 [info] <0.3614.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env dump_log_time_threshold: 180000

2016-04-10 16:45:44.439 [info] <0.3614.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env dump_log_update_in_place: true

2016-04-10 16:45:44.440 [info] <0.3614.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env dump_log_write_threshold: 1000

2016-04-10 16:45:44.440 [info] <0.3614.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env event_module: mnesia2_event

2016-04-10 16:45:46.464 [warning] <0.6.0> lager_error_logger_h dropped 5 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:45:46.465 [info] <0.3677.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): mnesia2_monitor starting: <0.3679.0>

2016-04-10 16:45:46.465 [info] <0.3677.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Version: "1.0.0"

2016-04-10 16:45:46.465 [info] <0.3677.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env access_module: mnesia2

2016-04-10 16:45:46.465 [info] <0.3677.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env auto_repair: true

2016-04-10 16:45:46.465 [info] <0.3677.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env backup_module: mnesia2_backup

2016-04-10 16:45:46.465 [info] <0.3677.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env debug: debug

2016-04-10 16:45:46.465 [info] <0.3677.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test7357@testing-worker-linux-docker-6a120f93-3374-linux-13.2016-04-10_16.45.00/Mnesia2.test7357@testing-worker-linux-docker-6a120f93-3374-linux-13"

2016-04-10 16:45:46.465 [info] <0.3677.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env dump_disc_copies_at_startup: true

2016-04-10 16:45:46.466 [info] <0.3677.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env dump_log_load_regulation: false

2016-04-10 16:45:46.466 [info] <0.3677.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env dump_log_time_threshold: 180000

2016-04-10 16:45:46.466 [info] <0.3677.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env dump_log_update_in_place: true

2016-04-10 16:45:46.466 [info] <0.3677.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env dump_log_write_threshold: 1000

2016-04-10 16:45:46.466 [info] <0.3677.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env event_module: mnesia2_event

2016-04-10 16:45:46.466 [info] <0.3677.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env extra_db_nodes: []

2016-04-10 16:45:46.466 [info] <0.3677.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env ignore_fallback_at_startup: false

2016-04-10 16:45:46.466 [info] <0.3677.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env fallback_error_function: {mnesia2,lkill}

2016-04-10 16:45:46.467 [info] <0.3677.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env max_wait_for_decision: infinity

2016-04-10 16:45:46.467 [info] <0.3677.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env schema_location: opt_disc

2016-04-10 16:45:46.467 [info] <0.3677.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env core_dir: false

2016-04-10 16:45:46.468 [info] <0.3683.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.3683.0>
2016-04-10 16:45:46.468 [info] <0.3677.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env pid_sort_order: false

2016-04-10 16:45:46.468 [info] <0.3677.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env no_table_loaders: 2

2016-04-10 16:45:46.468 [info] <0.3677.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env dc_dump_limit: 4

2016-04-10 16:45:46.468 [info] <0.3677.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env send_compressed: 0

2016-04-10 16:45:46.469 [info] <0.3677.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env send_max_packets: 20

2016-04-10 16:45:46.469 [info] <0.3677.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Env send_max_transfer_size: 7500

2016-04-10 16:45:46.469 [info] <0.3677.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Mnesia2 debug level set to debug
2016-04-10 16:45:46.469 [info] <0.3677.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): mnesia2_subscr starting: <0.3680.0>

2016-04-10 16:45:46.470 [info] <0.3677.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): mnesia2_locker starting: <0.3681.0>

2016-04-10 16:45:48.482 [warning] <0.6.0> lager_error_logger_h dropped 10 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:45:48.484 [info] <0.3748.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.3748.0>
2016-04-10 16:45:48.486 [info] <0.7.0> Application mnesia2 started on node 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:45:48.487 [error] <0.3739.0> CRASH REPORT Process <0.3739.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:45:48.487 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:45:50.565 [info] <0.3812.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.3812.0>
2016-04-10 16:45:50.567 [info] <0.7.0> Application mnesia2 started on node 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:45:50.568 [error] <0.3803.0> CRASH REPORT Process <0.3803.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:45:50.569 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:45:51.671 [info] <0.3883.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.3883.0>
2016-04-10 16:45:51.673 [info] <0.7.0> Application mnesia2 started on node 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:45:51.675 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:45:51.682 [info] <0.3944.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.3944.0>
2016-04-10 16:46:00.170 [warning] <0.3938.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 16:46:00.562 [warning] <0.3938.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 16:46:00.949 [warning] <0.3938.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 16:46:04.764 [warning] <0.3938.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 16:46:05.165 [warning] <0.3938.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 16:46:05.536 [warning] <0.3938.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 16:46:06.737 [error] <0.3935.0> CRASH REPORT Process <0.3935.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:46:06.737 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:46:08.870 [info] <0.4513.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.4513.0>
2016-04-10 16:46:08.872 [info] <0.7.0> Application mnesia2 started on node 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:46:14.882 [error] <0.4504.0> CRASH REPORT Process <0.4504.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:46:14.882 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:46:16.983 [info] <0.4613.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.4613.0>
2016-04-10 16:46:16.986 [info] <0.7.0> Application mnesia2 started on node 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:46:18.011 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:46:20.120 [info] <0.4729.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.4729.0>
2016-04-10 16:46:20.122 [info] <0.7.0> Application mnesia2 started on node 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:46:20.129 [error] <0.4720.0> CRASH REPORT Process <0.4720.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:46:20.129 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:46:22.161 [info] <0.4796.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.4796.0>
2016-04-10 16:46:22.163 [info] <0.7.0> Application mnesia2 started on node 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:46:22.187 [error] <0.4787.0> CRASH REPORT Process <0.4787.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:46:22.187 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:46:24.525 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:46:24.558 [info] <0.1790.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.1790.0>
2016-04-10 16:46:24.561 [info] <0.7.0> Application mnesia2 started on node 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:46:24.538 [info] <0.4888.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.4888.0>
2016-04-10 16:46:24.540 [info] <0.7.0> Application mnesia2 started on node 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:46:25.563 [error] <0.1842.0> gen_server <0.1842.0> terminated with reason: killed
2016-04-10 16:46:25.563 [error] <0.1842.0> CRASH REPORT Process <0.1842.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:46:25.564 [error] <0.1781.0> CRASH REPORT Process <0.1781.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:46:25.564 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:46:27.595 [info] <0.1858.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.1858.0>
2016-04-10 16:46:27.603 [info] <0.7.0> Application mnesia2 started on node 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:46:28.606 [error] <0.4951.0> gen_server <0.4951.0> terminated with reason: killed
2016-04-10 16:46:28.606 [error] <0.4951.0> CRASH REPORT Process <0.4951.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:46:28.606 [error] <0.4879.0> CRASH REPORT Process <0.4879.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:46:28.606 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:46:29.659 [error] <0.1849.0> CRASH REPORT Process <0.1849.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:46:29.659 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:46:30.749 [info] <0.1939.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.1939.0>
2016-04-10 16:46:30.767 [info] <0.7.0> Application mnesia2 started on node 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:46:30.769 [error] <0.1930.0> CRASH REPORT Process <0.1930.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:46:30.744 [info] <0.4994.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.4994.0>
2016-04-10 16:46:30.746 [info] <0.7.0> Application mnesia2 started on node 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:46:30.769 [error] <0.4985.0> CRASH REPORT Process <0.4985.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:46:30.770 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:46:30.819 [info] <0.5069.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.5069.0>
2016-04-10 16:46:30.769 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:46:34.764 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:46:34.843 [info] <0.5193.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.5193.0>
2016-04-10 16:46:34.848 [info] <0.7.0> Application mnesia2 started on node 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:46:34.834 [info] <0.2009.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.2009.0>
2016-04-10 16:46:34.835 [info] <0.7.0> Application mnesia2 started on node 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:46:44.038 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:46:44.049 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:46:45.177 [info] <0.2131.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.2131.0>
2016-04-10 16:46:45.186 [info] <0.7.0> Application mnesia2 started on node 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:46:45.248 [error] <0.2183.0> gen_server <0.2183.0> terminated with reason: killed
2016-04-10 16:46:45.248 [error] <0.2183.0> CRASH REPORT Process <0.2183.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:46:45.249 [error] <0.2122.0> CRASH REPORT Process <0.2122.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:46:45.169 [info] <0.5324.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.5324.0>
2016-04-10 16:46:45.171 [info] <0.7.0> Application mnesia2 started on node 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:46:45.271 [error] <0.5315.0> CRASH REPORT Process <0.5315.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:46:45.271 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:46:45.301 [info] <0.5412.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.5412.0>
2016-04-10 16:46:45.249 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:46:45.503 [info] <0.2219.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.2219.0>
2016-04-10 16:46:46.997 [warning] <0.6.0> lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:46:46.997 [error] <0.2210.0> CRASH REPORT Process <0.2210.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:46:46.997 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:46:48.054 [info] <0.2322.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.2322.0>
2016-04-10 16:46:48.060 [info] <0.7.0> Application mnesia2 started on node 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:46:48.071 [error] <0.2334.0> gen_server <0.2334.0> terminated with reason: killed
2016-04-10 16:46:48.042 [warning] <0.6.0> lager_error_logger_h dropped 14 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:46:48.048 [info] <0.5535.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.5535.0>
2016-04-10 16:46:48.050 [info] <0.7.0> Application mnesia2 started on node 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:46:48.072 [error] <0.5599.0> gen_server <0.5599.0> terminated with reason: killed
2016-04-10 16:46:48.071 [error] <0.2334.0> CRASH REPORT Process <0.2334.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:46:48.072 [error] <0.5599.0> CRASH REPORT Process <0.5599.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:46:48.071 [error] <0.2313.0> CRASH REPORT Process <0.2313.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:46:48.074 [error] <0.5526.0> CRASH REPORT Process <0.5526.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:46:48.074 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:46:48.071 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:46:50.269 [info] <0.5646.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.5646.0>
2016-04-10 16:46:50.271 [info] <0.7.0> Application mnesia2 started on node 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:46:50.340 [error] <0.5710.0> gen_server <0.5710.0> terminated with reason: killed
2016-04-10 16:46:50.331 [info] <0.2397.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.2397.0>
2016-04-10 16:46:50.336 [info] <0.7.0> Application mnesia2 started on node 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:46:50.341 [error] <0.2408.0> gen_server <0.2408.0> terminated with reason: killed
2016-04-10 16:46:50.340 [error] <0.5710.0> CRASH REPORT Process <0.5710.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:46:50.341 [error] <0.2408.0> CRASH REPORT Process <0.2408.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:46:50.340 [error] <0.5637.0> CRASH REPORT Process <0.5637.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:46:50.341 [error] <0.2388.0> CRASH REPORT Process <0.2388.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:46:50.340 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:46:50.341 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:46:52.373 [info] <0.5726.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.5726.0>
2016-04-10 16:46:52.380 [info] <0.7.0> Application mnesia2 started on node 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:46:52.400 [error] <0.5717.0> CRASH REPORT Process <0.5717.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:46:52.365 [info] <0.2456.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.2456.0>
2016-04-10 16:46:52.367 [info] <0.7.0> Application mnesia2 started on node 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:46:52.400 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:46:53.845 [error] <0.2447.0> CRASH REPORT Process <0.2447.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:46:53.845 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:46:54.960 [info] <0.5851.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.5851.0>
2016-04-10 16:46:54.963 [info] <0.7.0> Application mnesia2 started on node 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:46:55.295 [error] <0.5904.0> gen_server <0.5904.0> terminated with reason: killed
2016-04-10 16:46:54.964 [info] <0.2545.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.2545.0>
2016-04-10 16:46:54.985 [info] <0.7.0> Application mnesia2 started on node 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:46:55.296 [error] <0.2557.0> gen_server <0.2557.0> terminated with reason: killed
2016-04-10 16:46:55.296 [error] <0.2557.0> CRASH REPORT Process <0.2557.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:46:55.295 [error] <0.5904.0> CRASH REPORT Process <0.5904.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:46:55.295 [error] <0.5896.0> gen_server <0.5896.0> terminated with reason: killed
2016-04-10 16:46:55.296 [error] <0.2536.0> CRASH REPORT Process <0.2536.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:46:55.295 [error] <0.5896.0> CRASH REPORT Process <0.5896.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:46:55.295 [error] <0.5842.0> CRASH REPORT Process <0.5842.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:46:55.295 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:46:55.296 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:46:55.211 [info] <0.7.0> Application lager started on node 'd702824o702832n702832@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:46:55.211 [info] <0.7.0> Application poolgirl started on node 'd702824o702832n702832@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:46:55.236 [info] <0.102.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702824o702832n702832@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.102.0>
2016-04-10 16:46:55.252 [info] <0.7.0> Application mnesia2 started on node 'd702824o702832n702832@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:46:57.435 [info] <0.2626.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.2626.0>
2016-04-10 16:46:57.441 [info] <0.7.0> Application mnesia2 started on node 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:46:57.444 [error] <0.2637.0> gen_server <0.2637.0> terminated with reason: killed
2016-04-10 16:46:57.428 [info] <0.5946.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.5946.0>
2016-04-10 16:46:57.430 [info] <0.7.0> Application mnesia2 started on node 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:46:57.444 [error] <0.6008.0> gen_server <0.6008.0> terminated with reason: killed
2016-04-10 16:46:57.444 [error] <0.2637.0> CRASH REPORT Process <0.2637.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:46:57.444 [error] <0.6008.0> CRASH REPORT Process <0.6008.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:46:57.445 [error] <0.2617.0> CRASH REPORT Process <0.2617.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:46:57.444 [error] <0.5937.0> CRASH REPORT Process <0.5937.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:46:57.444 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:46:57.445 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:46:59.571 [info] <0.6040.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.6040.0>
2016-04-10 16:46:59.573 [info] <0.7.0> Application mnesia2 started on node 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:46:59.584 [error] <0.6084.0> gen_server <0.6084.0> terminated with reason: killed
2016-04-10 16:46:59.575 [info] <0.2696.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.2696.0>
2016-04-10 16:46:59.579 [info] <0.7.0> Application mnesia2 started on node 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:46:59.585 [error] <0.2707.0> gen_server <0.2707.0> terminated with reason: killed
2016-04-10 16:46:59.584 [error] <0.6084.0> CRASH REPORT Process <0.6084.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:46:59.585 [error] <0.2707.0> CRASH REPORT Process <0.2707.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:46:59.584 [error] <0.6031.0> CRASH REPORT Process <0.6031.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:46:59.585 [error] <0.2687.0> CRASH REPORT Process <0.2687.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:46:59.584 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:46:59.585 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:47:01.711 [info] <0.2771.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.2771.0>
2016-04-10 16:47:01.715 [info] <0.7.0> Application mnesia2 started on node 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:47:01.718 [error] <0.2762.0> CRASH REPORT Process <0.2762.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:47:01.696 [info] <0.6126.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.6126.0>
2016-04-10 16:47:01.699 [info] <0.7.0> Application mnesia2 started on node 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:47:01.718 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:47:02.745 [error] <0.6121.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.6138.0> exit with reason killed in context child_terminated
2016-04-10 16:47:02.745 [error] <0.6121.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.6138.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 16:47:02.745 [error] <0.6117.0> CRASH REPORT Process <0.6117.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:47:02.746 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:47:04.806 [info] <0.2841.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.2841.0>
2016-04-10 16:47:04.808 [info] <0.7.0> Application mnesia2 started on node 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:47:10.183 [info] <0.6204.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.6204.0>
2016-04-10 16:47:10.194 [info] <0.7.0> Application mnesia2 started on node 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:47:10.201 [error] <0.6266.0> gen_server <0.6266.0> terminated with reason: killed
2016-04-10 16:47:10.201 [error] <0.6266.0> CRASH REPORT Process <0.6266.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:10.201 [error] <0.6195.0> CRASH REPORT Process <0.6195.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:47:10.200 [error] <0.2908.0> gen_server <0.2908.0> terminated with reason: killed
2016-04-10 16:47:10.200 [error] <0.2908.0> CRASH REPORT Process <0.2908.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:10.203 [error] <0.2832.0> CRASH REPORT Process <0.2832.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:47:10.201 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:47:10.204 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:47:11.376 [info] <0.2941.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.2941.0>
2016-04-10 16:47:11.391 [info] <0.7.0> Application mnesia2 started on node 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:47:11.452 [error] <0.2931.0> CRASH REPORT Process <0.2931.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:47:11.364 [info] <0.6314.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.6314.0>
2016-04-10 16:47:11.368 [info] <0.7.0> Application mnesia2 started on node 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:47:11.531 [error] <0.6401.0> gen_server <0.6401.0> terminated with reason: killed
2016-04-10 16:47:11.531 [error] <0.6401.0> CRASH REPORT Process <0.6401.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:11.531 [error] <0.6305.0> CRASH REPORT Process <0.6305.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:47:11.398 [info] <0.192.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702824o702832n702832@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.192.0>
2016-04-10 16:47:11.409 [info] <0.7.0> Application mnesia2 started on node 'd702824o702832n702832@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:47:11.551 [error] <0.187.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.208.0> exit with reason killed in context child_terminated
2016-04-10 16:47:11.552 [error] <0.187.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.208.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 16:47:11.532 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:47:11.647 [info] <0.6436.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.6436.0>
2016-04-10 16:47:11.452 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:47:11.499 [info] <0.3031.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.3031.0>
2016-04-10 16:47:11.614 [info] <0.3126.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.3126.0>
2016-04-10 16:47:11.648 [info] <0.296.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702824o702832n702832@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.296.0>
2016-04-10 16:47:12.481 [warning] <0.6.0> lager_error_logger_h dropped 37 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:47:12.481 [error] <0.358.0> gen_server <0.358.0> terminated with reason: killed
2016-04-10 16:47:12.481 [error] <0.358.0> CRASH REPORT Process <0.358.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:12.482 [error] <0.368.0> gen_server <0.368.0> terminated with reason: killed
2016-04-10 16:47:12.482 [error] <0.368.0> CRASH REPORT Process <0.368.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:12.482 [error] <0.287.0> CRASH REPORT Process <0.287.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:47:12.482 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:47:12.523 [info] <0.392.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702824o702832n702832@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.392.0>
2016-04-10 16:47:12.524 [info] <0.7.0> Application mnesia2 started on node 'd702824o702832n702832@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:47:14.660 [warning] <0.6.0> lager_error_logger_h dropped 14 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:47:14.660 [error] <0.6534.0> gen_server <0.6534.0> terminated with reason: killed
2016-04-10 16:47:14.660 [error] <0.6502.0> gen_server <0.6502.0> terminated with reason: killed
2016-04-10 16:47:14.660 [error] <0.6534.0> CRASH REPORT Process <0.6534.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:14.660 [error] <0.6502.0> CRASH REPORT Process <0.6502.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:14.660 [error] <0.6427.0> CRASH REPORT Process <0.6427.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:47:14.681 [error] <0.3219.0> gen_server <0.3219.0> terminated with reason: killed
2016-04-10 16:47:14.681 [error] <0.3219.0> CRASH REPORT Process <0.3219.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:14.681 [error] <0.3117.0> CRASH REPORT Process <0.3117.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:47:14.660 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:47:14.895 [info] <0.6553.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.6553.0>
2016-04-10 16:47:15.202 [info] <0.7.0> Application mnesia2 started on node 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:47:14.681 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:47:14.934 [info] <0.3240.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.3240.0>
2016-04-10 16:47:14.956 [info] <0.7.0> Application mnesia2 started on node 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:47:14.830 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:47:14.862 [info] <0.498.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702824o702832n702832@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.498.0>
2016-04-10 16:47:14.864 [info] <0.7.0> Application mnesia2 started on node 'd702824o702832n702832@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:47:15.713 [error] <0.572.0> gen_server <0.572.0> terminated with reason: killed
2016-04-10 16:47:15.713 [error] <0.572.0> CRASH REPORT Process <0.572.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:15.713 [error] <0.566.0> gen_server <0.566.0> terminated with reason: killed
2016-04-10 16:47:15.713 [error] <0.566.0> CRASH REPORT Process <0.566.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:15.713 [error] <0.489.0> CRASH REPORT Process <0.489.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:47:15.713 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:47:15.740 [info] <0.597.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702824o702832n702832@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.597.0>
2016-04-10 16:47:15.741 [info] <0.7.0> Application mnesia2 started on node 'd702824o702832n702832@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:47:15.864 [error] <0.6648.0> gen_server <0.6648.0> terminated with reason: killed
2016-04-10 16:47:15.864 [error] <0.6648.0> CRASH REPORT Process <0.6648.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:15.864 [error] <0.6544.0> CRASH REPORT Process <0.6544.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:47:15.889 [error] <0.3327.0> gen_server <0.3327.0> terminated with reason: killed
2016-04-10 16:47:15.889 [error] <0.3327.0> CRASH REPORT Process <0.3327.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:15.889 [error] <0.3231.0> CRASH REPORT Process <0.3231.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:47:15.889 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:47:15.978 [info] <0.3348.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.3348.0>
2016-04-10 16:47:16.020 [info] <0.7.0> Application mnesia2 started on node 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:47:16.527 [error] <0.3341.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.3343.0> exit with reason killed in context child_terminated
2016-04-10 16:47:16.527 [error] <0.3341.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.3343.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 16:47:16.527 [error] <0.3345.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-10 16:47:16.527 [error] <0.3345.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:16.527 [error] <0.3344.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-10 16:47:16.527 [error] <0.3347.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-10 16:47:16.527 [error] <0.3347.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:16.527 [error] <0.3369.0> gen_server mnesia2_snmp_sup terminated with reason: killed
2016-04-10 16:47:16.527 [error] <0.3369.0> CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:15.865 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:47:15.979 [info] <0.6666.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.6666.0>
2016-04-10 16:47:15.991 [info] <0.7.0> Application mnesia2 started on node 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:47:16.529 [info] <0.7.0> Application mnesia2 exited with reason: shutdown
2016-04-10 16:47:16.592 [info] <0.3444.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.3444.0>
2016-04-10 16:47:16.602 [info] <0.7.0> Application mnesia2 started on node 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:47:15.916 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:47:15.932 [info] <0.698.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702824o702832n702832@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.698.0>
2016-04-10 16:47:17.640 [warning] <0.6.0> lager_error_logger_h dropped 5 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:47:17.642 [info] <0.3522.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.3522.0>
2016-04-10 16:47:17.674 [info] <0.7.0> Application mnesia2 started on node 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:47:17.711 [error] <0.3513.0> CRASH REPORT Process <0.3513.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:47:17.726 [error] <0.6778.0> gen_server <0.6778.0> terminated with reason: killed
2016-04-10 16:47:17.726 [error] <0.819.0> gen_server <0.819.0> terminated with reason: killed
2016-04-10 16:47:17.726 [error] <0.6778.0> CRASH REPORT Process <0.6778.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:17.726 [error] <0.819.0> CRASH REPORT Process <0.819.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:17.727 [error] <0.6728.0> gen_server <0.6728.0> terminated with reason: killed
2016-04-10 16:47:17.727 [error] <0.764.0> gen_server <0.764.0> terminated with reason: killed
2016-04-10 16:47:17.727 [error] <0.6728.0> CRASH REPORT Process <0.6728.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:17.727 [error] <0.764.0> CRASH REPORT Process <0.764.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:17.728 [error] <0.6657.0> CRASH REPORT Process <0.6657.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:47:17.728 [error] <0.689.0> CRASH REPORT Process <0.689.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:47:17.711 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:47:17.819 [info] <0.3600.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.3600.0>
2016-04-10 16:47:17.888 [info] <0.3695.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.3695.0>
2016-04-10 16:47:17.988 [info] <0.3785.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.3785.0>
2016-04-10 16:47:18.028 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:47:18.028 [error] <0.3844.0> gen_server <0.3844.0> terminated with reason: killed
2016-04-10 16:47:18.028 [error] <0.3844.0> CRASH REPORT Process <0.3844.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:18.028 [error] <0.3776.0> CRASH REPORT Process <0.3776.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:47:18.028 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:47:18.070 [info] <0.3885.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.3885.0>
2016-04-10 16:47:18.071 [info] <0.7.0> Application mnesia2 started on node 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:47:18.708 [error] <0.3940.0> gen_server <0.3940.0> terminated with reason: killed
2016-04-10 16:47:18.708 [error] <0.3940.0> CRASH REPORT Process <0.3940.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:17.728 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:47:17.812 [info] <0.6811.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.6811.0>
2016-04-10 16:47:17.816 [info] <0.7.0> Application mnesia2 started on node 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:47:18.067 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:47:18.666 [info] <0.6924.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.6924.0>
2016-04-10 16:47:18.693 [info] <0.7.0> Application mnesia2 started on node 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:47:18.707 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:47:17.728 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:47:18.751 [info] <0.7007.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.7007.0>
2016-04-10 16:47:19.358 [error] <0.7071.0> gen_server <0.7071.0> terminated with reason: killed
2016-04-10 16:47:19.272 [info] <0.3967.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.3967.0>
2016-04-10 16:47:19.302 [info] <0.7.0> Application mnesia2 started on node 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:47:19.359 [error] <0.3962.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.3969.0> exit with reason killed in context child_terminated
2016-04-10 16:47:19.358 [error] <0.7071.0> CRASH REPORT Process <0.7071.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:19.358 [error] <0.6998.0> CRASH REPORT Process <0.6998.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:47:19.359 [error] <0.3962.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.3969.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 16:47:19.360 [error] <0.3962.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_controller:start() at <0.3971.0> exit with reason killed in context shutdown_error
2016-04-10 16:47:19.362 [error] <0.3958.0> CRASH REPORT Process <0.3958.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:47:19.362 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:47:19.640 [info] <0.4059.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.4059.0>
2016-04-10 16:47:19.359 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:47:19.652 [info] <0.7108.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.7108.0>
2016-04-10 16:47:19.672 [info] <0.7.0> Application mnesia2 started on node 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:47:19.756 [error] <0.7099.0> CRASH REPORT Process <0.7099.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:47:19.640 [info] <0.848.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702824o702832n702832@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.848.0>
2016-04-10 16:47:19.643 [info] <0.7.0> Application mnesia2 started on node 'd702824o702832n702832@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:47:19.758 [error] <0.839.0> CRASH REPORT Process <0.839.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:47:19.759 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:47:19.801 [info] <0.952.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702824o702832n702832@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.952.0>
2016-04-10 16:47:19.803 [info] <0.7.0> Application mnesia2 started on node 'd702824o702832n702832@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:47:19.859 [error] emulator Error in process <0.1015.0> on node 'd702824o702832n702832@testing-worker-linux-docker-6a120f93-3374-linux-13' with exit value:
{badarg,[{mnesia2_tm,return_abort,3,[{file,"src/mnesia2_tm.erl"},{line,1092}]},{mnesia2_loader,init_receiver,5,[{file,"src/mnesia2_loader.erl"},{line,289}]},{mnesia2_loader,do_get_network_copy,5,[{file,"src/mnesia2_loader.erl"},{line,226}]},{mnesia2_controller,'-load_table_fun/1-fun-3-',5,[{file,"src/mnesia2_controller.erl"},{line,2177}]},{mnesia2_controller,'-load_and_reply/2-fun-0-',2,[{file,"src/mnesia2_controller.erl"},{line,2139}]}]}

2016-04-10 16:47:19.860 [error] <0.1001.0> gen_server <0.1001.0> terminated with reason: killed
2016-04-10 16:47:19.860 [error] <0.1001.0> CRASH REPORT Process <0.1001.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:19.860 [error] <0.996.0> gen_server <0.996.0> terminated with reason: killed
2016-04-10 16:47:19.891 [info] <0.1030.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702824o702832n702832@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.1030.0>
2016-04-10 16:47:19.756 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:47:19.823 [info] <0.7216.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.7216.0>
2016-04-10 16:47:19.911 [info] <0.7308.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.7308.0>
2016-04-10 16:47:19.799 [info] <0.4153.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.4153.0>
2016-04-10 16:47:19.888 [info] <0.4230.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.4230.0>
2016-04-10 16:47:29.919 [warning] <0.6.0> lager_error_logger_h dropped 6 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:47:29.920 [error] <0.7301.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at undefined exit with reason killed in context start_error
2016-04-10 16:47:29.920 [error] <0.7307.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-10 16:47:29.920 [error] <0.7307.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:29.920 [error] <0.7304.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-10 16:47:29.920 [error] <0.7327.0> gen_server mnesia2_snmp_sup terminated with reason: killed
2016-04-10 16:47:29.920 [error] <0.7327.0> CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:29.920 [error] <0.7305.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-10 16:47:29.920 [error] <0.7305.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:29.920 [error] <0.7299.0> CRASH REPORT Process <0.7299.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}} in application_master:init/4 line 134
2016-04-10 16:47:29.920 [info] <0.7.0> Application mnesia2 exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}}
2016-04-10 16:47:29.924 [error] <0.7304.0> CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:30.026 [warning] <0.6.0> lager_error_logger_h dropped 6 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:47:30.026 [error] <0.1074.0> gen_server <0.1074.0> terminated with reason: killed
2016-04-10 16:47:30.027 [warning] <0.6.0> lager_error_logger_h dropped 5 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:47:30.027 [error] <0.4274.0> gen_server <0.4274.0> terminated with reason: killed
2016-04-10 16:47:30.027 [error] <0.1074.0> CRASH REPORT Process <0.1074.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:30.027 [error] <0.4274.0> CRASH REPORT Process <0.4274.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:30.028 [error] <0.1021.0> CRASH REPORT Process <0.1021.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:47:30.027 [error] <0.4221.0> CRASH REPORT Process <0.4221.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:47:30.028 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:47:30.027 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:47:32.413 [info] <0.7417.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.7417.0>
2016-04-10 16:47:32.415 [info] <0.7.0> Application mnesia2 started on node 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:47:36.410 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:47:36.538 [info] <0.7553.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.7553.0>
2016-04-10 16:47:36.843 [info] <0.7.0> Application mnesia2 started on node 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:47:36.551 [info] <0.1127.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702824o702832n702832@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.1127.0>
2016-04-10 16:47:36.869 [info] <0.7.0> Application mnesia2 started on node 'd702824o702832n702832@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:47:36.566 [info] <0.4320.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.4320.0>
2016-04-10 16:47:36.576 [info] <0.7.0> Application mnesia2 started on node 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:47:42.992 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:47:43.145 [info] <0.4434.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.4434.0>
2016-04-10 16:47:43.153 [info] <0.7.0> Application mnesia2 started on node 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:47:42.999 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:47:43.120 [info] <0.7683.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.7683.0>
2016-04-10 16:47:43.123 [info] <0.7.0> Application mnesia2 started on node 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:47:43.028 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:47:43.147 [info] <0.1245.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702824o702832n702832@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.1245.0>
2016-04-10 16:47:43.161 [info] <0.7.0> Application mnesia2 started on node 'd702824o702832n702832@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:47:49.253 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:47:49.411 [info] <0.4547.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.4547.0>
2016-04-10 16:47:49.433 [info] <0.7.0> Application mnesia2 started on node 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:47:49.290 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:47:49.394 [info] <0.7812.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.7812.0>
2016-04-10 16:47:49.398 [info] <0.7.0> Application mnesia2 started on node 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:47:49.296 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:47:49.401 [info] <0.1361.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702824o702832n702832@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.1361.0>
2016-04-10 16:47:49.714 [info] <0.7.0> Application mnesia2 started on node 'd702824o702832n702832@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:48:07.266 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:48:07.421 [info] <0.8950.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.8950.0>
2016-04-10 16:48:07.729 [info] <0.7.0> Application mnesia2 started on node 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:48:07.267 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:48:07.424 [info] <0.5672.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.5672.0>
2016-04-10 16:48:07.428 [info] <0.7.0> Application mnesia2 started on node 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:48:07.298 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:48:07.444 [info] <0.2487.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702824o702832n702832@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.2487.0>
2016-04-10 16:48:07.453 [info] <0.7.0> Application mnesia2 started on node 'd702824o702832n702832@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:48:14.011 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:48:14.164 [info] <0.9090.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.9090.0>
2016-04-10 16:48:14.166 [info] <0.7.0> Application mnesia2 started on node 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:48:14.012 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:48:14.186 [info] <0.2610.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702824o702832n702832@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.2610.0>
2016-04-10 16:48:14.192 [info] <0.7.0> Application mnesia2 started on node 'd702824o702832n702832@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:48:14.042 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:48:14.168 [info] <0.5798.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.5798.0>
2016-04-10 16:48:14.474 [info] <0.7.0> Application mnesia2 started on node 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:48:20.771 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:48:20.930 [info] <0.4081.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702824o702832n702832@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.4081.0>
2016-04-10 16:48:20.940 [info] <0.7.0> Application mnesia2 started on node 'd702824o702832n702832@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:48:20.777 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:48:20.906 [info] <0.10570.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.10570.0>
2016-04-10 16:48:20.910 [info] <0.7.0> Application mnesia2 started on node 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:48:20.784 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:48:20.930 [info] <0.7271.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.7271.0>
2016-04-10 16:48:20.936 [info] <0.7.0> Application mnesia2 started on node 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:48:27.157 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:48:27.306 [info] <0.5464.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702824o702832n702832@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.5464.0>
2016-04-10 16:48:27.612 [info] <0.7.0> Application mnesia2 started on node 'd702824o702832n702832@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:48:27.166 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:48:27.290 [info] <0.11024.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.11024.0>
2016-04-10 16:48:27.595 [info] <0.7.0> Application mnesia2 started on node 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:48:27.187 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:48:27.309 [info] <0.9027.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.9027.0>
2016-04-10 16:48:27.324 [info] <0.7.0> Application mnesia2 started on node 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:48:33.724 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:48:33.857 [info] <0.5582.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702824o702832n702832@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.5582.0>
2016-04-10 16:48:34.176 [info] <0.7.0> Application mnesia2 started on node 'd702824o702832n702832@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:48:33.725 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:48:33.874 [info] <0.9820.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.9820.0>
2016-04-10 16:48:33.892 [info] <0.7.0> Application mnesia2 started on node 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:48:33.726 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:48:33.855 [info] <0.11154.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13', <0.11154.0>
2016-04-10 16:48:34.160 [info] <0.7.0> Application mnesia2 started on node 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'
2016-04-10 16:48:40.386 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:48:40.391 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:48:40.389 [info] <0.7.0> Application mnesia2 exited with reason: stopped
