2016-04-10 16:45:22.762 [error] <0.664.0> CRASH REPORT Process <0.664.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:45:23.063 [error] <0.793.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): ** ERROR ** (ignoring core) ** FATAL ** A fallback is installed and Mnesia2 must be restarted. Forcing shutdown after mnesia2_down from 'd702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13'...

2016-04-10 16:45:23.063 [error] <0.794.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_locker:start() at <0.797.0> exit with reason killed in context child_terminated
2016-04-10 16:45:23.063 [error] <0.794.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_locker:start() at <0.797.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 16:45:23.066 [error] <0.792.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.794.0> exit with reason shutdown in context child_terminated
2016-04-10 16:45:23.066 [error] <0.792.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.794.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 16:45:23.670 [error] <0.363.0> Mnesia2('d702830o702826n702826@testing-worker-linux-docker-6a120f93-3374-linux-13'): ** ERROR ** (ignoring core) ** FATAL ** A fallback is installed and Mnesia2 must be restarted. Forcing shutdown after mnesia2_down from 'test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'...

2016-04-10 16:45:24.468 [error] <0.517.0> gen_server <0.517.0> terminated with reason: killed
2016-04-10 16:45:24.467 [error] <0.1022.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.1042.0> exit with reason killed in context child_terminated
2016-04-10 16:45:24.468 [error] <0.517.0> CRASH REPORT Process <0.517.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:45:24.467 [error] <0.1022.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.1042.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 16:45:24.469 [error] <0.450.0> CRASH REPORT Process <0.450.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:45:24.469 [error] <0.1088.0> gen_server <0.1088.0> terminated with reason: killed
2016-04-10 16:45:24.469 [error] <0.1088.0> CRASH REPORT Process <0.1088.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:45:24.470 [error] <0.1018.0> CRASH REPORT Process <0.1018.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:45:25.160 [error] <0.1322.0> gen_server <0.1322.0> terminated with reason: killed
2016-04-10 16:45:25.158 [error] <0.661.0> gen_server <0.661.0> terminated with reason: killed
2016-04-10 16:45:25.160 [error] <0.1322.0> CRASH REPORT Process <0.1322.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:45:25.158 [error] <0.661.0> CRASH REPORT Process <0.661.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:45:25.160 [error] <0.1253.0> CRASH REPORT Process <0.1253.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:45:25.159 [error] <0.539.0> CRASH REPORT Process <0.539.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:45:25.402 [error] <0.816.0> gen_server <0.816.0> terminated with reason: killed
2016-04-10 16:45:25.407 [error] <0.1550.0> gen_server <0.1550.0> terminated with reason: killed
2016-04-10 16:45:25.403 [error] <0.816.0> CRASH REPORT Process <0.816.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:45:25.407 [error] <0.1550.0> CRASH REPORT Process <0.1550.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:45:25.404 [error] <0.753.0> CRASH REPORT Process <0.753.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:45:26.000 [error] <0.1715.0> CRASH REPORT Process <0.1715.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:45:26.555 [error] <0.1123.0> gen_server <0.1123.0> terminated with reason: killed
2016-04-10 16:45:26.552 [error] <0.1907.0> gen_server <0.1907.0> terminated with reason: killed
2016-04-10 16:45:26.555 [error] <0.1123.0> CRASH REPORT Process <0.1123.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:45:26.552 [error] <0.1907.0> CRASH REPORT Process <0.1907.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:45:26.556 [error] <0.1059.0> CRASH REPORT Process <0.1059.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:45:26.553 [error] <0.1841.0> CRASH REPORT Process <0.1841.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:45:27.231 [error] <0.2106.0> CRASH REPORT Process <0.2106.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:45:27.233 [error] <0.1261.0> CRASH REPORT Process <0.1261.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:45:28.000 [error] <0.2427.0> gen_server <0.2427.0> terminated with reason: killed
2016-04-10 16:45:28.000 [error] <0.2427.0> CRASH REPORT Process <0.2427.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:45:28.001 [error] <0.2377.0> CRASH REPORT Process <0.2377.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:45:28.246 [error] <0.1630.0> gen_server <0.1630.0> terminated with reason: killed
2016-04-10 16:45:28.248 [error] <0.2514.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.2531.0> exit with reason killed in context child_terminated
2016-04-10 16:45:28.247 [error] <0.1630.0> CRASH REPORT Process <0.1630.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:45:28.248 [error] <0.2514.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.2531.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 16:45:28.247 [error] <0.1567.0> CRASH REPORT Process <0.1567.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:45:31.165 [error] <0.2965.0> CRASH REPORT Process <0.2965.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:45:35.878 [error] <0.3239.0> CRASH REPORT Process <0.3239.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:45:38.280 [error] <0.3361.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.281 [error] <0.3363.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.281 [error] <0.3365.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.281 [error] <0.3364.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.281 [error] <0.3367.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_11,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_11,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.281 [error] <0.3368.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_12,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_12,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.281 [error] <0.3366.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_10,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_10,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.281 [error] <0.3373.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_17,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_17,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.281 [error] <0.3372.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_16,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_16,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.281 [error] <0.3375.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_19,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_19,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.282 [error] <0.3377.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_21,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_21,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.282 [error] <0.3376.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_20,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_20,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.282 [error] <0.3374.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_18,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_18,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.282 [error] <0.3379.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_23,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_23,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.282 [error] <0.3381.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_25,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_25,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.282 [error] <0.3380.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_24,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_24,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.282 [error] <0.3383.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_27,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_27,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.282 [error] <0.3385.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_29,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_29,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.282 [error] <0.3384.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_28,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_28,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.282 [error] <0.3388.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_32,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_32,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.283 [error] <0.3387.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_31,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_31,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.283 [error] <0.3386.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_30,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_30,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.283 [error] <0.3382.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_26,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_26,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.283 [error] <0.3378.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_22,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_22,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.283 [error] <0.3362.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_6,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_6,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 16:45:38.286 [error] <0.3322.0> CRASH REPORT Process <0.3322.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:45:40.381 [error] <0.3465.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.381 [error] <0.3467.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.381 [error] <0.3466.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.381 [error] <0.3464.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.381 [error] <0.3469.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.381 [error] <0.3471.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.381 [error] <0.3470.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.381 [error] <0.3473.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_11,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_11,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.381 [error] <0.3475.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_13,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_13,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.382 [error] <0.3474.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_12,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_12,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.382 [error] <0.3472.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_10,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_10,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.382 [error] <0.3477.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_15,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_15,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.382 [error] <0.3479.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_17,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_17,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.382 [error] <0.3478.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_16,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_16,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.382 [error] <0.3481.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_19,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_19,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.382 [error] <0.3483.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_21,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_21,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.382 [error] <0.3482.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_20,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_20,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.382 [error] <0.3480.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_18,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_18,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.382 [error] <0.3476.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_14,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_14,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.382 [error] <0.3485.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_23,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_23,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.382 [error] <0.3487.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_25,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_25,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.382 [error] <0.3486.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_24,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_24,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.383 [error] <0.3489.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_27,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_27,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.383 [error] <0.3491.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_29,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_29,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.383 [error] <0.3490.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_28,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_28,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:40.383 [error] <0.3494.0> Mnesia2('test7357@testing-worker-linux-docker-6a120f93-3374-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_32,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_32,shutdown]}}}} ({error,{already_started,<0.3496.0>}})

2016-04-10 16:45:48.487 [error] <0.3739.0> CRASH REPORT Process <0.3739.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:45:50.568 [error] <0.3803.0> CRASH REPORT Process <0.3803.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:46:06.737 [error] <0.3935.0> CRASH REPORT Process <0.3935.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:46:14.882 [error] <0.4504.0> CRASH REPORT Process <0.4504.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:46:20.129 [error] <0.4720.0> CRASH REPORT Process <0.4720.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:46:22.187 [error] <0.4787.0> CRASH REPORT Process <0.4787.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:46:25.563 [error] <0.1842.0> gen_server <0.1842.0> terminated with reason: killed
2016-04-10 16:46:25.563 [error] <0.1842.0> CRASH REPORT Process <0.1842.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:46:25.564 [error] <0.1781.0> CRASH REPORT Process <0.1781.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:46:28.606 [error] <0.4951.0> gen_server <0.4951.0> terminated with reason: killed
2016-04-10 16:46:28.606 [error] <0.4951.0> CRASH REPORT Process <0.4951.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:46:28.606 [error] <0.4879.0> CRASH REPORT Process <0.4879.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:46:29.659 [error] <0.1849.0> CRASH REPORT Process <0.1849.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:46:30.769 [error] <0.4985.0> CRASH REPORT Process <0.4985.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:46:30.769 [error] <0.1930.0> CRASH REPORT Process <0.1930.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:46:45.248 [error] <0.2183.0> gen_server <0.2183.0> terminated with reason: killed
2016-04-10 16:46:45.248 [error] <0.2183.0> CRASH REPORT Process <0.2183.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:46:45.249 [error] <0.2122.0> CRASH REPORT Process <0.2122.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:46:45.271 [error] <0.5315.0> CRASH REPORT Process <0.5315.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:46:46.997 [error] <0.2210.0> CRASH REPORT Process <0.2210.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:46:48.071 [error] <0.2334.0> gen_server <0.2334.0> terminated with reason: killed
2016-04-10 16:46:48.072 [error] <0.5599.0> gen_server <0.5599.0> terminated with reason: killed
2016-04-10 16:46:48.071 [error] <0.2334.0> CRASH REPORT Process <0.2334.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:46:48.072 [error] <0.5599.0> CRASH REPORT Process <0.5599.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:46:48.071 [error] <0.2313.0> CRASH REPORT Process <0.2313.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:46:48.074 [error] <0.5526.0> CRASH REPORT Process <0.5526.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:46:50.340 [error] <0.5710.0> gen_server <0.5710.0> terminated with reason: killed
2016-04-10 16:46:50.341 [error] <0.2408.0> gen_server <0.2408.0> terminated with reason: killed
2016-04-10 16:46:50.340 [error] <0.5710.0> CRASH REPORT Process <0.5710.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:46:50.341 [error] <0.2408.0> CRASH REPORT Process <0.2408.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:46:50.340 [error] <0.5637.0> CRASH REPORT Process <0.5637.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:46:50.341 [error] <0.2388.0> CRASH REPORT Process <0.2388.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:46:52.400 [error] <0.5717.0> CRASH REPORT Process <0.5717.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:46:53.845 [error] <0.2447.0> CRASH REPORT Process <0.2447.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:46:55.296 [error] <0.2557.0> gen_server <0.2557.0> terminated with reason: killed
2016-04-10 16:46:55.295 [error] <0.5904.0> gen_server <0.5904.0> terminated with reason: killed
2016-04-10 16:46:55.295 [error] <0.5904.0> CRASH REPORT Process <0.5904.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:46:55.296 [error] <0.2557.0> CRASH REPORT Process <0.2557.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:46:55.295 [error] <0.5896.0> gen_server <0.5896.0> terminated with reason: killed
2016-04-10 16:46:55.296 [error] <0.2536.0> CRASH REPORT Process <0.2536.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:46:55.295 [error] <0.5896.0> CRASH REPORT Process <0.5896.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:46:55.295 [error] <0.5842.0> CRASH REPORT Process <0.5842.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:46:57.444 [error] <0.2637.0> gen_server <0.2637.0> terminated with reason: killed
2016-04-10 16:46:57.444 [error] <0.6008.0> gen_server <0.6008.0> terminated with reason: killed
2016-04-10 16:46:57.444 [error] <0.2637.0> CRASH REPORT Process <0.2637.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:46:57.444 [error] <0.6008.0> CRASH REPORT Process <0.6008.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:46:57.445 [error] <0.2617.0> CRASH REPORT Process <0.2617.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:46:57.444 [error] <0.5937.0> CRASH REPORT Process <0.5937.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:46:59.584 [error] <0.6084.0> gen_server <0.6084.0> terminated with reason: killed
2016-04-10 16:46:59.585 [error] <0.2707.0> gen_server <0.2707.0> terminated with reason: killed
2016-04-10 16:46:59.584 [error] <0.6084.0> CRASH REPORT Process <0.6084.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:46:59.585 [error] <0.2707.0> CRASH REPORT Process <0.2707.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:46:59.584 [error] <0.6031.0> CRASH REPORT Process <0.6031.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:46:59.585 [error] <0.2687.0> CRASH REPORT Process <0.2687.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:47:01.718 [error] <0.2762.0> CRASH REPORT Process <0.2762.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:47:02.745 [error] <0.6121.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.6138.0> exit with reason killed in context child_terminated
2016-04-10 16:47:02.745 [error] <0.6121.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.6138.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 16:47:02.745 [error] <0.6117.0> CRASH REPORT Process <0.6117.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:47:10.201 [error] <0.6266.0> gen_server <0.6266.0> terminated with reason: killed
2016-04-10 16:47:10.201 [error] <0.6266.0> CRASH REPORT Process <0.6266.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:10.201 [error] <0.6195.0> CRASH REPORT Process <0.6195.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:47:10.200 [error] <0.2908.0> gen_server <0.2908.0> terminated with reason: killed
2016-04-10 16:47:10.200 [error] <0.2908.0> CRASH REPORT Process <0.2908.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:10.203 [error] <0.2832.0> CRASH REPORT Process <0.2832.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:47:11.452 [error] <0.2931.0> CRASH REPORT Process <0.2931.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:47:11.531 [error] <0.6401.0> gen_server <0.6401.0> terminated with reason: killed
2016-04-10 16:47:11.531 [error] <0.6401.0> CRASH REPORT Process <0.6401.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:11.531 [error] <0.6305.0> CRASH REPORT Process <0.6305.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:47:11.551 [error] <0.187.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.208.0> exit with reason killed in context child_terminated
2016-04-10 16:47:11.552 [error] <0.187.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.208.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 16:47:12.481 [error] <0.358.0> gen_server <0.358.0> terminated with reason: killed
2016-04-10 16:47:12.481 [error] <0.358.0> CRASH REPORT Process <0.358.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:12.482 [error] <0.368.0> gen_server <0.368.0> terminated with reason: killed
2016-04-10 16:47:12.482 [error] <0.368.0> CRASH REPORT Process <0.368.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:12.482 [error] <0.287.0> CRASH REPORT Process <0.287.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:47:14.660 [error] <0.6534.0> gen_server <0.6534.0> terminated with reason: killed
2016-04-10 16:47:14.660 [error] <0.6502.0> gen_server <0.6502.0> terminated with reason: killed
2016-04-10 16:47:14.660 [error] <0.6534.0> CRASH REPORT Process <0.6534.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:14.660 [error] <0.6502.0> CRASH REPORT Process <0.6502.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:14.660 [error] <0.6427.0> CRASH REPORT Process <0.6427.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:47:14.681 [error] <0.3219.0> gen_server <0.3219.0> terminated with reason: killed
2016-04-10 16:47:14.681 [error] <0.3219.0> CRASH REPORT Process <0.3219.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:14.681 [error] <0.3117.0> CRASH REPORT Process <0.3117.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:47:15.713 [error] <0.572.0> gen_server <0.572.0> terminated with reason: killed
2016-04-10 16:47:15.713 [error] <0.572.0> CRASH REPORT Process <0.572.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:15.713 [error] <0.566.0> gen_server <0.566.0> terminated with reason: killed
2016-04-10 16:47:15.713 [error] <0.566.0> CRASH REPORT Process <0.566.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:15.713 [error] <0.489.0> CRASH REPORT Process <0.489.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:47:15.864 [error] <0.6648.0> gen_server <0.6648.0> terminated with reason: killed
2016-04-10 16:47:15.864 [error] <0.6648.0> CRASH REPORT Process <0.6648.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:15.864 [error] <0.6544.0> CRASH REPORT Process <0.6544.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:47:15.889 [error] <0.3327.0> gen_server <0.3327.0> terminated with reason: killed
2016-04-10 16:47:15.889 [error] <0.3327.0> CRASH REPORT Process <0.3327.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:15.889 [error] <0.3231.0> CRASH REPORT Process <0.3231.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:47:16.527 [error] <0.3341.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.3343.0> exit with reason killed in context child_terminated
2016-04-10 16:47:16.527 [error] <0.3341.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.3343.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 16:47:16.527 [error] <0.3345.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-10 16:47:16.527 [error] <0.3345.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:16.527 [error] <0.3344.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-10 16:47:16.527 [error] <0.3347.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-10 16:47:16.527 [error] <0.3347.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:16.527 [error] <0.3369.0> gen_server mnesia2_snmp_sup terminated with reason: killed
2016-04-10 16:47:16.527 [error] <0.3369.0> CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:17.726 [error] <0.6778.0> gen_server <0.6778.0> terminated with reason: killed
2016-04-10 16:47:17.711 [error] <0.3513.0> CRASH REPORT Process <0.3513.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:47:17.726 [error] <0.819.0> gen_server <0.819.0> terminated with reason: killed
2016-04-10 16:47:17.726 [error] <0.6778.0> CRASH REPORT Process <0.6778.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:17.726 [error] <0.819.0> CRASH REPORT Process <0.819.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:17.727 [error] <0.6728.0> gen_server <0.6728.0> terminated with reason: killed
2016-04-10 16:47:17.727 [error] <0.764.0> gen_server <0.764.0> terminated with reason: killed
2016-04-10 16:47:17.727 [error] <0.6728.0> CRASH REPORT Process <0.6728.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:17.727 [error] <0.764.0> CRASH REPORT Process <0.764.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:17.728 [error] <0.6657.0> CRASH REPORT Process <0.6657.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:47:17.728 [error] <0.689.0> CRASH REPORT Process <0.689.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:47:18.028 [error] <0.3844.0> gen_server <0.3844.0> terminated with reason: killed
2016-04-10 16:47:18.028 [error] <0.3844.0> CRASH REPORT Process <0.3844.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:18.028 [error] <0.3776.0> CRASH REPORT Process <0.3776.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:47:18.708 [error] <0.3940.0> gen_server <0.3940.0> terminated with reason: killed
2016-04-10 16:47:18.708 [error] <0.3940.0> CRASH REPORT Process <0.3940.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:19.358 [error] <0.7071.0> gen_server <0.7071.0> terminated with reason: killed
2016-04-10 16:47:19.358 [error] <0.7071.0> CRASH REPORT Process <0.7071.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:19.359 [error] <0.3962.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.3969.0> exit with reason killed in context child_terminated
2016-04-10 16:47:19.358 [error] <0.6998.0> CRASH REPORT Process <0.6998.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:47:19.359 [error] <0.3962.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.3969.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 16:47:19.360 [error] <0.3962.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_controller:start() at <0.3971.0> exit with reason killed in context shutdown_error
2016-04-10 16:47:19.362 [error] <0.3958.0> CRASH REPORT Process <0.3958.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:47:19.756 [error] <0.7099.0> CRASH REPORT Process <0.7099.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:47:19.758 [error] <0.839.0> CRASH REPORT Process <0.839.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:47:19.859 [error] emulator Error in process <0.1015.0> on node 'd702824o702832n702832@testing-worker-linux-docker-6a120f93-3374-linux-13' with exit value:
{badarg,[{mnesia2_tm,return_abort,3,[{file,"src/mnesia2_tm.erl"},{line,1092}]},{mnesia2_loader,init_receiver,5,[{file,"src/mnesia2_loader.erl"},{line,289}]},{mnesia2_loader,do_get_network_copy,5,[{file,"src/mnesia2_loader.erl"},{line,226}]},{mnesia2_controller,'-load_table_fun/1-fun-3-',5,[{file,"src/mnesia2_controller.erl"},{line,2177}]},{mnesia2_controller,'-load_and_reply/2-fun-0-',2,[{file,"src/mnesia2_controller.erl"},{line,2139}]}]}

2016-04-10 16:47:19.860 [error] <0.1001.0> gen_server <0.1001.0> terminated with reason: killed
2016-04-10 16:47:19.860 [error] <0.1001.0> CRASH REPORT Process <0.1001.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:19.860 [error] <0.996.0> gen_server <0.996.0> terminated with reason: killed
2016-04-10 16:47:29.920 [error] <0.7301.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at undefined exit with reason killed in context start_error
2016-04-10 16:47:29.920 [error] <0.7307.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-10 16:47:29.920 [error] <0.7307.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:29.920 [error] <0.7304.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-10 16:47:29.920 [error] <0.7327.0> gen_server mnesia2_snmp_sup terminated with reason: killed
2016-04-10 16:47:29.920 [error] <0.7327.0> CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:29.920 [error] <0.7305.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-10 16:47:29.920 [error] <0.7305.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:29.920 [error] <0.7299.0> CRASH REPORT Process <0.7299.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}} in application_master:init/4 line 134
2016-04-10 16:47:29.924 [error] <0.7304.0> CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:30.026 [error] <0.1074.0> gen_server <0.1074.0> terminated with reason: killed
2016-04-10 16:47:30.027 [error] <0.4274.0> gen_server <0.4274.0> terminated with reason: killed
2016-04-10 16:47:30.027 [error] <0.1074.0> CRASH REPORT Process <0.1074.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:30.027 [error] <0.4274.0> CRASH REPORT Process <0.4274.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 16:47:30.028 [error] <0.1021.0> CRASH REPORT Process <0.1021.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 16:47:30.027 [error] <0.4221.0> CRASH REPORT Process <0.4221.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
