2016-04-10 22:50:21.881 [info] <0.7.0> Application lager started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:50:21.881 [info] <0.7.0> Application poolgirl started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:50:21.925 [info] <0.460.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.460.0>
2016-04-10 22:50:21.945 [info] <0.528.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.528.0>
2016-04-10 22:50:22.328 [error] <0.519.0> CRASH REPORT Process <0.519.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:50:22.328 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:22.413 [info] <0.638.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.638.0>
2016-04-10 22:50:22.415 [info] <0.7.0> Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:50:22.896 [error] <0.695.0> gen_server <0.695.0> terminated with reason: killed
2016-04-10 22:50:22.896 [error] <0.695.0> CRASH REPORT Process <0.695.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:50:22.897 [error] <0.629.0> CRASH REPORT Process <0.629.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:50:22.957 [info] <0.765.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.765.0>
2016-04-10 22:50:23.263 [info] <0.7.0> Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:50:23.432 [error] <0.759.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): ** ERROR ** (ignoring core) ** FATAL ** A fallback is installed and Mnesia2 must be restarted. Forcing shutdown after mnesia2_down from 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'...

2016-04-10 22:50:23.432 [error] <0.760.0> Supervisor mnesia2_kernel_sup had child mnesia2_locker started with mnesia2_locker:start() at <0.763.0> exit with reason killed in context child_terminated
2016-04-10 22:50:23.432 [error] <0.760.0> Supervisor mnesia2_kernel_sup had child mnesia2_locker started with mnesia2_locker:start() at <0.763.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:50:23.434 [error] <0.758.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.760.0> exit with reason shutdown in context child_terminated
2016-04-10 22:50:23.434 [error] <0.758.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.760.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:50:22.671 [info] <0.7.0> Application lager started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:50:22.671 [info] <0.7.0> Application poolgirl started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:50:22.722 [info] <0.99.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.99.0>
2016-04-10 22:50:22.960 [info] <0.215.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.215.0>
2016-04-10 22:50:23.429 [warning] <0.6.0> lager_error_logger_h dropped 6 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:50:23.429 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:50:23.496 [info] <0.369.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.369.0>
2016-04-10 22:50:23.500 [info] <0.7.0> Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:50:23.434 [info] <0.7.0> Application mnesia2 exited with reason: shutdown
2016-04-10 22:50:23.475 [info] <0.894.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.894.0>
2016-04-10 22:50:24.017 [error] <0.888.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): ** ERROR ** (ignoring core) ** FATAL ** A fallback is installed and Mnesia2 must be restarted. Forcing shutdown after mnesia2_down from 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'...

2016-04-10 22:50:24.015 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:50:24.051 [info] <0.459.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.459.0>
2016-04-10 22:50:24.058 [info] <0.7.0> Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:50:24.271 [error] <0.517.0> gen_server <0.517.0> terminated with reason: killed
2016-04-10 22:50:24.019 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:50:24.043 [info] <0.994.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.994.0>
2016-04-10 22:50:24.046 [info] <0.7.0> Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:50:24.273 [error] <0.993.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-10 22:50:24.271 [error] <0.517.0> CRASH REPORT Process <0.517.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:50:24.273 [error] <0.993.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:50:24.272 [error] <0.450.0> CRASH REPORT Process <0.450.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:50:24.273 [error] <0.988.0> CRASH REPORT Process mnesia2_event with 0 neighbours exited with reason: killed in gen_event:terminate_server/4 line 320
2016-04-10 22:50:24.273 [error] <0.990.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-10 22:50:24.272 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:24.344 [info] <0.549.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.549.0>
2016-04-10 22:50:24.909 [info] <0.763.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.763.0>
2016-04-10 22:50:24.340 [info] <0.1117.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.1117.0>
2016-04-10 22:50:24.478 [info] <0.1229.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.1229.0>
2016-04-10 22:50:24.908 [info] <0.1461.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.1461.0>
2016-04-10 22:50:25.029 [warning] <0.6.0> lager_error_logger_h dropped 35 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:50:25.029 [error] <0.1452.0> CRASH REPORT Process <0.1452.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:50:25.029 [warning] <0.6.0> lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:50:25.029 [error] <0.754.0> CRASH REPORT Process <0.754.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:50:25.029 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:25.088 [info] <0.864.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.864.0>
2016-04-10 22:50:25.101 [info] <0.7.0> Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:50:25.230 [error] <0.918.0> gen_server <0.918.0> terminated with reason: killed
2016-04-10 22:50:25.029 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:25.078 [info] <0.1574.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.1574.0>
2016-04-10 22:50:25.081 [info] <0.7.0> Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:50:25.230 [error] <0.1630.0> gen_server <0.1630.0> terminated with reason: killed
2016-04-10 22:50:25.230 [error] <0.1630.0> CRASH REPORT Process <0.1630.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:50:25.230 [error] <0.918.0> CRASH REPORT Process <0.918.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:50:25.232 [error] <0.1565.0> CRASH REPORT Process <0.1565.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:50:25.231 [error] <0.855.0> CRASH REPORT Process <0.855.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:50:25.232 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:25.281 [info] <0.1690.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.1690.0>
2016-04-10 22:50:25.551 [info] <0.1816.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.1816.0>
2016-04-10 22:50:25.231 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:25.302 [info] <0.965.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.965.0>
2016-04-10 22:50:25.553 [info] <0.1071.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.1071.0>
2016-04-10 22:50:26.036 [warning] <0.6.0> lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:50:26.050 [info] <0.1171.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.1171.0>
2016-04-10 22:50:26.053 [info] <0.7.0> Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:50:26.205 [error] <0.1166.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.1184.0> exit with reason killed in context child_terminated
2016-04-10 22:50:26.036 [warning] <0.6.0> lager_error_logger_h dropped 10 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:50:26.045 [info] <0.1948.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.1948.0>
2016-04-10 22:50:26.048 [info] <0.7.0> Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:50:26.207 [error] <0.2004.0> gen_server <0.2004.0> terminated with reason: killed
2016-04-10 22:50:26.207 [error] <0.2004.0> CRASH REPORT Process <0.2004.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:50:26.206 [error] <0.1166.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.1184.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:50:26.207 [error] <0.1939.0> CRASH REPORT Process <0.1939.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:50:26.206 [error] <0.1223.0> gen_server <0.1223.0> terminated with reason: killed
2016-04-10 22:50:26.206 [error] <0.1223.0> CRASH REPORT Process <0.1223.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:50:26.206 [error] <0.1162.0> CRASH REPORT Process <0.1162.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:50:26.207 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:26.267 [info] <0.2081.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.2081.0>
2016-04-10 22:50:26.850 [info] <0.2221.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.2221.0>
2016-04-10 22:50:26.206 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:26.280 [info] <0.1272.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.1272.0>
2016-04-10 22:50:26.863 [info] <0.1378.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.1378.0>
2016-04-10 22:50:27.153 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:50:27.156 [info] <0.7.0> Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:50:27.357 [error] <0.2266.0> gen_server <0.2266.0> terminated with reason: killed
2016-04-10 22:50:27.357 [error] <0.2266.0> CRASH REPORT Process <0.2266.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:50:27.355 [warning] <0.6.0> lager_error_logger_h dropped 6 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:50:27.355 [error] <0.1431.0> gen_server <0.1431.0> terminated with reason: killed
2016-04-10 22:50:27.367 [error] <0.2212.0> CRASH REPORT Process <0.2212.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:50:27.355 [error] <0.1431.0> CRASH REPORT Process <0.1431.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:50:27.356 [error] <0.1369.0> CRASH REPORT Process <0.1369.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:50:27.356 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:27.427 [info] <0.1466.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.1466.0>
2016-04-10 22:50:27.431 [info] <0.7.0> Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:50:27.581 [error] <0.1520.0> gen_server <0.1520.0> terminated with reason: killed
2016-04-10 22:50:27.581 [error] <0.1520.0> CRASH REPORT Process <0.1520.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:50:27.367 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:27.402 [info] <0.2353.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.2353.0>
2016-04-10 22:50:28.144 [warning] <0.6.0> lager_error_logger_h dropped 11 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:50:28.152 [info] <0.2485.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.2485.0>
2016-04-10 22:50:28.155 [info] <0.1578.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.1578.0>
2016-04-10 22:50:28.164 [info] <0.7.0> Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:50:28.298 [error] <0.1630.0> gen_server <0.1630.0> terminated with reason: killed
2016-04-10 22:50:28.154 [info] <0.7.0> Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:50:28.299 [error] <0.2539.0> gen_server <0.2539.0> terminated with reason: killed
2016-04-10 22:50:28.298 [error] <0.1630.0> CRASH REPORT Process <0.1630.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:50:28.299 [error] <0.2539.0> CRASH REPORT Process <0.2539.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:50:28.299 [error] <0.1569.0> CRASH REPORT Process <0.1569.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:50:28.299 [error] <0.2476.0> CRASH REPORT Process <0.2476.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:50:28.299 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:28.299 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:28.369 [info] <0.2608.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.2608.0>
2016-04-10 22:50:28.687 [info] <0.2736.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.2736.0>
2016-04-10 22:50:28.858 [info] <0.2830.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.2830.0>
2016-04-10 22:50:28.387 [info] <0.1665.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.1665.0>
2016-04-10 22:50:30.088 [warning] <0.6.0> lager_error_logger_h dropped 34 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:50:30.104 [info] <0.2940.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.2940.0>
2016-04-10 22:50:30.106 [info] <0.7.0> Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:50:31.286 [error] <0.2931.0> CRASH REPORT Process <0.2931.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:50:31.286 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:33.366 [info] <0.3046.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.3046.0>
2016-04-10 22:50:33.368 [info] <0.7.0> Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:50:33.370 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:50:33.371 [info] <0.3094.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.3094.0>
2016-04-10 22:50:33.376 [info] <0.3142.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.3142.0>
2016-04-10 22:50:35.475 [info] <0.3214.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.3214.0>
2016-04-10 22:50:35.478 [info] <0.7.0> Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:50:35.491 [error] <0.3205.0> CRASH REPORT Process <0.3205.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:50:35.491 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:37.543 [info] <0.3297.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.3297.0>
2016-04-10 22:50:37.546 [info] <0.7.0> Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:50:37.551 [info] <0.3291.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Restore aborted. mnesia2_config_backup:open_read["NonExisting.FILE"] -> {enoent,error}

2016-04-10 22:50:37.551 [info] <0.3291.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Restore aborted. mnesia2_config_backup:open_read["/home/travis/build/lrascao/mnesia2/logs/ct_run.test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16.2016-04-10_22.49.57/Mnesia2.test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16/LATEST.LOG"] -> badarg

2016-04-10 22:50:37.553 [error] <0.3325.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}}} ({error,{already_started,<0.3373.0>}})

2016-04-10 22:50:37.553 [error] <0.3327.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}}} ({error,{already_started,<0.3373.0>}})

2016-04-10 22:50:37.553 [error] <0.3326.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}}} ({error,{already_started,<0.3373.0>}})

2016-04-10 22:50:37.553 [error] <0.3324.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}}} ({error,{already_started,<0.3373.0>}})

2016-04-10 22:50:37.553 [error] <0.3329.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}}} ({error,{already_started,<0.3373.0>}})

2016-04-10 22:50:37.553 [error] <0.3331.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}}} ({error,{already_started,<0.3373.0>}})

2016-04-10 22:50:37.553 [error] <0.3330.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}}} ({error,{already_started,<0.3373.0>}})

2016-04-10 22:50:37.553 [error] <0.3333.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_11,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_11,shutdown]}}}} ({error,{already_started,<0.3373.0>}})

2016-04-10 22:50:39.630 [warning] <0.6.0> lager_error_logger_h dropped 15 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:50:39.631 [info] <0.3418.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_monitor starting: <0.3420.0>

2016-04-10 22:50:39.631 [info] <0.3418.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Mnesia2 debug level set to verbose
2016-04-10 22:50:39.632 [info] <0.3418.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_subscr starting: <0.3421.0>

2016-04-10 22:50:39.632 [info] <0.3418.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_locker starting: <0.3422.0>

2016-04-10 22:50:39.632 [info] <0.3418.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_recover starting: <0.3423.0>

2016-04-10 22:50:39.632 [info] <0.3424.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.3424.0>
2016-04-10 22:50:39.632 [info] <0.3418.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_tm starting: <0.3424.0>

2016-04-10 22:50:39.633 [info] <0.3418.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Schema initiated from: default

2016-04-10 22:50:39.633 [info] <0.3418.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_controller starting: <0.3427.0>

2016-04-10 22:50:39.633 [info] <0.3418.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_late_loader starting: <0.3428.0>

2016-04-10 22:50:39.634 [info] <0.3418.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Intend to load tables: []

2016-04-10 22:50:39.634 [info] <0.3418.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_tm_1 starting: <0.3430.0>

2016-04-10 22:50:39.634 [info] <0.3418.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_tm_2 starting: <0.3431.0>

2016-04-10 22:50:39.634 [info] <0.3418.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_tm_3 starting: <0.3432.0>

2016-04-10 22:50:39.635 [info] <0.3418.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_tm_4 starting: <0.3433.0>

2016-04-10 22:50:39.635 [info] <0.3418.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_tm_5 starting: <0.3434.0>

2016-04-10 22:50:39.635 [info] <0.3418.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_tm_6 starting: <0.3435.0>

2016-04-10 22:50:39.635 [info] <0.3418.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_tm_7 starting: <0.3436.0>

2016-04-10 22:50:39.635 [info] <0.3418.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_tm_8 starting: <0.3437.0>

2016-04-10 22:50:39.636 [info] <0.3418.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_tm_9 starting: <0.3438.0>

2016-04-10 22:50:39.636 [info] <0.3418.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_tm_10 starting: <0.3439.0>

2016-04-10 22:50:39.636 [info] <0.3418.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_tm_11 starting: <0.3440.0>

2016-04-10 22:50:39.636 [info] <0.3418.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_tm_12 starting: <0.3441.0>

2016-04-10 22:50:39.636 [info] <0.3418.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_tm_13 starting: <0.3442.0>

2016-04-10 22:50:39.636 [info] <0.3418.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_tm_14 starting: <0.3443.0>

2016-04-10 22:50:41.667 [warning] <0.6.0> lager_error_logger_h dropped 25 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:50:41.667 [info] <0.3492.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_monitor starting: <0.3494.0>

2016-04-10 22:50:41.667 [info] <0.3492.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Version: "1.0.0"

2016-04-10 22:50:41.668 [info] <0.3492.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env access_module: mnesia2

2016-04-10 22:50:41.668 [info] <0.3492.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env auto_repair: true

2016-04-10 22:50:41.668 [info] <0.3492.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env backup_module: mnesia2_backup

2016-04-10 22:50:41.668 [info] <0.3492.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env debug: debug

2016-04-10 22:50:41.668 [info] <0.3492.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16.2016-04-10_22.49.57/Mnesia2.test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16"

2016-04-10 22:50:41.669 [info] <0.3492.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env dump_disc_copies_at_startup: true

2016-04-10 22:50:41.669 [info] <0.3492.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env dump_log_load_regulation: false

2016-04-10 22:50:41.669 [info] <0.3492.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env dump_log_time_threshold: 180000

2016-04-10 22:50:41.669 [info] <0.3492.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env dump_log_update_in_place: true

2016-04-10 22:50:41.669 [info] <0.3492.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env dump_log_write_threshold: 1000

2016-04-10 22:50:41.669 [info] <0.3492.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env event_module: mnesia2_event

2016-04-10 22:50:41.669 [info] <0.3492.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env extra_db_nodes: []

2016-04-10 22:50:41.669 [info] <0.3492.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env ignore_fallback_at_startup: false

2016-04-10 22:50:41.670 [info] <0.3492.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env fallback_error_function: {mnesia2,lkill}

2016-04-10 22:50:41.670 [info] <0.3492.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env max_wait_for_decision: infinity

2016-04-10 22:50:41.670 [info] <0.3492.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env schema_location: opt_disc

2016-04-10 22:50:41.670 [info] <0.3492.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env core_dir: false

2016-04-10 22:50:41.670 [info] <0.3492.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env pid_sort_order: false

2016-04-10 22:50:41.670 [info] <0.3492.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env no_table_loaders: 2

2016-04-10 22:50:41.670 [info] <0.3492.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env dc_dump_limit: 4

2016-04-10 22:50:41.670 [info] <0.3492.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env send_compressed: 0

2016-04-10 22:50:41.671 [info] <0.3492.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env send_max_packets: 20

2016-04-10 22:50:41.671 [info] <0.3498.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.3498.0>
2016-04-10 22:50:41.671 [info] <0.3492.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env send_max_transfer_size: 7500

2016-04-10 22:50:41.671 [info] <0.3492.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env async_dirty_buffer_size: 524288

2016-04-10 22:50:41.671 [info] <0.3492.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env async_dirty_max_buffer_file_size: 100000000

2016-04-10 22:50:41.672 [info] <0.3492.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env async_dirty_tx_backlog_threshold: 200000

2016-04-10 22:50:41.672 [info] <0.3492.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env async_dirty_buffer_min_runtime: 10000

2016-04-10 22:50:41.672 [info] <0.3492.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env async_dirty_buffer_drained_cutoff: 5

2016-04-10 22:50:41.673 [info] <0.3492.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Mnesia2 debug level set to debug
2016-04-10 22:50:41.673 [info] <0.3492.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_subscr starting: <0.3495.0>

2016-04-10 22:50:41.673 [info] <0.3492.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_locker starting: <0.3496.0>

2016-04-10 22:50:41.673 [info] <0.3492.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_recover starting: <0.3497.0>

2016-04-10 22:50:43.698 [warning] <0.6.0> lager_error_logger_h dropped 14 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:50:43.698 [info] <0.3545.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_monitor starting: <0.3547.0>

2016-04-10 22:50:43.699 [info] <0.3545.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Version: "1.0.0"

2016-04-10 22:50:43.699 [info] <0.3545.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env access_module: mnesia2

2016-04-10 22:50:43.700 [info] <0.3545.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env auto_repair: true

2016-04-10 22:50:43.700 [info] <0.3551.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.3551.0>
2016-04-10 22:50:43.700 [info] <0.3545.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env backup_module: mnesia2_backup

2016-04-10 22:50:43.700 [info] <0.3545.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env debug: trace

2016-04-10 22:50:43.701 [info] <0.3545.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16.2016-04-10_22.49.57/Mnesia2.test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16"

2016-04-10 22:50:43.701 [info] <0.3545.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env dump_disc_copies_at_startup: true

2016-04-10 22:50:45.725 [warning] <0.6.0> lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:50:45.725 [info] <0.3595.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_monitor starting: <0.3597.0>

2016-04-10 22:50:45.726 [info] <0.3595.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Version: "1.0.0"

2016-04-10 22:50:45.726 [info] <0.3595.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env access_module: mnesia2

2016-04-10 22:50:45.726 [info] <0.3595.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env auto_repair: true

2016-04-10 22:50:45.726 [info] <0.3595.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env backup_module: mnesia2_backup

2016-04-10 22:50:45.727 [info] <0.3601.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.3601.0>
2016-04-10 22:50:45.727 [info] <0.3595.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env debug: debug

2016-04-10 22:50:45.727 [info] <0.3595.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16.2016-04-10_22.49.57/Mnesia2.test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16"

2016-04-10 22:50:45.728 [info] <0.3595.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env dump_disc_copies_at_startup: true

2016-04-10 22:50:45.728 [info] <0.3595.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env dump_log_load_regulation: false

2016-04-10 22:50:45.728 [info] <0.3595.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env dump_log_time_threshold: 180000

2016-04-10 22:50:45.728 [info] <0.3595.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env dump_log_update_in_place: true

2016-04-10 22:50:45.729 [info] <0.3595.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env dump_log_write_threshold: 1000

2016-04-10 22:50:45.729 [info] <0.3595.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env event_module: mnesia2_event

2016-04-10 22:50:45.729 [info] <0.3595.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env extra_db_nodes: []

2016-04-10 22:50:47.753 [warning] <0.6.0> lager_error_logger_h dropped 13 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:50:47.755 [info] <0.3664.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.3664.0>
2016-04-10 22:50:47.757 [info] <0.7.0> Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:50:47.758 [error] <0.3655.0> CRASH REPORT Process <0.3655.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:50:47.758 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:49.851 [info] <0.3728.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.3728.0>
2016-04-10 22:50:49.853 [info] <0.7.0> Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:50:49.854 [error] <0.3719.0> CRASH REPORT Process <0.3719.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:50:49.854 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:50.941 [info] <0.3799.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.3799.0>
2016-04-10 22:50:50.943 [info] <0.7.0> Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:50:50.949 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:50:50.957 [info] <0.3860.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.3860.0>
2016-04-10 22:50:54.311 [error] <0.3854.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:50:54.674 [error] <0.3854.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:50:55.043 [error] <0.3854.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:50:59.270 [error] <0.3854.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:51:03.317 [error] <0.3854.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:51:03.674 [error] <0.3854.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:51:04.050 [error] <0.3854.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:51:04.415 [error] <0.3854.0> Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:51:06.004 [error] <0.3851.0> CRASH REPORT Process <0.3851.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:51:06.004 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:08.128 [info] <0.4415.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.4415.0>
2016-04-10 22:51:08.131 [info] <0.7.0> Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:51:14.138 [error] <0.4406.0> CRASH REPORT Process <0.4406.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:51:14.138 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:16.225 [info] <0.4515.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.4515.0>
2016-04-10 22:51:16.227 [info] <0.7.0> Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:51:17.511 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:51:20.079 [info] <0.4631.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.4631.0>
2016-04-10 22:51:20.082 [info] <0.7.0> Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:51:20.086 [error] <0.4622.0> CRASH REPORT Process <0.4622.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:51:20.086 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:22.134 [info] <0.4698.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.4698.0>
2016-04-10 22:51:22.137 [info] <0.7.0> Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:51:22.161 [error] <0.4689.0> CRASH REPORT Process <0.4689.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:51:22.161 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:24.273 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:51:24.293 [info] <0.1792.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.1792.0>
2016-04-10 22:51:24.297 [info] <0.7.0> Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:51:24.290 [info] <0.4790.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.4790.0>
2016-04-10 22:51:24.594 [info] <0.7.0> Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:51:25.595 [error] <0.1845.0> gen_server <0.1845.0> terminated with reason: killed
2016-04-10 22:51:25.595 [error] <0.1845.0> CRASH REPORT Process <0.1845.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:51:25.596 [error] <0.1783.0> CRASH REPORT Process <0.1783.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:51:25.596 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:27.639 [info] <0.1861.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.1861.0>
2016-04-10 22:51:27.659 [info] <0.7.0> Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:51:28.661 [error] <0.4854.0> gen_server <0.4854.0> terminated with reason: killed
2016-04-10 22:51:28.661 [error] <0.4854.0> CRASH REPORT Process <0.4854.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:51:28.662 [error] <0.4781.0> CRASH REPORT Process <0.4781.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:51:28.662 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:29.712 [error] <0.1856.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.1874.0> exit with reason killed in context child_terminated
2016-04-10 22:51:29.712 [error] <0.1856.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.1874.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:51:29.713 [error] <0.1852.0> CRASH REPORT Process <0.1852.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:51:29.713 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:30.840 [info] <0.1942.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.1942.0>
2016-04-10 22:51:30.843 [info] <0.7.0> Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:51:30.845 [error] <0.1933.0> CRASH REPORT Process <0.1933.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:51:30.805 [info] <0.4897.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.4897.0>
2016-04-10 22:51:30.807 [info] <0.7.0> Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:51:30.845 [error] <0.4951.0> gen_server <0.4951.0> terminated with reason: killed
2016-04-10 22:51:30.845 [error] <0.4951.0> CRASH REPORT Process <0.4951.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:51:30.846 [error] <0.4888.0> CRASH REPORT Process <0.4888.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:51:30.846 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:30.889 [info] <0.4977.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.4977.0>
2016-04-10 22:51:30.845 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:34.762 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:51:34.827 [info] <0.5101.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.5101.0>
2016-04-10 22:51:34.831 [info] <0.7.0> Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:51:34.818 [info] <0.2012.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.2012.0>
2016-04-10 22:51:34.819 [info] <0.7.0> Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:51:46.200 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:51:46.222 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:51:47.364 [info] <0.2134.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.2134.0>
2016-04-10 22:51:47.368 [info] <0.7.0> Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:51:47.945 [error] <0.2125.0> CRASH REPORT Process <0.2125.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:51:47.346 [info] <0.5232.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.5232.0>
2016-04-10 22:51:47.349 [info] <0.7.0> Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:51:47.979 [error] <0.5223.0> CRASH REPORT Process <0.5223.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:51:47.979 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:48.030 [info] <0.5320.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.5320.0>
2016-04-10 22:51:48.032 [info] <0.7.0> Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:51:47.945 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:48.245 [info] <0.2222.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.2222.0>
2016-04-10 22:51:48.249 [info] <0.7.0> Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:51:48.637 [error] <0.5391.0> gen_server <0.5391.0> terminated with reason: killed
2016-04-10 22:51:48.637 [error] <0.5391.0> CRASH REPORT Process <0.5391.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:51:48.638 [error] <0.5311.0> CRASH REPORT Process <0.5311.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:51:48.638 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:49.908 [error] <0.2217.0> Supervisor mnesia2_kernel_sup had child mnesia2_controller started with mnesia2_controller:start() at <0.2243.0> exit with reason killed in context child_terminated
2016-04-10 22:51:49.908 [error] <0.2217.0> Supervisor mnesia2_kernel_sup had child mnesia2_controller started with mnesia2_controller:start() at <0.2243.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:51:49.908 [error] <0.2213.0> CRASH REPORT Process <0.2213.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:51:49.908 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:50.973 [info] <0.5443.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.5443.0>
2016-04-10 22:51:50.975 [info] <0.7.0> Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:51:50.997 [error] <0.5434.0> CRASH REPORT Process <0.5434.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:51:50.981 [info] <0.2325.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.2325.0>
2016-04-10 22:51:50.986 [info] <0.7.0> Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:51:50.997 [error] <0.2316.0> CRASH REPORT Process <0.2316.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:51:50.997 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:50.997 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:53.094 [info] <0.2400.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.2400.0>
2016-04-10 22:51:53.114 [info] <0.7.0> Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:51:53.116 [error] <0.2412.0> gen_server <0.2412.0> terminated with reason: killed
2016-04-10 22:51:53.088 [info] <0.5554.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.5554.0>
2016-04-10 22:51:53.090 [info] <0.7.0> Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:51:53.117 [error] <0.5616.0> gen_server <0.5616.0> terminated with reason: killed
2016-04-10 22:51:53.117 [error] <0.5616.0> CRASH REPORT Process <0.5616.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:51:53.116 [error] <0.2412.0> CRASH REPORT Process <0.2412.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:51:53.117 [error] <0.5545.0> CRASH REPORT Process <0.5545.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:51:53.116 [error] <0.2391.0> CRASH REPORT Process <0.2391.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:51:53.117 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:53.116 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:55.163 [info] <0.5634.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.5634.0>
2016-04-10 22:51:55.172 [info] <0.7.0> Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:51:55.185 [error] <0.5625.0> CRASH REPORT Process <0.5625.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:51:55.140 [info] <0.2459.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.2459.0>
2016-04-10 22:51:55.142 [info] <0.7.0> Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:51:55.186 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:56.563 [error] <0.2450.0> CRASH REPORT Process <0.2450.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:51:56.563 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:57.673 [info] <0.2546.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.2546.0>
2016-04-10 22:51:57.677 [info] <0.7.0> Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:51:57.968 [error] <0.2559.0> gen_server <0.2559.0> terminated with reason: killed
2016-04-10 22:51:57.668 [info] <0.5759.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.5759.0>
2016-04-10 22:51:57.670 [info] <0.7.0> Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:51:57.970 [error] <0.5750.0> CRASH REPORT Process <0.5750.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:51:57.968 [error] <0.2559.0> CRASH REPORT Process <0.2559.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:51:57.968 [error] <0.2597.0> gen_server <0.2597.0> terminated with reason: killed
2016-04-10 22:51:57.968 [error] <0.2597.0> CRASH REPORT Process <0.2597.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:51:57.969 [error] <0.2537.0> CRASH REPORT Process <0.2537.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:51:57.970 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:57.969 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:57.885 [info] <0.7.0> Application lager started on node 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:51:57.886 [info] <0.7.0> Application poolgirl started on node 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:51:57.910 [info] <0.100.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.100.0>
2016-04-10 22:51:57.927 [info] <0.7.0> Application mnesia2 started on node 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:52:00.092 [info] <0.2628.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.2628.0>
2016-04-10 22:52:00.097 [info] <0.7.0> Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:52:00.100 [error] <0.2619.0> CRASH REPORT Process <0.2619.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:52:00.085 [info] <0.5855.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.5855.0>
2016-04-10 22:52:00.087 [info] <0.7.0> Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:52:00.100 [error] <0.5917.0> gen_server <0.5917.0> terminated with reason: killed
2016-04-10 22:52:00.100 [error] <0.5917.0> CRASH REPORT Process <0.5917.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:52:00.100 [error] <0.5846.0> CRASH REPORT Process <0.5846.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:52:00.100 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:52:00.101 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:52:02.206 [info] <0.2698.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.2698.0>
2016-04-10 22:52:02.210 [info] <0.7.0> Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:52:02.213 [error] <0.2710.0> gen_server <0.2710.0> terminated with reason: killed
2016-04-10 22:52:02.201 [info] <0.5949.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.5949.0>
2016-04-10 22:52:02.203 [info] <0.7.0> Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:52:02.215 [error] <0.5993.0> gen_server <0.5993.0> terminated with reason: killed
2016-04-10 22:52:02.215 [error] <0.5993.0> CRASH REPORT Process <0.5993.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:52:02.214 [error] <0.2710.0> CRASH REPORT Process <0.2710.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:52:02.226 [error] <0.5940.0> CRASH REPORT Process <0.5940.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:52:02.214 [error] <0.2689.0> CRASH REPORT Process <0.2689.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:52:02.226 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:52:02.214 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:52:04.342 [info] <0.2773.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.2773.0>
2016-04-10 22:52:04.348 [info] <0.7.0> Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:52:04.350 [error] <0.2825.0> gen_server <0.2825.0> terminated with reason: killed
2016-04-10 22:52:04.350 [error] <0.2825.0> CRASH REPORT Process <0.2825.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:52:04.350 [error] <0.2764.0> CRASH REPORT Process <0.2764.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:52:04.336 [info] <0.6035.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.6035.0>
2016-04-10 22:52:04.339 [info] <0.7.0> Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:52:04.350 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:52:05.396 [error] <0.6030.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.6047.0> exit with reason killed in context child_terminated
2016-04-10 22:52:05.396 [error] <0.6030.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.6047.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:52:05.397 [error] <0.6026.0> CRASH REPORT Process <0.6026.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:52:05.397 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:52:07.463 [info] <0.2843.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.2843.0>
2016-04-10 22:52:07.465 [info] <0.7.0> Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:52:12.480 [info] <0.6113.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.6113.0>
2016-04-10 22:52:12.489 [info] <0.7.0> Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:52:12.498 [error] <0.6150.0> gen_server <0.6150.0> terminated with reason: killed
2016-04-10 22:52:12.496 [error] <0.2834.0> CRASH REPORT Process <0.2834.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:52:12.498 [error] <0.6150.0> CRASH REPORT Process <0.6150.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:52:12.498 [error] <0.6104.0> CRASH REPORT Process <0.6104.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:52:12.498 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:52:12.496 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:52:13.674 [info] <0.2942.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.2942.0>
2016-04-10 22:52:13.692 [info] <0.7.0> Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:52:13.779 [error] <0.3006.0> gen_server <0.3006.0> terminated with reason: killed
2016-04-10 22:52:13.779 [error] <0.3006.0> CRASH REPORT Process <0.3006.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:52:13.779 [error] <0.2997.0> gen_server <0.2997.0> terminated with reason: killed
2016-04-10 22:52:13.779 [error] <0.2997.0> CRASH REPORT Process <0.2997.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:52:13.779 [error] <0.2933.0> CRASH REPORT Process <0.2933.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:52:13.674 [info] <0.6223.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.6223.0>
2016-04-10 22:52:13.702 [info] <0.7.0> Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:52:13.843 [error] <0.6310.0> gen_server <0.6310.0> terminated with reason: killed
2016-04-10 22:52:13.843 [error] <0.6310.0> CRASH REPORT Process <0.6310.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:52:13.843 [error] <0.6326.0> gen_server <0.6326.0> terminated with reason: killed
2016-04-10 22:52:13.843 [error] <0.6326.0> CRASH REPORT Process <0.6326.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:52:13.843 [error] <0.6287.0> gen_server <0.6287.0> terminated with reason: killed
2016-04-10 22:52:13.843 [error] <0.6287.0> CRASH REPORT Process <0.6287.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:52:13.844 [error] <0.6214.0> CRASH REPORT Process <0.6214.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:52:13.619 [warning] <0.6.0> lager_error_logger_h dropped 9 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:52:13.706 [info] <0.191.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.191.0>
2016-04-10 22:52:13.711 [info] <0.7.0> Application mnesia2 started on node 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:52:13.864 [error] <0.274.0> gen_server <0.274.0> terminated with reason: killed
2016-04-10 22:52:13.864 [error] <0.274.0> CRASH REPORT Process <0.274.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:52:13.951 [info] <0.295.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.295.0>
2016-04-10 22:52:14.254 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:52:14.255 [info] <0.7.0> Application mnesia2 started on node 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:52:13.844 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:52:13.954 [info] <0.6345.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.6345.0>
2016-04-10 22:52:13.779 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:52:13.806 [info] <0.3034.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.3034.0>
2016-04-10 22:52:13.921 [info] <0.3129.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.3129.0>
2016-04-10 22:52:14.761 [error] <0.367.0> gen_server <0.367.0> terminated with reason: killed
2016-04-10 22:52:14.761 [error] <0.367.0> CRASH REPORT Process <0.367.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:52:14.761 [error] <0.360.0> gen_server <0.360.0> terminated with reason: killed
2016-04-10 22:52:14.761 [error] <0.360.0> CRASH REPORT Process <0.360.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:52:14.762 [error] <0.286.0> CRASH REPORT Process <0.286.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:52:14.762 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:52:14.791 [info] <0.394.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.394.0>
2016-04-10 22:52:17.414 [warning] <0.6.0> lager_error_logger_h dropped 12 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:52:17.414 [error] <0.6336.0> CRASH REPORT Process <0.6336.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:52:17.439 [warning] <0.6.0> lager_error_logger_h dropped 12 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:52:17.439 [error] <0.3221.0> gen_server <0.3221.0> terminated with reason: killed
2016-04-10 22:52:17.439 [error] <0.3221.0> CRASH REPORT Process <0.3221.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:52:17.440 [error] <0.3120.0> CRASH REPORT Process <0.3120.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:52:17.464 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:52:17.504 [info] <0.500.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.500.0>
2016-04-10 22:52:17.506 [info] <0.7.0> Application mnesia2 started on node 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:52:18.155 [error] <0.574.0> gen_server <0.574.0> terminated with reason: killed
2016-04-10 22:52:18.155 [error] <0.574.0> CRASH REPORT Process <0.574.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:52:18.155 [error] <0.568.0> gen_server <0.568.0> terminated with reason: killed
2016-04-10 22:52:18.155 [error] <0.568.0> CRASH REPORT Process <0.568.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:52:18.156 [error] <0.491.0> CRASH REPORT Process <0.491.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:52:17.415 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:52:17.524 [info] <0.6462.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.6462.0>
2016-04-10 22:52:17.830 [info] <0.7.0> Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:52:18.228 [error] <0.6556.0> gen_server <0.6556.0> terminated with reason: killed
2016-04-10 22:52:17.440 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:52:17.530 [info] <0.3242.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.3242.0>
2016-04-10 22:52:17.536 [info] <0.7.0> Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:52:18.250 [error] <0.3329.0> gen_server <0.3329.0> terminated with reason: killed
2016-04-10 22:52:18.156 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:52:18.181 [info] <0.599.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.599.0>
2016-04-10 22:52:18.182 [info] <0.7.0> Application mnesia2 started on node 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:52:18.228 [error] <0.6556.0> CRASH REPORT Process <0.6556.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:52:18.250 [error] <0.3329.0> CRASH REPORT Process <0.3329.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:52:18.228 [error] <0.6532.0> gen_server <0.6532.0> terminated with reason: killed
2016-04-10 22:52:18.250 [error] <0.3311.0> gen_server <0.3311.0> terminated with reason: killed
2016-04-10 22:52:18.228 [error] <0.6532.0> CRASH REPORT Process <0.6532.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:52:18.250 [error] <0.3311.0> CRASH REPORT Process <0.3311.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:52:18.250 [error] <0.3233.0> CRASH REPORT Process <0.3233.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:52:18.228 [error] <0.6551.0> gen_server <0.6551.0> terminated with reason: killed
2016-04-10 22:52:18.228 [error] <0.6551.0> CRASH REPORT Process <0.6551.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:52:18.229 [error] <0.6453.0> CRASH REPORT Process <0.6453.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:52:18.251 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:52:18.655 [info] <0.3350.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.3350.0>
2016-04-10 22:52:18.670 [info] <0.7.0> Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:52:19.005 [error] <0.3420.0> gen_server <0.3420.0> terminated with reason: killed
2016-04-10 22:52:19.005 [error] <0.3420.0> CRASH REPORT Process <0.3420.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:52:19.006 [error] <0.3411.0> gen_server <0.3411.0> terminated with reason: killed
2016-04-10 22:52:19.006 [error] <0.3411.0> CRASH REPORT Process <0.3411.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:52:19.006 [error] <0.3341.0> CRASH REPORT Process <0.3341.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:52:19.006 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:52:19.046 [info] <0.3446.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.3446.0>
2016-04-10 22:52:19.085 [info] <0.7.0> Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:52:19.099 [error] <0.3504.0> gen_server <0.3504.0> terminated with reason: killed
2016-04-10 22:52:19.099 [error] <0.3504.0> CRASH REPORT Process <0.3504.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:52:18.520 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:52:18.562 [info] <0.700.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.700.0>
2016-04-10 22:52:18.229 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:52:18.653 [info] <0.6575.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.6575.0>
2016-04-10 22:52:18.959 [info] <0.7.0> Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:52:20.186 [error] <0.6688.0> gen_server <0.6688.0> terminated with reason: killed
2016-04-10 22:52:20.120 [warning] <0.6.0> lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:52:20.122 [info] <0.3524.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.3524.0>
2016-04-10 22:52:20.131 [info] <0.7.0> Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:52:20.189 [error] <0.3572.0> gen_server <0.3572.0> terminated with reason: killed
2016-04-10 22:52:20.188 [warning] <0.6.0> lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:52:20.189 [error] <0.814.0> gen_server <0.814.0> terminated with reason: killed
2016-04-10 22:52:20.186 [error] <0.6688.0> CRASH REPORT Process <0.6688.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:52:20.189 [error] <0.3572.0> CRASH REPORT Process <0.3572.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:52:20.189 [error] <0.814.0> CRASH REPORT Process <0.814.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:52:20.186 [error] <0.6641.0> gen_server <0.6641.0> terminated with reason: killed
2016-04-10 22:52:20.189 [error] <0.3567.0> gen_server <0.3567.0> terminated with reason: killed
2016-04-10 22:52:20.189 [error] <0.774.0> gen_server <0.774.0> terminated with reason: killed
2016-04-10 22:52:20.186 [error] <0.6641.0> CRASH REPORT Process <0.6641.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:52:20.189 [error] <0.3567.0> CRASH REPORT Process <0.3567.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:52:20.189 [error] <0.774.0> CRASH REPORT Process <0.774.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:52:20.187 [error] <0.6566.0> CRASH REPORT Process <0.6566.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:52:20.189 [error] <0.3515.0> CRASH REPORT Process <0.3515.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:52:20.189 [error] <0.823.0> gen_server <0.823.0> terminated with reason: killed
2016-04-10 22:52:20.189 [error] <0.823.0> CRASH REPORT Process <0.823.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:52:20.189 [error] <0.691.0> CRASH REPORT Process <0.691.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:52:20.189 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:52:20.325 [info] <0.3602.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.3602.0>
2016-04-10 22:52:20.404 [info] <0.3699.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.3699.0>
2016-04-10 22:52:20.470 [info] <0.3789.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.3789.0>
2016-04-10 22:52:20.526 [info] <0.3889.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.3889.0>
2016-04-10 22:52:21.097 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:52:21.097 [error] <0.3880.0> CRASH REPORT Process <0.3880.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:52:21.097 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:52:20.187 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:52:20.328 [info] <0.6721.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.6721.0>
2016-04-10 22:52:20.332 [info] <0.7.0> Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:52:20.524 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:52:21.055 [info] <0.6832.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.6832.0>
2016-04-10 22:52:21.070 [info] <0.7.0> Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:52:21.096 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:52:21.136 [info] <0.6915.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.6915.0>
2016-04-10 22:52:20.189 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:52:21.641 [info] <0.3971.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.3971.0>
2016-04-10 22:52:21.667 [info] <0.7.0> Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:52:21.719 [error] <0.4021.0> gen_server <0.4021.0> terminated with reason: killed
2016-04-10 22:52:21.719 [error] <0.4021.0> CRASH REPORT Process <0.4021.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:52:21.719 [error] <0.3962.0> CRASH REPORT Process <0.3962.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:52:21.720 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:52:21.812 [info] <0.4063.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.4063.0>
2016-04-10 22:52:22.180 [error] <0.4054.0> CRASH REPORT Process <0.4054.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:52:21.783 [info] <0.7016.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.7016.0>
2016-04-10 22:52:22.086 [warning] <0.6.0> lager_error_logger_h dropped 7 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:52:22.088 [info] <0.7.0> Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:52:22.181 [error] <0.7007.0> CRASH REPORT Process <0.7007.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:52:21.784 [info] <0.851.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.851.0>
2016-04-10 22:52:22.115 [info] <0.7.0> Application mnesia2 started on node 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:52:22.182 [error] <0.912.0> gen_server <0.912.0> terminated with reason: killed
2016-04-10 22:52:22.182 [error] <0.917.0> gen_server <0.917.0> terminated with reason: killed
2016-04-10 22:52:22.182 [error] <0.912.0> CRASH REPORT Process <0.912.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:52:22.183 [error] <0.917.0> CRASH REPORT Process <0.917.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:52:22.183 [error] <0.842.0> CRASH REPORT Process <0.842.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:52:22.181 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:52:22.222 [info] <0.4154.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.4154.0>
2016-04-10 22:52:22.223 [info] <0.7.0> Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:52:22.255 [error] <0.4208.0> gen_server <0.4208.0> terminated with reason: killed
2016-04-10 22:52:22.255 [error] <0.4208.0> CRASH REPORT Process <0.4208.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:52:22.255 [error] <0.4198.0> gen_server <0.4198.0> terminated with reason: killed
2016-04-10 22:52:22.255 [error] <0.4198.0> CRASH REPORT Process <0.4198.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:52:22.290 [info] <0.4231.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.4231.0>
2016-04-10 22:52:22.181 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:52:22.240 [info] <0.7128.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.7128.0>
2016-04-10 22:52:22.307 [info] <0.7220.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.7220.0>
2016-04-10 22:52:22.183 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:52:22.220 [info] <0.958.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.958.0>
2016-04-10 22:52:22.289 [info] <0.1036.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.1036.0>
2016-04-10 22:52:32.314 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:52:32.314 [error] <0.7213.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at undefined exit with reason killed in context start_error
2016-04-10 22:52:32.314 [error] <0.7216.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-10 22:52:32.314 [error] <0.7219.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-10 22:52:32.314 [error] <0.7219.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:52:32.314 [error] <0.7239.0> gen_server mnesia2_snmp_sup terminated with reason: killed
2016-04-10 22:52:32.314 [error] <0.7239.0> CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:52:32.314 [error] <0.7211.0> CRASH REPORT Process <0.7211.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}} in application_master:init/4 line 133
2016-04-10 22:52:32.315 [info] <0.7.0> Application mnesia2 exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}}
2016-04-10 22:52:32.315 [error] <0.7217.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-10 22:52:32.315 [error] <0.7217.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:52:32.316 [error] <0.7216.0> CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:52:32.410 [error] <0.4275.0> gen_server <0.4275.0> terminated with reason: killed
2016-04-10 22:52:32.410 [warning] <0.6.0> lager_error_logger_h dropped 5 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:52:32.410 [error] <0.1085.0> gen_server <0.1085.0> terminated with reason: killed
2016-04-10 22:52:32.410 [error] <0.4275.0> CRASH REPORT Process <0.4275.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:52:32.410 [error] <0.1085.0> CRASH REPORT Process <0.1085.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:52:32.410 [error] <0.4222.0> CRASH REPORT Process <0.4222.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:52:32.410 [error] <0.1080.0> gen_server <0.1080.0> terminated with reason: killed
2016-04-10 22:52:32.410 [error] <0.1080.0> CRASH REPORT Process <0.1080.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-10 22:52:32.410 [error] <0.1027.0> CRASH REPORT Process <0.1027.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-10 22:52:32.410 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:52:32.410 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:52:34.798 [info] <0.7331.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.7331.0>
2016-04-10 22:52:34.800 [info] <0.7.0> Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:52:38.682 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:52:38.829 [info] <0.7467.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.7467.0>
2016-04-10 22:52:39.133 [info] <0.7.0> Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:52:38.833 [info] <0.1134.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.1134.0>
2016-04-10 22:52:38.858 [info] <0.7.0> Application mnesia2 started on node 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:52:38.834 [info] <0.4322.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.4322.0>
2016-04-10 22:52:38.857 [info] <0.7.0> Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:52:45.227 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:52:45.375 [info] <0.4438.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.4438.0>
2016-04-10 22:52:45.380 [info] <0.7.0> Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:52:45.229 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:52:45.357 [info] <0.1248.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.1248.0>
2016-04-10 22:52:45.685 [info] <0.7.0> Application mnesia2 started on node 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:52:45.237 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:52:45.354 [info] <0.7597.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.7597.0>
2016-04-10 22:52:45.658 [info] <0.7.0> Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:52:51.778 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:52:51.907 [info] <0.4551.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.4551.0>
2016-04-10 22:52:52.211 [info] <0.7.0> Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:52:51.779 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:52:51.908 [info] <0.1366.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.1366.0>
2016-04-10 22:52:51.915 [info] <0.7.0> Application mnesia2 started on node 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:52:51.782 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:52:51.901 [info] <0.7728.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.7728.0>
2016-04-10 22:52:51.903 [info] <0.7.0> Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:53:08.113 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:53:08.260 [info] <0.5677.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.5677.0>
2016-04-10 22:53:08.272 [info] <0.7.0> Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:53:08.133 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:53:08.245 [info] <0.8866.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.8866.0>
2016-04-10 22:53:08.557 [info] <0.7.0> Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:53:08.135 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:53:08.267 [info] <0.2491.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.2491.0>
2016-04-10 22:53:08.270 [info] <0.7.0> Application mnesia2 started on node 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:53:14.929 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:53:15.073 [info] <0.9006.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.9006.0>
2016-04-10 22:53:15.076 [info] <0.7.0> Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:53:14.930 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:53:15.086 [info] <0.2614.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.2614.0>
2016-04-10 22:53:15.095 [info] <0.7.0> Application mnesia2 started on node 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:53:14.948 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:53:15.085 [info] <0.5804.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.5804.0>
2016-04-10 22:53:15.091 [info] <0.7.0> Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:53:21.394 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:53:21.494 [info] <0.10486.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.10486.0>
2016-04-10 22:53:21.800 [info] <0.7.0> Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:53:21.400 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:53:21.519 [info] <0.7273.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.7273.0>
2016-04-10 22:53:21.528 [info] <0.7.0> Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:53:21.395 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:53:21.497 [info] <0.4084.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.4084.0>
2016-04-10 22:53:21.563 [info] <0.7.0> Application mnesia2 started on node 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:53:28.027 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:53:28.188 [info] <0.12279.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.12279.0>
2016-04-10 22:53:28.493 [info] <0.7.0> Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:53:28.031 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:53:28.200 [info] <0.5413.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.5413.0>
2016-04-10 22:53:28.219 [info] <0.7.0> Application mnesia2 started on node 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:53:28.074 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:53:28.204 [info] <0.7624.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.7624.0>
2016-04-10 22:53:28.208 [info] <0.7.0> Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:53:34.644 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:53:34.811 [info] <0.7736.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.7736.0>
2016-04-10 22:53:34.816 [info] <0.7.0> Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:53:34.649 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:53:34.807 [info] <0.12410.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.12410.0>
2016-04-10 22:53:35.112 [info] <0.7.0> Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:53:34.677 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:53:34.811 [info] <0.6209.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.6209.0>
2016-04-10 22:53:34.819 [info] <0.7.0> Application mnesia2 started on node 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16'
2016-04-10 22:53:41.406 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:53:41.357 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:53:41.358 [info] <0.7.0> Application mnesia2 exited with reason: stopped
