2016-04-10 22:39:32.896 [info] <0.7.0> Application lager started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:39:32.896 [info] <0.7.0> Application poolgirl started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:39:32.923 [info] <0.494.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.494.0>
2016-04-10 22:39:32.941 [info] <0.562.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.562.0>
2016-04-10 22:39:33.337 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:39:33.337 [error] <0.553.0> CRASH REPORT Process <0.553.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:33.337 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:33.443 [info] <0.672.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.672.0>
2016-04-10 22:39:33.446 [info] <0.7.0> Application mnesia2 started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:39:33.916 [error] <0.729.0> gen_server <0.729.0> terminated with reason: killed
2016-04-10 22:39:33.917 [error] <0.729.0> CRASH REPORT Process <0.729.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:39:33.928 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:34.009 [info] <0.798.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.798.0>
2016-04-10 22:39:34.009 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:39:34.012 [info] <0.7.0> Application mnesia2 started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:39:34.277 [error] <0.792.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): ** ERROR ** (ignoring core) ** FATAL ** A fallback is installed and Mnesia2 must be restarted. Forcing shutdown after mnesia2_down from 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16'...

2016-04-10 22:39:34.277 [error] <0.793.0> Supervisor mnesia2_kernel_sup had child mnesia2_locker started with mnesia2_locker:start() at <0.796.0> exit with reason killed in context child_terminated
2016-04-10 22:39:34.277 [error] <0.793.0> Supervisor mnesia2_kernel_sup had child mnesia2_locker started with mnesia2_locker:start() at <0.796.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:39:34.280 [error] <0.791.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.793.0> exit with reason shutdown in context child_terminated
2016-04-10 22:39:34.280 [error] <0.791.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.793.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:39:33.656 [info] <0.7.0> Application lager started on node 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:39:33.657 [info] <0.7.0> Application poolgirl started on node 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:39:33.708 [info] <0.99.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.99.0>
2016-04-10 22:39:34.017 [info] <0.215.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.215.0>
2016-04-10 22:39:34.017 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:39:34.045 [info] <0.7.0> Application mnesia2 started on node 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:39:34.278 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:39:34.315 [info] <0.368.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.368.0>
2016-04-10 22:39:34.396 [info] <0.458.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.458.0>
2016-04-10 22:39:34.281 [info] <0.7.0> Application mnesia2 exited with reason: shutdown
2016-04-10 22:39:34.306 [info] <0.926.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.926.0>
2016-04-10 22:39:34.380 [info] <0.1026.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.1026.0>
2016-04-10 22:39:35.125 [warning] <0.6.0> lager_error_logger_h dropped 14 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:39:35.125 [error] <0.516.0> gen_server <0.516.0> terminated with reason: killed
2016-04-10 22:39:35.126 [warning] <0.6.0> lager_error_logger_h dropped 5 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:39:35.127 [error] <0.1087.0> gen_server <0.1087.0> terminated with reason: killed
2016-04-10 22:39:35.127 [error] <0.1087.0> CRASH REPORT Process <0.1087.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:39:35.125 [error] <0.516.0> CRASH REPORT Process <0.516.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:39:35.127 [error] <0.1017.0> CRASH REPORT Process <0.1017.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:35.125 [error] <0.449.0> CRASH REPORT Process <0.449.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:35.125 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:35.228 [info] <0.547.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.547.0>
2016-04-10 22:39:35.235 [info] <0.7.0> Application mnesia2 started on node 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:39:35.127 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:35.208 [info] <0.1149.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.1149.0>
2016-04-10 22:39:35.210 [info] <0.7.0> Application mnesia2 started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:39:35.775 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:39:35.800 [info] <0.1261.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.1261.0>
2016-04-10 22:39:36.328 [error] <0.662.0> gen_server <0.662.0> terminated with reason: killed
2016-04-10 22:39:36.331 [error] <0.1252.0> CRASH REPORT Process <0.1252.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:36.328 [error] <0.662.0> CRASH REPORT Process <0.662.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:39:36.329 [error] <0.538.0> CRASH REPORT Process <0.538.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:36.331 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:36.410 [info] <0.1493.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.1493.0>
2016-04-10 22:39:36.412 [info] <0.7.0> Application mnesia2 started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:39:36.546 [error] <0.1484.0> CRASH REPORT Process <0.1484.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:36.329 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:36.415 [info] <0.761.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.761.0>
2016-04-10 22:39:36.426 [info] <0.7.0> Application mnesia2 started on node 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:39:36.547 [error] <0.815.0> gen_server <0.815.0> terminated with reason: killed
2016-04-10 22:39:36.547 [error] <0.815.0> CRASH REPORT Process <0.815.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:39:36.548 [error] <0.752.0> CRASH REPORT Process <0.752.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:36.548 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:37.163 [info] <0.861.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.861.0>
2016-04-10 22:39:37.184 [info] <0.7.0> Application mnesia2 started on node 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:39:36.546 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:37.134 [info] <0.1607.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.1607.0>
2016-04-10 22:39:37.137 [info] <0.7.0> Application mnesia2 started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:39:37.506 [error] <0.1663.0> gen_server <0.1663.0> terminated with reason: killed
2016-04-10 22:39:37.505 [error] <0.855.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.873.0> exit with reason killed in context child_terminated
2016-04-10 22:39:37.506 [error] <0.1663.0> CRASH REPORT Process <0.1663.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:39:37.505 [error] <0.855.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.873.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:39:37.508 [error] <0.1598.0> CRASH REPORT Process <0.1598.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:37.506 [error] <0.858.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-10 22:39:37.506 [error] <0.858.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:39:37.506 [error] <0.856.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-10 22:39:37.506 [error] <0.856.0> CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:39:37.636 [info] <0.961.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.961.0>
2016-04-10 22:39:37.960 [info] <0.1067.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.1067.0>
2016-04-10 22:39:37.508 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:37.630 [info] <0.1723.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.1723.0>
2016-04-10 22:39:37.941 [info] <0.1849.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.1849.0>
2016-04-10 22:39:38.245 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:39:38.245 [info] <0.7.0> Application mnesia2 started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:39:39.466 [error] <0.1906.0> gen_server <0.1906.0> terminated with reason: killed
2016-04-10 22:39:39.467 [warning] <0.6.0> lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:39:39.467 [error] <0.1122.0> gen_server <0.1122.0> terminated with reason: killed
2016-04-10 22:39:39.467 [error] <0.1122.0> CRASH REPORT Process <0.1122.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:39:39.466 [error] <0.1906.0> CRASH REPORT Process <0.1906.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:39:39.468 [error] <0.1058.0> CRASH REPORT Process <0.1058.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:39.467 [error] <0.1840.0> CRASH REPORT Process <0.1840.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:39.467 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:39.558 [info] <0.1981.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.1981.0>
2016-04-10 22:39:39.560 [info] <0.7.0> Application mnesia2 started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:39:39.468 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:39.576 [info] <0.1167.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.1167.0>
2016-04-10 22:39:39.590 [info] <0.7.0> Application mnesia2 started on node 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:39:40.967 [error] <0.1972.0> CRASH REPORT Process <0.1972.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:40.967 [error] <0.1221.0> gen_server <0.1221.0> terminated with reason: killed
2016-04-10 22:39:40.967 [error] <0.1221.0> CRASH REPORT Process <0.1221.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:39:40.967 [error] <0.1158.0> CRASH REPORT Process <0.1158.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:40.967 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:41.023 [info] <0.1268.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.1268.0>
2016-04-10 22:39:41.026 [info] <0.7.0> Application mnesia2 started on node 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:39:41.269 [error] <0.1322.0> gen_server <0.1322.0> terminated with reason: killed
2016-04-10 22:39:40.967 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:41.017 [info] <0.2114.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.2114.0>
2016-04-10 22:39:41.020 [info] <0.7.0> Application mnesia2 started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:39:41.272 [error] <0.2170.0> gen_server <0.2170.0> terminated with reason: killed
2016-04-10 22:39:41.269 [error] <0.1322.0> CRASH REPORT Process <0.1322.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:39:41.272 [error] <0.2170.0> CRASH REPORT Process <0.2170.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:39:41.270 [error] <0.1259.0> CRASH REPORT Process <0.1259.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:41.272 [error] <0.2105.0> CRASH REPORT Process <0.2105.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:41.270 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:41.352 [info] <0.1374.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.1374.0>
2016-04-10 22:39:41.355 [info] <0.7.0> Application mnesia2 started on node 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:39:41.558 [error] <0.1369.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.1387.0> exit with reason killed in context child_terminated
2016-04-10 22:39:41.558 [error] <0.1369.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.1387.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:39:41.559 [error] <0.1428.0> gen_server <0.1428.0> terminated with reason: killed
2016-04-10 22:39:41.559 [error] <0.1428.0> CRASH REPORT Process <0.1428.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:39:41.559 [error] <0.1365.0> CRASH REPORT Process <0.1365.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:41.559 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:41.624 [info] <0.1461.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.1461.0>
2016-04-10 22:39:41.875 [info] <0.1573.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.1573.0>
2016-04-10 22:39:41.272 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:41.335 [info] <0.2254.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.2254.0>
2016-04-10 22:39:41.620 [info] <0.2385.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.2385.0>
2016-04-10 22:39:41.842 [info] <0.2517.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.2517.0>
2016-04-10 22:39:42.006 [warning] <0.6.0> lager_error_logger_h dropped 33 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:39:42.006 [error] <0.1627.0> gen_server <0.1627.0> terminated with reason: killed
2016-04-10 22:39:42.008 [warning] <0.6.0> lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:39:42.008 [error] <0.2573.0> gen_server <0.2573.0> terminated with reason: killed
2016-04-10 22:39:42.008 [error] <0.2573.0> CRASH REPORT Process <0.2573.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:39:42.006 [error] <0.1627.0> CRASH REPORT Process <0.1627.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:39:42.008 [error] <0.2508.0> CRASH REPORT Process <0.2508.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:42.007 [error] <0.1564.0> CRASH REPORT Process <0.1564.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:42.007 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:42.076 [info] <0.1660.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.1660.0>
2016-04-10 22:39:42.091 [info] <0.7.0> Application mnesia2 started on node 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:39:42.143 [error] <0.1712.0> gen_server <0.1712.0> terminated with reason: killed
2016-04-10 22:39:42.143 [error] <0.1712.0> CRASH REPORT Process <0.1712.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:39:42.008 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:42.072 [info] <0.2640.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.2640.0>
2016-04-10 22:39:42.075 [info] <0.7.0> Application mnesia2 started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:39:42.355 [error] <0.2631.0> CRASH REPORT Process <0.2631.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:42.356 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:42.391 [info] <0.2768.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.2768.0>
2016-04-10 22:39:42.472 [info] <0.2862.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.2862.0>
2016-04-10 22:39:43.714 [warning] <0.6.0> lager_error_logger_h dropped 35 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:39:43.720 [info] <0.2972.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.2972.0>
2016-04-10 22:39:43.722 [info] <0.7.0> Application mnesia2 started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:39:44.935 [error] <0.2963.0> CRASH REPORT Process <0.2963.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:44.935 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:47.022 [info] <0.3078.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.3078.0>
2016-04-10 22:39:47.024 [info] <0.7.0> Application mnesia2 started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:39:47.025 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:39:47.027 [info] <0.3126.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.3126.0>
2016-04-10 22:39:47.031 [info] <0.3174.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.3174.0>
2016-04-10 22:39:49.121 [info] <0.3246.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.3246.0>
2016-04-10 22:39:49.123 [info] <0.7.0> Application mnesia2 started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:39:49.145 [error] <0.3237.0> CRASH REPORT Process <0.3237.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:49.145 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:39:51.180 [info] <0.3329.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.3329.0>
2016-04-10 22:39:51.183 [info] <0.7.0> Application mnesia2 started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:39:51.187 [info] <0.3323.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Restore aborted. mnesia2_config_backup:open_read["NonExisting.FILE"] -> {enoent,error}

2016-04-10 22:39:51.188 [info] <0.3323.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Restore aborted. mnesia2_config_backup:open_read["/home/travis/build/lrascao/mnesia2/logs/ct_run.test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16.2016-04-10_22.38.54/Mnesia2.test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16/LATEST.LOG"] -> badarg

2016-04-10 22:39:51.189 [error] <0.3357.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}}} ({error,{already_started,<0.3405.0>}})

2016-04-10 22:39:51.189 [error] <0.3359.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}}} ({error,{already_started,<0.3405.0>}})

2016-04-10 22:39:51.190 [error] <0.3358.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}}} ({error,{already_started,<0.3405.0>}})

2016-04-10 22:39:51.190 [error] <0.3356.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}}} ({error,{already_started,<0.3405.0>}})

2016-04-10 22:39:51.190 [error] <0.3363.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}}} ({error,{already_started,<0.3405.0>}})

2016-04-10 22:39:51.190 [error] <0.3365.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}}} ({error,{already_started,<0.3405.0>}})

2016-04-10 22:39:51.190 [error] <0.3364.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}}} ({error,{already_started,<0.3405.0>}})

2016-04-10 22:39:51.190 [error] <0.3367.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_11,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_11,shutdown]}}}} ({error,{already_started,<0.3405.0>}})

2016-04-10 22:39:53.268 [warning] <0.6.0> lager_error_logger_h dropped 23 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:39:53.269 [info] <0.3455.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): mnesia2_monitor starting: <0.3457.0>

2016-04-10 22:39:53.270 [info] <0.3455.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Mnesia2 debug level set to verbose
2016-04-10 22:39:53.270 [info] <0.3455.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): mnesia2_subscr starting: <0.3458.0>

2016-04-10 22:39:53.270 [info] <0.3455.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): mnesia2_locker starting: <0.3459.0>

2016-04-10 22:39:53.270 [info] <0.3455.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): mnesia2_recover starting: <0.3460.0>

2016-04-10 22:39:53.271 [info] <0.3455.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): mnesia2_tm starting: <0.3461.0>

2016-04-10 22:39:53.271 [info] <0.3455.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Schema initiated from: default

2016-04-10 22:39:53.271 [info] <0.3461.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.3461.0>
2016-04-10 22:39:53.272 [info] <0.3455.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): mnesia2_controller starting: <0.3464.0>

2016-04-10 22:39:53.272 [info] <0.3455.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): mnesia2_late_loader starting: <0.3465.0>

2016-04-10 22:39:53.273 [info] <0.3455.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Intend to load tables: []

2016-04-10 22:39:53.273 [info] <0.3455.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): mnesia2_tm_1 starting: <0.3467.0>

2016-04-10 22:39:53.273 [info] <0.3455.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): mnesia2_tm_2 starting: <0.3468.0>

2016-04-10 22:39:53.273 [info] <0.3455.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): mnesia2_tm_3 starting: <0.3469.0>

2016-04-10 22:39:53.274 [info] <0.3455.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): mnesia2_tm_4 starting: <0.3470.0>

2016-04-10 22:39:53.274 [info] <0.3455.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): mnesia2_tm_5 starting: <0.3471.0>

2016-04-10 22:39:53.274 [info] <0.3455.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): mnesia2_tm_6 starting: <0.3472.0>

2016-04-10 22:39:53.274 [info] <0.3455.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): mnesia2_tm_7 starting: <0.3473.0>

2016-04-10 22:39:53.275 [info] <0.3455.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): mnesia2_tm_8 starting: <0.3474.0>

2016-04-10 22:39:55.299 [warning] <0.6.0> lager_error_logger_h dropped 33 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:39:55.299 [info] <0.3536.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): mnesia2_monitor starting: <0.3538.0>

2016-04-10 22:39:55.300 [info] <0.3536.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Version: "1.0.0"

2016-04-10 22:39:55.300 [info] <0.3536.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env access_module: mnesia2

2016-04-10 22:39:55.300 [info] <0.3536.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env auto_repair: true

2016-04-10 22:39:55.300 [info] <0.3536.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env backup_module: mnesia2_backup

2016-04-10 22:39:55.300 [info] <0.3536.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env debug: debug

2016-04-10 22:39:55.300 [info] <0.3536.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16.2016-04-10_22.38.54/Mnesia2.test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16"

2016-04-10 22:39:55.301 [info] <0.3536.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env dump_disc_copies_at_startup: true

2016-04-10 22:39:55.301 [info] <0.3536.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env dump_log_load_regulation: false

2016-04-10 22:39:55.301 [info] <0.3536.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env dump_log_time_threshold: 180000

2016-04-10 22:39:55.301 [info] <0.3536.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env dump_log_update_in_place: true

2016-04-10 22:39:55.301 [info] <0.3536.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env dump_log_write_threshold: 1000

2016-04-10 22:39:55.301 [info] <0.3536.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env event_module: mnesia2_event

2016-04-10 22:39:55.301 [info] <0.3536.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env extra_db_nodes: []

2016-04-10 22:39:55.301 [info] <0.3536.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env ignore_fallback_at_startup: false

2016-04-10 22:39:55.301 [info] <0.3536.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env fallback_error_function: {mnesia2,lkill}

2016-04-10 22:39:55.301 [info] <0.3536.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env max_wait_for_decision: infinity

2016-04-10 22:39:55.302 [info] <0.3536.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env schema_location: opt_disc

2016-04-10 22:39:55.302 [info] <0.3536.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env core_dir: false

2016-04-10 22:39:55.302 [info] <0.3536.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env pid_sort_order: false

2016-04-10 22:39:55.302 [info] <0.3536.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env no_table_loaders: 2

2016-04-10 22:39:55.303 [info] <0.3536.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env dc_dump_limit: 4

2016-04-10 22:39:55.303 [info] <0.3542.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.3542.0>
2016-04-10 22:39:55.303 [info] <0.3536.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env send_compressed: 0

2016-04-10 22:39:55.303 [info] <0.3536.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env send_max_packets: 20

2016-04-10 22:39:55.303 [info] <0.3536.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env send_max_transfer_size: 7500

2016-04-10 22:39:55.303 [info] <0.3536.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env async_dirty_buffer_size: 524288

2016-04-10 22:39:55.304 [info] <0.3536.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env async_dirty_max_buffer_file_size: 100000000

2016-04-10 22:39:55.304 [info] <0.3536.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env async_dirty_tx_backlog_threshold: 200000

2016-04-10 22:39:55.304 [info] <0.3536.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env async_dirty_buffer_min_runtime: 10000

2016-04-10 22:39:55.304 [info] <0.3536.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env async_dirty_buffer_drained_cutoff: 5

2016-04-10 22:39:55.305 [info] <0.3536.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Mnesia2 debug level set to debug
2016-04-10 22:39:55.305 [info] <0.3536.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): mnesia2_subscr starting: <0.3539.0>

2016-04-10 22:39:55.305 [info] <0.3536.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): mnesia2_locker starting: <0.3540.0>

2016-04-10 22:39:57.330 [warning] <0.6.0> lager_error_logger_h dropped 42 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:39:57.330 [info] <0.3616.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): mnesia2_monitor starting: <0.3618.0>

2016-04-10 22:39:57.331 [info] <0.3616.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Version: "1.0.0"

2016-04-10 22:39:57.331 [info] <0.3616.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env access_module: mnesia2

2016-04-10 22:39:57.331 [info] <0.3616.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env auto_repair: true

2016-04-10 22:39:57.331 [info] <0.3616.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env backup_module: mnesia2_backup

2016-04-10 22:39:57.332 [info] <0.3616.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env debug: trace

2016-04-10 22:39:57.332 [info] <0.3616.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16.2016-04-10_22.38.54/Mnesia2.test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16"

2016-04-10 22:39:57.332 [info] <0.3616.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env dump_disc_copies_at_startup: true

2016-04-10 22:39:57.332 [info] <0.3622.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.3622.0>
2016-04-10 22:39:57.333 [info] <0.3616.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env dump_log_load_regulation: false

2016-04-10 22:39:57.333 [info] <0.3616.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env dump_log_time_threshold: 180000

2016-04-10 22:39:57.333 [info] <0.3616.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env dump_log_update_in_place: true

2016-04-10 22:39:57.333 [info] <0.3616.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env dump_log_write_threshold: 1000

2016-04-10 22:39:57.334 [info] <0.3616.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env event_module: mnesia2_event

2016-04-10 22:39:57.334 [info] <0.3616.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env extra_db_nodes: []

2016-04-10 22:39:57.334 [info] <0.3616.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env ignore_fallback_at_startup: false

2016-04-10 22:39:57.335 [info] <0.3616.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env fallback_error_function: {mnesia2,lkill}

2016-04-10 22:39:59.358 [warning] <0.6.0> lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:39:59.358 [info] <0.3668.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): mnesia2_monitor starting: <0.3670.0>

2016-04-10 22:39:59.359 [info] <0.3668.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Version: "1.0.0"

2016-04-10 22:39:59.359 [info] <0.3668.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env access_module: mnesia2

2016-04-10 22:39:59.360 [info] <0.3668.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env auto_repair: true

2016-04-10 22:39:59.360 [info] <0.3668.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env backup_module: mnesia2_backup

2016-04-10 22:39:59.361 [info] <0.3668.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env debug: debug

2016-04-10 22:39:59.361 [info] <0.3668.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16.2016-04-10_22.38.54/Mnesia2.test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16"

2016-04-10 22:39:59.361 [info] <0.3668.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env dump_disc_copies_at_startup: true

2016-04-10 22:39:59.362 [info] <0.3668.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env dump_log_load_regulation: false

2016-04-10 22:39:59.362 [info] <0.3668.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env dump_log_time_threshold: 180000

2016-04-10 22:39:59.362 [info] <0.3668.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env dump_log_update_in_place: true

2016-04-10 22:39:59.363 [info] <0.3674.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.3674.0>
2016-04-10 22:39:59.364 [info] <0.3668.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env dump_log_write_threshold: 1000

2016-04-10 22:39:59.364 [info] <0.3668.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env event_module: mnesia2_event

2016-04-10 22:39:59.364 [info] <0.3668.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env extra_db_nodes: []

2016-04-10 22:39:59.365 [info] <0.3668.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env ignore_fallback_at_startup: false

2016-04-10 22:39:59.365 [info] <0.3668.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env fallback_error_function: {mnesia2,lkill}

2016-04-10 22:39:59.366 [info] <0.3668.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env max_wait_for_decision: infinity

2016-04-10 22:39:59.366 [info] <0.3668.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): Env schema_location: opt_disc

2016-04-10 22:40:01.390 [warning] <0.6.0> lager_error_logger_h dropped 28 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:40:01.392 [info] <0.3732.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.3732.0>
2016-04-10 22:40:01.394 [info] <0.7.0> Application mnesia2 started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:40:01.395 [error] <0.3723.0> CRASH REPORT Process <0.3723.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:01.395 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:40:03.487 [info] <0.3796.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.3796.0>
2016-04-10 22:40:03.489 [info] <0.7.0> Application mnesia2 started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:40:03.490 [error] <0.3787.0> CRASH REPORT Process <0.3787.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:03.490 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:40:07.140 [info] <0.3867.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.3867.0>
2016-04-10 22:40:07.142 [info] <0.7.0> Application mnesia2 started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:40:07.171 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:40:07.188 [info] <0.3928.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.3928.0>
2016-04-10 22:40:09.189 [error] <0.3922.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:40:09.960 [error] <0.3922.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:40:10.338 [error] <0.3922.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:40:10.718 [error] <0.3922.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:40:11.099 [error] <0.3922.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:40:11.478 [error] <0.3922.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:40:11.857 [error] <0.3922.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:40:12.229 [error] <0.3922.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:40:12.619 [error] <0.3922.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:40:13.001 [error] <0.3922.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:40:13.020 [error] <0.3922.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:40:13.398 [error] <0.3922.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:40:13.774 [error] <0.3922.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:40:14.146 [error] <0.3922.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:40:14.532 [error] <0.3922.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:40:14.913 [error] <0.3922.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:40:15.292 [error] <0.3922.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:40:15.661 [error] <0.3922.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:40:16.425 [error] <0.3922.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:40:16.800 [error] <0.3922.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:40:17.182 [error] <0.3922.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:40:17.567 [error] <0.3922.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:40:17.752 [error] <0.3922.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:40:18.132 [error] <0.3922.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:40:18.509 [error] <0.3922.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:40:18.655 [error] <0.3922.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:40:19.038 [error] <0.3922.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:40:19.417 [error] <0.3922.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:40:20.182 [error] <0.3922.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:40:20.556 [error] <0.3922.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:40:21.046 [error] <0.3922.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:40:21.426 [error] <0.3922.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:40:22.244 [error] <0.3922.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:40:22.672 [error] <0.3919.0> CRASH REPORT Process <0.3919.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:22.672 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:40:24.795 [info] <0.4183.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.4183.0>
2016-04-10 22:40:24.797 [info] <0.7.0> Application mnesia2 started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:40:30.805 [error] <0.4174.0> CRASH REPORT Process <0.4174.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:30.805 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:40:41.209 [info] <0.4283.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.4283.0>
2016-04-10 22:40:41.212 [info] <0.7.0> Application mnesia2 started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:40:42.246 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:40:44.350 [info] <0.4399.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.4399.0>
2016-04-10 22:40:44.353 [info] <0.7.0> Application mnesia2 started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:40:44.357 [error] <0.4390.0> CRASH REPORT Process <0.4390.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:44.357 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:40:53.391 [info] <0.4466.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.4466.0>
2016-04-10 22:40:53.394 [info] <0.7.0> Application mnesia2 started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:40:53.418 [error] <0.4457.0> CRASH REPORT Process <0.4457.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:53.418 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:40:55.548 [info] <0.4558.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.4558.0>
2016-04-10 22:40:55.551 [info] <0.7.0> Application mnesia2 started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:40:55.561 [info] <0.1787.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.1787.0>
2016-04-10 22:40:55.593 [info] <0.7.0> Application mnesia2 started on node 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:40:56.595 [error] <0.1839.0> gen_server <0.1839.0> terminated with reason: killed
2016-04-10 22:40:56.595 [error] <0.1839.0> CRASH REPORT Process <0.1839.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:40:56.596 [error] <0.1778.0> CRASH REPORT Process <0.1778.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:56.596 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:40:58.667 [info] <0.1855.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.1855.0>
2016-04-10 22:40:58.681 [info] <0.7.0> Application mnesia2 started on node 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:40:59.683 [error] <0.4621.0> gen_server <0.4621.0> terminated with reason: killed
2016-04-10 22:40:59.683 [error] <0.4621.0> CRASH REPORT Process <0.4621.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:40:59.684 [error] <0.4549.0> CRASH REPORT Process <0.4549.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:59.684 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:00.735 [error] <0.1846.0> CRASH REPORT Process <0.1846.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:00.735 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:02.298 [info] <0.1936.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.1936.0>
2016-04-10 22:41:02.301 [info] <0.7.0> Application mnesia2 started on node 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:41:02.303 [error] <0.1927.0> CRASH REPORT Process <0.1927.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:02.292 [info] <0.4664.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.4664.0>
2016-04-10 22:41:02.294 [info] <0.7.0> Application mnesia2 started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:41:02.303 [error] <0.4655.0> CRASH REPORT Process <0.4655.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:02.303 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:02.348 [info] <0.4739.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.4739.0>
2016-04-10 22:41:02.303 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:06.409 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:41:06.479 [info] <0.4863.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.4863.0>
2016-04-10 22:41:06.484 [info] <0.7.0> Application mnesia2 started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:41:06.471 [info] <0.2006.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.2006.0>
2016-04-10 22:41:06.473 [info] <0.7.0> Application mnesia2 started on node 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:41:15.829 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:41:15.830 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:41:22.880 [info] <0.2129.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.2129.0>
2016-04-10 22:41:22.883 [info] <0.7.0> Application mnesia2 started on node 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:41:22.944 [error] <0.2182.0> gen_server <0.2182.0> terminated with reason: killed
2016-04-10 22:41:22.944 [error] <0.2182.0> CRASH REPORT Process <0.2182.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:41:22.945 [error] <0.2119.0> CRASH REPORT Process <0.2119.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:22.865 [info] <0.4994.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.4994.0>
2016-04-10 22:41:22.867 [info] <0.7.0> Application mnesia2 started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:41:22.977 [error] <0.4985.0> CRASH REPORT Process <0.4985.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:22.977 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:23.073 [info] <0.5082.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.5082.0>
2016-04-10 22:41:23.076 [info] <0.7.0> Application mnesia2 started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:41:23.792 [error] <0.5151.0> gen_server <0.5151.0> terminated with reason: killed
2016-04-10 22:41:23.792 [error] <0.5151.0> CRASH REPORT Process <0.5151.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:41:23.793 [error] <0.5073.0> CRASH REPORT Process <0.5073.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:23.793 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:22.945 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:23.320 [info] <0.2216.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.2216.0>
2016-04-10 22:41:23.324 [info] <0.7.0> Application mnesia2 started on node 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:41:24.923 [error] <0.2207.0> CRASH REPORT Process <0.2207.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:24.923 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:26.005 [info] <0.2319.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.2319.0>
2016-04-10 22:41:26.020 [info] <0.7.0> Application mnesia2 started on node 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:41:26.050 [error] <0.2358.0> gen_server <0.2358.0> terminated with reason: killed
2016-04-10 22:41:25.995 [info] <0.5205.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.5205.0>
2016-04-10 22:41:25.999 [info] <0.7.0> Application mnesia2 started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:41:26.050 [error] <0.5200.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.5216.0> exit with reason killed in context child_terminated
2016-04-10 22:41:26.053 [error] <0.5200.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.5216.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:41:26.050 [error] <0.2358.0> CRASH REPORT Process <0.2358.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:41:26.053 [error] <0.5198.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.5200.0> exit with reason killed in context child_terminated
2016-04-10 22:41:26.051 [error] <0.2310.0> CRASH REPORT Process <0.2310.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:26.053 [error] <0.5269.0> gen_server <0.5269.0> terminated with reason: killed
2016-04-10 22:41:26.053 [error] <0.5269.0> CRASH REPORT Process <0.5269.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:41:26.054 [error] <0.5198.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.5200.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:41:26.055 [error] <0.5196.0> CRASH REPORT Process <0.5196.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:26.055 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:26.052 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:28.315 [info] <0.5316.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.5316.0>
2016-04-10 22:41:28.321 [info] <0.7.0> Application mnesia2 started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:41:28.337 [error] <0.5380.0> gen_server <0.5380.0> terminated with reason: killed
2016-04-10 22:41:28.328 [info] <0.2394.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.2394.0>
2016-04-10 22:41:28.333 [info] <0.7.0> Application mnesia2 started on node 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:41:28.340 [error] <0.2406.0> gen_server <0.2406.0> terminated with reason: killed
2016-04-10 22:41:28.337 [error] <0.5380.0> CRASH REPORT Process <0.5380.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:41:28.340 [error] <0.2406.0> CRASH REPORT Process <0.2406.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:41:28.337 [error] <0.5307.0> CRASH REPORT Process <0.5307.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:28.341 [error] <0.2385.0> CRASH REPORT Process <0.2385.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:28.338 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:28.341 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:30.385 [info] <0.5396.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.5396.0>
2016-04-10 22:41:30.394 [info] <0.7.0> Application mnesia2 started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:41:30.407 [error] <0.5433.0> gen_server <0.5433.0> terminated with reason: killed
2016-04-10 22:41:30.407 [error] <0.5433.0> CRASH REPORT Process <0.5433.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:41:30.408 [error] <0.5387.0> CRASH REPORT Process <0.5387.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:30.376 [info] <0.2453.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.2453.0>
2016-04-10 22:41:30.377 [info] <0.7.0> Application mnesia2 started on node 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:41:30.408 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:31.849 [error] <0.2444.0> CRASH REPORT Process <0.2444.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:31.849 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:32.946 [info] <0.5521.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.5521.0>
2016-04-10 22:41:32.949 [info] <0.7.0> Application mnesia2 started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:41:33.372 [error] <0.5574.0> gen_server <0.5574.0> terminated with reason: killed
2016-04-10 22:41:32.969 [info] <0.2542.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.2542.0>
2016-04-10 22:41:32.986 [info] <0.7.0> Application mnesia2 started on node 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:41:33.373 [error] <0.2593.0> gen_server <0.2593.0> terminated with reason: killed
2016-04-10 22:41:33.274 [info] <0.7.0> Application lager started on node 'd1169922o1169898n1169892@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:41:33.275 [info] <0.7.0> Application poolgirl started on node 'd1169922o1169898n1169892@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:41:33.305 [info] <0.101.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169922o1169898n1169892@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.101.0>
2016-04-10 22:41:33.325 [info] <0.7.0> Application mnesia2 started on node 'd1169922o1169898n1169892@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:41:33.372 [error] <0.5574.0> CRASH REPORT Process <0.5574.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:41:33.374 [error] <0.2593.0> CRASH REPORT Process <0.2593.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:41:33.372 [error] <0.5566.0> gen_server <0.5566.0> terminated with reason: killed
2016-04-10 22:41:33.374 [error] <0.2584.0> gen_server <0.2584.0> terminated with reason: killed
2016-04-10 22:41:33.372 [error] <0.5566.0> CRASH REPORT Process <0.5566.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:41:33.374 [error] <0.2584.0> CRASH REPORT Process <0.2584.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:41:33.372 [error] <0.5512.0> CRASH REPORT Process <0.5512.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:33.374 [error] <0.2533.0> CRASH REPORT Process <0.2533.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:33.372 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:33.374 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:35.606 [info] <0.2623.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.2623.0>
2016-04-10 22:41:35.621 [info] <0.7.0> Application mnesia2 started on node 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:41:35.634 [error] <0.2614.0> CRASH REPORT Process <0.2614.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:35.591 [info] <0.5616.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.5616.0>
2016-04-10 22:41:35.595 [info] <0.7.0> Application mnesia2 started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:41:35.634 [error] <0.5680.0> gen_server <0.5680.0> terminated with reason: killed
2016-04-10 22:41:35.634 [error] <0.5680.0> CRASH REPORT Process <0.5680.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:41:35.635 [error] <0.5607.0> CRASH REPORT Process <0.5607.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:35.635 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:35.634 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:37.739 [info] <0.2693.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.2693.0>
2016-04-10 22:41:37.743 [info] <0.7.0> Application mnesia2 started on node 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:41:37.759 [error] <0.2705.0> gen_server <0.2705.0> terminated with reason: killed
2016-04-10 22:41:37.733 [info] <0.5710.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.5710.0>
2016-04-10 22:41:37.735 [info] <0.7.0> Application mnesia2 started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:41:37.761 [error] <0.5754.0> gen_server <0.5754.0> terminated with reason: killed
2016-04-10 22:41:37.761 [error] <0.5754.0> CRASH REPORT Process <0.5754.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:41:37.759 [error] <0.2705.0> CRASH REPORT Process <0.2705.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:41:37.762 [error] <0.5701.0> CRASH REPORT Process <0.5701.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:37.760 [error] <0.2684.0> CRASH REPORT Process <0.2684.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:37.762 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:37.760 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:39.929 [info] <0.2768.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.2768.0>
2016-04-10 22:41:39.933 [info] <0.7.0> Application mnesia2 started on node 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:41:39.935 [error] <0.2763.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.2781.0> exit with reason killed in context child_terminated
2016-04-10 22:41:39.935 [error] <0.2763.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.2781.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:41:39.935 [error] <0.2820.0> gen_server <0.2820.0> terminated with reason: killed
2016-04-10 22:41:39.935 [error] <0.2820.0> CRASH REPORT Process <0.2820.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:41:39.936 [error] <0.2759.0> CRASH REPORT Process <0.2759.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:39.913 [info] <0.5796.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.5796.0>
2016-04-10 22:41:39.915 [info] <0.7.0> Application mnesia2 started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:41:39.936 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:40.964 [error] <0.5787.0> CRASH REPORT Process <0.5787.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:40.964 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:42.996 [info] <0.2838.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.2838.0>
2016-04-10 22:41:42.998 [info] <0.7.0> Application mnesia2 started on node 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:41:48.026 [info] <0.5874.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.5874.0>
2016-04-10 22:41:48.035 [info] <0.7.0> Application mnesia2 started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:41:48.041 [error] <0.5918.0> gen_server <0.5918.0> terminated with reason: killed
2016-04-10 22:41:48.041 [error] <0.5918.0> CRASH REPORT Process <0.5918.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:41:48.042 [error] <0.2905.0> gen_server <0.2905.0> terminated with reason: killed
2016-04-10 22:41:48.041 [error] <0.5865.0> CRASH REPORT Process <0.5865.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:48.042 [error] <0.2905.0> CRASH REPORT Process <0.2905.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:41:48.042 [error] <0.2829.0> CRASH REPORT Process <0.2829.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:48.041 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:48.042 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:49.239 [info] <0.2937.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.2937.0>
2016-04-10 22:41:49.251 [info] <0.7.0> Application mnesia2 started on node 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:41:49.336 [error] <0.2928.0> CRASH REPORT Process <0.2928.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:49.224 [info] <0.5984.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.5984.0>
2016-04-10 22:41:49.226 [info] <0.7.0> Application mnesia2 started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:41:49.422 [error] <0.6071.0> gen_server <0.6071.0> terminated with reason: killed
2016-04-10 22:41:49.422 [error] <0.6071.0> CRASH REPORT Process <0.6071.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:41:49.422 [error] <0.6046.0> gen_server <0.6046.0> terminated with reason: killed
2016-04-10 22:41:49.422 [error] <0.6046.0> CRASH REPORT Process <0.6046.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:41:49.423 [error] <0.6087.0> gen_server <0.6087.0> terminated with reason: killed
2016-04-10 22:41:49.423 [error] <0.6087.0> CRASH REPORT Process <0.6087.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:41:49.423 [error] <0.5975.0> CRASH REPORT Process <0.5975.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:49.190 [warning] <0.6.0> lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:41:49.281 [info] <0.192.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169922o1169898n1169892@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.192.0>
2016-04-10 22:41:49.293 [info] <0.7.0> Application mnesia2 started on node 'd1169922o1169898n1169892@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:41:49.443 [error] <0.274.0> gen_server <0.274.0> terminated with reason: killed
2016-04-10 22:41:49.443 [error] <0.274.0> CRASH REPORT Process <0.274.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:41:49.541 [info] <0.296.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169922o1169898n1169892@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.296.0>
2016-04-10 22:41:49.423 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:49.536 [info] <0.6106.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.6106.0>
2016-04-10 22:41:49.336 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:49.362 [info] <0.3028.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.3028.0>
2016-04-10 22:41:49.506 [info] <0.3123.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.3123.0>
2016-04-10 22:41:50.371 [warning] <0.6.0> lager_error_logger_h dropped 33 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:41:50.371 [error] <0.356.0> gen_server <0.356.0> terminated with reason: killed
2016-04-10 22:41:50.371 [error] <0.356.0> CRASH REPORT Process <0.356.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:41:50.371 [error] <0.367.0> gen_server <0.367.0> terminated with reason: killed
2016-04-10 22:41:50.371 [error] <0.367.0> CRASH REPORT Process <0.367.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:41:50.373 [error] <0.286.0> CRASH REPORT Process <0.286.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:50.373 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:50.406 [info] <0.391.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169922o1169898n1169892@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.391.0>
2016-04-10 22:41:50.410 [info] <0.7.0> Application mnesia2 started on node 'd1169922o1169898n1169892@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:41:52.488 [error] <0.6167.0> gen_server <0.6167.0> terminated with reason: killed
2016-04-10 22:41:52.488 [error] <0.6167.0> CRASH REPORT Process <0.6167.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:41:52.488 [error] <0.6206.0> gen_server <0.6206.0> terminated with reason: killed
2016-04-10 22:41:52.488 [error] <0.6206.0> CRASH REPORT Process <0.6206.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:41:52.497 [error] <0.6097.0> CRASH REPORT Process <0.6097.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:52.509 [error] <0.3216.0> gen_server <0.3216.0> terminated with reason: killed
2016-04-10 22:41:52.509 [error] <0.3216.0> CRASH REPORT Process <0.3216.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:41:52.510 [error] <0.3114.0> CRASH REPORT Process <0.3114.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:52.497 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:52.601 [info] <0.6223.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.6223.0>
2016-04-10 22:41:52.907 [info] <0.7.0> Application mnesia2 started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:41:52.510 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:52.603 [info] <0.3237.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.3237.0>
2016-04-10 22:41:52.614 [info] <0.7.0> Application mnesia2 started on node 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:41:52.550 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:41:52.571 [info] <0.497.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169922o1169898n1169892@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.497.0>
2016-04-10 22:41:52.573 [info] <0.7.0> Application mnesia2 started on node 'd1169922o1169898n1169892@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:41:55.928 [error] <0.488.0> CRASH REPORT Process <0.488.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:56.045 [error] <0.6293.0> gen_server <0.6293.0> terminated with reason: killed
2016-04-10 22:41:56.045 [error] <0.6293.0> CRASH REPORT Process <0.6293.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:41:56.045 [error] <0.6317.0> gen_server <0.6317.0> terminated with reason: killed
2016-04-10 22:41:56.045 [error] <0.6317.0> CRASH REPORT Process <0.6317.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:41:56.046 [error] <0.6311.0> gen_server <0.6311.0> terminated with reason: killed
2016-04-10 22:41:56.046 [error] <0.6311.0> CRASH REPORT Process <0.6311.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:41:56.046 [error] <0.6214.0> CRASH REPORT Process <0.6214.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:56.066 [error] <0.3325.0> gen_server <0.3325.0> terminated with reason: killed
2016-04-10 22:41:56.066 [error] <0.3325.0> CRASH REPORT Process <0.3325.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:41:56.067 [error] <0.3228.0> CRASH REPORT Process <0.3228.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:55.928 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:55.954 [info] <0.595.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169922o1169898n1169892@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.595.0>
2016-04-10 22:41:55.955 [info] <0.7.0> Application mnesia2 started on node 'd1169922o1169898n1169892@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:41:56.107 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:41:56.123 [info] <0.696.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169922o1169898n1169892@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.696.0>
2016-04-10 22:41:56.124 [info] <0.7.0> Application mnesia2 started on node 'd1169922o1169898n1169892@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:41:56.067 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:56.163 [info] <0.3346.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.3346.0>
2016-04-10 22:41:56.479 [info] <0.7.0> Application mnesia2 started on node 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:41:56.982 [error] <0.3414.0> gen_server <0.3414.0> terminated with reason: killed
2016-04-10 22:41:56.046 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:56.177 [info] <0.6335.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.6335.0>
2016-04-10 22:41:56.982 [error] <0.3414.0> CRASH REPORT Process <0.3414.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:41:56.982 [error] <0.3337.0> CRASH REPORT Process <0.3337.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:56.983 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:57.277 [info] <0.3445.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.3445.0>
2016-04-10 22:41:57.290 [info] <0.7.0> Application mnesia2 started on node 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:41:57.332 [error] <0.3503.0> gen_server <0.3503.0> terminated with reason: killed
2016-04-10 22:41:57.332 [error] <0.3503.0> CRASH REPORT Process <0.3503.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:41:57.332 [error] <0.3493.0> gen_server <0.3493.0> terminated with reason: killed
2016-04-10 22:41:57.332 [error] <0.3493.0> CRASH REPORT Process <0.3493.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:41:57.332 [error] <0.3459.0> gen_server <0.3459.0> terminated with reason: killed
2016-04-10 22:41:57.332 [error] <0.3459.0> CRASH REPORT Process <0.3459.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:41:58.363 [info] <0.3523.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.3523.0>
2016-04-10 22:41:58.388 [info] <0.7.0> Application mnesia2 started on node 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:41:58.434 [error] <0.3548.0> gen_server <0.3548.0> terminated with reason: killed
2016-04-10 22:41:58.434 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:41:58.434 [error] <0.6326.0> CRASH REPORT Process <0.6326.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:58.436 [error] <0.819.0> gen_server <0.819.0> terminated with reason: killed
2016-04-10 22:41:58.434 [error] <0.3548.0> CRASH REPORT Process <0.3548.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:41:58.436 [error] <0.819.0> CRASH REPORT Process <0.819.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:41:58.434 [error] <0.3514.0> CRASH REPORT Process <0.3514.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:58.436 [error] <0.813.0> gen_server <0.813.0> terminated with reason: killed
2016-04-10 22:41:58.436 [error] <0.813.0> CRASH REPORT Process <0.813.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:41:58.436 [error] <0.762.0> gen_server <0.762.0> terminated with reason: killed
2016-04-10 22:41:58.436 [error] <0.762.0> CRASH REPORT Process <0.762.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:41:58.436 [error] <0.687.0> CRASH REPORT Process <0.687.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:58.435 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:58.732 [info] <0.3601.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.3601.0>
2016-04-10 22:41:58.435 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:41:58.711 [info] <0.6479.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.6479.0>
2016-04-10 22:41:58.713 [info] <0.7.0> Application mnesia2 started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:41:58.436 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:42:06.221 [error] <0.3655.0> gen_server <0.3655.0> terminated with reason: killed
2016-04-10 22:42:06.221 [error] <0.3655.0> CRASH REPORT Process <0.3655.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:42:06.223 [error] <0.3592.0> CRASH REPORT Process <0.3592.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:42:06.223 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:42:06.293 [info] <0.3696.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.3696.0>
2016-04-10 22:42:06.327 [info] <0.7.0> Application mnesia2 started on node 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:42:06.345 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:06.402 [info] <0.3786.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.3786.0>
2016-04-10 22:42:06.464 [info] <0.3886.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.3886.0>
2016-04-10 22:42:07.050 [warning] <0.6.0> lager_error_logger_h dropped 10 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:42:07.051 [error] <0.3877.0> CRASH REPORT Process <0.3877.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:42:07.051 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:42:06.462 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:06.981 [info] <0.6592.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.6592.0>
2016-04-10 22:42:07.020 [info] <0.7.0> Application mnesia2 started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:42:07.049 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:07.090 [info] <0.6675.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.6675.0>
2016-04-10 22:42:07.092 [info] <0.7.0> Application mnesia2 started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:42:07.683 [error] <0.6740.0> gen_server <0.6740.0> terminated with reason: killed
2016-04-10 22:42:07.595 [info] <0.3968.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.3968.0>
2016-04-10 22:42:07.633 [info] <0.7.0> Application mnesia2 started on node 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:42:07.685 [error] <0.4019.0> gen_server <0.4019.0> terminated with reason: killed
2016-04-10 22:42:07.683 [error] <0.6740.0> CRASH REPORT Process <0.6740.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:42:07.686 [error] <0.4019.0> CRASH REPORT Process <0.4019.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:42:07.684 [error] <0.6666.0> CRASH REPORT Process <0.6666.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:42:07.686 [error] <0.3959.0> CRASH REPORT Process <0.3959.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:42:07.686 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:42:07.766 [info] <0.4060.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.4060.0>
2016-04-10 22:42:08.070 [info] <0.7.0> Application mnesia2 started on node 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:42:07.684 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:42:07.762 [info] <0.6776.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.6776.0>
2016-04-10 22:42:07.767 [info] <0.846.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169922o1169898n1169892@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.846.0>
2016-04-10 22:42:07.783 [info] <0.7.0> Application mnesia2 started on node 'd1169922o1169898n1169892@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:42:08.979 [error] <0.6839.0> gen_server <0.6839.0> terminated with reason: killed
2016-04-10 22:42:08.980 [error] <0.908.0> gen_server <0.908.0> terminated with reason: killed
2016-04-10 22:42:08.979 [error] <0.6839.0> CRASH REPORT Process <0.6839.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:42:08.984 [error] <0.4124.0> gen_server <0.4124.0> terminated with reason: killed
2016-04-10 22:42:08.979 [error] <0.6832.0> gen_server <0.6832.0> terminated with reason: killed
2016-04-10 22:42:08.984 [error] <0.4124.0> CRASH REPORT Process <0.4124.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:42:08.980 [error] <0.908.0> CRASH REPORT Process <0.908.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:42:08.979 [error] <0.6832.0> CRASH REPORT Process <0.6832.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:42:08.984 [error] <0.4119.0> gen_server <0.4119.0> terminated with reason: killed
2016-04-10 22:42:08.980 [error] <0.901.0> gen_server <0.901.0> terminated with reason: killed
2016-04-10 22:42:08.982 [error] <0.6767.0> CRASH REPORT Process <0.6767.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:42:08.984 [error] <0.4119.0> CRASH REPORT Process <0.4119.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:42:08.984 [error] <0.4051.0> CRASH REPORT Process <0.4051.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:42:08.981 [error] <0.901.0> CRASH REPORT Process <0.901.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:42:08.981 [error] <0.837.0> CRASH REPORT Process <0.837.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:42:08.981 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:42:09.010 [info] <0.949.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169922o1169898n1169892@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.949.0>
2016-04-10 22:42:09.012 [info] <0.7.0> Application mnesia2 started on node 'd1169922o1169898n1169892@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:42:09.059 [error] <0.998.0> gen_server <0.998.0> terminated with reason: killed
2016-04-10 22:42:08.984 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:42:09.021 [info] <0.4154.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.4154.0>
2016-04-10 22:42:09.022 [info] <0.7.0> Application mnesia2 started on node 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:42:09.061 [error] <0.4198.0> gen_server <0.4198.0> terminated with reason: killed
2016-04-10 22:42:08.982 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:42:09.042 [info] <0.6887.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.6887.0>
2016-04-10 22:42:09.052 [info] <0.7.0> Application mnesia2 started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:42:09.061 [error] <0.6878.0> CRASH REPORT Process <0.6878.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:42:09.061 [error] <0.4198.0> CRASH REPORT Process <0.4198.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:42:09.059 [error] <0.998.0> CRASH REPORT Process <0.998.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:42:09.062 [error] <0.4209.0> gen_server <0.4209.0> terminated with reason: killed
2016-04-10 22:42:09.060 [error] <0.1007.0> gen_server <0.1007.0> terminated with reason: killed
2016-04-10 22:42:09.062 [error] <0.4209.0> CRASH REPORT Process <0.4209.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:42:09.063 [error] <0.4145.0> CRASH REPORT Process <0.4145.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:42:09.060 [error] <0.1007.0> CRASH REPORT Process <0.1007.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:42:09.060 [error] <0.993.0> gen_server <0.993.0> terminated with reason: killed
2016-04-10 22:42:09.060 [error] <0.993.0> CRASH REPORT Process <0.993.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:42:09.060 [error] <0.940.0> CRASH REPORT Process <0.940.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:42:09.061 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:42:09.116 [info] <0.6979.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.6979.0>
2016-04-10 22:42:09.123 [error] <0.6973.0> Mnesia2('test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'): ** ERROR ** (core dumped to file: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16.2016-04-10_22.38.54/Mnesia2Core.test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16_1460_328129_122322")
 ** FATAL ** Failed to merge schema: Bad cookie in table definition tab1: 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16' = {cstruct,tab1,set,['d1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16','d1169922o1169898n1169892@testing-worker-linux-docker-71fc02f6-3370-linux-16'],['test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'],[],0,read_write,false,[],[],false,tab1,[key,val],[],[],[],{{1460328128957648,1460328128957651,1},'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'},{{2,0},[]}}, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16' = {cstruct,tab1,set,['d1169922o1169898n1169892@testing-worker-linux-docker-71fc02f6-3370-linux-16'],[],[],0,read_write,false,[],[],false,tab1,[key,val],[],[],[],{{1460328129103480,1460328129103481,1},'d1169922o1169898n1169892@testing-worker-linux-docker-71fc02f6-3370-linux-16'},{{2,0},[]}}


2016-04-10 22:42:09.060 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:42:09.098 [info] <0.1026.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169922o1169898n1169892@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.1026.0>
2016-04-10 22:42:09.063 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:42:09.096 [info] <0.4232.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.4232.0>
2016-04-10 22:42:19.124 [error] <0.6972.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at undefined exit with reason killed in context start_error
2016-04-10 22:42:19.124 [error] <0.6975.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-10 22:42:19.124 [error] <0.6978.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-10 22:42:19.124 [error] <0.6978.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:42:19.124 [error] <0.6998.0> gen_server mnesia2_snmp_sup terminated with reason: killed
2016-04-10 22:42:19.124 [error] <0.6998.0> CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:42:19.124 [error] <0.6976.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-10 22:42:19.124 [error] <0.6976.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:42:19.125 [error] <0.6970.0> CRASH REPORT Process <0.6970.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}} in application_master:init/4 line 133
2016-04-10 22:42:19.125 [info] <0.7.0> Application mnesia2 exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}}
2016-04-10 22:42:19.127 [error] <0.6975.0> CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:42:19.237 [error] <0.4276.0> gen_server <0.4276.0> terminated with reason: killed
2016-04-10 22:42:19.237 [warning] <0.6.0> lager_error_logger_h dropped 39 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:42:19.237 [error] <0.1017.0> CRASH REPORT Process <0.1017.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:42:19.237 [error] <0.4276.0> CRASH REPORT Process <0.4276.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 22:42:19.237 [error] <0.4223.0> CRASH REPORT Process <0.4223.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:42:19.237 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:42:19.238 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:42:21.603 [info] <0.7088.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.7088.0>
2016-04-10 22:42:21.605 [info] <0.7.0> Application mnesia2 started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:42:25.579 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:25.742 [info] <0.7224.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.7224.0>
2016-04-10 22:42:26.047 [info] <0.7.0> Application mnesia2 started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:42:25.745 [info] <0.4323.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.4323.0>
2016-04-10 22:42:26.070 [info] <0.7.0> Application mnesia2 started on node 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:42:25.746 [info] <0.1122.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169922o1169898n1169892@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.1122.0>
2016-04-10 22:42:25.753 [info] <0.7.0> Application mnesia2 started on node 'd1169922o1169898n1169892@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:42:32.128 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:32.444 [info] <0.7354.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.7354.0>
2016-04-10 22:42:32.486 [info] <0.7.0> Application mnesia2 started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:42:32.129 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:32.444 [info] <0.4441.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.4441.0>
2016-04-10 22:42:32.751 [info] <0.7.0> Application mnesia2 started on node 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:42:32.162 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:32.472 [info] <0.1236.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169922o1169898n1169892@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.1236.0>
2016-04-10 22:42:32.482 [info] <0.7.0> Application mnesia2 started on node 'd1169922o1169898n1169892@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:42:38.823 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:38.980 [info] <0.1350.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169922o1169898n1169892@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.1350.0>
2016-04-10 22:42:38.858 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:38.966 [info] <0.7483.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.7483.0>
2016-04-10 22:42:39.271 [info] <0.7.0> Application mnesia2 started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:42:38.857 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:38.982 [info] <0.4558.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.4558.0>
2016-04-10 22:42:38.992 [info] <0.7.0> Application mnesia2 started on node 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:42:40.408 [info] <0.7.0> Application mnesia2 started on node 'd1169922o1169898n1169892@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:42:58.716 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:58.892 [info] <0.8622.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.8622.0>
2016-04-10 22:42:58.896 [info] <0.7.0> Application mnesia2 started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:42:58.719 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:58.909 [info] <0.2477.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169922o1169898n1169892@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.2477.0>
2016-04-10 22:42:58.921 [info] <0.7.0> Application mnesia2 started on node 'd1169922o1169898n1169892@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:42:58.733 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:42:58.908 [info] <0.5682.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.5682.0>
2016-04-10 22:42:59.212 [info] <0.7.0> Application mnesia2 started on node 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:43:05.588 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:43:05.721 [info] <0.2602.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169922o1169898n1169892@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.2602.0>
2016-04-10 22:43:06.040 [info] <0.7.0> Application mnesia2 started on node 'd1169922o1169898n1169892@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:43:05.596 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:43:05.706 [info] <0.8760.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.8760.0>
2016-04-10 22:43:06.024 [info] <0.7.0> Application mnesia2 started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:43:05.597 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:43:05.726 [info] <0.5809.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.5809.0>
2016-04-10 22:43:05.729 [info] <0.7.0> Application mnesia2 started on node 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:43:12.318 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:43:12.449 [info] <0.10242.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.10242.0>
2016-04-10 22:43:12.759 [info] <0.7.0> Application mnesia2 started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:43:12.325 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:43:12.465 [info] <0.7278.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.7278.0>
2016-04-10 22:43:12.482 [info] <0.7.0> Application mnesia2 started on node 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:43:12.318 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:43:12.453 [info] <0.4075.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169922o1169898n1169892@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.4075.0>
2016-04-10 22:43:12.492 [info] <0.7.0> Application mnesia2 started on node 'd1169922o1169898n1169892@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:43:19.086 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:43:19.258 [info] <0.7653.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.7653.0>
2016-04-10 22:43:19.267 [info] <0.7.0> Application mnesia2 started on node 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:43:19.090 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:43:19.241 [info] <0.12006.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.12006.0>
2016-04-10 22:43:19.244 [info] <0.7.0> Application mnesia2 started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:43:19.093 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:43:19.257 [info] <0.5398.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169922o1169898n1169892@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.5398.0>
2016-04-10 22:43:19.458 [info] <0.7.0> Application mnesia2 started on node 'd1169922o1169898n1169892@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:43:25.629 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:43:25.806 [info] <0.7769.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.7769.0>
2016-04-10 22:43:25.829 [info] <0.7.0> Application mnesia2 started on node 'd1169912o1169900n1169900@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:43:25.651 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:43:25.802 [info] <0.12135.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.12135.0>
2016-04-10 22:43:26.112 [info] <0.7.0> Application mnesia2 started on node 'test3953@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:43:25.655 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:43:25.812 [info] <0.6190.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1169922o1169898n1169892@testing-worker-linux-docker-71fc02f6-3370-linux-16', <0.6190.0>
2016-04-10 22:43:25.817 [info] <0.7.0> Application mnesia2 started on node 'd1169922o1169898n1169892@testing-worker-linux-docker-71fc02f6-3370-linux-16'
2016-04-10 22:43:32.361 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:43:32.361 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:43:32.368 [info] <0.7.0> Application mnesia2 exited with reason: stopped
