--- Test run on 2016/04/10 22:49:56 ---
Converting "/home/travis/build/lrascao/mnesia2/." to "/home/travis/build/lrascao/mnesia2" and re-inserting with add_patha/1


Common Test v1.7.3 starting (cwd is /home/travis/build/lrascao/mnesia2)


Common Test: Running make in test directories...
Recompile: mnesia2_extra_light_SUITE
Recompile: ts_install_cth
Recompile: mt
Recompile: mnesia2_trans_access_test
Recompile: mnesia2_tpcb
Recompile: mnesia2_test_lib
Recompile: mnesia2_schema_recovery_test
mnesia2_schema_recovery_test.erl:261: Warning: variable 'Bad' is unused
Recompile: mnesia2_registry_test
Recompile: mnesia2_recovery_test
mnesia2_recovery_test.erl:1571: Warning: variable 'Config' is unused
Recompile: mnesia2_qlc_test
Recompile: mnesia2_nice_coverage_test
Recompile: mnesia2_meter
Recompile: mnesia2_measure_test
Recompile: mnesia2_majority_test
Recompile: mnesia2_isolation_test
Recompile: mnesia2_install_test
Recompile: mnesia2_inconsistent_database_test
Recompile: mnesia2_frag_test
Recompile: mnesia2_frag_hash_test
Recompile: mnesia2_examples_test
Recompile: mnesia2_evil_coverage_test
Recompile: mnesia2_evil_backup
Recompile: mnesia2_durability_test
Recompile: mnesia2_dirty_access_test
Recompile: mnesia2_dbn_meters
Recompile: mnesia2_cost
Recompile: mnesia2_consistency_test
Recompile: mnesia2_config_test
Recompile: mnesia2_config_event
Recompile: mnesia2_config_backup
Recompile: mnesia2_atomicity_test

CWD set to: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16.2016-04-10_22.49.57"

TEST INFO: 1 test(s), 52 case(s) in 1 suite(s)

Cover compiling 'mnesia2' (32 files) - this may take some time... done

Testing lrascao.mnesia2.mnesia2_extra_light_SUITE: Starting test, 52 test cases

----------------------------------------------------
2016-04-10 22:50:21.653
starting test group: extra_light


----------------------------------------------------
2016-04-10 22:50:21.680
starting test group: install


----------------------------------------------------
2016-04-10 22:50:21.759
starting test case: silly_durability

22:50:21.881 [info] Application lager started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:50:21.881 [info] Application poolgirl started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:50:21.925 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.460.0>
22:50:21.945 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.528.0>

----------------------------------------------------
2016-04-10 22:50:21.950
ending test case: silly_durability


----------------------------------------------------
2016-04-10 22:50:21.975
starting test case: silly_move

22:50:22.328 [error] CRASH REPORT Process <0.519.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:50:22.328 [info] Application mnesia2 exited with reason: killed
22:50:22.413 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.638.0>
22:50:22.415 [info] Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:50:22.671 [info] Application lager started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:50:22.671 [info] Application poolgirl started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:50:22.722 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.99.0>

----------------------------------------------------
2016-04-10 22:50:22.868
ending test case: silly_move


----------------------------------------------------
2016-04-10 22:50:22.894
starting test case: silly_upgrade

22:50:22.896 [error] gen_server <0.695.0> terminated with reason: killed
22:50:22.896 [error] CRASH REPORT Process <0.695.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:50:22.897 [error] CRASH REPORT Process <0.629.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:50:22.957 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.765.0>
22:50:22.960 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.215.0>
22:50:23.263 [info] Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:50:23.429 [warning] lager_error_logger_h dropped 6 messages in the last second that exceeded the limit of 50 messages/sec
22:50:23.429 [info] Application mnesia2 exited with reason: stopped
22:50:23.432 [error] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): ** ERROR ** (ignoring core) ** FATAL ** A fallback is installed and Mnesia2 must be restarted. Forcing shutdown after mnesia2_down from 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'...

22:50:23.432 [error] Supervisor mnesia2_kernel_sup had child mnesia2_locker started with mnesia2_locker:start() at <0.763.0> exit with reason killed in context child_terminated
22:50:23.432 [error] Supervisor mnesia2_kernel_sup had child mnesia2_locker started with mnesia2_locker:start() at <0.763.0> exit with reason reached_max_restart_intensity in context shutdown
22:50:23.434 [error] Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.760.0> exit with reason shutdown in context child_terminated
22:50:23.434 [error] Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.760.0> exit with reason reached_max_restart_intensity in context shutdown
22:50:23.434 [info] Application mnesia2 exited with reason: shutdown
22:50:23.475 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.894.0>
22:50:23.496 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.369.0>
22:50:23.500 [info] Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:50:24.015 [info] Application mnesia2 exited with reason: stopped
22:50:24.017 [error] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): ** ERROR ** (ignoring core) ** FATAL ** A fallback is installed and Mnesia2 must be restarted. Forcing shutdown after mnesia2_down from 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'...

22:50:24.019 [info] Application mnesia2 exited with reason: stopped
22:50:24.043 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.994.0>
22:50:24.046 [info] Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:50:24.051 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.459.0>
22:50:24.058 [info] Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'

----------------------------------------------------
2016-04-10 22:50:24.076
ending test case: silly_upgrade


----------------------------------------------------
2016-04-10 22:50:24.156
ending test group: install


----------------------------------------------------
2016-04-10 22:50:24.183
starting test group: nice


----------------------------------------------------
2016-04-10 22:50:24.269
starting test case: nice

22:50:24.271 [error] gen_server <0.517.0> terminated with reason: killed
22:50:24.273 [error] gen_server mnesia2_recover terminated with reason: killed
22:50:24.271 [error] CRASH REPORT Process <0.517.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:50:24.273 [error] CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:50:24.272 [error] CRASH REPORT Process <0.450.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:50:24.272 [info] Application mnesia2 exited with reason: killed
22:50:24.273 [error] CRASH REPORT Process mnesia2_event with 0 neighbours exited with reason: killed in gen_event:terminate_server/4 line 320
22:50:24.273 [error] gen_server mnesia2_monitor terminated with reason: killed
22:50:24.340 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.1117.0>
22:50:24.344 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.549.0>
22:50:24.478 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.1229.0>

----------------------------------------------------
2016-04-10 22:50:24.634
ending test case: nice


----------------------------------------------------
2016-04-10 22:50:24.714
ending test group: nice


----------------------------------------------------
2016-04-10 22:50:24.740
starting test group: qlc


----------------------------------------------------
2016-04-10 22:50:24.844
starting test case: dirty_nice_ram_copies

22:50:24.908 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.1461.0>
22:50:24.909 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.763.0>

----------------------------------------------------
2016-04-10 22:50:24.990
ending test case: dirty_nice_ram_copies


----------------------------------------------------
2016-04-10 22:50:25.017
starting test case: dirty_nice_disc_copies

22:50:25.029 [warning] lager_error_logger_h dropped 35 messages in the last second that exceeded the limit of 50 messages/sec
22:50:25.029 [warning] lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
22:50:25.029 [error] CRASH REPORT Process <0.754.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:50:25.029 [info] Application mnesia2 exited with reason: killed
22:50:25.029 [error] CRASH REPORT Process <0.1452.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:50:25.029 [info] Application mnesia2 exited with reason: killed
22:50:25.078 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.1574.0>
22:50:25.081 [info] Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:50:25.088 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.864.0>
22:50:25.101 [info] Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'

----------------------------------------------------
2016-04-10 22:50:25.186
ending test case: dirty_nice_disc_copies


----------------------------------------------------
2016-04-10 22:50:25.227
starting test case: dirty_nice_disc_only_copies

22:50:25.230 [error] gen_server <0.1630.0> terminated with reason: killed
22:50:25.230 [error] gen_server <0.918.0> terminated with reason: killed
22:50:25.230 [error] CRASH REPORT Process <0.1630.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:50:25.230 [error] CRASH REPORT Process <0.918.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:50:25.232 [error] CRASH REPORT Process <0.1565.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:50:25.232 [info] Application mnesia2 exited with reason: killed
22:50:25.231 [error] CRASH REPORT Process <0.855.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:50:25.231 [info] Application mnesia2 exited with reason: killed
22:50:25.281 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.1690.0>
22:50:25.302 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.965.0>

----------------------------------------------------
2016-04-10 22:50:25.420
ending test case: dirty_nice_disc_only_copies


----------------------------------------------------
2016-04-10 22:50:25.497
starting test case: trans_nice_ram_copies

22:50:25.551 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.1816.0>
22:50:25.553 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.1071.0>

----------------------------------------------------
2016-04-10 22:50:25.957
ending test case: trans_nice_ram_copies


----------------------------------------------------
2016-04-10 22:50:25.983
starting test case: trans_nice_disc_copies

22:50:26.036 [warning] lager_error_logger_h dropped 10 messages in the last second that exceeded the limit of 50 messages/sec
22:50:26.036 [warning] lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
22:50:26.045 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.1948.0>
22:50:26.048 [info] Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:50:26.050 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.1171.0>
22:50:26.053 [info] Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'

----------------------------------------------------
2016-04-10 22:50:26.177
ending test case: trans_nice_disc_copies


----------------------------------------------------
2016-04-10 22:50:26.203
starting test case: trans_nice_disc_only_copies

22:50:26.205 [error] Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.1184.0> exit with reason killed in context child_terminated
22:50:26.207 [error] gen_server <0.2004.0> terminated with reason: killed
22:50:26.207 [error] CRASH REPORT Process <0.2004.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:50:26.206 [error] Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.1184.0> exit with reason reached_max_restart_intensity in context shutdown
22:50:26.207 [error] CRASH REPORT Process <0.1939.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:50:26.207 [info] Application mnesia2 exited with reason: killed
22:50:26.206 [error] gen_server <0.1223.0> terminated with reason: killed
22:50:26.206 [error] CRASH REPORT Process <0.1223.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:50:26.206 [error] CRASH REPORT Process <0.1162.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:50:26.206 [info] Application mnesia2 exited with reason: killed
22:50:26.267 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.2081.0>
22:50:26.280 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.1272.0>

----------------------------------------------------
2016-04-10 22:50:26.736
ending test case: trans_nice_disc_only_copies


----------------------------------------------------
2016-04-10 22:50:26.790
starting test case: atomic_eval

22:50:26.850 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.2221.0>
22:50:26.863 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.1378.0>
22:50:27.153 [warning] lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
22:50:27.156 [info] Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'

----------------------------------------------------
2016-04-10 22:50:27.275
ending test case: atomic_eval


----------------------------------------------------
2016-04-10 22:50:27.353
starting test case: frag

22:50:27.355 [warning] lager_error_logger_h dropped 6 messages in the last second that exceeded the limit of 50 messages/sec
22:50:27.357 [error] gen_server <0.2266.0> terminated with reason: killed
22:50:27.357 [error] CRASH REPORT Process <0.2266.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:50:27.355 [error] gen_server <0.1431.0> terminated with reason: killed
22:50:27.367 [error] CRASH REPORT Process <0.2212.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:50:27.367 [info] Application mnesia2 exited with reason: killed
22:50:27.355 [error] CRASH REPORT Process <0.1431.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:50:27.356 [error] CRASH REPORT Process <0.1369.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:50:27.356 [info] Application mnesia2 exited with reason: killed
22:50:27.402 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.2353.0>
22:50:27.427 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.1466.0>
22:50:27.431 [info] Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'

----------------------------------------------------
2016-04-10 22:50:27.552
ending test case: frag


----------------------------------------------------
2016-04-10 22:50:27.578
starting test case: info

22:50:27.581 [error] gen_server <0.1520.0> terminated with reason: killed
22:50:27.581 [error] CRASH REPORT Process <0.1520.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:50:28.144 [warning] lager_error_logger_h dropped 11 messages in the last second that exceeded the limit of 50 messages/sec
22:50:28.152 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.2485.0>
22:50:28.154 [info] Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:50:28.155 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.1578.0>
22:50:28.164 [info] Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'

----------------------------------------------------
2016-04-10 22:50:28.270
ending test case: info


----------------------------------------------------
2016-04-10 22:50:28.296
starting test case: mnesia2_down

22:50:28.298 [error] gen_server <0.1630.0> terminated with reason: killed
22:50:28.299 [error] gen_server <0.2539.0> terminated with reason: killed
22:50:28.298 [error] CRASH REPORT Process <0.1630.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:50:28.299 [error] CRASH REPORT Process <0.2539.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:50:28.299 [error] CRASH REPORT Process <0.1569.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:50:28.299 [info] Application mnesia2 exited with reason: killed
22:50:28.299 [error] CRASH REPORT Process <0.2476.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:50:28.299 [info] Application mnesia2 exited with reason: killed
22:50:28.369 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.2608.0>
22:50:28.387 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.1665.0>
---> Participant transactions <--- 
---> Coordinator transactions <---
Tid: 10 (owned by <0.2685.0>) 

----------------------------------------------------
2016-04-10 22:50:28.464
ending test case: mnesia2_down


----------------------------------------------------
2016-04-10 22:50:28.544
ending test group: qlc


----------------------------------------------------
2016-04-10 22:50:28.570
starting test group: registry


----------------------------------------------------
2016-04-10 22:50:28.649
starting test case: good_dump

22:50:28.687 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.2736.0>

----------------------------------------------------
2016-04-10 22:50:28.787
ending test case: good_dump


----------------------------------------------------
2016-04-10 22:50:28.813
starting test case: bad_dump

22:50:28.858 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.2830.0>

----------------------------------------------------
2016-04-10 22:50:28.866
ending test case: bad_dump


----------------------------------------------------
2016-04-10 22:50:28.947
ending test group: registry


----------------------------------------------------
2016-04-10 22:50:28.973
starting test group: config


----------------------------------------------------
2016-04-10 22:50:29.053
starting test case: access_module

22:50:30.088 [warning] lager_error_logger_h dropped 34 messages in the last second that exceeded the limit of 50 messages/sec
22:50:30.104 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.2940.0>
22:50:30.106 [info] Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:50:31.286 [error] CRASH REPORT Process <0.2931.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:50:31.286 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:50:32.309
ending test case: access_module


----------------------------------------------------
2016-04-10 22:50:32.336
starting test case: auto_repair

22:50:33.366 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.3046.0>
22:50:33.368 [info] Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:50:33.370 [info] Application mnesia2 exited with reason: stopped
22:50:33.371 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.3094.0>
22:50:33.376 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.3142.0>

----------------------------------------------------
2016-04-10 22:50:34.392
ending test case: auto_repair


----------------------------------------------------
2016-04-10 22:50:34.419
starting test case: backup_module

22:50:35.475 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.3214.0>
22:50:35.478 [info] Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:50:35.491 [error] CRASH REPORT Process <0.3205.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:50:35.491 [info] Application mnesia2 exited with reason: killed
22:50:37.543 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.3297.0>
22:50:37.546 [info] Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:50:37.551 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Restore aborted. mnesia2_config_backup:open_read["NonExisting.FILE"] -> {enoent,error}

22:50:37.551 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Restore aborted. mnesia2_config_backup:open_read["/home/travis/build/lrascao/mnesia2/logs/ct_run.test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16.2016-04-10_22.49.57/Mnesia2.test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16/LATEST.LOG"] -> badarg

22:50:37.553 [error] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}}} ({error,{already_started,<0.3373.0>}})

22:50:37.553 [error] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}}} ({error,{already_started,<0.3373.0>}})

22:50:37.553 [error] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}}} ({error,{already_started,<0.3373.0>}})

22:50:37.553 [error] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}}} ({error,{already_started,<0.3373.0>}})

22:50:37.553 [error] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}}} ({error,{already_started,<0.3373.0>}})

22:50:37.553 [error] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}}} ({error,{already_started,<0.3373.0>}})

22:50:37.553 [error] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}}} ({error,{already_started,<0.3373.0>}})

22:50:37.553 [error] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_11,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_11,shutdown]}}}} ({error,{already_started,<0.3373.0>}})


----------------------------------------------------
2016-04-10 22:50:38.576
ending test case: backup_module


----------------------------------------------------
2016-04-10 22:50:38.602
starting test case: debug

22:50:39.630 [warning] lager_error_logger_h dropped 15 messages in the last second that exceeded the limit of 50 messages/sec
22:50:39.631 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_monitor starting: <0.3420.0>

22:50:39.631 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Mnesia2 debug level set to verbose
22:50:39.632 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_subscr starting: <0.3421.0>

22:50:39.632 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_locker starting: <0.3422.0>

22:50:39.632 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_recover starting: <0.3423.0>

22:50:39.632 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.3424.0>
22:50:39.632 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_tm starting: <0.3424.0>

22:50:39.633 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Schema initiated from: default

22:50:39.633 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_controller starting: <0.3427.0>

22:50:39.633 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_late_loader starting: <0.3428.0>

22:50:39.634 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Intend to load tables: []

22:50:39.634 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_tm_1 starting: <0.3430.0>

22:50:39.634 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_tm_2 starting: <0.3431.0>

22:50:39.634 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_tm_3 starting: <0.3432.0>

22:50:39.635 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_tm_4 starting: <0.3433.0>

22:50:39.635 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_tm_5 starting: <0.3434.0>

22:50:39.635 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_tm_6 starting: <0.3435.0>

22:50:39.635 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_tm_7 starting: <0.3436.0>

22:50:39.635 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_tm_8 starting: <0.3437.0>

22:50:39.636 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_tm_9 starting: <0.3438.0>

22:50:39.636 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_tm_10 starting: <0.3439.0>

22:50:39.636 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_tm_11 starting: <0.3440.0>

22:50:39.636 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_tm_12 starting: <0.3441.0>

22:50:39.636 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_tm_13 starting: <0.3442.0>

22:50:39.636 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_tm_14 starting: <0.3443.0>

22:50:41.667 [warning] lager_error_logger_h dropped 25 messages in the last second that exceeded the limit of 50 messages/sec
22:50:41.667 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_monitor starting: <0.3494.0>

22:50:41.667 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Version: "1.0.0"

22:50:41.668 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env access_module: mnesia2

22:50:41.668 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env auto_repair: true

22:50:41.668 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env backup_module: mnesia2_backup

22:50:41.668 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env debug: debug

22:50:41.668 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16.2016-04-10_22.49.57/Mnesia2.test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16"

22:50:41.669 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env dump_disc_copies_at_startup: true

22:50:41.669 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env dump_log_load_regulation: false

22:50:41.669 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env dump_log_time_threshold: 180000

22:50:41.669 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env dump_log_update_in_place: true

22:50:41.669 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env dump_log_write_threshold: 1000

22:50:41.669 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env event_module: mnesia2_event

22:50:41.669 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env extra_db_nodes: []

22:50:41.669 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env ignore_fallback_at_startup: false

22:50:41.670 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env fallback_error_function: {mnesia2,lkill}

22:50:41.670 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env max_wait_for_decision: infinity

22:50:41.670 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env schema_location: opt_disc

22:50:41.670 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env core_dir: false

22:50:41.670 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env pid_sort_order: false

22:50:41.670 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env no_table_loaders: 2

22:50:41.670 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env dc_dump_limit: 4

22:50:41.670 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env send_compressed: 0

22:50:41.671 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env send_max_packets: 20

22:50:41.671 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.3498.0>
22:50:41.671 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env send_max_transfer_size: 7500

22:50:41.671 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env async_dirty_buffer_size: 524288

22:50:41.671 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env async_dirty_max_buffer_file_size: 100000000

22:50:41.672 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env async_dirty_tx_backlog_threshold: 200000

22:50:41.672 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env async_dirty_buffer_min_runtime: 10000

22:50:41.672 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env async_dirty_buffer_drained_cutoff: 5

22:50:41.673 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Mnesia2 debug level set to debug
22:50:41.673 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_subscr starting: <0.3495.0>

22:50:41.673 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_locker starting: <0.3496.0>

22:50:41.673 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_recover starting: <0.3497.0>

22:50:43.698 [warning] lager_error_logger_h dropped 14 messages in the last second that exceeded the limit of 50 messages/sec
22:50:43.698 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_monitor starting: <0.3547.0>

22:50:43.699 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Version: "1.0.0"

22:50:43.699 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env access_module: mnesia2

22:50:43.700 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env auto_repair: true

22:50:43.700 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.3551.0>
22:50:43.700 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env backup_module: mnesia2_backup

22:50:43.700 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env debug: trace

22:50:43.701 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16.2016-04-10_22.49.57/Mnesia2.test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16"

22:50:43.701 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env dump_disc_copies_at_startup: true

22:50:45.725 [warning] lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
22:50:45.725 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): mnesia2_monitor starting: <0.3597.0>

22:50:45.726 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Version: "1.0.0"

22:50:45.726 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env access_module: mnesia2

22:50:45.726 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env auto_repair: true

22:50:45.726 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env backup_module: mnesia2_backup

22:50:45.727 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.3601.0>
22:50:45.727 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env debug: debug

22:50:45.727 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16.2016-04-10_22.49.57/Mnesia2.test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16"

22:50:45.728 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env dump_disc_copies_at_startup: true

22:50:45.728 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env dump_log_load_regulation: false

22:50:45.728 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env dump_log_time_threshold: 180000

22:50:45.728 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env dump_log_update_in_place: true

22:50:45.729 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env dump_log_write_threshold: 1000

22:50:45.729 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env event_module: mnesia2_event

22:50:45.729 [info] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): Env extra_db_nodes: []

22:50:47.753 [warning] lager_error_logger_h dropped 13 messages in the last second that exceeded the limit of 50 messages/sec
22:50:47.755 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.3664.0>
22:50:47.757 [info] Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:50:47.758 [error] CRASH REPORT Process <0.3655.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:50:47.758 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:50:48.796
ending test case: debug


----------------------------------------------------
2016-04-10 22:50:48.822
starting test case: dir

22:50:49.851 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.3728.0>
22:50:49.853 [info] Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:50:49.854 [error] CRASH REPORT Process <0.3719.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:50:49.854 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:50:50.888
ending test case: dir


----------------------------------------------------
2016-04-10 22:50:50.914
starting test case: dump_log_load_regulation

22:50:50.941 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.3799.0>
22:50:50.943 [info] Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:50:50.949 [info] Application mnesia2 exited with reason: stopped
22:50:50.957 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.3860.0>
22:50:54.311 [error] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

22:50:54.674 [error] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

22:50:55.043 [error] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

22:50:59.270 [error] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

22:51:03.317 [error] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

22:51:03.674 [error] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

22:51:04.050 [error] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

22:51:04.415 [error] Mnesia2('test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

22:51:06.004 [error] CRASH REPORT Process <0.3851.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:51:06.004 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:51:07.026
ending test case: dump_log_load_regulation


----------------------------------------------------
2016-04-10 22:51:07.078
starting test case: dump_log_time_threshold

22:51:08.128 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.4415.0>
22:51:08.131 [info] Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:51:14.138 [error] CRASH REPORT Process <0.4406.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:51:14.138 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:51:15.161
ending test case: dump_log_time_threshold


----------------------------------------------------
2016-04-10 22:51:15.187
starting test case: dump_log_write_threshold

22:51:16.225 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.4515.0>
22:51:16.227 [info] Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:51:17.511 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:51:18.525
ending test case: dump_log_write_threshold


----------------------------------------------------
2016-04-10 22:51:18.577
starting test case: dump_log_update_in_place

22:51:20.079 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.4631.0>
22:51:20.082 [info] Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:51:20.086 [error] CRASH REPORT Process <0.4622.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:51:20.086 [info] Application mnesia2 exited with reason: killed
22:51:22.134 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.4698.0>
22:51:22.137 [info] Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:51:22.161 [error] CRASH REPORT Process <0.4689.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:51:22.161 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:51:23.184
ending test case: dump_log_update_in_place


----------------------------------------------------
2016-04-10 22:51:23.220
starting test case: event_module

22:51:24.273 [warning] lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
22:51:24.290 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.4790.0>
22:51:24.293 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.1792.0>
22:51:24.297 [info] Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:51:24.594 [info] Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
Got event: {mnesia2_system_event,
               {mnesia2_up,
                   'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'}}
Got event: {mnesia2_system_event,
               {mnesia2_up,
                   'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'}}
Got event: {mnesia2_system_event,
               {mnesia2_down,
                   'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'}}
22:51:25.595 [error] gen_server <0.1845.0> terminated with reason: killed
22:51:25.595 [error] CRASH REPORT Process <0.1845.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:51:25.596 [error] CRASH REPORT Process <0.1783.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:51:25.596 [info] Application mnesia2 exited with reason: killed
22:51:27.639 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.1861.0>
Got event: {mnesia2_system_event,
               {mnesia2_up,
                   'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'}}
22:51:27.659 [info] Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
Got event: {mnesia2_system_event,
               {mnesia2_up,
                   'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'}}
Got event: {mnesia2_system_event,
               {mnesia2_down,
                   'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'}}
22:51:28.661 [error] gen_server <0.4854.0> terminated with reason: killed
22:51:28.661 [error] CRASH REPORT Process <0.4854.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:51:28.662 [error] CRASH REPORT Process <0.4781.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:51:28.662 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:51:29.684
ending test case: event_module


----------------------------------------------------
2016-04-10 22:51:29.711
starting test case: inconsistent_database

22:51:29.712 [error] Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.1874.0> exit with reason killed in context child_terminated
22:51:29.712 [error] Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.1874.0> exit with reason reached_max_restart_intensity in context shutdown
22:51:29.713 [error] CRASH REPORT Process <0.1852.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:51:29.713 [info] Application mnesia2 exited with reason: killed
22:51:30.805 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.4897.0>
22:51:30.807 [info] Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:51:30.840 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.1942.0>
22:51:30.843 [info] Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:51:30.845 [error] gen_server <0.4951.0> terminated with reason: killed
22:51:30.845 [error] CRASH REPORT Process <0.1933.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:51:30.845 [info] Application mnesia2 exited with reason: killed
22:51:30.845 [error] CRASH REPORT Process <0.4951.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:51:30.846 [error] CRASH REPORT Process <0.4888.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:51:30.846 [info] Application mnesia2 exited with reason: killed
22:51:30.889 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.4977.0>
22:51:34.762 [info] Application mnesia2 exited with reason: stopped
22:51:34.818 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.2012.0>
22:51:34.819 [info] Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:51:34.827 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.5101.0>
22:51:34.831 [info] Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:51:46.200 [info] Application mnesia2 exited with reason: stopped
22:51:46.222 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:51:47.249
ending test case: inconsistent_database


----------------------------------------------------
2016-04-10 22:51:47.275
starting test case: max_wait_for_decision


----------------------------------------------------
2016-04-10 22:51:47.276
ending test case: max_wait_for_decision


----------------------------------------------------
2016-04-10 22:51:47.302
starting test case: send_compressed

22:51:47.346 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.5232.0>
22:51:47.349 [info] Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:51:47.364 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.2134.0>
22:51:47.368 [info] Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:51:47.945 [error] CRASH REPORT Process <0.2125.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:51:47.945 [info] Application mnesia2 exited with reason: killed
22:51:47.979 [error] CRASH REPORT Process <0.5223.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:51:47.979 [info] Application mnesia2 exited with reason: killed
22:51:48.030 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.5320.0>
22:51:48.032 [info] Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:51:48.245 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.2222.0>
22:51:48.249 [info] Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:51:48.637 [error] gen_server <0.5391.0> terminated with reason: killed
22:51:48.637 [error] CRASH REPORT Process <0.5391.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:51:48.638 [error] CRASH REPORT Process <0.5311.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:51:48.638 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:51:49.660
ending test case: send_compressed


----------------------------------------------------
2016-04-10 22:51:49.687
starting test case: app_test


----------------------------------------------------
2016-04-10 22:51:49.853
ending test case: app_test


----------------------------------------------------
2016-04-10 22:51:49.906
starting test case: start_one_disc_full_then_one_disc_less

22:51:49.908 [error] Supervisor mnesia2_kernel_sup had child mnesia2_controller started with mnesia2_controller:start() at <0.2243.0> exit with reason killed in context child_terminated
22:51:49.908 [error] Supervisor mnesia2_kernel_sup had child mnesia2_controller started with mnesia2_controller:start() at <0.2243.0> exit with reason reached_max_restart_intensity in context shutdown
22:51:49.908 [error] CRASH REPORT Process <0.2213.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:51:49.908 [info] Application mnesia2 exited with reason: killed
22:51:50.973 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.5443.0>
22:51:50.975 [info] Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:51:50.981 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.2325.0>
22:51:50.986 [info] Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:51:50.997 [error] CRASH REPORT Process <0.5434.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:51:50.997 [info] Application mnesia2 exited with reason: killed
22:51:50.997 [error] CRASH REPORT Process <0.2316.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:51:50.997 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:51:52.020
ending test case: start_one_disc_full_then_one_disc_less


----------------------------------------------------
2016-04-10 22:51:52.047
starting test case: start_first_one_disc_less_then_one_disc_full

22:51:53.088 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.5554.0>
22:51:53.090 [info] Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:51:53.094 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.2400.0>
22:51:53.114 [info] Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:51:53.116 [error] gen_server <0.2412.0> terminated with reason: killed
22:51:53.117 [error] gen_server <0.5616.0> terminated with reason: killed
22:51:53.117 [error] CRASH REPORT Process <0.5616.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:51:53.116 [error] CRASH REPORT Process <0.2412.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:51:53.117 [error] CRASH REPORT Process <0.5545.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:51:53.117 [info] Application mnesia2 exited with reason: killed
22:51:53.116 [error] CRASH REPORT Process <0.2391.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:51:53.116 [info] Application mnesia2 exited with reason: killed
22:51:55.140 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.2459.0>
22:51:55.142 [info] Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:51:55.163 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.5634.0>
22:51:55.172 [info] Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:51:55.185 [error] CRASH REPORT Process <0.5625.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:51:55.186 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:51:56.208
ending test case: start_first_one_disc_less_then_one_disc_full


----------------------------------------------------
2016-04-10 22:51:56.235
starting test case: start_first_one_disc_less_then_two_more_disc_less

22:51:56.563 [error] CRASH REPORT Process <0.2450.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:51:56.563 [info] Application mnesia2 exited with reason: killed
22:51:57.668 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.5759.0>
22:51:57.670 [info] Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:51:57.673 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.2546.0>
22:51:57.677 [info] Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:51:57.885 [info] Application lager started on node 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:51:57.886 [info] Application poolgirl started on node 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:51:57.910 [info] starting mnesia2_tm, 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.100.0>
22:51:57.927 [info] Application mnesia2 started on node 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:51:57.970 [error] CRASH REPORT Process <0.5750.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:51:57.970 [info] Application mnesia2 exited with reason: killed
22:51:57.968 [error] gen_server <0.2559.0> terminated with reason: killed
22:51:57.968 [error] CRASH REPORT Process <0.2559.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:51:57.968 [error] gen_server <0.2597.0> terminated with reason: killed
22:51:57.968 [error] CRASH REPORT Process <0.2597.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:51:57.969 [error] CRASH REPORT Process <0.2537.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:51:57.969 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:51:58.999
ending test case: start_first_one_disc_less_then_two_more_disc_less


----------------------------------------------------
2016-04-10 22:51:59.027
starting test case: schema_location_and_extra_db_nodes_combinations

22:52:00.085 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.5855.0>
22:52:00.087 [info] Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:52:00.092 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.2628.0>
22:52:00.097 [info] Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:52:00.100 [error] CRASH REPORT Process <0.2619.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:52:00.100 [error] gen_server <0.5917.0> terminated with reason: killed
22:52:00.101 [info] Application mnesia2 exited with reason: killed
22:52:00.100 [error] CRASH REPORT Process <0.5917.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:52:00.100 [error] CRASH REPORT Process <0.5846.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:52:00.100 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:52:01.124
ending test case: schema_location_and_extra_db_nodes_combinations


----------------------------------------------------
2016-04-10 22:52:01.151
starting test case: table_load_to_disc_less_nodes

22:52:02.201 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.5949.0>
22:52:02.203 [info] Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:52:02.206 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.2698.0>
22:52:02.210 [info] Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:52:02.213 [error] gen_server <0.2710.0> terminated with reason: killed
22:52:02.215 [error] gen_server <0.5993.0> terminated with reason: killed
22:52:02.214 [error] CRASH REPORT Process <0.2710.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:52:02.215 [error] CRASH REPORT Process <0.5993.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:52:02.226 [error] CRASH REPORT Process <0.5940.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:52:02.226 [info] Application mnesia2 exited with reason: killed
22:52:02.214 [error] CRASH REPORT Process <0.2689.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:52:02.214 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:52:03.239
ending test case: table_load_to_disc_less_nodes


----------------------------------------------------
2016-04-10 22:52:03.265
starting test case: schema_merge

22:52:04.336 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.6035.0>
22:52:04.339 [info] Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:52:04.342 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.2773.0>
22:52:04.348 [info] Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:52:04.350 [error] gen_server <0.2825.0> terminated with reason: killed
22:52:04.350 [error] CRASH REPORT Process <0.2825.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:52:04.350 [error] CRASH REPORT Process <0.2764.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:52:04.350 [info] Application mnesia2 exited with reason: killed
22:52:05.396 [error] Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.6047.0> exit with reason killed in context child_terminated
22:52:05.396 [error] Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.6047.0> exit with reason reached_max_restart_intensity in context shutdown
22:52:05.397 [error] CRASH REPORT Process <0.6026.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:52:05.397 [info] Application mnesia2 exited with reason: killed
22:52:07.463 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.2843.0>
22:52:07.465 [info] Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:52:12.480 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.6113.0>
22:52:12.489 [info] Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:52:12.498 [error] gen_server <0.6150.0> terminated with reason: killed
22:52:12.496 [error] CRASH REPORT Process <0.2834.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:52:12.496 [info] Application mnesia2 exited with reason: killed
22:52:12.498 [error] CRASH REPORT Process <0.6150.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:52:12.498 [error] CRASH REPORT Process <0.6104.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:52:12.498 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:52:13.519
ending test case: schema_merge


----------------------------------------------------
2016-04-10 22:52:13.572
starting test case: dynamic_basic

22:52:13.619 [warning] lager_error_logger_h dropped 9 messages in the last second that exceeded the limit of 50 messages/sec
22:52:13.674 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.6223.0>
22:52:13.674 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.2942.0>
22:52:13.692 [info] Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:52:13.702 [info] Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:52:13.706 [info] starting mnesia2_tm, 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.191.0>
22:52:13.711 [info] Application mnesia2 started on node 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:52:13.779 [error] gen_server <0.3006.0> terminated with reason: killed
22:52:13.779 [error] CRASH REPORT Process <0.3006.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:52:13.779 [error] gen_server <0.2997.0> terminated with reason: killed
22:52:13.779 [error] CRASH REPORT Process <0.2997.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:52:13.779 [error] CRASH REPORT Process <0.2933.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:52:13.779 [info] Application mnesia2 exited with reason: killed
22:52:13.806 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.3034.0>
22:52:13.843 [error] gen_server <0.6310.0> terminated with reason: killed
22:52:13.843 [error] CRASH REPORT Process <0.6310.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:52:13.843 [error] gen_server <0.6326.0> terminated with reason: killed
22:52:13.843 [error] CRASH REPORT Process <0.6326.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:52:13.843 [error] gen_server <0.6287.0> terminated with reason: killed
22:52:13.843 [error] CRASH REPORT Process <0.6287.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:52:13.844 [error] CRASH REPORT Process <0.6214.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:52:13.844 [info] Application mnesia2 exited with reason: killed
22:52:13.864 [error] gen_server <0.274.0> terminated with reason: killed
22:52:13.864 [error] CRASH REPORT Process <0.274.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:52:13.921 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.3129.0>
22:52:13.951 [info] starting mnesia2_tm, 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.295.0>
22:52:13.954 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.6345.0>
22:52:14.254 [warning] lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
22:52:14.255 [info] Application mnesia2 started on node 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:52:14.761 [error] gen_server <0.367.0> terminated with reason: killed
22:52:14.761 [error] CRASH REPORT Process <0.367.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:52:14.761 [error] gen_server <0.360.0> terminated with reason: killed
22:52:14.761 [error] CRASH REPORT Process <0.360.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:52:14.762 [error] CRASH REPORT Process <0.286.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:52:14.762 [info] Application mnesia2 exited with reason: killed
22:52:14.791 [info] starting mnesia2_tm, 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.394.0>
22:52:17.414 [warning] lager_error_logger_h dropped 12 messages in the last second that exceeded the limit of 50 messages/sec
22:52:17.439 [warning] lager_error_logger_h dropped 12 messages in the last second that exceeded the limit of 50 messages/sec
22:52:17.414 [error] CRASH REPORT Process <0.6336.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:52:17.415 [info] Application mnesia2 exited with reason: killed
22:52:17.439 [error] gen_server <0.3221.0> terminated with reason: killed
22:52:17.439 [error] CRASH REPORT Process <0.3221.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:52:17.440 [error] CRASH REPORT Process <0.3120.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:52:17.440 [info] Application mnesia2 exited with reason: killed
22:52:17.464 [info] Application mnesia2 exited with reason: stopped
22:52:17.504 [info] starting mnesia2_tm, 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.500.0>
22:52:17.506 [info] Application mnesia2 started on node 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:52:17.524 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.6462.0>
22:52:17.530 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.3242.0>
22:52:17.536 [info] Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:52:17.830 [info] Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:52:18.155 [error] gen_server <0.574.0> terminated with reason: killed
22:52:18.155 [error] CRASH REPORT Process <0.574.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:52:18.155 [error] gen_server <0.568.0> terminated with reason: killed
22:52:18.155 [error] CRASH REPORT Process <0.568.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:52:18.156 [error] CRASH REPORT Process <0.491.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:52:18.156 [info] Application mnesia2 exited with reason: killed
22:52:18.181 [info] starting mnesia2_tm, 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.599.0>
22:52:18.182 [info] Application mnesia2 started on node 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:52:18.520 [info] Application mnesia2 exited with reason: stopped
22:52:18.228 [error] gen_server <0.6556.0> terminated with reason: killed
22:52:18.250 [error] gen_server <0.3329.0> terminated with reason: killed
22:52:18.228 [error] CRASH REPORT Process <0.6556.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:52:18.250 [error] CRASH REPORT Process <0.3329.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:52:18.228 [error] gen_server <0.6532.0> terminated with reason: killed
22:52:18.250 [error] gen_server <0.3311.0> terminated with reason: killed
22:52:18.250 [error] CRASH REPORT Process <0.3311.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:52:18.228 [error] CRASH REPORT Process <0.6532.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:52:18.250 [error] CRASH REPORT Process <0.3233.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:52:18.228 [error] gen_server <0.6551.0> terminated with reason: killed
22:52:18.251 [info] Application mnesia2 exited with reason: killed
22:52:18.228 [error] CRASH REPORT Process <0.6551.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:52:18.229 [error] CRASH REPORT Process <0.6453.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:52:18.229 [info] Application mnesia2 exited with reason: killed
22:52:18.562 [info] starting mnesia2_tm, 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.700.0>
22:52:18.653 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.6575.0>
22:52:18.655 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.3350.0>
22:52:18.670 [info] Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:52:18.959 [info] Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:52:19.005 [error] gen_server <0.3420.0> terminated with reason: killed
22:52:19.005 [error] CRASH REPORT Process <0.3420.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:52:19.006 [error] gen_server <0.3411.0> terminated with reason: killed
22:52:19.006 [error] CRASH REPORT Process <0.3411.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:52:19.006 [error] CRASH REPORT Process <0.3341.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:52:19.006 [info] Application mnesia2 exited with reason: killed
22:52:19.046 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.3446.0>
22:52:19.085 [info] Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:52:19.099 [error] gen_server <0.3504.0> terminated with reason: killed
22:52:19.099 [error] CRASH REPORT Process <0.3504.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:52:20.120 [warning] lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
22:52:20.122 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.3524.0>
22:52:20.131 [info] Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'

----------------------------------------------------
2016-04-10 22:52:20.145
ending test case: dynamic_basic


----------------------------------------------------
2016-04-10 22:52:20.183
starting test case: dynamic_ext

22:52:20.188 [warning] lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
22:52:20.186 [error] gen_server <0.6688.0> terminated with reason: killed
22:52:20.189 [error] gen_server <0.3572.0> terminated with reason: killed
22:52:20.189 [error] gen_server <0.814.0> terminated with reason: killed
22:52:20.189 [error] CRASH REPORT Process <0.3572.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:52:20.186 [error] CRASH REPORT Process <0.6688.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:52:20.189 [error] CRASH REPORT Process <0.814.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:52:20.186 [error] gen_server <0.6641.0> terminated with reason: killed
22:52:20.189 [error] gen_server <0.3567.0> terminated with reason: killed
22:52:20.189 [error] gen_server <0.774.0> terminated with reason: killed
22:52:20.186 [error] CRASH REPORT Process <0.6641.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:52:20.189 [error] CRASH REPORT Process <0.3567.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:52:20.189 [error] CRASH REPORT Process <0.774.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:52:20.189 [error] gen_server <0.823.0> terminated with reason: killed
22:52:20.187 [error] CRASH REPORT Process <0.6566.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:52:20.187 [info] Application mnesia2 exited with reason: killed
22:52:20.189 [error] CRASH REPORT Process <0.3515.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:52:20.189 [info] Application mnesia2 exited with reason: killed
22:52:20.325 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.3602.0>
22:52:20.189 [error] CRASH REPORT Process <0.823.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:52:20.189 [error] CRASH REPORT Process <0.691.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:52:20.189 [info] Application mnesia2 exited with reason: killed
22:52:20.328 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.6721.0>
22:52:20.332 [info] Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:52:20.404 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.3699.0>
22:52:20.470 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.3789.0>
22:52:20.524 [info] Application mnesia2 exited with reason: stopped
22:52:20.526 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.3889.0>
22:52:21.055 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.6832.0>
22:52:21.070 [info] Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:52:21.096 [info] Application mnesia2 exited with reason: stopped
22:52:21.097 [warning] lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
22:52:21.097 [error] CRASH REPORT Process <0.3880.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:52:21.097 [info] Application mnesia2 exited with reason: killed
22:52:21.136 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.6915.0>
22:52:21.641 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.3971.0>
22:52:21.667 [info] Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'

----------------------------------------------------
2016-04-10 22:52:21.689
ending test case: dynamic_ext


----------------------------------------------------
2016-04-10 22:52:21.715
starting test case: dynamic_bad

22:52:21.719 [error] gen_server <0.4021.0> terminated with reason: killed
22:52:21.719 [error] CRASH REPORT Process <0.4021.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:52:21.719 [error] CRASH REPORT Process <0.3962.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:52:21.720 [info] Application mnesia2 exited with reason: killed
22:52:21.783 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.7016.0>
22:52:21.784 [info] starting mnesia2_tm, 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.851.0>
22:52:21.812 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.4063.0>
22:52:22.086 [warning] lager_error_logger_h dropped 7 messages in the last second that exceeded the limit of 50 messages/sec
22:52:22.088 [info] Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:52:22.115 [info] Application mnesia2 started on node 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:52:22.180 [error] CRASH REPORT Process <0.4054.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:52:22.181 [info] Application mnesia2 exited with reason: killed
22:52:22.181 [error] CRASH REPORT Process <0.7007.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:52:22.181 [info] Application mnesia2 exited with reason: killed
22:52:22.182 [error] gen_server <0.912.0> terminated with reason: killed
22:52:22.182 [error] gen_server <0.917.0> terminated with reason: killed
22:52:22.182 [error] CRASH REPORT Process <0.912.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:52:22.183 [error] CRASH REPORT Process <0.917.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:52:22.183 [error] CRASH REPORT Process <0.842.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:52:22.183 [info] Application mnesia2 exited with reason: killed
22:52:22.220 [info] starting mnesia2_tm, 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.958.0>
22:52:22.222 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.4154.0>
22:52:22.223 [info] Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:52:22.240 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.7128.0>
22:52:22.255 [error] gen_server <0.4208.0> terminated with reason: killed
22:52:22.255 [error] CRASH REPORT Process <0.4208.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:52:22.255 [error] gen_server <0.4198.0> terminated with reason: killed
22:52:22.255 [error] CRASH REPORT Process <0.4198.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:52:22.289 [info] starting mnesia2_tm, 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.1036.0>
22:52:22.290 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.4231.0>
22:52:22.307 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.7220.0>
22:52:32.314 [warning] lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec

----------------------------------------------------
2016-04-10 22:52:32.316
ending test case: dynamic_bad

22:52:32.314 [error] Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at undefined exit with reason killed in context start_error
22:52:32.314 [error] gen_server mnesia2_monitor terminated with reason: killed
22:52:32.314 [error] gen_server mnesia2_recover terminated with reason: killed
22:52:32.314 [error] CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:52:32.314 [error] gen_server mnesia2_snmp_sup terminated with reason: killed
22:52:32.314 [error] CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:52:32.314 [error] CRASH REPORT Process <0.7211.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}} in application_master:init/4 line 133
22:52:32.315 [info] Application mnesia2 exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}}
22:52:32.315 [error] gen_server mnesia2_subscr terminated with reason: killed
22:52:32.315 [error] CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:52:32.316 [error] CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744

----------------------------------------------------
2016-04-10 22:52:32.407
starting test case: unknown_config

22:52:32.410 [warning] lager_error_logger_h dropped 5 messages in the last second that exceeded the limit of 50 messages/sec
22:52:32.410 [error] gen_server <0.4275.0> terminated with reason: killed
22:52:32.410 [error] gen_server <0.1085.0> terminated with reason: killed
22:52:32.410 [error] CRASH REPORT Process <0.4275.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:52:32.410 [error] CRASH REPORT Process <0.1085.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:52:32.410 [error] CRASH REPORT Process <0.4222.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:52:32.410 [error] gen_server <0.1080.0> terminated with reason: killed
22:52:32.410 [info] Application mnesia2 exited with reason: killed
22:52:32.410 [error] CRASH REPORT Process <0.1080.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
22:52:32.410 [error] CRASH REPORT Process <0.1027.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
22:52:32.410 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:52:34.473
ending test case: unknown_config


----------------------------------------------------
2016-04-10 22:52:34.554
ending test group: config


----------------------------------------------------
2016-04-10 22:52:34.580
starting test group: examples


----------------------------------------------------
2016-04-10 22:52:34.661
starting test case: bup


----------------------------------------------------
2016-04-10 22:52:34.701
ending test case: bup


- - - - - - - - - - - - - - - - - - - - - - - - - -
Error detected: error
- - - - - - - - - - - - - - - - - - - - - - - - - -

Testing lrascao.mnesia2.mnesia2_extra_light_SUITE: *** FAILED *** test case 41 of 52

----------------------------------------------------
2016-04-10 22:52:34.730
starting test case: company


----------------------------------------------------
2016-04-10 22:52:34.731
ending test case: company


----------------------------------------------------
2016-04-10 22:52:34.757
starting test case: meter

22:52:34.798 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.7331.0>
22:52:34.800 [info] Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:52:38.682 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:52:38.702
ending test case: meter


----------------------------------------------------
2016-04-10 22:52:38.754
starting test case: replica_test

22:52:38.829 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.7467.0>
22:52:38.833 [info] starting mnesia2_tm, 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.1134.0>
22:52:38.834 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.4322.0>
22:52:38.857 [info] Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:52:38.858 [info] Application mnesia2 started on node 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:52:39.133 [info] Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:52:45.227 [info] Application mnesia2 exited with reason: stopped
22:52:45.229 [info] Application mnesia2 exited with reason: stopped
22:52:45.237 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:52:45.238
ending test case: replica_test


----------------------------------------------------
2016-04-10 22:52:45.277
starting test case: sticky_replica_test

22:52:45.354 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.7597.0>
22:52:45.357 [info] starting mnesia2_tm, 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.1248.0>
22:52:45.375 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.4438.0>
22:52:45.380 [info] Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:52:45.658 [info] Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:52:45.685 [info] Application mnesia2 started on node 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:52:51.778 [info] Application mnesia2 exited with reason: stopped
22:52:51.779 [info] Application mnesia2 exited with reason: stopped
22:52:51.782 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:52:51.783
ending test case: sticky_replica_test


----------------------------------------------------
2016-04-10 22:52:51.823
starting test case: dist_test

22:52:51.901 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.7728.0>
22:52:51.903 [info] Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:52:51.907 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.4551.0>
22:52:51.908 [info] starting mnesia2_tm, 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.1366.0>
22:52:51.915 [info] Application mnesia2 started on node 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:52:52.211 [info] Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:53:08.113 [info] Application mnesia2 exited with reason: stopped
22:53:08.133 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:53:08.135
ending test case: dist_test

22:53:08.135 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:53:08.164
starting test case: conflict_test

22:53:08.245 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.8866.0>
22:53:08.260 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.5677.0>
22:53:08.267 [info] starting mnesia2_tm, 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.2491.0>
22:53:08.270 [info] Application mnesia2 started on node 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:53:08.272 [info] Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:53:08.557 [info] Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:53:14.929 [info] Application mnesia2 exited with reason: stopped
22:53:14.930 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:53:14.948
ending test case: conflict_test

22:53:14.948 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:53:14.974
starting test case: frag_test

22:53:15.073 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.9006.0>
22:53:15.076 [info] Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:53:15.085 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.5804.0>
22:53:15.086 [info] starting mnesia2_tm, 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.2614.0>
22:53:15.091 [info] Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:53:15.095 [info] Application mnesia2 started on node 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:53:21.394 [info] Application mnesia2 exited with reason: stopped
22:53:21.395 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:53:21.401
ending test case: frag_test

22:53:21.400 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:53:21.427
starting test case: frag2_test

22:53:21.494 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.10486.0>
22:53:21.497 [info] starting mnesia2_tm, 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.4084.0>
22:53:21.519 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.7273.0>
22:53:21.528 [info] Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:53:21.563 [info] Application mnesia2 started on node 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:53:21.800 [info] Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:53:28.027 [info] Application mnesia2 exited with reason: stopped
22:53:28.031 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:53:28.074
ending test case: frag2_test

22:53:28.074 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:53:28.102
starting test case: remote_test

22:53:28.188 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.12279.0>
22:53:28.200 [info] starting mnesia2_tm, 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.5413.0>
22:53:28.204 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.7624.0>
22:53:28.208 [info] Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:53:28.219 [info] Application mnesia2 started on node 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:53:28.493 [info] Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:53:34.644 [info] Application mnesia2 exited with reason: stopped
22:53:34.649 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:53:34.677
ending test case: remote_test

22:53:34.677 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:53:34.704
starting test case: remote_frag2_test

22:53:34.807 [info] starting mnesia2_tm, 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.12410.0>
22:53:34.811 [info] starting mnesia2_tm, 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.7736.0>
22:53:34.811 [info] starting mnesia2_tm, 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16', <0.6209.0>
22:53:34.816 [info] Application mnesia2 started on node 'd1143875o1143865n1143867@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:53:34.819 [info] Application mnesia2 started on node 'd1143869o1143863n1143905@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:53:35.112 [info] Application mnesia2 started on node 'test3189@testing-worker-linux-docker-bd2e3344-3366-linux-16'
22:53:41.357 [info] Application mnesia2 exited with reason: stopped
22:53:41.358 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:53:41.406
ending test case: remote_frag2_test

22:53:41.406 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:53:41.512
ending test group: examples


----------------------------------------------------
2016-04-10 22:53:41.538
ending test group: extra_light


----------------------------------------------------
2016-04-10 22:53:41.579
starting test case: clean_up_suite


----------------------------------------------------
2016-04-10 22:53:41.598
ending test case: clean_up_suite

Testing lrascao.mnesia2.mnesia2_extra_light_SUITE: TEST COMPLETE, 51 ok, 1 failed of 52 test cases

Cover analysing...
Updating /home/travis/build/lrascao/mnesia2/logs/index.html... done
Updating /home/travis/build/lrascao/mnesia2/logs/all_runs.html... done

