2016-04-10 22:48:53.129 [info] <0.7.0> Application lager started on node 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:48:53.130 [info] <0.7.0> Application poolgirl started on node 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:48:53.164 [info] <0.494.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.494.0>
2016-04-10 22:48:53.191 [info] <0.562.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.562.0>
2016-04-10 22:48:53.733 [info] <0.672.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.672.0>
2016-04-10 22:48:53.995 [info] <0.7.0> Application lager started on node 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:48:53.995 [info] <0.7.0> Application poolgirl started on node 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:48:54.062 [info] <0.99.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.99.0>
2016-04-10 22:48:54.078 [info] <0.7.0> Application mnesia2 started on node 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:48:54.217 [error] <0.155.0> gen_server <0.155.0> terminated with reason: killed
2016-04-10 22:48:54.217 [error] <0.155.0> CRASH REPORT Process <0.155.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:48:54.221 [error] <0.729.0> gen_server <0.729.0> terminated with reason: killed
2016-04-10 22:48:54.217 [error] <0.90.0> CRASH REPORT Process <0.90.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:48:54.221 [error] <0.729.0> CRASH REPORT Process <0.729.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:48:54.222 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:48:54.222 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:48:54.294 [info] <0.798.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.798.0>
2016-04-10 22:48:54.601 [info] <0.7.0> Application mnesia2 started on node 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:48:54.926 [error] <0.792.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): ** ERROR ** (ignoring core) ** FATAL ** A fallback is installed and Mnesia2 must be restarted. Forcing shutdown after mnesia2_down from 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10'...

2016-04-10 22:48:54.217 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:48:54.296 [info] <0.215.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.215.0>
2016-04-10 22:48:54.991 [info] <0.369.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.369.0>
2016-04-10 22:48:54.985 [info] <0.927.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.927.0>
2016-04-10 22:48:55.003 [info] <0.7.0> Application mnesia2 started on node 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:48:55.529 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:48:55.573 [info] <0.459.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.459.0>
2016-04-10 22:48:55.527 [warning] <0.6.0> lager_error_logger_h dropped 23 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:48:55.527 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:48:55.551 [info] <0.1027.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.1027.0>
2016-04-10 22:48:55.554 [info] <0.7.0> Application mnesia2 started on node 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:48:56.303 [error] <0.1018.0> CRASH REPORT Process <0.1018.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:48:56.304 [warning] <0.6.0> lager_error_logger_h dropped 27 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:48:56.304 [error] <0.519.0> gen_server <0.519.0> terminated with reason: killed
2016-04-10 22:48:56.304 [error] <0.519.0> CRASH REPORT Process <0.519.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:48:56.305 [error] <0.450.0> CRASH REPORT Process <0.450.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:48:56.303 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:48:56.366 [info] <0.1150.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.1150.0>
2016-04-10 22:48:56.371 [info] <0.7.0> Application mnesia2 started on node 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:48:56.506 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:48:56.521 [info] <0.1262.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.1262.0>
2016-04-10 22:48:56.305 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:48:56.380 [info] <0.548.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.548.0>
2016-04-10 22:48:56.396 [info] <0.7.0> Application mnesia2 started on node 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:48:56.941 [error] <0.663.0> gen_server <0.663.0> terminated with reason: killed
2016-04-10 22:48:56.941 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:48:57.042 [info] <0.762.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.762.0>
2016-04-10 22:48:57.046 [info] <0.7.0> Application mnesia2 started on node 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:48:57.003 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:48:57.023 [info] <0.1494.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.1494.0>
2016-04-10 22:48:57.337 [info] <0.7.0> Application mnesia2 started on node 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:48:57.503 [error] <0.1485.0> CRASH REPORT Process <0.1485.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:48:57.501 [error] <0.761.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-10 22:48:57.501 [error] <0.761.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:48:57.501 [error] <0.755.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.757.0> exit with reason killed in context child_terminated
2016-04-10 22:48:57.501 [error] <0.755.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.757.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:48:57.502 [error] <0.759.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-10 22:48:57.502 [error] <0.759.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:48:57.503 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:48:57.568 [info] <0.1610.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.1610.0>
2016-04-10 22:48:57.789 [info] <0.1726.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.1726.0>
2016-04-10 22:48:57.575 [info] <0.862.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.862.0>
2016-04-10 22:48:57.802 [info] <0.963.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.963.0>
2016-04-10 22:48:58.017 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:48:58.017 [error] <0.1015.0> gen_server <0.1015.0> terminated with reason: killed
2016-04-10 22:48:58.019 [warning] <0.6.0> lager_error_logger_h dropped 29 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:48:58.019 [error] <0.1782.0> gen_server <0.1782.0> terminated with reason: killed
2016-04-10 22:48:58.017 [error] <0.1015.0> CRASH REPORT Process <0.1015.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:48:58.020 [error] <0.1782.0> CRASH REPORT Process <0.1782.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:48:58.017 [error] <0.954.0> CRASH REPORT Process <0.954.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:48:58.021 [error] <0.1717.0> CRASH REPORT Process <0.1717.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:48:58.017 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:48:58.099 [info] <0.1069.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.1069.0>
2016-04-10 22:48:58.119 [info] <0.7.0> Application mnesia2 started on node 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:48:58.295 [error] <0.1123.0> gen_server <0.1123.0> terminated with reason: killed
2016-04-10 22:48:58.021 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:48:58.084 [info] <0.1852.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.1852.0>
2016-04-10 22:48:58.088 [info] <0.7.0> Application mnesia2 started on node 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:48:58.295 [error] <0.1908.0> gen_server <0.1908.0> terminated with reason: killed
2016-04-10 22:48:58.295 [error] <0.1123.0> CRASH REPORT Process <0.1123.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:48:58.296 [error] <0.1908.0> CRASH REPORT Process <0.1908.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:48:58.385 [info] <0.1168.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.1168.0>
2016-04-10 22:48:58.350 [info] <0.1983.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.1983.0>
2016-04-10 22:48:58.606 [info] <0.2116.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.2116.0>
2016-04-10 22:48:58.940 [info] <0.2256.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.2256.0>
2016-04-10 22:48:58.612 [info] <0.1269.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.1269.0>
2016-04-10 22:48:58.929 [info] <0.1375.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.1375.0>
2016-04-10 22:48:59.232 [warning] <0.6.0> lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:48:59.233 [info] <0.7.0> Application mnesia2 started on node 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:48:59.466 [error] <0.1370.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.1389.0> exit with reason killed in context child_terminated
2016-04-10 22:48:59.469 [warning] <0.6.0> lager_error_logger_h dropped 10 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:48:59.469 [error] <0.2311.0> gen_server <0.2311.0> terminated with reason: killed
2016-04-10 22:48:59.466 [error] <0.1370.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.1389.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:48:59.469 [error] <0.2311.0> CRASH REPORT Process <0.2311.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:48:59.466 [error] <0.1430.0> gen_server <0.1430.0> terminated with reason: killed
2016-04-10 22:48:59.469 [error] <0.2247.0> CRASH REPORT Process <0.2247.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:48:59.466 [error] <0.1430.0> CRASH REPORT Process <0.1430.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:48:59.467 [error] <0.1366.0> CRASH REPORT Process <0.1366.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:48:59.467 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:48:59.585 [info] <0.1465.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.1465.0>
2016-04-10 22:48:59.469 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:48:59.586 [info] <0.2386.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.2386.0>
2016-04-10 22:48:59.592 [info] <0.7.0> Application mnesia2 started on node 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:49:00.250 [error] <0.2441.0> gen_server <0.2441.0> terminated with reason: killed
2016-04-10 22:49:00.250 [error] <0.2441.0> CRASH REPORT Process <0.2441.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:49:00.248 [warning] <0.6.0> lager_error_logger_h dropped 32 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:49:00.248 [error] <0.1522.0> gen_server <0.1522.0> terminated with reason: killed
2016-04-10 22:49:00.248 [error] <0.1522.0> CRASH REPORT Process <0.1522.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:49:00.251 [error] <0.2377.0> CRASH REPORT Process <0.2377.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:49:00.248 [error] <0.1456.0> CRASH REPORT Process <0.1456.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:49:00.252 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:49:00.301 [info] <0.2517.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.2517.0>
2016-04-10 22:49:00.304 [info] <0.7.0> Application mnesia2 started on node 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:49:00.248 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:49:00.322 [info] <0.1580.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.1580.0>
2016-04-10 22:49:00.334 [info] <0.7.0> Application mnesia2 started on node 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:49:00.500 [error] <0.1632.0> gen_server <0.1632.0> terminated with reason: killed
2016-04-10 22:49:00.501 [error] <0.2508.0> CRASH REPORT Process <0.2508.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:49:00.500 [error] <0.1632.0> CRASH REPORT Process <0.1632.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:49:00.501 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:49:00.570 [info] <0.2640.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.2640.0>
2016-04-10 22:49:01.180 [error] <0.2631.0> CRASH REPORT Process <0.2631.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:49:00.574 [info] <0.1667.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.1667.0>
2016-04-10 22:49:01.181 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:49:01.221 [info] <0.2769.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.2769.0>
2016-04-10 22:49:01.223 [info] <0.7.0> Application mnesia2 started on node 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:49:01.265 [error] <0.2760.0> CRASH REPORT Process <0.2760.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:49:01.265 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:49:01.306 [info] <0.2863.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.2863.0>
2016-04-10 22:49:02.579 [info] <0.2973.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.2973.0>
2016-04-10 22:49:02.583 [info] <0.7.0> Application mnesia2 started on node 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:49:03.868 [error] <0.2964.0> CRASH REPORT Process <0.2964.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:49:03.868 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:49:05.960 [info] <0.3079.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.3079.0>
2016-04-10 22:49:05.962 [info] <0.7.0> Application mnesia2 started on node 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:49:05.965 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:49:05.966 [info] <0.3127.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.3127.0>
2016-04-10 22:49:05.982 [info] <0.3175.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.3175.0>
2016-04-10 22:49:08.070 [info] <0.3247.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.3247.0>
2016-04-10 22:49:08.073 [info] <0.7.0> Application mnesia2 started on node 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:49:08.096 [error] <0.3238.0> CRASH REPORT Process <0.3238.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:49:08.096 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:49:10.133 [info] <0.3330.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.3330.0>
2016-04-10 22:49:10.137 [info] <0.7.0> Application mnesia2 started on node 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:49:10.142 [info] <0.3324.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Restore aborted. mnesia2_config_backup:open_read["NonExisting.FILE"] -> {enoent,error}

2016-04-10 22:49:10.143 [info] <0.3324.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Restore aborted. mnesia2_config_backup:open_read["/home/travis/build/lrascao/mnesia2/logs/ct_run.test3137@testing-worker-linux-docker-9639c711-3403-linux-10.2016-04-10_22.48.26/Mnesia2.test3137@testing-worker-linux-docker-9639c711-3403-linux-10/LATEST.LOG"] -> badarg

2016-04-10 22:49:10.145 [error] <0.3366.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}}} ({error,{already_started,<0.3406.0>}})

2016-04-10 22:49:10.145 [error] <0.3365.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}}} ({error,{already_started,<0.3406.0>}})

2016-04-10 22:49:10.145 [error] <0.3368.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_11,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_11,shutdown]}}}} ({error,{already_started,<0.3406.0>}})

2016-04-10 22:49:10.145 [error] <0.3369.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_12,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_12,shutdown]}}}} ({error,{already_started,<0.3406.0>}})

2016-04-10 22:49:10.146 [error] <0.3367.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_10,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_10,shutdown]}}}} ({error,{already_started,<0.3406.0>}})

2016-04-10 22:49:10.146 [error] <0.3374.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_15,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_15,shutdown]}}}} ({error,{already_started,<0.3406.0>}})

2016-04-10 22:49:10.146 [error] <0.3376.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_17,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_17,shutdown]}}}} ({error,{already_started,<0.3406.0>}})

2016-04-10 22:49:10.146 [error] <0.3375.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_16,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_16,shutdown]}}}} ({error,{already_started,<0.3406.0>}})

2016-04-10 22:49:12.230 [warning] <0.6.0> lager_error_logger_h dropped 13 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:49:12.231 [info] <0.3448.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): mnesia2_monitor starting: <0.3450.0>

2016-04-10 22:49:12.232 [info] <0.3448.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Mnesia2 debug level set to verbose
2016-04-10 22:49:12.233 [info] <0.3448.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): mnesia2_subscr starting: <0.3451.0>

2016-04-10 22:49:12.233 [info] <0.3448.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): mnesia2_locker starting: <0.3452.0>

2016-04-10 22:49:12.234 [info] <0.3448.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): mnesia2_recover starting: <0.3453.0>

2016-04-10 22:49:12.234 [info] <0.3454.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.3454.0>
2016-04-10 22:49:12.234 [info] <0.3448.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): mnesia2_tm starting: <0.3454.0>

2016-04-10 22:49:12.236 [info] <0.3448.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Schema initiated from: default

2016-04-10 22:49:12.237 [info] <0.3448.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): mnesia2_controller starting: <0.3457.0>

2016-04-10 22:49:14.260 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:49:14.260 [info] <0.3502.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): mnesia2_monitor starting: <0.3504.0>

2016-04-10 22:49:14.260 [info] <0.3502.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Version: "1.0.0"

2016-04-10 22:49:14.261 [info] <0.3502.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env access_module: mnesia2

2016-04-10 22:49:14.261 [info] <0.3502.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env auto_repair: true

2016-04-10 22:49:14.261 [info] <0.3502.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env backup_module: mnesia2_backup

2016-04-10 22:49:14.261 [info] <0.3502.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env debug: debug

2016-04-10 22:49:14.261 [info] <0.3502.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test3137@testing-worker-linux-docker-9639c711-3403-linux-10.2016-04-10_22.48.26/Mnesia2.test3137@testing-worker-linux-docker-9639c711-3403-linux-10"

2016-04-10 22:49:14.262 [info] <0.3502.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env dump_disc_copies_at_startup: true

2016-04-10 22:49:14.262 [info] <0.3502.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env dump_log_load_regulation: false

2016-04-10 22:49:14.262 [info] <0.3502.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env dump_log_time_threshold: 180000

2016-04-10 22:49:14.263 [info] <0.3502.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env dump_log_update_in_place: true

2016-04-10 22:49:14.263 [info] <0.3508.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.3508.0>
2016-04-10 22:49:14.263 [info] <0.3502.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env dump_log_write_threshold: 1000

2016-04-10 22:49:14.263 [info] <0.3502.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env event_module: mnesia2_event

2016-04-10 22:49:14.263 [info] <0.3502.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env extra_db_nodes: []

2016-04-10 22:49:14.264 [info] <0.3502.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env ignore_fallback_at_startup: false

2016-04-10 22:49:14.264 [info] <0.3502.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env fallback_error_function: {mnesia2,lkill}

2016-04-10 22:49:14.264 [info] <0.3502.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env max_wait_for_decision: infinity

2016-04-10 22:49:14.264 [info] <0.3502.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env schema_location: opt_disc

2016-04-10 22:49:14.265 [info] <0.3502.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env core_dir: false

2016-04-10 22:49:14.265 [info] <0.3502.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env pid_sort_order: false

2016-04-10 22:49:14.265 [info] <0.3502.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env no_table_loaders: 2

2016-04-10 22:49:14.265 [info] <0.3502.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env dc_dump_limit: 4

2016-04-10 22:49:16.289 [warning] <0.6.0> lager_error_logger_h dropped 10 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:49:16.289 [info] <0.3560.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): mnesia2_monitor starting: <0.3562.0>

2016-04-10 22:49:16.290 [info] <0.3560.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Version: "1.0.0"

2016-04-10 22:49:16.290 [info] <0.3560.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env access_module: mnesia2

2016-04-10 22:49:16.290 [info] <0.3560.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env auto_repair: true

2016-04-10 22:49:16.290 [info] <0.3560.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env backup_module: mnesia2_backup

2016-04-10 22:49:16.290 [info] <0.3560.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env debug: trace

2016-04-10 22:49:16.290 [info] <0.3560.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test3137@testing-worker-linux-docker-9639c711-3403-linux-10.2016-04-10_22.48.26/Mnesia2.test3137@testing-worker-linux-docker-9639c711-3403-linux-10"

2016-04-10 22:49:16.291 [info] <0.3560.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env dump_disc_copies_at_startup: true

2016-04-10 22:49:16.291 [info] <0.3560.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env dump_log_load_regulation: false

2016-04-10 22:49:16.291 [info] <0.3560.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env dump_log_time_threshold: 180000

2016-04-10 22:49:16.291 [info] <0.3560.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env dump_log_update_in_place: true

2016-04-10 22:49:16.291 [info] <0.3560.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env dump_log_write_threshold: 1000

2016-04-10 22:49:16.291 [info] <0.3560.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env event_module: mnesia2_event

2016-04-10 22:49:16.292 [info] <0.3560.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env extra_db_nodes: []

2016-04-10 22:49:16.292 [info] <0.3560.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env ignore_fallback_at_startup: false

2016-04-10 22:49:16.292 [info] <0.3560.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env fallback_error_function: {mnesia2,lkill}

2016-04-10 22:49:16.292 [info] <0.3560.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env max_wait_for_decision: infinity

2016-04-10 22:49:16.292 [info] <0.3560.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env schema_location: opt_disc

2016-04-10 22:49:16.292 [info] <0.3560.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env core_dir: false

2016-04-10 22:49:16.292 [info] <0.3560.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env pid_sort_order: false

2016-04-10 22:49:16.293 [info] <0.3560.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env no_table_loaders: 2

2016-04-10 22:49:16.293 [info] <0.3566.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.3566.0>
2016-04-10 22:49:16.293 [info] <0.3560.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env dc_dump_limit: 4

2016-04-10 22:49:16.293 [info] <0.3560.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env send_compressed: 0

2016-04-10 22:49:16.293 [info] <0.3560.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env send_max_packets: 20

2016-04-10 22:49:16.293 [info] <0.3560.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env send_max_transfer_size: 7500

2016-04-10 22:49:16.294 [info] <0.3560.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env async_dirty_buffer_size: 524288

2016-04-10 22:49:16.294 [info] <0.3560.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env async_dirty_max_buffer_file_size: 100000000

2016-04-10 22:49:16.294 [info] <0.3560.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env async_dirty_tx_backlog_threshold: 200000

2016-04-10 22:49:16.295 [info] <0.3560.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env async_dirty_buffer_min_runtime: 10000

2016-04-10 22:49:16.295 [info] <0.3560.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env async_dirty_buffer_drained_cutoff: 5

2016-04-10 22:49:16.295 [info] <0.3560.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Mnesia2 debug level set to trace
2016-04-10 22:49:16.295 [info] <0.3560.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): mnesia2_subscr starting: <0.3563.0>

2016-04-10 22:49:18.320 [warning] <0.6.0> lager_error_logger_h dropped 22 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:49:18.320 [info] <0.3629.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): mnesia2_monitor starting: <0.3631.0>

2016-04-10 22:49:18.321 [info] <0.3629.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Version: "1.0.0"

2016-04-10 22:49:18.321 [info] <0.3629.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env access_module: mnesia2

2016-04-10 22:49:18.322 [info] <0.3629.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env auto_repair: true

2016-04-10 22:49:18.322 [info] <0.3635.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.3635.0>
2016-04-10 22:49:18.322 [info] <0.3629.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env backup_module: mnesia2_backup

2016-04-10 22:49:18.322 [info] <0.3629.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env debug: debug

2016-04-10 22:49:18.323 [info] <0.3629.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test3137@testing-worker-linux-docker-9639c711-3403-linux-10.2016-04-10_22.48.26/Mnesia2.test3137@testing-worker-linux-docker-9639c711-3403-linux-10"

2016-04-10 22:49:18.323 [info] <0.3629.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env dump_disc_copies_at_startup: true

2016-04-10 22:49:18.324 [info] <0.3629.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): Env dump_log_load_regulation: false

2016-04-10 22:49:20.347 [warning] <0.6.0> lager_error_logger_h dropped 6 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:49:20.349 [info] <0.3692.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.3692.0>
2016-04-10 22:49:20.351 [info] <0.7.0> Application mnesia2 started on node 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:49:20.352 [error] <0.3683.0> CRASH REPORT Process <0.3683.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:49:20.352 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:49:22.448 [info] <0.3756.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.3756.0>
2016-04-10 22:49:22.450 [info] <0.7.0> Application mnesia2 started on node 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:49:22.451 [error] <0.3747.0> CRASH REPORT Process <0.3747.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:49:22.451 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:49:23.553 [info] <0.3827.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.3827.0>
2016-04-10 22:49:23.555 [info] <0.7.0> Application mnesia2 started on node 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:49:23.558 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:49:23.564 [info] <0.3888.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.3888.0>
2016-04-10 22:49:30.911 [error] <0.3882.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:49:38.062 [error] <0.3882.0> Mnesia2('test3137@testing-worker-linux-docker-9639c711-3403-linux-10'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:49:38.800 [error] <0.3879.0> CRASH REPORT Process <0.3879.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:49:38.800 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:49:40.931 [info] <0.4548.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.4548.0>
2016-04-10 22:49:40.934 [info] <0.7.0> Application mnesia2 started on node 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:49:46.940 [error] <0.4543.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.4559.0> exit with reason killed in context child_terminated
2016-04-10 22:49:46.941 [error] <0.4543.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.4559.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:49:46.941 [error] <0.4539.0> CRASH REPORT Process <0.4539.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:49:46.942 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:49:49.044 [info] <0.4648.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.4648.0>
2016-04-10 22:49:49.046 [info] <0.7.0> Application mnesia2 started on node 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:49:50.064 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:49:52.180 [info] <0.4764.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.4764.0>
2016-04-10 22:49:52.182 [info] <0.7.0> Application mnesia2 started on node 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:49:52.191 [error] <0.4755.0> CRASH REPORT Process <0.4755.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:49:52.191 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:49:54.242 [info] <0.4831.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.4831.0>
2016-04-10 22:49:54.245 [info] <0.7.0> Application mnesia2 started on node 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:49:54.271 [error] <0.4822.0> CRASH REPORT Process <0.4822.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:49:54.271 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:49:56.382 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:49:56.409 [info] <0.1795.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.1795.0>
2016-04-10 22:49:56.413 [info] <0.7.0> Application mnesia2 started on node 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:49:56.390 [info] <0.4923.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.4923.0>
2016-04-10 22:49:56.392 [info] <0.7.0> Application mnesia2 started on node 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:49:57.414 [error] <0.1847.0> gen_server <0.1847.0> terminated with reason: killed
2016-04-10 22:49:57.414 [error] <0.1847.0> CRASH REPORT Process <0.1847.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:49:57.415 [error] <0.1786.0> CRASH REPORT Process <0.1786.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:49:57.415 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:49:59.495 [info] <0.1863.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.1863.0>
2016-04-10 22:49:59.498 [info] <0.7.0> Application mnesia2 started on node 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:50:00.500 [error] <0.4986.0> gen_server <0.4986.0> terminated with reason: killed
2016-04-10 22:50:00.500 [error] <0.4986.0> CRASH REPORT Process <0.4986.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:50:00.500 [error] <0.4914.0> CRASH REPORT Process <0.4914.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:00.500 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:01.553 [error] <0.1854.0> CRASH REPORT Process <0.1854.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:01.553 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:02.649 [info] <0.5029.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.5029.0>
2016-04-10 22:50:02.651 [info] <0.7.0> Application mnesia2 started on node 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:50:02.688 [error] <0.5022.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.5024.0> exit with reason killed in context child_terminated
2016-04-10 22:50:02.673 [info] <0.1945.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.1945.0>
2016-04-10 22:50:02.687 [info] <0.7.0> Application mnesia2 started on node 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:50:02.688 [error] <0.1935.0> CRASH REPORT Process <0.1935.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:02.688 [error] <0.5022.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.5024.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:50:02.688 [error] <0.5025.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-10 22:50:02.689 [info] <0.7.0> Application mnesia2 exited with reason: shutdown
2016-04-10 22:50:02.734 [info] <0.5104.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.5104.0>
2016-04-10 22:50:02.688 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:06.892 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:50:06.957 [info] <0.5228.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.5228.0>
2016-04-10 22:50:06.962 [info] <0.7.0> Application mnesia2 started on node 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:50:06.948 [info] <0.2015.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.2015.0>
2016-04-10 22:50:06.949 [info] <0.7.0> Application mnesia2 started on node 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:50:16.226 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:50:16.243 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:50:17.410 [info] <0.2138.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.2138.0>
2016-04-10 22:50:17.419 [info] <0.7.0> Application mnesia2 started on node 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:50:17.435 [error] <0.2189.0> gen_server <0.2189.0> terminated with reason: killed
2016-04-10 22:50:17.435 [error] <0.2189.0> CRASH REPORT Process <0.2189.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:50:17.436 [error] <0.2128.0> CRASH REPORT Process <0.2128.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:17.391 [info] <0.5359.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.5359.0>
2016-04-10 22:50:17.394 [info] <0.7.0> Application mnesia2 started on node 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:50:17.457 [error] <0.5350.0> CRASH REPORT Process <0.5350.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:17.457 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:17.499 [info] <0.5447.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.5447.0>
2016-04-10 22:50:18.063 [warning] <0.6.0> lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:50:18.063 [error] <0.5438.0> CRASH REPORT Process <0.5438.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:18.063 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:17.436 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:17.709 [info] <0.2225.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.2225.0>
2016-04-10 22:50:19.185 [error] <0.2216.0> CRASH REPORT Process <0.2216.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:19.185 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:20.243 [info] <0.2328.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.2328.0>
2016-04-10 22:50:20.264 [info] <0.7.0> Application mnesia2 started on node 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:50:20.273 [error] <0.2369.0> gen_server <0.2369.0> terminated with reason: killed
2016-04-10 22:50:20.236 [info] <0.5570.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.5570.0>
2016-04-10 22:50:20.238 [info] <0.7.0> Application mnesia2 started on node 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:50:20.274 [error] <0.5632.0> gen_server <0.5632.0> terminated with reason: killed
2016-04-10 22:50:20.273 [error] <0.2369.0> CRASH REPORT Process <0.2369.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:50:20.274 [error] <0.5632.0> CRASH REPORT Process <0.5632.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:50:20.274 [error] <0.2319.0> CRASH REPORT Process <0.2319.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:20.274 [error] <0.5561.0> CRASH REPORT Process <0.5561.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:20.275 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:20.274 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:22.402 [info] <0.2403.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.2403.0>
2016-04-10 22:50:22.410 [info] <0.7.0> Application mnesia2 started on node 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:50:22.424 [error] <0.2394.0> CRASH REPORT Process <0.2394.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:22.394 [info] <0.5681.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.5681.0>
2016-04-10 22:50:22.396 [info] <0.7.0> Application mnesia2 started on node 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:50:22.424 [error] <0.5745.0> gen_server <0.5745.0> terminated with reason: killed
2016-04-10 22:50:22.424 [error] <0.5745.0> CRASH REPORT Process <0.5745.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:50:22.425 [error] <0.5672.0> CRASH REPORT Process <0.5672.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:22.425 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:22.424 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:24.489 [info] <0.5761.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.5761.0>
2016-04-10 22:50:24.496 [info] <0.7.0> Application mnesia2 started on node 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:50:24.786 [error] <0.5824.0> gen_server <0.5824.0> terminated with reason: killed
2016-04-10 22:50:24.786 [error] <0.5824.0> CRASH REPORT Process <0.5824.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:50:24.786 [error] <0.5752.0> CRASH REPORT Process <0.5752.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:24.455 [info] <0.2463.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.2463.0>
2016-04-10 22:50:24.759 [info] <0.7.0> Application mnesia2 started on node 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:50:24.786 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:26.220 [error] <0.2453.0> CRASH REPORT Process <0.2453.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:26.220 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:27.289 [info] <0.5888.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.5888.0>
2016-04-10 22:50:27.291 [info] <0.7.0> Application mnesia2 started on node 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:50:27.605 [error] <0.5941.0> gen_server <0.5941.0> terminated with reason: killed
2016-04-10 22:50:27.308 [info] <0.2551.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.2551.0>
2016-04-10 22:50:27.312 [info] <0.7.0> Application mnesia2 started on node 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:50:27.605 [error] <0.2575.0> gen_server <0.2575.0> terminated with reason: killed
2016-04-10 22:50:27.605 [error] <0.2575.0> CRASH REPORT Process <0.2575.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:50:27.605 [error] <0.5941.0> CRASH REPORT Process <0.5941.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:50:27.605 [error] <0.2542.0> CRASH REPORT Process <0.2542.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:27.605 [error] <0.5933.0> gen_server <0.5933.0> terminated with reason: killed
2016-04-10 22:50:27.605 [error] <0.5933.0> CRASH REPORT Process <0.5933.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:50:27.606 [error] <0.5879.0> CRASH REPORT Process <0.5879.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:27.606 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:27.605 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:27.530 [info] <0.7.0> Application lager started on node 'd867244o867184n867177@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:50:27.530 [info] <0.7.0> Application poolgirl started on node 'd867244o867184n867177@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:50:27.555 [info] <0.99.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867244o867184n867177@testing-worker-linux-docker-9639c711-3403-linux-10', <0.99.0>
2016-04-10 22:50:27.572 [info] <0.7.0> Application mnesia2 started on node 'd867244o867184n867177@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:50:29.731 [info] <0.2632.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.2632.0>
2016-04-10 22:50:29.737 [info] <0.7.0> Application mnesia2 started on node 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:50:29.738 [error] <0.2675.0> gen_server <0.2675.0> terminated with reason: killed
2016-04-10 22:50:29.724 [info] <0.5983.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.5983.0>
2016-04-10 22:50:29.726 [info] <0.7.0> Application mnesia2 started on node 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:50:29.739 [error] <0.6045.0> gen_server <0.6045.0> terminated with reason: killed
2016-04-10 22:50:29.738 [error] <0.2675.0> CRASH REPORT Process <0.2675.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:50:29.739 [error] <0.6045.0> CRASH REPORT Process <0.6045.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:50:29.738 [error] <0.2623.0> CRASH REPORT Process <0.2623.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:29.740 [error] <0.5974.0> CRASH REPORT Process <0.5974.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:29.740 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:29.739 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:31.827 [info] <0.2702.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.2702.0>
2016-04-10 22:50:31.830 [info] <0.7.0> Application mnesia2 started on node 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:50:31.856 [error] <0.2714.0> gen_server <0.2714.0> terminated with reason: killed
2016-04-10 22:50:31.822 [info] <0.6077.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.6077.0>
2016-04-10 22:50:31.824 [info] <0.7.0> Application mnesia2 started on node 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:50:31.857 [error] <0.6121.0> gen_server <0.6121.0> terminated with reason: killed
2016-04-10 22:50:31.857 [error] <0.6121.0> CRASH REPORT Process <0.6121.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:50:31.856 [error] <0.2714.0> CRASH REPORT Process <0.2714.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:50:31.858 [error] <0.6068.0> CRASH REPORT Process <0.6068.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:31.857 [error] <0.2693.0> CRASH REPORT Process <0.2693.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:31.858 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:31.857 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:33.995 [info] <0.2777.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.2777.0>
2016-04-10 22:50:34.006 [info] <0.7.0> Application mnesia2 started on node 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:50:34.009 [error] <0.2829.0> gen_server <0.2829.0> terminated with reason: killed
2016-04-10 22:50:34.009 [error] <0.2829.0> CRASH REPORT Process <0.2829.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:50:34.009 [error] <0.2768.0> CRASH REPORT Process <0.2768.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:33.972 [info] <0.6163.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.6163.0>
2016-04-10 22:50:33.974 [info] <0.7.0> Application mnesia2 started on node 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:50:34.009 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:35.037 [error] <0.6154.0> CRASH REPORT Process <0.6154.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:35.037 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:37.090 [info] <0.2847.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.2847.0>
2016-04-10 22:50:37.092 [info] <0.7.0> Application mnesia2 started on node 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:50:42.128 [info] <0.6241.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.6241.0>
2016-04-10 22:50:42.148 [info] <0.7.0> Application mnesia2 started on node 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:50:42.187 [error] <0.6303.0> gen_server <0.6303.0> terminated with reason: killed
2016-04-10 22:50:42.187 [error] <0.2916.0> gen_server <0.2916.0> terminated with reason: killed
2016-04-10 22:50:42.187 [error] <0.6303.0> CRASH REPORT Process <0.6303.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:50:42.187 [error] <0.2916.0> CRASH REPORT Process <0.2916.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:50:42.188 [error] <0.2838.0> CRASH REPORT Process <0.2838.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:42.187 [error] <0.6232.0> CRASH REPORT Process <0.6232.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:42.187 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:42.188 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:43.390 [info] <0.2946.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.2946.0>
2016-04-10 22:50:43.395 [info] <0.7.0> Application mnesia2 started on node 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:50:43.460 [error] <0.3007.0> gen_server <0.3007.0> terminated with reason: killed
2016-04-10 22:50:43.461 [error] <0.3007.0> CRASH REPORT Process <0.3007.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:50:43.461 [error] <0.2998.0> gen_server <0.2998.0> terminated with reason: killed
2016-04-10 22:50:43.461 [error] <0.2998.0> CRASH REPORT Process <0.2998.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:50:43.461 [error] <0.2937.0> CRASH REPORT Process <0.2937.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:43.359 [info] <0.6351.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.6351.0>
2016-04-10 22:50:43.364 [info] <0.7.0> Application mnesia2 started on node 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:50:43.533 [error] <0.6454.0> gen_server <0.6454.0> terminated with reason: killed
2016-04-10 22:50:43.533 [error] <0.6454.0> CRASH REPORT Process <0.6454.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:50:43.533 [error] <0.6413.0> gen_server <0.6413.0> terminated with reason: killed
2016-04-10 22:50:43.534 [error] <0.6413.0> CRASH REPORT Process <0.6413.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:50:43.534 [error] <0.6438.0> gen_server <0.6438.0> terminated with reason: killed
2016-04-10 22:50:43.534 [error] <0.6438.0> CRASH REPORT Process <0.6438.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:50:43.536 [error] <0.6342.0> CRASH REPORT Process <0.6342.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:43.321 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:50:43.417 [info] <0.189.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867244o867184n867177@testing-worker-linux-docker-9639c711-3403-linux-10', <0.189.0>
2016-04-10 22:50:43.421 [info] <0.7.0> Application mnesia2 started on node 'd867244o867184n867177@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:50:43.554 [error] <0.272.0> gen_server <0.272.0> terminated with reason: killed
2016-04-10 22:50:43.554 [error] <0.272.0> CRASH REPORT Process <0.272.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:50:43.641 [info] <0.293.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867244o867184n867177@testing-worker-linux-docker-9639c711-3403-linux-10', <0.293.0>
2016-04-10 22:50:43.536 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:43.630 [info] <0.6473.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.6473.0>
2016-04-10 22:50:43.461 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:43.488 [info] <0.3037.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.3037.0>
2016-04-10 22:50:43.607 [info] <0.3132.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.3132.0>
2016-04-10 22:50:44.461 [warning] <0.6.0> lager_error_logger_h dropped 6 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:50:44.461 [error] <0.354.0> gen_server <0.354.0> terminated with reason: killed
2016-04-10 22:50:44.462 [error] <0.354.0> CRASH REPORT Process <0.354.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:50:44.462 [error] <0.284.0> CRASH REPORT Process <0.284.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:44.462 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:44.492 [info] <0.389.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867244o867184n867177@testing-worker-linux-docker-9639c711-3403-linux-10', <0.389.0>
2016-04-10 22:50:44.493 [info] <0.7.0> Application mnesia2 started on node 'd867244o867184n867177@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:50:46.554 [warning] <0.6.0> lager_error_logger_h dropped 4 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:50:46.555 [error] <0.6571.0> gen_server <0.6571.0> terminated with reason: killed
2016-04-10 22:50:46.555 [error] <0.6571.0> CRASH REPORT Process <0.6571.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:50:46.555 [error] <0.6543.0> gen_server <0.6543.0> terminated with reason: killed
2016-04-10 22:50:46.555 [error] <0.6543.0> CRASH REPORT Process <0.6543.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:50:46.555 [error] <0.6464.0> CRASH REPORT Process <0.6464.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:46.576 [warning] <0.6.0> lager_error_logger_h dropped 60 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:50:46.576 [error] <0.3123.0> CRASH REPORT Process <0.3123.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:46.600 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:50:46.675 [info] <0.495.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867244o867184n867177@testing-worker-linux-docker-9639c711-3403-linux-10', <0.495.0>
2016-04-10 22:50:46.677 [info] <0.7.0> Application mnesia2 started on node 'd867244o867184n867177@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:50:47.537 [error] <0.562.0> gen_server <0.562.0> terminated with reason: killed
2016-04-10 22:50:47.537 [error] <0.562.0> CRASH REPORT Process <0.562.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:50:47.537 [error] <0.568.0> gen_server <0.568.0> terminated with reason: killed
2016-04-10 22:50:47.537 [error] <0.568.0> CRASH REPORT Process <0.568.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:50:46.555 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:46.705 [info] <0.6590.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.6590.0>
2016-04-10 22:50:47.010 [info] <0.7.0> Application mnesia2 started on node 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:50:47.538 [error] <0.486.0> CRASH REPORT Process <0.486.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:46.576 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:46.710 [info] <0.3246.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.3246.0>
2016-04-10 22:50:46.715 [info] <0.7.0> Application mnesia2 started on node 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:50:47.538 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:47.564 [info] <0.593.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867244o867184n867177@testing-worker-linux-docker-9639c711-3403-linux-10', <0.593.0>
2016-04-10 22:50:47.565 [info] <0.7.0> Application mnesia2 started on node 'd867244o867184n867177@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:50:47.621 [error] <0.6680.0> gen_server <0.6680.0> terminated with reason: killed
2016-04-10 22:50:47.621 [error] <0.6680.0> CRASH REPORT Process <0.6680.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:50:47.622 [error] <0.6581.0> CRASH REPORT Process <0.6581.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:47.644 [error] <0.3336.0> gen_server <0.3336.0> terminated with reason: killed
2016-04-10 22:50:47.644 [error] <0.3336.0> CRASH REPORT Process <0.3336.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:50:47.644 [error] <0.3237.0> CRASH REPORT Process <0.3237.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:47.644 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:47.729 [info] <0.3355.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.3355.0>
2016-04-10 22:50:47.733 [info] <0.7.0> Application mnesia2 started on node 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:50:48.066 [error] <0.3427.0> gen_server <0.3427.0> terminated with reason: killed
2016-04-10 22:50:48.066 [error] <0.3427.0> CRASH REPORT Process <0.3427.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:50:48.066 [error] <0.3417.0> gen_server <0.3417.0> terminated with reason: killed
2016-04-10 22:50:48.067 [error] <0.3417.0> CRASH REPORT Process <0.3417.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:50:48.067 [error] <0.3346.0> CRASH REPORT Process <0.3346.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:48.067 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:48.122 [info] <0.3451.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.3451.0>
2016-04-10 22:50:48.138 [info] <0.7.0> Application mnesia2 started on node 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:50:48.177 [error] <0.3509.0> gen_server <0.3509.0> terminated with reason: killed
2016-04-10 22:50:48.177 [error] <0.3509.0> CRASH REPORT Process <0.3509.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:50:48.177 [error] <0.3494.0> gen_server <0.3494.0> terminated with reason: killed
2016-04-10 22:50:48.177 [error] <0.3494.0> CRASH REPORT Process <0.3494.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:50:48.177 [error] <0.3499.0> gen_server <0.3499.0> terminated with reason: killed
2016-04-10 22:50:48.178 [error] <0.3499.0> CRASH REPORT Process <0.3499.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:50:47.623 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:47.727 [info] <0.6704.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.6704.0>
2016-04-10 22:50:48.032 [info] <0.7.0> Application mnesia2 started on node 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:50:47.674 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:50:47.687 [info] <0.694.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867244o867184n867177@testing-worker-linux-docker-9639c711-3403-linux-10', <0.694.0>
2016-04-10 22:50:49.214 [info] <0.3529.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.3529.0>
2016-04-10 22:50:49.223 [info] <0.7.0> Application mnesia2 started on node 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:50:49.302 [error] <0.3520.0> CRASH REPORT Process <0.3520.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:49.301 [error] <0.818.0> gen_server <0.818.0> terminated with reason: killed
2016-04-10 22:50:49.304 [error] <0.6818.0> gen_server <0.6818.0> terminated with reason: killed
2016-04-10 22:50:49.301 [error] <0.818.0> CRASH REPORT Process <0.818.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:50:49.304 [error] <0.6818.0> CRASH REPORT Process <0.6818.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:50:49.301 [error] <0.809.0> gen_server <0.809.0> terminated with reason: killed
2016-04-10 22:50:49.304 [error] <0.6771.0> gen_server <0.6771.0> terminated with reason: killed
2016-04-10 22:50:49.302 [error] <0.809.0> CRASH REPORT Process <0.809.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:50:49.304 [error] <0.6771.0> CRASH REPORT Process <0.6771.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:50:49.302 [error] <0.768.0> gen_server <0.768.0> terminated with reason: killed
2016-04-10 22:50:49.304 [error] <0.6695.0> CRASH REPORT Process <0.6695.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:49.302 [error] <0.768.0> CRASH REPORT Process <0.768.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:50:49.302 [error] <0.685.0> CRASH REPORT Process <0.685.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:49.302 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:49.367 [info] <0.3607.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.3607.0>
2016-04-10 22:50:49.748 [info] <0.3704.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.3704.0>
2016-04-10 22:50:49.852 [info] <0.3794.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.3794.0>
2016-04-10 22:50:50.247 [warning] <0.6.0> lager_error_logger_h dropped 57 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:50:50.247 [error] <0.3856.0> gen_server <0.3856.0> terminated with reason: killed
2016-04-10 22:50:50.247 [error] <0.3856.0> CRASH REPORT Process <0.3856.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:50:50.248 [error] <0.3785.0> CRASH REPORT Process <0.3785.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:49.303 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:49.305 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:49.366 [info] <0.6850.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.6850.0>
2016-04-10 22:50:49.670 [info] <0.7.0> Application mnesia2 started on node 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:50:50.283 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:50:50.248 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:50.285 [info] <0.3894.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.3894.0>
2016-04-10 22:50:50.286 [info] <0.7.0> Application mnesia2 started on node 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:50:50.860 [error] <0.3949.0> gen_server <0.3949.0> terminated with reason: killed
2016-04-10 22:50:50.860 [error] <0.3949.0> CRASH REPORT Process <0.3949.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:50:50.818 [info] <0.6963.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.6963.0>
2016-04-10 22:50:50.833 [info] <0.7.0> Application mnesia2 started on node 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:50:50.859 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:50:50.895 [info] <0.7046.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.7046.0>
2016-04-10 22:50:51.470 [error] <0.7041.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.7064.0> exit with reason killed in context child_terminated
2016-04-10 22:50:51.400 [info] <0.3976.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.3976.0>
2016-04-10 22:50:51.414 [info] <0.7.0> Application mnesia2 started on node 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:50:51.471 [error] <0.4027.0> gen_server <0.4027.0> terminated with reason: killed
2016-04-10 22:50:51.471 [error] <0.7041.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.7064.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:50:51.472 [error] <0.4027.0> CRASH REPORT Process <0.4027.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:50:51.472 [error] <0.7110.0> gen_server <0.7110.0> terminated with reason: killed
2016-04-10 22:50:51.472 [error] <0.3967.0> CRASH REPORT Process <0.3967.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:51.472 [error] <0.7110.0> CRASH REPORT Process <0.7110.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:50:51.473 [error] <0.7037.0> CRASH REPORT Process <0.7037.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:51.473 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:51.529 [info] <0.7147.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.7147.0>
2016-04-10 22:50:51.534 [info] <0.7.0> Application mnesia2 started on node 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:50:51.565 [info] <0.845.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867244o867184n867177@testing-worker-linux-docker-9639c711-3403-linux-10', <0.845.0>
2016-04-10 22:50:51.874 [info] <0.7.0> Application mnesia2 started on node 'd867244o867184n867177@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:50:51.952 [error] <0.907.0> gen_server <0.907.0> terminated with reason: killed
2016-04-10 22:50:51.952 [error] <0.907.0> CRASH REPORT Process <0.907.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:50:51.952 [error] <0.902.0> gen_server <0.902.0> terminated with reason: killed
2016-04-10 22:50:51.952 [error] <0.902.0> CRASH REPORT Process <0.902.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:50:51.954 [error] <0.836.0> CRASH REPORT Process <0.836.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:52.010 [info] <0.7259.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.7259.0>
2016-04-10 22:50:52.010 [warning] <0.6.0> lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:50:52.023 [info] <0.7.0> Application mnesia2 started on node 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:50:52.060 [error] <0.7321.0> gen_server <0.7321.0> terminated with reason: killed
2016-04-10 22:50:51.472 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:51.571 [info] <0.4068.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.4068.0>
2016-04-10 22:50:51.984 [info] <0.4159.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.4159.0>
2016-04-10 22:50:52.059 [warning] <0.6.0> lager_error_logger_h dropped 35 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:50:52.059 [error] <0.4215.0> gen_server <0.4215.0> terminated with reason: killed
2016-04-10 22:50:51.954 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:51.984 [info] <0.950.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867244o867184n867177@testing-worker-linux-docker-9639c711-3403-linux-10', <0.950.0>
2016-04-10 22:50:52.063 [error] <0.941.0> CRASH REPORT Process <0.941.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:52.060 [error] <0.7321.0> CRASH REPORT Process <0.7321.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:50:52.061 [error] <0.7250.0> CRASH REPORT Process <0.7250.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:52.059 [error] <0.4215.0> CRASH REPORT Process <0.4215.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:50:52.059 [error] <0.4203.0> gen_server <0.4203.0> terminated with reason: killed
2016-04-10 22:50:52.059 [error] <0.4203.0> CRASH REPORT Process <0.4203.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:50:52.059 [error] <0.4150.0> CRASH REPORT Process <0.4150.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:50:52.059 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:52.089 [info] <0.4238.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.4238.0>
2016-04-10 22:50:52.091 [info] <0.7.0> Application mnesia2 started on node 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:50:52.063 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:52.090 [info] <0.1027.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867244o867184n867177@testing-worker-linux-docker-9639c711-3403-linux-10', <0.1027.0>
2016-04-10 22:50:52.091 [info] <0.7.0> Application mnesia2 started on node 'd867244o867184n867177@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:50:52.061 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:50:52.123 [info] <0.7351.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.7351.0>
2016-04-10 22:51:02.130 [error] <0.7344.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at undefined exit with reason killed in context start_error
2016-04-10 22:51:02.130 [error] <0.7347.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-10 22:51:02.130 [error] <0.7348.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-10 22:51:02.130 [error] <0.7348.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:51:02.130 [error] <0.7350.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-10 22:51:02.130 [error] <0.7350.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:51:02.130 [error] <0.7370.0> gen_server mnesia2_snmp_sup terminated with reason: killed
2016-04-10 22:51:02.130 [error] <0.7370.0> CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:51:02.130 [error] <0.7342.0> CRASH REPORT Process <0.7342.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}} in application_master:init/4 line 133
2016-04-10 22:51:02.130 [info] <0.7.0> Application mnesia2 exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}}
2016-04-10 22:51:02.131 [error] <0.7347.0> CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:51:02.225 [error] <0.4282.0> gen_server <0.4282.0> terminated with reason: killed
2016-04-10 22:51:02.225 [error] <0.1071.0> gen_server <0.1071.0> terminated with reason: killed
2016-04-10 22:51:02.225 [error] <0.4282.0> CRASH REPORT Process <0.4282.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:51:02.226 [error] <0.1071.0> CRASH REPORT Process <0.1071.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:51:02.226 [error] <0.4229.0> CRASH REPORT Process <0.4229.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:51:02.226 [error] <0.1018.0> CRASH REPORT Process <0.1018.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:51:02.226 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:02.226 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:51:04.622 [info] <0.7460.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.7460.0>
2016-04-10 22:51:04.624 [info] <0.7.0> Application mnesia2 started on node 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:51:08.782 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:51:08.923 [info] <0.7596.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.7596.0>
2016-04-10 22:51:08.940 [info] <0.7.0> Application mnesia2 started on node 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:51:08.921 [info] <0.1123.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867244o867184n867177@testing-worker-linux-docker-9639c711-3403-linux-10', <0.1123.0>
2016-04-10 22:51:08.933 [info] <0.7.0> Application mnesia2 started on node 'd867244o867184n867177@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:51:08.921 [info] <0.4329.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.4329.0>
2016-04-10 22:51:09.226 [info] <0.7.0> Application mnesia2 started on node 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:51:15.322 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:51:15.489 [info] <0.1238.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867244o867184n867177@testing-worker-linux-docker-9639c711-3403-linux-10', <0.1238.0>
2016-04-10 22:51:15.501 [info] <0.7.0> Application mnesia2 started on node 'd867244o867184n867177@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:51:15.350 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:51:15.486 [info] <0.7725.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.7725.0>
2016-04-10 22:51:15.802 [info] <0.7.0> Application mnesia2 started on node 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:51:15.351 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:51:15.495 [info] <0.4446.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.4446.0>
2016-04-10 22:51:15.498 [info] <0.7.0> Application mnesia2 started on node 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:51:21.890 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:51:22.049 [info] <0.1354.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867244o867184n867177@testing-worker-linux-docker-9639c711-3403-linux-10', <0.1354.0>
2016-04-10 22:51:22.063 [info] <0.7.0> Application mnesia2 started on node 'd867244o867184n867177@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:51:21.901 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:51:22.055 [info] <0.4559.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.4559.0>
2016-04-10 22:51:22.060 [info] <0.7.0> Application mnesia2 started on node 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:51:21.901 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:51:22.038 [info] <0.7856.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.7856.0>
2016-04-10 22:51:22.354 [info] <0.7.0> Application mnesia2 started on node 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:51:38.695 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:51:38.831 [info] <0.8996.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.8996.0>
2016-04-10 22:51:39.137 [info] <0.7.0> Application mnesia2 started on node 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:51:38.685 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:51:38.836 [info] <0.2480.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867244o867184n867177@testing-worker-linux-docker-9639c711-3403-linux-10', <0.2480.0>
2016-04-10 22:51:38.850 [info] <0.7.0> Application mnesia2 started on node 'd867244o867184n867177@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:51:38.698 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:51:38.835 [info] <0.5681.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.5681.0>
2016-04-10 22:51:39.148 [info] <0.7.0> Application mnesia2 started on node 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:51:45.595 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:51:45.788 [info] <0.2604.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867244o867184n867177@testing-worker-linux-docker-9639c711-3403-linux-10', <0.2604.0>
2016-04-10 22:51:46.094 [info] <0.7.0> Application mnesia2 started on node 'd867244o867184n867177@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:51:45.601 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:51:45.780 [info] <0.9135.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.9135.0>
2016-04-10 22:51:45.784 [info] <0.7.0> Application mnesia2 started on node 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:51:45.598 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:51:45.790 [info] <0.5809.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.5809.0>
2016-04-10 22:51:45.796 [info] <0.7.0> Application mnesia2 started on node 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:51:52.489 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:51:52.608 [info] <0.4076.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867244o867184n867177@testing-worker-linux-docker-9639c711-3403-linux-10', <0.4076.0>
2016-04-10 22:51:52.676 [info] <0.7.0> Application mnesia2 started on node 'd867244o867184n867177@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:51:52.497 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:51:52.621 [info] <0.7279.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.7279.0>
2016-04-10 22:51:52.638 [info] <0.7.0> Application mnesia2 started on node 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:51:52.502 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:51:52.602 [info] <0.10615.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.10615.0>
2016-04-10 22:51:52.909 [info] <0.7.0> Application mnesia2 started on node 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:51:59.205 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:51:59.341 [info] <0.5333.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867244o867184n867177@testing-worker-linux-docker-9639c711-3403-linux-10', <0.5333.0>
2016-04-10 22:51:59.645 [info] <0.7.0> Application mnesia2 started on node 'd867244o867184n867177@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:51:59.209 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:51:59.335 [info] <0.12318.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.12318.0>
2016-04-10 22:51:59.337 [info] <0.7.0> Application mnesia2 started on node 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:51:59.212 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:51:59.352 [info] <0.7645.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.7645.0>
2016-04-10 22:51:59.367 [info] <0.7.0> Application mnesia2 started on node 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:52:05.788 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:52:05.943 [info] <0.7760.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10', <0.7760.0>
2016-04-10 22:52:05.951 [info] <0.7.0> Application mnesia2 started on node 'd867236o867192n867192@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:52:05.793 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:52:05.943 [info] <0.6128.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd867244o867184n867177@testing-worker-linux-docker-9639c711-3403-linux-10', <0.6128.0>
2016-04-10 22:52:05.957 [info] <0.7.0> Application mnesia2 started on node 'd867244o867184n867177@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:52:05.803 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:52:05.940 [info] <0.12447.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10', <0.12447.0>
2016-04-10 22:52:06.247 [info] <0.7.0> Application mnesia2 started on node 'test3137@testing-worker-linux-docker-9639c711-3403-linux-10'
2016-04-10 22:52:12.678 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:52:12.698 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:52:12.681 [info] <0.7.0> Application mnesia2 exited with reason: stopped
